### PR TITLE
Fix: Stop linebreak-style from crashing (fixes #2490)

### LINKED ISSUE #2490: linebreak-style: throws error if file is one line without line ending.
I'm experiencing the following error.

```
                lineOfError = linebreaks.indexOf(expectedLF ? "\r\n" : "\n");
                                         ^
TypeError: Cannot call method 'indexOf' of null
```

This happened with a file that was only 1 line long with no actual `LF` or `CRLF` at the end of the file.

This was due to the following line in [lib/rules/linebreak-style.js#L21](https://github.com/eslint/eslint/blob/aab38ca5c867edd980dc4f23e2e9477319430e39/lib/rules/linebreak-style.js#L21) not matching any linefeeds.

### PR DESCRIPTION
**Pull request by whitneyit**
Due to the fact that the `linebreak-style` rule always expected to find linebreaks within a file there was a possibility that the rule would throw an Error if this was not the case.

This can be causes by a file with 1 line or less being generated in a windows environment that does not insert linefeeds on the last line of the file.

### CODE REVIEW

File: lib/rules/linebreak-style.js [hunk 1]
```diff
@@ -12,20 +13,31 @@
 
 module.exports = function (context) {
     var EXPECTED_LF_MSG = "Expected linebreaks to be 'LF' but found 'CRLF'.",
-        EXPECTED_CRLF_MSG = "Expected linebreaks to be 'CRLF' but found 'LF'.";
+        EXPECTED_CRLF_MSG = "Expected linebreaks to be 'CRLF' but found 'LF'.",
+        MISSING_LF_MSG = "Expected linebreaks to be 'LF' but none were found.",
```
Comment (ilyavolodin) [inline lib/rules/linebreak-style.js]: I'm not sure this rule should be checking for existence of linebreaks. We have eol-last rules that already checks for this.

Comment (nzakas) [inline lib/rules/linebreak-style.js]: Agreed. The rule should just do nothing in this case.

**Comment by whitneyit** [comment]
Updated to remove the `MISSING_MSG`'s and checks.

**Comment by ilyavolodin** [comment]
LGTM
