### PR TITLE
fix: Clearer error message for wrong plugin format

### LINKED ISSUE #18926: Bug: [Flat config] Errors should indicate which config object contains error
[My apologies for not using the template to provide an executable MRE.   Hopefully this problem is self-evident enough that's not needed]

### Environment

```
$ npx eslint --env-info
Environment Info:

Node version: v20.16.0
npm version: v10.8.1
Local ESLint version: v9.10.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 23.5.0
```

### Problem

As mentioned in the title, if a `eslint.config.js` file exports an array of configs with more than one item, diagnosing which config object has the error can be problematic. 

### Example

**The config: eslint.config.js**
```
 // Note: Invalid plugins object structure in 3rd config object
export default [ {}, {}, {  plugins: ['react'] }, {} ]
```

**The error**
```bash
$ eslint .

Oops! Something went wrong! :(

A config object has a "plugins" key defined as an array of strings.

Flat config requires "plugins" to be an object in this form:

    {
        plugins: {
            react: pluginObject
        }
    }
```

NOTE: Log output fails to show which of the four config objects has the bad `plugins` key.  This puts the user in the position of having to guess and/or use trial and error to track down which of the four config objects is the problem.

This becomes particularly problematic as the size and complexity of the array grows.  For example, our (CodePen's) current config setup has a dozen different config objects:
```js
export default [
  js.configs.recommended,
  ...eslintTypescript.configs.recommended,
  eslintImport.flatConfigs.recommended,
  eslintJest.configs['flat/recommended'],
  eslintPromise.configs['flat/recommended'],
  eslintReact.configs.flat.recommended,
  eslintReactHooksFlat,
  eslintSonar.configs.recommended,
  eslintUnicorn.configs.recommended,

  // custom configs
  codepenIgnores,
  codepenGraphql,
  codepenRailsGraphql
];

```
### Solution (Proposed)

**Option 1: include config index in error**

At a minimum, including the index of the config object in the error message would  be helpful.  For example...
> ~~A config object~~ **Config object at index 2** has a "plugins" key defined as an array of strings.

**Option 2: support `config#name` property on config objects, and include in error**

For example, with this config...
```
export default [ 
 { name: 'oneConfig' },  
 { name: 'twoConfig' }, 
 { name: 'redConfig', plugins: ['react'] }, 
 { name: 'blueConfig' }
]
```

... the error might read:
> ~~A config object~~ **"redConfig#plugins"** key defined as an array of strings.

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Updated the error message that's displayed when eslintrc-style plugins are found in a config. Hopefully this will give more of a clue of what to look for.

It turned out to be very difficult to get more information about the location of the error in the config array because this error is thrown during validation, which happens only when `getConfig()` is called. If we want a more robust solution, we'd need to change `ConfigArray` to validate upon normalization instead of lazily validating.

fixes #18926

### CODE REVIEW

File: messages/eslintrc-plugins.js [hunk 1]
```diff
@@ -5,9 +5,14 @@ module.exports = function({ plugins }) {
     const isArrayOfStrings = typeof plugins[0] === "string";
 
     return `
-A config object has a "plugins" key defined as an array${isArrayOfStrings ? " of strings" : ""}.
+A config object has a "plugins" key defined as an array${isArrayOfStrings ? " of strings" : ""}. It
+looks something like this:
```
Comment (Tanujkanti4441) [inline messages/eslintrc-plugins.js:9]: May be we can write it like this?
```suggestion
A config object has a "plugins" key defined as an array${isArrayOfStrings ? " of strings" : ""}.
It looks something like this:
```
OR

```suggestion
A config object has a "plugins" key defined as an array${isArrayOfStrings ? " of strings" : ""}. It looks something like this:
```

File: messages/eslintrc-plugins.js [hunk 2]
```diff
@@ -5,9 +5,14 @@ module.exports = function({ plugins }) {
...
 
-Flat config requires "plugins" to be an object in this form:
+    {
+        "plugins": ${JSON.stringify(plugins)}
+    }
+
+Flat config requires "plugins" to be an object in this form, like this:
```
Comment (Tanujkanti4441) [inline messages/eslintrc-plugins.js:15]:
```suggestion
Flat config requires "plugins" to be an object, like this:
```
last part seems repetitive, how about this one?

**Review by Tanujkanti4441 — APPROVED** [review]
LGTM. Thanks!

Would like another team member to review this.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
