### PR TITLE
Update: autofix bug in lines-between-class-members (fixes #12391)

### LINKED ISSUE #12391: Disallow lines-between-class-members deletes comments and docblocks between methods
**Tell us about your environment**
Windows 10/git bash

* **ESLint Version:**
6.5.1
* **Node Version:**
v11.9.0
* **npm Version:**
6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint 9.0.0

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "parserOptions": {
    "ecmaVersion": 2016,
    "sourceType": "module"
  },
  "rules": {
    "lines-between-class-members": [2, "never"]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
class MyClass {
    myMethod1 (param) {
    }
    
    /** 
     * test comment
     */
    myMethod2 (param) {
    }
}
```

```bash
eslint MyClass.js --fix
```

**What did you expect to happen?**
Remove line 4 in MyClass.js

**What actually happened? Please include the actual, raw output from ESLint.**
Removed lines 4-7 in MyClass.js

```js
class MyClass {
    myMethod1 (param) {
    }
myMethod2 (param) {
    }
}
```
**Are you willing to submit a pull request to fix this bug?**
I suppose I'm not familiar enough with the code base to be of any help by now. I'd be willing to invest some time though.

### PR DESCRIPTION
**Pull request by yeonjuan**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

This PR will fix three bugs in `lines-between-class-members`.
 1. #12391
 2. doesn't work well with `semicolons`. 
    * the actual master version.
    ```js
    /* eslint lines-between-class-members: ["error", "always"] */

    class A {
      foo() {}
      /* comment */;
      ;  // No error, but here is no blank line.
      bar() {}
    }
    ```
    * this PR
    ```js
    /* eslint lines-between-class-members: ["error", "always"] */

    class A {
      foo() {}
      /* comment */; // Lint Error
      ; 
      bar() {}
    }
    ```

 3. incorrect fixing trailing comments
    ```js
    /* eslint lines-between-class-members: ["error", "always"] */

    class foo{ 
      bar(){} //comment
      baz(){}
    }
     ```
    * the actual master version
    ```js
    /* eslint lines-between-class-members: ["error", "always"] */

     class foo{ 
       bar(){}
      //comment
       baz(){}
     }
     ```
   
    * this PR
    ```js
    /* eslint lines-between-class-members: ["error", "always"] */

     class foo{ 
       bar(){} //comment

       baz(){}
     }
     ```

**Is there anything you'd like reviewers to focus on?**
#12391

### CODE REVIEW

**Comment by yeonjuan** [comment]
@mdjermanovic 
Yes. It still removes comments in that case. In my opinion, it's worth to merge because it covers usual cases. What about just do not fix(atofix) in those cases(blank line both before, after)?

**Comment by yeonjuan** [comment]
@mdjermanovic  
oh..Yes. this is how `padding-line-between-statements` handles comments - [demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgcGFkZGluZy1saW5lLWJldHdlZW4tc3RhdGVtZW50czogW1xuICAgIFwiZXJyb3JcIixcbiAgICB7IGJsYW5rTGluZTogXCJuZXZlclwiLCBwcmV2OiBcImZ1bmN0aW9uXCIsIG5leHQ6IFwiZnVuY3Rpb25cIiB9XG5dKi9cblxuZnVuY3Rpb24gZm9vICgpIHtcbn1cblxuLyoqXG4qL1xuXG5mdW5jdGlvbiB0ZXN0ICgpIHtcblxufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTAsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)(no fix).
I changed it. thanks! :)

**Comment by mdjermanovic** [comment]
Thank for the change! Looks like the comments are completely safe now.

There is another thing to note. In some extremely rare cases, this fix can change the behavior of this rule to report more or fewer warnings. The actual master version looks for comments before the next member (using `sourceCode.getCommentsBefore`, which returns comments after the first preceding non-comment token), while this fix searches from both sides. 

This will almost always produce the same result at the end, but a class body can also contain useless empty members (semicolons), which don't exist in AST.

An example where the actual version doesn't report warning, but the version from this PR does:

```js
/* eslint lines-between-class-members: ["error", "always"] */

class A {
  foo() {}
  /* comment */;
  bar() {}
}
```

This rule in general at the moment doesn't work well with these semicolons. I think it's okay to merge this PR as is (just mark with `Update` because it can produce more warnings) and maybe later analyze and fix handling of semicolons in a separate PR.

**Comment by yeonjuan** [comment]
@mdjermanovic 
Thanks for the elaborate review. I changed the pr message(fix -> update).

**Comment by kaicataldo** [comment]
TIL! Nice catch, @mdjermanovic :+1:

I'm personally not sure we should defer the fix until later. Would it be possible to check for semicolon tokens in addition to comments in this PR?

**Comment by yeonjuan** [comment]
@kaicataldo @mdjermanovic 

May I ask some questions?
Before I move on, I would like to double-check whether I understand correctly. :)

The actual version doesn't report an error in case1. But I assume that this is a bug. ...right?
* case1
```js
/* eslint lines-between-class-members: ["error", "always"] */

class A {
  foo() {}
  /* comment */; // No error, but here is no blank line.
  bar() {}
}
```

The PR version report an error in case1, but no error in case2.
* case2
```js
/* eslint lines-between-class-members: ["error", "always"] */

class A {
  foo() {}
  /* comment */;
  ;  // No error, but here is no blank line.
  bar() {}
}
```
So I need to add check for semicolon tokens. Do I get this right?

**Comment by mdjermanovic** [comment]
> The actual version doesn't report an error in case1. But I assume that this is a bug. ...right?

In my opinion - yes, this is a bug, It seems that the actual master version doesn't handle semicolons well. In some cases, this rule can even remove them:

```js
/* eslint lines-between-class-members: ["error", "never"] */

class A {
  foo() {}
  ;
  bar() {}
}
```

This is fixed to:

```js
/* eslint lines-between-class-members: ["error", "never"] */

class A {
  foo() {}
bar() {}
}
```

This doesn't look like something this rule should do, `no-extra-semi` removes these semicolons.

> So I need to add check for semicolon tokens. Do I get this right?

While these semicolons are technically class members (I think), this rule should probably treat them as it treats comments - don't require/disallow empty lines around semicolons, but a line with a semicolon shouldn't be seen as an empty line.

Maybe `getLastConsecutiveTokenAfter`/`getFirstConsecutiveTokenBefore` shouldn't explicitly check for comments and semicolons, but use first/last token of the following/previous class members as a stop token instead.

**Comment by yeonjuan** [comment]
@mdjermanovic @kaicataldo 
there is one more bug(in my opinion) in the actual version. - [demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGxpbmVzLWJldHdlZW4tY2xhc3MtbWVtYmVyczogW1wiZXJyb3JcIiwgXCJhbHdheXNcIl0gKi9cblxuY2xhc3MgZm9veyBcbiAgYmFyKCl7fSAvL2NvbW1lbnRcbiAgYmF6KCl7fVxufVxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMCwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6eyJqc3giOnRydWV9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)
```
/* eslint lines-between-class-members: ["error", "always"] */

class foo{ 
  bar(){} //comment
  baz(){}
}
```
This is fixed to:
```
/* eslint lines-between-class-members: ["error", "always"] */

class foo{ 
  bar(){}

  //comment
  baz(){}
}
```
I push the commit includes fixing this problem also. thanks.

File: lib/rules/lines-between-class-members.js [hunk 1]
```diff
@@ -120,20 +93,26 @@ module.exports = {
...
                     const curLast = sourceCode.getLastToken(body[i]);
                     const nextFirst = sourceCode.getFirstToken(body[i + 1]);
-                    const isPadded = isPaddingBetweenTokens(curLast, nextFirst);
                     const isMulti = !astUtils.isTokenOnSameLine(curFirst, curLast);
                     const skip = !isMulti && options[1].exceptAfterSingleLine;
-
+                    const beforePadding = findLastConsecutiveTokenAfter(curLast, nextFirst, 1);
+                    const afterPadding = findFirstConsecutiveTokenBefore(nextFirst, curLast, 1);
+                    const isPadded = afterPadding.loc.start.line - beforePadding.loc.start.line > 1;
+                    const hasPaddedComments = sourceCode.commentsExistBetween(beforePadding, afterPadding);
```
Comment (mdjermanovic) [inline lib/rules/lines-between-class-members.js]: I think we should check for any tokens between, not just comments.

For example, fix for the following code will remove the semicolon:

```js
/* eslint lines-between-class-members: ["error", "never"] */

class A {
    foo() {}

    ;

    bar() {}
}
```

File: lib/rules/lines-between-class-members.js [hunk 2]
```diff
@@ -120,20 +93,26 @@ module.exports = {
                     const curFirst = sourceCode.getFirstToken(body[i]);
                     const curLast = sourceCode.getLastToken(body[i]);
                     const nextFirst = sourceCode.getFirstToken(body[i + 1]);
-                    const isPadded = isPaddingBetweenTokens(curLast, nextFirst);
                     const isMulti = !astUtils.isTokenOnSameLine(curFirst, curLast);
                     const skip = !isMulti && options[1].exceptAfterSingleLine;
-
+                    const beforePadding = findLastConsecutiveTokenAfter(curLast, nextFirst, 1);
+                    const afterPadding = findFirstConsecutiveTokenBefore(nextFirst, curLast, 1);
+                    const isPadded = afterPadding.loc.start.line - beforePadding.loc.start.line > 1;
```
Comment (mdjermanovic) [inline lib/rules/lines-between-class-members.js]: Feels more correct to use `beforePadding.loc.end.line` here? That would also probably require to check if `afterPadding` and `beforePadding` are the same token, in order to avoid mistake with a single multiline comment between class members.

It's probably impossible to design an example where this can make a difference with the current syntax, but I think it makes more sense and is easier to understand than comparing start lines.

With the future syntax (or present with `babel-eslint`), this would be an example:

```js
class A {
  x = `multiline
  template string`
  y = 1
}
```

(to avoid confusion - there is no need to add `babel-eslint` test).

**Comment by yeonjuan** [comment]
@mdjermanovic 
thanks for the reviews. I'm all done :)

File: tests/lib/rules/lines-between-class-members.js [hunk 3]
```diff
@@ -73,6 +76,71 @@ ruleTester.run("lines-between-class-members", rule, {
...
+            output: "class foo{ bar(){}\n/* comment-1 */\n/* comment-2 */\nbaz(){}}",
+            options: ["never"],
+            errors: [neverError]
+        }, {
+            code: "class foo{ bar(){}\n\n/* comment */\n\nbaz(){}}",
+            output: null,
+            options: ["never"],
+            errors: [neverError]
+        }, {
+            code: "class foo{ bar(){}\n\n// comment */\n\nbaz(){}}",
```
Comment (mdjermanovic) [inline tests/lib/rules/lines-between-class-members.js]: I guess `*/` is extra in the `// comment */` line.

File: tests/lib/rules/lines-between-class-members.js [hunk 4]
```diff
@@ -40,6 +40,9 @@ ruleTester.run("lines-between-class-members", rule, {
         "class A{ foo() {}\n/* a */ /* b */\n\nbar() {}}",
         "class A{ foo() {}/* a */ \n\n /* b */bar() {}}",
 
+        "class A {\nfoo() {}\n/* comment */;\n;\n\nbar() {}\n}",
+        "class A {\nfoo() {}\n// comment */\n\n;\n;\nbar() {}\n}",
```
Comment (mdjermanovic) [inline tests/lib/rules/lines-between-class-members.js]: I guess `*/` is extra in the `// comment */` line.

File: tests/lib/rules/lines-between-class-members.js [hunk 5]
```diff
@@ -73,6 +76,71 @@ ruleTester.run("lines-between-class-members", rule, {
...
+            options: ["never"],
+            errors: [neverError]
+        }, {
+            code: "class foo{ bar(){}\n/* comment-1 */\n\n;\n\n/* comment-3 */\nbaz(){}}",
+            output: null,
+            options: ["never"],
+            errors: [neverError]
+        }, {
+            code: "class A {\nfoo() {}// comment */;\n;\n/* comment */\nbar() {}\n}",
+            output: "class A {\nfoo() {}// comment */;\n\n;\n/* comment */\nbar() {}\n}",
```
Comment (mdjermanovic) [inline tests/lib/rules/lines-between-class-members.js]: This was probably meant to be `/* comment */;` ?

**Comment by yeonjuan** [comment]
@mdjermanovic 
Oh.. sorry for my mistake. I fixed typo.

**Comment by kaicataldo** [comment]
Thanks for contributing!
