### PR TITLE
Update: Implement auto fix for semi-spacing rule (fixes #3829)

### LINKED ISSUE #3829: Implement auto fix functionality for semi-spacing rule
Implement auto fix functionality for semi-spacing rule

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26743689-implement-auto-fix-functionality-for-semi-spacing-rule?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

File: tests/lib/rules/semi-spacing.js [hunk 1]
```diff
@@ -61,75 +61,91 @@ ruleTester.run("semi-spacing", rule, {
...
             code: "var a = function() {\n} ;",
-            errors: [ { message: "Unexpected whitespace before semicolon.", type: "VariableDeclaration", line: 2, column: 3 } ]
+            errors: [ { message: "Unexpected whitespace before semicolon.", type: "VariableDeclaration", line: 2, column: 3 } ],
+            output: "var a = function() {\n};"
         },
         {
             code: "/^a$/.test('b') ;",
-            errors: [ { message: "Unexpected whitespace before semicolon.", type: "ExpressionStatement", line: 1, column: 17 } ]
+            errors: [ { message: "Unexpected whitespace before semicolon.", type: "ExpressionStatement", line: 1, column: 17 } ],
+            output: "/^a$/.test('b');"
```
Comment (gyandeeps) [inline tests/lib/rules/semi-spacing.js]: Please put output next to code so that its easy to see the difference.
Example: https://github.com/eslint/eslint/pull/3802/files

File: lib/rules/semi-spacing.js [hunk 2]
```diff
@@ -104,22 +104,52 @@ module.exports = function(context) {
 
             if (hasLeadingSpace(token)) {
                 if (!requireSpaceBefore) {
-                    context.report(node, location, "Unexpected whitespace before semicolon.");
+                    context.report({
```
Comment (gyandeeps) [inline lib/rules/semi-spacing.js]: can we have a central function (like report) which handles the reporting? 
So that we dont have to keep changing this at 4 spots.

Comment (alberto) [inline lib/rules/semi-spacing.js]: @gyandeeps can you point me at one example you like? Or tell me how it would be different from the current `checkSemicolonSpacing` function.

Comment (gyandeeps) [inline lib/rules/semi-spacing.js]: simple example: https://github.com/eslint/eslint/pull/3772/files
Advanced example: https://github.com/eslint/eslint/pull/3738/files

Comment (alberto) [inline lib/rules/semi-spacing.js]: See if you like it better now.

Comment (gyandeeps) [inline lib/rules/semi-spacing.js]: I am sorry but based on the current change, i think it was better off before.
Lets just leave it as you had before.

Thanks

**Comment by nzakas** [comment]
I'm not sure if we want to add this rule yet. There could be a conflict with `semi` fixes. I'd rather hold off for a bit.

@alberto I appreciate your enthusiasm, but please wait until an issue is marked as "accepted" before starting working on it.

**Comment by nzakas** [comment]
We're going to hold off on this for a while, so closing.

**Comment by alberto** [comment]
@nzakas would you reconsider this one now?

**Comment by alberto** [comment]
Reopened and resubmitted.

**Comment by nzakas** [comment]
Lgtm
