### PR TITLE
Fix: no-whitespace-before-property ignores whitespace inside brackets (fixes #5167)

### LINKED ISSUE #5167: `no-whitespace-before-property` false positive
Using eslint 2.0.0-rc.0.

Code: 

```js
var arr = [1, 2, 3]
var first = arr[ 0 ]
```

Rules:

```js
{
  "rules": {
    "no-whitespace-before-property": 2
  }
}
```

Gives the following error:

```
  2:13  error  Unexpected whitespace before property 'undefined'  no-whitespace-before-property
```

The rule shouldn't consider this to be invalid whitespace, since the whitespace occurs *within* the square brackets. Spacing within square brackets is already covered by another rule.

This should be continue to be considered an error:

```js
foo [bar]
```

But not this:

```js
foo[ bar ]
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30595222-no-whitespace-before-property-false-positive?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kaicataldo**
Rule ignores whitespace inside brackets and correctly reports property name

### CODE REVIEW

File: lib/rules/no-whitespace-before-property.js [hunk 1]
```diff
@@ -16,6 +16,42 @@ module.exports = function(context) {
...
+     * @returns {string} The name of the node.
+     * @private
+     */
+    function getPropName(token) {
+        if (token.type === "Literal") {
+            return token.value;
+        } else if (token.type === "Identifier") {
+            return token.name;
+        }
+        return false;
```
Comment (mysticatea) [inline lib/rules/no-whitespace-before-property.js]: `false` is not a string (jsdoc says return type is string).
IMO, we can use `sourceCode.getText(prop)` or a constant text such as `"computed property"` instead of this function.

Could you add tests?: `foo["on" + name]`

File: lib/rules/no-whitespace-before-property.js [hunk 2]
```diff
@@ -25,14 +61,20 @@ module.exports = function(context) {
...
+                if (punc.type !== "Punctuator") {
+                    return;
+                }
+
+                if (punc.value === ".") {
+                    if (sourceCode.isSpaceBetweenTokens(obj, prop)) {
+                        reportError(node, prop);
+                    }
+                } else if (punc.value === "[") {
+                    if (sourceCode.isSpaceBetweenTokens(obj, punc)) {
```
Comment (michaelficarra) [inline lib/rules/no-whitespace-before-property.js]: 75-77 are exactly the same as 71-73. Combine them.

File: lib/rules/no-whitespace-before-property.js [hunk 3]
```diff
@@ -25,14 +61,20 @@ module.exports = function(context) {
...
-                        node: node,
-                        message: "Unexpected whitespace before property '{{ propName }}'.",
-                        data: {
-                            propName: prop.name
-                        }
-                    });
+                var punc = sourceCode.getTokenBefore(prop);
+
+                if (punc.type !== "Punctuator") {
+                    return;
```
Comment (michaelficarra) [inline lib/rules/no-whitespace-before-property.js]: Will this ever be reached?

File: tests/lib/rules/no-whitespace-before-property.js [hunk 4]
```diff
@@ -47,16 +61,25 @@ ruleTester.run("no-whitespace-before-property", rule, {
...
+        "foo\n .bar\n [ baz ]",
         "foo\n\t.bar\n\t.baz",
         "foo.\n\tbar.\n\tbaz",
         "foo\n\t.bar()\n\t.baz()",
         "foo.\n\tbar().\n\tbaz()",
-        "foo\n\t.bar\n\t[baz]"
+        "foo\n\t.bar\n\t[baz]",
+        "foo\n\t.bar\n\t['baz']",
+        "foo\n\t.bar\n\t[0]",
+        "foo\n\t.bar\n\t[ baz ]"
```
Comment (michaelficarra) [inline tests/lib/rules/no-whitespace-before-property.js]: I'd like to see tests which include parenthesised targets and parenthesised properties with various spacing inside/outside the parentheses.

File: lib/rules/no-whitespace-before-property.js [hunk 5]
```diff
@@ -16,6 +16,42 @@ module.exports = function(context) {
...
+
+    /**
+     * Returns the name of the property.
+     * @param {Token} token - The token to check.
+     * @returns {string} The name of the node.
+     * @private
+     */
+    function getPropName(token) {
+        if (token.type === "Literal") {
+            return token.value;
```
Comment (michaelficarra) [inline lib/rules/no-whitespace-before-property.js]: This also may not be a string.

File: lib/rules/no-whitespace-before-property.js [hunk 6]
```diff
@@ -25,14 +61,20 @@ module.exports = function(context) {
...
-                            propName: prop.name
-                        }
-                    });
+                var punc = sourceCode.getTokenBefore(prop);
+
+                if (punc.type !== "Punctuator") {
+                    return;
+                }
+
+                if (punc.value === ".") {
```
Comment (michaelficarra) [inline lib/rules/no-whitespace-before-property.js]: Will `punc.value` ever be something other than these two?

Comment (mysticatea) [inline lib/rules/no-whitespace-before-property.js]: Maybe, `(`.

This rule may need some tests for parens.

```js
( a ? b : c ).foo;
a.foo[ ("name") ];
```

**Comment by kaicataldo** [comment]
Hey all, thanks for the awesome code review! I'll try to get back to this later today.

File: lib/rules/no-whitespace-before-property.js (hunk 2 above)
Comment (kaicataldo) [inline lib/rules/no-whitespace-before-property.js]: They're actually not exactly the same, though it's easy to miss! As per the accepted proposal [here](https://github.com/eslint/eslint/issues/1086), dots are warning if there is space before or after them, while this update aims to only warn for spaces before the enclosing brackets for bracket notation.

File: lib/rules/no-whitespace-before-property.js (hunk 3 above)
Comment (kaicataldo) [inline lib/rules/no-whitespace-before-property.js]: It shouldn't, no - was trying to be defensive in case something outside the rule goes wrong. Do you feel like that's unnecessary?

File: tests/lib/rules/no-whitespace-before-property.js (hunk 4 above)
Comment (kaicataldo) [inline tests/lib/rules/no-whitespace-before-property.js]: Great idea!

File: lib/rules/no-whitespace-before-property.js (hunk 5 above)
Comment (kaicataldo) [inline lib/rules/no-whitespace-before-property.js]: Ah, you're totally right. I'm going to try to implement something along the lines of what @mysticatea suggested.

File: lib/rules/no-whitespace-before-property.js (hunk 6 above)
Comment (kaicataldo) [inline lib/rules/no-whitespace-before-property.js]: Good point. I'll look into this and make the appropriate changes

File: lib/rules/no-whitespace-before-property.js (hunk 1 above)
Comment (kaicataldo) [inline lib/rules/no-whitespace-before-property.js]: :+1:

File: lib/rules/no-whitespace-before-property.js (hunk 2 above)
Comment (michaelficarra) [inline lib/rules/no-whitespace-before-property.js]: Ah, I see, `prop` vs `punc`. I had to read that many times to see the difference.

Comment (kaicataldo) [inline lib/rules/no-whitespace-before-property.js]: Yeah, I should see if there's a clearer way to write that

File: lib/rules/no-whitespace-before-property.js (hunk 3 above)
Comment (michaelficarra) [inline lib/rules/no-whitespace-before-property.js]: I feel like that's unnecessary.

File: lib/rules/no-whitespace-before-property.js (hunk 2 above)
Comment (michaelficarra) [inline lib/rules/no-whitespace-before-property.js]: There is:

```js
let x = punc.value === "." ? prop : punc;
if (sourceCode.isSpaceBetweenTokens(obj, x))
...
```

**Comment by kaicataldo** [comment]
Again, fantastic comments from everyone. Updated with much better checks that now factor in computed properties as well as parentheses in both the object and property names.

File: lib/rules/no-whitespace-before-property.js [hunk 7]
```diff
@@ -25,14 +46,37 @@ module.exports = function(context) {
...
+                var tokenBeforePunc;
+
+                tokenBeforeProp = sourceCode.getTokenBefore(prop);
+                while (tokenBeforeProp.value !== "." && tokenBeforeProp.value !== "[") {
+                    tokenBeforeProp = sourceCode.getTokenBefore(tokenBeforeProp);
+                }
+
+                tokenBeforePunc = sourceCode.getTokenBefore(tokenBeforeProp);
+
+                if (tokenBeforeProp.value === ".") {
```
Comment (mysticatea) [inline lib/rules/no-whitespace-before-property.js]: Thank you for good work!

But I think this `if` statements are too complexity.
Others look good to me.

A code in my head:

```js
var leftToken, rightToken;
if (node.computed) {
    rightToken = findOpenBracket(node);                    // "["
    leftToken = sourceCode.getTokenBefore(rightToken);     // the last token of `node.object` or `)`
} else {
    rightToken = sourceCode.getFirstToken(node.property);  // the token of `node.property`
    leftToken = sourceCode.getTokenBefore(rightToken, 1);  // the last token of `node.object` or `)`
}

if (sourceCode.isSpaceBetweenTokens(leftToken, rightToken)) {
    reportError(node, rightToken); // IMO, in computed properties case, to show "before '['" is more understandable.
}
```

Comment (kaicataldo) [inline lib/rules/no-whitespace-before-property.js]: Hey @mysticatea, thanks for the feedback :) `leftToken` and `rightToken` is much clearer - I like that! Maybe I'm missing something, but each conditional branch checks for whitespace between different tokens - no two are the same. I'd love to simplify it down to what you have in your example above, but I'm not seeing a way to do that. Mind explaining?

I'm going to change variable names right now though!

Comment (mysticatea) [inline lib/rules/no-whitespace-before-property.js]: @kaicataldo `leftToken` and `rightToken` are different token in each case, so `if` statements to check the type of tokens are not needed :)

This should pass all tests: https://gist.github.com/mysticatea/8ad720c48dd9c67336e3

Comment (kaicataldo) [inline lib/rules/no-whitespace-before-property.js]: Ah, I understand. I didn't know about `node.computed` - that saves a lot of hassle!

**Comment by kaicataldo** [comment]
Updated once more. Thanks again to everyone for all the fantastic feedback and help improving this PR!

File: lib/rules/no-whitespace-before-property.js (hunk 7 above)
Comment (kaicataldo) [inline lib/rules/no-whitespace-before-property.js]: Thanks @mysticatea - your help has been invaluable!

**Comment by mysticatea** [comment]
Looks great to me.
Thank you for amazing work!

**Comment by gyandeeps** [comment]
LGTM. Thanks
