### PR TITLE
Fix: only run no-unexpected-multiline division operator if needed (fixes #8550)

### LINKED ISSUE #8550: Cannot read property 'range' of null
**Tell us about your environment**

* **ESLint Version: 4.0.0-alpha.2**
* **Node Version: 7.10.0**
* **npm Version: 4.2.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```js
module.exports = {
    "extends": "eslint:recommended"
};
```

**What did you do? Please include the actual source code causing the issue.**

```js
const number = 5;
number / (5 / 5);
```

**What did you expect to happen?**
No error

**What actually happened? Please include the actual, raw output from ESLint.**
```
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenAfter (/node_modules/eslint/lib/token-store/index.js:319:17)
    at EventEmitter.BinaryExpression[operator='/'] > BinaryExpression[operator='/'] (/node_modules/eslint/lib/rules/no-unexpected-multiline.js:85:55)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at Traverser.enter (/node_modules/eslint/lib/eslint.js:909:36)
    at Traverser.__execute (/node_modules/estraverse/estraverse.js:397:31)
```

### PR DESCRIPTION
**Pull request by BridgeAR**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
The rule should only execute if two division operators are found next to each other.

**Is there anything you'd like reviewers to focus on?**
I'm not sure if this is the best solution but it works as far as I see it.

### CODE REVIEW

File: lib/rules/no-unexpected-multiline.js [hunk 1]
```diff
@@ -82,6 +82,10 @@ module.exports = {
 
             "BinaryExpression[operator='/'] > BinaryExpression[operator='/']"(node) {
```
Comment (not-an-aardvark) [inline lib/rules/no-unexpected-multiline.js]: This is a [selector](http://eslint.org/docs/developer-guide/selectors) -- the function will get called whenever there is a division expression which is a child of another division expression. It's designed to work when the child expression is in the *left* part of the division expression:

```js
foo
/bar/g

// this is actually (foo / bar) / g, and the `node` parameter in the function is `foo / bar`.
```

In the case where `node` is on the left, there will always be a `/` token after `node` because the parent is also a division expression. However, when `node` is on the right, there isn't always a `/` token after the child, which is why `sourceCode.getTokenAfter` returned null and an error was thrown.

As-is, I'm not sure your fix is correct, because there might be another `/` token later in an unrelated part of the program:

```js
5 / (5
/ 5);

var foo = bar / baz; // `secondSlash` for the division above will be the `/` token here, which is unexpected.
```

Instead, I think the best way to fix this is to make sure the function only gets called when the child division expression is on the *left* of its parent. This can be done by adding a field to the selector:

```js
"BinaryExpression[operator='/'] > BinaryExpression[operator='/'].left"(node) {
    // ...
}
```

Comment (BridgeAR) [inline lib/rules/no-unexpected-multiline.js]: Thanks for the explanation! I almost thought the fix wouldn't be sufficient but I thought it does not hurt to open the PR to learn a bit more about eslint.

**Comment by not-an-aardvark** [comment]
Thanks for contributing!
