### PR TITLE
Fix: `spaced-comment` allows a mix of markers and exceptions

### LINKED ISSUE #2895: spaced-comment not recognizing exceptions and markers together.
I'm using:  
```
"spaced-comment": [2, "always", {"exceptions": ["-"], "markers": ["/"]}], 
```
But it still says these lines are errors:
```
///-----------------------------------------------------------------------------------------
```

Additionally, how do i allow empty comments? Something like:
```
///
```

My full documentation comment block is supposed to look like:
```
///-----------------------------------------------------------------------------------------
///
/// @description    Functions description
///
/// @param    [string]    value    parameter description
///
///-----------------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #2895.

I refactored since the rule has a complex flow chart...

New logic is:

1. Makes a `RegExp` object from `markers` and `exceptions`, to validate comments.
2. Checks comments with using the `RegExp` object.

### CODE REVIEW

File: lib/rules/spaced-comment.js [hunk 1]
```diff
@@ -1,111 +1,185 @@
...
+// Helpers
 //------------------------------------------------------------------------------
 
-module.exports = function(context) {
+/**
+ * Escapes the control characters of a given string.
+ * @param {string} s - A string to escape.
+ * @returns {string} An escaped string.
+ */
+function escape(s) {
```
Comment (nzakas) [inline lib/rules/spaced-comment.js]: You can use the `escape-string-regexp` module for this

File: lib/rules/spaced-comment.js [hunk 2]
```diff
@@ -1,111 +1,185 @@
...
-    var markerMatcher = new RegExp(" ");
-    var jsDocMatcher = new RegExp("((^(\\*)))[ \\r\\n]");
+/**
+ * Parses `markers` option.
+ * If markers is not includes `"*"`, adds it to allow JSDoc comments.
+ * @param {string[]|null} markers - A marker list.
+ * @returns {string[]} A marker list.
+ */
+function parseMakersOption(markers) {
+    if (markers == null) {
```
Comment (nzakas) [inline lib/rules/spaced-comment.js]: Misspelled markers as makers.

**Comment by mysticatea** [comment]
Thanks for the review.

I modified using `escape-string-regexp`, and fixed typo.

**Comment by nzakas** [comment]
LGTM
