### PR TITLE
Fix: Check type to be file when looking for config files (fixes #2790)

### LINKED ISSUE #2790: Error: EISDIR, illegal operation on a directory if directory called "package.json" exists
## STR (OS X)

1. Install latest eslint command line
2. `cd ~`, `mkdir package.json`
3. go to some JavaScript and run `eslint .`

## Actual
```
➜  electron-hello-world git:(master) eslint .

/usr/local/lib/node_modules/eslint/lib/config.js:76
                throw e;
                      ^
Error: Cannot read config file: /Users/vladikoff/package.json
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:488:19)
    at Object.fs.readFileSync (fs.js:322:28)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:72:57)
    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:209:23)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:351:22)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:178:27)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:332:26
    at /usr/local/lib/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:41:54)
```

## Expected

Should lint the project

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

File: tests/lib/file-finder.js [hunk 1]
```diff
@@ -88,6 +88,22 @@ describe("FileFinder", function() {
                 assert.equal(actual, expected);
             });
         });
+
+        describe("Not consider directory with expected file names", function() {
+
+            it("should not be found, and an empty array returned", function() {
+                var expected = path.join(process.cwd(), "package.json");
+                process.chdir(fileFinderDir);
+                var finder = new FileFinder("package.json");
```
Comment (nzakas) [inline tests/lib/file-finder.js]: We shouldn't change the cwd during test execution, this could have unintended consequences

Comment (gyandeeps) [inline tests/lib/file-finder.js]: I have to, to hit a particular scenario. 
I dont see any problems. I can put the revert inside the `afterEach` so that it would always put the path back to original but other than that I dont see any issues.

Comment (nzakas) [inline tests/lib/file-finder.js]: I'm still very uncomfortable with this. There has to be a way to stimulate changing cwd without actually needing to change it. Maybe pass in to File Finder some how?

Comment (gyandeeps) [inline tests/lib/file-finder.js]: One way I can think of is to `stub` the `process.cwd()` function. Do you think that would be fine?

Comment (nzakas) [inline tests/lib/file-finder.js]: Why not just pass in what should be cwd as an argument?

**Comment by gyandeeps** [comment]
Done. Should be good to go.

File: tests/lib/file-finder.js [hunk 2]
```diff
@@ -88,6 +88,16 @@ describe("FileFinder", function() {
...
             });
         });
+
+        describe("Not consider directory with expected file names", function() {
+            it("should not be found, and an empty array returned", function() {
+                var expected = path.join(process.cwd(), "package.json");
+                var finder = new FileFinder("package.json");
+                var actual = finder.findInDirectoryOrParents(fileFinderDir);
+
+                assert.equal(actual, expected);
```
Comment (nzakas) [inline tests/lib/file-finder.js]: This doesn't look like it's returning an empty array. Am I missing something?

File: tests/lib/file-finder.js [hunk 3]
```diff
@@ -158,5 +168,15 @@ describe("FileFinder", function() {
                 assert.lengthOf(actual, 0);
             });
         });
+
+        describe("Not consider directory with expected file names", function() {
+            it("should not be found, and an empty array returned", function() {
+                expected = path.join(process.cwd(), "package.json");
+                finder = new FileFinder("package.json");
+                actual = finder.findAllInDirectoryAndParents(fileFinderDir);
```
Comment (nzakas) [inline tests/lib/file-finder.js]: Same here.

File: tests/lib/file-finder.js (hunk 2 above)
Comment (gyandeeps) [inline tests/lib/file-finder.js]: Dang it. Forgot to update the description.
Will fix it.

**Comment by nzakas** [comment]
Hmm, it looks like there isn't a test that checks the `package.json` directory?

**Comment by gyandeeps** [comment]
I created a directory with name "package.json". It doesn't consider it.

**Comment by nzakas** [comment]
Doesn't file Finder start from cwd though? In that case, it would skip over the fixtures directory named package.json, right?

**Comment by gyandeeps** [comment]
Right now I pass in a directory, so it will start from that directory. But it will read all the content inside that directory. So as of now the package.json directory is being read.
If you run the unit test without the code change they would fail as it would consider the directory package.json as file.

**Comment by nzakas** [comment]
Ooh, I'm sorry, must be tired. I see it now. Lgtm.
