### PR TITLE
Fix: `no-useless-constructor` rule crashes sometimes

### LINKED ISSUE #5290: no-useless-constructor rule causing crash
The version of ESLint you are using.
```
$ node_modules/.bin/eslint -v
v2.0.0
```

Env and parserOptions 
```
    "env": {
        "browser": true,
        "node": true,
        "jasmine": true,
        "es6": true
    },
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true,
            "experimentalObjectRestSpread": true
        }
    },
```

What you did.
`"no-useless-constructor": 2`

What you expected to happen.
eslint not to crash.

What actually happened.
eslint crashed.

## Repro 1

```
import React from 'react';
var foo = 2;
class TestComponent extends React.Component {
    constructor() {
        super(foo);
    }
    render() {
        return <div/>;
    }
}
```
```
/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:30
            return (arg.type === "Identifier" && arg.name === ctorParams[index].name) ||
                                                                               ^

TypeError: Cannot read property 'name' of undefined
    at /Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:30:80
    at Array.every (native)
    at isRedundantSuperCall (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:30:45)
    at EventEmitter.checkForConstructor (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:53:46)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/eslint.js:836:36)

```

## Repro 2

```
import React from 'react';
class TestComponent extends React.Component {
    constructor() {
        super(...arguments);
    }
    render() {
        return <div/>;
    }
}
```
```
/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:33
                ctorParams[index].type === "RestElement" &&
                                 ^

TypeError: Cannot read property 'type' of undefined
    at /Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:33:34
    at Array.every (native)
    at isRedundantSuperCall (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:29:45)
    at EventEmitter.checkForConstructor (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:52:46)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/eslint.js:836:36)
```

### PR DESCRIPTION
**Pull request by BYK**
Fixes #5290

### CODE REVIEW

File: lib/rules/no-useless-constructor.js [hunk 1]
```diff
@@ -25,13 +25,19 @@ module.exports = function(context) {
...
+                ctorParams.length &&
+                arg.name === ctorParams[index].name
+            ) || (
                 arg.type === "SpreadElement" &&
+                ctorParams.length &&
                 ctorParams[index].type === "RestElement" &&
                 arg.argument.name === ctorParams[index].argument.name
+            ) || (
+                arg.type === "SpreadElement" &&
+                arg.argument.name === "arguments"
```
Comment (michaelficarra) [inline lib/rules/no-useless-constructor.js]: Needs to also check `!ctorParams.length` to avoid reporting constructors with observable effects in their parameter lists.

Comment (BYK) [inline lib/rules/no-useless-constructor.js]: Are you sure? I'm specifically checking for `arguments` which should not be affected by any parameters taken. Right?

Comment (nzakas) [inline lib/rules/no-useless-constructor.js]: @michaelficarra can you give an example?

Comment (michaelficarra) [inline lib/rules/no-useless-constructor.js]:
```js
class A { constructor([a, b, c]) { super(...arguments); } }
```

This will call `next` on the generator passed in as the first argument three times. This is observable.

```js
class A { constructor(a = f()) { super(...arguments); } }
```

This will call `f` when zero arguments are passed. This is observable.

```js
class A { constructor({[f()]: a}) { super(...arguments); } }
```

This will call `f` unconditionally. This is observable.

Comment (BYK) [inline lib/rules/no-useless-constructor.js]: @michaelficarra thanks for the examples! So you are saying we should only warn on this iff `constructor` doesn't receive any named/defined arguments and super is called with `...arguments`, correct?

Comment (michaelficarra) [inline lib/rules/no-useless-constructor.js]: Yes, the additional check I listed above should be sufficient.

Comment (BYK) [inline lib/rules/no-useless-constructor.js]: Awesome, thanks!

**Comment by BYK** [comment]
Updated per @michaelficarra's suggestion.

File: lib/rules/no-useless-constructor.js [hunk 2]
```diff
@@ -25,13 +25,20 @@ module.exports = function(context) {
             return false;
         }
 
-
         return body[0].expression.arguments.every(function(arg, index) {
-            return (arg.type === "Identifier" && arg.name === ctorParams[index].name) ||
```
Comment (michaelficarra) [inline lib/rules/no-useless-constructor.js]: This works, but I would write it more like

```js
var superArgs = body[0].expression.arguments;
var isSimpleParameterList = ctorParams.every(function(param, index) {
    return param.type === "Identifier" || param.type === "RestElement";
});
var spreadsArguments = 
    superArgs.length === 1 &&
    superArgs[0].type === "SpreadElement" &&
    superArgs[0].argument.name === "arguments";
var passesParamsAsArgs =
    superArgs.length === ctorParams.length && 
    superArgs.every(function(arg, index) {
        return (
            arg.type === "Identifier" &&
            arg.name === ctorParams[index].name
        ) || (
            arg.type === "SpreadElement" &&
            ctorParams[index].type === "RestElement" &&
            arg.argument.name === ctorParams[index].argument.name
        );
    });
return isSimpleParameterList && spreadsArguments || passesParamsAsArgs;
```

Also, I do some additional length checks which are necessary.

Comment (BYK) [inline lib/rules/no-useless-constructor.js]: Nice refactoring! I can create a PR but I don't wanna take credit for the work you did. Would it be hard for you to create a PR for this? If not I'll do it.

Comment (BYK) [inline lib/rules/no-useless-constructor.js]: I meant I can update this one lol :)

I'm just trying to say I'd rather you follow-up after this patch is merged if this looks okay to you.

Comment (michaelficarra) [inline lib/rules/no-useless-constructor.js]: It's fine, you can just incorporate it. You should add some tests that show the benefits of my implementation, such as 

```js
class A extends B { constructor(a, b, ...c) { super(...arguments); } }
```

Comment (BYK) [inline lib/rules/no-useless-constructor.js]: Alright, if you insist :)

**Comment by BYK** [comment]
Updated one more time :)

**Comment by michaelficarra** [comment]
Please also add this test:

```js
class A extends B { constructor(a, b, c) { super(a, b); } }
```

**Comment by BYK** [comment]
@michaelficarra that revealed a bug (guessing you were already aware). Fixed and updated.

**Comment by michaelficarra** [comment]
@BYK Nooooo, that is supposed to be reported by this rule. The additional `c` parameter is inconsequential. The implementation was correct before.

**Comment by BYK** [comment]
@michaelficarra how is inconsequential? What if the original constructor takes an optional last argument and the implementor wants to force it to the default value at all times?

**Comment by michaelficarra** [comment]
You're right, but this means that pass-through arguments must always include a rest parameter. So we just need to replace `passesParamsAsArgs` with

```js
var passesParamsAsArgs =
    superArgs.length === ctorParams.length &&
    superArgs.length >= 1 &&
    superArgs[superArgs.length - 1].type === "SpreadElement" &&
    superArgs.every(function(arg, index) {
        return (
            arg.type === "Identifier" &&
            arg.name === ctorParams[index].name
        ) || (
            arg.type === "SpreadElement" &&
            ctorParams[index].type === "RestElement" &&
            arg.argument.name === ctorParams[index].argument.name
        );
    });
```

**Comment by BYK** [comment]
>but this means that pass-through arguments must always include a rest parameter

Not necessarily. I think my implementation and the test cases cover it. Consider the following:
```js
class A { constructor(a, b, c=5) {} }
class B extends A { constructor (a, b, c) { super(a, b); } }
```

We should //not// warn when we see this code (but your suggestion would). The reason is we do not warn for the code below:

```js
class A { constructor(a, b, c=5) {} }
class B extends A { constructor (a, b) { super(a, b); } }
```

Makes sense?

**Comment by michaelficarra** [comment]
Yeah, that's what I meant by "must always include a rest parameter". I meant "in order to report the pass-through arguments case, they ...". Additionally, your implementation looks like it will error on

```js
class A extends B { constructor() { super(); } }
```

because it checks the type of `lastSuperArg` without first checking that it must exist (`superArgs.length >= 1`) like I do above.

**Comment by BYK** [comment]
@michaelficarra - can't believe we didn't have that obvious test case!

Anyways, added it and verified it works as expected with the existing code because the first part of the `||` statement comes back as `true` so it never tries to evaluate the second part.

**Comment by michaelficarra** [comment]
LGTM.
