### PR TITLE
fix: wrong suggestion and message in `no-misleading-character-class`

### LINKED ISSUE #17537: Bug: `no-misleading-character-class` suggests to add `u` flag when it's already there
### Environment

Node version: v20.4.0
npm version: v9.7.2
Local ESLint version: v8.48.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19045

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
{
    "parserOptions": {
        "ecmaVersion": "latest"
    }
}
```
</details>

```js
/*eslint no-misleading-character-class: "error"*/

new RegExp("[\\ud83d\\u{dc4d}]", "u");
```

### What did you expect to happen?

No suggestions.

### What actually happened?

I'm getting this suggestion:

> Add unicode 'u' flag to regex.

But the flag is already set.

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3M6IFwiZXJyb3JcIiovXG5cbm5ldyBSZWdFeHAoXCJbXFxcXHVkODNkXFxcXHV7ZGM0ZH1dXCIsIFwidVwiKTtcbiIsIm9wdGlvbnMiOnsiZW52Ijp7ImVzNiI6dHJ1ZX0sInJ1bGVzIjp7fSwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9LCJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQifX19

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by ota-meshi**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

close #17537

Fixed incorrect message and changed to not suggest u flag, when Unicode code point escapes were included.

### CODE REVIEW

**Comment by ota-meshi** [comment]
Hmm. I don't really understand why Browser Test fails.
I suspect that the webdriverio update may be the cause, but I'm not sure.

https://github.com/webdriverio/webdriverio/pull/11175

**Comment by mdjermanovic** [comment]
> Hmm. I don't really understand why Browser Test fails. I suspect that the webdriverio update may be the cause, but I'm not sure.
> 
> [webdriverio/webdriverio#11175](https://github.com/webdriverio/webdriverio/pull/11175)

It's failing on `main` too. I opened https://github.com/eslint/eslint/issues/17572. Shouldn't be a blocker for this PR.

File: tests/lib/rules/no-misleading-character-class.js [hunk 1]
```diff
@@ -628,6 +628,38 @@ ruleTester.run("no-misleading-character-class", rule, {
                 suggestions: null
             }]
         },
+        {
+            code: String.raw`/[\ud83d\u{dc4d}]/u`,
+            env: { es2020: true },
```
Comment (mdjermanovic) [inline tests/lib/rules/no-misleading-character-class.js:633]:
```suggestion
```

This isn't necessary for this test case, so it might be confusing why it is here.

File: tests/lib/rules/no-misleading-character-class.js [hunk 2]
```diff
@@ -628,6 +628,38 @@ ruleTester.run("no-misleading-character-class", rule, {
...
+            errors: [{
+                messageId: "surrogatePair",
+                suggestions: null
+            }]
+        },
+        {
+            code: String.raw`/[\u{d83d}\udc4d]/u`,
+            env: { es2020: true },
```
Comment (mdjermanovic) [inline tests/lib/rules/no-misleading-character-class.js:641]:
```suggestion
```

File: tests/lib/rules/no-misleading-character-class.js [hunk 3]
```diff
@@ -628,6 +628,38 @@ ruleTester.run("no-misleading-character-class", rule, {
...
+            errors: [{
+                messageId: "surrogatePair",
+                suggestions: null
+            }]
+        },
+        {
+            code: String.raw`/[\u{d83d}\u{dc4d}]/u`,
+            env: { es2020: true },
```
Comment (mdjermanovic) [inline tests/lib/rules/no-misleading-character-class.js:649]:
```suggestion
```

File: tests/lib/rules/no-misleading-character-class.js [hunk 4]
```diff
@@ -628,6 +628,38 @@ ruleTester.run("no-misleading-character-class", rule, {
...
+            errors: [{
+                messageId: "surrogatePair",
+                suggestions: null
+            }]
+        },
+        {
+            code: String.raw`/[\uD83D\u{DC4d}]/u`,
+            env: { es2020: true },
```
Comment (mdjermanovic) [inline tests/lib/rules/no-misleading-character-class.js:657]:
```suggestion
```

**Review by mdjermanovic — CHANGES_REQUESTED** [review]
Just a small suggestion about the tests, then LGTM.

**Comment by ota-meshi** [comment]
Thank you for checking this PR! I changed this PR.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
