### PR TITLE
Fix: Make no-implied-eval match more types of strings (fixes #2898)

### LINKED ISSUE #2898: no-implied-eval doesn't work on template strings or with concatinated strings
For example, `no-implied-eval` could catch:

```js
setInterval(`helper(${foo}, ${bar})`, 50);
// or
setInterval("helper(" + foo + ", " + bar + ")", 50);
```

The first case is easy, as it just needs to check for a TemplateLiteral. The second part is probably a bit more controversial, but basically any concatenation with a literal string implies a string result.

I'm willing to fix this if people want it. (I already have a patch ready)

### PR DESCRIPTION
**Pull request by bgw**
- TemplateLiterals are strings
- Concatinating with a literal string implies a string. Eg.

  ```js
  setInterval("helper(" + foo + ", " + bar + ")", 50);
  ```

### CODE REVIEW

**Comment by michaelficarra** [comment]
What about `setTimeout(1 + ";" + 1, 0)`?

**Comment by nzakas** [comment]
Maybe we can make this simpler by checking to see if the first argument is either an identifier or a function, and if not, then warn?

I don't think we want to get too far down the path of trying to determine if something evaluates to a string or not.

**Comment by michaelficarra** [comment]
What about a function call? Or a member access? Spread? There's probably others, as well...

**Comment by nzakas** [comment]
Can you suggest an approach? We need either a whitelist or a blacklist, which would you recommend?

**Comment by michaelficarra** [comment]
I say leave it like it is. If you see a string (or possibly untagged template), report it. Otherwise, assume it will be fine.

**Comment by bgw** [comment]
Sorry, I mentally checked out for the three day weekend.

This is a rabbit hole: Checking types is probably something that's more the job of Flow or TypeScript, rather than ESLint, so I understand if this doesn't get merged, or if you only want to merge the untagged template literal case. Let me know if you'd rather just do that and I can open a separate PR.

However, these kinds of ad-hoc checks are still useful for code that isn't typechecked, which is why I think checking string concatenation is a pragmatic approach. Concatenation is at least easy to check, and I suspect one of the most common offending cases.

@michaelficarra, This would warn on that example of `setTimeout(1 + ";" + 1, 0)`. Since `isStringType` is evaluated recursively, it will eventually hit the the string literal by traversing down two levels of `BinaryExpression`s. I also agree of course that it will miss many opportunities as well.

@nzakas, I agree with @michaelficarra here that a whitelist approach will result in far too many false positives, and I'd rather have false negatives than false positives.

**Comment by nzakas** [comment]
If we're going to merge, we have to eliminate the recursive descent in `isStringType()`, as that's very inefficient. We are already doing a traversal in ESLint, so it would be best to use that instead of doing another one.

**Comment by bgw** [comment]
I'd argue that the recursive descent is efficient, because it's only entered for `setTimeout`/`setInterval` `CallExpressions` where the argument is a `BinaryExpression`, which should be rare.

Unless I'm missing something alternative is:

1. Track enter of the `CallExpression`, followed by exit of the *first argument* (otherwise it will keep evaluating additional arguments). If you want to be technically correct here, you have to maintain a stack, because somebody could do `setTimeout(setTimeout(foo) + "bar", 50)`, but that's an extreme edge case.
2. On *any* `BinaryExpression`:
  1. Check if the entered `CallExpression` flag is set, or
  2. Check that the immediate ancestor is part of the chain leading up to the potentially unsafe `CallExpression`.
  3. If one of the above is true, mark this `BinaryExpression` as part of the chain leading up to the potentially unsafe `CallExpression`. Otherwise you might get false positives on something like `setInterval(getCallback('this is' + 'safe'))` where the parent of the `BinaryExpression` isn't actually `setInterval`.
  4. If a string literal is encountered, report an error on the original `CallExpression`, and then unset the state flag to avoid triggering on every remaining literal string that's part of the concatenation.

Which quickly becomes near-impossible to reason about. You could simplify this by inspecting the ancestors of every `BinaryExpression`, but that's even worse for performance than the occasional recursive descent.

**Comment by nzakas** [comment]
@bgw this is a general rule we have for all rules - no adhoc traversal outside of the ESLint traversal. You can look up the tree or down at immediate children, but anything further starts to add up. Plus, you need to arbitrarily cut off at some point, which is always strange.

We maintain stacks in many rules, and that approach is correct. 

I think you can simply by setting a flag when you enter the first argument. At that point, any BinaryExpression reports an error when any argument is a string.

**Comment by bgw** [comment]
> I think you can simply by setting a flag when you enter the first argument. At that point, any BinaryExpression reports an error when any argument is a string.

But what if you're given: `setInterval(getCallback('this is' + 'safe'))`? You've entered the first arg of `setInterval`, and you'll traverse a `BinaryExpression` with strings, but the `BinaryExpression` wasn't passed immediately to the parent argument. You must inspect the `BinaryExpression`'s parent.

It's not like this code is traversing the entire sub-AST. The moment it encounters something other than a `BinaryExpression`, string literal, or template literal, it stops.

> We maintain stacks in many rules, and that approach is correct.

But in those cases, you're checking all children of an AST node. In this case we're checking all *immediate* children of the AST node, which is different.

[Here's an example in babel where they've got a similar issue](https://github.com/babel/babel/blob/master/src/babel/transformation/transformers/es6/template-literals.js#L19). They normally traverse using `visitor`, but they need to cut off the traversal once they visit something that doesn't match `_templateLiteralProduced`, so they use ad-hoc recursion.

**Comment by nzakas** [comment]
You can always look down one level. So if the first argument is not a BinaryExpression, then don't set the flag.

**Comment by bgw** [comment]
@nzakas Sorry it took so long, I was delayed by some other stuff. I did this as a separate commit so it's easier to compare the differences between the changesets, but let me know if you want to merge it and I'll squash it down.

I'm open to suggestions about ways to simplify this implementation.

File: lib/rules/no-implied-eval.js [hunk 1]
```diff
@@ -12,51 +12,78 @@
...
+            isDangerousCallee =
+                (isIdentifier && CALLEE_RE.test(node.callee.name)) ||
+                (isMemberExpression && isDangerousMemberExpression(node.callee));
+
+        return isDangerousCallee && node.arguments.length;
+    }
 
-        return isSetMethod && hasStringLiteralArgument(node);
+    function hasDangerousParent(node) {
+        var parent = last(context.getAncestors(node));
```
Comment (bgw) [inline lib/rules/no-implied-eval.js]: Is there a faster way to get the parent? getAncestors copies the entire traversal path, but we only really need one element. [We seem to use this pattern a lot in eslint though](https://github.com/eslint/eslint/search?utf8=%E2%9C%93&q=getAncestors%28%29.pop%28%29).

Should I submit a PR to estraverse to add a `parent()` method (in addition to `parents()`) that gets only the immediate parent?

Comment (michaelficarra) [inline lib/rules/no-implied-eval.js]: That function would not be total. Return `null` for nodes without parents?

Comment (bgw) [inline lib/rules/no-implied-eval.js]: Are you referring to `hasDangerousParent` or the hypothetical estraverse `parent()` method? For the former, there's always going to be a parent, even if it's `Program`. For the later, yes, I'd probably do that.

Comment (michaelficarra) [inline lib/rules/no-implied-eval.js]: The latter.

Comment (ilyavolodin) [inline lib/rules/no-implied-eval.js]: There's actually already a parent property on node element. It's attached during traversal and should be accessible anywhere inside the rule as `node.parent`.

Comment (bgw) [inline lib/rules/no-implied-eval.js]: @ilyavolodin, Agasp! Why do we use `context.getAncestors().pop()` in so many places? @nzakas?

**Comment by DmitrySoshnikov** [comment]
The implementation with several manual (sub)stacks seems to me messy. After all, probably recursive decent in this specific case ins't that bad, since there should be no in practice cases, where it won't stop first level of check. But, it's up to @nzakas and other maintainers if your guys prefer complicating the code with manual "stacks of stacks". With recursion (and automatically reusing the call-stack), it's much nicer and simpler code.

File: lib/rules/no-implied-eval.js (hunk 1 above)
Comment (ilyavolodin) [inline lib/rules/no-implied-eval.js]: @bgw I don't remember the whole history, but `node.parent` was added later then `context.getAncestors` as far as I recall. In a lot of rules you also need more then just immediate parent, so people got used to `context.getAncestors`. Actually we were talking to too long ago about removing `node.paren` because it's underused and can be replicated with other functionality, but we decided against it anyways.

Comment (bgw) [inline lib/rules/no-implied-eval.js]: @ilyavolodin, Would you be opposed if I did a find-replace in ESLint to use `node.parent` everywhere the `context.getAncestors().pop()` is currently in use?

Comment (ilyavolodin) [inline lib/rules/no-implied-eval.js]: I'm not 100% sure what we would gain with that change. My guess is slightly less memory consumed, but I think it will be negligible. Performance also should be affected by this. Also in 2.0.0 we are planning to add support for selector syntax for nodes that will solve this problem anyways for most of the rules.

Comment (nzakas) [inline lib/rules/no-implied-eval.js]: Initially we didn't have node.parent, it was added after a lot of rules were already created. We just update them as we update rules, so a mass migration isn't necessary or useful for this.

File: lib/rules/no-implied-eval.js [hunk 2]
```diff
@@ -12,51 +12,77 @@
...
     /**
-     * Checks if the given MemberExpression node is window.setTimeout or window.setInterval.
+     * Checks if the given MemberExpression node is a dangerous identifier on window.
      * @param {ASTNode} node The MemberExpression node to check.
-     * @returns {boolean} Whether or not the given node is window.set*.
+     * @returns {boolean} Whether or not the given node is potentially dangerous.
+     * @private
      */
-    function isSetMemberExpression(node) {
+    function isDangerousMemberExpression(node) {
```
Comment (nzakas) [inline lib/rules/no-implied-eval.js]: I think the term "dangerous" is confusing throughout. I'd replace with "implied eval" wherever possible.

File: lib/rules/no-implied-eval.js [hunk 3]
```diff
@@ -12,51 +12,77 @@
...
-                (isMemberExpression && isSetMemberExpression(node.callee));
+            isDangerousCallee =
+                (isIdentifier && CALLEE_RE.test(node.callee.name)) ||
+                (isMemberExpression && isDangerousMemberExpression(node.callee));
+
+        return isDangerousCallee && node.arguments.length;
+    }
 
-        return isSetMethod && hasStringLiteralArgument(node);
+    function hasDangerousParent(node) {
```
Comment (nzakas) [inline lib/rules/no-implied-eval.js]: Please add JSDoc

**Comment by nzakas** [comment]
@DmitrySoshnikov manual recursion with arbitrary cutoff still leaves edge cases uncovered. Using the existing traversal, we get to cover all cases.

Plus, this is a scaling issue for us. If we have one rule doing manual traversal, we will end up with more, and when too many are doing it there is a perf impact (happened early on, that's why we keep an eye out for it now).

**Comment by ilyavolodin** [comment]
I think this should be good to merge now after squash and rebase.

**Comment by bgw** [comment]
Squashed and rebased.

**Comment by nzakas** [comment]
Can you sign our CLA? http://eslint.org/cla

**Comment by bgw** [comment]
Signed.
