### PR TITLE
Fix: space-before-keywords fails with super keyword (fixes #3946)

### LINKED ISSUE #3946: "space-before-keywords" doesn't work nicelly with ES6's "super" keyword
The following code throws with ``space-before-keywords: [2, "always"]`` enabled:

```javascript
(super.componentWillMount || noop)(...arguments);
```

Error thrown:
``Missing space before keyword "super". (space-before-keyword)``

I think ``super`` keyword in ES6 could be considered as a "normal" variable, so this rule kind of breaks on normal use cases.

ESLint version: ``v1.5.0``

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26972491-space-before-keywords-doesn-t-work-nicelly-with-es6-s-super-keyword?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

**Comment by alberto** [comment]
I'm resubmitting this. I don't know what happened to the previous PR.

**Comment by ilyavolodin** [comment]
LGTM. @nzakas can you check if that's the behavior you wanted?

File: tests/lib/rules/space-before-keywords.js [hunk 1]
```diff
@@ -218,25 +218,6 @@ ruleTester.run("space-before-keywords", rule, {
             code: "; class Bar extends Foo.Baz {}",
             ecmaFeatures: { classes: true },
             options: never
-        },
-        // Super
-        {
```
Comment (nzakas) [inline tests/lib/rules/space-before-keywords.js]: Shouldn't these tests still pass?

Comment (alberto) [inline tests/lib/rules/space-before-keywords.js]: Do you mean just the valid ones, or all of them? They valid ones still pass, but it didn't make much sense to me keeping them after removing the check on super.

Comment (nzakas) [inline tests/lib/rules/space-before-keywords.js]: The valid ones. In general, we want to avoid removing valid test cases for rules to ensure backwards compatibility. Can you add these back?

Comment (alberto) [inline tests/lib/rules/space-before-keywords.js]: Sure.

Comment (alberto) [inline tests/lib/rules/space-before-keywords.js]: @nzakas done.

**Comment by gyandeeps** [comment]
LGTM.
