### PR TITLE
fix!: assert 'text' is a string across all RuleFixer methods

### LINKED ISSUE #18807: Change Request: Reject non string replacements in `fixer.replaceText()`
### ESLint version

v9

### What problem do you want to solve?

In a rule `fix` function, 

```js
fixer.replaceText(node, replacement.text);
```

when `replacement.text` is undefined, it will replace the node with `undefined`.

### What do you think is the correct solution?

Throw an error instead.

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

Prevent mistakes.

### PR DESCRIPTION
**Pull request by Pixel998**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

This PR enforces string-only inputs for all fixer methods that take a string (throwing a `TypeError` when a non-string is provided), updates JSDoc to document this behavior, and adds tests to cover the error case.

Closes #18807

### CODE REVIEW

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Would like a second review before moving https://github.com/eslint/eslint/issues/18807 to the "Ready for Merge" status.

File: lib/rules/dot-notation.js [hunk 1]
```diff
@@ -125,7 +125,7 @@ module.exports = {
 						}
 						yield fixer.replaceTextRange(
 							[leftBracket.range[0], rightBracket.range[1]],
-							value,
+							String(value),
```
Comment (fasttime) [inline lib/rules/dot-notation.js:128]: `value` is typed as `string` in JSDoc, but I guess that was a mistake?

Comment (Pixel998) [reply lib/rules/dot-notation.js:128]: Yes — the JSDoc was too narrow.

**Review by fasttime — DISMISSED** [review]
LGTM, thanks!

**Review by mdjermanovic — DISMISSED** [review]

**Review by fasttime — APPROVED** [review]
LGTM, thanks again!
