### PR TITLE
Fix: vars-on-top conflict with ES6 import (fixes #2099)

### LINKED ISSUE #2099: vars-on-top conflicts with ES6 `import`
When `vars-on-top` is enabled, it warns (IMO incorrectly) on this ES6 code

```js
import React from 'react';

var foo = 'bar';
```

It wants `var` declaration to be before `import` call. That is unnecessary.

I'm using `babel-eslint` parser and `browser` env.

### PR DESCRIPTION
**Pull request by gyandeeps**
Just checking for `import` right now.
Any others I should be looking at?

### CODE REVIEW

File: lib/rules/vars-on-top.js [hunk 1]
```diff
@@ -28,6 +28,15 @@ module.exports = function (context) {
     }
 
     /**
+     * Check to see if its a ES6 import declaration
+     * @param {ASTNode} node - any node
+     * @returns {Boolean} whether the given node represents a import declaration
+     */
+    function looksLikeImport(node) {
+        return node.type === "ImportDeclaration";
```
Comment (btmills) [inline lib/rules/vars-on-top.js]: ESTree split this up into multiple node types - see https://github.com/estree/estree/blob/master/es6.md#modules, though I don't recall whether Espree implements them yet. Should be able to check them all here for forward-compatibility even if they aren't parsed that way yet.

Comment (gyandeeps) [inline lib/rules/vars-on-top.js]: Sounds good to me. I will that implemented in few mins.

**Comment by nzakas** [comment]
LGTM.
