### PR TITLE
Fix: no-mixed-tabs-and-spaces fails with some comments (fixes #4086)

### LINKED ISSUE #4086: Bug: no-mixed-tabs-and-spaces fails with non-jsdoc multiline comments
Multiline comments don't require `*` at the beginning of the inner lines.

This test should pass, but currently doesn't:
```
        {
            code: "/*\n\n \t \n*/"
        }
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27268074-bug-no-mixed-tabs-and-spaces-fails-with-non-jsdoc-multiline-comments?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

File: lib/rules/no-mixed-spaces-and-tabs.js [hunk 1]
```diff
@@ -69,6 +66,20 @@ module.exports = function(context) {
...
 
+    /**
+     * Determines if a given line and column are contained in a list of tokens.
+     * @param {array} tokens The array of tokens to look at.
+     * @param {int} line The line to check.
+     * @param {int} column The column to check.
+     * @returns {boolean} True if the line and column are inside any of the tokens.
+     * @private
+     */
+    function isInTokens(tokens, line, column) {
```
Comment (nzakas) [inline lib/rules/no-mixed-spaces-and-tabs.js]: This is pretty inefficient because it always good through every comment. In reality, you can eliminate more comments as you go through the file. If like to see a more efficient approach here.

Comment (alberto) [inline lib/rules/no-mixed-spaces-and-tabs.js]: Optimized. Please review.

**Comment by nzakas** [comment]
LGTM. Thanks!
