### PR TITLE
Fix: Method name resolution in complexity rule (fixes #2049)

### LINKED ISSUE #2049: complexity rule doesn't understand ES6 class function names
In an ES6 class that fails the `complexity` rule, e.g.:

```js
class MyClass {
  foo() {
    ...
  }
}
```

I get the message:

> Function 'anonymous' has a complexity of N (complexity)

It would be better if this message (and likely others) included the function's name instead of "anonymous".

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9593889-complexity-rule-doesn-t-understand-es6-class-function-names?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

**Comment by btmills** [comment]
The build is failing due to a missing space before `ecmaFeatures` on line 45 of the tests.

File: tests/lib/rules/complexity.js [hunk 1]
```diff
@@ -20,48 +20,48 @@ var eslint = require("../../../lib/eslint"),
...
-        { code: "function a(x) {return x || 4;}", args: [1, 2] },
-        { code: "function a(x) {x && 4;}", args: [1, 1] },
-        { code: "function a(x) {switch(x){case 1: 1; break; case 2: 2; break; default: 3;}}", args: [1, 3] },
-        { code: "function a(x) {switch(x){case 1: 1; break; case 2: 2; break; default: if(x == 'foo') {5;};}}", args: [1, 4] },
-        { code: "function a(x) {while(true) {'foo';}}", args: [1, 2] },
-        { code: "function a(x) {do {'foo';} while (true)}", args: [1, 2] },
-        { code: "if (foo) { bar(); }", args: [1, 3] },
-        { code: "var a = (x) => {do {'foo';} while (true)}", args: [1, 2], ecmaFeatures: { arrowFunctions: true } }
-
+        { code: "function a(x) {}", options: [1] },
```
Comment (ilyavolodin) [inline tests/lib/rules/complexity.js]: Why removal of the second parameter in the options? Isn't that supposed to be threshold?

Comment (nzakas) [inline tests/lib/rules/complexity.js]: We've been replacing `args` with `options` because it doesn't make sense to include the rule severity in tests. So `args: [2, 1]` becomes `options: [1]`, and `options` now matches what's passed in on `context.options` to rules.

I've been trying to update this as I go.

Comment (ilyavolodin) [inline tests/lib/rules/complexity.js]: Ahh.. ok, got it.
