### PR TITLE
Fix: init error in extending recommended config (fixes #12707)

### LINKED ISSUE #12707: eslint --init: config.extends.push
**Tell us about your environment**
Node version: v12.14.0
npm version: v6.13.4
Local ESLint version: v6.8.0 (Currently used)
Global ESLint version: Not found

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
I want to enable eslint for my exists TypeScript project.

```bash
eslint --init
```
```text
? How would you like to use ESLint? To check syntax, find problems, and enforce code style
? What type of modules does your project use? JavaScript modules (import/export)
? Which framework does your project use? React
? Does your project use TypeScript? Yes
? Where does your code run? Browser, Node
? How would you like to define a style for your project? Inspect your JavaScript file(s)
? Which file(s), path(s), or glob(s) should be examined? ./src/**.{ts,tsx}
? What format do you want your config file to be in? JavaScript
```

**What actually happened? Please include the actual, raw output from ESLint.**
Several module not found：
* @typescript-eslint/parser
* eslint-plugin-react
* @typescript-eslint

After install them all, It show me an error:
```text
Determining Config: 0% [------------------------------] 0.0s elapsed, eta 0.0s Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
Determining Config: 100% [==============================] 0.1s elapsed, eta 0.0s

Enabled 275 out of 275 rules based on 2 files.

config.extends.push is not a function
TypeError: config.extends.push is not a function
    at processAnswers (/MY_PROJ/node_modules/eslint/lib/init/config-initializer.js:331:24)
    at /MY_PROJ/node_modules/eslint/lib/init/config-initializer.js:615:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Are you willing to submit a pull request to fix this bug?**
No, I found the problem, but don't know how to fix it (in your way).

https://github.com/eslint/eslint/blob/master/lib/init/autoconfig.js#L336

`extendFromRecommended` will set `config.extends` to `RECOMMENDED_CONFIG_NAME`, there are two problems:
* RECOMMENDED_CONFIG_NAME is a string, after `extendFromRecommended` return, the parent scope expect `config.extends` is an array
* It drop my selection of "react" (or "vue")

### PR DESCRIPTION
**Pull request by yeonjuan**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Fix #12707. It still has a `triage label` but I can reproduce it 
reproduced - https://github.com/yeonjuan/autoconfbug

**Is there anything you'd like reviewers to focus on?**

The cause of the problem is precisely what [here](https://github.com/eslint/eslint/issues/12707#issue-541987711) mentioned.
> RECOMMENDED_CONFIG_NAME is a string, after extendFromRecommended return, the parent scope expect config.extends is an array

### CODE REVIEW

File: lib/init/autoconfig.js [hunk 1]
```diff
@@ -333,7 +333,7 @@ function extendFromRecommended(config) {
             delete newConfig.rules[ruleId];
         }
     });
-    newConfig.extends = RECOMMENDED_CONFIG_NAME;
+    newConfig.extends = [RECOMMENDED_CONFIG_NAME];
```
Comment (kaicataldo) [inline lib/init/autoconfig.js]: I think this will overwrite any other plugins that are already set [here](https://github.com/eslint/eslint/blob/master/lib/init/config-initializer.js#L289-L297). Can we instead push to `newConfig.extends`? It will get normalized in the end [here](https://github.com/eslint/eslint/blob/master/lib/init/config-initializer.js#L333-L338) anyway.

Comment (yeonjuan) [reply lib/init/autoconfig.js]: @kaicataldo 
Yes. I'll add test cases. thanks. :)

**Comment by kaicataldo** [comment]
Thanks for adding tests for this! I just had a thought - would it make more sense to put `eslint:recommended` at the beginning of the array? I can't think of a case where it would be overriding other extended plugins, but can think of cases where the opposite might be true.

Also, would it be possible to write an integration test or two for [`lib/config-initializer`](https://github.com/eslint/eslint/blob/master/lib/init/config-initializer) to assert that this works correctly?

**Comment by yeonjuan** [comment]
@kaicataldo 

While I write an integration test code, 
I realize that `eslint --init` doesn't ask for installing modules when I answered with **"Inspect your JavaScript file(s)"**(answers.source = auto)

Is it intended?

**Comment by kaicataldo** [comment]
Sorry I missed this! That seems like a bug to me. Can you make a separate issue for that?

**Comment by kaicataldo** [comment]
Thanks for contributing!

**Comment by yeonjuan** [comment]
> That seems like a bug to me. Can you make a separate issue for that?
@kaicataldo Sure!
