### PR TITLE
Fix: improve `newline-per-chained-call` message (fixes #6340)

### LINKED ISSUE #6340: Wrong output indentation in all messages if one massage has a long multiline quote
**What version of ESLint are you using?**

2.11.1

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```JSON
{
  "root": true,

  "extends": [
    "eslint:recommended",
    "airbnb-base"
  ],

  "parserOptions": {
    "ecmaVersion": 7,
    "sourceType": "script"
  },

  "env": {
    "browser": false,
    "es6": true,
    "node": true
  },

  "rules": {
    "arrow-parens": [2, "as-needed"],
    "eqeqeq": 2,
    "key-spacing": [2, { "beforeColon": false, "afterColon": true, "mode": "minimum" }],
    "no-console": 0,
    "no-eq-null": 2,
    "no-extra-parens": [2, "all"],
    "no-multi-spaces": 0,
    "no-unused-vars": 2,
    "no-use-before-define": [2, { "functions": false }],
    "quotes": [2, "single"],
    "spaced-comment": [2, "always", { "exceptions": ["/", "*"] }],
    "strict": [2, "global"],
    "unicode-bom": [2, "always"]
  }
}
```
**What did you do? Please include the actual source code causing the issue.**

```js
const http = require('http');

http.request({
  // Param
  // Param
  // Param
}).on('response', response => {
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
}).on('error', error => {
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
}).end();
```

**What did you expect to happen?**

An output with readable indentation and alignment.

**What actually happened? Please include the actual, raw output from ESLint.**

Compare with the output after the last error fixed:

### PR DESCRIPTION
**Pull request by mysticatea**
fixes #6340.

- Changed the message to `Expected line break before 'PropertyName'.`  
  - Property is shorter than object if it's chained.
  - The error locations are at properties, so it's more consistent.

### CODE REVIEW

File: lib/rules/newline-per-chained-call.js [hunk 1]
```diff
@@ -38,6 +38,19 @@ module.exports = {
...
 
+        /**
+         * Gets the property text of a given MemberExpression node.
+         * If the text is multiline, this returns only the first line.
+         *
+         * @param {ASTNode} node - A MemberExpression node to get.
+         * @returns {string} The property text of the node.
+         */
+        function getPropertyText(node) {
+            var prefix = node.computed ? "[" : ".";
```
Comment (platinumazure) [inline lib/rules/newline-per-chained-call.js]: Do we possibly want a suffix (at least for when the property name is single-like) as well?

File: tests/lib/rules/newline-per-chained-call.js [hunk 2]
```diff
@@ -53,56 +53,86 @@ ruleTester.run("newline-per-chained-call", rule, {
...
+            "    // Do something with error.",
+            "    // Do something with error.",
+            "    // Do something with error.",
+            "}).end();"
+        ].join("\n"),
+        errors: [{
+            message: "Expected line break before `.on`."
         }, {
-            message: "Expected line break after `m1().m2\\n.m3().m4().m5().m6()`."
+            message: "Expected line break before `.end`."
```
Comment (platinumazure) [inline tests/lib/rules/newline-per-chained-call.js]: Might be good to add some test cases for computed properties.

**Comment by mysticatea** [comment]
Thank you for the review!

I updated this.

- Added suffix for a single line computed property.
- Added a test for computed properties.

File: lib/rules/newline-per-chained-call.js [hunk 3]
```diff
@@ -38,6 +38,21 @@ module.exports = {
...
+            var lines = sourceCode.getText(node.property).split(/\r\n|\r|\n/g);
+            var surfix = node.computed && lines.length === 1 ? "]" : "";
```
Comment (nzakas) [inline lib/rules/newline-per-chained-call.js]: surfix -> suffix

Comment (mysticatea) [inline lib/rules/newline-per-chained-call.js]: Thank you, I updated it.

**Comment by nzakas** [comment]
LGTM
