### PR TITLE
fix: ignore vars with non-identifier references in no-useless-assignment

### LINKED ISSUE #19160: Change Request: `no-useless-assignment` should check only references created by Identifier
### ESLint version

v9.x

### What problem do you want to solve?

I propose that ESLint rules that use scope-manager only handle `Reference`s generated by `Identifier`.

ESLint does not assume any semantics for jsx nodes (reference, scope..).
This is not a problem when using ESLint's scope manager, but when using the custom scope manager in a custom parser, the ESLint core rules that rely on `Reference` don't work well. see https://github.com/typescript-eslint/typescript-eslint/issues/10219#issuecomment-2492086613

It is possible that `Reference`s are generated by the custom parser with a variety of node types, so I propose that ESLint core only handles references generated from Identifiers in the rules.

### What do you think is the correct solution?

https://github.com/eslint/eslint/blob/main/lib/rules/no-useless-assignment.js#L311-L313

```js
const readReferences = targetAssignment.variable.references.filter(reference => reference.isRead() && reference.identifier.type ==="Identifier'');
```

Or, it may be better to wrap the scope-manager used by the core rules so that it only handles references whose node type is Identifier.

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by yeonjuan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain: https://github.com/eslint/eslint/issues/19160

#### What changes did you make? (Give an overview)
Fixes #19160
Change no-useless-assignment to only check for references created by Identifier.

#### Is there anything you'd like reviewers to focus on?

https://github.com/eslint/eslint/issues/19160#issuecomment-2503122368

### CODE REVIEW

File: lib/rules/no-useless-assignment.js [hunk 1]
```diff
@@ -309,7 +309,7 @@ module.exports = {
                 }
 
 
-                const readReferences = targetAssignment.variable.references.filter(reference => reference.isRead());
+                const readReferences = targetAssignment.variable.references.filter(reference => reference.isRead() && reference.identifier.type === "Identifier");
```
Comment (mdjermanovic) [inline lib/rules/no-useless-assignment.js:312]: Would this work for example from https://github.com/eslint/eslint/issues/19160#issuecomment-2499928852? I think it would be better to just skip checking anything for a variable that has at least one non-identifier reference.

Comment (yeonjuan) [reply lib/rules/no-useless-assignment.js]: @mdjermanovic  sure 218922e

File: tests/lib/rules/no-useless-assignment.js [hunk 2]
```diff
@@ -353,7 +369,39 @@ ruleTester.run("no-useless-assignment", rule, {
...
+                    }
+                }
+            }
+        },
+        {
+            code: `/*eslint test/jsx:1*/
+                function App() {
+                    let A = "";
+                    foo(A);
+                    a = "A";
```
Comment (mdjermanovic) [inline tests/lib/rules/no-useless-assignment.js:393]: This test is passing without the code change. Should this line maybe be this:

```suggestion
                    A = "a";
```

File: tests/lib/rules/no-useless-assignment.js [hunk 3]
```diff
@@ -353,7 +369,39 @@ ruleTester.run("no-useless-assignment", rule, {
...
+                }
+            `,
+            languageOptions: {
+                parserOptions: {
+                    ecmaFeatures: {
+                        jsx: true
+                    }
+                }
+            }
+        }
```
Comment (mdjermanovic) [inline tests/lib/rules/no-useless-assignment.js:404]:
```suggestion
        },
        {
            code: `/*eslint test/jsx:1*/
                function App() {
                    let A = "a";
                    A = "b";
                    A = "c";
                    foo(A);
                    return <A/>;
                }
            `,
            languageOptions: {
                parserOptions: {
                    ecmaFeatures: {
                        jsx: true
                    }
                }
            }
        }
```

One more test to confirm that these variables are entirely ignored.

File: tests/lib/rules/no-useless-assignment.js (hunk 2 above)
Comment (yeonjuan) [reply tests/lib/rules/no-useless-assignment.js]: oops. sure! Thank you.  I made the change. https://github.com/eslint/eslint/pull/19200/commits/41e2e34ef84648f8ffff0c5f31e8299c15089888

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Leaving it open for couple days if anyone else would like to take a look.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!
