### PR TITLE
Fix: no-trailing-spaces autofix to account for blank lines (fixes #3912)

### LINKED ISSUE #3912: no-trailing-spaces: Auto fix issue
**Eslint:** 1.5.1
**Parser:** Default

**Code:**
```js
"\n" +
"measAr.push(\"<dl></dl>\",  \n" +
"         \" </dt><dd class ='pta-res'>\");"
```

**Current Fix Output:**
```js
"\n" +
"measAr.push(\"<dl></dl>\" \n" +
"         \" </dt><dd class ='pta-res'>\");"
```

**Expected Fix Output:**
```js
"\n" +
"measAr.push(\"<dl></dl>\",\n" +
"         \" </dt><dd class ='pta-res'>\");"
```

**Issue:** On line 2, it got rid of the comma at the end. Which it shouldn't.

Confirmed: this is only happening when you have a empty line on top of the issue line.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26898895-no-trailing-spaces-auto-fix-issue?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

File: tests/lib/rules/no-trailing-spaces.js [hunk 1]
```diff
@@ -66,6 +66,32 @@ ruleTester.run("no-trailing-spaces", rule, {
 
     invalid: [
         {
+            code:
+            "\n" +
```
Comment (nzakas) [inline tests/lib/rules/no-trailing-spaces.js]: Can you move output next to code?

Comment (gyandeeps) [inline tests/lib/rules/no-trailing-spaces.js]: Sorry, forgot again.

Comment (gyandeeps) [inline tests/lib/rules/no-trailing-spaces.js]: Done.
