### PR TITLE
Fix: Missing undeclared variables in JSX (fixes #1676)

### LINKED ISSUE #1676: no-undef misses JSX references
The no-undef rules misses the references to undefined variables in JSX.

Examples:

```jsx
React.render(<UnknownApp />);
```
Should report `'UnknownApp' is not defined`

```jsx
React.render(<div className={unknownClass} />);
```
Should report `'unknownClass' is not defined`

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7874622-no-undef-misses-jsx-references?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by yannickcr**
My fix attempt for #1676.

For the JSXExpressionContainer and JSXOpeningElement nodes, I go through the upper scopes (as in my previous fix #1675) and get the declared variables, then I compare them to the current node name. If I cannot find a matching variable the node is reported as not defined.

For the JSXOpeningElement nodes, [the tags supported by React](https://github.com/facebook/react/blob/master/docs/docs/ref-04-tags-and-attributes.md#supported-tags) are whitelisted to not be marked as not defined.

The report messages were moved in the `NOT_DEFINED_MESSAGE` and `READ_ONLY_MESSAGE` variables to avoid the duplication of the string.

I also added 6 additional tests to confirm the fix.

### CODE REVIEW

**Comment by vegetableman** [comment]
React is going to deprecate limited support for tags. Check this out:- http://facebook.github.io/react/blog/2014/10/16/react-v0.12-rc1.html. So, you could just return if a node starts with a lower-case letter or contains a dash.

**Comment by nzakas** [comment]
Nice, thanks @vegetableman.

File: lib/rules/no-undef.js [hunk 1]
```diff
@@ -66,12 +109,27 @@ module.exports = function(context) {
...
+                    context.report(ref.identifier, NOT_DEFINED_MESSAGE, { name: name });
                 } else if (ref.isWrite() && variable.writeable === false) {
-                    context.report(ref.identifier, "'{{name}}' is read only.", { name: name });
+                    context.report(ref.identifier, READ_ONLY_MESSAGE, { name: name });
                 }
             });
+        },
+
+        "JSXExpressionContainer": function(node) {
+            if (node.expression.type !== "Identifier") {
```
Comment (nzakas) [inline lib/rules/no-undef.js]: We don't do early returns for single conditions. This should be:

```js
if (node.expresion.type === "Identifier") {
    checkIdentifierInJSX(node.expression);
}
```

File: lib/rules/no-undef.js [hunk 2]
```diff
@@ -49,8 +49,51 @@ function hasTypeOfOperator(node) {
...
+     */
+    function checkIdentifierInJSX(node) {
+        var scope = context.getScope(),
+            variables = scope.variables,
+            i,
+            len;
+
+        while (scope.type !== "global") {
+            scope = scope.upper;
+            variables = [].concat.apply(scope.variables, variables);
```
Comment (nzakas) [inline lib/rules/no-undef.js]: You can just do `scope.variables.concat(variables)` here.

File: lib/rules/no-undef.js [hunk 3]
```diff
@@ -49,8 +49,51 @@ function hasTypeOfOperator(node) {
...
+    "radialGradient", "rect", "stop", "svg", "text", "tspan"
+];
+
 module.exports = function(context) {
 
+    var NOT_DEFINED_MESSAGE = "'{{name}}' is not defined.",
+        READ_ONLY_MESSAGE = "'{{name}}' is read only.";
+
+    /**
+     * @param {ASTNode} node - Identifier or JSXIdentifier node
```
Comment (nzakas) [inline lib/rules/no-undef.js]: Please add a JSDoc description for the function.

**Comment by nzakas** [comment]
This will probably hold us over until I can figure out some better way. Constantly searching for each variable through all scopes is going to be a performance sink in large files, so it's definitely not a long-term solution.

**Comment by yannickcr** [comment]
@vegetableman Thanks. I now use the same method as React to check the tag name.
@nzakas I made the requested changes. I'm agree it is not a clean fix, I hope we could later find a better solution with escope.

**Comment by nzakas** [comment]
Looks good. Thanks!
