### PR TITLE
fix: skip processor code blocks that match only universal patterns

### LINKED ISSUE #15949: Bug: Ignores don't apply to processor blocks
### Environment

Node version: v18.2.0
npm version: v8.9.0
Local ESLint version: v8.16.0 (Currently used)
Global ESLint version: v8.16.0
Operating System: darwin 21.5.0

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```json
{
    "plugins": ["markdown"],
    "extends": ["eslint:recommended"],
    "overrides": [
        {
            "files": ["*.jsx"],
            "parserOptions": {
                "jsx": true
            }
        },
        {
            "files": ["**/*.md"],
            "processor": "markdown/markdown"
        }
    ]
}
```

```
# .eslintignore
**/*.md/*.jsx
```
</details>

````md
```js
This is not valid JS syntax!
```

```jsx
This is not valid JSX syntax!
```
````

For a more complete demo, see https://github.com/jeremymeng/eslint-markdown-repo.

<details>
<summary>As part of an attempted fix in #15813, I put together a set of `CLIEngine` tests, and I've shared the diff here.</summary>

```diff
diff --git tests/lib/cli-engine/cli-engine.js tests/lib/cli-engine/cli-engine.js
index 2d2d8ba98..e7a69b85c 100644
--- tests/lib/cli-engine/cli-engine.js
+++ tests/lib/cli-engine/cli-engine.js
@@ -5394,6 +5394,117 @@ describe("CLIEngine", () => {
     describe("with ignorePatterns config", () => {
         const root = getFixturePath("cli-engine/ignore-patterns");
 
+        describe("applies to processor code blocks", () => {
+
+            const { prepare, cleanup, getPath } = createCustomTeardown({
+                cwd: root,
+                files: {
+                    ".eslintrc.json": {
+                        plugins: ["test-processor"],
+                        rules: {
+                            "no-console": 2
+                        },
+
+                        // Add an override so that .jsx files and processor blocks also get linted.
+                        overrides: [
+                            {
+                                files: "*.jsx",
+                                parserOptions: {
+                                    jsx: true
+                                }
+                            }
+                        ]
+                    },
+                    "foo.txt": [
+                        "js:console.log(42);",
+                        "jsx:console.log(42);"
+                    ].join("\n")
+                }
+            });
+
+            const testProcessor = {
+                processors: {
+                    ".txt": {
+                        preprocess(text) {
+                            return text.split("\n").map((line, index) => {
+                                const [syntax, code] = line.split(":");
+
+                                return {
+                                    filename: `${index}.${syntax}`,
+                                    text: code
+                                };
+                            });
+                        },
+                        postprocess(allMessages) {
+                            return allMessages.flatMap(
+                                (messages, index) =>
+                                    messages.map(message => ({
+                                        ...message,
+                                        line: index + 1
+                                    }))
+                            );
+                        }
+                    }
+                }
+            };
+
+            beforeEach(prepare);
+            afterEach(cleanup);
+
+            it("normally lints both blocks", () => {
+                const engine = new CLIEngine({
+                    cwd: getPath()
+                }, {
+                    preloadedPlugins: {
+                        "test-processor": testProcessor
+                    }
+                });
+
+                const report = engine.executeOnFiles(["foo.txt"]);
+
+                assert.strictEqual(report.results.length, 1);
+                assert.strictEqual(report.results[0].messages.length, 2);
+                assert.strictEqual(report.results[0].messages[0].line, 1);
+                assert.strictEqual(report.results[0].messages[1].line, 2);
+            });
+
+            it("when ignoring all .js files", () => {
+                const engine = new CLIEngine({
+                    cwd: getPath(),
+                    ignorePattern: "**/*.js"
+                }, {
+                    preloadedPlugins: {
+                        "test-processor": testProcessor
+                    }
+                });
+
+                const report = engine.executeOnFiles(["foo.txt"]);
+
+                // The .js block on line 1 should be ignored. This error is on the .jsx block on line 2.
+                assert.strictEqual(report.results.length, 1);
+                assert.strictEqual(report.results[0].messages.length, 1);
+                assert.strictEqual(report.results[0].messages[0].line, 2);
+            });
+
+            it("when ignoring .js blocks inside .txt files", () => {
+                const engine = new CLIEngine({
+                    cwd: getPath(),
+                    ignorePattern: "**/*.txt/*.js"
+                }, {
+                    preloadedPlugins: {
+                        "test-processor": testProcessor
+                    }
+                });
+
+                const report = engine.executeOnFiles(["foo.txt"]);
+
+                // The .js block on line 1 should be ignored. This error is on the .jsx block on line 2.
+                assert.strictEqual(report.results.length, 1);
+                assert.strictEqual(report.results[0].messages.length, 1);
+                assert.strictEqual(report.results[0].messages[0].line, 2);
+            });
+        });
+
         describe("ignorePatterns can add an ignore pattern ('foo.js').", () => {
 
             const { prepare, cleanup, getPath } = createCustomTeardown({
```
</details>

### What did you expect to happen?

A code block with a virtual filenames like `docs/example.md/0_0.jsx` should be skipped by an ignore pattern like `**/*.md/*.jsx`.

All three tests should pass.

### What actually happened?

Both the `js` and the `jsx` code blocks get linted, throwing syntax errors.

The latter two tests fail because code blocks that match ignore patterns were not ignored.

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

This was originally reported in https://github.com/eslint/eslint-plugin-markdown/issues/201. I attempted a fix in https://github.com/eslint/eslint/pull/15813, but we didn't want to make any changes to `CLIEngine`. I'm opening this issue so that we can close that PR and track the fix here instead.

I filed this as a bug and have been using the word "fix" because I don't believe this was ever an intentional behavior. Based on mdjermanovic's research in https://github.com/eslint/eslint/pull/15813#issuecomment-1121135716, the design for virtual filenames didn't contemplate how they might interact with ignore patterns. However, there's concern that this would be a breaking change. That's discussed in https://github.com/eslint/eslint/pull/15813#issuecomment-1121135716. If we release this as part of `FlatESLint`, that removes backwards compatibility as a concern, and it becomes a behavior difference between `.eslintrc.js` and `eslint.config.js`.

### LINKED ISSUE #18493: Bug: `No matching configuration found` warning for code block matched only by non-universal patterns
### Environment

Node version: v20.12.0
npm version: 10.5.0
Local ESLint version: v9.3.0
Global ESLint version: no
Operating System: windows

### What parser are you using?

Default (Espree)

### What did you do?

I wanted to make a repro with `eslint-plugin-markdown`, but since [this warning](https://github.com/eslint/eslint/blob/389744be255717c507fafc158746e579ac08d77e/lib/linter/linter.js#L1986-L1993) has `line: 0` (which might be another bug), `eslint-plugin-markdown` filters it out as out-of-range. So I made a simple processor that assumes that the entire markdown file is one ` ```ts ` code block.

```js
// eslint.config.js
export default [
  {
      plugins: {
          "my-plugin": {
              processors: {
                  "my-processor": {

                      // dummy processor that assumes that the whole content of a file is a single ```ts code block 
                      preprocess(text) {
                          const lines = text.split("\n");
                          return [{
                              filename: "foo.ts",
                              text: lines.slice(1, -1).join("\n")
                          }]
                      },

                      // just increment lines to adjust for the first ```ts line
                      postprocess(messages) {
                          const retv = messages[0]; // there's always exactly 1 code block

                          retv.forEach(message => {
                              message.line++
                              message.endLine++; 
                          });

                          return retv;
                      }
                  }
              }
          }
      }
  },
  {
      files: ["**/*.md"],
      processor: "my-plugin/my-processor"
  },
  {
      files: ["**/*"],
      rules: {
          "no-undef": 2
      }
  }
];

```

`test.md`:

````md
```ts
foo
```
````

### What did you expect to happen?

Since the `.ts` virtual file doesn't have an explicit match in the config, I'd expect it to be silently ignored, so at the end I'd expect no lint errors or warnings.

### What actually happened?

```
C:\projects\tmp\tmp\test.md
  1:0  warning  No matching configuration found for C:\projects\tmp\tmp\test.md\0_foo.ts

✖ 1 problem (0 errors, 1 warning)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-hqxgng?file=eslint.config.js

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

We found this problem while discussing https://github.com/eslint/rewrite/pull/7.

I think we could just replace the following line with `return configs.getConfig(blockFilename) !== void 0;`

https://github.com/eslint/eslint/blob/389744be255717c507fafc158746e579ac08d77e/lib/eslint/eslint.js#L512

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #18493

Closes #15949

#### What changes did you make? (Give an overview)

* Fixed #18493 by changing the code block filter condition to `configs.getConfig(blockFilename) !== void 0`.
* Updated documentation and added tests for #15949.

### CODE REVIEW

File: tests/lib/eslint/eslint.js [hunk 1]
```diff
@@ -3761,6 +3767,178 @@ describe("ESLint", () => {
...
+                    assert.strictEqual(result.messages[2].ruleId, "no-undef");
+                    assert.match(result.messages[2].message, /foo_cjs/u);
+                    assert.strictEqual(result.messages[2].line, 10);
+                    assert.strictEqual(result.messages[3].ruleId, "no-undef");
+                    assert.match(result.messages[3].message, /foo_mjs/u);
+                    assert.strictEqual(result.messages[3].line, 14);
+                });
+
+                // https://github.com/eslint/eslint/issues/18493
+                it("should silently skip virtual files that match only universal patterns", async () => {
```
Comment (mdjermanovic) [inline tests/lib/eslint/eslint.js:3856]: Only this test was failing before the code change. The others represent behavior that was valid both before and after the change.

**Review by nzakas — APPROVED** [review]
LGTM. Waiting a couple days before merging to give others a chance to review.

**Comment by nzakas** [comment]
Just re-kicked-off the browser test to see if it was just flaky.

**Review by fasttime — APPROVED** [review]
LGTM. Kudos for fixing two bugs with one line 👍🏻

I'm going to merge this PR now since it has another approval and has been open for three days.
