### PR TITLE
Fix: Don't require commas after rest properties (fixes #7297)

### LINKED ISSUE #7297: `comma-dangle` incorrectly requires commas after rest properties
**What rule do you want to change?**
comma-dangle

**Does this change cause the rule to produce more or fewer warnings?**
I guess it depends. But probably more warnings.

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option, something like `{forbidAfterRest: true}`

**Please provide some example code that this change will affect:**
```js
const {
  x,
  y,
  ...z
} = foo;
```

**What does the rule currently do for this code?**
When using this rule with string option `"always-multiline"`, it will warn about missing trailing comma after `...z`.

**What will the rule do after it's changed?**
No trailing comma after `...z` will be correct, and a trailing comma will be incorrect.

**Motivation:**
Seems like the [spec](http://sebmarkbage.github.io/ecmascript-rest-spread/) doesn't even allow that kind of trailing comma.

[Babel's Babylon v6.11.3](https://github.com/babel/babylon/releases/tag/v6.11.3) went so far as to consider that as syntax error.
> The rationale for this is that the use case for trailing comma is that you can add something at the end without affecting the line above. Since a RestProperty always has to be the last property it doesn't make sense.

[Babylon v6.11.4](https://github.com/babel/babylon/releases/tag/v6.11.4) temporary rolled back that behavior.

So for now I guess is up to the user to choose if that trailing comma is incorrect or not with the new `forbidAfterRest` option.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

See https://github.com/eslint/eslint/issues/7297

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- (n/a) I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**

This fixes `comma-dangle` to not require trailing commas after rest properties with `experimentalObjectRestSpread` enabled, since this is a SyntaxError according to the [spec](https://sebmarkbage.github.io/ecmascript-rest-spread/).

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: lib/rules/comma-dangle.js [hunk 1]
```diff
@@ -13,14 +13,17 @@ const lodash = require("lodash");
...
  *
  * @param {ASTNode} node - A node to check.
  * @param {ASTNode} lastItem - The node of the last element in the given node.
  * @returns {boolean} `true` if a trailing comma is allowed.
  */
 function isTrailingCommaAllowed(node, lastItem) {
-    return node.type !== "ArrayPattern" || lastItem.type !== "RestElement";
+    return !(
+        (node.type === "ArrayPattern" && lastItem.type === "RestElement") ||
+        (node.type === "ObjectPattern" && (lastItem.type === "RestProperty" || lastItem.type === "ExperimentalRestProperty"))
```
Comment (kaicataldo) [inline lib/rules/comma-dangle.js]: Do we have nodes with the "RestProperty" type in Espree? Or is this for the benefit of other parsers?

Comment (not-an-aardvark) [inline lib/rules/comma-dangle.js]: I haven't seen any `RestProperty` nodes. I put it there assuming that the name will eventually be `RestProperty` once it's no longer experimental.

Comment (kaicataldo) [inline lib/rules/comma-dangle.js]: I'd like to hear others' opinions on this. My preference would be not to do this "just in case" and to add it in when that becomes a reality (or, hopefully, remove the support for "ExperimentalRestProperty" and add in "RestProperty"). If this helps with other parsers that support this syntax (since we do, even though it's still stage 3), then I'm not opposed to it.

Comment (not-an-aardvark) [inline lib/rules/comma-dangle.js]: Incidentally, why does espree add the `Experimental` prefix? I can understand the need to mark it as experimental, but I would think that is already accomplished by naming the option `experimentalObjectRestSpread`. When the node name eventually does change, it will almost certainly break downstream users, and that seems unnecessary to me. (Each node can only have one type, so this isn't like CSS vendor prefixes where the experimental and final versions can be supported simultaneously.)

Comment (hzoo) [inline lib/rules/comma-dangle.js]: `RestProperty` is used in Babel and it was added to estree as experimental as well https://github.com/estree/estree/commit/6e4d212e6387f0633ee7188600f2b063f93fc50e

Comment (nzakas) [inline lib/rules/comma-dangle.js]: Espree uses `ExperimentalRestProperty` because the feature was experimental. If there was a change before the proposal was fully added to the specification (which just happened), we had the ability to ensure that rules could target both the old representation and the official versions (`RestProperty`). I didn't want people relying on an experimental node without knowing that they were doing so.

When we fully implement the spec, we'll use `RestProperty`.
