### PR TITLE
Fix: invalid autofix in function-call-argument-newline (fixes #12454)

### LINKED ISSUE #12454: function-call-argument-newline invalid autofix with a line comment
**Tell us about your environment**

* **ESLint Version:**  6.5.1
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 2015,
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGZ1bmN0aW9uLWNhbGwtYXJndW1lbnQtbmV3bGluZTogW1wiZXJyb3JcIiwgXCJuZXZlclwiXSAqL1xuXG5mKGEsIC8vIGNvbW1lbnRcbiAgYik7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

```js
/* eslint function-call-argument-newline: ["error", "never"] */

f(a, // comment
  b);
```

```bash
eslint index.js --fix
```

**What did you expect to happen?**

I'm not sure, maybe an error without autofix.

**What actually happened? Please include the actual, raw output from ESLint.**

```js
/* eslint function-call-argument-newline: ["error", "never"] */

f(a, // comment b);
```

**Are you willing to submit a pull request to fix this bug?**

Yes. #12280 should be probably merged first.

Autofix also doesn't work quite well when a comment or the comma `,` is on the same line with the argument that shouldn't have a linebreak before - [Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGZ1bmN0aW9uLWNhbGwtYXJndW1lbnQtbmV3bGluZTogW1wiZXJyb3JcIiwgXCJuZXZlclwiXSAqL1xuXG5mKGEgXG4sICBiKTtcblxuZihhIFxuICAsYik7XG5cbmYoYSxcbiAgLyoqLyAgIGIpOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

The reported locations are wrong and autofix just removes whitespace (or even inserts a new space in some cases), but the linebreak and the error are still there.

Maybe we could do here the same as with `array-element-newline` - [Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGFycmF5LWVsZW1lbnQtbmV3bGluZTogW1wiZXJyb3JcIiwgXCJuZXZlclwiXSAqL1xuXG5bYSwgLy8gY29tbWVudFxuICBiXTtcblxuW2EsIC8qKi9cbiAgYl07XG5cblthIC8qKi9cbiAgLGJdO1xuXG5bYSxcbiAgLyoqLyAgIGJdO1xuXG5bYSBcbiwgIGJdO1xuXG5bYSBcbiAgLGJdO1xuXG5bYSwgXG4gIGJdO1xuXG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

From this demo, it looks like the logic is as the following:

* If there is a comment anywhere between two elements, just report error without any autofixes.
* If there are no comments, then fix the code. If the comma is on the same line as the second element, remove the range between the first element and the comma, instead of between the comma and the second element.

Reported locations are also not correct.

### PR DESCRIPTION
**Pull request by yeonjuan**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

This is a PR for #12454
- Add checking whether there is a line comment(`// comment`) before currentArgToken

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by platinumazure** [comment]
@kaicataldo It looks like there are some tests with the "consistent" option which show that the autofix works: https://github.com/eslint/eslint/blob/d679dd89cfc672252eee3396c506dd45ed28f1d5/tests/lib/rules/function-call-argument-newline.js#L423-L450

It may be a good idea to add more tests for other options, but could that potentially be in a separate PR?

**Comment by kaicataldo** [comment]
Ah, I missed that. Thanks for pointing that out!

File: tests/lib/rules/function-call-argument-newline.js [hunk 1]
```diff
@@ -390,6 +390,21 @@ ruleTester.run("function-call-argument-newline", rule, {
                 }
             ]
         },
+        {
+            code: "fn(a,/* commeent */\nb)",
```
Comment (kaicataldo) [inline tests/lib/rules/function-call-argument-newline.js]: Not a blocker, but I’m assuming the intention was `comment` rather than `commeent` here 😄

**Comment by yeonjuan** [comment]
@kaicataldo oh. it's typo. I'll fix it

File: tests/lib/rules/function-call-argument-newline.js (hunk 1 above)
Comment (yeonjuan) [reply tests/lib/rules/function-call-argument-newline.js]: @kaicataldo Oh it's type. I fixed it. Thanks.
