### PR TITLE
Fix: arrow-parens no reporting for comments inside (fixes #12995)

### LINKED ISSUE #12995: Allow JSDoc make arrow parens needed
**What rule do you want to change?**

    arrow-parens: "as-needed"

**Does this change cause the rule to produce more or fewer warnings?**

Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**

Prefer new option, make default should be fine too.

**Please provide some example code that this change will affect:**

```js
/*eslint arrow-parens: ["error", "as-needed"]*/

const f = (/** @type {number} */a) => a + a;
f(42);
```

[Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYXJyb3ctcGFyZW5zOiBbXCJlcnJvclwiLCBcImFzLW5lZWRlZFwiXSovXG5cbmNvbnN0IGYgPSAoLyoqIEB0eXBlIHtudW1iZXJ9ICovYSkgPT4gYSArIGE7XG5mKDQyKTtcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOjIsImZvci1kaXJlY3Rpb24iOjIsImdldHRlci1yZXR1cm4iOjIsIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOjIsIm5vLWNhc2UtZGVjbGFyYXRpb25zIjoyLCJuby1jbGFzcy1hc3NpZ24iOjIsIm5vLWNvbXBhcmUtbmVnLXplcm8iOjIsIm5vLWNvbmQtYXNzaWduIjoyLCJuby1jb25zdC1hc3NpZ24iOjIsIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6Miwibm8tY29udHJvbC1yZWdleCI6Miwibm8tZGVidWdnZXIiOjIsIm5vLWRlbGV0ZS12YXIiOjIsIm5vLWR1cGUtYXJncyI6Miwibm8tZHVwZS1jbGFzcy1tZW1iZXJzIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtY2F0Y2giOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJuby13aXRoIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6e319fQ==)

**What does the rule currently do for this code?**

    3:33 - Unexpected parentheses around single function argument.

**What will the rule do after it's changed?**

No error.

**Are you willing to submit a pull request to implement this change?**

Not.

----

My IDE seems do not know type of variable `a` in `(/** @type {number} */a) => a` if the braces are omitted. I want to make JSDoc a exception of validating `arrow-parens: "as-needed"`.

### PR DESCRIPTION
**Pull request by anikethsaha**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
**rule: `arrow-parens`**

no reporting when there are comments inside params. 
applicable for `as-needed` option for 

Example of valid code [(these are invalid in master as of now)](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYXJyb3ctcGFyZW5zOiBbXCJlcnJvclwiLCBcImFzLW5lZWRlZFwiXSovXG5cblxuY29uc3QgZiA9ICgvKiogQHR5cGUge251bWJlcn0gKi9hLyoqaGVsbG8qLykgPT4gYSArIGE7XG5jb25zdCBmZiA9IChhIC8qKi8pID0+IGFcbmNvbnN0IGZmZiA9ICgvL1xuYSkgPT4gYSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

```js
/*eslint arrow-parens: ["error", "as-needed"]*/


const f = (/** @type {number} */a/**hello*/) => a + a;
const ff = (a /**/) => a
const fff = (//
a) => a

```
These are valid by default in `master` as well

#### Is there anything you'd like reviewers to focus on?
None

### CODE REVIEW

File: lib/rules/arrow-parens.js [hunk 1]
```diff
@@ -105,6 +105,14 @@ module.exports = {
                 ], `${shouldAddSpaceForAsync ? " " : ""}${paramToken.value}`);
             }
 
+            if (
+                node.params.length === 1 &&
+                (sourceCode.getCommentsBefore(node.params[0]).length > 0 ||
+                sourceCode.getCommentsAfter(node.params[0]).length > 0)
+            ) {
+                return;
+            }
```
Comment (mdjermanovic) [inline lib/rules/arrow-parens.js:114]: It looks like this would also wrongly prevent some errors for `"always"`:

```js
/* eslint arrow-parens: ["error", "always"] */

var foo = /**/ a => b;

var bar = a /**/ =>  b;
```

Also, there is an `as-needed` edge case that isn't covered:

```js
/* eslint arrow-parens: ["error", "as-needed"] */

var foo = (a,/**/) => b;
```

Comment (anikethsaha) [reply lib/rules/arrow-parens.js:114]: > It looks like this would also wrongly prevent some errors for `"always"`:
> 
> ```js
> /* eslint arrow-parens: ["error", "always"] */
> 
> var foo = /**/ a => b;
> 
> var bar = a /**/ =>  b;
> ```

let me check them

> ```js
> /* eslint arrow-parens: ["error", "as-needed"] */
> 
> var foo = (a,/**/) => b;
> ```

I will add test case for this. but is will same as without the `,` cause I think the `params` length is still 1 here

Comment (anikethsaha) [reply lib/rules/arrow-parens.js]: done

**Comment by anikethsaha** [comment]
@mdjermanovic I added a check for opening parent before first token for having the false positive which you mentioned

> ```js
> /* eslint arrow-parens: ["error", "always"] */
> 
> var foo = /**/ a => b;
> ```


the other way for this was to check if the option is `as-needed` or not.

Let me know if the current change is fine  👍

File: docs/rules/arrow-parens.md [hunk 2]
```diff
@@ -177,6 +178,7 @@ a.then(foo => { if (true) {} });
 (a = 10) => a;
 ([a, b]) => a;
 ({a, b}) => a;
+const f = /** @type {number} */a => a + a;
```
Comment (mdjermanovic) [inline docs/rules/arrow-parens.md:181]: I think these examples don't reflect this change. We should add some correct examples with parens and comment inside.

File: docs/rules/arrow-parens.md [hunk 3]
```diff
@@ -177,6 +178,7 @@ a.then(foo => { if (true) {} });
 (a = 10) => a;
 ([a, b]) => a;
 ({a, b}) => a;
+const f = (/** @type {number} */a) => a + a;
```
Comment (mdjermanovic) [inline docs/rules/arrow-parens.md:181]: :+1: 

It might be nice to also add a couple of `correct` examples with random comments, to show that we're not checking jsdoc, e.g. these two:

```js
const g = (/* comment */ a) => a + a;
const h = (a /* comment */) => a + a;
```

File: lib/rules/arrow-parens.js [hunk 4]
```diff
@@ -105,10 +105,27 @@ module.exports = {
                 ], `${shouldAddSpaceForAsync ? " " : ""}${paramToken.value}`);
             }
 
+            /**
+             * Checks whether there are comments inside the params or not.
+             * @returns {boolean} `true` if there are comments inside of parens, else `false`
+             */
+            function hasCommentsInParens() {
+                if (firstTokenOfParam.type === "Punctuator" && firstTokenOfParam.value === "(") {
```
Comment (mdjermanovic) [inline lib/rules/arrow-parens.js:113]: Can we use `astUtils.isOpeningParenToken` instead?

File: docs/rules/arrow-parens.md [hunk 5]
```diff
@@ -159,6 +159,9 @@ Examples of **incorrect** code for this rule with the `"as-needed"` option:
 a.then((foo) => {});
 a.then((foo) => a);
 a((foo) => { if (true) {} });
+const f = /** @type {number} */(a) => a + a;
+const g = (/* comment */ a) => a + a;
+const h = (a /* comment */) => a + a;
```
Comment (mdjermanovic) [inline docs/rules/arrow-parens.md:164]: These two should be in `correct`

Comment (anikethsaha) [reply docs/rules/arrow-parens.md:164]: opz,

**Comment by kaicataldo** [comment]
Thank you!
