### PR TITLE
fix: Prevent false positives with no-constant-condition

### LINKED ISSUE #15467: Bug: False positives with no-constant-condition
### Environment

Online Playground

### What parser are you using?

Default (Espree)

### What did you do?

```js
if(`${[...a]}`) {
  //
};

if(`${[{toString: () => a}]}`) {
  //
};


if("" + {toString: () => a}) {
  //
}

if("" + [{toString: () => a}]) {
  //
};

if(+[{toString: () => a}]) {
  //
};



```

[Playground Link](https://eslint.org/demo#eyJ0ZXh0IjoiXG5pZihgJHtbLi4uYV19YCkge1xuICAvL1xufTtcblxuaWYoYCR7W3t0b1N0cmluZzogKCkgPT4gYX1dfWApIHtcbiAgLy9cbn07XG5cblxuaWYoXCJcIiArIHt0b1N0cmluZzogKCkgPT4gYX0pIHtcbiAgLy9cbn1cblxuaWYoXCJcIiArIFt7dG9TdHJpbmc6ICgpID0+IGF9XSkge1xuICAvL1xufTtcblxuaWYoK1t7dG9TdHJpbmc6ICgpID0+IGF9XSkge1xuICAvL1xufTtcblxuXG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLWNvbnN0YW50LWNvbmRpdGlvbiI6Mn0sImVudiI6e319fQ==)

### What did you expect to happen?

No errors

### What actually happened?

Each condition triggers `no-constant-condition`

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I was looking into the implementation of the `isConstant` function in `no-constant-condition` as part of #15296. Specifically I was trying to understand the meaning of the case where the `inBooleanPosition` flag is set to false.

I realized that the reason I was having such a hard time understanding it is that it's not really sound. For example, we call `isConstant` with `inBooleanPosition = false` in cases where values are going to get coerced into numbers or strings and we want to know if the resulting string/number will have constant truthiness. However, the checks are not sufficient to actually validate that.

I think that currently isConstant with inBooleanPosition set to false is supposed to check if a value has constant truthiness, even when that value is being first coerced to some other type (string/number/...). I'm not sure that's a function which is feasible to write correctly. Instead, I suspect we will want individual functions that handle the string and number cases, or something along those lines.

Rather than trying to solve this by adding more special cases to `isConstant` (which is already rather hard to grock), I wonder if we could break it up into a collection of simpler helper functions which check for more explicit cases.

### PR DESCRIPTION
**Pull request by captbaritone**
Fixes #15467 by defining `isConstant` with `inBooleanPosition` set to `false` as meaning:

> For both string and number, if coerced to that type, the value will be constant.

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))

#### What changes did you make? (Give an overview)

Make `no-constant-condition` more correct. See #15467 for more information.

#### Is there anything you'd like reviewers to focus on?

Would ESLint treat this as a breaking change? It will remove some false positives, but also -- in a few rare cases -- introduce a few false negatives.

### CODE REVIEW

File: tests/lib/rules/no-constant-condition.js [hunk 1]
```diff
@@ -262,8 +277,6 @@ ruleTester.run("no-constant-condition", rule, {
 
         // #5228 , typeof conditions
         { code: "if(typeof x){}", errors: [{ messageId: "unexpected", type: "UnaryExpression" }] },
-        { code: "if(`${typeof x}`){}", errors: [{ messageId: "unexpected", type: "TemplateLiteral" }] },
-        { code: "if(`${''}${typeof x}`){}", errors: [{ messageId: "unexpected", type: "TemplateLiteral" }] },
```
Comment (captbaritone) [inline tests/lib/rules/no-constant-condition.js:266]: These are true errors that we won't catch any more.

File: tests/lib/rules/no-constant-condition.js [hunk 2]
```diff
@@ -358,18 +371,6 @@ ruleTester.run("no-constant-condition", rule, {
             code: "if(''+[]) {}",
             errors: [{ messageId: "unexpected", type: "BinaryExpression" }]
         },
-        {
-            code: "if([a]==[a]) {}",
```
Comment (captbaritone) [inline tests/lib/rules/no-constant-condition.js:362]: This is a true error that we won't catch any more, but it is equivalent to a false positive (`if([a]==[b]) {}`) which used to be a false positive.

File: tests/lib/rules/no-constant-condition.js [hunk 3]
```diff
@@ -358,18 +371,6 @@ ruleTester.run("no-constant-condition", rule, {
...
-            errors: [{ messageId: "unexpected", type: "BinaryExpression" }]
-        },
-        {
-            code: "if([a] - '') {}",
```
Comment (captbaritone) [inline tests/lib/rules/no-constant-condition.js:366]: This was a false positive. If `a = 1` the condition is true, if `a =0` it is false.

File: tests/lib/rules/no-constant-condition.js [hunk 4]
```diff
@@ -358,18 +371,6 @@ ruleTester.run("no-constant-condition", rule, {
...
-            errors: [{ messageId: "unexpected", type: "BinaryExpression" }]
-        },
-        {
-            code: "if(+[a]) {}",
```
Comment (captbaritone) [inline tests/lib/rules/no-constant-condition.js:370]: This was a false positive. If `a = 1` the condition is true, if `a =0` it is false.

File: lib/rules/no-constant-condition.js [hunk 5]
```diff
@@ -138,15 +139,28 @@ module.exports = {
...
                 case "ClassExpression":
                     return true;
+                case "ObjectExpression":
+                    if (!inBooleanPosition) {
+                        return node.properties.every(prop => {
+                            if (prop.type === "SpreadElement") {
+                                return isConstant(prop, false);
+                            }
+                            if (prop.type === "Property") {
+                                return prop.key.name !== "toString" && prop.key.name !== "valueOf";
```
Comment (captbaritone) [inline lib/rules/no-constant-condition.js:151]: Oops. I think I failed to account for other types of keys here, like `{1: foo}` and `{[someExpression]: foo}`.

I'll update the PR to fix that.

Comment (captbaritone) [reply lib/rules/no-constant-condition.js:151]: Actually, before I dig into this too much more (it's a little complicated), we should decide: Do we care about false positives where users are redefining `toString` or `valueOf`? If not, I can skip all of this.

If we do, we'll need to ensure we catch things like `{["toString"]: () => foo}` as well as `{[`toString`]: () => foo}` etc.

@nzakas

Comment (nzakas) [reply lib/rules/no-constant-condition.js:151]: I think we can skip the toString and valueOf cases, at least for now. Those seem like extremely rare cases so I’m fine with false positives on those.

Comment (captbaritone) [reply lib/rules/no-constant-condition.js]: I've updated the PR.

File: tests/lib/rules/no-constant-condition.js (hunk 2 above)
Comment (mdjermanovic) [reply tests/lib/rules/no-constant-condition.js:362]: Is `if([a]==[b]) {}` a false positive? Both sides are objects, so this should be comparison by reference, and thus always `false` (even when the elements are same)?

```js
[1]==[1] // false
```

Comment (captbaritone) [reply tests/lib/rules/no-constant-condition.js:362]: Ah, yes. Sorry, not sure what I was thinking.

That said, `[a]` cannot be considered "constant" for the purposes of `==` comparison unless we also know what we are comparing it to (and thus how it will be compared), and currently the rule does not try to determine that information.

```JavaScript
[1] == 1
true
[0] == 1
false
```

So, you're absolutely right that `if([a]==[b]) {}` is a constant condition, but I still think it's appropriate to treat `[a]` as a non-constant expression when comparing with `inBooleanPosition: false`.

Comment (mdjermanovic) [reply tests/lib/rules/no-constant-condition.js:362]: Will `no-constant-binary-expression` catch these cases?

* ArrayExpression === anything
* ArrayExpression !== anything
* ArrayExpression  == ArrayExpression
* ArrayExpression  != ArrayExpression

I'm asking because these look like realistic mistakes that will be no longer reported by `no-constant-condition`,  so it might be good to special-case them to retain that behavior. But if they will be reported by another rule, then there's no need for that.

Comment (captbaritone) [reply tests/lib/rules/no-constant-condition.js:362]: These would get caught by `no-constnat-binary-expression`:

* ArrayExpression === anything
* ArrayExpression !== anything

These would _not_:

* ArrayExpression == ArrayExpression
* ArrayExpression != ArrayExpression

However, I suspect (hope!) that most people would be using some form of the `eqeqeq` rule to avoid the many many pitfalls and foot-guns exposed by testing for `==` equality.

Comment (mdjermanovic) [reply tests/lib/rules/no-constant-condition.js:362]: > These would _not_:
> 
> * ArrayExpression == ArrayExpression
> * ArrayExpression != ArrayExpression

I've just left a question about this on the `no-constant-binary-expression` PR: https://github.com/eslint/eslint/pull/15296#discussion_r780776004

File: lib/rules/no-constant-condition.js [hunk 6]
```diff
@@ -138,15 +139,23 @@ module.exports = {
...
                     return true;
+                case "ObjectExpression":
+
+                    /**
+                     * In theory an object like `{toString: () => a}` or
+                     * `{valueOf: () => a}` is not constant when
+                     * `inBooleanPosition` is false, but it's an
+                     * edge case we've opted not to handle.
+                     */
+                    return true;
```
[the remark this answers is not in the document]
Comment (captbaritone) [reply lib/rules/no-constant-condition.js:152]: Good point. I had forgotten about `static`.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! I'll leave this open for a few days in case anyone else wants to review it before merging.

**Review by nzakas — APPROVED** [review]
LGTM
