### PR TITLE
Fix: allow no tokens after `return` keyword (fixes #10372)

### LINKED ISSUE #10372: TypeError: Cannot read property 'value' of null
**Tell us about your environment**

* **ESLint Version:** v4.15.0
* **Node Version:** v8.9.4
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
- `babel-eslint`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
	parser: "babel-eslint",
	rules   : {
		'arrow-body-style' : ['warn', 'as-needed'],
	},
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
test = () => { return }
```

```bash
./node_modules/.bin/eslint FILE
```

**What did you expect to happen?**

Eslint to lint the file

**What actually happened? Please include the actual, raw output from ESLint.**

Error received `TypeError: Cannot read property 'value' of null`

```
Cannot read property 'value' of null
TypeError: Cannot read property 'value' of null
    at Object.isOpeningBraceToken (./node_modules/eslint/lib/ast-utils.js:354:18)
    at validate (./node_modules/eslint/lib/rules/arrow-body-style.js:119:41)
    at listeners.(anonymous function).forEach.listener (./node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (./node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (./node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (./node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (./node_modules/eslint/lib/util/node-event-generator.js:303:14)
    at CodePathAnalyzer.leaveNode (./node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:630:23)
    at Traverser.leave [as _leave] (./node_modules/eslint/lib/linter.js:1001:32)
```

### PR DESCRIPTION
**Pull request by g-plane**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

close #10372 

**What changes did you make? (Give an overview)**
Allow:
```js
test = () => { return }
```

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

File: lib/rules/arrow-body-style.js [hunk 1]
```diff
@@ -124,6 +124,8 @@ module.exports = {
                         messageId = "unexpectedEmptyBlock";
                     } else if (blockBody.length > 1) {
                         messageId = "unexpectedOtherBlock";
+                    } else if (sourceCode.getFirstToken(blockBody[0], { skip: 1 }) === null) {
+                        messageId = "unexpectedSingleBlock";
```
Comment (not-an-aardvark) [inline lib/rules/arrow-body-style.js]: It might be slightly more readable to use:

```js
} else if (blockBody[0].argument === null) {
```

**Comment by Aladdin-ADD** [comment]
Thanks for contributing!~
