### PR TITLE
Fix: Allow inline comments in newline-after-var rule (fixes #2229)

### LINKED ISSUE #2229: Ignore trailing comments in `newline-after-var` rule
The `newline-after-var` rule is issuing a warning in cases where there may be a trailing comment after the `var` declaration:

The following case is currently considered a warning, even though a newline follows the var statement:
```js
var foo = "foo", // more about foo
    bar = "bar"; // this comment causes the warning 

/* ... */
```

Perhaps we just need an option to allow trailing comments?

### PR DESCRIPTION
**Pull request by cvisco**
Previously, the newline-after-var rule relied on a RegEx pattern to
inspect the whitespace following a variable declaration. This resulted
in a warning when an inline comment followed a variable declaration.

* Switch to token-based inspection of line numbers
* Simplify error message for both "always" and "never" cases
* Shortcut rule if no next token exists
* Use `VariableDeclaration` instead of `VariableDeclaration:exit`
* Add additional tests for updated behavior

### CODE REVIEW

File: lib/rules/newline-after-var.js [hunk 1]
```diff
@@ -11,35 +12,70 @@
...
+        }
+    }
+
+    //--------------------------------------------------------------------------
+    // Public
+    //--------------------------------------------------------------------------
+
+    return {
+        "VariableDeclaration:exit": checkForBlankLine
     };
```
Comment (nzakas) [inline lib/rules/newline-after-var.js]: I think just "VariableDeclaration" will do here.

**Comment by nzakas** [comment]
This looks really good! Just had one question (see inline comment).

File: lib/rules/newline-after-var.js (hunk 1 above)
Comment (cvisco) [inline lib/rules/newline-after-var.js]: Yea, it would seem so! I updated this commit on my fork but I am sad to say I can't seem to get the actual Pull Request to update with the new change here. Thoughts?

Comment (nzakas) [inline lib/rules/newline-after-var.js]: Make sure your using the same branch. Make your change, then do `git commit --amend --no-edit` followed by `git push -f`. The pull request tracks your remote branch.

**Comment by cvisco** [comment]
@nzakas: Looks like it's been updated at this point.

**Comment by nzakas** [comment]
Yup, looks good. Nice work!
