### PR TITLE
Fix: Shallow cloning issues in eslint config (fixes #2961)

### LINKED ISSUE #2961: Inconsistent rule configuration with new eslint.CLIEngine
I'm trying to make a smaller proof of bug here, but here is what I have so far:

## STR

```
git clone https://github.com/mozilla/fxa-content-server#e29f5d654e8359051507314fb14efcf1e109bf46
cd fxa-content-server
npm install
```

1) Run
```
node_modules/.bin/grunt eslint
```
runs all tasks (including the one below), everything passes

2) Run
```
node_modules/.bin/grunt eslint:tests
```

Throws the error:
```
tests/functional/force_auth.js
  23:2  error  Designated alias 'self' is not assigned to 'this'  consistent-this
  32:2  error  Designated alias 'self' is not assigned to 'this'  consistent-this

✖ 2 problems (2 errors, 0 warnings)
```

## End of STR

From my investigation the options that are passed via the grunt task in https://github.com/sindresorhus/grunt-eslint/blob/master/tasks/eslint.js#L46 are identical 

The traversal has a different rule setting in 1) and 2):
image

Grunt task configuration here: https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/eslint.js#L24

At this moment it seems that eslint has some global state of linting rules that merges itself instead of being independent for each `var engine = new eslint.CLIEngine(opts);`

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

File: lib/eslint.js [hunk 1]
```diff
@@ -302,12 +302,12 @@ function modifyConfigsFromComments(filename, ast, config, reportingConfig, messa
     // apply environment configs
     Object.keys(commentConfig.env).forEach(function (name) {
         if (environments[name]) {
-            util.mergeConfigs(commentConfig, environments[name]);
+            assign(commentConfig, environments[name]);
```
Comment (nzakas) [inline lib/eslint.js]: Are you sure you want a shallow copy here? Seems like this should also be a deep merge.

Comment (gyandeeps) [inline lib/eslint.js]: Cheeez I forgot to change it, I had in my head. (Spent too much time on the deep merge code lol)

**Comment by nzakas** [comment]
Lgtm
