### PR TITLE
Fix: wrong comment when module not found in config (fixes #8192)

### LINKED ISSUE #8192: "Extends" with plugins displays a confusing error message
**Tell us about your environment**

* **ESLint Version:** 3.16.1
* **Node Version:** 7.6.0
* **yarn Version:** 0.20.3

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**Please show your full configuration:**
```js
module.exports = {
  extends: ['airbnb', 'plugin:flowtype/recommended'],
  plugins: ['flowtype'],
  rules: {
    'flowtype/define-flow-type': 1,
    'flowtype/use-flow-type': 1,
    'flowtype/delimiter-dangle': [2, 'always'],
    'flowtype/semi': [2, 'always'],
  },
  settings: {
    flowtype: {
      onlyFilesWithFlowAnnotation: true,
    },
  },
};
```

package.json:
```json
...
"eslint-plugin-flowtype": "2.30.0",
...
```

**What did you expect to happen?**
My code would be linted with 'flowtype' rules.

**What actually happened? Please include the actual, raw output from ESLint.**
I get:
```
Oops! Something went wrong! :(

ESLint couldn't find the config "plugin:flowtype/recommended" to extend from. Please check that the name of the config is correct.
```

### PR DESCRIPTION
**Pull request by alberto**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
PR https://github.com/eslint/eslint/pull/8100 modified the message when there was an error loading a plugin or config, but didn't account for other possible errors. In this case, `babel-eslint` was not present, and the error was misleading.

**Is there anything you'd like reviewers to focus on?**
Is there a cleaner way to check for this rather than using the error message?

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
> Is there a cleaner way to check for this rather than using the error message?

You can detect module-loading errors by checking `err.code === "MODULE_NOT_FOUND"`.

Could you clarify what errors this logic is checking for? Intuitively, it seems like we should be able to avoid throwing TypeErrors, so I'm confused what the effect of catching them is. Also, I'm not sure I understand why this logic is only catching missing-module errors related to `eslint-config-eslint`.

**Comment by alberto** [comment]
I have updated the PR, I hope the intention is clearer now. I tried to provide a better error for people trying to load an inexistent config from a shared config, a plugin or an interal eslint rule. Main use case is someone has a typo in his config (e.g. `eslint:recommend` instead of `eslint:recommended`).

File: lib/config/config-file.js [hunk 1]
```diff
@@ -360,43 +406,23 @@ function applyExtends(config, filePath, relativeTo) {
...
+                parentPath = getEslintCoreConfigPath(parentPath);
+            } else if (isFilePath(parentPath)) {
+
+                /*
+                 * If the `extends` path is relative, use the directory of the current configuration
+                 * file as the reference point. Otherwise, use as-is.
+                 */
+                parentPath = (!path.isAbsolute(parentPath)
+                    ? path.join(relativeTo || path.dirname(filePath), parentPath)
+                    : parentPath
```
Comment (not-an-aardvark) [inline lib/config/config-file.js]: It might be more readable to avoid negating the condition here.

```js
parentPath = path.isAbsolute(parentPath)
    ? parentPath
    : path.join(relativeTo || path.dirname(filePath), parentPath);
```

File: lib/config/config-file.js [hunk 2]
```diff
@@ -472,13 +498,14 @@ function resolve(filePath, relativeTo) {
...
     if (filePath.indexOf("plugin:") === 0) {
+        const pluginPath = filePath;
         const packagePath = filePath.substr(7, filePath.lastIndexOf("/") - 7);
         const configName = filePath.substr(filePath.lastIndexOf("/") + 1, filePath.length - filePath.lastIndexOf("/") - 1);
 
         normalizedPackageName = normalizePackageName(packagePath, "eslint-plugin");
         debug(`Attempting to resolve ${normalizedPackageName}`);
         filePath = resolver.resolve(normalizedPackageName, getLookupPath(relativeTo));
-        return { filePath, configName };
+        return { filePath, configName, pluginPath };
```
Comment (not-an-aardvark) [inline lib/config/config-file.js]: Is there a reason to include `pluginPath` in the return value when it's always the same as `filePath`?

According to the JSDoc comment, the return value of this function is "A path that can be used directly to load the configuration", but it would be useful if it described the properties of the return value in more detail.

Comment (alberto) [inline lib/config/config-file.js]: `pluginPath` is not a very accurate name. Maybe `configFullName` is more appropriate. Something like `plugin:node/recommended`.
`filePath` is modified in the previous line to contain the resolved path of the config file.

I'm not very fond of JSDoc. How should I document the optional properties of a return object?

File: lib/config/config-file.js [hunk 3]
```diff
@@ -360,43 +406,23 @@ function applyExtends(config, filePath, relativeTo) {
...
-             * file as the reference point. Otherwise, use as-is.
-             */
-            parentPath = (!path.isAbsolute(parentPath)
-                ? path.join(relativeTo || path.dirname(filePath), parentPath)
-                : parentPath
-            );
-        }
-
         try {
+            if (parentPath.indexOf("eslint:") === 0) {
```
Comment (alberto) [inline lib/config/config-file.js]: yeah, thanks!

File: lib/config/config-file.js (hunk 1 above)
Comment (alberto) [inline lib/config/config-file.js]: I didn't really touch this part, but, yeah, I will update it while I am on it

File: lib/config/config-file.js (hunk 2 above)
Comment (not-an-aardvark) [inline lib/config/config-file.js]: I'm not sure if there's an official JSDoc way to do it, but just explaining the optional properties in words would be a good improvement.

**Comment by alberto** [comment]
@not-an-aardvark let me know if it LGTY now. Thanks for your feedback, I'm much happier with the code now :)
