### PR TITLE
Fix: Allow leading/trailing whitespace in rule message parameters. (fixes #3690)

### LINKED ISSUE #3690: Enhancement request: Support leading/trailing spaces in rule message format placeholder names
When using formatted/interpolated rule messages, the contents of the identifier between `{{` and `}}` characters are extracted exactly as is, meaning it is impossible to use whitespace for readability without doing some interesting things in the interpolation code.

Possible now:

```js
// No spaces:
var message = "Unexpected {{thing}}";
context.report(node, message, { thing: "foo" });

// With spaces, but weird interpolation hackery needed:
var message = "Unexpected {{ thing }}";
context.report(node, message, { " thing ": "foo" });

// Desired but doesn't work:
var message = "Unexpected {{ thing }}";
context.report(node, message, { thing: "foo" });    // Trims " thing " before storing it as interpolation point
```

This might be a breaking change in case anyone has been using the second behavior.

I know this is a pretty trivial thing, but sometimes, a little readability goes a long way. (And I'm happy to implement if this gets accepted, as well, since I know the core team would probably not have time for something like this.)

### PR DESCRIPTION
**Pull request by platinumazure**
Also added a bunch of unit tests which do pass under the old version of the code, to show previously undocumented assumptions.

Some other notes:
1. I intentionally moved the message interpolation code *below* the code that checks if the rule is even on in the first place. I didn't see a lot of point in running regexes over the message if it wasn't even going to be used. If this is a problem, I can move it back.
2. Rather than iterating over keys and constructing a `new RegExp` each time, I chose to run a general regex over the whole pattern and do lookup from there. I [tested on jsperf][1] and it said my approach was loads faster, but I don't know how good my test cases are and furthermore I was testing my browser rather than Node. If anyone has any good tips on how to perf-test in Node, I'm all ears.

Fixes #3690.

  [1]: http://jsperf.com/eslint-interpolation-test

### CODE REVIEW

File: tests/lib/eslint.js [hunk 1]
```diff
@@ -723,6 +723,137 @@ describe("eslint", function() {
...
+                };
+            });
+
+            var config = { rules: {} };
+            config.rules["test-rule"] = 1;
+
+            var messages = eslint.verify("0", config);
+            assert.equal(messages[0].message, "message {{parameter}}");
+        });
+
```
Comment (platinumazure) [inline tests/lib/eslint.js]: NOTE: All tests before this point pass even with old code. These are the tests which document previously undocumented assumptions. All tests after this point fail with the old code.

**Comment by platinumazure** [comment]
Also, a more general question/concern: Does running `eslint.reset()` at the beginning of those tests feel like a smell to anyone else? At the very least, if the `eslint` object in those tests is a singleton and this cannot be fixed, I wonder if `eslint.reset()` should be run in setup or teardown...

**Comment by btmills** [comment]
Implementation and tests both look good! Can you shorten the commit message a bit? Our changelog will truncate past ~70 characters.

I'll defer the `reset()` question to someone who's more familiar with that part of the code. @nzakas?

**Comment by platinumazure** [comment]
@btmills Done, just waiting on travis. If a first-line commit message should really be less than 70 characters, could that be added to `npm run check-commit`? I did run that and it didn't flag any issues, and this seems like it might be worth flagging. I can create an issue if needed.

**Comment by btmills** [comment]
> If a first-line commit message should really be less than 70 characters, could that be added to npm run check-commit? ... I can create an issue if needed.

Good idea! Please do, it's at least worth discussing.

This PR is now :+1: from me!

**Comment by platinumazure** [comment]
@btmills Done; please see issue #3760.

**Comment by BYK** [comment]
I think this should be tagged with `Update: `.

**Comment by btmills** [comment]
> I think this should be tagged with `Update:`.

Based on @nzakas's [comment](https://github.com/eslint/eslint/issues/3690#issuecomment-138681560) in #3690 and the `bug` label, I think `Fix:` is correct.

**Comment by ilyavolodin** [comment]
I agree, this was unintended behavior before, hence "fix"
