### PR TITLE
Update: fix `quotes` rule's false negative (fixes #7084)

### LINKED ISSUE #7084: quotes does not catch errors in strings wrapped in {...} within jsx
**What version are you using?**
3.4.0

**What did you do?**
Run lint with `quotes` rule turned on (prefer single quotes) over jsx code that looks like:
`<SomeComponent someProp={"blah"} />`

**What happened?**
The linter passed, when it should have errored on the double quotes. This is not covered by jsx-quotes because the string is wrapped in `{...}`, which makes it a JS string and not a jsx string.

**What did you expect to happen?**
Error for violating the `quotes` rule

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

```
[ ] Documentation update
[x] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:
```

See the template of #7084.

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- n/a I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**

the spec of JSX AST is here: https://github.com/facebook/jsx/blob/master/AST.md

`JSXExpressionContainer` has a normal expression, so `quotes` rule should check string literals in `JSXExpressionContainer`. But the rule had ignored string literals in all node which starts with `JSX`.

As the spec, `quotes` rule should ignore string literals in only `JSXAttribute` and `JSXElement`.

**Semver-minor**: This is a bug fix which increases errors.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: lib/rules/quotes.js [hunk 1]
```diff
@@ -128,7 +128,7 @@ module.exports = {
          * @private
          */
         function isJSXElement(node) {
```
Comment (btmills) [inline lib/rules/quotes.js]: Since this is no longer checking exclusively for `JSXElement`, perhaps rename it to `isJSX`, pass it the `Literal` node directly, and have it return `node.parent.type !== "JSXExpressionContainer"`? Then the check below becomes just "Is this `Literal` node a JSX literal or a JS literal?", and the method of checking the parent becomes just a hidden implementation detail.

**Comment by nzakas** [comment]
LGTM. Agree with @btmills comment.

File: lib/rules/quotes.js [hunk 2]
```diff
@@ -123,12 +123,26 @@ module.exports = {
 
         /**
          * Determines if a given node is part of JSX syntax.
-         * @param {ASTNode} node The node to check.
-         * @returns {boolean} True if the node is a JSX node, false if not.
+         *
+         * This function returns `ture` in the following cases:
```
Comment (platinumazure) [inline lib/rules/quotes.js]: s/ture/true

**Comment by platinumazure** [comment]
LGTM except for a small typo in a comment. Thanks!

File: lib/rules/quotes.js (hunk 2 above)
Comment (mysticatea) [inline lib/rules/quotes.js]: Oops, thank you!

**Comment by mysticatea** [comment]
I updated it.

File: lib/rules/quotes.js [hunk 3]
```diff
@@ -123,12 +123,26 @@ module.exports = {
 
         /**
          * Determines if a given node is part of JSX syntax.
```
Comment (kaicataldo) [inline lib/rules/quotes.js]: Should this description be updated?

File: lib/rules/quotes.js [hunk 4]
```diff
@@ -123,12 +123,26 @@ module.exports = {
...
+         * In particular, this function returns `false` in the following cases:
+         *
+         * - `<div className={"foo"}></div>`
+         * - `<div>{"foo"}</div>`
+         *
+         * In both cases, inside of the braces is handled as normal JavaScript.
+         * The braces are `JSXExpressionContainer` nodes.
+         *
+         * @param {ASTNode} node The Literal node to check.
+         * @returns {boolean} True if the node is a part of JSX, false if not.
```
Comment (kaicataldo) [inline lib/rules/quotes.js]: Should the description for `@returns` also be updated?

File: lib/rules/quotes.js (hunk 3 above)
Comment (mysticatea) [inline lib/rules/quotes.js]: I think shouldn't.
I thought `Literal`s of `JSXAttribute`/`JSXElement` is part of JSX syntax. Those are `JSXDoubleStringCharacters`/`JSXSingleStringCharacters`/`JSXText` production in original spec. On the other hand, inside of braces is `AssignmentExpression` production of ECMAScript.

Comment (kaicataldo) [inline lib/rules/quotes.js]: Alright, fair enough!
