### PR TITLE
fix: Ensure that dot files are found with globs.

### LINKED ISSUE #16265: Bug: [new config system] globs are ignoring dot files
### Environment

Node version: v16.14.0
npm version: v8.3.1
Local ESLint version: v8.23.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19044

### What parser are you using?

Default (Espree)

### What did you do?

```js
// eslint.config.js

module.exports = [];
```

```js
// .foo.js
```

```
npx eslint *.js -f tap
```

### What did you expect to happen?

Per the [RFC](https://github.com/eslint/rfcs/blob/893b49194689fcf0d34743eac75773d098264656/designs/2019-config-simplification/README.md?plain=1#L534), this should include ` .foo.js`?

> 1. **Defaults** - by default, ESLint will ignore `node_modules` and `.git` directories only. This is different from the current behavior where ESLint ignores `node_modules` and all files/directories beginning with a dot (`.`).

In that case, I would expect this output:

```
TAP version 13
1..2
ok 1 - D:\tmp\tmp\.foo.js
ok 2 - D:\tmp\tmp\eslint.config.js
```

### What actually happened?

The `.foo.js` file was not linted:

```
TAP version 13
1..1
ok 1 - D:\tmp\tmp\eslint.config.js
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Previously, glob patterns didn't match dot files and couldn't be changed while we were using globby for flat config. Because we moved to our own glob search, we can now include dot files in our searches automatically.

Note that `ConfigArray` was [already matching](https://github.com/humanwhocodes/config-array/blob/main/src/config-array.js#L26) patterns against dot files. This change brings our glob search into alignment with how `ConfigArray` works.

Fixes #16265

#### Is there anything you'd like reviewers to focus on?

I had to adjust some existing tests because they had dot files in the directories they were running in. Please double-check those changes.

### CODE REVIEW

File: tests/lib/eslint/flat-eslint.js [hunk 1]
```diff
@@ -773,7 +790,7 @@ describe("FlatESLint", () => {
             });
             const results = await eslint.lintFiles(["fixtures/files/"]);
 
-            assert.strictEqual(results.length, 2);
+            assert.strictEqual(results.length, 3);
```
Comment (nzakas) [inline tests/lib/eslint/flat-eslint.js:793]: `fixtures/files` actually has a dot file in it. Because this directory is also used for `cli-engine` tests, I didn't want to change the directory itself. So I just updated the results.

The same is true for a few other tests as well.

**Review by snitin315 — APPROVED** [review]
LGTM. Thank you.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
