### PR TITLE
Fix: Exit code should be 1 for any number of errors (fixes #1795)

### LINKED ISSUE #1795: "Exit code is now error count" breaking CI code
Version 0.14.0 of eslint has changed the exit code to be equal to the number of errors and breaks quite a few tests in my CI environment.
I did not find any issue on this and would like to understand why this change has been introduced and suggest to rather differentiate between errors and warning as this is something that I currently do with a separate parsing step and might come useful to others as well.

Exit codes:
0 - success
1 - error (like before and therefore not changing existing uses of eslint)
2 - warning

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/8391289-exit-code-is-now-error-count-breaking-ci-code?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

File: lib/cli.js [hunk 1]
```diff
@@ -181,7 +181,7 @@ var cli = {
             }
 
             if (printResults(engine, result.results, currentOptions.format, currentOptions.outputFile)) {
-                return result.errorCount;
+                return result.errorCount > 0;
```
Comment (michaelficarra) [inline lib/cli.js]: This function returns numbers, not Booleans.

Comment (nzakas) [inline lib/cli.js]: Oops, good call.
