### PR TITLE
Fix: avoid crashing on malformed configuration comments (fixes #9373)

### LINKED ISSUE #9373: Handle rule configuration errors more consistently
I've noticed that our error-handling strategy is very inconsistent across different error scenarios. This inconsistency is a problem because it creates unexpected edge cases in integrations (causing bugs like https://github.com/eslint/eslint.github.io/issues/413).

| **Problem**                                                      | **Current error-handling behavior** |
|--------------------------------------------------------------|---------------------------------|
| Unrecognized rule in config file                             | Linting error                   |
| Invalid rule config in config file                           | Fatal error                     |
| Invalid rule config in `Linter#verify`                       | No error                        |
| Unrecognized rule in `/* eslint */` comment                  | Linting error                   |
| Unparseable rule config in `/* eslint */` comment            | *Linting error*                   |
| Parseable, but invalid rule config in `/* eslint */` comment | *Fatal error*                     |
| Unrecognized rule in `/* eslint-disable */` comment          | No error                        |

I've italicized the cases that I find particularly surprising (namely, that linting can continue if an `/* eslint */` comment contains a parsing error, but the process crashes if the rule config is parseable and doesn't match the schema). It seems like an unparseable rule config should always be a more severe issue than an invalid rule config, because all invalid rule configs are parseable.

This is also strange because `Linter#verify` doesn't verify rule schemas at all, so it ends up that only inline config schemas are verified, not the main config being used for the file.

I think we should make invalid rule configs in `/* eslint */` comments into a linting error, rather than a fatal error. That would create a useful invariant where `Linter#verify` should never throw an error when given a valid config, regardless of the source text being linted.

Separately, I think we might want to reconsider https://github.com/eslint/eslint/issues/8325 (validating configs in `Linter#verify`). There were two objections brought up before: performance and separation of concerns.

* I don't think performance would be a problem in practice, because we could cache config objects and avoid validating them again if we see a config which is known to be valid. This would prevent `CLIEngine` from slowing down.
* `Linter` already validates rule schemas anyway for inline comments, so I don't think validating the top-level config would introduce any new issues relating to separation of concerns that aren't already present.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/9373)

**What changes did you make? (Give an overview)**

This updates `Linter` to treat malformed configuration comments as linting errors rather than fatal issues that crash the process. Previously, this could cause surprising behavior because it was the only known instance where a problem in the source code (given a valid configuration) could cause an error to be thrown.

For example, this also fixes https://github.com/eslint/eslint.github.io/issues/413.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: lib/linter.js [hunk 1]
```diff
@@ -340,7 +340,19 @@ function modifyConfigsFromComments(filename, ast, config, ruleMapper) {
...
+                                try {
+                                    validator.validateRuleOptions(ruleMapper(name), name, ruleValue);
+                                } catch (err) {
+                                    problems.push({
+                                        ruleId: name,
+                                        severity: 2,
+                                        source: null,
+                                        message: err.message,
+                                        line: comment.loc.start.line,
+                                        column: comment.loc.start.column + 1,
```
Comment (mysticatea) [inline lib/linter.js]: I think good if it defines `endLine` and `endColumn` with `comment.loc.end`.

File: lib/config/config-validator.js [hunk 2]
```diff
@@ -112,7 +113,13 @@ function validateRuleOptions(rule, ruleId, options, source) {
             validateRuleSchema(rule, Array.isArray(options) ? options.slice(1) : []);
         }
     } catch (err) {
-        throw new Error(`${source}:\n\tConfiguration for rule "${ruleId}" is invalid:\n${err.message}`);
+        const enhancedMessage = `Configuration for rule "${ruleId}" is invalid:\n${err.message}`;
```
Comment (platinumazure) [inline lib/config/config-validator.js]: Wondering if this should say "Inline configuration" (or equivalent), in order to make it clear that it's from a configuration comment rather than from a user's configuration files?

File: lib/linter.js [hunk 3]
```diff
@@ -340,7 +340,19 @@ function modifyConfigsFromComments(filename, ast, config, ruleMapper) {
                             Object.keys(parseResult.config).forEach(name => {
                                 const ruleValue = parseResult.config[name];
 
-                                validator.validateRuleOptions(ruleMapper(name), name, ruleValue, `${filename} line ${comment.loc.start.line}`);
+                                try {
+                                    validator.validateRuleOptions(ruleMapper(name), name, ruleValue);
+                                } catch (err) {
```
Comment (platinumazure) [inline lib/linter.js]: Should we decorate the thrown error object with some property to indicate it is specifically the validation error we want to report? That way, if we check for that property here, an unexpected exception (from something not directly due to schema validation) would propagate as a crash.

File: lib/config/config-validator.js (hunk 2 above)
Comment (not-an-aardvark) [reply lib/config/config-validator.js]: I went with the current behavior on the assumption that it would be clear because the reported problem is at the comment's location.

I'd be fine with changing it if you feel strongly about it, although I wonder if we would want to refactor this function to make the error messages more flexible.

File: lib/linter.js (hunk 3 above)
Comment (not-an-aardvark) [reply lib/linter.js]: Seems reasonable, although I think we already use thrown errors to communicate schema issues in other places.

Maybe it would be better to switch to a result type instead, where `validator.validateRuleOptions` would return something like `{ success: true }` or `{ success: false, error: err }`. Then a thrown error would always indicate that something went wrong.

**Comment by platinumazure** [comment]
I don't feel strongly enough on any of these to demand a change- just
wanted your thoughts. Consider this approved on my end- we definitely need
to avoid crashing here. Thanks!

**Comment by platinumazure** [comment]
@not-an-aardvark Instead of calculating line/column/endLine/endColumn manually, can we just pass the comment token to `context.report`? Or does that not support comments, only nodes/tokens?

**Comment by not-an-aardvark** [comment]
I can look into doing that. I think it would be nontrivial because a `context` only exists when a rule has been created, but it would be nice to reuse the report translator logic to avoid needing to manually remember all of the properties.

**Comment by platinumazure** [comment]
> I think it would be nontrivial because a context only exists when a rule has been created

Ack, for some reason I thought we were calling context.report, but you're quite right. I don't think we should pull out the report translator here. I'm fine with this going in as is. Maybe we could look into that functionality later... Thanks!
