### PR TITLE
Fix: prefer-const false positive with object spread (fixes #8187)

### LINKED ISSUE #8187: Destructuring two variables and reassigning the value of one is hard with let and const
**Tell us about your environment**

* **ESLint Version:** 3.16.1
* **Node Version:** v6.6.0
* **npm Version:** 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```js
module.exports = {
  "env": {
    "browser": true,
    "es6": true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
    "sourceType": "module",
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  },
  "rules": {
    "prefer-const": ["error", {
      "destructuring": "any",
      "ignoreReadBeforeAssign": false
    }],
    "no-console": "off"
  }
};
```

**What did you do? Please include the actual source code causing the issue.**

I have a basic test case of the problem in this code:

```js
const props = {
  name: "Eric",
  age: 30,
  occupation: "Artist"
}

let { name, age } = props;
age = 3;

console.log(name);
console.log(age);
```

ESLint says that `let { name, age } = props;` is a problem and should use `const`. 

Here, two variables are created via destructuring syntax, and one is later reassigned but the other is not. 

Fixing the code as the rule suggests means using `const`, which creates a syntax error.

**What did you expect to happen?** 

I'm not sure :)

**What actually happened? Please include the actual, raw output from ESLint.**

```
$ ./node_modules/.bin/eslint app.js

/Users/eric/Desktop/eslint/app.js
  7:7  error  'name' is never reassigned. Use 'const' instead  prefer-const

✖ 1 problem (1 error, 0 warnings)
```

### PR DESCRIPTION
**Pull request by vitorbal**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

This fixes a false-positive with `prefer-const` and the `destructuring: "all"` option. Essentially, the option was not taking into account destructurings that contained a rest operator.
The original bug-report is here: https://github.com/eslint/eslint/issues/8187#issuecomment-283822912

**What changes did you make? (Give an overview)**
I've added a couple of test cases that reproduce the bug, then modified the `prefer-const` rule accordingly to fix the bug.

**Is there anything you'd like reviewers to focus on?**
I'm not sure, but I think not. Maybe suggestions for more test cases?

### CODE REVIEW

**Comment by vitorbal** [comment]
> not-an-aardvark commented 4 minutes ago
Actually, ESTree ended up switching to RestElement. I think babel-eslint might still use RestProperty though.

That's a good point. [This issue](https://github.com/estree/estree/issues/145#issuecomment-274709116) leads me to believe babel-eslint indeed is still using `RestProperty`. ping @hzoo can you confirm?

**Comment by vitorbal** [comment]
I reached out to @hzoo and it looks like babel-eslint still uses `RestProperty`, so I'm gonna update the PR to add a check for it as well.

As far as I understand, the `RestProperty` usage will be cleaned up after https://github.com/babel/babel-eslint/issues/440, so we could do a sweeping change and clean up the occurences in eslint too once that's done.

**Comment by platinumazure** [comment]
@vitorbal Thanks for checking! I think removing RestProperty from every rule should probably be considered a semver-major change since we don't know what other parsers might use it and rely on ESLint supporting that node type.

**Comment by vitorbal** [comment]
@platinumazure Hmm that's a very good point, thanks for pointing it out!

File: lib/rules/prefer-const.js [hunk 1]
```diff
@@ -9,7 +9,7 @@
 // Helpers
 //------------------------------------------------------------------------------
 
-const PATTERN_TYPE = /^(?:.+?Pattern|RestElement|Property)$/;
+const PATTERN_TYPE = /^(?:.+?Pattern|RestElement|ExperimentalRestProperty|Property)$/;
```
Comment (platinumazure) [inline lib/rules/prefer-const.js]: Given what we've uncovered in the discussion, this should probably include RestProperty as well.

If at all possible, a test which simulates the babel-eslint parser's output would also be awesome, but don't put too much effort into that.

**Comment by vitorbal** [comment]
Ok so I did a bit more investigating and I found out that babel-eslint already outputs `ExperimentalRestProperty` since v6.x (https://github.com/babel/babel-eslint/commit/31dd8116f09ad08a6970d7e2bcbaf5d4fe0373f0).

On previous versions of babel-eslint, the node type was being set to `SpreadProperty`  (instead of RestProperty, like we previously believed).

I added `SpreadProperty` to the regexp pattern, since I assume babel-eslint 5.x still sees some usage (it only supports ESLint 1.x, though...).
I also wrote a stub parser fixture for the ast output from babel-eslint 5.x, and a couple of tests.
If folks think the tests are not necessary I can remove them, but I figured it wouldn't hurt.

**Comment by vitorbal** [comment]
ping @not-an-aardvark @platinumazure. Any chance you guys could take another look at this? Would like to get it merged before the release this Friday, if possible.
