### PR TITLE
Fix: reduced `no-loop-func` false positive (fixes #5044)

### LINKED ISSUE #5044: no-loop-func shouldn't warn when a function is used inside a forEach or such functions
**What version are you using?**
2.0.0-beta.1

**What did you do?**
I tested this code using the no-loop-func rule:

```javascript
  for (const score in scores) {
    const letters = scores[score];
    letters.split('').forEach(letter => {
      result[letter] = score;
    });
  }
```
Because of the function in forEach, the no-loop-func gives a warning here. Yet this is not an issue because forEach's parameter actually runs right away, it's not an asynchronous callback.

This should be relaxed at least for all Array iteration methods (also for Map and Set, but this is also a `forEach` method; maybe we can accept that all forEach/map/etc methods will behave the same).
And also the Promise constructor.
I'd be happy enough with a rule configuration.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30147507-no-loop-func-shouldn-t-warn-when-a-function-is-used-inside-a-foreach-or-such-functions?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #5044.

This PR adds a check of references which refer to upper variables from functions in a loop. The `no-loop-func` rule comes to warn the function only if there are unsafe reference. The unsafe reference is a reference that the referred variable can be modified after the function.

### CODE REVIEW

File: tests/lib/rules/no-loop-func.js [hunk 1]
```diff
@@ -60,6 +59,42 @@ ruleTester.run("no-loop-func", rule, {
         {
             code: "for (let i = 0; i < 10; ++i) { for (let x in xs.filter(x => x != i)) {  } }",
             parserOptions: { ecmaVersion: 6 }
+        },
```
Comment (nzakas) [inline tests/lib/rules/no-loop-func.js]: Can you add a test with typeof, like I'm the issue?

Comment (mysticatea) [inline tests/lib/rules/no-loop-func.js]: I added it (though the test is not using `typeof`)

**Comment by ilyavolodin** [comment]
LGTM
