### PR TITLE
Fix: ignore aligning single line in key-spacing (fixes #11414)

### LINKED ISSUE #11414: key-spacing + align: 'value' + jsx objects becomes ugly sometimes
screenshot 2019-02-19 at 18 51 23

image

**👀 Look at the repo with minimal reproducible example (dependencies, config, source):** https://github.com/a-x-/eslint-align-check

<br/><br/>

----

<br/><br/>

**environment**

* **ESLint Version:** latest (5.13.0)
* **Node Version:** latest (11.9.0)
* **npm Version:** latest (6.8.0)

**parser**: Babel-ESLint 

**minimal configuration:** (full config has no sense never : )

```js
{
  "plugins": [
    "react",
  ],
  "rules": {
    "key-spacing": ["warn", {
      "multiLine": {"align": "value"},
    }],
    // some related a bit rules
    "object-curly-newline": ["warn", { "multiline": true, "minProperties": 5 }],
    "object-property-newline": ["warn", {"allowAllPropertiesOnSameLine": true }],
    "object-curly-spacing": ["warn", "always", {
      "arraysInObjects": false,
      "objectsInObjects": false,
    }],
    // ...
  },
}
```

**source and command**

<details><summary>source before eslint --fix ran</summary>

```jsx
function Component () {
      return <div>
        <span style={{ display: 'inline-block', marginRight: '10px' }}>
          <Fa
            icon={ d.icon }
            style={{ marginRight: '4px', color: '#0C090A', opacity: '0.6', fontSize: '18px', verticalAlign: 'middle' }}
          />
          <span style={{ verticalAlign: 'bottom' }}>{ d.title }</span>
        </span>
        <span>
          <Fa
            icon="location-arrow"
            style={{ marginRight: '4px', color: '#0C090A', opacity: '0.6', fontSize: '18px', verticalAlign: 'middle' }}
          />
          <span style={{ verticalAlign: 'bottom' }}>{ this.state.info?.device.app_version }</span>
          <br />
          <span style={{ color: '#999999' }} title="Когда последний раз делал что-то в приложении">
            { this.state.info?.device.last_request_at }
          </span>
        </span>
      </div>;
}
```

</details>

```bash
eslint --fix file.jsx
```

**Expected:** don't re-align objects in jsx curlies.

**PR?** I'm not sure, maybe I can.

### PR DESCRIPTION
**Pull request by yeonjuan**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
fix #11414 
make it ignore aligning single line properties.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

File: lib/rules/key-spacing.js [hunk 1]
```diff
@@ -611,17 +612,35 @@ module.exports = {
...
+        /**
+         * Verifies vertical alignment, taking into account groups of properties.
+         * @param  {ASTNode} node ObjectExpression node being evaluated.
+         * @returns {void}
+         */
+        function verifyAlignment(node) {
+            createGroups(node).forEach(group => {
+                const properties = group.filter(isKeyValueProperty);
+
+                if (properties.length > 0 && isSingleLineProperties(properties)) {
```
Comment (kaicataldo) [inline lib/rules/key-spacing.js]: Can we add a test for `properties.length === 1`?

File: tests/lib/rules/key-spacing.js [hunk 2]
```diff
@@ -757,6 +757,34 @@ ruleTester.run("key-spacing", rule, {
             }
         }],
         parserOptions: { ecmaVersion: 6 }
+    }, {
+        code: [
+            "var obj = {",
+            "    foo : 1, 'bar' : 2, baz : 3, longlonglong : 4",
```
Comment (kaicataldo) [inline tests/lib/rules/key-spacing.js]: Can we add more varied tests? Some examples:

```
var obj = {   foo : 1, 'bar' : 2, baz : 3, longlonglong : 4 };
```

```
var obj = {  
    foo : 1, 
    'bar' : 2, baz : 3, longlonglong : 4 
};
```

```
var obj = {  
    foo : 1, 
    'bar' : 2, baz : 3, 
    longlonglong : 4 
};
```

Comment (yeonjuan) [reply tests/lib/rules/key-spacing.js]: @kaicataldo 
Yes, But I have a question.
This PR does not have differences with the actual version([demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgXCJrZXktc3BhY2luZ1wiOiBbXCJ3YXJuXCIsIHtcIm11bHRpTGluZVwiOiB7XCJhbGlnblwiOiBcImNvbG9uXCJ9fV0qL1xuXG5zdHlsZT17XG4gZm9vOiAxLCBiYXI6IDIsXG4gbG9uZ2xvbmdsb25nOiAzLFxufVxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMCwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6eyJqc3giOnRydWV9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)) in some cases you mentioned.
```
var obj = {  
    foo : 1, 
    'bar' : 2, baz : 3, longlonglong : 4 
};
```
I already opened PR(#12651) for those cases but closed it, because the closed PR would change the concept of the "group" in this rule.
```
// closed one 
var obj = {  
    foo : 1,  // groupA
    'bar' : 2, baz : 3, longlonglong : 4  // groupB
};
```
so I want to know which behavior is correct ,This PR or closed PR(#12651)?

File: lib/rules/key-spacing.js (hunk 1 above)
Comment (yeonjuan) [reply lib/rules/key-spacing.js]: Sure!

File: tests/lib/rules/key-spacing.js (hunk 2 above)
Comment (kaicataldo) [reply tests/lib/rules/key-spacing.js]: I think the behavior here is correct.

File: lib/rules/key-spacing.js (hunk 1 above)
Comment (yeonjuan) [reply lib/rules/key-spacing.js]: https://github.com/eslint/eslint/blob/841ccc6fc97a8a506ea80303258eadb15151a965/tests/lib/rules/key-spacing.js#L789-L819
@kaicataldo  Thanks. I added more test cases for ```properties.length === 1```

File: tests/lib/rules/key-spacing.js (hunk 2 above)
Comment (kaicataldo) [reply tests/lib/rules/key-spacing.js]: My intention in requesting tests here is to protect against regressions. Does that make sense?

Comment (yeonjuan) [reply tests/lib/rules/key-spacing.js]: yes! That makes sense. I'll work on it.

Comment (yeonjuan) [reply tests/lib/rules/key-spacing.js]: @kaicataldo 
all done! thanks! :)

File: tests/lib/rules/key-spacing.js [hunk 3]
```diff
@@ -1769,5 +1904,206 @@ ruleTester.run("key-spacing", rule, {
...
+        code: [
+            "var obj = {",
+            "    foo: 1,",
+            "    'bar': 2, baz: 3, longlonglong: 4",
+            "}"
+        ].join("\n"),
+        output: [
+            "var obj = {",
+            "    foo         : 1,",
+            "    'bar'       : 2, baz         : 3, longlonglong: 4",
```
Comment (kaicataldo) [inline tests/lib/rules/key-spacing.js]: I understand why this is the way it is, but I wonder if this actually makes sense?

Feels like it should be:
```
var obj = {
    foo  : 1,
    'bar': 2, baz: 3, longlonglong: 4
};
```
or
```
var obj = {
    foo: 1, 'bar'       : 2,
    baz: 3, longlonglong: 4
};
```

File: tests/lib/rules/key-spacing.js [hunk 4]
```diff
@@ -1769,5 +1904,206 @@ ruleTester.run("key-spacing", rule, {
...
+            "var obj = {",
+            "    foo : 1,",
+            "    'bar' : 2, baz : 3,",
+            "    longlonglong: 4",
+            "}"
+        ].join("\n"),
+        output: [
+            "var obj = {",
+            "    foo         : 1,",
+            "    'bar'       : 2, baz         : 3,",
```
Comment (kaicataldo) [inline tests/lib/rules/key-spacing.js]: Same comment as above

File: tests/lib/rules/key-spacing.js (hunk 2 above)
Comment (kaicataldo) [reply tests/lib/rules/key-spacing.js]: Thank you!

File: tests/lib/rules/key-spacing.js (hunk 4 above)
Comment (yeonjuan) [reply tests/lib/rules/key-spacing.js]: @kaicataldo 
Yes, I agree :)  Can I work on that in different PR?.
