### PR TITLE
Fix: Formatters keep trailing '.' if preceded by a space (fixes #9154)

### LINKED ISSUE #9154: Formatters sometimes omit important info from parser error messages
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 8.4.0
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

(no configuration)

**What did you do? Please include the actual source code causing the issue.**

I linted an invalid piece of JavaScript text which only consists of a single dot: `.`

```bash
$ echo '.' | eslint --stdin --no-eslintrc
```

**What did you expect to happen?**

I expected a parser error including the message `Unexpected token .`

**What actually happened? Please include the actual, raw output from ESLint.**

```
<text>
  1:1  error  Parsing error: Unexpected token
```

The `stylish` and `codeframe` formatters strip trailing `.` characters from report messages, presumably for stylistic reasons. However, this leads to confusing messages when the `.` is actually an important component of the message, rather than a period at the end of the sentence.

One way to address this would be to avoid removing the trailing `.` for `fatal` messages. Another solution would be to just stop removing trailing `.` characters entirely.

### PR DESCRIPTION
**Pull request by i-ron-y**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
For codeframe.js and stylish.js, I checked if the reported messages end with a " ." - if they do, the " ." is kept in the output. For "."s that aren't preceded by a space, the "." is removed in the output (how all "."s were handled by codeframe.js and stylish.js originally). I also added tests for the new behaviour.

**Is there anything you'd like reviewers to focus on?**
N/A

### CODE REVIEW

File: lib/formatters/codeframe.js [hunk 1]
```diff
@@ -47,7 +47,7 @@ function formatFilePath(filePath, line, column) {
  */
 function formatMessage(message, parentResult) {
     const type = (message.fatal || message.severity === 2) ? chalk.red("error") : chalk.yellow("warning");
-    const msg = `${chalk.bold(message.message.replace(/\.$/, ""))}`;
+    const msg = message.message.search(/ \.$/) >= 0 ? `${chalk.bold(message.message)}` : `${chalk.bold(message.message.replace(/\.$/, ""))}`;
```
Comment (not-an-aardvark) [inline lib/formatters/codeframe.js]: Nitpick: I think it would be simpler to do something like

```js
const msg = chalk.bold(message.message.replace(/[^ ]\.$/, "");
```

rather than using a ternary expression and another regex.

File: lib/formatters/stylish.js [hunk 2]
```diff
@@ -65,7 +65,7 @@ module.exports = function(results) {
                     message.line || 0,
                     message.column || 0,
                     messageType,
-                    message.message.replace(/\.$/, ""),
+                    message.message.search(/ \.$/) >= 0 ? message.message : message.message.replace(/\.$/, ""),
```
Comment (not-an-aardvark) [inline lib/formatters/stylish.js]: Nitpick: I think it would be simpler to do something like

```js
message.message.replace(/[^ ]\.$/, "")
```

rather than using a ternary expression and another regex.

**Comment by i-ron-y** [comment]
Hmm... I just tried it out and `message.message.replace(/[^ ]\.$/, "")` seems to be replacing both the character that precedes the full stop and the full stop with "". So "Unexpected foo." becomes "Unexpected fo".

**Comment by not-an-aardvark** [comment]
Oops, you're right. I think something like this would work:

```js
message.message.replace(/([^ ])\.$/, "$1")
```

Alternatively, instead of using `.search` you could use `endsWith`:

```js
message.message.endsWith(" .")
```

**Comment by i-ron-y** [comment]
That regex works perfectly, thank you so much!

Is it okay if I commit again with the sleeker code incorporating your solution?

**Comment by not-an-aardvark** [comment]
Sure, fine by me.

**Comment by not-an-aardvark** [comment]
Thanks for contributing!
