### PR TITLE
Fix: Indent rule errors with array of objects (fixes #3329)

### LINKED ISSUE #3329: Indent rule errors with array of objects
This issue appeared with v1.1.0.

Rule:
```yml
indent: [2, 2, {"SwitchCase": 1, "VariableDeclarator": 2}]
```

Code:
```js
var tests = [
  { host: 'a.com', cert: { subject: { CN: 'a.com' } } },
  { host: 'a.com', cert: { subject: { CN: 'A.COM' } } },
  {
    host: 'a.com',
    cert: { subject: { CN: 'b.com' } },
    error: 'Host: a.com. is not cert\'s CN: b.com'
  },
  { host: 'a.com', cert: { subject: { CN: 'a.com.' } } },
  { host: 'b.a.com', cert: { subject: { CN: '*.a.com' } } },
  {
    host: 'foo.com', cert: {
      subject: { CN: ['foo.com', 'bar.com'] }
    }
  }
];

```

Error:
```
   4:3  error  Expected indentation of 4 characters but found 2  indent
   5:5  error  Expected indentation of 6 characters but found 4  indent
   6:5  error  Expected indentation of 6 characters but found 4  indent
   7:5  error  Expected indentation of 6 characters but found 4  indent
   8:4  error  Expected indentation of 4 characters but found 2  indent
  11:3  error  Expected indentation of 4 characters but found 2  indent
  12:5  error  Expected indentation of 6 characters but found 4  indent
  15:4  error  Expected indentation of 4 characters but found 2  indent
```

Cross-reference: https://github.com/nodejs/io.js/pull/2286

### PR DESCRIPTION
**Pull request by BYK**
May not be the greatest fix for #3329 but it at least avoids double checking Array and Object expressions with conflicting rules so fixing the "infinite" or "unfixable" state that is caused by setting the `VariableDeclarator` option.

Now I'd argue that this is also the expected behavior but I leave that decision to the reviewers and the author of the issue.

### CODE REVIEW

File: lib/rules/indent.js [hunk 1]
```diff
@@ -119,7 +119,10 @@ module.exports = function(context) {
     function checkNodesIndent(nodes, indent, excludeCommas) {
         nodes.forEach(function(node) {
             var nodeIndent = getNodeIndent(node, false, excludeCommas);
-            if (nodeIndent !== indent && isNodeFirstInLine(node)) {
+            if (
```
Comment (gyandeeps) [inline lib/rules/indent.js]: Is there a way to make this additional check outside this function as this function is generic and is called from different portions of the code.

**Comment by gyandeeps** [comment]
@BYK I am not sure either as we are entering a zone where its legal for some people and illegal for some. Now it is becoming difficult to say what would this rule check for what not (under objects and arrays).

File: lib/rules/indent.js (hunk 1 above)
Comment (BYK) [inline lib/rules/indent.js]: I'm not really sure. I can probably filter `nodes` in `checkIndentInArrayOrObjectBlock` before passing here but the current implementation feels better since `ArrayExpression` and `ObjectExpression` nodes will be covered autoamtically (since they are defined in exports).

Does this make sense?

**Comment by BYK** [comment]
>@BYK I am not sure either as we are entering a zone where its legal for some people and illegal for some. Now it is becoming difficult to say what would this rule check for what not (under objects and arrays).

This really just fixes the double-check/report behavior. It still checks everything it used to (thanks to tests, I'm confident in that). I just added a new test case and left all existing ones intact which reassures me that this is a completely backwards-compatible change.

**Comment by BYK** [comment]
@gyandeeps anything you need me to do to move this forward?

**Comment by gyandeeps** [comment]
Looks good :+1:
