### PR TITLE
Fix: failed to parse `/*eslint` comments by colon (fixes #6224)

### LINKED ISSUE #6224: Definining the max-len rule with ignorePattern containing a colon inline in a file results in a JSON parsing error
**What version of ESLint are you using?**
2.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
In .eslintrc I have configured the max-len rule to be:
`"max-len": [2, 80, 2, {"ignoreUrls": true, "ignorePattern": "data:image\/|\\s*require\\s*\\(|^\\s*loader\\.lazy|-\\*-"}],`

**What did you do? Please include the actual source code causing the issue.**
I wanted to experiment with 100 long lines in just one file, and didn't want to change the global rule config in .eslintrc. So I tried added the following comment at the top of the file:

`/* eslint max-len: [2, 100, 2, {ignoreUrls: true, "ignorePattern": "data:image\/|\\s*require\\s*\\(|^\\s*loader\\.lazy|-\\*-"}] */`

**What did you expect to happen?**
I wanted the 100 config to be taken into consideration and the ignorePattern to be applied too.

**What actually happened? Please include the actual, raw output from ESLint.**
The following error message appears:

`Failed to parse JSON from ' "max-len": [2, 100, 2, {"ignoreUrls": true, "ignorePattern": "data":image\/|\\s*require\\s*\\(|^\\s*loader\\.lazy|-\\*-"}]': Unexpected token d`

It looks like the code in eslint that reads rule configuration inline in files tries to convert it to valid JSON and in doing so replaces `:` with `":` which, in my case, actually breaks the JSON because of the regex I use in ignorePattern which includes a `:` character.

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #6224.

It came to use Optionator to parse the comments by the same way as parsing CLI option. But Optionator cannot parse commaless notation, so there is a fallback for that.

Also, I just reordered requirements by file paths.

### CODE REVIEW

File: lib/eslint.js [hunk 1]
```diff
@@ -780,7 +813,7 @@ module.exports = (function() {
             }).forEach(function(key) {
                 var ruleCreator,
                     severity,
-                    options,
+                    ruleOptions,
```
Comment (mysticatea) [inline lib/eslint.js]: Just avoided shadowing.

File: lib/eslint.js [hunk 2]
```diff
@@ -9,25 +9,25 @@
...
-    assert = require("assert"),
-    CodePathAnalyzer = require("./code-path-analysis/code-path-analyzer");
-
-var DEFAULT_PARSER = require("../conf/eslint.json").parser;
+    Environments = require("./config/environments"),
+    CommentEventGenerator = require("./util/comment-event-generator"),
+    NodeEventGenerator = require("./util/node-event-generator"),
+    SourceCode = require("./util/source-code"),
+    Traverser = require("./util/traverser"),
+    options = require("./options"),
```
Comment (mysticatea) [inline lib/eslint.js]: I added `options = require("./options"),` for this fix.

**Comment by platinumazure** [comment]
Should we use `./options` rather than just pulling in levn or optionator directly? Using our wrapper seems like an unnecessary abstraction that just makes it harder to understand what's going on.

File: lib/eslint.js [hunk 3]
```diff
@@ -70,6 +70,25 @@ function parseBooleanConfig(string, comment) {
     return items;
 }
 
+var VALID_LEVELS = [0, 1, 2, "off", "warn", "error"];
```
Comment (nzakas) [inline lib/eslint.js]: We use the term "severity" in most places, instead of "level".

File: lib/eslint.js [hunk 4]
```diff
@@ -80,11 +99,26 @@ function parseBooleanConfig(string, comment) {
 function parseJsonConfig(string, location, messages) {
     var items = {};
 
+    // Parses a JSON-like comment by the same way as parsing CLI option.
+    try {
+        items = options.parse(["", "", "--rule", string]).rule || {};
+
+        // Some tests say that it should ignore invalid comments such as `/*eslint no-alert:abc*/`.
+        if (levelsAreValid(items)) {
+            return items;
```
Comment (nzakas) [inline lib/eslint.js]: Does `else` fall through and reparse?

File: lib/eslint.js [hunk 5]
```diff
@@ -70,6 +70,25 @@ function parseBooleanConfig(string, comment) {
...
 
+var VALID_LEVELS = [0, 1, 2, "off", "warn", "error"];
+
+/**
+ * Checks whether all rules' level is valid or not.
+ *
+ * @param {object} config - A config object to check.
+ * @returns {boolean} `true` if all rules' level is valid.
+ */
+function levelsAreValid(config) {
```
Comment (nzakas) [inline lib/eslint.js]: Maybe `isInlineConfigValid`?

Also, maybe create `ConfigOps.isValidSeverity()` to keep that logic in one place?

File: lib/eslint.js (hunk 4 above)
Comment (mysticatea) [inline lib/eslint.js]: Yes, I added comments to explain this.

**Comment by mysticatea** [comment]
- I changed `options.parse` to `levn.parse`. Levn is the parser Optionator is using, so this doesn't add any dependency.
- I moved a function to check severity to `config-ops.js`.

File: lib/config/config-ops.js [hunk 6]
```diff
@@ -248,6 +249,30 @@ module.exports = {
...
+        }
+        return VALID_SEVERITIES.indexOf(severity) !== -1;
+    },
+
+    /**
+     * Checks whether every rule of a given config has valid severity or not.
+     * @param {object} config - The configuration for rules.
+     * @returns {boolean} `true` if the configuration has valid severity.
+     */
+    isEveryValidSeverify: function(config) {
```
Comment (platinumazure) [inline lib/config/config-ops.js]: I think you might want `isEverySeverityValid` here.

File: lib/eslint.js [hunk 7]
```diff
@@ -80,6 +80,25 @@ function parseBooleanConfig(string, comment) {
...
 
+    // Parses a JSON-like comment by the same way as parsing CLI option.
+    try {
+        items = levn.parse("Object", string) || {};
+
+        // Some tests say that it should ignore invalid comments such as `/*eslint no-alert:abc*/`.
+        // Also, commaless notations have invalid severity:
+        //     "no-alert: 2 no-console: 2" --> {"no-alert": "2 no-console:2"}
+        // Should ignore that case as well.
+        if (ConfigOps.isEveryValidSeverify(items)) {
```
Comment (platinumazure) [inline lib/eslint.js]: I realize this if statement shouldn't throw, but should this be outside the try block anyway just to be safe? (If the condition is prefixed with `items &&`, I think it can be done safely.)

**Comment by platinumazure** [comment]
Thanks! Really appreciate the switch to levn, it feels more semantically accurate. I threw in a couple of comments for some small questions I had, but they're really small things and overall this looks great.

File: lib/config/config-ops.js (hunk 6 above)
Comment (mysticatea) [inline lib/config/config-ops.js]: Thank you, I renamed it.
In fact, I was worried about this name :smile:

File: lib/eslint.js (hunk 7 above)
Comment (mysticatea) [inline lib/eslint.js]: The target of this check is the result of `levn.parse`, so I think this should inside of this `try` block since this location will be executed only if `levn.parse` succeeded.

**Comment by nzakas** [comment]
Lgtm
