### PR TITLE
Fix: add warnIgnored flag to CLIEngine.executeOnText (fixes #6302)

### LINKED ISSUE #6302: Option to suppress ignored file warnings
Using version 2.10.2 with browserify via eslintify.  All files that our code 'require( )'s gets passed into eslint.  This includes things that should be ignored such as npm or bower packages.  Currently, this results in a bunch of warnings about ignored files which aren't really useful in this case.  Ideally, eslint would have an option to suppress ignored file warnings.   

Since eslintify is calling `executeOnText`, a `warnIgnored` parameter added here would probably be a quick fix: https://github.com/eslint/eslint/blob/c10c07f0eec529ea055e8d95d9f9899228274911/lib/cli-engine.js#L745

See also https://github.com/yaycmyk/eslintify/pull/10

### PR DESCRIPTION
**Pull request by robertlevy**
added a warnIgnored parameter to executeOnText similar to the existing executeOnFile function.  the check is for an explicit `false` parameter so this doesn't break existing code

### CODE REVIEW

File: lib/cli-engine.js [hunk 1]
```diff
@@ -754,8 +755,7 @@ CLIEngine.prototype = {
         if (filename && !isAbsolute(filename)) {
             filename = path.resolve(options.cwd, filename);
         }
-        if (filename && ignoredPaths.contains(filename)) {
-
+        if (filename && warnIgnored !== false && ignoredPaths.contains(filename)) {
```
Comment (nzakas) [inline lib/cli-engine.js]: This works the opposite of how the `executeOnFile` version works. We always have optional arguments default to `false`, so we have to have that here as well. A bit concerned that this would result in a breaking change though. :-/

Comment (robertlevy) [inline lib/cli-engine.js]: yeah, i figured that having a default of true would be preferred to a breaking change.  i'd be happy to update the code throughout this repo to explicitly pass in `true` and have the default be `false` but 3rd party code calling `executeOnText` directly would stop getting these warnings until they added the `true` parameter

**Comment by robertlevy** [comment]
@nzakas by adding the breaking tag i assume that means you'd like me to switch this around so the default is true?

**Comment by nzakas** [comment]
The breaking label was added so people are aware that there is a discussion about a breaking change on this pull request. If you have a suggestion for how to do this without a breaking change, we can evaluate that, but we can't accept the current PR because it doesn't follow our guidelines for optional arguments.

**Comment by nzakas** [comment]
@eslint/eslint-team thoughts on whether this is worth a breaking change? I'm leaning towards "yes" here, but would like some other opinions.

**Comment by ilyavolodin** [comment]
Don't have a strong opinion, but it's seems a little to default it to `true`.

**Comment by platinumazure** [comment]
@ilyavolodin Missing a key word there-- seems a little what?

**Comment by robertlevy** [comment]
updated this to have the default be false (more intuitive and consistent) despite being a breaking change

**Comment by nzakas** [comment]
I'm feeling more and more that this is the right choice even though it's breaking.

@robertlevy can you also add a bit to the docs here: https://github.com/eslint/eslint/blob/master/docs/developer-guide/nodejs-api.md#executeontext

**Comment by platinumazure** [comment]
@nzakas Given how the JSCS Compatibility goals have supplanted most of what is on the 3.0 roadmap, is it work cutting a 3.0 release fairly soon and moving most of the 3.0 roadmap issues to 4.0?

**Comment by nzakas** [comment]
Yeah, that's what I'm thinking. We have a few very small breaking changes that I think would be good to merge and release. I'll throw together an issue to discuss.

**Comment by robertlevy** [comment]
@nzakas docs appended

File: docs/developer-guide/nodejs-api.md [hunk 2]
```diff
@@ -310,6 +310,8 @@ var report = cli.executeOnText("var foo = 'bar';", "foo.js");
 
 The `report` returned from `executeOnText()` is in the same format as from `executeOnFiles()`, but there is only ever one result in `report.results`.
 
+This function will return no errors or warnings if filename provided in the optional 2nd parameter matches a file that is configured to be ignored.  Pass `true` as the optional 3rd parameter to have a warning generated when this happens.
```
Comment (pedrottimark) [inline docs/developer-guide/nodejs-api.md]: @robertlevy Here is wording for how I interpreted the cause-and-effect relationship, but not sure if it is correct:

If a filename in the optional second parameter matches a file that is configured to be ignored, then this function returns no errors or warnings. To return a warning instead, call the method with `true` as the optional third parameter.

If the preceding is unusable, here are incremental suggestions about wording in the original:
* if the filename in the optional second parameter
* Call the method with `true` as the optional third parameter

Comment (nzakas) [inline docs/developer-guide/nodejs-api.md]: Also, please use "second" and "third" instead of 2nd and 3rd.

**Comment by nzakas** [comment]
@robertlevy can you take care of the doc fixes so we can merge this?

**Comment by nzakas** [comment]
Lgtm. Thanks!

**Comment by vitorbal** [comment]
Hi @joshkel, I don't think what you are describing was the desired behavior at all, so we should investigate it. Could you please open a bug ticket so we can move the discussion there?

**Comment by joshkel** [comment]
Added as #6611. Thanks.
