### PR TITLE
fix: rule tester ignore irrelevant test case properties

### LINKED ISSUE #18173: Change Request: Rule Tester omit specific properties for duplicate test case detection
### ESLint version

8.57.0

### What problem do you want to solve?

The RuleTester currently stringifies all test case properties for each test case to check for duplicate test cases (see [here](https://github.com/eslint/eslint/blob/main/lib/rule-tester/rule-tester.js#L866)).
This means some duplicate test cases are not discovered.
Test cases with different `name`s:
```javascript
ruleTester.run('rule', rule, {
	valid: [
		{ code: 'code' },
		{ name: 'name', code: 'code' },
	],
	invalid: [],
}),
```

Test cases with a different error matcher:
```javascript
ruleTester.run('rule', rule, {
	valid: [],
	invalid: [	
		{ code: 'code', errors: 1 },
		{ code: 'code', errors: [{ messageId: 'id' }] },
	],
}
```

Not fixable test cases one specifying `output` and the other not:
```javascript
ruleTester.run('rule', rule, {
	valid: [],
	invalid: [	
		{ code: 'code', errors: 1, output: null },
		{ code: 'code', errors: 1 },
	],
}
```

### What do you think is the correct solution?

The used serialize package offers a [replacer](https://github.com/samn/json-stable-stringify#replacer) method which could exclude the properties `name`, `errors` and `output`.
The other Rule Tester specific property is `only` but I do not think that developers want to be warned about duplicate test cases when focusing on a test case.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by DMartens**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x] Other, please explain: Rule Tester

#### What changes did you make? (Give an overview)
Fixes #18173.
Ignore the properties `name`, `errors` and `output` as they are irrelevant when checking for duplicate test cases by using the replacer argument of the JSON stringifier.
Unfortunately the custom JSON stringifier does not support the array form of the `JSON.stringify` replacer.
Also normalized valid string test cases to the object form, as otherwise the following would not be detected:
```javascript
ruleTester.run('Undetected', rule, {
	valid: [
		'same',
		{ code: 'same' },
	],
	invalid: [],
})
```

#### Is there anything you'd like reviewers to focus on?
Some additional duplicate test cases of core rules were flagged and I tried to resolve the errors the best I could.
For example some test cases checked only the location and later other properties were tested.
Rather than merging the test cases, I opted to change the identifier names to keep the intent of the test cases.

### CODE REVIEW

File: tests/lib/rules/accessor-pairs.js [hunk 1]
```diff
@@ -1047,10 +1047,10 @@ ruleTester.run("accessor-pairs", rule, {
 
         // Full location tests
         {
-            code: "var o = { get a() {} };",
+            code: "var o = { get b() {} };",
```
Comment (aladdin-add) [inline tests/lib/rules/accessor-pairs.js:1050]: Is this test the same as some other one? If so, we can just remove it.

File: tests/lib/rules/accessor-pairs.js [hunk 2]
```diff
@@ -1831,11 +1831,11 @@ ruleTester.run("accessor-pairs", rule, {
             }]
         },
         {
-            code: "class A { static get a() {} };",
+            code: "class A { static get b() {} };",
```
Comment (aladdin-add) [inline tests/lib/rules/accessor-pairs.js:1834]: same here.

File: tests/lib/rules/no-useless-backreference.js [hunk 3]
```diff
@@ -162,9 +162,9 @@ ruleTester.run("no-useless-backreference", rule, {
             }]
         },
         {
-            code: String.raw`/\k<foo>(?<foo>a)/`,
+            code: String.raw`/\k<foo>(?<foo>bar)/`,
```
Comment (aladdin-add) [inline tests/lib/rules/no-useless-backreference.js:165]: same here.

**Review by aladdin-add — CHANGES_REQUESTED** [review]
just a question about the tests, otherwise LGTM! 👍

File: lib/rule-tester/rule-tester.js [hunk 4]
```diff
@@ -863,7 +872,8 @@ class RuleTester {
                 return;
             }
 
-            const serializedTestCase = stringify(item);
+            const normalizedItem = typeof item === "string" ? { code: item } : item;
+            const serializedTestCase = stringify(normalizedItem, { replacer: (key, value) => (!duplicationIgnoredParameters.has(key) ? value : void 0) });
```
Comment (mdjermanovic) [inline lib/rule-tester/rule-tester.js:876]: We should only exclude top-level test case properties. Otherwise, if the rule has options with these names, test cases like the following would be mistakenly detected as duplicates:

```js
{
    code: "var foo;",
    options: [{ name: "bar" }]
},
{
    code: "var foo;",
    options: [{ name: "baz" }]
}
```

**Review by mdjermanovic — CHANGES_REQUESTED** [review]

File: tests/lib/rules/accessor-pairs.js (hunk 1 above)
Comment (DMartens) [reply tests/lib/rules/accessor-pairs.js:1050]: This is what I meant trying to "resolve" the found duplicate test cases.
In this case there is a comment above that the following tests are for the error location.
As such I just renamed the identifier to keep the test cases intent.
The other options are just removing or merging the test cases.

File: lib/rule-tester/rule-tester.js (hunk 4 above)
Comment (DMartens) [reply lib/rule-tester/rule-tester.js]: Good catch. I resolved this via checking whether the current context object `this` is the root test case object.

File: tests/lib/rules/accessor-pairs.js (hunk 1 above)
Comment (aladdin-add) [reply tests/lib/rules/accessor-pairs.js:1050]: it sounds safe to remove the other one - it should have been covered by this one.

Comment (DMartens) [reply tests/lib/rules/accessor-pairs.js:1050]: All the duplicates were found because different error properties were tested, e.g. one test case for the message and one for the error location.
As such a part of the tests would be lost when deleting one of the test cases.
I thought the easiest solution would be to rename the identifier to keep the test case grouping intact.
Another solution would be to add the missing error properties for all the test cases.

Comment (aladdin-add) [reply tests/lib/rules/accessor-pairs.js:1050]: > Another solution would be to add the missing error properties for all the test cases.

👍 exactly what I mean to. :)

Comment (aladdin-add) [reply tests/lib/rules/accessor-pairs.js:1050]: adding `type` in this one, so that one can be removed.

https://github.com/eslint/eslint/blob/56d7198484d9f87b62fb1323174154a311fee305/tests/lib/rules/accessor-pairs.js#L636-L638

Comment (aladdin-add) [reply tests/lib/rules/accessor-pairs.js:1050]: > I thought the easiest solution would be to rename the identifier to keep the test case grouping intact.

It's more like a workaround, not a solution.

The question here is: do we allow/encourage users to write such tests?

Comment (DMartens) [reply tests/lib/rules/accessor-pairs.js:1050]: I think we should *allow* users to write these kinds of tests but not *encourage* it.
I think the majority of developers want to detect this but as I said there are various ways to resolve this and each developer may choose a different way.

Comment (mdjermanovic) [reply tests/lib/rules/accessor-pairs.js:1050]: > The question here is: do we allow/encourage users to write such tests? If yes, we may not ignore the `errors`, instead of letting users use a workaround.

I think it's useful to detect tests that have the same input (code + options + config) because they might have been unintentional duplicates. And I think it's okay to use the workaround to modify the input a bit to avoid duplicates when the intent is to group test cases by differents kinds of assertions. We'll see feedback from users when we release this.

**Review by aladdin-add — DISMISSED** [review]
LGTM, thanks! Would like another review before merging.

File: tests/lib/rules/no-unused-vars.js [hunk 5]
```diff
@@ -1461,21 +1461,16 @@ ruleTester.run("no-unused-vars", rule, {
...
-            code: "const a = () => { a(); };",
-            languageOptions: { ecmaVersion: 2015 },
-            errors: [assignedError("a")]
+            errors: [{ ...assignedError("a"), line: 1, column: 5 }]
         },
         {
             code: "const a = () => () => { a(); };",
             languageOptions: { ecmaVersion: 2015 },
-            errors: [assignedError("a")]
+            errors: [{ ...assignedError("a") }]
```
Comment (mdjermanovic) [inline tests/lib/rules/no-unused-vars.js:1473]:
```suggestion
            errors: [{ ...assignedError("a"), line: 1, column: 7 }]
```
