### PR TITLE
fix: retry on EMFILE when writing autofix results

### LINKED ISSUE #19924: Bug: running `--fix` throws EMFILE: too many open files
### Environment

Node version: 22.11.0
npm version: 10.9.0
Local ESLint version: 9.28.0
Global ESLint version: 9.28.0
Operating System: Windows

### What parser are you using?

Default (Espree)

### What did you do?

eslint ./ --fix

### What did you expect to happen?

All files with auto-fixable issues are fixed.

### What actually happened?

Running `--fix` command in a big repository with 106152 problems and 103.985 auto-fixable issues across ~9000 files. 
I constantly get EMFILE: too many open files error:
`at async open (node:internal/fs/promises:638:25)
    at async Object.writeFile (node:internal/fs/promises:1208:14)
    at async Promise.all (index 8189)
    at async ESLint.outputFixes (...\node_modules\eslint\lib\eslint\eslint.js:534:3)
    at async Object.execute (...\node_modules\eslint\lib\cli.js:642:4)
    at async main (...\node_modules\eslint\bin\eslint.js:175:19)`
https://github.com/eslint/eslint/blob/main/lib/eslint/eslint.js#L533 this happens here!

### Link to Minimal Reproducible Example

/

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Is there a workaround I can set that will work on windows and linux. 
As a QA engineer, I am providing a list of rules and configurations for ESLint for different implementation teams within our company.  Which means all rules will be applied from 0 only once.

### PR DESCRIPTION
**Pull request by TKDev7**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Added retry logic to the `outputFixes` method to handle EMFILE errors when writing autofix results. This prevents ESLint from crashing if the system runs out of file descriptors during autofix operations.

Fixes #19924

### CODE REVIEW

File: tools/check-emfile-handling.js [hunk 1]
```diff
@@ -102,6 +102,13 @@ execSync(
 );
 console.log("✅ No errors encountered running ESLint.");
 
+console.log("Running ESLint with --fix...");
+execSync(
+	`node bin/eslint.js ${OUTPUT_DIRECTORY} --fix --no-config-lookup --rule "eol-last: [error, always]"`,
+	{ stdio: "inherit" },
+);
+console.log("✅ No errors encountered running ESLint with --fix.");
```
Comment (fasttime) [inline tools/check-emfile-handling.js]: I think it's not necessary to run ESLint twice. We could run it just once with the `--fix` option.

Also, the [`eol-last`](https://eslint.org/docs/latest/rules/eol-last) rule is deprecated, so it's probably better to use a different one for testing. It's also fine to change the content of the generated files to make sure it gets autofixed by one of the rules in the current config:

https://github.com/eslint/eslint/blob/f82e152b4300b067ab5870c73b5f10a8002eaa80/tools/check-emfile-handling.js#L66

**Review by fasttime — COMMENTED** [review]
The logic LGMT. I left a comment about the test.

File: tools/check-emfile-handling.js (hunk 1 above)
Comment (TKDev7) [reply tools/check-emfile-handling.js]: Done!

**Review by fasttime — APPROVED** [review]
LGTM, thanks!

**Review by sins921 — APPROVED** [review]
