### PR TITLE
Update: fix counting jsx comment len in max-len (fixes #12213)

### LINKED ISSUE #12213: max-len: comments: ignores JSX
**Tell us about your environment**

* **ESLint Version:**
^6.1.0
* **Node Version:**
12.9.0
* **npm Version:**
6.9.0
**What parser (default, Babel-ESLint, etc.) are you using?**
"@typescript-eslint/parser": ^2.0.0
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
env:
  #https://medium.com/@jzarzoso/setting-eslint-on-meteor-for-react-development-10af658b44e2
  browser: true
  jest/globals: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "hardcore-fp"
  - "plugin:jest/recommended"
  - "plugin:react/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
#  project: "./tsconfig.json"
  ecmaVersion: "2019"
  sourceType: module
plugins:
  - "@typescript-eslint/eslint-plugin"
  - jest
  - react
  - react-hooks
  - promise
overrides:
  - files:
      - "*.test.js"
      - "*.spec.js"
    rules:
      fp/no-unused-expression: "off"
rules:
  "@typescript-eslint/camelcase": off
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
  "@typescript-eslint/interface-name-prefix":
    - error
    - prefixWithI: always
  "@typescript-eslint/no-use-before-define": off
  arrow-body-style: "off"
  camelcase: off
  comma-dangle: "off"
  fp/no-mutating-methods:
    - error
    # Allow reassign Lodash methods
    - allowedObjects:
        - _
  fp/no-mutation:
    - error
    # Allow module.exports
    - commonjs: true
      allowThis: false
      # Allow assigning to window global
      exceptions:
        - object: window
#  fp/no-nil: "off"
  fp/no-unused-expression: "off"
  func-style: warn
  id-length:
    - warn
    - exceptions:
        - e
        - f
        - i
        - v
        - x
        - "y"
        - z
  id-match:
    - error
    - "^[a-zA-Z_]*$"
    - properties: true
  indent: off
  lines-around-comment:
    - warn
    - ignorePattern: /prettier-ignore/
  max-len:
    - warn
    - code: 90
      comments: 120
      tabWidth: 2
      ignorePattern: "import"
      ignoreUrls: true
  max-params:
    - error
    - 6
  multiline-ternary: "off"
  new-cap: off
  no-inline-comments: "off"
  no-magic-numbers:
    - error
    - ignore:
        - 0
        - 1
  no-multi-spaces: "off"
  no-return-await: off
  no-param-reassign:
    - error
    - props: true
  no-nested-ternary: "off"
  no-shadow:
    - error
    - builtinGlobals: true
  no-warning-comments: warn
  no-undef: error
  no-unneeded-ternary: "off"
  no-unused-vars: warn
  no-use-before-define: "off"
  object-curly-newline: "off"
  one-var: off
  operator-linebreak:
    - error
    - before
    - overrides:
        =: ignore
  padding-line-between-statements: "off"
  radix: "off"
  react/no-string-refs:
    - error
    - noTemplateLiterals: true
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/display-name: "off"
  react/prop-types: "off"
  semi: warn
settings: {}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
export function ScoringResultsItem() {
  return (
    <List.Item>
      <Checkbox checked={state.checked}>
        <Avatar src={bankDatum.logoURL} />
        {/* Some really really really really really really really really really long comment */}
        <a href={bankDatum.PAURL} target="_blank">
          {bankDatum.name}
        </a>
      </Checkbox>
    </List.Item>
  );
}

```

```bash
eslint foo.js
```

**What did you expect to happen?**
no warnings logged

**What actually happened? Please include the actual, raw output from ESLint.**
`6:1   warning  This line has a length of 96. Maximum allowed is 90                                                                           max-len`

**Are you willing to submit a pull request to fix this bug?**
nope

### PR DESCRIPTION
**Pull request by yeonjuan**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
This pr will fix #12213.

If the comment is in the single line jsx comment, change the comment node for checking with JSXExpressionContainer. 

ex)

```jsx
<>
  {/* comment */}
</>
```

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by kaicataldo** [comment]
CI is failing because of the issue reported [here](https://github.com/eslint/eslint/pull/12662).

**Comment by yeonjuan** [comment]
@kaicataldo sure!

**Comment by yeonjuan** [comment]
@kaicataldo Friendly ping :)

File: lib/rules/max-len.js [hunk 1]
```diff
@@ -183,6 +183,23 @@ module.exports = {
...
+
+            if (!node || !node.parent || node.type !== "JSXEmptyExpression" || node.parent.type !== "JSXExpressionContainer") {
+                return false;
+            }
+
+            const parent = node.parent;
+
+            return parent.loc.start.line === parent.loc.end.line;
+        }
+
```
Comment (mdjermanovic) [inline lib/rules/max-len.js]: I'm not sure what would be correct behavior when there are two comments inside, like `{ /* 1 */ /* 2 */ }`.

A small difference is that this is now a `valid` comment-only line:

```js
{
    code: "var jsx = (<>\n" +
         "  {/* this line has > 20 characters */ /* but < 100 */}\n" +
         "</>)",
    options: [{ code: 20, comments: 100 }],
    parserOptions: { ecmaFeatures: { jsx: true } }
}
```

while this is `invalid`, because a line with two comments is treated as a 'code' line:

```js
{
    code: "var foo = \n" +
        "  /* this line has > 20 characters */ /* but < 100 */\n" +
        "5;",
     options: [{ code: 20, comments: 100 }],
     errors: 1 // "This line has a length of 53. Maximum allowed is 20."
}
```

Thoughts? Maybe this doesn't matter as much.

Comment (yeonjuan) [reply lib/rules/max-len.js]: Although it needs to be evaluated by eslint members, In my opinion, the second case looks like a bug. :)

File: lib/rules/max-len.js [hunk 2]
```diff
@@ -305,6 +322,11 @@ module.exports = {
                     // and step back by one
                     comment = comments[--commentsIndex];
 
+                    // check jsx comment
+                    if (isCommentInSingleLineJSXEmptyExpression(comment)) {
+                        comment = sourceCode.getNodeByRangeIndex(comment.range[0]).parent;
+                    }
```
[the remark this answers is not in the document]
Comment (yeonjuan) [reply lib/rules/max-len.js]: > This might execute relatively costly isCommentInSingleLineJSXEmptyExpression on some irrelevant comments like those inside code, but could end up being more optimal because the do-while loop in lines.forEach often gets back to the same comment, if I correctly understand the loop?

Thanks for the always careful review! I agree and, I'll care of it.

File: lib/rules/max-len.js (hunk 1 above)
Comment (mdjermanovic) [reply lib/rules/max-len.js]: I agree and would vote to do with JSX comments whatever seems to be easier for the other problem (with trailing comments).

**Comment by yeonjuan** [comment]
@kaicataldo 
Thanks!. I added more test cases you mentioned. 
But Maybe there would be no change in those cases compared with the actual version.

@mdjermanovic 
I changed the code and commit.  Thanks! :)

File: tests/lib/rules/max-len.js [hunk 3]
```diff
@@ -650,6 +734,204 @@ ruleTester.run("max-len", rule, {
...
+                    line: 2,
+                    column: 1
+                }
+            ]
+        },
+        {
+            code: "var jsx = (<>\n" +
+                  "{ 38/* this line has 38 characters */}\n" +
+                  "</>)",
+            options: [15, { comments: 37 }],
```
Comment (mdjermanovic) [inline tests/lib/rules/max-len.js]: This could be `comments: 38` to show that line fails because it isn't a comment?

Also, it feels like some tests with an expression (`a && b`) + comment inside `{}` might be missing `ignoreTrailingComments: true` or `ignoreComments: true` to show that this doesn't count as a comment?

And I think (could be wrong) that there is no test where there is only a comment inside `{}`, but `{` and `}` are not on the same line so it doesn't count as a comment because of that.

Comment (yeonjuan) [reply tests/lib/rules/max-len.js]: Sure!

Comment (yeonjuan) [reply tests/lib/rules/max-len.js]: @mdjermanovic 
Humm.. what do you think about this case? A multi-line comment in JSXEmptyExpression should be treated as a code?
```jsx
var jsx = (<foo>
     {/* multiline comment
         without code */ }
</foo>);
```
so if then, Should I treat the case below as an invalid?
```
 {
     code: "var jsx = (<>\n" +
                  "  {/*  multi-line          comment\n" +
                  "                   but it is a code ? */ }\n"
                  "</>)",
    options: [20, { ignoreComments: true }],
    parserOptions: { ecmaFeatures: { jsx: true } }
 }
```

Comment (yeonjuan) [reply tests/lib/rules/max-len.js]: @mdjermanovic 
> I think the decision to treat the whole { /* */ } as a comment only if everything incl. braces is on the same line is a good decision, since it's a minimal change in behavior.

Humm, I'm confusing 🤔
Maybe treating the whole {/* ... *} as a comment in this PR would be better? ( and change tag `fix` to `update`)

Comment (mdjermanovic) [reply tests/lib/rules/max-len.js]: Sorry for the confusion! Just wanted to say that I agree that only those `{/* */}` where everything is on the same line should be treated as comments, as you already implemented with the `parent.loc.start.line === parent.loc.end.line` condition :+1:

File: lib/rules/max-len.js [hunk 4]
```diff
@@ -183,6 +183,21 @@ module.exports = {
...
+         * @returns {boolean} True if the node is a JSXEmptyExpression contained in a single line JSXExpressionContainer.
+         */
+        function isJSXEmptyExpressionInSingleLineContainer(node) {
+            if (!node || !node.parent || node.type !== "JSXEmptyExpression" || node.parent.type !== "JSXExpressionContainer") {
+                return false;
+            }
+
+            const parent = node.parent;
+
+            return parent.loc.start.line === parent.loc.end.line;
```
[the remark this answers is not in the document]
Comment (yeonjuan) [reply lib/rules/max-len.js]: @mdjermanovic 
Thanks. you are definitely right. :)

**Comment by kaicataldo** [comment]
I think it's fine to accept this as a semver-minor bug fix (though, in practice I'm not sure it matters since we are merging breaking changes in preparation for v8 right now).

**Comment by kaicataldo** [comment]
Thanks for contributing to ESLint!
