### PR TITLE
Fix: Ensure ./ works correctly with CLI (fixes #3792)

### LINKED ISSUE #3792: with ESLint 1.4.x `eslint ./` will lint all files on a drive
With eslint 1.4.x a new globbing matcher was introduced and the `processPath()` method used to pass it an appropriate glob has introduced a bug whereby a relative path to the current directory in the form of `./` would end up with a glob of `/**/*.js` - in effect searching from the root of the drive.

To resolve this, it may be better, instead of replacing the `./` in `processPath()`, to use `path.normalize()`.

I've added a console.log to cli-engine.js at CLIEngine.prototype.executeOnFiles:

```js 
console.log('before processing pattern is:', patterns);
patterns = patterns.map(processPath(extensions));
console.log('after processing pattern is:', patterns);
```

With the current code:

```
[~/src/testrepo]$ ./node_modules/eslint/bin/eslint.js ./ ../ .
before processing pattern is: [ './', '../', '.' ]
after processing pattern is: [ '/**/*.js', '..//**/*.js', '**/*.js' ]
```

Note that the first pattern passed in, `./` is transformed to `/**/*.js`

With the `path.normalize()` fix:

```
[~/src/testrepo]$ ./node_modules/eslint/bin/eslint.js ./ ../ .
before processing pattern is: [ './', '../', '.' ]
after processing pattern is: [ '**/*.js', '../**/*.js', '**/*.js' ]
```

To summarise:

1. Run `eslint ./`
2. Expected result: JS files in the current directory are linted
3. Actual result: All JS files on the drive are linted
4. Suggested fix: use `path.normalize()` in favour of replacing `./` at the start of a path.

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

File: lib/cli-engine.js [hunk 1]
```diff
@@ -467,6 +468,20 @@ CLIEngine.prototype = {
     },
 
     /**
+     * Resolves the patterns passed into executeOnFiles() into glob-based patterns
+     * for easier handling.
+     * @param {string[]} patterns The file patterns passed on the command line.
+     * @returns {string[]} The equivalent glob patterns.
+     */
+    resolveFileGlobPatterns: function(patterns) {
```
Comment (BYK) [inline lib/cli-engine.js]: Heh, nice trick for testing :+1:

**Comment by BYK** [comment]
Looks great to me.
