### PR TITLE
Fix: `no-extra-parens` incorrect precedence (fixes #7978)

### LINKED ISSUE #7978: no-extra-parens handles precedence incorrectly in some cases
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 7.4.0
* **npm Version:** 4.0.5

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```yml
rules:
  no-extra-parens: error
parserOptions:
  ecmaVersion: 2016
```

**What did you do? Please include the actual source code causing the issue.**

```js
(new Foo)();

-(foo ** bar);

(-foo) ** bar;
```

**What did you expect to happen?**

I expected no errors to be reported, because removing parentheses from each of those cases results in a change in behavior or a syntax error.

**What actually happened? Please include the actual, raw output from ESLint.**

3 errors were reported:

```
<text>
  1:1  error  Gratuitous parentheses around expression  no-extra-parens
  3:2  error  Gratuitous parentheses around expression  no-extra-parens
  5:1  error  Gratuitous parentheses around expression  no-extra-parens
```

### PR DESCRIPTION
**Pull request by alberto**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Fix bug https://github.com/eslint/eslint/issues/7978

**Is there anything you'd like reviewers to focus on?**
No.

### CODE REVIEW

File: lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -168,6 +168,18 @@ module.exports = {
...
         /**
+         * Determines if a constructor function is newed-up with parens
+         * @param {ASTNode} newExpression - The NewExpression node to be checked.
+         * @returns {boolean} True if the constructor is called with parens.
+         * @private
+         */
+        function isNewExpressionWithParens(newExpression) {
+            const lastToken = sourceCode.getLastToken(newExpression);
+
+            return lastToken.value === ")";
```
Comment (not-an-aardvark) [inline lib/rules/no-extra-parens.js]: This function will incorrectly return `true` for

```js
new (Foo)
```

As a result, the rule still incorrectly reports the following code, even with this patch:

```js
(new (Foo || Bar))()
```

I think the correct way to do this is to check the second-to-last token as well, like the implementation in [new-parens](https://github.com/eslint/eslint/blob/df2351a695462d9490f665119a7153157bd16ef3/lib/rules/new-parens.js).

File: tests/lib/rules/no-extra-parens.js [hunk 2]
```diff
@@ -120,6 +121,8 @@ ruleTester.run("no-extra-parens", rule, {
         "a(b)(c)",
         "a((b, c))",
         "new new A",
+        { code: "1 ** 2 ** 3", parserOptions: { ecmaVersion: 7 } },
+        { code: "1 ** (2 ** 3)", parserOptions: { ecmaVersion: 7 } },
```
Comment (not-an-aardvark) [inline tests/lib/rules/no-extra-parens.js]: This should be invalid -- the parens are unnecessary in that case because `**` is right-associative.

```js
2 ** 3 ** 4

// is equivalent to

2 ** (3 ** 4)
```

So the existing rule also behaves incorrectly in this case:

```js
(2 ** 3) ** 4 // this should be valid
```

**Comment by alberto** [comment]
Good catch @not-an-aardvark, thanks!
Let me know if you think it's ok now.

File: lib/rules/no-extra-parens.js [hunk 3]
```diff
@@ -395,13 +413,14 @@ module.exports = {
          */
         function dryBinaryLogical(node) {
             const prec = precedence(node);
-            const shouldSkipLeft = NESTED_BINARY && (node.left.type === "BinaryExpression" || node.left.type === "LogicalExpression");
+            const shouldSkipLeft = (NESTED_BINARY && (node.left.type === "BinaryExpression" || node.left.type === "LogicalExpression")) ||
+              node.left.type === "UnaryExpression" && node.operator === "**";
             const shouldSkipRight = NESTED_BINARY && (node.right.type === "BinaryExpression" || node.right.type === "LogicalExpression");
 
-            if (!shouldSkipLeft && hasExcessParens(node.left) && precedence(node.left) >= prec) {
+            if (!shouldSkipLeft && hasExcessParens(node.left) && (precedence(node.left) > prec || (precedence(node.left) === prec && node.operator !== "**"))) {
```
Comment (not-an-aardvark) [inline lib/rules/no-extra-parens.js]: Instead of adding a special case here for `**`, I think it would be better to update the precedence function in `ast-utils` to give `**` a higher precedence. (The function already gives `*` and `/` a higher precedence than `+` and `-`.)

Comment (alberto) [inline lib/rules/no-extra-parens.js]: Oh, I thought precendence was already set for exponentiation. I added the conditions to deal with the right associative nature of `**`.

File: lib/rules/no-extra-parens.js [hunk 4]
```diff
@@ -395,13 +413,14 @@ module.exports = {
          */
         function dryBinaryLogical(node) {
             const prec = precedence(node);
-            const shouldSkipLeft = NESTED_BINARY && (node.left.type === "BinaryExpression" || node.left.type === "LogicalExpression");
+            const shouldSkipLeft = (NESTED_BINARY && (node.left.type === "BinaryExpression" || node.left.type === "LogicalExpression")) ||
+              node.left.type === "UnaryExpression" && node.operator === "**";
```
Comment (alberto) [inline lib/rules/no-extra-parens.js]: @not-an-aardvark or did you mean here?

Comment (not-an-aardvark) [inline lib/rules/no-extra-parens.js]: I meant [here](https://github.com/eslint/eslint/blob/df2351a695462d9490f665119a7153157bd16ef3/lib/ast-utils.js#L644-L678).

Comment (alberto) [inline lib/rules/no-extra-parens.js]: I mean I don't see how adding a precedence for `**` (which I will anyways, I'm not arguing it should be there) would change the code I added to deal with associativity.

Comment (not-an-aardvark) [inline lib/rules/no-extra-parens.js]: Before updating the `precedence` function, the rule incorrectly considered this code valid:

```js
async function foo(){
  (await foo) ** bar;
}
```

File: lib/ast-utils.js [hunk 5]
```diff
@@ -673,6 +673,8 @@ module.exports = {
                     case "/":
                     case "%":
                         return 13;
+                    case "**":
+                        return 15;
```
Comment (not-an-aardvark) [inline lib/ast-utils.js]: It doesn't really matter, but is it intentional that you skipped 14 here?

Comment (alberto) [inline lib/ast-utils.js]: I followed [this table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence).
