### PR TITLE
Fix: no-duplicate-imports allow unmergeable (fixes #12758, fixes #12760)

### LINKED ISSUE #12758: [no-duplicate-imports] Treat namespace imports as different
**What rule do you want to change?**
no-duplicate-imports

**Does this change cause the rule to produce more or fewer warnings?**
Reduces warnings.

**How will the change be implemented? (New option, new default behavior, etc.)?**
Behavioural change, which could be either option controlled or new default behaviour.
Prior art: [TSLint](https://github.com/palantir/tslint/pull/4524).

**Please provide some example code that this change will affect:**

```js
import * as parsers from '@src/parsers';
import { SpecificParser } from '@src/parsers';
```

**What does the rule currently do for this code?**
Marks the imports as duplicates

**What will the rule do after it's changed?**
Not mark the imports as duplicates

**Are you willing to submit a pull request to implement this change?**
Yes

----

The primary use I have for the above is with mocking in jest, such as [here](https://github.com/G-Rath/terraport/blob/master/test/src/parser/parseTFAttribute.spec.ts) where I want to both use the parsers & also spy on them to test that specific ones are called.

While I can use destructuring, or reference off `parsers`, the former won't be understood by auto-importers (i.e TS & IDE), and the latter would be inconsistent to how I use the functions in the rest of the codebase.

### LINKED ISSUE #12760: no-duplicate-imports should ignore export *
**Tell us about your environment**

* **ESLint Version:** v6.8.0
* **Node Version:** v12.14.0
* **npm Version:** v6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    parserOptions: {
        ecmaVersion: 2015,
        sourceType: "module"
    },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWR1cGxpY2F0ZS1pbXBvcnRzOiBbXCJlcnJvclwiLCB7IFwiaW5jbHVkZUV4cG9ydHNcIjogdHJ1ZSB9XSAqL1xuXG5pbXBvcnQgZm9vIGZyb20gJ2Zvbyc7XG5leHBvcnQgKiBmcm9tICdmb28nO1xuXG5pbXBvcnQgeyBhIH0gZnJvbSAnYmFyJztcbmV4cG9ydCAqIGZyb20gJ2Jhcic7XG5cbmltcG9ydCAqIGFzIG5zIGZyb20gJ2Jheic7XG5leHBvcnQgKiBmcm9tICdiYXonO1xuXG5leHBvcnQgeyBhIGFzIGIgfSBmcm9tICdxdXV4JztcbmV4cG9ydCAqIGZyb20gJ3F1dXgnO1xuXG5leHBvcnQgeyBkZWZhdWx0IH0gZnJvbSAncXV1dXgnO1xuZXhwb3J0ICogZnJvbSAncXV1dXgnOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

```js
/* eslint no-duplicate-imports: ["error", { "includeExports": true }] */

import foo from 'foo';
export * from 'foo';

import { a } from 'bar';
export * from 'bar';

import * as ns from 'baz';
export * from 'baz';

export { a as b } from 'quux';
export * from 'quux';

export { default } from 'quuux';
export * from 'quuux';
```

```bash
eslint index.js
```

**What did you expect to happen?**

I think no errors. The rule requires only 1 import/export statement per source module. I'm not sure how to rewrite any of these 5 examples to achieve that. Or any other code with  `export *` and another import/export from the same source, including the test case:

```js
{
    code: "import os from \"os\";\nexport * from \"os\";",
    options: [{ includeExports: true }],
    errors: [{ messageId: "exportAs", data: { module: "os" }, type: "ExportAllDeclaration" }]
}
```

 If I'm not missing something, this rule should probably ignore `export *`.

**What actually happened? Please include the actual, raw output from ESLint.**

Errors for all 5 `export *` declarations:

```
   4:1  error  'foo' export is duplicated as import  no-duplicate-imports
   7:1  error  'bar' export is duplicated as import  no-duplicate-imports
  10:1  error  'baz' export is duplicated as import  no-duplicate-imports
  13:1  error  'quux' export is duplicated           no-duplicate-imports
  16:1  error  'quuux' export is duplicated          no-duplicate-imports
```

**Are you willing to submit a pull request to fix this bug?**

Yes.

### PR DESCRIPTION
**Pull request by boutahlilsoufiane**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

#### What changes did you make? (Give an overview)
Fix the issue here: #12758

This PR fixes a bug in the rule **no-duplicate-imports** and follows this heuristic **An import that can be merged with another import is a duplicate of that other**. So for example, if we have specific import and namespace import, these two can’t be merged. We should remove the mark import as duplicate.

Fix the issue here: #12760

This PR  fixes also a bug in the rule **no-duplicate-imports**, it removes the export is duplicate mark from exportAllDeclaration because it can’t be merged with any other import/export, but there is a case when the export can be marked as duplicated, like this example (export * from "mod"; export * from "mod"), the second export is duplicated.

### CODE REVIEW

**Review by mdjermanovic — CHANGES_REQUESTED** [review]
@boutahlilsoufiane thanks for the PR!

Can you fix the linting errors, so we could take a look at the code?

`npm run lint` or `npm test` can show the errors locally.

**Comment by boutahlilsoufiane** [comment]
@mdjermanovic thanks for reviewing the PR, I fixed the linting error.

**Comment by boutahlilsoufiane** [comment]
> @boutahlilsoufiane thanks for the PR!
> 
> Can you fix the linting errors, so we could take a look at the code?
> 
> `npm run lint` or `npm test` can show the errors locally.
Hi @mdjermanovic can you please review the PR!

File: lib/rules/no-duplicate-imports.js [hunk 1]
```diff
@@ -54,21 +134,55 @@ function checkAndReport(context, node, value, array, messageId) {
...
             }
-
             importsInFile.push(value);
+            if (modulesWithImportTypes[value]) {
+                modulesWithImportTypes[value] = modulesWithImportTypes[
+                    value
+                ].concat(type);
+            } else {
+                modulesWithImportTypes[value] = [type];
+            }
```
Comment (mdjermanovic) [inline lib/rules/no-duplicate-imports.js:185]: Do we need both `importsInFile` and `modulesWithImportTypes` now, it seems redundant. Can we instead maintain only one map? The key would be the module source, the value would be an array of import declarations with that path.

File: lib/rules/no-duplicate-imports.js [hunk 2]
```diff
@@ -21,18 +57,62 @@ function getValue(node) {
...
+function checkAndReport(
+    context,
+    node,
+    value,
+    array,
+    messageId,
+    modulesWithImportTypes,
+    type,
+    ExportAllDeclarationsInFile
+) {
```
Comment (mdjermanovic) [inline lib/rules/no-duplicate-imports.js:99]: This looks like too many parameters. Can we pass just `context`, `node`, `messageId`, and previous declarations?

**Review by mdjermanovic — CHANGES_REQUESTED** [review]

File: lib/rules/no-duplicate-imports.js [hunk 3]
```diff
@@ -21,18 +57,62 @@ function getValue(node) {
...
+ */
+function shouldReportContradictoryImportType(importTypes, importType) {
+    if (importTypes.indexOf(importType) > -1) {
+        return true;
+    }
+    return (
+        importTypes.findIndex(importTypeItem => CONTRADICTORY_IMPORT_TYPES.includes(importTypeItem)) === -1
+    );
+
+}
```
[the remark this answers is not in the document]
Comment (boutahlilsoufiane) [reply lib/rules/no-duplicate-imports.js:75]: I think the third import shouldn’t be reported because the second one can be merged with the first one, so in this case, the third import can’t be merged with the first one!

So the code will be like this:
```

import mod, * as modns  from 'mod';

import { foo } from 'mod';

```
For your proposed logic, I think it will simplify the code.

File: lib/rules/no-duplicate-imports.js [hunk 4]
```diff
@@ -21,18 +57,62 @@ function getValue(node) {
...
+    modulesWithImportTypes,
+    type,
+    ExportAllDeclarationsInFile
+) {
+    let isDuplicate = false;
+
+    if (type === EXPORT_ALL_DECLARATION) {
+        if (ExportAllDeclarationsInFile.indexOf(value) !== -1) {
+            isDuplicate = true;
+        }
```
[the remark this answers is not in the document]
Comment (boutahlilsoufiane) [reply lib/rules/no-duplicate-imports.js:105]: The first example should be reported. 
For the second example, I think the two import/export can trigger side effects, so they can be merged.

File: lib/rules/no-duplicate-imports.js (hunk 1 above)
Comment (boutahlilsoufiane) [reply lib/rules/no-duplicate-imports.js:185]: Yes, it’s redundant, we can use one variable in this case our map with source module and declarations, then we will remove these variables: **importsInFile**, **modulesWithImportTypes**, **exportsInFile** and **exportAllDeclarationsInFile**.

File: lib/rules/no-duplicate-imports.js (hunk 2 above)
Comment (boutahlilsoufiane) [reply lib/rules/no-duplicate-imports.js:99]: Yes, we can use  4 parameters instead of 8, the same thing for the functions `handleExports `and `handleImports`.

**Comment by boutahlilsoufiane** [comment]
Hi @mdjermanovic, can you please review the PR, thanks!

**Comment by boutahlilsoufiane** [comment]
Hi Mdjermanovic, I worked on your notes, could you review the PR?
Thank you so much.

File: lib/rules/no-duplicate-imports.js [hunk 5]
```diff
@@ -8,39 +8,188 @@
...
+    return false;
+}
+
+/**
+ * Returns array contains only nodes with declarations types equal to type.
+ * @param {[{node: ASTNode, declarationType: string}]} nodes An array contains objects, each object contains a node and a declaration type.
+ * @param {string} type Declaration type.
+ * @returns {[ASTNode]} An array contains only nodes with declarations types equal to type, if the nodes are null we return [].
+ */
+function getNodesByDeclarationTypeAndFormat(nodes, type) {
```
Comment (mdjermanovic) [inline lib/rules/no-duplicate-imports.js:115]: What does "AndFormat" mean?

**Review by mdjermanovic — CHANGES_REQUESTED** [review]

File: lib/rules/no-duplicate-imports.js [hunk 6]
```diff
@@ -125,18 +267,30 @@ module.exports = {
 
     create(context) {
         const includeExports = (context.options[0] || {}).includeExports,
-            importsInFile = [],
-            exportsInFile = [];
-
+            modules = {};
```
[the remark this answers is not in the document]
Comment (ljharb) [reply lib/rules/no-duplicate-imports.js:270]: or, alternatively, `Object.create(null)` (a "null object")

**Comment by boutahlilsoufiane** [comment]
Hi @mdjermanovic and @ljharb  thanks for reviewing the PR.

File: lib/rules/no-duplicate-imports.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (boutahlilsoufiane) [reply lib/rules/no-duplicate-imports.js]: @mdjermanovic  I used the Map object instead of the object to prevent the mentioned error and in order to perform better because our scenario (modules) involves frequent additions. @ljharb thanks for your suggestion, I think it's the easiest solution.

File: lib/rules/no-duplicate-imports.js [hunk 7]
```diff
@@ -8,39 +8,188 @@
...
+    if (node.type === "ExportAllDeclaration") {
+        if (node.exported) {
+            return "ExportNamespaceSpecifier";
+        }
+        return "ExportAll";
+    }
+    if (node.type === "ImportDeclaration") {
+        return "SideEffectImport";
+    }
+    return node.type;
```
[the remark this answers is not in the document]
Comment (boutahlilsoufiane) [reply lib/rules/no-duplicate-imports.js]: Yes, we can return "SideEffectImport" to handle this case.

File: lib/rules/no-duplicate-imports.js [hunk 8]
```diff
@@ -8,39 +8,188 @@
...
+ * @returns {boolean} True if (import|export) type is belong to (ImportSpecifier|ExportSpecifier) or (ImportNamespaceSpecifier|ExportNamespaceSpecifier) and false if it doesn't.
+ */
+function isImportExportSpecifier(importExportType, type) {
+    const specifiersTypes = ["ImportSpecifier", "ExportSpecifier"];
+    const namespacesTypes = [
+        "ImportNamespaceSpecifier",
+        "ExportNamespaceSpecifier"
+    ];
+    const arrayToCheck =
+          type === "specifier" ? specifiersTypes : namespacesTypes;
```
[the remark this answers is not in the document]
Comment (boutahlilsoufiane) [reply lib/rules/no-duplicate-imports.js]: I renamed "specifier" to "named" and also "specifiersTypes" to "namedTypes", these names are better.

File: lib/rules/no-duplicate-imports.js [hunk 9]
```diff
@@ -8,39 +8,188 @@
...
+    return arrayToCheck.includes(importExportType);
+}
+
+/**
+ * Return the type of (import|export).
+ * @param {ASTNode} node A node to get.
+ * @returns {string} The type of the (import|export).
+ */
+function getImportExportType(node) {
+    if (node && node.specifiers && node.specifiers.length > 0) {
```
[the remark this answers is not in the document]
Comment (boutahlilsoufiane) [reply lib/rules/no-duplicate-imports.js]: Its useless to do the check, I removed it from the condition.

File: lib/rules/no-duplicate-imports.js [hunk 10]
```diff
@@ -8,39 +8,188 @@
...
-    if (array.indexOf(value) !== -1) {
+function checkAndReport(
+    context,
+    node,
+    modules,
+    declarationType,
+    includeExports
+) {
+    const module = getModule(node);
+    const previousNodes = modules[module];
```
[the remark this answers is not in the document]
Comment (boutahlilsoufiane) [reply lib/rules/no-duplicate-imports.js]: By your suggestion, we will reduce the complexity of the function `shouldReportImportExport` and `getNodesByDeclarationTypeAndFormat`, so I removed some unnecessary checks from the two functions.

File: lib/rules/no-duplicate-imports.js (hunk 5 above)
Comment (boutahlilsoufiane) [reply lib/rules/no-duplicate-imports.js]: The meaning is formatting the array after the filtering, instead of returning an array of objects, we return an array of nodes. But I removed it to make the name of the function simple.

File: lib/rules/no-duplicate-imports.js [hunk 11]
```diff
@@ -9,87 +9,215 @@
...
 
 /**
- * Returns the name of the module imported or re-exported.
+ * Check if (import|export) type is belong to (ImportSpecifier|ExportSpecifier) or (ImportNamespaceSpecifier|ExportNamespaceSpecifier).
+ * @param {string} importExportType An import type to get.
+ * @param {string} type Specifier type can be namespace or specifier
+ * @returns {boolean} True if (import|export) type is belong to (ImportSpecifier|ExportSpecifier) or (ImportNamespaceSpecifier|ExportNamespaceSpecifier) and false if it doesn't.
+ */
+function isImportExportSpecifier(importExportType, type) {
+    const namedTypes = ["ImportSpecifier", "ExportSpecifier"];
```
Comment (ljharb) [inline lib/rules/no-duplicate-imports.js:18]: These two arrays can be defined at module level, so they’re not created every time this function runs.

File: tests/lib/rules/no-duplicate-imports.js [hunk 12]
```diff
@@ -16,73 +16,222 @@ const rule = require("../../../lib/rules/no-duplicate-imports"),
...
     valid: [
-        "import os from \"os\";\nimport fs from \"fs\";",
-        "import { merge } from \"lodash-es\";",
-        "import _, { merge } from \"lodash-es\";",
-        "import * as Foobar from \"async\";",
-        "import \"foo\"",
-        "import os from \"os\";\nexport { something } from \"os\";",
-        {
-            code: "import os from \"os\";\nexport { hello } from \"hello\";",
+        'import os from "os";\nimport fs from "fs";',
```
Comment (ljharb) [inline tests/lib/rules/no-duplicate-imports.js:25]: it’s hard to review these test diffs with the unrelated style changes. can they be reverted?

File: lib/rules/no-duplicate-imports.js (hunk 11 above)
Comment (boutahlilsoufiane) [reply lib/rules/no-duplicate-imports.js]: Thank you for taking the time to review the PR. I created these two arrays at the module level in section Helpers.

File: tests/lib/rules/no-duplicate-imports.js (hunk 12 above)
Comment (boutahlilsoufiane) [reply tests/lib/rules/no-duplicate-imports.js]: I reverted the file, I think now you can see diffs between commits.

File: tests/lib/rules/no-duplicate-imports.js [hunk 13]
```diff
@@ -80,7 +101,17 @@ ruleTester.run("no-duplicate-imports", rule, {
...
+            options: [{ includeExports: true }],
+            errors: [{ messageId: "exportAs", data: { module: "mod" }, type: "ExportAllDeclaration" }]
+        },
+        {
+            code: "export * from \"os\";\nexport * from \"os\";",
+            options: [{ includeExports: true }],
+            errors: [{ messageId: "export", data: { module: "os" }, type: "ExportAllDeclaration" }]
+        },
+        {
+            code: "import \"os\";\nexport * from \"os\";",
```
Comment (mdjermanovic) [inline tests/lib/rules/no-duplicate-imports.js:114]: Can you also add the following `invalid` tests:

```js
        {
            code: "import os from \"os\";\nexport * as os from \"os\";",
            options: [{ includeExports: true }],
            errors: [{ messageId: "exportAs", data: { module: "os" }, type: "ExportAllDeclaration" }]
        },
        {
            code: "export * as os from \"os\";\nimport os from \"os\";",
            options: [{ includeExports: true }],
            errors: [{ messageId: "importAs", data: { module: "os" }, type: "ImportDeclaration" }]
        }
```

**Review by mdjermanovic — CHANGES_REQUESTED** [review]
The code looks good! I left some suggestions about the documentation, jsdoc, and tests.

**Comment by boutahlilsoufiane** [comment]
Thank you so much @mdjermanovic for your comments, I think I've fixed everything.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by nzakas** [comment]
@boutahlilsoufiane if you can drop me your email address (either sent a message to contact (at) eslint (dot) org or ping me on Discord), we'd like to thank you for this pull request.

**Comment by boutahlilsoufiane** [comment]
Hi @nzakas, I sent a message to contact (at) eslint (dot) org.

**Comment by boutahlilsoufiane** [comment]
Hi @mdjermanovic, thank you so much for accepting the PR.

**Comment by mdjermanovic** [comment]
Thanks for contributing!
