### PR TITLE
Fix: isSpaceBetweenTokens() recognizes spaces in JSXText (fixes #12614)

### LINKED ISSUE #12614: v6.7.0 broke autofixing for eslint-plugin-react
Tests pass on master in https://github.com/yannickcr/eslint-plugin-react on v6.6, and fail on v6.7.0 or v6.7.1. https://travis-ci.org/yannickcr/eslint-plugin-react/jobs/616996307 is an example of the failures; they're related to whitespace placement, within jsx.

I'm not sure which item in the [changelog](https://github.com/eslint/eslint/blob/master/CHANGELOG.md) might be responsible, but perhaps #12491 (cc @kaicataldo)?

The change doesn't need to be reverted if i have a reliable way in the react plugin to detect the different behavior, but I suspect that's also difficult.

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix: #12614 

**What changes did you make? (Give an overview)**

This PR changes `isSpaceBetweenTokens()` method to recognize spaces in `JSXText` tokens in order to fix #12614. The `JSXText` tokens include whitespaces such as indentation.

**Is there anything you'd like reviewers to focus on?**

- Is this direction right?

### CODE REVIEW

File: lib/source-code/source-code.js [hunk 1]
```diff
@@ -447,7 +447,19 @@ class SourceCode extends TokenStore {
...
+
+                /*
+                 * For backward compatibility, check speces in JSXText.
+                 * https://github.com/eslint/eslint/issues/12614
+                 */
+                (
+                    nextToken !== finalToken &&
+                    nextToken.type === "JSXText" &&
+                    /\s/u.test(nextToken.value)
+                )
```
Comment (kaicataldo) [inline lib/source-code/source-code.js]: Thanks for fixing this. I wonder if we should only add this in for the deprecated version? I feel like since it’s part of the `JSXText` node, it shouldn’t actually be treated as whitespace.

File: tests/lib/source-code/source-code.js [hunk 2]
```diff
@@ -2225,6 +2225,47 @@ describe("SourceCode", () => {
...
+                const sourceCode = new SourceCode(code, ast);
+                const jsx = ast.body[0].declarations[0].init;
+
+                assert.strictEqual(
+                    sourceCode.isSpaceBetweenTokens(jsx.openingElement, jsx.closingElement),
+                    true
+                );
+            });
+
+            it("JSXText tokens that contain only letters should NOT be handled as space", () => {
```
Comment (kaicataldo) [inline tests/lib/source-code/source-code.js]: Can we add more tests that tests nested and reversed nodes?

**Comment by ljharb** [comment]
It'd be great if you had the time to verify that eslint-plugin-react's tests pass on master with this change :-)

**Comment by mysticatea** [comment]
I'm sorry, today I failed to get time to follow the review. I will do it tomorrow (JST).

> It'd be great if you had the time to verify that eslint-plugin-react's tests pass on master with this change :-)

I confirmed it by copying/pasting this patch to `node_modules/eslint` and running tests.

**Comment by mysticatea** [comment]
I have updated this PR. Now, this patch doesn't apply to the new `isSpaceBetween()` method.
