### PR TITLE
fix: Ensure that glob patterns are normalized

### LINKED ISSUE #16259: Bug: [new config system] glob arguments with Windows separator `\` don't work
### Environment

Node version: v16.14.0
npm version: v8.3.1
Local ESLint version: v8.23.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19044

### What parser are you using?

Default (Espree)

### What did you do?

Running ESLint in a local ESLint repo, `main` branch.

```
npx eslint lib\*.js -f tap
```

### What did you expect to happen?

Successful linting and a list with the 4 files in the `lib` dir. The exact same command works as expected with `.eslintrc.js` (when `eslint.config.js` is removed).

### What actually happened?

```
Oops! Something went wrong! :(

ESLint: 8.23.0

No files matching the pattern "lib\\*.js" were found.
Please check for typing mistakes in the pattern.
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I submitted this as a bug because it's a backward-incompatible behavior.

Alternatively, we could say that glob patterns are a syntax for itself that has only `/` as separators, which is apparently how `globby` (and the latest `minimatch`) work.

### PR DESCRIPTION
**Pull request by nzakas**
Glob patterns must be normalized to posix-style file paths before being passed in to globby.

Fixes #16259

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

I ensured that glob patterns are normalized to posix-style slashes before passing in to globby.

I also updated tests to verify that this fix worked.

#### Is there anything you'd like reviewers to focus on?

Nothing in particular.

### CODE REVIEW

File: tests/lib/cli.js [hunk 1]
```diff
@@ -171,11 +171,18 @@ describe("cli", () => {
             });
         });
 
-        describe("when there is a local config file", () => {
-            const code = "lib/cli.js";
+        describe.only("when there is a local config file", () => {
```
Comment (aladdin-add) [inline tests/lib/cli.js:174]:
```suggestion
        describe("when there is a local config file", () => {
```

Comment (nzakas) [reply tests/lib/cli.js]: Please let PR authors merge suggestions. :)

**Review by btmills — APPROVED** [review]
