### PR TITLE
Fix: Don't warn about parens around yield (fixes #1981)

### LINKED ISSUE #1981: yield + Gratuitous parentheses around expression
Hey there thanks for the cool project,

I noticed the following error:
the following code produce  a "Gratuitous parentheses around expression"

```js
if ((yield someGenerator()) === 1) {
}
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9339155-yield-gratuitous-parentheses-around-expression?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

File: tests/lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -139,7 +139,10 @@ eslintTester.addRuleTest("lib/rules/no-extra-parens", {
         "var foo = (function() { return bar(); })()",
         "var o = { foo: (function() { return bar(); })() };",
         "o.foo = (function(){ return bar(); })();",
-        "(function(){ return bar(); })(), (function(){ return bar(); })()"
+        "(function(){ return bar(); })(), (function(){ return bar(); })()",
+
+        // parens are required around yield
+        { code: "var foo = (function*() { if ((yield foo()) + 1) { return; } }())", ecmaFeatures: { generators: true } },
```
Comment (ilyavolodin) [inline tests/lib/rules/no-extra-parens.js]: Extra comma at the end. That's why build is failing.

Comment (nzakas) [inline tests/lib/rules/no-extra-parens.js]: Oops, thanks.
