### PR TITLE
fix: revert directive detection in no-unused-expressions

### LINKED ISSUE #19637: `no-unused-expressions` started to trigger on `'use strict'` in 9.25.0
### Environment

Node version: 23.10.0
npm version: 11.3.0
Local ESLint version: 9.25.0
Global ESLint version: -
Operating System: MacOS 15.5 Beta

### What parser are you using?

Default (Espree)

### What did you do?

`no-unused-expressions` started to trigger on `'use strict'` in 9.25.0

### What did you expect to happen?

No errors.

### What actually happened?

Image

### Additional comments

You could check it on `core-js` repo.

Config: https://github.com/zloirock/core-js/blob/master/tests/eslint/eslint.config.js
`package.json`: https://github.com/zloirock/core-js/blob/master/tests/eslint/package.json

`npm run lint` in the root.

### PR DESCRIPTION
**Pull request by sethamus**
#### Prerequisites checklist

-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

#19564 modified the no-unused-expressions rule to use the `node.directive` property for detecting directives. This change introduced a compatibility issue with ES3 codebases, as the directive property does not exist on nodes in ES3 ASTs.

Closes #19637

### CODE REVIEW

**Comment by snitin315** [comment]
@sethamus Lint is failing, can you please check?

**Review by snitin315 — COMMENTED** [review]
@sethamus can you please add a test case as well?

File: tests/lib/rules/no-unused-expressions.js [hunk 1]
```diff
@@ -36,7 +36,10 @@ ruleTester.run("no-unused-expressions", rule, {
 		},
 		"delete foo.bar",
 		"void new C",
-		'"use strict";',
+		{
+			code: '"use strict";',
+			languageOptions: { ecmaVersion: 3, sourceType: "script" },
+		},
```
Comment (snitin315) [inline tests/lib/rules/no-unused-expressions.js:42]: I think we can keep the old `'"use strict";',` case as well.

File: lib/types/rules.d.ts [hunk 2]
```diff
@@ -3915,6 +3915,7 @@ export interface ESLintRules extends Linter.RulesRecord {
 	 * @since 0.1.0
 	 * @see https://eslint.org/docs/latest/rules/no-unused-expressions
 	 */
+
```
Comment (snitin315) [inline lib/types/rules.d.ts:3918]: Unwanted change?
```suggestion
```

**Comment by snitin315** [comment]
Accepting & marking this as a patch candidate since [we officially support ECMAScript 3](https://eslint.org/docs/latest/use/configure/language-options#specifying-javascript-options).

// @mdjermanovic @JoshuaKGoldberg @SwetaTanwar

**Review by mdjermanovic — APPROVED** [review]
LGTM if we decide to revert the directive detection in this rule.

**Review by snitin315 — APPROVED** [review]
LGTM, thanks!

**Comment by snitin315** [comment]
Merging as accepted.
