### PR TITLE
Breaking: validate eslintrc properties (fixes #8213)

### LINKED ISSUE #8213: Proposal: validate eslintrc's properties
**Tell us about your environment**

* **ESLint Version:** 3.17.1
* **Node Version:** 7.2.0
* **npm Version:** 3.10.9

**Please show your full configuration:**

```
module.exports = {
	ecmaVersion: 2017
};
```

**Current behavior**

ESLint ignores properties it doesn't understand

**Suggested behavior**

ESLint cli prints a notice about the invalid eslintrc

**y tho**

The config above looks fine, the property name is correct but its position is wrong. It should be like this:

```
module.exports = {
	parserOptions: {
		ecmaVersion: 2017
	}
};
```

I was wondering why ESLint wasn't recognizing my `async/await` and `--debug` didn't mention anything wrong with the config :(

This didn't help either, it looked like it was correctly picked up:

```
$ eslint --print-config index.js
{
  "globals": {},
  "env": {},
  "rules": {},
  "parserOptions": {},
  "ecmaVersion": 2017
}
```

### PR DESCRIPTION
**Pull request by alberto**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[X] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Create a json schema to validate top level properties in eslint configuration files. See https://github.com/eslint/eslint/issues/8213 for details.

**Is there anything you'd like reviewers to focus on?**
- I disabled a test because of https://github.com/eslint/eslint/pull/8291
- I had to add a `global` property, besides `globals`. I guess this is for historical reasons, the same as the object vs array value. Do we want to do anything here.
- This is a WIP. I'm not very happy with the hardcoded error messages from the library, I'll submit a different commit with a new parser.

### CODE REVIEW

File: tests/lib/config.js [hunk 1]
```diff
@@ -776,7 +776,7 @@ describe("Config", () => {
         });
 
         describe("with env in a child configuration file", () => {
-            it("should overwrite parserOptions of the parent with env of the child", () => {
+            xit("should overwrite parserOptions of the parent with env of the child", () => {
```
Comment (not-an-aardvark) [inline tests/lib/config.js]: Skipping this is fine for now, but at some point we should make a decision about the intended behavior and write tests to make sure it doesn't change.

File: tests/lib/config/config-validator.js [hunk 2]
```diff
@@ -102,116 +102,253 @@ describe("Validator", () => {
...
-            const fn = validator.validate.bind(null, { env: { browser: true, invalid: true } });
+        describe("extends", () => {
+            it("should not throw with an empty array", () => {
+                const fn = validator.validate.bind(null, { extends: [] });
+
+                assert.doesNotThrow(fn);
+            });
 
-            assert.throws(fn, "Environment key \"invalid\" is unknown\n");
+            it("should not throw with an string", () => {
```
Comment (btmills) [inline tests/lib/config/config-validator.js]: Grammar nit: "with a string"

File: tests/lib/config.js (hunk 1 above)
Comment (not-an-aardvark) [inline tests/lib/config.js]: @btmills See the discussion in https://github.com/eslint/eslint/pull/8291.

File: conf/config-schema.json [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+        "global": { "type": ["object", "array"] },
+        "parser": { "type": ["string", "null"] },
+        "env": { "type": "object" },
+        "plugins": { "type": ["array"] },
+        "settings": { "type": "object" },
+        "extends": { "type": ["string", "array"] },
+        "rules": { "type": "object" },
+        "parserOptions": { "type": "object" }
+    },
+    "additionalProperties": false
```
Comment (platinumazure) [inline conf/config-schema.json]: This is already a "breaking" PR and should be semver-major-- I think we could safely error for ecmaFeatures as long as we include something in the 4.0.0 migration guide. (Just my two cents.)

File: lib/config/config-validator.js [hunk 4]
```diff
@@ -123,40 +124,66 @@ function validateEnvironment(environment, source) {
...
 }
 
 /**
- * Validates an entire config object.
+ * Formats an array of schema validation errors.
+ * @param {Array} errors An array of error messages to format.
+ * @returns {string} Formatted error message
+ */
+function formatErrors(errors) {
+    return errors.map(error => `\t- Property "${error.field.replace(/^(data\.)/, "")}" ${error.message}. Current value is: "${JSON.stringify(error.value)}".\n`).join("");
```
Comment (platinumazure) [inline lib/config/config-validator.js]: Yeah, I was going to say the same thing here. We use backticks in a lot of other places; I think that would work pretty well here.

File: tests/lib/config.js (hunk 1 above)
Comment (btmills) [inline tests/lib/config.js]: @not-an-aardvark makes sense, thanks!

File: conf/config-schema.json (hunk 3 above)
Comment (not-an-aardvark) [inline conf/config-schema.json]: Seems reasonable, provided that `ecmaFeatures` isn't too common. (I'm wondering if it would be feasible to pull a bunch of eslint configs from a GitHub search and validate them with the new logic to see how many actually break.)

Comment (alberto) [inline conf/config-schema.json]: I'm sorry, I'm confused. `ecmaFeatures` removal was discussed and approved in https://github.com/eslint/eslint/pull/8239

Silently ignoring it could lead to people configuring ecmaFeatures there, which would have no effect. This is exactly what this change wants to prevent.

File: conf/config-schema.json [hunk 5]
```diff
@@ -0,0 +1,16 @@
...
+}
```
Comment (alberto) [inline conf/config-schema.json]: Yes, this is exactly why I wanted to try a different parser.

File: lib/testers/rule-tester.js [hunk 6]
```diff
@@ -296,9 +285,11 @@ RuleTester.prototype = {
...
                 code = item.code;
 
-                // Assumes everything on the item is a config except for the
-                // parameters used by this tester
-                const itemConfig = lodash.omit(item, RuleTesterParameters);
+                // Validate only config properties
+                const schemaProperties = Object.keys(configSchema.properties);
+
+                // const schemaValidator = validator(configSchema, { verbose: true });
+                const itemConfig = lodash.pick(item, schemaProperties);
```
Comment (alberto) [inline lib/testers/rule-tester.js]: It would be nice indeed, I was hoping to do that. Unfortunately we are using the test object as the config too and some tests add additional properties for their internal use, so they fail (I can look for some examples if you want). We could fix those tests, but plugins could be doing the same thing, so it seemed safer to not restrict it.

File: tests/lib/config.js (hunk 1 above)
Comment (alberto) [inline tests/lib/config.js]: Yes. This should be dealt with in https://github.com/eslint/eslint/pull/8291

I'll add a comment

File: conf/config-schema.json (hunk 3 above)
Comment (mysticatea) [inline conf/config-schema.json]: > Silently ignoring it could lead to people configuring ecmaFeatures there, which would have no effect. This is exactly what this change wants to prevent.

I agree.

File: conf/config-schema.json [hunk 7]
```diff
@@ -0,0 +1,16 @@
+{
+    "type": "object",
+    "properties": {
+        "root": { "type": "boolean" },
+        "globals": { "type": ["object", "array"] },
+        "global": { "type": ["object", "array"] },
```
Comment (mysticatea) [inline conf/config-schema.json]: Does `globals` allow an array?
I didn't find it in the doc: http://eslint.org/docs/user-guide/configuring#specifying-globals

Comment (mysticatea) [inline conf/config-schema.json]: I tried it, but if I gave an array to `globals` of an `.eslintrc` file then ESLint was broken silently.

File: conf/config-schema.json (hunk 3 above)
Comment (not-an-aardvark) [inline conf/config-schema.json]: I was saying that although ecmaFeatures currently doesn't do anything, it's possible that a lot of people have it in their configs, so it might be better to just ignore it to avoid breaking a bunch of peoples' builds. But I'm fine with not allowing it.

File: lib/testers/rule-tester.js (hunk 6 above)
Comment (not-an-aardvark) [inline lib/testers/rule-tester.js]: I definitely think it would be worthwhile. It turns out that only one rule actually does this intentionally, and the others just have typos (see https://github.com/eslint/eslint/pull/8305). Applying [this diff](https://gist.github.com/not-an-aardvark/d879e6273318fd85be2694502c3f3dad) to your current branch would fix the one rule that does it intentionally and add the validation back.

File: conf/config-schema.json (hunk 7 above)
Comment (alberto) [inline conf/config-schema.json]: I asked about this in the first comment. Even if it is not documented, it's used in https://github.com/eslint/eslint/blob/c4ffb49d5a5544e1de0f367e594b989a10ea9c44/lib/eslint.js#L453 as a fallback for globals.

It's also used in a dozen or so tests: https://github.com/eslint/eslint/blob/c4ffb49d5a5544e1de0f367e594b989a10ea9c44/tests/lib/rules/no-global-assign.js#L56
https://github.com/eslint/eslint/blob/c4ffb49d5a5544e1de0f367e594b989a10ea9c44/tests/lib/rules/no-undef.js#L26
to list a few.

Re: the array vs object, here is a test using it: https://github.com/eslint/eslint/blob/c4ffb49d5a5544e1de0f367e594b989a10ea9c44/tests/lib/rules/no-param-reassign.js#L26

I'm fine if we decide to remove/deprecate those, but that should be a TSC decision.

File: lib/testers/rule-tester.js (hunk 6 above)
Comment (alberto) [inline lib/testers/rule-tester.js]: Ok, since we can fix this without special casing our tests, I agree we should add it in the hope it doesn't cause breakage for others (we could always fall back to checking only known properties). Thanks!

Comment (not-an-aardvark) [inline lib/testers/rule-tester.js]: :+1:

On a loosely related note, should we also validate `errors` objects to make sure they only contain allowed properties (`line`, `column`, etc.)? (This might be a separate issue, since it's not directly tied to config validation.)

**Comment by alberto** [comment]
PR updated with the feedback I got. I have also removed the property "args" from the RuleTesterParameters list, since it seems to be something from the past that has no effect.

File: conf/config-schema.json (hunk 7 above)
Comment (mysticatea) [inline conf/config-schema.json]: Hmm, but I'm sure `.eslintrc` files does not support `global` property and the array value of `globals` property. Those are not working.

----

```
~\Documents\GitHub\sandbox2> cat .eslintrc.json
{
    "global": {"foo": false},
    "extends": "eslint:recommended"
}
~\Documents\GitHub\sandbox2> cat test.js
Object
foo
~\Documents\GitHub\sandbox2> eslint test.js

C:\Users\t-nagashima.AD\Documents\GitHub\sandbox2\test.js
  2:1  error  'foo' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```

----

```
~\Documents\GitHub\sandbox2> cat .eslintrc.json
{
    "globals": ["foo"],
    "extends": "eslint:recommended"
}
~\Documents\GitHub\sandbox2> cat test.js
Object
foo
~\Documents\GitHub\sandbox2> eslint test.js

C:\Users\t-nagashima.AD\Documents\GitHub\sandbox2\test.js
  2:1  error  'foo' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```

----

```
~\Documents\GitHub\sandbox2> cat .eslintrc.json
{
    "globals": {"foo": false},
    "extends": "eslint:recommended"
}
~\Documents\GitHub\sandbox2> cat test.js
Object
foo
~\Documents\GitHub\sandbox2> eslint test.js
```

Comment (alberto) [inline conf/config-schema.json]: Ok, after digging deeper into this I think I have a better understanding of what's going on. Sorry for the long post.

As @mysticatea pointed out, `global` object nor `globals` array are valid in the config.

There is one case of `global` array in the tests, but it is a false negative. So we can definitely remove the array option.

The Config object itself accepts `globals` as an array and converts it to an object. https://github.com/eslint/eslint/blob/8733e6a852ea9b49cef26650357598ca8c2c2a1f/lib/config.js#L214
This is used for the command line options. e.g `--global foo --global bar` so we need to keep that

So the only question is whether we should remove `global` object.

`eslint` `prepareConfig` has a conditional to use `global` if `globals` is falsy. 
https://github.com/eslint/eslint/blob/8733e6a852ea9b49cef26650357598ca8c2c2a1f/lib/eslint.js#L453
This code was added 3 years ago. I think `globals` was added later, and `global` was kept for backwards compatibility.

I think in a Config object `globals` is always truthy, so this could be removed. 
https://github.com/eslint/eslint/blob/8733e6a852ea9b49cef26650357598ca8c2c2a1f/lib/config.js#L214

The only gotcha is in RuleTester we are validating a regular object, not built through Config. So it happily accepts `global` or `globals`
and passes it to eslint.verify.

There are tests from 2 years ago (v.1.0.0 days) validating this behavior: https://github.com/eslint/eslint/blame/8733e6a852ea9b49cef26650357598ca8c2c2a1f/tests/lib/testers/rule-tester.js#L479

However the jsdoc in verify mentions it expects `globals` not `global`.
https://github.com/eslint/eslint/blob/8733e6a852ea9b49cef26650357598ca8c2c2a1f/lib/eslint.js#L742

So, to the best of my knowledge, `global` is only used by our tests and could be removed. It might break some people tests if they are using it too. If we decide to keep it, we should skip it or special case it, so the validation doesn't fail.

File: lib/testers/rule-tester.js [hunk 8]
```diff
@@ -69,8 +69,8 @@ const RuleTesterParameters = [
     "code",
     "filename",
     "options",
-    "args",
-    "errors"
+    "errors",
```
Comment (not-an-aardvark) [inline lib/testers/rule-tester.js]: Should we also validate the properties of error objects in tests? For example, someone could accidentally use `lineEnd` instead of `endLine` and errors wouldn't be caught.

Comment (alberto) [inline lib/testers/rule-tester.js]: I can do it, but as you said, it seems unrelated to this issue, so maybe it should go as a different PR.

File: lib/config/config-validator.js [hunk 9]
```diff
@@ -123,40 +124,63 @@ function validateEnvironment(environment, source) {
...
-                const message = [
-                    source, ":\n",
-                    "\tEnvironment key \"", env, "\" is unknown\n"
-                ];
-
-                throw new Error(message.join(""));
-            }
-        });
-    } else {
-        throw new Error("Environment must be an object");
```
Comment (alberto) [inline lib/config/config-validator.js]: It threw if it wasn't an object. This is now covered by the schema.

File: tests/lib/config/config-validator.js [hunk 10]
```diff
@@ -102,116 +102,253 @@ describe("Validator", () => {
...
+                assert.doesNotThrow(fn);
+            });
+
+            it("should not allow options for rules with no options", () => {
+                eslint.defineRule("mock-no-options-rule", mockNoOptionsRule);
+
+                const fn = validator.validate.bind(null, { rules: { "mock-no-options-rule": [2, "extra"] } }, "tests");
+
+                assert.throws(fn, "tests:\n\tConfiguration for rule \"mock-no-options-rule\" is invalid:\n\tValue \"extra\" has more items than allowed.\n");
+            });
```
Comment (alberto) [inline tests/lib/config/config-validator.js]: I do!

File: conf/config-schema.json (hunk 7 above)
Comment (alberto) [inline conf/config-schema.json]: @eslint/eslint-team I would like feedback on what to do with the `global` option in eslint.js as mentioned above

File: lib/config/config-validator.js (hunk 9 above)
Comment (not-an-aardvark) [inline lib/config/config-validator.js]: No particular case, I just wasn't sure why the logic changed.

File: lib/testers/rule-tester.js [hunk 11]
```diff
@@ -69,8 +69,8 @@ const RuleTesterParameters = [
...
+    "output"
```
Comment (not-an-aardvark) [inline lib/testers/rule-tester.js]: Can we add a test to `rule-tester` to verify that an error is thrown when an unknown property is included in a test?

File: conf/config-schema.json (hunk 7 above)
Comment (not-an-aardvark) [inline conf/config-schema.json]: :+1: for removing `global`.

Comment (ilyavolodin) [inline conf/config-schema.json]: `globals` vs. `global` were done before version 1.0.0 because JSHint supported both. So it was done for backwards compatibility. I would be 👎 on removing either one at this point. This would be a major breaking change from my perspective. I'm not sure why `global` is not used in config, it should be, it might've been lost during refactoring. But inline comments accept both `globals` and `global`

**Comment by alberto** [comment]
I'm continuing the conversation about `global` here because it got hidden by github after updating my PR and it makes it hard to find it. The original conversation is [here](https://github.com/eslint/eslint/pull/8295#discussion_r107329633).

@ilyavolodin Inline comments still would allow `global` inline comments. They are stored separately in `astGlobals`.

**Comment by alberto** [comment]
**TSC Summary:** `eslint.verify` accepts a `global` object property as a fallback from `globals`. Note this is not used for command-line arguments, which are stored in `astGlobals`. See https://github.com/eslint/eslint/pull/8295#discussion_r107405716 for details

**TSC Question:** Should we remove this?

**Comment by not-an-aardvark** [comment]
In today's [TSC meeting](https://github.com/eslint/tsc-meetings/blob/master/notes/2017/2017-03-30.md), the TSC decided to remove the `global` config property in favor of the documented `globals` property.

**Comment by not-an-aardvark** [comment]
@alberto How is this coming along? It looks like the only remaining thing to do is improve the error messages -- would it be helpful if someone else took over that last item?

**Comment by alberto** [comment]
Yes, the only thing missing is to improve the error messages. I was planning to use a different schema validator library, like ajv. Unfortunately I can't finish it right now, so I'd appreciate if someone else did.

**Comment by not-an-aardvark** [comment]
Working on this.

**Comment by not-an-aardvark** [comment]
Updated to add better error messages. This was easier than expected because `is-my-json-valid` outputs the expected type of a value as part of the error object [since 2.13.0](https://github.com/mafintosh/is-my-json-valid/commit/22aa92ba00b2982e6218b5fc28924ae13aeca93f).

File: tests/lib/config/config-validator.js [hunk 12]
```diff
@@ -102,116 +102,249 @@ describe("Validator", () => {
...
+                const fn = validator.validate.bind(null, { extends: "react" });
+
+                assert.doesNotThrow(fn);
+            });
+
+            it("should throw with an object", () => {
+                const fn = validator.validate.bind(null, { extends: {} });
 
-            assert.throws(fn, "Environment key \"invalid\" is unknown\n");
+                assert.throws(fn, "Property \"extends\" is the wrong type (expected string,array but got `{}`).");
```
Comment (platinumazure) [inline tests/lib/config/config-validator.js]: Wondering if we can improve the expected type display by transliterating commas to forward slashes?

File: tests/lib/testers/rule-tester.js [hunk 13]
```diff
@@ -621,9 +612,33 @@ describe("RuleTester", () => {
...
+    it("throw an error when an unknown config option is included", () => {
+
+        assert.throws(() => {
+            ruleTester.run("no-eval", require("../../fixtures/testers/rule-tester/no-eval"), {
+                valid: [
+                    { code: "Eval(foo)", foo: "bar" }
+                ],
+                invalid: []
+            });
+        }, /ESLint configuration is invalid./);
```
Comment (platinumazure) [inline tests/lib/testers/rule-tester.js]: Can this message be improved for RuleTester tests? (Maybe instead of "ESLint configuration", something like "Test configuration"... maybe?)

Comment (not-an-aardvark) [inline tests/lib/testers/rule-tester.js]: I think this would be tricky to do because `RuleTester` uses `linter.verify` to verify the config and run the rule at the same time, so it would need to be able to reliably distinguish between config errors and other types of thrown errors (e.g. rule crashes). Personally, I think "ESLint configuration is invalid" is reasonably clear (the issue in this case is that a test case contained an invalid key which did, in fact, get used as configuration), so IMO it might not be worth increasing complexity for a different message.

Also, it's worth noting that messages like this will still contain more information about what was wrong (in this case, it will complain about the "foo" key being invalid), so the user will still be given some direction for fixing the error.
