### PR TITLE
Fix: avoid crashing when using baseConfig with extends (fixes #8791)

### LINKED ISSUE #8791: Gensite fails while building formatters page
During release today, release script failed while generating formatters page for the site. It looks like glob-based configs introduced a regression for configs that use `extend` with `baseConfig`. This branch of code is not covered by unit tests, and it wasn't clear how to fix it during the release. So we skipped generation of formatter page and decided to fix it over the weekend.
We traced the error to this line of code: https://github.com/eslint/eslint/blob/7d9e3beeb58c1ee71d53dfcfd3e3b0721dd79b46/lib/config/config-file.js#L567
Also config is passing two properties here: https://github.com/eslint/eslint/blob/7d9e3beeb58c1ee71d53dfcfd3e3b0721dd79b46/lib/config.js#L70 but `loadObject` function only accepts one. Even when I changed the code locally to accept two arguments and pass `configContext` as second parameter into `applyExtends` it failed with the same error, because we only add `configCache` after we call `loadObject`.

Error message is below:

```js
/var/lib/jenkins/workspace/Releases/ESLint Release/eslint/lib/config/config-file.js:431
            throw e;
            ^

TypeError: Cannot read property 'getConfig' of undefined
Referenced from: undefined
    at load (/var/lib/jenkins/workspace/Releases/ESLint Release/eslint/lib/config/config-file.js:582:51)
    at configExtends.reduceRight.e (/var/lib/jenkins/workspace/Releases/ESLint Release/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/var/lib/jenkins/workspace/Releases/ESLint Release/eslint/lib/config/config-file.js:405:28)
    at Object.loadObject (/var/lib/jenkins/workspace/Releases/ESLint Release/eslint/lib/config/config-file.js:567:35)
    at new Config (/var/lib/jenkins/workspace/Releases/ESLint Release/eslint/lib/config.js:70:46)
    at new CLIEngine (/var/lib/jenkins/workspace/Releases/ESLint Release/eslint/lib/cli-engine.js:427:23)
    at getFormatterResults (/var/lib/jenkins/workspace/Releases/ESLint Release/eslint/Makefile.js:467:15)
    at Function.target.gensite (/var/lib/jenkins/workspace/Releases/ESLint Release/eslint/Makefile.js:736:31)
    at Object.global.target.(anonymous function) [as gensite] (/var/lib/jenkins/workspace/Releases/ESLint Release/eslint/node_modules/shelljs/make.js:36:40)
```

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/8791)

**What changes did you make? (Give an overview)**

Due to a bug, an invalid Config instance was getting used when applying extensions to a `baseConfig` object. This updates the `Config` constructor to use the correct context, and to make sure the config cache exists when the `baseConfig` is evaluated.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: lib/config.js [hunk 1]
```diff
@@ -66,13 +66,14 @@ class Config {
         this.parser = options.parser;
         this.parserOptions = options.parserOptions || {};
 
+        this.configCache = new ConfigCache();
```
Comment (ilyavolodin) [inline lib/config.js]: That's exactly what I've tried earlier today. If you attach a debugger and look at `this.baseConfig` after it's been resolved, you'll see that `extends` haven't been resolved and now there are 3 of them there, instead of 1 that's supposed to be. I don't think that's right.

Comment (not-an-aardvark) [inline lib/config.js]: I don't understand the issue -- the test asserts that a specific value `rules` and `env` is present, which is the expected value for extending the given configs.

The `extends` are still present on the `baseConfig` due to https://github.com/eslint/eslint/pull/8636 (we don't remove `extends` from a merged config even after applying the extensions).

Comment (ilyavolodin) [inline lib/config.js]: Are we also supposed to flatten `extends` as well? Cause I'm getting 3 `extends` in baseConfig after resolution, one that was initially there, and 2 from the `array` config.

Comment (not-an-aardvark) [inline lib/config.js]: I'm not sure. Personally I think it would make more sense to omit `extends` entirely after the config has already been merged, but that seems like a separate issue.

Comment (not-an-aardvark) [inline lib/config.js]: Also, it's worth noting that the flattening behavior has been present since 4.0.0, so it's not part of this regression.

Comment (ilyavolodin) [inline lib/config.js]: Ok, got it. Sorry, I haven't really looked at this code much since the last refactoring.
