### PR TITLE
fix: Ensure FlatESLint#findConfigFile() doesn't throw.

### LINKED ISSUE #17150: Bug: `FlatESLint#findConfigFile` should return `undefined` if it doesn't find `eslint.config.js`
### Environment

Node version: v16.14.0
npm version: 8.3.1
Local ESLint version: `main` branch
Global ESLint version: 
Operating System: windows

### What parser are you using?

Default (Espree)

### What did you do?

In the `main` branch, I deleted the `eslint.config.js` file, and added the following `test.mjs` file:

```js
import unsupportedAPI from "eslint/use-at-your-own-risk";

const { FlatESLint } = unsupportedAPI;

const eslint = new FlatESLint();

console.log(await eslint.findConfigFile());


```

Then ran `node test.mjs`

### What did you expect to happen?

`FlatESLint#findConfigFile()` to return `undefined` when it doesn't find an `eslint.config.js` file.

### What actually happened?

Throws an error:

```
Error: Could not find config file.
    at locateConfigFileToUse (C:\milos\eslint\lib\eslint\flat-eslint.js:346:19)
    at async FlatESLint.findConfigFile (C:\milos\eslint\lib\eslint\flat-eslint.js:1189:36)
    at async file:///C:/milos/eslint/test.mjs:8:15
```

### Link to Minimal Reproducible Example

`main` branch

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

If findConfigFile() can't find eslint.config.js, it now returns undefined instead of throwing an error.

Fixes #17150

#### Is there anything you'd like reviewers to focus on?

Did I miss any edge cases?

### CODE REVIEW

File: lib/eslint/flat-eslint.js [hunk 1]
```diff
@@ -326,14 +326,15 @@ async function loadFlatConfigFile(filePath) {
...
- * @returns {{configFilePath:string,basePath:string}} Location information for
+ * @returns {{configFilePath:string,basePath:string,error:boolean}} Location information for
  *      the config file.
  */
 async function locateConfigFileToUse({ configFile, cwd }) {
 
     // determine where to load config file from
     let configFilePath;
     let basePath = cwd;
+    let error = false;
```
Comment (snitin315) [inline lib/eslint/flat-eslint.js:337]: The name `error` sounds generic and I expected it to be an instance of `Error`. Can we use something like `isConfigFileDetected`/`hasConfigFile`? I feel it's better suited for a boolean value.

Comment (aladdin-add) [reply lib/eslint/flat-eslint.js:337]: Or we can return an error object `error = new Erro("Could not find config file.");`, which can be thrown directly where it is used?

Comment (aladdin-add) [reply lib/eslint/flat-eslint.js:337]: sure, will do!
