### PR TITLE
Fix: Handle comment lines in newline-after-var (fixed #2237)

### LINKED ISSUE #2237: false positive in rule "newline-after-var"
When using eslint v0.18.0 on the windows platform the following code example:
```javascript
/*eslint-env node*/
/*eslint newline-after-var:[2, "always"]*/

"use strict";

var test = require("selenium-webdriver/testing");

test.describe("Widget - User defined", function () {
	var client;

	//	Prepare the tests

	this.timeout(client);
});
```

shows the following false positives:
```
6:0  error  Newline is always expected after a "var" statement  newline-after-var
9:1  error  Newline is always expected after a "var" statement  newline-after-var
```

### PR DESCRIPTION
**Pull request by cvisco**
This fixes a regression in how the `newline-after-var` rule handles
comments on the next line. Since switching from a RegEx to token-based
inspection, if the line after a `var` declaration contained a comment,
this was not seen by the rule and would cause a false-positive. The
solution here was to add some additional checks for the presence of a
comment if no token exists on the next line.

* Expand test examples to catch additional corner cases
* DRY-up tests

### CODE REVIEW

File: lib/rules/newline-after-var.js [hunk 1]
```diff
@@ -35,6 +35,29 @@ module.exports = function(context) {
...
+        return token.loc.start.line;
+    }
+
+    /**
+     * Check if a comment exists on the given line number
+     * @private
+     * @param {Number} lineNum - line number to test
+     * @returns {Boolean} `true` if line contains a comment
+     */
+    function isCommentLine(lineNum) {
```
Comment (nzakas) [inline lib/rules/newline-after-var.js]: This is pretty expensive to call for every variable declaration. Can you cache the mapped comments?

Comment (cvisco) [inline lib/rules/newline-after-var.js]: Wow, that seems painfully obvious now that you mention it. Good catch!

**Comment by cvisco** [comment]
@nzakas: Cached comment line numbers per your request.

**Comment by nzakas** [comment]
Lgtm. Thanks!
