### PR TITLE
Fix: --quiet no longer fixes warnings (fixes #8675)

### LINKED ISSUE #8675: Confusion around how --quiet and --fix should behave together
See #8353 for background.

I think the best way to fix this is to allow users the option to go either way and to be very explicit about how the options work.

Here's one proposal along those lines:

* Rename --quiet to --no-report-warnings (supporting --quiet as an alias and preserving its behavior), to avoid reporting warnings but possibly fix them
* Add option --no-fix-warnings to support not running autofix on warnings but possibly report them (no effect if `--fix` not specified)
* Users can use both to completely ignore warnings altogether

With this proposal, our CLI options become more clear and more flexible with regard to whether warnings are *reported/logged* (`--quiet`/`--no-report-warnings`) and whether warnings are *fixed* (`--no-fix-warnings`).

I'll champion.

### PR DESCRIPTION
**Pull request by platinumazure**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

See #8675.

**What changes did you make? (Give an overview)**

When `--quiet` is specified by user, lib/cli.js will pass a fix predicate function to CLIEngine so that only errors are fixed. That way, warnings (which aren't even reported in `--quiet` mode and about which they might know nothing) are not fixed and users are thus no longer surprised by extra changes being made to ESLint.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

**Comment by platinumazure** [comment]
Hmm... Possible improvement might be to expose the fix predicate as `CLIEngine.fixErrorsOnlyPredicate` or similar so CLIEngine users can easily emulate `--quiet` on the CLI.

File: lib/cli.js [hunk 1]
```diff
@@ -29,6 +29,17 @@ const debug = require("debug")("eslint:cli");
...
 
 /**
+ * Predicate function for whether or not to apply fixes in quiet mode.
+ * If a message is a warning, do not apply a fix.
+ * @param {LintResult} lintResult The lint result.
+ * @returns {boolean} True if the lint message is an error (and thus should be
+ * autofixed), false otherwise.
+ */
+function quietFixPredicate(lintResult) {
+    return Boolean(lintResult && lintResult.severity === 2);
```
Comment (not-an-aardvark) [inline lib/cli.js]: Why can't this be `return lintResult.severity === 2`? Is `lintResult` ever null?

Comment (platinumazure) [inline lib/cli.js]: It probably should never be null. Normally I favor defensive coding to be safe; but since this could be a tight path (running this function on every lint message), I am happy to shave off those cycles. I'll update tonight (US).

**Comment by platinumazure** [comment]
Adding "do not merge" so I can make a suggested change.

**Comment by platinumazure** [comment]
@not-an-aardvark Updated per your suggestion, thanks!
