### PR TITLE
Fix: Ensure proper lookup of config files (fixes #5175)

### LINKED ISSUE #5175: New config file plugin/extends resolution not working with node.js API and `configFile` option
The file resolution for the `plugin` and `extends` options works differently in eslint 2.0.0.

`standard` 6.0.0 is using `eslint` 2.0.0-rc.0 and the `configFile` option to the node.js API. [The code](https://github.com/feross/standard/blob/39a54d33f95ca564d976ea2cb97f4c3a45ed0c09/options.js) looks roughly like this:

```js
var CLIEngine = require("eslint").CLIEngine
var cli = new CLIEngine({ configFile: path.join(__dirname, 'rc', '.eslintrc') })
```

This `.eslintrc` file contains:

```json
{
  "extends": ["standard", "standard-jsx"]
}
```

The `eslint-config-standard` and `eslint-config-standard-jsx` packages are dependencies of the `standard` package, of course. 

The problem is that when users install `standard` as a dependency of their own project and run it, they get the following error:

```
Error: Cannot find module 'eslint-config-standard-jsx' from '/home/travis/build/matjaz/stdin2'
Referenced from: /home/travis/build/matjaz/stdin2/node_modules/standard/rc/.eslintrc
    at Function.module.exports [as sync] (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/node_modules/resolve/lib/sync.js:33:11)
    at resolve (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config/config-file.js:393:38)
    at load (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config/config-file.js:412:24)
    at /home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config/config-file.js:331:36
    at Array.reduceRight (native)
    at applyExtends (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config/config-file.js:314:28)
    at Object.load (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config/config-file.js:436:22)
    at loadConfig (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config.js:67:33)
    at new Config (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config.js:192:38)
    at CLIEngine.executeOnFiles (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/cli-engine.js:492:28)
```

It seems that the `process.cwd()` is being used as starting point for the search, instead of the config file's folder.

Perhaps the `relativeTo` argument is not being passed to the `resolve` function [in this code](https://github.com/eslint/eslint/blob/11435afd76278a1291566c92af985bf8fad0731f/lib/config/config-file.js#L389-L394)?

In any case, this affected `standard` [recently](https://github.com/feross/standard/issues/406) and required [this hack](https://github.com/feross/standard/compare/v6.0.1...v6.0.3) to workaround. Hoping we can figure out a real fix to this.

### PR DESCRIPTION
**Pull request by nzakas**
This is a proof-of-concept to get some feedback. Some tests are currently failing, but want to make sure this is working for the few cases we have before proceeding.

### CODE REVIEW

File: lib/config/config-file.js [hunk 1]
```diff
@@ -19,7 +19,8 @@ var debug = require("debug"),
     ConfigOps = require("./config-ops"),
     validator = require("./config-validator"),
     Plugins = require("./plugins"),
-    resolveModule = require("resolve"),
+    Module = require("module"),
```
Comment (ilyavolodin) [inline lib/config/config-file.js]: I can't really find any documentation for `module`, what exactly does it do (or rather I can see that implements Node's module system, but why do you need it here?). It also looks like you are not using it anywhere.

File: lib/util/module-resolver.js [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+         */
+        var lookupPaths = this.options.lookupPaths.concat();
+        lookupPaths.unshift(extraLookupPath);
+
+        /**
+         * Module._findPath is an internal method to Node.js, then one they use to
+         * lookup file paths when require() is called. So, we are hooking into the
+         * exact same logic that Node.js uses.
+         */
+        var result = Module._findPath(name, lookupPaths);
```
Comment (ilyavolodin) [inline lib/util/module-resolver.js]: Since it's an underscore method, it's marked as private, are we sure we want to use private methods? While I understand that this is much better approach then what we've been doing, it just makes me feel a bit uneasy.

File: lib/config/config-file.js (hunk 1 above)
Comment (nzakas) [inline lib/config/config-file.js]: It's a straggler I forgot to remove. `module` is how modules are implemented in Node.js: https://github.com/nodejs/node/blob/master/lib/module.js

File: lib/util/module-resolver.js (hunk 2 above)
Comment (nzakas) [inline lib/util/module-resolver.js]: There are a bunch of tools that hook into underscore methods on `Module`, so if they change it, we won't be the only thing that breaks. If this PoC actually works, I plan on filling an issue with Node.js to see if they will formally support it.
