### PR TITLE
Fix: Track JSX global variable correctly (fixes #1534)

### LINKED ISSUE #1534: es6jsx: no-unused-vars misses JSX references
I'm using eslint v0.11.0-alpha.0 and getting `no-unused-vars` errors in my JSX template code:

```JavaScript
var React = require('react');

var App = React.createClass({
  render: function() {
    return (
      <div>
        <h1>wat</h1>
      </div>
    );
  }
});

React.render(<App />, document.body);
```

This produces the following errors:

```bash
ಠ_ಠ  ~/code/happytrack λ eslint durp.jsx

durp.jsx
  3:4   error  App is defined but never used                                 no-unused-vars
```

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/6634342-es6jsx-no-unused-vars-misses-jsx-references?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

File: tests/lib/rules/no-unused-vars.js [hunk 1]
```diff
@@ -17,38 +17,39 @@ var eslint = require("../../../lib/eslint"),
...
-        { code: "var a=10; (function() { alert(a); })();", args: [1, {vars: "all"}] },
-        { code: "function g(bar, baz) { return baz; }; g();", args: [1, {"vars": "all"}] },
-        { code: "function g(bar, baz) { return baz; }; g();", args: [1, {"vars": "all", "args": "after-used"}] },
-        { code: "function g(bar, baz) { return bar; }; g();", args: [1, {"vars": "all", "args": "none"}] },
-        { code: "function g(bar, baz) { return 2; }; g();", args: [1, {"vars": "all", "args": "none"}] },
-        { code: "function g(bar, baz) { return bar + baz; }; g();", args: [1, {"vars": "locals", "args": "all"}] },
-        { code: "var g = function (bar, baz) { return 2; }; g();", args: [1, {"vars": "all", "args": "none"}] },
-        "(function z() { z(); })();",
-        { code: " ", globals: {a: true} }
+        // { code: "a; var a;", args: [1, "all"] },
```
Comment (michaelficarra) [inline tests/lib/rules/no-unused-vars.js]: Uuuuuhhh. Mistake?

Comment (nzakas) [inline tests/lib/rules/no-unused-vars.js]: Yup, fixing now.

**Comment by lo1tuma** [comment]
LGTM
