### PR TITLE
Fix: clarify AST and don't use `node.start`/`node.end` (fixes #8956)

### LINKED ISSUE #8956: Clarify non-standard properties of AST that custom parsers should create
I think we should clarify our position about non-standard properties of AST. Especially:

- `node.range`
- `node.start`
- `node.end`
- Properties of tokens and comments.

ESTree does not have those properties. However, we have been using `node.range` properties to write core rules since v0.x.y.

After ESLint v2.0.0, AST nodes have `node.start` and `node.end` properties as well for some reason. However, as far as I know, we have not been using those two properties in core rules, because the use of those two properties is a breaking change for custom parsers and we have not announced the change.

I thought so, but in fact, we have seemed to be using `node.start` and `node.end` in core rules, e.g. `padded-blocks` (1c123e29619fcc144262571688999d02777382cf).

If we clarify about non-standard properties of AST, it will become an important resource for the developer of custom parsers.

My position is:

- AST nodes require `node.range` property.
- AST nodes don't require `node.start` and `node.end` properties (so we should not use `node.start` and `node.end` in core rules) at this time. We can add `node.start` and `node.end` in the next major release.
- Tokens and comments are should be the following shape:

```ts
interface Token {
    type: string
    range: [number, number]
    loc: SourceLocation    // SourceLocation is defined in ESTree.
    value: string
}
```

----

**Tell us about your environment**

* **ESLint Version:** v4.1.1
* **Node Version:**  v8.1.4
* **npm Version:** v5.1.0

**What parser (default, Babel-ESLint, etc.) are you using?**

- `typescript-eslint-parser`

**What did you do? Please include the actual source code causing the issue.**

```js
/*eslint padded-blocks: [error, never] */
do {
    foo()
    // comment

} while (a)
```

```console
$ eslint test.js --no-eslintrc --no-ignore --fix --parser typescript-eslint-parser
```

**What did you expect to happen?**

```js
/*eslint padded-blocks: [error, never] */
do {
    foo()
    // comment
} while (a)
```

**What actually happened? Please include the actual, raw output from ESLint.**

The most code was lost.

```js

} while (a)

```

The root cause is that the comment tokens of `typescript-eslint-parser` don't have `start` and `end` properties but `padded-blocks` rule is using those.

I'm not sure which of `padded-blocks` and `typescript-eslint-parser` I should fix because the specification of AST is unclear.

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

Fixes #8956.

**What changes did you make? (Give an overview)**

This PR updates the document "Working with Custom Parsers" to clarify the specification of AST.
Also, this PR fixes 8 rules which are violating the spec.

It's hard that we catch the violations in review since `start` and `end` properties are legal on Location objects. So I added the custom parser which removes the properties from the result of `espree`. Tests of core rules use the custom parser by default. This does not affect to plugin developers.

**Is there anything you'd like reviewers to focus on?**

- Please correct my English.
- Check whether the added document is enough or not.

### CODE REVIEW

File: lib/testers/test-parser.js [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+const Traverser = require("../util/traverser");
+
+/**
+ * Remove `start`/`end` properties from the given node.
+ * @param {ASTNode} node The node to remove.
+ * @returns {void}
+ */
+function removeStartEnd(node) {
+    delete node.start;
+    delete node.end;
```
Comment (not-an-aardvark) [inline lib/testers/test-parser.js]: I think it might be confusing for new developers if the `start` and `end` properties are removed. For example, if someone uses `console.log(node)` when running the rule on regular code, it will have the `start` and `end` properties, but the properties will disappear during the test.

Would it work to do this instead?

```js
Object.defineProperty(node, "start", { get() {
    throw new Error("Use node.range[0] instead of node.start");
} };

Object.defineProperty(node, "end", { get() {
    throw new Error("Use node.range[1] instead of node.end");
} };
```

Comment (mysticatea) [inline lib/testers/test-parser.js]: Oh, good idea!
I will do.

File: docs/developer-guide/working-with-plugins.md [hunk 2]
```diff
@@ -246,4 +246,33 @@ exports.parseForESLint = function(code, options) {
 
 ```
 
+### The AST specification
 
+The AST that custom parsers should create is based on [ESTree](https://github.com/estree/estree) basically. The AST requires some additional properties about detail information of the source code.
```
Comment (platinumazure) [inline docs/developer-guide/working-with-plugins.md]: I think the word "basically" can be removed.

File: docs/developer-guide/working-with-plugins.md [hunk 3]
```diff
@@ -246,4 +246,33 @@ exports.parseForESLint = function(code, options) {
...
+
+#### All nodes:
+
+All nodes must have `range` property.
+
+* `range` (`number[]`) is the array of two numbers. Both numbers are a 0-based index which is the position in the array of source code characters. The first is the start position of the node, the second is the end position of the node. `code.slice(node.range[0], node.range[1])` must be the text of the node. This range does not include spaces which are around the node.
```
Comment (platinumazure) [inline docs/developer-guide/working-with-plugins.md]: The first sentence should probably end with "is an array of two numbers" (replace the with an).

Do we need to make a note about parentheses surrounding the node, in some cases? I'm fairly sure parentheses are usually excluded also from the range, unless they're part of the grammar (e.g., arrow function parameters).

File: docs/developer-guide/working-with-plugins.md [hunk 4]
```diff
@@ -246,4 +246,33 @@ exports.parseForESLint = function(code, options) {
...
+* `loc` (`SourceLocation`) must not be `null`. [The `loc` property is defined as nullable by ESTree](https://github.com/estree/estree/blob/25834f7247d44d3156030f8e8a2d07644d771fdb/es5.md#node-objects), but ESLint requires this property. On the other hand, `SourceLocation#source` property can be `undefined`. ESLint does not use the `SourceLocation#source` property.
```
Comment (platinumazure) [inline docs/developer-guide/working-with-plugins.md]: I think it would be good to note that for location positions, `line` is one-based and `column` is zero-based.

Saying so, maybe this should have a sublist? The main point is the `loc` must not be null even though `loc` is nullable in ESTree; then the sublist's bullet points can say that `start` and `end` must be a position with 1-based line and 0-based column, and `source` is not used by ESLint at all.

File: docs/developer-guide/working-with-plugins.md [hunk 5]
```diff
@@ -246,4 +246,33 @@ exports.parseForESLint = function(code, options) {
...
+
+The `parent` property of all nodes must be rewriteable. ESLint set their parent node to the `parent` properties while traversing.
```
Comment (platinumazure) [inline docs/developer-guide/working-with-plugins.md]: I feel the second sentence would flow better with the first by reversing the nouns:

> ESLint sets each node's `parent` properties to its parent node while traversing.

File: docs/developer-guide/working-with-plugins.md [hunk 6]
```diff
@@ -246,4 +246,33 @@ exports.parseForESLint = function(code, options) {
...
+
+#### The `Program` node:
+
+The `Program` node must have `tokens` and `comments` properties. Both properties are the array of the below Token interface.
```
Comment (platinumazure) [inline docs/developer-guide/working-with-plugins.md]: I think "Both properties are an array..." works better here.

File: docs/developer-guide/working-with-plugins.md [hunk 7]
```diff
@@ -246,4 +246,33 @@ exports.parseForESLint = function(code, options) {
...
+```ts
+interface Token {
+    type: string;
+    loc: SourceLocation;
+    range: [number, number];
+    value: string;
+}
+```
+
+* `tokens` (`Token[]`) is the array of tokens which affect the behavior of programs. Arbitrary spaces can exist between tokens, so rules check the `Token#range` to detect spaces between tokens. This must be sorted by `Token#range[0]`.
```
Comment (platinumazure) [inline docs/developer-guide/working-with-plugins.md]: I assume the `range` of tokens does not include surrounding whitespace, just like for nodes?

File: docs/developer-guide/working-with-plugins.md [hunk 8]
```diff
@@ -246,4 +246,33 @@ exports.parseForESLint = function(code, options) {
...
+* `comments` (`Token[]`) is the array of comment tokens. This must be sorted by `Token#range[0]`.
+
+The `tokens` and the `comments` must not be overlapped themselves and each other.
```
Comment (platinumazure) [inline docs/developer-guide/working-with-plugins.md]: I'm not sure I understand what you are trying to say here. Are you saying that for any comment or token, its `range[1]` must be less than or equal to all later tokens/comments `range[0]` so that the ranges do not overlap?

If so, I think that could be expressed like this:

> The `range` indexes of all tokens and comments must not overlap with the `range` of other tokens and comments.

Otherwise, if I've misunderstood, let me know.

File: lib/testers/test-parser.js [hunk 9]
```diff
@@ -0,0 +1,55 @@
+/**
+ * @author Toru Nagashima <https://github.com/mysticatea>
+ */
+"use strict";
+
+const espree = require("espree");
+const Traverser = require("../util/traverser");
+
+/**
+ * Remove `start`/`end` properties from the given node.
```
Comment (platinumazure) [inline lib/testers/test-parser.js]: We're no longer removing the `start`/`end` properties, but rather redefining them as getters that throw. Does this JSDoc need to be changed?

File: lib/testers/test-parser.js [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+ * @param {ASTNode} node The node to remove.
+ * @returns {void}
+ */
+function removeStartEnd(node) {
```
Comment (platinumazure) [inline lib/testers/test-parser.js]: We're no longer removing the `start`/`end` properties, but rather redefining them as getters that throw. Does this function name need to be changed?

File: lib/testers/test-parser.js [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+ * @author Toru Nagashima <https://github.com/mysticatea>
+ */
+"use strict";
+
+const espree = require("espree");
+const Traverser = require("../util/traverser");
+
+/**
+ * Remove `start`/`end` properties from the given node.
+ * @param {ASTNode} node The node to remove.
```
Comment (platinumazure) [inline lib/testers/test-parser.js]: We're no longer removing the `start`/`end` properties, but rather redefining them as getters that throw. Does this JSDoc need to be changed?

**Comment by mysticatea** [comment]
I added about `Literal#raw` properties since I have noticed the property does not exist in ESTree.

**Comment by mysticatea** [comment]
I'm sorry for delay.

@platinumazure Thank you for the review! I fixed those except one; about 1-based line and 0-based column of `SourceLocation`. It's defined by ESTree and ESLint has no different.
