### PR TITLE
Fix: prefer-const object destructuring false positive (fixes #9108)

### LINKED ISSUE #9108: prefer-const object destructuring false positive
**Tell us about your environment**

* **ESLint Version:** 4.4.0

**What parser (default, Babel-ESLint, etc.) are you using?** Babel-ESLint

**Please show your full configuration:**
```js
/* eslint prefer-const: [ "warn", { "destructuring": "all", "ignoreReadBeforeAssign": true } ] */
```

**What did you do? Please include the actual source code causing the issue.**

```js
/* eslint prefer-const: [ "warn", { "destructuring": "all", "ignoreReadBeforeAssign": true } ] */
/* global someFunc */
(function ({ a }) {
    let b;
    ({ a, b } = someFunc({ a }));
    return { a, b };
})()
```

**What did you expect to happen?**

Should pass since neither `let` nor `const` can be specified at the start of the variable assignment statement.

**What actually happened? Please include the actual, raw output from ESLint.**

```
5:11 - 'b' is never reassigned. Use 'const' instead. (prefer-const)
```

### PR DESCRIPTION
**Pull request by g-plane**
close #9108

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

https://github.com/eslint/eslint/issues/9108

**What changes did you make? (Give an overview)**
Allow:
```js
(function ({ a }) {
  let b;
  ({ a, b } = obj);
})();
```
or
```js
let a;
{
  let b;
  ({ a, b } = obj);
}
```

### CODE REVIEW

File: lib/rules/prefer-const.js [hunk 1]
```diff
@@ -290,7 +340,7 @@ module.exports = {
                     (varDeclParent.parent.type === "ForInStatement" || varDeclParent.parent.type === "ForOfStatement" || varDeclParent.declarations[0].init) &&
 
                     /*
-                     * If options.destucturing is "all", then this warning will not occur unless
+                     * If options.destructuring is "all", then this warning will not occur unless
```
Comment (btmills) [inline lib/rules/prefer-const.js]: Thank you :smile:
