### PR TITLE
fix: `no-dupe-keys` false positive with proto setter

### LINKED ISSUE #19504: Bug: (no-dupe-keys) The rule should differentiate computed `__proto__` and non-computed `__proto__`
### Environment

Node version: v23.6.0
npm version: v10.9.2
Local ESLint version: v9.13.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 24.3.0

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```js
export default [
    {
        "rules": {
            "no-dupe-keys": [
                "error"
            ]
        }
    }
];
```
</details>

```js
({
  ["__proto__"]: null,
  __proto__: null
})
```

### What did you expect to happen?

No errors. The computed `__proto__` key is a valid property while the non-computed one is the prototype setter.

### What actually happened?

3:3 Error: Duplicate key '__proto__'.  ([no-dupe-keys](https://eslint.org/docs/rules/no-dupe-keys))

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiKHtcbiAgW1wiX19wcm90b19fXCJdOiBudWxsLFxuICBfX3Byb3RvX186IG51bGxcbn0pIiwib3B0aW9ucyI6eyJydWxlcyI6eyJuby1kdXBlLWtleXMiOlsiZXJyb3IiXX0sImxhbmd1YWdlT3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Found this issue when drafting a Babel test: https://github.com/babel/babel/pull/17175. We have to disable this rule for the specific line.

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #19504

#### What changes did you make? (Give an overview)

Updated `no-dupe-keys` rule to ignore proto setter syntax in object literals.

### CODE REVIEW

File: tests/lib/rules/no-dupe-keys.js [hunk 1]
```diff
@@ -40,7 +40,11 @@ ruleTester.run("no-dupe-keys", rule, {
         { code: "var x = ({ null: 1, [/(?<zero>0)/]: 2 })", languageOptions: { ecmaVersion: 2018 } },
         { code: "var {a, a} = obj", languageOptions: { ecmaVersion: 6 } },
         "var x = { 012: 1, 12: 2 };",
-        { code: "var x = { 1_0: 1, 1: 2 };", languageOptions: { ecmaVersion: 2021 } }
+        { code: "var x = { 1_0: 1, 1: 2 };", languageOptions: { ecmaVersion: 2021 } },
+        { code: "var x = { __proto__: null, ['__proto__']: null };", languageOptions: { ecmaVersion: 6 } },
+        { code: "var x = { ['__proto__']: null, __proto__: null };", languageOptions: { ecmaVersion: 6 } },
+        { code: "var x = { '__proto__': null, ['__proto__']: null };", languageOptions: { ecmaVersion: 6 } },
+        { code: "var x = { ['__proto__']: null, '__proto__': null };", languageOptions: { ecmaVersion: 6 } },
```
Comment (JLHwung) [inline tests/lib/rules/no-dupe-keys.js:47]: Could you add a test case for `{ __proto__: null, __proto__ }`?

**Review by nzakas — APPROVED** [review]
LGTM. Would like @JLHwung to verify his feedback has been addressed.

**Comment by JLHwung** [comment]
LGTM, thank you for the prompt fix.
