### PR TITLE
Fix: no-irregular-whitespace should work with irregular line breaks (fixes #2316)

### LINKED ISSUE #2316: no-irregular-whitespace not catching \u2028
The [docs](http://eslint.org/docs/rules/no-irregular-whitespace.html) list [`\u2028` (Line Separator)](http://www.fileformat.info/info/unicode/char/2028/index.htm) as one of the characters that the `no-irregular-whitespace` rule will catch. In my experience, this is not the case:

screen shot 2015-04-14 at 5 31 41 pm

Allowing this character caused an uglify step in a build of mine to fail. Would be nice if ESLint could catch  it. If not, the docs need to be updated.

I'm on a Mac, in case that helps.

### PR DESCRIPTION
**Pull request by lo1tuma**
The underlying problem of `\u2028` and `\u2029` not being checked by this rule was that it only operated on the source lines retrieved by `context.getSourceLines()`. `\u2028` and `\u2029` are line terminators and are removed by [splitting the source](https://github.com/eslint/eslint/blob/88b5ffa14fe11b0cc55ca60bf42d508a32d5c231/lib/eslint.js#L692) into lines.

### CODE REVIEW

File: lib/rules/no-irregular-whitespace.js [hunk 1]
```diff
@@ -47,12 +48,52 @@ module.exports = function(context) {
     function removeInvalidNodeErrors(node) {
         if (typeof node.value === "string") {
             // If we have irregular characters remove them from the errors list
-            if (node.value.match(irregularWhitespace)) {
+            if (node.raw.match(irregularWhitespace) || node.raw.match(irregularLineTerminators)) {
```
Comment (lo1tuma) [inline lib/rules/no-irregular-whitespace.js]: Linebreaks are removed from `node.value` so we have to use `node.raw` instead.

File: lib/rules/no-irregular-whitespace.js [hunk 2]
```diff
@@ -47,12 +48,52 @@ module.exports = function(context) {
...
 
+    function checkForIrregularWhitespace(node) {
+        var sourceLines = context.getSourceLines();
+
+        sourceLines.forEach(function (sourceLine, lineIndex) {
+            var lineNumber = lineIndex + 1,
+                location,
+                match;
+
+            while ((match = irregularWhitespace.exec(sourceLine)) !== null) {
```
Comment (lo1tuma) [inline lib/rules/no-irregular-whitespace.js]: Drive-by-fix: using a while instead of if, allows to detect multiple errors in a single line.

File: lib/rules/no-irregular-whitespace.js [hunk 3]
```diff
@@ -61,26 +102,13 @@ module.exports = function(context) {
...
-                }
-            });
+            checkForIrregularWhitespace(node);
+            checkForIrregularLineTerminators(node);
         },
+
         "Identifier": removeInvalidNodeErrors,
         "Literal": removeInvalidNodeErrors,
-        "Statement": removeInvalidNodeErrors,
-        "Expression": removeInvalidNodeErrors,
```
Comment (lo1tuma) [inline lib/rules/no-irregular-whitespace.js]: I removed `"Statement"` and `"Expression"` because I don’t think those node types even exist.

I’m not sure about `"Identifier"`, everything seems to work if I remove this listener.

File: lib/rules/no-irregular-whitespace.js [hunk 4]
```diff
@@ -47,12 +48,52 @@ module.exports = function(context) {
...
         if (typeof node.value === "string") {
             // If we have irregular characters remove them from the errors list
-            if (node.value.match(irregularWhitespace)) {
+            if (node.raw.match(irregularWhitespace) || node.raw.match(irregularLineTerminators)) {
                 removeStringError(node);
             }
         }
     }
 
+    function checkForIrregularWhitespace(node) {
```
Comment (nzakas) [inline lib/rules/no-irregular-whitespace.js]: Can you add JSDoc comments for the new functions?

File: lib/rules/no-irregular-whitespace.js [hunk 5]
```diff
@@ -47,12 +48,52 @@ module.exports = function(context) {
...
+            lineNumber,
+            location,
+            match;
+
+        while ((match = irregularLineTerminators.exec(source)) !== null) {
+            lineNumber = linebreaks.indexOf(match[0], lastLineNumber + 1) + 1 || 1;
+
+            location = {
+                line: lineNumber,
+                column: context.getSourceLines()[lineNumber - 1].length
```
Comment (nzakas) [inline lib/rules/no-irregular-whitespace.js]: Better to cache the result of getSourceLines() as it never changes

**Comment by nzakas** [comment]
I'm wondering if we can avoid two separate loops by splitting getSource() on just the normal line breaks?

**Comment by nzakas** [comment]
@lo1tuma any update on this?

**Comment by lo1tuma** [comment]
@nzakas sorry for the delay, I had a lot of work this week.

I’ve added the JSDoc comment and cached the result of `getSourceLines`. But I don’t have a good idea how to combine both loops. If I would split the source just on the normal line breaks I can’t determine the correct location of errors

**Comment by nzakas** [comment]
Gotcha. I'm a bit concerned about performance with two doing two l loops, but dying have a better option right now. Lgtm
