### PR TITLE
fix: unify timing report for concurrent linting

### LINKED ISSUE #20063: Change Request: unified TIMING report with concurrent linting
### ESLint version

9.34.0

### What problem do you want to solve?

If I run `TIMING=all eslint --concurrency=3`, I get 3 different timing reports (probably one per thread) that all show different rules taking different times.

### What do you think is the correct solution?

A unified timing report that has a full overview, just as we get when used without concurrent linting.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by crimsonjay0**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

When running ESLint with `--concurrency`, multiple timing reports were generated — one per worker thread — resulting in fragmented timing data.

This change ensures that timing information is collected and merged into a single unified report, matching the behavior seen when linting without concurrency.

- Add `getData()` to expose per-rule timing totals from each worker.
- Add `mergeData()` to aggregate worker timings in the main thread.
- Print the timing table only from the main thread to avoid multiple outputs.

Fixes #20063

### CODE REVIEW

**Comment by mdjermanovic** [comment]
When I test this locally, with this project, it prints 3 extra headers for the table:

```
$ TIMING=10 node bin/eslint . --concurrency 2
(node:9364) ESLintIgnoreWarning: The ".eslintignore" file is no longer supported. Switch to using the "ignores" property in "eslint.config.js": https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files(Use `node --trace-warnings ...` to show where the warning was created)
Rule | Time (ms) | Relative
:----|----------:|--------:
Rule | Time (ms) | Relative
:----|----------:|--------:
Rule                                | Time (ms) | Relative
:-----------------------------------|----------:|--------:
n/no-extraneous-require             |  1138.998 |     5.5%
jsdoc/valid-types                   |   975.487 |     4.7%
expect-type/expect                  |   845.054 |     4.1%
jsdoc/check-access                  |   822.265 |     3.9%
jsdoc/check-values                  |   758.577 |     3.6%
jsdoc/check-types                   |   702.723 |     3.4%
n/no-unsupported-features/es-syntax |   571.277 |     2.7%
jsdoc/check-tag-names               |   554.260 |     2.7%
jsdoc/check-alignment               |   539.435 |     2.6%
n/no-unpublished-require            |   534.973 |     2.6%
Rule | Time (ms) | Relative
:----|----------:|--------:
```

Not sure why and how this happens.

File: lib/linter/timing.js [hunk 1]
```diff
@@ -158,15 +157,50 @@ module.exports = (function () {
...
+			data[key] += value;
+		}
+	}
+
 	if (enabled) {
-		process.on("exit", () => {
-			display(data);
-		});
+		try {
+			const { isMainThread } = require("node:worker_threads");
```
Comment (mdjermanovic) [inline lib/linter/timing.js]: I have concerns that adding a dependency to a `node:` module in code that is used by `Linter` (which can be used in browsers) might cause problems when bundling for browsers. Would it make sense to, instead, export a `disableDisplay()` function that sets a flag to disable display, and then call it in `worker.js`?

Comment (crimsonjay0) [reply lib/linter/timing.js]: Makes sense to me 👍

**Comment by crimsonjay0** [comment]
@mdjermanovic I tested this multiple times locally, but I’m not getting the extra headers

**Comment by mdjermanovic** [comment]
I'm still getting extra headers, but it's interesting that I'm also getting one extra header on the `main` branch even without concurrency.

```
$ TIMING=10 npx eslint Makefile.js
(node:12608) ESLintIgnoreWarning: The ".eslintignore" file is no longer supported. Switch to using the "ignores" property in "eslint.config.js": https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files
(Use `node --trace-warnings ...` to show where the warning was created)
Rule                                | Time (ms) | Relative
:-----------------------------------|----------:|--------:
n/no-extraneous-require             |    43.087 |    17.0%
regexp/confusing-quantifier         |    23.604 |     9.3%
jsdoc/check-access                  |     9.383 |     3.7%
jsdoc/valid-types                   |     7.549 |     3.0%
jsdoc/check-types                   |     6.048 |     2.4%
n/no-unsupported-features/es-syntax |     5.920 |     2.3%
n/no-unpublished-require            |     5.436 |     2.1%
n/no-missing-require                |     5.267 |     2.1%
jsdoc/check-values                  |     5.156 |     2.0%
jsdoc/require-property-description  |     4.477 |     1.8%
Rule | Time (ms) | Relative
:----|----------:|--------:
```

Anyone else getting the same? It could be that some of the eslint plugins we're using is doing something unusual, like importing Linter.

**Comment by fasttime** [comment]
> Anyone else getting the same? It could be that some of the eslint plugins we're using is doing something unusual, like importing Linter.

I'm not getting multiple headers with `TIMING=10 npx eslint Makefile.js`. Is the initialization code in `lib/linter/timing.js` running twice for you?

**Comment by mdjermanovic** [comment]
Okay, I got it. `eslint-plugin-jsdoc` and `eslint-plugin-unicorn` are importing some `eslint` modules, and that also triggers loading the `timing.js` module. Plus, after some testing, I had both plugins installed under `packages/eslint-config-eslint/node_modules` along with a copy of `eslint`, and that copy of `eslint` was printing extra headers. So it's definitely not a problem caused by this PR.

File: lib/eslint/worker.js [hunk 2]
```diff
@@ -158,5 +165,7 @@ debug("Dependencies loaded in %t", depsLoadedTime - startTime);
 	indexedResults.netLintingDuration =
 		lintingDuration - loadConfigTotalDuration - readFileCounter.duration;
 
+	indexedResults.timings = timing.getData();
```
Comment (mdjermanovic) [inline lib/eslint/worker.js]:
```suggestion
	if (timing.enabled) {
		indexedResults.timings = timing.getData();
	}
```

Maybe we could attach this object only when it's needed?

File: lib/eslint/eslint.js [hunk 3]
```diff
@@ -503,6 +504,11 @@ async function runWorkers(
 					worstNetLintingRatio,
 					netLintingRatio,
 				);
+
+				if (timing.enabled) {
+					timing.mergeData(indexedResults.timings);
```
Comment (fasttime) [inline lib/eslint/eslint.js:509]: If an error is thrown while processing files, for example because a rule crashes, an empty header is printed:

```shell
$ TIMING=10 node ./bin/eslint.js --concurrency=2
(node:57750) ESLintIgnoreWarning: The ".eslintignore" file is no longer supported. Switch to using the "ignores" property in "eslint.config.js": https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files
(Use `node --trace-warnings ...` to show where the warning was created)

Oops! Something went wrong! :(

ESLint: 9.37.0

TypeError: Cannot read properties of null (reading 'length')
Occurred while linting .../eslint/.trunk/configs/svgo.config.js:1
Rule: "strict"
    at Program (.../eslint/lib/rules/strict.js:282:27)
    at .../eslint/lib/linter/timing.js:147:19
    at ruleErrorHandler (.../eslint/lib/linter/linter.js:1173:33)
    at .../eslint/lib/linter/source-code-visitor.js:76:46
    at Array.forEach (<anonymous>)
    at SourceCodeVisitor.callSync (.../eslint/lib/linter/source-code-visitor.js:76:30)
    at .../eslint/lib/linter/source-code-traverser.js:291:18
    at Array.forEach (<anonymous>)
    at SourceCodeTraverser.traverseSync (.../eslint/lib/linter/source-code-traverser.js:290:10)
    at runRules (.../eslint/lib/linter/linter.js:1214:12)
Rule | Time (ms) | Relative
:----|----------:|--------:
```

Without concurrency, the timing report is always printed.

File: lib/eslint/worker.js [hunk 4]
```diff
@@ -29,6 +29,13 @@ const {
 	processOptions,
 } = require("./eslint-helpers");
 const { WarningService } = require("../services/warning-service");
+const timing = require("../linter/timing");
+
+/*
+ * Prevent timing module from printing profiling output from worker threads.
+ * The main thread is responsible for displaying any aggregated timings.
+ */
+timing.disableDisplay();
```
Comment (fasttime) [inline lib/eslint/worker.js]: Can we move this function call under the "Main" program section below?

https://github.com/eslint/eslint/blob/469e9385811343fa8ded39573145b30553bd52d2/lib/eslint/worker.js#L63-L65

File: lib/eslint/eslint.js
Comment (fasttime) [inline lib/eslint/eslint.js:1]: In the rare case where some worker threads finish successfully while others fail, the timing output may become inconsistent. This happens because `mergeData()` is only invoked for threads that exit normally. One possible solution would be to call `disableDisplay()` in the main thread to suppress timing output whenever the promise returned by `runWorkerThreads()` rejects:

https://github.com/eslint/eslint/blob/469e9385811343fa8ded39573145b30553bd52d2/lib/eslint/eslint.js#L558-L563

Alternatively, we could consider this scenario too unlikely to matter in practice and leave the current logic unchanged. What do you think?

Comment (crimsonjay0) [reply lib/eslint/eslint.js:1]: I think that’s a sensible, low-risk fix 👍

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
