### PR TITLE
Fix: arrow-parens fixer gets tripped up with trailing comma in args

### LINKED ISSUE #8834: arrow-parens fixer gets tripped up with trailing comma in args
**Tell us about your environment**

* **ESLint Version:** v4.1.1
* **Node Version:** v6.2.2
* **npm Version:** v3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
Default

**Please show your full configuration:**
```json
{
  "root": true,
  "parserOptions": {
    "ecmaVersion": 8
  },

  "rules": {
    "arrow-parens": ["error", "as-needed", {
      "requireForBlockBody": true
    }]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

With this code:
```js
const foo = (
  bar,
) => ({});
```

and then running `eslint --fix`

**What did you expect to happen?**

```js
const foo = bar => ({});
```

**What actually happened? Please include the actual, raw output from ESLint.**

The file was transformed to this syntax error.
```js
const foo = bar
) => ({});
```

The eslint output complains about the syntax error it introduced:

>  2:1  error  Parsing error: Unexpected token )

The fixer seems to work correctly if I remove the trailing comma from the argument.

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

**What changes did you make? (Give an overview)**
fixes #8834 

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

File: lib/rules/arrow-parens.js [hunk 1]
```diff
@@ -66,7 +66,13 @@ module.exports = {
              */
             function fixParamsWithParenthesis(fixer) {
                 const paramToken = sourceCode.getTokenAfter(firstTokenOfParam);
-                const closingParenToken = sourceCode.getTokenAfter(paramToken);
+                let closingParenToken = sourceCode.getTokenAfter(paramToken);
```
Comment (platinumazure) [inline lib/rules/arrow-parens.js]: Can we use a predicate here instead of using the if statement below? Maybe something like `sourceCode.getTokenAfter(paramToken, astUtils.isClosingParenToken)`?

Comment (Aladdin-ADD) [inline lib/rules/arrow-parens.js]: great, I'm just looking for something like this. thanks~~
