### PR TITLE
Fix: prevent crashing from JSON parsing error (fixes #10364)

### LINKED ISSUE #10364: crash on malformed package.json
If `package.json` is malformed, eslint fails by crashing. This is relevant because then in Atom, every file that is to be checked by eslint is marked as invalid.

**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 9.8.0
* **npm Version:** 6.0.1

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

original `package.json` so I can `npm i` eslint:

```json
{
  "name": "test",
  "version": "0.1.0",
  "description": "test eslint",
  "main": "app.js",
  "scripts": {
    "lint": "eslint ."
  },
  "author": "Jacek Kopecky <jacek@jacek.cz>",
  "engines": {
    "node": ">=8.7.0"
  },
  "devDependencies": {
    "eslint": "^4.19.1"
  }
}
```

No `.eslintrc` or anything like that.

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I was editing package.json and introduced a syntax error - the usual extra comma (near the end of the file below).

```json
{
  "name": "test",
  "version": "0.1.0",
  "description": "test eslint",
  "main": "app.js",
  "scripts": {
    "lint": "eslint ."
  },
  "author": "Jacek Kopecky <jacek@jacek.cz>",
  "engines": {
    "node": ">=8.7.0"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
  }
}
```

Then I want to lint the project:

```bash
eslint .
```

**What did you expect to happen?**

Eslint should either fail gracefully with a warning because it can't parse `package.json`, or it assumes there's nothing in `package.json` of interest to eslint (which is correct) and proceeds to check the directory, which is otherwise empty so eslint succeeds quietly. If eslint fails, its output should clearly blame `package.json` in the normal »this file has a linting error« format.

**What actually happened? Please include the actual, raw output from ESLint.**

Crash.

```
Unexpected token } in JSON at position 275
SyntaxError: Unexpected token } in JSON at position 275
    at JSON.parse (<anonymous>)
    at new IgnoredPaths (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/ignored-paths.js:176:55)
    at lodash.memoize.optionsObj (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/util/glob-util.js:115:13)
    at memoized (/Users/kopeckyj/tmp/eslint/node_modules/lodash/lodash.js:10551:27)
    at globPatterns.forEach.pattern (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/util/glob-util.js:175:34)
    at Array.forEach (<anonymous>)
    at Object.listFilesToProcess (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/util/glob-util.js:158:18)
    at CLIEngine.executeOnFiles (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/cli-engine.js:518:35)
    at Object.execute (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/cli.js:189:111)
    at Object.<anonymous> (/Users/kopeckyj/tmp/eslint/node_modules/eslint/bin/eslint.js:74:28)
```

### PR DESCRIPTION
**Pull request by g-plane**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

close #10364 

**What changes did you make? (Give an overview)**
Display better error message when failed to parse JSON.

### CODE REVIEW

**Comment by g-plane** [comment]
So what should the `message` looks like? The original error message looks like `SyntaxError: Unexpected token } in JSON at position ...`

**Comment by g-plane** [comment]
The reason I removed that line is, IMHO, it's duplicated because the old line contains `e.message` which equals to the original error message. However, on the other hand, the template just says `failed to parse JSON` instead of `Cannot read config file`(it tells the users something broken in config file instead of other JSON files).

And, I haven't tested it by using Node.js API `CLIEngine`. So maybe you are right.

What do you think?

**Comment by platinumazure** [comment]
@g-plane I think you're probably right that the message "Failed to parse JSON" is not super useful. But I also think "Syntax error: Unexpected token }" is not very useful either, hence the motivation for the message template that says failed to parse config file.

Maybe we should still wrap/change `e.message`, but with something close to what the template says?

If you get a chance to test this case in CLIEngine, hopefully you'll see what I'm getting at. :smile:

**Comment by g-plane** [comment]
Ok, you are right. Wrapping the error message is friendly for `CLIEngine`.

Another question,
> I also think "Syntax error: Unexpected token }" is not very useful either
Can we use `babel-code-frame` to solve this problem?

**Comment by platinumazure** [comment]
@g-plane 

> Can we use `babel-code-frame` to solve this problem?

Not sure what you mean. Could you please elaborate on this? Thanks!

**Comment by g-plane** [comment]
@platinumazure I have updated for `lib/config/config-file.js`.

File: lib/config/config-file.js [hunk 1]
```diff
@@ -115,6 +115,11 @@ function loadJSONConfigFile(filePath) {
     } catch (e) {
         debug(`Error reading JSON file: ${filePath}`);
         e.message = `Cannot read config file: ${filePath}\nError: ${e.message}`;
+        e.messageTemplate = "failed-to-parse-json";
+        e.messageData = {
+            path: filePath,
+            messsage: e.messsage
```
Comment (platinumazure) [inline lib/config/config-file.js]: s/messsage/message (twice)

File: lib/util/npm-util.js [hunk 2]
```diff
@@ -109,7 +109,11 @@ function check(packages, opt) {
     try {
         fileJson = JSON.parse(fs.readFileSync(pkgJson, "utf8"));
     } catch (e) {
-        log.info("Could not read package.json file. Please check that the file contains valid JSON.");
+        e.messageTemplate = "failed-to-parse-json";
+        e.messageData = {
+            path: pkgJson,
+            messsage: e.messsage
```
Comment (platinumazure) [inline lib/util/npm-util.js]: s/messsage/message (twice)

**Comment by g-plane** [comment]
It seems that there no such tests to check message template. (Not only this template but also other templates.)

**Comment by platinumazure** [comment]
Hi, apologies, I just meant adding any assertions to existing tests that
check that the exception is thrown in the first place. On top of checking
that the exception is thrown, we could inspect its properties.

We don't need to test the rendering of the template. We just want to test
that this exception is associated with a template... Hope that makes sense.

**Comment by g-plane** [comment]
Updated.

File: lib/config/config-file.js [hunk 3]
```diff
@@ -115,6 +115,11 @@ function loadJSONConfigFile(filePath) {
     } catch (e) {
         debug(`Error reading JSON file: ${filePath}`);
         e.message = `Cannot read config file: ${filePath}\nError: ${e.message}`;
+        e.messageTemplate = "failed-to-parse-json";
```
Comment (not-an-aardvark) [inline lib/config/config-file.js]: I don't think the error here will necessarily be a JSON parsing error. This error-handling code will run when anything in `JSON.parse(stripComments(readFile(filePath)))` throws an error, which could include errors from the filesystem.

This could either be addressed by using different `try`/`catch` blocks for the different function calls (and providing a different error message as appropriate), or making the `failed-to-parse-json` error message more generic (e.g. "Failed to read JSON file" rather than "Failed to parse JSON file").

**Comment by g-plane** [comment]
@not-an-aardvark I have moved it to a separated try/catch block.

**Comment by not-an-aardvark** [comment]
Thanks! However, I think the same concern about the error message applies to all of the other `try`/`catch` blocks in this PR too. (Sorry, I should have been more clear originally.)

**Comment by g-plane** [comment]
@not-an-aardvark Review again?
