### PR TITLE
Fix: Incorrect object-property-newline behavior (fixes #6207)

### LINKED ISSUE #6207: object-property-newline has problems with the experimental object rest spread feature
**What version of ESLint are you using?**
2.10.2
**What parser (default, Babel-ESLint, etc.) are you using?**
default, Babel-ESLint - both don't work
**Please show your full configuration:**
```js
parserOptions: {
  ecmaVersion: 6,
  ecmaFeatures: {
    experimentalObjectRestSpread: true
  }
}
```
**What did you do? Please include the actual source code causing the issue.**
```js
var obj = { k1: 'val1', k2: 'val2', ...{} };
```
**What did you expect to happen?**
No errors.
**What actually happened? Please include the actual, raw output from ESLint.**
```
TypeError: Cannot read property 'range' of undefined
      at SourceCode.api.getFirstToken (D:\Projects\eslint\lib\token-store.js:9:3834)
      at EventEmitter.ObjectExpression (D:\Projects\eslint\lib\rules\object-property-newline.js:9:2164)
      at NodeEventGenerator.enterNode (D:\Projects\eslint\lib\util\node-event-generator.js:9:359)
      at CodePathAnalyzer.enterNode (D:\Projects\eslint\lib\code-path-analysis\code-path-analyzer.js:9:23334)
      at CommentEventGenerator.enterNode (D:\Projects\eslint\lib\util\comment-event-generator.js:9:2024)
      at Controller.traverser.traverse.enter (D:\Projects\eslint\lib\eslint.js:9:32865)
      at Controller.__execute (D:\Projects\eslint\node_modules\estraverse\estraverse.js:397:31)
      at Controller.traverse (D:\Projects\eslint\node_modules\estraverse\estraverse.js:501:28)
      at Controller.Traverser.controller.traverse (D:\Projects\eslint\lib\util\traverser.js:9:626)
      at EventEmitter.module.exports.api.verify (D:\Projects\eslint\lib\eslint.js:9:32670)
      at runRuleForItem (D:\Projects\eslint\lib\testers\rule-tester.js:9:9027)
      at testValidTemplate (D:\Projects\eslint\lib\testers\rule-tester.js:9:9669)
      at Context.<anonymous> (D:\Projects\eslint\lib\testers\rule-tester.js:9:14513)
      at callFn (D:\Projects\eslint\node_modules\mocha\lib\runnable.js:315:21)
      at Test.Runnable.run (D:\Projects\eslint\node_modules\mocha\lib\runnable.js:308:7)
      at Runner.runTest (D:\Projects\eslint\node_modules\mocha\lib\runner.js:422:10)
      at D:\Projects\eslint\node_modules\mocha\lib\runner.js:533:12
      at next (D:\Projects\eslint\node_modules\mocha\lib\runner.js:342:14)
      at D:\Projects\eslint\node_modules\mocha\lib\runner.js:352:7
      at next (D:\Projects\eslint\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (D:\Projects\eslint\node_modules\mocha\lib\runner.js:320:5)
```

I'd like to try and fix this, if that's ok. I've already started setting up some tests and reading the code.

### PR DESCRIPTION
**Pull request by fatfisz**
Syntax that wasn't handled correctly / caused errors to be thrown:
- computed keys spanning multiple lines
- experimental object spread

### CODE REVIEW

File: lib/rules/object-property-newline.js [hunk 1]
```diff
@@ -56,8 +56,8 @@ module.exports = {
                 }
 
                 for (var i = 1; i < node.properties.length; i++) {
-                    lastTokenOfPreviousValue = sourceCode.getLastToken(node.properties[i - 1].value);
-                    firstTokenOfCurrentKey = sourceCode.getFirstToken(node.properties[i].key);
+                    lastTokenOfPreviousValue = sourceCode.getLastToken(node.properties[i - 1]);
+                    firstTokenOfCurrentKey = sourceCode.getFirstToken(node.properties[i]);
```
Comment (vitorbal) [inline lib/rules/object-property-newline.js]: I think the variables should be renamed to reflect what they store now. How about something like:
`lastTokenOfPreviousProperty` and `firstTokenOfCurrentProperty`

Comment (fatfisz) [inline lib/rules/object-property-newline.js]: Good catch! Will fix this.

File: lib/rules/object-property-newline.js [hunk 2]
```diff
@@ -40,14 +40,14 @@ module.exports = {
...
             ObjectExpression: function(node) {
-                var lastTokenOfPreviousValue, firstTokenOfCurrentKey;
+                var lastTokenOfPreviousProperty, firstTokenOfCurrentProperty;
 
                 if (allowSameLine) {
                     if (node.properties.length > 1) {
-                        var firstToken = sourceCode.getFirstToken(node.properties[0].key);
-                        var lastToken = sourceCode.getLastToken(node.properties[node.properties.length - 1].value);
+                        var firstTokenOfFirstProperty = sourceCode.getFirstToken(node.properties[0]);
+                        var lastTokenOfLastProperty = sourceCode.getLastToken(node.properties[node.properties.length - 1]);
```
Comment (fatfisz) [inline lib/rules/object-property-newline.js]: @vitorbal I've also changed these so they would be more verbose and more consistent with the other var names. Is that ok?

Comment (vitorbal) [inline lib/rules/object-property-newline.js]: Sounds great, good idea!

**Comment by nzakas** [comment]
Lgtm. Thanks @fatfisz !
