### PR TITLE
Fix: no-magic-numbers: variable declarations (fixes #4192)

### LINKED ISSUE #4192: no-magic-numbers: UnaryExpression + number is considered as error
Currently following code is considered as error: ```var foo = -42;```
I don't think it should do so

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27519646-no-magic-numbers-unaryexpression-number-is-considered-as-error?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ipanasenko**
Currently following code is considered as error: ```var foo = -42;```
I don't think it should

### CODE REVIEW

**Comment by michaelficarra** [comment]
This will allow negative magic numbers anywhere. It will also allow unary computation on magic numbers in any position, such as `~1`.

**Comment by ipanasenko** [comment]
Sorry, I will provide update to this PR now

**Comment by ipanasenko** [comment]
updated

File: lib/rules/no-magic-numbers.js [hunk 1]
```diff
@@ -79,6 +79,10 @@ module.exports = function(context) {
                 return;
             }
 
+            if (parent.type === "UnaryExpression" && parent.operator === "-") {
```
Comment (michaelficarra) [inline lib/rules/no-magic-numbers.js]: You should move this up above line 69, and any reference to `node.value` should be replaced with a stored value that is negated when we get into this block.

**Comment by ipanasenko** [comment]
Updated PR.
I also added ignoring of ```.toString(radix)``` calls

**Comment by michaelficarra** [comment]
That was not part of the issue. If you want to do that, open a separate issue and separate PR for it.

**Comment by michaelficarra** [comment]
LGTM otherwise. :+1:

**Comment by ipanasenko** [comment]
Updated PR, removed .toString, will create new issue and PR
Thanks!

File: lib/rules/no-magic-numbers.js [hunk 2]
```diff
@@ -42,12 +42,12 @@ module.exports = function(context) {
...
-     * Returns whether the node is number literal
-     * @param {Node} node - the node literal being evaluated
-     * @returns {boolean} true if the node is a number literal
+     * Returns whether the value is number
+     * @param {*} value - the value being evaluated
+     * @returns {boolean} true if value is a number
      */
-    function isNumber(node) {
-        return typeof node.value === "number";
+    function isNumber(value) {
```
Comment (nzakas) [inline lib/rules/no-magic-numbers.js]: This seems like an unnecessary change. Why was it made?

Comment (ipanasenko) [inline lib/rules/no-magic-numbers.js]: because of line 75: node = parent.
node passed to isNumber is not number Literal, but its UnaryExpression parent, which value is '-'

Comment (nzakas) [inline lib/rules/no-magic-numbers.js]: `isNumber()` is only called on line 70, at which point you're just passing in `node.value` anyway. Line 75 changes `value`, but that's after the point that `isNumber()` is called. Unless I'm missing something?

Comment (michaelficarra) [inline lib/rules/no-magic-numbers.js]: We should just get rid of this function then and do this test inline.

Comment (ipanasenko) [inline lib/rules/no-magic-numbers.js]: Removed this function, updated PR
Do we also need ```shouldIgnoreNumber``` function? It's also used only once and that test can be done inline too

Comment (michaelficarra) [inline lib/rules/no-magic-numbers.js]: That's up to you. I would remove it.

Comment (nzakas) [inline lib/rules/no-magic-numbers.js]: I think it's cleaner with the two functions. Note, I didn't ask for the function to be removed, just to leave it alone. :)

Comment (ipanasenko) [inline lib/rules/no-magic-numbers.js]: Okay, I returned it all back

**Comment by nzakas** [comment]
Lgtm. Thanks!
