### PR TITLE
Fix: no-trailing-spaces now handles skipBlankLines (fixes #2575)

### LINKED ISSUE #2575: no-trailing-spaces does not properly handle skipBlankLines
When running
```
eslint --reset --rule 'no-trailing-spaces: [2, {skipBlankLines:true}]' test.js
```

with `test.js` as (where `_` is a space and `>` is a tab character)
```javascript
var a = 'bar';__
_
>
```

outputs the following:
```
test.js
  2:0  error  Trailing spaces not allowed  no-trailing-spaces
  3:0  error  Trailing spaces not allowed  no-trailing-spaces

✖ 2 problems (2 errors, 0 warnings)
```

which is incorrect. The expected outcome is
```
test.js
  1:14  error  Trailing spaces not allowed  no-trailing-spaces

✖ 1 problem (1 error, 0 warnings)
```

This is being caused by the [regex used for detecting trailing whitespace](https://github.com/eslint/eslint/blob/master/lib/rules/no-trailing-spaces.js#L32).

### PR DESCRIPTION
**Pull request by gcochard**
This does potentially two regexp tests per line. With this change, the performance does not seem to be impacted in a statistically significant way.

With: 
```
node Makefile.js perf
CPU Speed is 2200 with multiplier 7500000
Performance Run #1:  2177.437605ms
Performance Run #2:  2095.757845ms
Performance Run #3:  2085.389922ms
Performance Run #4:  2096.332165ms
Performance Run #5:  2082.197974ms
Performance budget ok:  2095.757845ms (limit: 3409.090909090909ms)
```
Without:
```
node Makefile.js perf
CPU Speed is 2200 with multiplier 7500000
Performance Run #1:  2085.415068ms
Performance Run #2:  2181.624126ms
Performance Run #3:  2082.826633ms
Performance Run #4:  2136.809016ms
Performance Run #5:  2126.298463ms
Performance budget ok:  2126.298463ms (limit: 3409.090909090909ms)
```

### CODE REVIEW

File: lib/rules/no-trailing-spaces.js [hunk 1]
```diff
@@ -25,25 +27,31 @@ module.exports = function(context) {
...
+                skipMatch = new RegExp(SKIP_BLANK),
+                matches, lines = src.split(/\r?\n/), location;
 
-            while ((match = re.exec(src)) !== null) {
-                lines = src.slice(0, re.lastIndex).split(/\r?\n/g);
+            for (var i = 0, ii = lines.length; i < ii; i++) {
+                if (skipBlankLines && skipMatch.test(lines[i])) {
+                    continue;
+                }
+                matches = re.exec(lines[i]);
```
Comment (ilyavolodin) [inline lib/rules/no-trailing-spaces.js]: I think I would swap the order of those tests. First check if it has any trailing spaces, then check if it's a blank line, only if it has trailing spaces. It's a good assumption that number of lines with content is going to be greater then number of empty lines, and number of lines with trailing spaces will be less then full number of lines. So in the end two RegEx will execute less often (only for lines with trailing spaces or empty lines).

Comment (gcochard) [inline lib/rules/no-trailing-spaces.js]: Great point. I have swapped those tests.

**Comment by gcochard** [comment]
Comments addressed. Good to go.
