### PR TITLE
Breaking: support @scope shorthand in plugins (fixes #9903)

### LINKED ISSUE #9903: Proposal: support @scope for @scope/eslint-plugin
**Tell us about your environment**

* **ESLint Version:** v4.16.0
* **Node Version:** v9.2.0
* **npm Version:** v5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

- default

**Please show your full configuration:**

<details open>
<summary>Configuration</summary>

```js
module.exports = {
  plugins: [
    '@scope'
  ],
  rules: {
    '@scope/rule': 'error'
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I run ESLint.

**What did you expect to happen?**

ESLint loads `@scope/eslint-plugin`.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint failed to load `eslint-plugin-@scope`.

```
Oops! Something went wrong! :(

ESLint: 4.16.0.
ESLint couldn't find the plugin "eslint-plugin-@scope". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-@scope is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-@scope@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

----

ESLint supports `@scope` for `@scope/eslint-config` since #3123, but doesn't support `@scope` for `@scope/eslint-plugin`.
It looks inconsistent.

I propose the feature, ESLint resolves `plugins: ["@scope"]` to `@scope/eslint-plugin`.

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[X] Add something to the core
[ ] Other, please explain:

Fixes #9903.

**What changes did you make? (Give an overview)**

This is a reference implementation for #9903.
This PR changes the logic to normalize plugin names as same as shareable config's.
As the result, we can use `plugins: ["@scope"]` shorthand for `@scope/eslint-plugin` package.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: lib/util/naming.js [hunk 1]
```diff
@@ -60,23 +60,28 @@ function normalizePackageName(name, prefix) {
...
  * @param {string} prefix The prefix to remove.
- * @param {string} term The term which may have the prefix.
  * @returns {string} The term without prefix.
  */
-function removePrefixFromTerm(prefix, term) {
-    return term.startsWith(prefix) ? term.slice(prefix.length) : term;
-}
+function getShorthandName(fullname, prefix) {
+    if (fullname[0] === "@") {
+        let m = new RegExp(`^(@[^/]+)/${prefix}$`).exec(fullname);
```
Comment (platinumazure) [inline lib/util/naming.js]: Could we use a more descriptive variable name here?

**Comment by mysticatea** [comment]
Thank you for the review and I'm sorry for my delay.

I updated this PR.
