### PR TITLE
Fix: `quote-props` should not crash for object rest spread syntax (fixes #3595)

### LINKED ISSUE #3595: `quote-props` crashes when using object rest spread syntax
```bash
$> eslint -v
v1.3.1
```

Having the following `.eslintrc`:

```json
{
  "ecmaFeatures": {
    "experimentalObjectRestSpread": true
  },
  "rules": {
    "quote-props": [2, "consistent"]
  }
}
```

And using object rest spread syntax:

```javascript
var x = {a: 1};
({...x});
```

Results in the following stacktrace when running `eslint`:

```bash
/Code/node_modules/eslint/lib/rules/quote-props.js:130
            if (key.type === "Literal" && typeof key.value === "string") {
                   ^

TypeError: Cannot read property 'type' of undefined
    at /Code/node_modules/eslint/lib/rules/quote-props.js:130:20
    at Array.forEach (native)
    at checkConsistency (/Code/node_modules/eslint/lib/rules/quote-props.js:122:25)
    at EventEmitter.ObjectExpression (/Code/node_modules/eslint/lib/rules/quote-props.js:171:17)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Controller.controller.traverse.enter (/Code/node_modules/eslint/lib/eslint.js:815:25)
    at Controller.__execute (/Code/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Code/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/Code/node_modules/eslint/lib/eslint.js:808:24)
```

### PR DESCRIPTION
**Pull request by joakimbeng**
```bash
$> eslint -v
v1.3.1
```

Having the following `.eslintrc`:

```json
{
  "ecmaFeatures": {
    "experimentalObjectRestSpread": true
  },
  "rules": {
    "quote-props": [2, "consistent"]
  }
}
```

And using object rest spread syntax:

```javascript
var x = {a: 1};
({...x});
```

Results in the following stacktrace when running `eslint`:

```bash
/Code/node_modules/eslint/lib/rules/quote-props.js:130
            if (key.type === "Literal" && typeof key.value === "string") {
                   ^

TypeError: Cannot read property 'type' of undefined
    at /Code/node_modules/eslint/lib/rules/quote-props.js:130:20
    at Array.forEach (native)
    at checkConsistency (/Code/node_modules/eslint/lib/rules/quote-props.js:122:25)
    at EventEmitter.ObjectExpression (/Code/node_modules/eslint/lib/rules/quote-props.js:171:17)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Controller.controller.traverse.enter (/Code/node_modules/eslint/lib/eslint.js:815:25)
    at Controller.__execute (/Code/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Code/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/Code/node_modules/eslint/lib/eslint.js:808:24)
```

Which is what this PR fixes.

### CODE REVIEW

**Comment by BYK** [comment]
Hey there, thanks for the PR! Can you first file an issue first? You can read the contributing guideline here: http://eslint.org/docs/developer-guide/contributing

**Comment by joakimbeng** [comment]
Sorry for missing that, fixed now...

File: lib/rules/quote-props.js [hunk 1]
```diff
@@ -123,7 +123,7 @@ module.exports = function(context) {
             var key = property.key,
                 tokens;
 
-            if (property.method || property.computed || property.shorthand) {
+            if (property.method || property.computed || property.shorthand || property.type === "ExperimentalSpreadProperty") {
```
Comment (BYK) [inline lib/rules/quote-props.js]: How about we simply add `key &&` to the front and cover some other possible scenarios?

Comment (joakimbeng) [inline lib/rules/quote-props.js]: Ha, of course, much better :)

File: lib/rules/quote-props.js [hunk 2]
```diff
@@ -123,7 +123,7 @@ module.exports = function(context) {
             var key = property.key,
                 tokens;
 
-            if (property.method || property.computed || property.shorthand) {
+            if (!key || property.method || property.computed || property.shorthand) {
```
Comment (joakimbeng) [inline lib/rules/quote-props.js]: @BYK there you have it :)

**Comment by gyandeeps** [comment]
LGTM
