### PR TITLE
Fix: no-cond-assign within a function expression (fixes #6908)

### LINKED ISSUE #6908: no-cond-assign analyzes too deep into conditionals
**What version are you using?**

3.2.2

**What did you do?**
```js
const arr = [1, 2, 3];

if (arr.some(val => {
  let b = true;
  if (val === 2) {
    b = false;
  }
  return b;
})) console.log('returned true');
```

**What happened?**

With this eslintrc:

```js
module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "rules": {
      "no-console": 0,
      "no-cond-assign": [2, 'always']
    }
};
```

It signaled:

```sh
Unexpected assignment within an 'if' statement  no-cond-assign
```

**What did you expect to happen?**

It should have ceased to analyze once in the callback of `Array.prototype.some` and should not care at all about any assignments within.  The purpose of the rule is to avoid mistakenly doing an assignment instead of a comparison within a conditional, not to prevent assignments at all.

### PR DESCRIPTION
**Pull request by pmcelhaney**
**What issue does this pull request address?**
#6908 

Stops checking to see if an assignment is within a condition if the assignment is wrapped in a call expression, making the behavior consistent between "except-parens" and "always"

**What changes did you make? (Give an overview)**
I noticed that the behavior depends on whether the configuration is set to "always" or "except-parens". If configured to "except-parens" the behavior was as expected in the bug report. "always" is more strict.

**Is there anything you'd like reviewers to focus on?**
This might be a breaking change. I actually moved one of the unit tests from invalid to valid. But we should probably discuss that in the issue.

### CODE REVIEW

File: tests/lib/rules/no-cond-assign.js [hunk 1]
```diff
@@ -36,7 +36,8 @@ ruleTester.run("no-cond-assign", rule, {
         "while (someNode || (someNode = parentNode)) { }",
         "do { } while (someNode || (someNode = parentNode));",
         "for (;someNode || (someNode = parentNode););",
-        "if ((function(node) { return (node = parentNode); })(someNode)) { }",
+        { code: "if ((function(node) { return (node = parentNode); })(someNode)) { }", options: ["except-parens"] },
+        { code: "if ((function(node) { return (node = parentNode); })(someNode)) { }", options: ["always"] },
```
Comment (pmcelhaney) [inline tests/lib/rules/no-cond-assign.js]: Moved the rule from invalid to valid in the "always" config, and updated the "except-parens" config to be more explicit, so you can see that the code is now considered valid in either case.

File: lib/rules/no-cond-assign.js [hunk 2]
```diff
@@ -59,7 +59,7 @@ module.exports = {
                 if (isConditionalTestExpression(currentAncestor)) {
                     return currentAncestor.parent;
                 }
-            } while ((currentAncestor = currentAncestor.parent));
+            } while ((currentAncestor = currentAncestor.parent) && currentAncestor.type !== "CallExpression");
```
Comment (pmcelhaney) [inline lib/rules/no-cond-assign.js]: If the assignment is inside a function body, bail out. We don't consider that to be assignment inside a conditional. If the function wasn't inline, we wouldn't even be looking at it.

Comment (platinumazure) [inline lib/rules/no-cond-assign.js]: Shouldn't this say "FunctionExpression" instead, in that case? "CallExpression" is for actual function calls.

In the case of `anArray.some(function () { a = 5; })`, the FunctionExpression is just the argument, but the CallExpression is the whole example.

I don't think we should address the CallExpression problem (`doSomething(a = 5)`) in this issue/PR. The original issue/PR was about an assignment happening in a different scope. The scope is introduced by the FunctionExpression, not the CallExpression.

Comment (pmcelhaney) [inline lib/rules/no-cond-assign.js]: Good call. I'll fix it.

File: tests/lib/rules/no-cond-assign.js [hunk 3]
```diff
@@ -36,7 +36,10 @@ ruleTester.run("no-cond-assign", rule, {
...
+        { code: "if ((node => node = parentNode)(someNode)) { }", options: ["except-parens"], parserOptions: { ecmaVersion: 6 } },
+        { code: "if ((node => node = parentNode)(someNode)) { }", options: ["always"], parserOptions: { ecmaVersion: 6 } },
```
Comment (platinumazure) [inline tests/lib/rules/no-cond-assign.js]: I'd love to see a test just for the function expression itself (not immediately invoked). Yes, that's a useless/constant condition, but it'd be good to make sure that case is covered anyway.

**Comment by platinumazure** [comment]
LGTM except for this:

* [ ] I'd love to see a test just for the function expression itself (not immediately invoked). Yes, that's a useless/constant condition, but it'd be good to make sure that case is covered anyway.

**Comment by pmcelhaney** [comment]
Okay, I've added a couple more test cases to cover the function expression without invocation.

File: lib/rules/no-cond-assign.js [hunk 4]
```diff
@@ -59,7 +59,7 @@ module.exports = {
                 if (isConditionalTestExpression(currentAncestor)) {
                     return currentAncestor.parent;
                 }
-            } while ((currentAncestor = currentAncestor.parent));
+            } while ((currentAncestor = currentAncestor.parent) && currentAncestor.type !== "FunctionExpression" && currentAncestor.type !== "ArrowFunctionExpression");
```
Comment (platinumazure) [inline lib/rules/no-cond-assign.js]: Would ast-utils' [`isFunction`](https://github.com/eslint/eslint/blob/master/lib/ast-utils.js#L612) method work here?

**Comment by platinumazure** [comment]
Thanks @pmcelhaney! I've added one more comment.

LGTM, except:
* [ ] Wondering if ast-utils might come in handy when checking that the node type is FunctionExpression or ArrowFunctionExpression? (The function I named also checks FunctionDeclaration, which syntactically can't be in an if statement, but you would need to triple-check that the upward traversal definitely stops at the conditional statement.)

If that's not feasible or desired, then this can be merged (as far as I'm concerned). Thanks!

**Comment by pmcelhaney** [comment]
Added the astUtils function. Good idea. Thanks!

**Comment by platinumazure** [comment]
Oh man, I can't believe I let this sit. Sorry! LGTM.
