### PR TITLE
fix: Better error message for unserializable parser

### LINKED ISSUE #19322: Bug: Cannot serialize key "parse" in parser: Function values are not supported.
### Environment

Description

I’m encountering an issue with ESLint when using the FlatCompat utility and Next.js. The error occurs both during npm run lint and npm run build. It seems related to the serialization of the parse function in the ESLint parser.

Environment Details
	•	Node.js Version: v22.12.0
	•	npm Version: 10.9.0
	•	ESLint Local Version: 9.17.0
	•	ESLint Global Version: 9.17.0
	•	Next.js Version: 15.1.4
	•	Operating System: Mac OS Sequoia

### What parser are you using?

Default (Espree)

### What did you do?

Steps to Reproduce
1.	Install ESLint and Next.js in a project.
2.	Use the following eslint.config.mjs configuration:

```
import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
})

const eslintConfig = [
  ...compat.config({
    extends: ['next'],
    rules: {
      'react/no-unescaped-entities': 'off',
      '@next/next/no-page-custom-font': 'off',
    },
  }),
]

export default eslintConfig
```

3.	Run npm run lint:

```
npm run lint
```
Output:
Cannot serialize key "parse" in parser: Function values are not supported.

4.	Run npm run lint -- --no-cache:
```
npm run lint -- --no-cache
```
This works without errors.

5.	Delete the .next/cache directory and run npm run lint again:

```
rm -rf .next/cache
npm run lint
```
Output:
Cannot serialize key "parse" in parser: Function values are not supported.

6.	Run npm run build:

```
npm run build
```
Output:
Linting and checking validity of types  . ⨯ ESLint: Cannot serialize key "parse" in parser: Function values are not supported.

### What did you expect to happen?

- 	The npm run lint command should work without requiring --no-cache.
- 	The npm run build command should complete without errors.

### What actually happened?

- Running npm run lint without --no-cache results in the error: Cannot serialize key "parse" in parser: Function values are not supported.
- Running npm run build also fails with the same error during the linting phase.

### Link to Minimal Reproducible Example

[Stackblitz Demo](https://stackblitz.com/edit/stackblitz-starters-8rcrwybu?file=demo-app%2Fpackage.json)
Just go to the project and run ```npm run build``` or ```next lint```

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

- 	Clearing the .next/cache directory does not resolve the issue.
- 	Using --no-cache allows npm run lint to pass, but this is not ideal for builds.

### Request for Help

1. Is this issue caused by the FlatCompat utility or an incompatibility between FlatCompat and the Next.js ESLint configuration (next/core-web-vitals)?
2. Is there a workaround or fix for this issue?

Thank you for looking into this! Let me know if additional information or debugging steps are required.

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[x] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Updated the error message that is displayed when a function value can't be serialized. There's a special message when it's a parser vs. any other key.

fixes #19322

### CODE REVIEW

File: messages/config-serialize-function.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
+"use strict";
+
+module.exports = function({ key, objectKey }) {
+
+    // special case for parsers
+    const isParser = objectKey === "parser" && key === "parse";
```
Comment (mdjermanovic) [inline messages/config-serialize-function.js:6]:
```suggestion
    const isParser = objectKey === "parser" && (key === "parse" || key === "parseForESLint");
```

Custom parsers more often provide `parseForESLint()` instead of `parse()`.

File: messages/config-serialize-function.js [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+    const parserMessage = `
+    This typically happens when you're using a custom parser that does not
+provide a "meta" property, which is how ESLint determines the serialized
+representation. Please open an issue with the maintainer of the custom parser
+and share this link:
+
+https://eslint.org/docs/latest/extend/custom-parsers#meta-data-in-custom-parsers
+`.trimStart();
```
Comment (mdjermanovic) [inline messages/config-serialize-function.js:14]:
```suggestion
`.trim();
```

To avoid having two blank lines between this link and "If you still have problems...".

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
