### PR TITLE
Fix: `no-unused-vars` had not been showing correct locations for `/*global`

### LINKED ISSUE #3617: `no-unused-vars` reports global vars on wrong line
Consider:

```js
/*eslint no-unused-vars: 2*/
/*global some_used_var */

var x = 10;
```

This will give the result:

```
  4:1  error  "some_used_var" is defined but never used  no-unused-vars
  4:5  error  "x" is defined but never used              no-unused-vars
```

It's a bit of a quibble, but might it be possible to report the error for some_used_var on line 2 (where it is defined as a global) instead?

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #3617.

### CODE REVIEW

File: lib/eslint.js [hunk 1]
```diff
@@ -46,9 +46,10 @@ estraverse.VisitorKeys.Property.push("argument");
  * Parses a list of "name:boolean_value" or/and "name" options divided by comma or
  * whitespace.
  * @param {string} string The string to parse.
+ * @param {Comment} comment The comment node which has the string.
  * @returns {Object} Result map object of names and boolean values
  */
-function parseBooleanConfig(string) {
+function parseBooleanConfig(string, comment) {
```
Comment (ilyavolodin) [inline lib/eslint.js]: I think we should add unittests to verify that comments are attached to the resulting object.

Comment (mysticatea) [inline lib/eslint.js]: I added.
