### PR TITLE
Fix: ensure configs from a plugin are cached separately (fixes #8792)

### LINKED ISSUE #8792: 4.1 breaks on extending multiple configs from a plugin
**Tell us about your environment**

* **ESLint Version:** 4.1.0
* **Node Version:** 8.0.3
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?**
default and typescript

**Please show your full configuration:**

```
{
  "plugins": [
    "@corbinu/corbinu"
  ],
  "extends": [
    "plugin:@corbinu/corbinu/base",
    "plugin:@corbinu/corbinu/node",
    "plugin:@corbinu/corbinu/lodash",
    "plugin:@corbinu/corbinu/relax"
  ],
  "rules": {
    "node/no-missing-require": "off"
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
I upgraded to 4.1 and began seeing output as if "sourceType" was not set to module.

If I remove all the extends except for "plugin:@corbinu/corbinu/base" then things begin to resolve again or if I paste and merge the configs from each of those then everything reacts normally

Sorry know it makes it more complex to dig into my plugin the source is here: [https://gitlab.com/corbinu/eslint-plugin-corbinu](https://gitlab.com/corbinu/eslint-plugin-corbinu)

It is only a set of configs no rules of my own.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/8792)

**What changes did you make? (Give an overview)**

Config files are cached by file path to avoid needing to load the same config file twice. However, configs provided by plugins all have the same file path (the index file of the plugin). This created a bug when loading multiple configs for the same plugin where only the highest-precedence config from that plugin would be loaded. All other configs from that plugin would be considered identical by the cache, so they would all end up getting pulled from the cache as the same config.

This commit updates the caching logic to use the config full name as a cache index. This is still the file path when resolving a config from the filesystem, but it is the unique plugin config identifier (e.g. 'plugin:foo/node-config') when resolving a plugin config.

**Is there anything you'd like reviewers to focus on?**

Are there any other places where we assume that the `filePath` of a resolved config is unique?

### CODE REVIEW

File: lib/config/config-file.js [hunk 1]
```diff
@@ -524,7 +527,7 @@ function resolve(filePath, relativeTo) {
 function loadFromDisk(resolvedPath, configContext) {
     const dirname = path.dirname(resolvedPath.filePath),
         lookupPath = getLookupPath(dirname);
-    let config = loadConfigFile(resolvedPath);
+    let config = loadConfigFile(resolvedPath, configContext);
```
Comment (smably) [inline lib/config/config-file.js]: `loadConfigFile` doesn't seem to take a second argument. Was this change deliberate?

Comment (not-an-aardvark) [inline lib/config/config-file.js]: Oops, this was unintentional, thanks. While working on this I initially considered adding a second argument to `loadConfigFile`, but then I forgot to remove it here.

**Comment by not-an-aardvark** [comment]
> Sorry to hear about the bugs in this release. I was worried that might happen. Thanks for cleaning up my mess!

No worries -- the codebase probably should have had more tests for this even before you started working on it. 😅

Configs are complicated. It's hard to tell whether a change will break something that's untested, especially if you haven't worked on the code before.

**Comment by smably** [comment]
Yes, very complicated, as I discovered even before these bugs appeared!

File: lib/config/config-cache.js [hunk 2]
```diff
@@ -29,31 +29,31 @@ function hash(vector) {
...
+        this.configFullNameCache = new Map();
         this.localHierarchyCache = new Map();
         this.mergedVectorCache = new Map();
         this.mergedCache = new Map();
     }
 
     /**
      * Gets a config object from the cache for the specified config file path.
-     * @param {string} configFilePath the absolute path to the config file
+     * @param {string} configFullName the absolute path to the config file
```
Comment (platinumazure) [inline lib/config/config-cache.js]: Could this line be updated to match lib/config/config-file.js lines 491-492?

File: lib/config/config-cache.js [hunk 3]
```diff
@@ -29,31 +29,31 @@ function hash(vector) {
...
-    getConfig(configFilePath) {
-        return this.filePathCache.get(configFilePath);
+    getConfig(configFullName) {
+        return this.configFullNameCache.get(configFullName);
     }
 
     /**
      * Sets a config object in the cache for the specified config file path.
-     * @param {string} configFilePath the absolute path to the config file
+     * @param {string} configFullName the absolute path to the config file
```
Comment (platinumazure) [inline lib/config/config-cache.js]: Could this line be updated to match lib/config/config-file.js lines 491-492?

**Comment by not-an-aardvark** [comment]
@platinumazure Updated, good catch.
