### PR TITLE
Fix: env had been rewritten by modules

### LINKED ISSUE #4814: (alpha-2) TypeError: Cannot assign to read only property 'globalReturn' of #<Object>
image

I got an error under the following conditions:

- I'm using v2.0.0-alpha-2
- A test has `env: {node: true}`
- A test has `parserOptions: {sourceType: "module"}`

The cause is [this assign()](https://github.com/eslint/eslint/blob/v2.0.0-alpha-2/lib/eslint.js#L396) and [this assignment](https://github.com/eslint/eslint/blob/v2.0.0-alpha-2/lib/eslint.js#L416)

I will fix the `assign()` with `ConfigOps.merge()`.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29417136-alpha-2-typeerror-cannot-assign-to-read-only-property-globalreturn-of-object?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #4814

### CODE REVIEW

File: tests/lib/eslint.js [hunk 1]
```diff
@@ -3189,6 +3189,32 @@ describe("eslint", function() {
             eslint.verify("var { a='a' } = {};", { parserOptions: { ecmaVersion: 6 }});
         });
 
+        it("should not rewrite env setting in core (https://github.com/eslint/eslint/issues/4814)", function() {
+            eslint.defineRule("test", function() {
+                return {};
+            });
+            eslint.verify("var a = 0;", {
+                env: {node: true},
```
Comment (nzakas) [inline tests/lib/eslint.js]: Why are you calling `verify` twice? I'm unclear on what the actual error is from looking at this test.

Comment (mysticatea) [inline tests/lib/eslint.js]: This test focuses the instance of [`{globalReturn: true}`](https://github.com/eslint/eslint/blob/v2.0.0-alpha-2/conf/environments.js#L26-L28)

The first `verify()` modifies the instance with `{globalReturn: false}` at https://github.com/eslint/eslint/blob/v2.0.0-alpha-2/lib/eslint.js#L416, before this PR.
Then the second `verify()` takes and checks the instance was not modified.

#4814 is doing an additional thing, `RuleTester` freezes the instance.
Then the second `verify()` throws an error at https://github.com/eslint/eslint/blob/v2.0.0-alpha-2/lib/eslint.js#L416 since the instance was frozen.

After this PR, when `verify()` takes environment object, it copies the instance deeply, so the second `verify()` works as expected.

Comment (nzakas) [inline tests/lib/eslint.js]: OK, can you add some comments explaining that?

Comment (mysticatea) [inline tests/lib/eslint.js]: I added it.
