### PR TITLE
Fix: duplicated autofix output for inverted fix ranges (fixes #8116)

### LINKED ISSUE #8116: 3.16.0 regression: padded-blocks autofix can generate incorrect code
**Tell us about your environment**

* **ESLint Version:** 3.16.0
* **Node Version:** 6.9.1
* **npm Version:** 3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```
module.exports = {
  rules: {
    "padded-blocks": ['error', 'never'],
  }
};
```

(This is the value specified by eslint-config-airbnb.)

**What did you do? Please include the actual source code causing the issue.**

I ran `eslint --fix` on this source code:

```js
function f() { // a

  b;
}
```

**What did you expect to happen?**

I expected it to fix the formatting and generate correct code.

**What actually happened? Please include the actual, raw output from ESLint.**

eslint generated this output:
```
➜  eslint_test_3 git:(master) ./node_modules/.bin/eslint --fix test.js

/Users/alanpierce/code/eslint_test_3/test.js
  6:1  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)
```

And the JS file was changed to have these contents:
```
function f() {
function f() { // a

  b;
}
```

This is a syntax error, so the file fails to parse after this change.

When I try this on eslint 3.15.0, it doesn't have any problems.

This is breaking the [coffeelint example build](https://github.com/decaffeinate/decaffeinate#status) for the decaffeinate project. The [lexical_linter.js](https://github.com/decaffeinate-examples/coffeelint/blob/decaffeinate/src/lexical_linter.js) file has two `static initClass` lines near the start, which causes a syntax error. (The example builds are a bit like eslint-canary for the decaffeinate project, and one of the conversion steps is to run `eslint --fix` on the resulting JS code.)

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/8116)

**What changes did you make? (Give an overview)**

The padded-blocks rule sometimes produces a fix range where the start index of the range is larger than the end index. Due to the changes in fcc38db469d987e97b668675bf7822c7c0, when source-code-fixer encountered such a range, it would output the text between the end index and the start index twice. This commit ensures that source-code-fixer behaves the same way as it previously did when it encounters an inverted fix range (it should act as if the start and end indices were equal). In the future, we should also update padded-blocks to avoid producing inverted fix ranges.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

**Comment by alangpierce** [comment]
Thanks! I just re-ran my failing test suite with this patch applied to eslint and the test suite passes now.

File: tests/lib/rules/padded-blocks.js [hunk 1]
```diff
@@ -463,6 +463,12 @@ ruleTester.run("padded-blocks", rule, {
                     line: 9
                 }
             ]
+        },
+        {
+            code: "function foo() { // a\n\n  b;\n}",
+            output: "function foo() {\n // a\n\n  b;\n}",
```
Comment (alberto) [inline tests/lib/rules/padded-blocks.js]: This isn't doing the right thing. Was this the previous behaviour?

File: lib/util/source-code-fixer.js [hunk 2]
```diff
@@ -108,7 +108,13 @@ SourceCodeFixer.applyFixes = function(sourceCode, messages) {
...
             output += text.slice(Math.max(0, lastPos), Math.max(0, start));
             output += fix.text;
-            lastPos = end;
+
+            /*
+             * If the start of the range is larger than the end for some reason, make sure
+             * the text between the end and the start doesn't get duplicated.
+             * https://github.com/eslint/eslint/issues/8116
+             */
+            lastPos = Math.max(start, end);
```
Comment (alberto) [inline lib/util/source-code-fixer.js]: A negative range looks like a problem with the fixer to me. Shouldn't we skip them instead?

Comment (mysticatea) [inline lib/util/source-code-fixer.js]: Ah, it's nice as well.

File: tests/lib/rules/padded-blocks.js (hunk 1 above)
Comment (not-an-aardvark) [inline tests/lib/rules/padded-blocks.js]: Yes.

File: lib/util/source-code-fixer.js (hunk 2 above)
Comment (not-an-aardvark) [inline lib/util/source-code-fixer.js]: We could do that, but it might be a breaking change. Given that one of the core rules had a negative range, it seems likely that there are custom rules that use a negative range as well. The goal of this PR just is to fix the regression by restoring the previous behavior.
