### PR TITLE
Fix: Check for concatenation in no-throw-literal (fixes #3099)

### LINKED ISSUE #3099: `no-throw-literal` does not catch concatenated exception messages
Using eslint `master`, and the following code:

```
throw 'a' + 'b'
```

and the following rule:

```
"no-throw-literal": 2
```

I expect an error, but get none.

### PR DESCRIPTION
**Pull request by IanVS**
Previously the rule only checked for a single literal.

This change will now check for string concatenation (or other BinaryExpression)

A current limitation of this rule is that it cannot handle literal template strings.

### CODE REVIEW

**Comment by IanVS** [comment]
I didn't realize that force pushing to a branch with a closed PR would require me to create a new PR.

File: lib/rules/no-throw-literal.js [hunk 1]
```diff
@@ -1,12 +1,32 @@
...
+ * @param  {ASTNode}  node  ASTNode to check for only literals
+ * @returns {Boolean}       True if considered literal, false otherwise
+ */
+function isLiteral(node) {
+    if (node.type === "Literal") {
+        return true;
+    }
+
+    if (node.type === "BinaryExpression") {
+        return true;
```
Comment (nzakas) [inline lib/rules/no-throw-literal.js]: This will also flag `throw a + b`. Is that intended?

Comment (ilyavolodin) [inline lib/rules/no-throw-literal.js]: `throw a+b` will not be able to produce a valid Error object.

Comment (IanVS) [inline lib/rules/no-throw-literal.js]: Yes, I tested and even if `a` and `b` are error objects, they are recast to strings during concatenation.  So, yes, intended.

Comment (ilyavolodin) [inline lib/rules/no-throw-literal.js]: Problem is, now the name of the rule doesn't align with the function.

Comment (IanVS) [inline lib/rules/no-throw-literal.js]: I agree, but I would say it's closer to the original intent behind the rule, at least according to it's docs:

> It is considered good practice to only `throw` the `Error` object itself or an object using the `Error` object as base objects for user-defined exceptions. The fundamental benefit of `Error` objects is that they automatically keep track of where they were built and originated. This rule restrict what can be thrown as an exception by preventing to throw literals.

Would it be better to create a new rule with a better name?  Since 1.0 is not final, could the rule even be replaced (although that's not much warning)?

Comment (nzakas) [inline lib/rules/no-throw-literal.js]: This is where we start to fall down the rabbit hole. Every rule has gaps in coverage because we can't possibly account for every possibility through static analysis. With this, we are starting to cross the line over static analysis into runtime interpretation, which starts to get dangerous because that's when people start asking questions like, "how come it doesn't flag throw foo() because foo() returns a string?"

The original intent of the rule was to flag `throw "foo"`, we expanded to other literals because it was cheap. I'm on the fence as to whether checking for binary expressions makes sense here because, as Ilya stated, that's not what the rule's name implies.

As for changing the name, it's too late to do that now. Even though 1.0.0 isn't final, I don't want to start changing rule names at this stage.

I think the fundamental question here is if flagging binary expressions in this situation makes sense? If yes, then we can answer whether it belongs in this rule or not.

Comment (IanVS) [inline lib/rules/no-throw-literal.js]: The reason this came up was that someone had the following type of code which was not being caught:

```
if (counter !== 1) { throw 'some assertion failed to exec. counter = ' + counter } 
```

Am I wrong in thinking that **all** BinayExpressions will become a literal when executed?  If that is true, we can say the rule is to prevent throwing a literal *or things which are always guaranteed to be a literal*.  I think that still fits the name and is within the realm of static analysis (as long as they are true guarantees, and not depending on runtime interpretation).

Comment (nzakas) [inline lib/rules/no-throw-literal.js]: A literal is a syntactic term meaning "not an identifier". All binary expressions return *primitive values*.

Comment (mysticatea) [inline lib/rules/no-throw-literal.js]: "literal" is such as `true`, `0`, `100`, `"text"`, `null`, `{foo: 1}`, `[1, 2, 3]`, `function() {}`, ...
In short, it's the notation for a static constant value.

So, actually this rule name was wrong, but I believe people can guess the purpose of this rule from this name.  I guessed "I should throw an `Error` object".

I thought what my best effort is below.  I'm sure I cannot detect all patterns, but when that function returned `true`, the result of the expression should be not an error object.  (I did not run the code)

```js
function isNotErrorObject(node) {
    switch (node.type) {
        case "Identifier":
        case "CallExpression":
        case "NewExpression":
        case "MemberExpression":
        case "TaggedTemplateExpression":
        case "YieldExpression":
            return false; // possibly an error object.

        case "AssignmentExpression":
            return isNotErrorObject(node.right);

        case "SequenceExpression":
            var exprs = node.expressions;
            return exprs.length === 0 || isNotErrorObject(exprs[exprs.length - 1]);

        case "LogicalExpression"
            return isNotErrorObject(node.left) || isNotErrorObject(node.right);

        case "ConditionalExpression"
            return isNotErrorObject(node.consequent) || isNotErrorObject(node.alternate);

        default:
            return true;
    }
}
```

Comment (IanVS) [inline lib/rules/no-throw-literal.js]: @nzakas what direction would you like to go here?  What @mysticatea proposes is very thorough, perhaps it deserves its own issue/discussion?

Comment (nzakas) [inline lib/rules/no-throw-literal.js]: He mentioned it on the issue as well. Okay, let's go with his approach...I'll deal with my pedantry regarding the rule name in private. :)

I would suggest, though, that the function be named `isErrorObject()`...the "not" confused me.

Comment (IanVS) [inline lib/rules/no-throw-literal.js]: I'm finishing this up now.  @mysticatea in what case would a `SequenceExpression` have zero expressions?  Before this I didn't even know a SequenceExpression was a thing, so I have pretty much no familiarity with their intricacies.  This is all very enlightening for me.

Comment (mysticatea) [inline lib/rules/no-throw-literal.js]: The case does not exist, as far as I know :)
But ESTree spec does not have restrictions about array-length, so just to be foolproof, I wrote checking.

**Comment by IanVS** [comment]
OK, I have taken the advice of @mysticatea, and I believe this is ready for review.

File: lib/rules/no-throw-literal.js [hunk 2]
```diff
@@ -1,12 +1,50 @@
...
 "use strict";
 
 //------------------------------------------------------------------------------
+// Helpers
+//------------------------------------------------------------------------------
+
+/**
+ * Determine if a node has a possiblity to be an Error object
+ * @param  {ASTNode}  node  ASTNode to check
+ * @returns {Boolean}       True if there is a chance it contains an Error obj
```
Comment (nzakas) [inline lib/rules/no-throw-literal.js]: Lowercase: boolean

File: tests/lib/rules/no-throw-literal.js [hunk 3]
```diff
@@ -23,37 +23,48 @@ eslintTester.addRuleTest("lib/rules/no-throw-literal", {
...
+        "throw foo ? 'literal' : new Error();", // ConditionalExpression (alternate)
+        { code: "throw tag `${foo}`;", ecmaFeatures: {templateStrings: true} }, // TaggedTemplateExpression
+        { code: "function* foo() { var index = 0; throw yield index++; }", ecmaFeatures: {generators: true} } // YieldExpression
     ],
     invalid: [
         {
             code: "throw 'error';",
             errors: [{
-                message: "Do not throw a literal.",
+                message: "Did not throw an Error object.",
```
Comment (nzakas) [inline tests/lib/rules/no-throw-literal.js]: I think this message is a bit too mysterious. It really doesn't matter if you throw an `Error` object or another object, we just don't want them throwing a literal or primitive. Something like, "Expected an object to be thrown" may be clearer.

File: lib/rules/no-throw-literal.js (hunk 2 above)
Comment (IanVS) [inline lib/rules/no-throw-literal.js]: Thanks.  What is the guideline on capital/lowercase for these?  I tend to look for other examples to copy and invariably it turns out to be wrong.  

Besides, since `Boolean` is named after George Boole, it seemed to make sense that it was capitalized. :-P

Comment (nzakas) [inline lib/rules/no-throw-literal.js]: In JavaScript, `Boolean` is an object while `boolean` is a primitive. The uppercase letter indicates the difference (same for string and number).

Comment (mysticatea) [inline lib/rules/no-throw-literal.js]: I remembered that just now. #3056

File: lib/rules/no-throw-literal.js [hunk 4]
```diff
@@ -1,12 +1,50 @@
...
+
+        case "SequenceExpression":
+            var exprs = node.expressions;
+            return exprs.length !== 0 && couldBeError(exprs[exprs.length - 1]);
+
+        case "LogicalExpression":
+            return couldBeError(node.left) || couldBeError(node.right);
+
+        case "ConditionalExpression":
+            return couldBeError(node.consequent) || couldBeError(node.alternate);
```
Comment (mysticatea) [inline lib/rules/no-throw-literal.js]: I think `&&` should be used (`LogicalExpression` also).
If one of operand is a literal, it can throw a literal.

Comment (IanVS) [inline lib/rules/no-throw-literal.js]: Yes, but it's also possible to throw an Object, and since this rule is on a best-effort basis as it is, I think it would be best to avoid possible false positives.  I've named the function `couldBeError` (maybe it's better to call it `couldBeObject` based on earlier comments from @nzakas), which I think fits with the logic that is currently being used.

**Comment by nzakas** [comment]
Let's go with this for now. We can always tweak as necessary later.

File: lib/rules/no-throw-literal.js (hunk 4 above)
Comment (michaelficarra) [inline lib/rules/no-throw-literal.js]: But that's not what this rule is looking for. We don't care that it's possible that they *may not* hit the error case, we care that it's possible that they *may* hit the error case.
