### PR TITLE
Fix: no-multi-spaces conflicts with smart tabs (fixes #2077)

### LINKED ISSUE #2077: `no-multi-spaces` conflicts with `smart-tabs`
If I have `"no-mixed-spaces-and-tabs":[2, "smart-tabs"]`, then `no-multi-spaces` should not throw an error/warning for lines that use smart-tabs.

test case, try with the following code:
```
/*eslint no-mixed-spaces-and-tabs:[2, "smart-tabs"], no-multi-spaces:2 */
var i=10,
    j=20;
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9628407-no-multi-spaces-conflicts-with-smart-tabs?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by afahim**
I've added `\t` to the list of negated characters to the regular expression that determines whether the multiple spaces that are being detected should be reported or not.

Thus, in case smart tabs are being used like in the following case, the rule won't throw an error anymore.

```javascript
\t\t var one = 1,
\t\t\s\s two = 2;
```

The only shortcoming of this fix that I can see is when a tab is used within an expression, and directly after the tab, multiple spaces have been added. In that case, the rule won't be able to report an error. For instance:

```javascript
var a =\t\s\s1;
```

However, seeing as that using tabs inline is not a practice anyways, I don't think that's an issue. Do let me know if you think otherwise!

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks! It might be better to check that the tabs are found at the beginning of a line, rather than adding `\t` to the negated characters. That way, you will still catch that last example you cite.

**Comment by afahim** [comment]
@nzakas I've made it such that all whitespace before the first character of the line is ignored. I've also added a test to show that case now works.

**Comment by afahim** [comment]
Upon second thought, we can just use `\s` instead of trying to maintain a whitespace negated character set. Let me know if you think that's a bad idea.

File: lib/rules/no-multi-spaces.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ module.exports = function(context) {
 
             var source = context.getSource(),
                 allComments = context.getAllComments(),
-                pattern = /[^\n\r\u2028\u2029 ] {2,}/g,  // note: repeating space
+                pattern = /[^\s].? {2,}/g,  // note: repeating space
```
Comment (nzakas) [inline lib/rules/no-multi-spaces.js]: Not all whitespace is the same. There are four valid JS line breaks (seen in previous version of this file). It's best to keep those explicit and then do a space or tab.

Comment (afahim) [inline lib/rules/no-multi-spaces.js]: I've updated it to ignore the list of whitespace and tabs before the first character. Since JS regex doesn't support negative lookbehinds, the other alternative would be to trim leading tabs and then do the pattern matching, but that approach sounds superfluous to me.

**Comment by nzakas** [comment]
Lgtm
