### PR TITLE
fix: allow `RuleTester` to test files inside `node_modules/`

### LINKED ISSUE #19471: Bug: Can't test cases that filename contains `node_modules/`
### Environment

Node version: v22.14.0
npm version: v9.1.2
Local ESLint version: v9.21.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19045

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

N/A
</details>

```js
import {RuleTester} from 'eslint'

new RuleTester().run('foo', {create:() =>({})}, {
  valid: [
    {
      code: 'foo',
      filename: 'node_modules/foo.js'
    }
  ],
  invalid:[]
})
```

### What did you expect to happen?

Should pass without error

### What actually happened?

Error thrown.

```
AssertionError [ERR_ASSERTION]: Should have no errors but had 1: [
  {
    ruleId: null,
    severity: 1,
    message: 'No matching configuration found for node_modules/foo.js.',
    line: 0,
    column: 0,
    nodeType: null
  }
]

1 !== 0

    at testValidTemplate (<CWD>\node_modules\eslint\lib\rule-tester\rule-tester.js:925:20)
    at RuleTester.<anonymous> (<CWD>\node_modules\eslint\lib\rule-tester\rule-tester.js:1274:37)
    at RuleTester.itDefaultHandler (<CWD>\node_modules\eslint\lib\rule-tester\rule-tester.js:385:23)
    at <CWD>\node_modules\eslint\lib\rule-tester\rule-tester.js:1269:71
    at Array.forEach (<anonymous>)
    at RuleTester.<anonymous> (<CWD>\node_modules\eslint\lib\rule-tester\rule-tester.js:1268:32)
    at RuleTester.describeDefaultHandler (<CWD>\node_modules\eslint\lib\rule-tester\rule-tester.js:402:19)
    at RuleTester.<anonymous> (<CWD>\node_modules\eslint\lib\rule-tester\rule-tester.js:1267:34)
    at RuleTester.describeDefaultHandler (<CWD>\node_modules\eslint\lib\rule-tester\rule-tester.js:402:19)
    at RuleTester.run (<CWD>\node_modules\eslint\lib\rule-tester\rule-tester.js:1265:26) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 1,
  expected: 0,
  operator: 'strictEqual'
}
```

### Link to Minimal Reproducible Example

I can setup if required

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

I think it's something left over from https://github.com/eslint/eslint/issues/17962

What I can't understand is why RuleTest still trying to resolve config...

### PR DESCRIPTION
**Pull request by fisker**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Stop applying default ignores to RuleTester.
Fixes #19471

#### Is there anything you'd like reviewers to focus on?

No

### CODE REVIEW

File: tests/lib/rule-tester/rule-tester.js [hunk 1]
```diff
@@ -2211,24 +2211,31 @@ describe("RuleTester", () => {
         }, /Fixable rules must set the `meta\.fixable` property/u);
     });
 
-    // https://github.com/eslint/eslint/issues/17962
-    it("should not throw an error in case of absolute paths", () => {
+    it("should allow test any file", () => {
```
Comment (mdjermanovic) [inline tests/lib/rule-tester/rule-tester.js:2214]:
```suggestion
    it("should allow testing of any file", () => {
```

File: tests/lib/rule-tester/rule-tester.js [hunk 2]
```diff
@@ -2211,24 +2211,31 @@ describe("RuleTester", () => {
...
+        const filenames = [
+
+            // Ignored by default
```
Comment (mdjermanovic) [inline tests/lib/rule-tester/rule-tester.js:2217]:
```suggestion
            /*
             * Ignored by default
             * https://github.com/eslint/eslint/issues/19471
             */
```

**Review by nzakas — APPROVED** [review]
LGTM. Thanks.
