### PR TITLE
Fix: Indent Ignore Variable Declaration init operator (fixes #8546)

### LINKED ISSUE #8546: Indent should ignore indentation of variable assigment in multiline variable declaration
**Tell us about your environment**
* **ESLint Version:**
master
* **Node Version:**
6.10
* **npm Version:**
3.10

**What parser (default, Babel-ESLint, etc.) are you using?**
typescript
**Please show your full configuration:**

```js
module.exports = {
//    "extends": ["eslint:all"],
    "parser": "typescript-eslint-parser",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "indent": "error"
    }
};
```

**What did you do? Please include the actual source code causing the issue.**

Invalid
```js
const fooLongName
        = 1,
    barLongName
        = 2,
    bazLongName
        = 3;
```

**What did you expect to happen?**

I expected this to be a valid indentation style. The indent-legacy rule allows for this style. Also if equal operators are on the previous line it is considered a valid indentation.

Valid
```js
const fooLongName =
        1,
    barLongName =
        2,
    bazLongName =
        3;
```

**What actually happened? Please include the actual, raw output from ESLint.**
It is expected to be indented like so:

```js
const fooLongName
    = 1,
    barLongName
    = 2,
    bazLongName
    = 3;
```

```
/mnt/c/Users/reyad.attiyat/Workspace/eslint-test/test-var-indent.ts
  2:1  error  Expected indentation of 4 spaces but found 8  indent
  4:1  error  Expected indentation of 4 spaces but found 8  indent
  6:1  error  Expected indentation of 4 spaces but found 8  indent
```

I can a create a PR to fix this. Just want to confirm this is not intended behavior. When the equal operator is on the line with the variable identifier the assignment indentation is ignored completely. We should probably do the same when the equal operator is on the same line as the assignment.

I have tested the changes made in https://github.com/eslint/eslint/pull/8498 and it does not fix this case.

### PR DESCRIPTION
**Pull request by soda0289**
**What is the purpose of this pull request? (put an "X" next to item)**

[X ] Bug fix (fixes #8546 )

**What changes did you make? (Give an overview)**
Allow the VariableDeclarator node listener to ignore the operator as well as the initial value.

**Is there anything you'd like reviewers to focus on?**
I tried to match the behavior of variable assignment but might have missed something. The following are now all valid:
```js
const aLongName 
    = 1,
  bLongName
    = 2;
```
```js
const aLongName 
    =
  1,
  bLongName
     =
     2;
```

### CODE REVIEW

File: lib/rules/indent.js [hunk 1]
```diff
@@ -1011,6 +1011,11 @@ module.exports = {
 
             VariableDeclarator(node) {
                 if (node.init) {
+                    const operator = sourceCode.getTokenBefore(node.init);
```
Comment (not-an-aardvark) [inline lib/rules/indent.js]: I think this will work incorrectly if `node.init` is parenthesized. Using `sourceCode.getTokenBefore(node.init, astUtils.isNotOpeningParenToken)` should resolve that.

File: lib/rules/indent.js [hunk 2]
```diff
@@ -1011,6 +1011,11 @@ module.exports = {
...
+
+                    if (operator.type === "Punctuator" && operator.value === "=" && tokenInfo.isFirstTokenOfLine(operator)) {
```
Comment (not-an-aardvark) [inline lib/rules/indent.js]: Why is it necessary to check that the operator is an equals sign?

File: lib/rules/indent.js [hunk 3]
```diff
@@ -1011,6 +1011,11 @@ module.exports = {
...
+                        offsets.ignoreToken(operator);
```
Comment (not-an-aardvark) [inline lib/rules/indent.js]: `offsets.ignoreToken` is a no-op if a token is not the first token of its line, so it's not necessary to check for that in the `if` statement.

**Comment by soda0289** [comment]
@not-an-aardvark Thanks for the review. I can't reply to your comments, some JS isn't loading, but I made the following changes:

- I used `astUtils.isNotOpeningParenToken()` to ensure the previous token is not a parenthese. Also added a test for this case
- Removed the check to ensure it was an equal operator. I think I was concerned it could be a comma or some other token but cannot think of an example
- Removed the first token of line since it is not needed

File: lib/rules/indent.js [hunk 4]
```diff
@@ -1039,6 +1039,11 @@ module.exports = {
 
             VariableDeclarator(node) {
                 if (node.init) {
+                    const equalOperator = sourceCode.getTokenBefore(node.init, astUtils.isNotOpeningParenToken);
+
+                    if (equalOperator) {
```
Comment (not-an-aardvark) [inline lib/rules/indent.js]: Will this condition ever be false?

Comment (soda0289) [inline lib/rules/indent.js]: I thought that since getTokenBefore() can return null, and ignoreToken() cannot handle null values, I should have a check. In this case it should always return the equal operator.

I will remove the if statement to clean this up.

Comment (not-an-aardvark) [inline lib/rules/indent.js]: I suppose that makes sense, but if that happens, then some invariant has been violated and it's likely that the rule will do the wrong thing anyway. So I think it's better to avoid unnecessary checks unless we know that they're necessary in a particular case.

**Comment by soda0289** [comment]
Removed the if statement complete. Thanks.
