### PR TITLE
Fix: camelcase rule fix for import declarations (fixes #6755)

### LINKED ISSUE #6755: camelcase lint error on module import when deconstructing
**ESLint version:** 

3.1.1
___
**Rule:** 

`"camelcase": [2, { "properties": "never" }]` 
___
**Problem**

Lint fails on module import when deconstructing  properties and aliasing.

``` javascript
// this cause lint error
import { no_camel_case_prop as CamelCaseProp } from 'external-module';
```

But with 186e8f0a555701f02ba0207e8e71b3d941de665a that rule should ignore camelcase during deconstructing.

_(I know that import deconstructing is not a real object deconstructing, but probably it should follow the same rule)_

For now I have to workaround this issue this way:

``` javascript
// this not cause lint error
import * as externalModule from 'external-module';
externalModule.no_camel_case_prop
```
___
Thank you :)

### PR DESCRIPTION
**Pull request by lordgiotto**
Fixes #6755 

Calmecase rule now doesn't report an error if camelcased identifier is imported with a camecased alias. Otherwhise it reports an error as expected.

### CODE REVIEW

File: tests/lib/rules/camelcase.js [hunk 1]
```diff
@@ -207,6 +215,76 @@ ruleTester.run("camelcase", rule, {
...
+        },
+        {
+            code: "import no_camelcased, { another_no_camelcased as camelCased } from \"external-module\";",
+            parserOptions: { ecmaVersion: 6, sourceType: "module" },
+            errors: [
+                {
+                    message: "Identifier 'no_camelcased' is not in camel case.",
+                    type: "Identifier"
+                }
+            ]
```
Comment (vitorbal) [inline tests/lib/rules/camelcase.js]: Could you add a test for `import { no_camelcased as no_camel_cased } from \"external module\";` as well?

Comment (lordgiotto) [inline tests/lib/rules/camelcase.js]: It reports two errors in that case, both for the local and the imported identifier. It's a desired behavior in your opinion, or I should fix the code to handle it?

Comment (lordgiotto) [inline tests/lib/rules/camelcase.js]: Ok, I added that test and slightly changed the rule check to not report the error twice: now it only checks local identifier (that is the one we care about) and never the imported one.

**Comment by nzakas** [comment]
LGTM, just waiting another day to let others review.

File: tests/lib/rules/camelcase.js [hunk 2]
```diff
@@ -65,6 +65,14 @@ ruleTester.run("camelcase", rule, {
...
             parserOptions: { ecmaVersion: 6 },
             options: [{properties: "never"}]
+        },
+        {
+            code: "import { no_camelcased as camelCased } from \"external-module\";",
+            parserOptions: { ecmaVersion: 6, sourceType: "module" }
+        },
+        {
+            code: "import { no_camelcased as camelCased, anoterCamelCased } from \"external-module\";",
+            parserOptions: { ecmaVersion: 6, sourceType: "module" }
```
Comment (vitorbal) [inline tests/lib/rules/camelcase.js]: Sorry for not asking this before, could you also add a test for `import { camelCased } from \"external module\";` as well, just in case?

File: tests/lib/rules/camelcase.js [hunk 3]
```diff
@@ -207,6 +215,86 @@ ruleTester.run("camelcase", rule, {
...
+        },
+        {
+            code: "import no_camelcased, { another_no_camelcased as camelCased } from \"external-module\";",
+            parserOptions: { ecmaVersion: 6, sourceType: "module" },
+            errors: [
+                {
+                    message: "Identifier 'no_camelcased' is not in camel case.",
+                    type: "Identifier"
+                }
+            ]
```
Comment (vitorbal) [inline tests/lib/rules/camelcase.js]: Again, my apologies for not asking this before.
Could you also add a test for `import { camelCased as no_camel_cased } from \"external module\";`, just in case? That should re-enforce your latest change of only checking the local import and never the imported one.

File: tests/lib/rules/camelcase.js (hunk 1 above)
Comment (lordgiotto) [inline tests/lib/rules/camelcase.js]: @vitorbal Added both the tests you suggested :)

Comment (vitorbal) [inline tests/lib/rules/camelcase.js]: thanks, looking great!

**Comment by vitorbal** [comment]
Lgtm

**Comment by kaicataldo** [comment]
Thanks for contributing, @lordgiotto! Code changes looks great. Can you add a description of this behavior to the docs for the rule?

**Comment by lordgiotto** [comment]
@kaicataldo Docs updated! Please, let me know if what I wrote is acceptable: since english is not my mother thong, even it's good enough to communicate, it could be not good enough to write official documentation :P

File: docs/rules/camelcase.md [hunk 4]
```diff
@@ -4,7 +4,7 @@ When it comes to naming variables, style guides generally fall into one of two c
 
 ## Rule Details
 
-This rule looks for any underscores (`_`) located within the source code. It ignores leading and trailing underscores and only checks those in the middle of a variable name. If ESLint decides that the variable is a constant (all uppercase), then no warning will be thrown. Otherwise, a warning will be thrown. This rule only flags definitions and assignments but not function calls.
+This rule looks for any underscores (`_`) located within the source code. It ignores leading and trailing underscores and only checks those in the middle of a variable name. If ESLint decides that the variable is a constant (all uppercase), then no warning will be thrown. Otherwise, a warning will be thrown. This rule only flags definitions and assignments but not function calls. In case of es6 `import` statements, this rule only targets the name of the variable that will be imported into the local module scope.
```
Comment (kaicataldo) [inline docs/rules/camelcase.md]: This looks great to me! Could we make it `ES6` instead of `es6` for consistency with our documentation?

**Comment by kaicataldo** [comment]
@lordgiotto Your English is great. One tiny, tiny nitpick, but otherwise the docs look really good to me. Thanks!

File: docs/rules/camelcase.md (hunk 4 above)
Comment (lordgiotto) [inline docs/rules/camelcase.md]: Fixed, thank you :)

**Comment by kaicataldo** [comment]
Looks like the tests are failing, but doesn't seem like it's because of anything in this PR: 

```
Validating licenses
undefined license for circular-json@0.3.0 is impermissible.
npm ERR! Test failed.  See above for more details.
```

**Comment by gyandeeps** [comment]
huh, I didn't know that we check for license on indirect dependencies also. I always thought we only checked for direct dependencies.

**Comment by lordgiotto** [comment]
Very strange, this is my output of `npm test`, no licenses errors.
[eslint-test.txt](https://github.com/eslint/eslint/files/394132/eslint-test.txt)

**Comment by nzakas** [comment]
Hmm, can someone track down where that dependency is building pulled in?

Also, note for whomever ends up merging: The commit message should begin with "Update:" since it adds new default functionality.

**Comment by lordgiotto** [comment]
@nzakas ok, i'll change commit message, I misunderstood the guide and used 'fix' since it was referred to an issue marked as bug, sorry.

**Comment by lordgiotto** [comment]
@kaicataldo I pushed a new commit with the correct message and this time it passed all the test. Weird :)

**Comment by platinumazure** [comment]
@lordgiotto We managed to get a PR into the upstream project that was causing the test failures, and now everything is fixed. :smile: Thanks for your patience!

**Comment by vitorbal** [comment]
@lordgiotto thanks a lot for your contribution! We really appreciate it 🎉

**Comment by lordgiotto** [comment]
Thank you @vitorbal and all the reviewers, it was a pleasure :)
