### PR TITLE
Update: Fixes multiline no-warning-comments rule. (fixes #9884)

### LINKED ISSUE #9884: no-warning-comments does not work with multiline comments
I'm going to report using the online demo rather than my own project, so that anyone else can reproduce this bug as well. It happens in the online demo. https://eslint.org/demo

[Direct link to the demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyoqXG4gKiB0b2RvXG4gKi9cblxuLypcbiAqIHRvZG9cbiAqL1xuXG4vLyB0b2RvXG5cbnZhciBmb28gPSBiYXI7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc29sZSI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lbXB0eSI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Miwibm8td2FybmluZy1jb21tZW50cyI6Mn0sImVudiI6e319fQ==)

* **ESLint Version:** 4.16.0
* **Node Version:** N/A
* **npm Version:** N/A

**What parser (default, Babel-ESLint, etc.) are you using?**
Default (unless the online demo uses something else?)

**Please show your full configuration:**
I checked `no-warning-comments` in the demo and downloaded the JSON file.
<details>
<summary>Configuration</summary>

```json
{
    "parserOptions": {
        "ecmaVersion": 5,
        "sourceType": "script",
        "ecmaFeatures": {}
    },
    "rules": {
        "constructor-super": 2,
        "no-case-declarations": 2,
        "no-class-assign": 2,
        "no-compare-neg-zero": 2,
        "no-cond-assign": 2,
        "no-console": 2,
        "no-const-assign": 2,
        "no-constant-condition": 2,
        "no-control-regex": 2,
        "no-debugger": 2,
        "no-delete-var": 2,
        "no-dupe-args": 2,
        "no-dupe-class-members": 2,
        "no-dupe-keys": 2,
        "no-duplicate-case": 2,
        "no-empty-character-class": 2,
        "no-empty-pattern": 2,
        "no-empty": 2,
        "no-ex-assign": 2,
        "no-extra-boolean-cast": 2,
        "no-extra-semi": 2,
        "no-fallthrough": 2,
        "no-func-assign": 2,
        "no-global-assign": 2,
        "no-inner-declarations": 2,
        "no-invalid-regexp": 2,
        "no-irregular-whitespace": 2,
        "no-mixed-spaces-and-tabs": 2,
        "no-new-symbol": 2,
        "no-obj-calls": 2,
        "no-octal": 2,
        "no-redeclare": 2,
        "no-regex-spaces": 2,
        "no-self-assign": 2,
        "no-sparse-arrays": 2,
        "no-this-before-super": 2,
        "no-undef": 2,
        "no-unexpected-multiline": 2,
        "no-unreachable": 2,
        "no-unsafe-finally": 2,
        "no-unsafe-negation": 2,
        "no-unused-labels": 2,
        "no-unused-vars": 2,
        "no-useless-escape": 2,
        "require-yield": 2,
        "use-isnan": 2,
        "valid-typeof": 2,
        "no-warning-comments": 2
    },
    "env": {}
}
```
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/**
 * todo
 */

/*
 * todo
 */

// todo

var foo = bar;
```

Run it in the [online demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyoqXG4gKiB0b2RvXG4gKi9cblxuLypcbiAqIHRvZG9cbiAqL1xuXG4vLyB0b2RvXG5cbnZhciBmb28gPSBiYXI7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc29sZSI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lbXB0eSI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Miwibm8td2FybmluZy1jb21tZW50cyI6Mn0sImVudiI6e319fQ==).

**What did you expect to happen?**
The sections
```
/*
 * todo
 */
```
and
```
/**
 * todo
 */
```
should be flagged for `no-warning-comments`.

**What actually happened? Please include the actual, raw output from ESLint.**
Only
```
// todo
```
is flagged for `no-warning-comments`.

### PR DESCRIPTION
**Pull request by sstern6**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Updated the RegExp to look for the term provided in the body of the comment, not just the beginning. 

**Is there anything you'd like reviewers to focus on?**
Please review new test cases add/moved from valid to invalid.  The examples on the documentation were not throwing errors https://eslint.org/docs/2.0.0/rules/no-warning-comments as stated, ie:

[Previous to the PR was not throwing any errors](https://eslint.org/demo/#eyJ0ZXh0IjoiLypcbipVbmV4cGVjdGVkICdhbnkgb3RoZXIgdGVybScgY29tbWVudC5cbiAqIFRoZSBzYW1lIGdvZXMgZm9yIHRoaXMgVE9ETyBjb21tZW50XG4gKiBPciBhIGZpeG1lXG4gKiBhcyB3ZWxsIGFzIGFueSBvdGhlciB0ZXJtXG4qL1xuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc29sZSI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lbXB0eSI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Miwibm8td2FybmluZy1jb21tZW50cyI6Mn0sImVudiI6e319fQ==).
```
/*
*Unexpected 'any other term' comment.
 * The same goes for this TODO comment
 * Or a fixme
 * as well as any other term
*/
``` 

Only had 1 error not 2 errors:

```
// todo and fixme
```

Thank you

Fixes: https://github.com/eslint/eslint/issues/9884

### CODE REVIEW

File: lib/rules/no-warning-comments.js [hunk 1]
```diff
@@ -79,12 +81,12 @@ module.exports = {
...
                 prefix = "^\\s*";
             } else if (/^\w/.test(term)) {
-                prefix = "\\b";
+                prefix = wordBoundary;
             } else {
                 prefix = "";
             }
 
-            return new RegExp(prefix + escaped + suffix, "i");
+            return new RegExp(prefix + escaped + suffix + eitherOrWordBoundary + term + wordBoundary, "i");
```
Comment (platinumazure) [inline lib/rules/no-warning-comments.js]: I think it would be really helpful to have a comment here showing what the regex should look like for an example term.

Also: Based on the issues I've identified in the tests, we want to make sure that this regex is only augmented when `{ location: "anywhere" }` option is specified.

File: tests/lib/rules/no-warning-comments.js [hunk 2]
```diff
@@ -24,15 +24,10 @@ ruleTester.run("no-warning-comments", rule, {
         { code: "// any comment", options: [{ terms: ["fixme", "todo"] }] },
         "// any comment",
         { code: "// any comment", options: [{ location: "anywhere" }] },
-        { code: "// any comment with TODO, FIXME or XXX", options: [{ location: "start" }] },
```
Comment (platinumazure) [inline tests/lib/rules/no-warning-comments.js]: This should still be valid: the rule option `{ location: "start" }` means only flag the comment if it starts with TODO/FIXME/XXX.

File: tests/lib/rules/no-warning-comments.js [hunk 3]
```diff
@@ -24,15 +24,10 @@ ruleTester.run("no-warning-comments", rule, {
...
-        "// any comment with TODO, FIXME or XXX",
```
Comment (platinumazure) [inline tests/lib/rules/no-warning-comments.js]: This should be valid as well: `{ location: "start" }` appears to be the rule default. This should only be flagged if the `{ location: "anywhere" }` option is explicitly specified.

File: tests/lib/rules/no-warning-comments.js [hunk 4]
```diff
@@ -24,15 +24,10 @@ ruleTester.run("no-warning-comments", rule, {
...
         { code: "/* any block comment */", options: [{ terms: ["fixme"] }] },
         { code: "/* any block comment */", options: [{ terms: ["fixme", "todo"] }] },
         "/* any block comment */",
         { code: "/* any block comment */", options: [{ location: "anywhere" }] },
-        { code: "/* any block comment with TODO, FIXME or XXX */", options: [{ location: "start" }] },
```
Comment (platinumazure) [inline tests/lib/rules/no-warning-comments.js]: This should be valid since the term is not at the start of the comment.

File: tests/lib/rules/no-warning-comments.js [hunk 5]
```diff
@@ -24,15 +24,10 @@ ruleTester.run("no-warning-comments", rule, {
...
-        "/* any block comment with TODO, FIXME or XXX */",
```
Comment (platinumazure) [inline tests/lib/rules/no-warning-comments.js]: This should be valid since the term is not at the start of the comment.

File: tests/lib/rules/no-warning-comments.js [hunk 6]
```diff
@@ -24,15 +24,10 @@ ruleTester.run("no-warning-comments", rule, {
...
-        "/* any block comment with (TODO, FIXME's or XXX!) */",
```
Comment (platinumazure) [inline tests/lib/rules/no-warning-comments.js]: This should be valid since the term is not at the start of the comment.

File: tests/lib/rules/no-warning-comments.js [hunk 7]
```diff
@@ -50,11 +45,15 @@ ruleTester.run("no-warning-comments", rule, {
         { code: "// any fixme or todo", options: [{ terms: ["fixme", "todo"], location: "anywhere" }], errors: [{ message: "Unexpected 'fixme' comment." }, { message: "Unexpected 'todo' comment." }] },
         { code: "/* any fixme or todo */", options: [{ terms: ["fixme", "todo"], location: "anywhere" }], errors: [{ message: "Unexpected 'fixme' comment." }, { message: "Unexpected 'todo' comment." }] },
         { code: "/* any fixme or todo */", options: [{ location: "anywhere" }], errors: [{ message: "Unexpected 'todo' comment." }, { message: "Unexpected 'fixme' comment." }] },
-        { code: "/* fixme and todo */", errors: [{ message: "Unexpected 'fixme' comment." }] },
+        { code: "/* fixme and todo */", errors: [{ message: "Unexpected 'todo' comment." }, { message: "Unexpected 'fixme' comment." }] },
```
Comment (platinumazure) [inline tests/lib/rules/no-warning-comments.js]: This should only be invalid with 2 messages if `{ location: "anywhere" }` is specified as an option.

File: tests/lib/rules/no-warning-comments.js [hunk 8]
```diff
@@ -50,11 +45,15 @@ ruleTester.run("no-warning-comments", rule, {
...
         { code: "/* any fixme */", options: [{ location: "anywhere" }], errors: [{ message: "Unexpected 'fixme' comment." }] },
         { code: "/* fixme! */", options: [{ terms: ["fixme"] }], errors: [{ message: "Unexpected 'fixme' comment." }] },
         { code: "// regex [litera|$]", options: [{ terms: ["[litera|$]"], location: "anywhere" }], errors: [{ message: "Unexpected '[litera|$]' comment." }] },
         { code: "/* eslint one-var: 2 */", options: [{ terms: ["eslint"] }], errors: [{ message: "Unexpected 'eslint' comment." }] },
-        { code: "/* eslint one-var: 2 */", options: [{ terms: ["one"], location: "anywhere" }], errors: [{ message: "Unexpected 'one' comment." }] }
+        { code: "/* eslint one-var: 2 */", options: [{ terms: ["one"], location: "anywhere" }], errors: [{ message: "Unexpected 'one' comment." }] },
+        { code: "/* any block comment with TODO, FIXME or XXX */", options: [{ location: "start" }], errors: [{ message: "Unexpected 'todo' comment." }, { message: "Unexpected 'fixme' comment." }, { message: "Unexpected 'xxx' comment." }] },
```
Comment (platinumazure) [inline tests/lib/rules/no-warning-comments.js]: This should only be invalid when `{ location: "anywhere" }` is specified.

File: tests/lib/rules/no-warning-comments.js [hunk 9]
```diff
@@ -50,11 +45,15 @@ ruleTester.run("no-warning-comments", rule, {
...
+        { code: "/* any block comment with (TODO, FIXME's or XXX!) */", options: [{ location: "start" }], errors: [{ message: "Unexpected 'todo' comment." }, { message: "Unexpected 'fixme' comment." }, { message: "Unexpected 'xxx' comment." }] },
```
Comment (platinumazure) [inline tests/lib/rules/no-warning-comments.js]: This should only be invalid when `{ location: "anywhere" }` is specified.

File: tests/lib/rules/no-warning-comments.js [hunk 10]
```diff
@@ -50,11 +45,15 @@ ruleTester.run("no-warning-comments", rule, {
...
+        { code: "/** \n *any block comment \n*with (TODO, FIXME's or XXX!) **/", options: [{ location: "start" }], errors: [{ message: "Unexpected 'todo' comment." }, { message: "Unexpected 'fixme' comment." }, { message: "Unexpected 'xxx' comment." }] },
```
Comment (platinumazure) [inline tests/lib/rules/no-warning-comments.js]: This should only be invalid when `{ location: "anywhere" }` is specified.

File: tests/lib/rules/no-warning-comments.js [hunk 11]
```diff
@@ -50,11 +45,15 @@ ruleTester.run("no-warning-comments", rule, {
...
+        { code: "// any comment with TODO, FIXME or XXX", options: [{ location: "start" }], errors: [{ message: "Unexpected 'todo' comment." }, { message: "Unexpected 'fixme' comment." }, { message: "Unexpected 'xxx' comment." }] }
```
Comment (platinumazure) [inline tests/lib/rules/no-warning-comments.js]: This should only be invalid when `{ location: "anywhere" }` is specified.

**Comment by platinumazure** [comment]
Oh, forgot to mention: This should be an "Update" since this is a bugfix that potentially increases the number of warnings the user might experience. Please change the commit message accordingly. Thanks!

**Comment by sstern6** [comment]
Thanks for the feedback @platinumazure addressed all comments and split the logic between location `start` and location `anywhere` for the appropriate regexp with some comments.  Let me know if there are any more comments to address

Thanks

**Comment by kaicataldo** [comment]
Sorry for losing track of this. Marking this as accepted, since the corresponding issue is accepted. @sstern6 Do you mind updating the description to reference the issue?

@platinumazure have your comments been addressed?

**Comment by platinumazure** [comment]
Apologies @sstern6 and @kaicataldo, yes, my concerns are addressed.

**Comment by kaicataldo** [comment]
Thanks for contributing to ESLint!
