### PR TITLE
Build: Fix site generation (fixes #6791)

### LINKED ISSUE #6791: Entire site is giving 404s
So:
 
1. Go to [this link](http://eslint.org/docs/rules/)
2. Choose any of the rules
3. Click

It does not work :-1:

### PR DESCRIPTION
**Pull request by nzakas**
**What issue does this pull request address?**

#6791

**What changes did you make? (Give an overview)**

https://github.com/eslint/eslint/pull/6658 mistakenly removed a line that output the frontmatter into the Jekyll pages which resulted in 404s on eslint.org. This PR simply adds that line back in.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: Makefile.js [hunk 1]
```diff
@@ -663,11 +663,14 @@ target.gensite = function(prereleaseVersion) {
                 }
                 text += "* [Documentation source](" + docsUrl + baseName + ")\n";
             }
+
+            // 9. Update content of the file with changes
+            text.to(filename.replace("README.md", "index.md"));
```
Comment (ilyavolodin) [inline Makefile.js]: I removed that line because I also removed `README.md` from under `rules` directory. Or is this from some other directory?

Comment (nzakas) [inline Makefile.js]: This runs for every file and directory.

**Comment by kaicataldo** [comment]
LGTM

File: Makefile.js (hunk 1 above)
Comment (ilyavolodin) [inline Makefile.js]: Ah, ok, in that case, it should work as expected, since I deleted README from rules directory

Comment (vitorbal) [inline Makefile.js]: In that case, would it not be fine to remove the .replace() call?

**Comment by vitorbal** [comment]
Lgtm
