### PR TITLE
Breaking: Implement yield-star-spacing rule (fixes #4115)

### LINKED ISSUE #4115: Create yield-star-spacing rule
My settings: `"space-unary-ops": [1, { "words": true, "nonwords": false }]`

Fails on the code: `yield *iterateChildren(tgChildRow);` with message _Unary word operator "yield*" must be followed by whitespace_.

Version 1.6.0

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27330565-create-yield-star-spacing-rule?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by bryanrsmith**
This change removes checking of yield* operators from the space-unary-ops rule, and adds a new yield-star-spacing rule to check spacing around the * in yield* expressions.

### CODE REVIEW

File: lib/rules/yield-star-spacing.js [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+    /**
+     * Checks the spacing between two tokens before or after the star token.
+     * @param {string} side Either "before" or "after".
+     * @param {Token} leftToken `function` keyword token if side is "before", or
+     *     star token if side is "after".
+     * @param {Token} rightToken Star token if side is "before", or identifier
+     *     token if side is "after".
+     * @returns {void}
+     */
+    function checkSpacing(side, leftToken, rightToken) {
```
Comment (bryanrsmith) [inline lib/rules/yield-star-spacing.js]: This is duplicated from generator-star-spacing. Is it desirable to keep rules self-contained, or should I factor it into a util module?

Comment (nzakas) [inline lib/rules/yield-star-spacing.js]: We kind of already have one: https://github.com/eslint/eslint/blob/master/lib/util/source-code.js#L281

Comment (bryanrsmith) [inline lib/rules/yield-star-spacing.js]: Thanks. Updated to use the `SourceCode` helper.

**Comment by nzakas** [comment]
Looks good to me.
