### PR TITLE
Fix: --init with Vue.js failed (fixes #11970)

### LINKED ISSUE #11970: `eslint --init` alwalys fails
**Tell us about your environment**

* **ESLint Version:**v6.0.1
* **Node Version:**v10.14.0
* **npm Version:**6.4.1

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
`eslint --init`

```
? How would you like to use ESLint? To check syntax, find problems, and enforce code style
? What type of modules does your project use? JavaScript modules (import/export)
? Which framework does your project use? Vue.js
? Where does your code run? (Press <space> to select, <a> to toggle all, <i> to invert selection)Browser
? How would you like to define a style for your project? Use a popular style guide
? Which style guide do you want to follow? Standard (https://github.com/standard/standard)
? What format do you want your config file to be in? JSON
Checking peerDependencies of eslint-config-plugin:vue/essential,standard@latest
Local ESLint installation not found.
The config that you've selected requires the following dependencies:

eslint-plugin-vue@latest eslint-config-plugin:vue/essential,standard@latest error@[object Object] eslint@latest
? Would you like to install them now with npm? Yes
Installing eslint-plugin-vue@latest, eslint-config-plugin:vue/essential,standard@latest, error@[object Object], eslint@latest
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "[object Object]": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-07-09T02_28_04_967Z-debug.log
Successfully created .eslintrc.json file in G:\user\esli
ESLint was installed locally. We recommend using this local copy instead of your globally-installed copy.
```

**What did you expect to happen?**
ESLint inits successfully.

**What actually happened? Please include the actual, raw output from ESLint.**
When i install the dependences, always encounter the above errors. In issues i have seen the same question, but i still do not understand the question and find the solution. And i have used different computers, such as windows, mac, but they still have the question.

**Are you willing to submit a pull request to fix this bug?**
no idea

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix: #11970

**What changes did you make? (Give an overview)**

This PR fixes `--init` to work.

We didn't seem to test `--init` when we added Vue.js support. It has assumed that `extends` is a string and doesn't include plugin configs.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: lib/init/config-initializer.js [hunk 1]
```diff
@@ -100,14 +100,21 @@ function getModulesList(config, installESLint) {
...
-            getPeerDependencies(`${moduleName}@latest`)
-        );
+    if (config.extends) {
+        const extendList = Array.isArray(config.extends) ? config.extends : [config.extends];
+
+        for (const extend of extendList) {
+            if (extend.startsWith("eslint:") || extend.startsWith("plugin:")) {
+                continue;
+            }
+            const moduleName = `eslint-config-${extend}`;
```
Comment (platinumazure) [inline lib/init/config-initializer.js]: `extends: ["eslint-config-airbnb"]` is valid, but this line will cause a problem with that case. I highly recommend importing our "naming" utility module and using that to ensure proper normalization of config names.

**Comment by mysticatea** [comment]
Thank you for your review. I updated this PR.
