### PR TITLE
Fix: invalidate cache when config changes. (fixes #3770)

### LINKED ISSUE #3770: Invalidate cache when rules change
We should automatically invalidate the cache when the configuration used to test the file was changed. This will allow people to use the cache on continuous integration machines that do incremental builds (opposed to travis which does a full checkout each time). 

In order to support this I think we would need to store the full configuration each file was linted with in the eslintcache file. That would provide support for upstream plugins being changed, environments in higher folders being changed, etc.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26638550-invalidate-cache-when-rules-change?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by royriojas**
cache will be skipped if 

- config changed
- plugins version changed

### CODE REVIEW

**Comment by TheSavior** [comment]
It doesn't look like there are tests for when a plugin version has changed. I'm not actually sure why the plugin version matters. The plugin version changing would only matter if it changes the configuration the file is tested with, right? In which case, we are already checking the configuration...

**Comment by lo1tuma** [comment]
@TheSavior if a plugin version changes in could mean that the plugin has changed the behavior of its rules. So you could get different linting results without changing your config. 

@royriojas what about the eslint version? I think it should be included in the checksum too.

**Comment by BYK** [comment]
:+1: to @lo1tuma

**Comment by royriojas** [comment]
@TheSavior I'm having some issues to think about how to make the tests for the plugins. So far this is what I was thinking was:

- manually copy a dummy plugin to the node_modules folder before the test
- run with cache
- update the version of the package.json of the plugin
- run again and check cache was invalidated

What do you think?

**Comment by royriojas** [comment]
I have updated the code to also hash the version of eslint

**Comment by nzakas** [comment]
As I mentioned on the issue, we can't make assumptions about where the plugins will be located going forward, so copying files around from a particular location doesn't seem like a good idea. What we probably need is some API that lists each loaded plugin with its version...but that can only happen after each config is fully calculated. I'd say let's move forward without plugin support and open a separate issue to track that.

**Comment by royriojas** [comment]
@nzakas, done

File: lib/util/md5-hash.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+"use strict";
+
+var crypto = require( "crypto" );
```
Comment (gyandeeps) [inline lib/util/md5-hash.js]: Dont we need this package inside our dependency? if yes, the how is the unit test passing?

Also can you remove spaces around it just for consistency sake.

File: lib/util/md5-hash.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+/**
+ * create a md5Hash of a given string
+ * @param   {string} str the string to calculate the hash for
+ * @returns {string}     the calculated hash
+ */
+module.exports = function md5Hash( str ) {
```
Comment (gyandeeps) [inline lib/util/md5-hash.js]: Minor: I would get rid of the spaces around `str` for consistency sake.

Comment (royriojas) [inline lib/util/md5-hash.js]: done!

File: lib/util/md5-hash.js (hunk 1 above)
Comment (royriojas) [inline lib/util/md5-hash.js]: Done. `crypto` is part of node default pacakges like `path`

File: lib/util/md5-hash.js [hunk 3]
```diff
@@ -0,0 +1,15 @@
+"use strict";
+
+var crypto = require("crypto");
```
Comment (gyandeeps) [inline lib/util/md5-hash.js]: Why is this module not listed as a dependency in `package.json`?

File: lib/util/md5-hash.js (hunk 1 above)
Comment (gyandeeps) [inline lib/util/md5-hash.js]: Got it. Thanks.
Never used it so sounded like an external module.

**Comment by IanVS** [comment]
Couldn't the plugin version be determined by looking at the `package.json` of any packages in `node_modules` starting with `eslint-plugin-`? There's a chance they're not actually being used in a configuration, of course, but it would be relatively simple to do and it's probably better to err on the side of breaking cache than failing to do so.

**Comment by lo1tuma** [comment]
> we can't make assumptions about where the plugins will be located going forward, so copying files around from a particular location doesn't seem like a good idea.

I don’t get this. There wasn’t copied any file, instead we used `require.resolve` which should always work except you define a completely different location in the `main` field of the `package.json`.

**Comment by royriojas** [comment]
I can put back the check I had before for the plugins. No problem on that it seemed to be working fine. 

How to make a test for that was the thing I didn't had that clear

**Comment by royriojas** [comment]
@nzakas, reading again your text is clear to me that plugins might not be installed in `node_modules` all the time. If that is true, then I guess this pull request is up to date. We can open another issue to see how can we invalidate the cache when plugin versions change.

Regards

**Comment by nzakas** [comment]
@lo1tuma You're assuming that the only way we'll ever include a plugin is via `require()`, and I'm not sure that's a valid assumption right now. If we somehow allow multiple plugins to be bundled together, that could change the equation considerably. So it's not safe to assume one plugin = one folder in `node_modules` or that `require.resolve()` will always be the way that plugins are located.

File: lib/util/md5-hash.js [hunk 4]
```diff
@@ -0,0 +1,15 @@
+"use strict";
```
Comment (nzakas) [inline lib/util/md5-hash.js]: Can you update this file to follow conventions from other files? http://eslint.org/docs/developer-guide/code-conventions.html

Comment (nzakas) [inline lib/util/md5-hash.js]: Another option is to move this function into `cli-engine.js`, as that's the only place it seems to be used.

File: lib/cli-engine.js [hunk 5]
```diff
@@ -506,6 +510,33 @@ CLIEngine.prototype = {
...
         };
 
+
+        /**
+         * Calculates the hash of the config file used to validate a given file
+         * @param  {string} filename The path of the file to retrieve a config object for to calculate the hash
+         * @returns {string}         the hash of the config
+         */
+        function hashOfConfigFor(filename) {
+            var config = configHelper.getConfig(filename);
```
Comment (nzakas) [inline lib/cli-engine.js]: I might be wrong, but it looks like we'll be calling `getConfig(filename)` two times for each filename, once here and once in `executeOnFile()`. This is a pretty expensive operation, so it would be good to do it only once.

**Comment by lo1tuma** [comment]
> You're assuming that the only way we'll ever include a plugin is via require(), and I'm not sure that's a valid assumption right now.

No, I’m assuming that right now the only way to include a plugin is via `require()`. If we change this we also need a new way to get the plugin versions.

File: lib/cli-engine.js (hunk 5 above)
Comment (lo1tuma) [inline lib/cli-engine.js]: `getConfig` already returns the cached config of a file if you call it multiple times with the same filename, see https://github.com/eslint/eslint/blob/18a3f1bff2e9a36bb9672517ceb1453678fc6ca2/lib/config.js#L400-L404

**Comment by nzakas** [comment]
> If we change this we also need a new way to get the plugin versions.

Not necessarily. If we add a method somewhere that's basically `getInstalledPlugins()`, then we'd just be able to change that implementation to return the same information. That's why I said we should split off into a separate issue to discuss.

Crawling around the filesystem looking for things is an inherently fragile approach that only works with our current implementation. I want to avoid that by having some sort of abstraction that allows us to change a minimal amount of code should we this change in the future.

**Comment by royriojas** [comment]
@nzakas, so I had put back the function for hashing inside `cli-engine` I guess for now it is ok that way. please let me know if there are other changes to make

**Comment by lo1tuma** [comment]
@nzakas Agreed, I somehow missed the point that you are not against using plugin versions, but just wanted to discuss the solution approach for that separately :+1:.

File: lib/cli-engine.js (hunk 5 above)
Comment (nzakas) [inline lib/cli-engine.js]: Ooh right. Cool.

**Comment by nzakas** [comment]
Lgtm
