### PR TITLE
Fix: `no-extra-parens` false positive at IIFE with member accessing

### LINKED ISSUE #3653: Problem with no-extra-parens
I use mocha for test, and always write the following code for asserting function exception.

```js
it('should throw', function() {
  (function() {
    testFunctionCall();
  }).should.throw('error message');
});
```

I configured `no-extra-parens` with `2`, and got the error (eslint version is 1.3.1).

```
4:3  error  Gratuitous parentheses around expression  no-extra-parens
```

Is there any best practice for this?

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #3653.

### CODE REVIEW

File: tests/lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -152,7 +154,6 @@ ruleTester.run("no-extra-parens", rule, {
         "var o = { foo: (function() { return bar(); })() };",
         "o.foo = (function(){ return bar(); })();",
         "(function(){ return bar(); })(), (function(){ return bar(); })()",
-        "((function(){ return bar(); })())",
```
Comment (mysticatea) [inline tests/lib/rules/no-extra-parens.js]: I thought this pattern should be reported.
But I will revert if it's a problem. ... (it's a bit troublesome...)

File: lib/rules/no-extra-parens.js [hunk 2]
```diff
@@ -321,6 +394,11 @@ module.exports = function(context) {
                         // RegExp literal is allowed to have parens (#1589)
                         (node.object.type === "Literal" && node.object.regex)
                     )
+                ) &&
+                !(
+                    node.object.type === "FunctionExpression" &&
```
Comment (BYK) [inline lib/rules/no-extra-parens.js]: You may wanna add `"ArrowFunctionExpression"` too.

Comment (BYK) [inline lib/rules/no-extra-parens.js]: Not that I'm aware of such a pattern. So may be not :)

File: lib/rules/no-extra-parens.js [hunk 3]
```diff
@@ -75,6 +76,68 @@ module.exports = function(context) {
...
+                    }
+                    break;
+
+                case "MemberExpression":
+                    if (parent.object !== node || isParenthesised(node)) {
+                        return false;
+                    }
+                    break;
+
+                case "ExpressionStatement":
```
Comment (michaelficarra) [inline lib/rules/no-extra-parens.js]: Why is this ever passed in? It's not an expression.

File: tests/lib/rules/no-extra-parens.js (hunk 1 above)
Comment (nzakas) [inline tests/lib/rules/no-extra-parens.js]: We need to be very careful about deciding valid cases are no longer valid. Can you check when this case was added (use blame).

File: lib/rules/no-extra-parens.js [hunk 4]
```diff
@@ -75,6 +76,68 @@ module.exports = function(context) {
...
+     * Checks whether or not a given node is located at the head of ExpressionStatement.
+     * @param {ASTNode} node - A node to check.
+     * @returns {boolean} `true` if the node is located at the head of ExpressionStatement.
+     */
+    function isHeadOfExpressionStatement(node) {
+        var parent = node.parent;
+        while (parent != null) {
+            switch (parent.type) {
+                case "SequenceExpression":
+                    if (parent.expressions[0] !== node || isParenthesised(node)) {
```
Comment (michaelficarra) [inline lib/rules/no-extra-parens.js]: Instead of checking `isParenthesised` in every case, just early exit.

**Comment by michaelficarra** [comment]
Are there any plans to do the same for `class` and `let [`?

File: tests/lib/rules/no-extra-parens.js (hunk 1 above)
Comment (michaelficarra) [inline tests/lib/rules/no-extra-parens.js]: Why is that? If we fix a bug, I'm sure they would be happy to start getting notified about things that eslint was missing before.

Comment (nzakas) [inline tests/lib/rules/no-extra-parens.js]: Because we might have added this exception as a result of an issue. In that case, we need to be sure that we aren't creating a regression.

If this case was there since the rule was created, then it's more obvious to say its a bug we should fix.

Comment (michaelficarra) [inline tests/lib/rules/no-extra-parens.js]: It was added in response to an issue, but in error. The IIFE wrapping exception was not there when this rule was created.

Comment (mysticatea) [inline tests/lib/rules/no-extra-parens.js]: I think this test case is not a regression test.
This is added in https://github.com/eslint/eslint/commit/9ea75573c95bb3bd66f922bf19bab500962162eb.
The commit merges `no-extra-parens` and `no-wrap-func`.
However, `no-wrap-func` had not been having this test case: https://github.com/eslint/eslint/blob/v0.24.1/tests/lib/rules/no-wrap-func.js

File: lib/rules/no-extra-parens.js (hunk 2 above)
Comment (mysticatea) [inline lib/rules/no-extra-parens.js]: `FunctionExpression` becomes `FunctionDeclaration` if it was not enclosed by parens, so it needs parens.
However, `ArrowFunctionExpression` is not so :)

File: lib/rules/no-extra-parens.js (hunk 4 above)
Comment (mysticatea) [inline lib/rules/no-extra-parens.js]: Actually, I want to not do `isParenthesised(node)` if `parent.type` is `"ExpressionStatement"`. Because in `((function() {}).foo)` case, I want to not warn both parens.

**Comment by mysticatea** [comment]
@michaelficarra `class` has the same issue, I got it.

```js
let [a] = [0];

(let[a]) = 0;
```

Ahh...
But `(let[a]) = 0;` cannot be parsed by esprima, espree, acorn, and babylon.

**Comment by mysticatea** [comment]
I added handling around classes and immediate member expressions.

File: tests/lib/rules/no-extra-parens.js (hunk 1 above)
Comment (nzakas) [inline tests/lib/rules/no-extra-parens.js]: Awesome, thanks for double checking.

**Comment by nzakas** [comment]
Looks like we need another rebase. Not sure what's going on with pull requests today.
