### PR TITLE
Fix: preserve whitespace in multiline-comment-style (fixes #12312)

### LINKED ISSUE #12312: [multiline-comment-style] autofix removes indentation in the comment
**Tell us about your environment**

* **ESLint Version:** 6.4.0
* **Node Version:** 12.10.0
* **npm Version:** 6.11.3

**What parser (default, Babel-ESLint, etc.) are you using?**

Default.

**Please show your full configuration:**
**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbXVsdGlsaW5lLWNvbW1lbnQtc3R5bGU6IFtlcnJvcl0gKi9cblxuLypcbntcbiAgICBcImZvb1wiOiAxLFxuICAgIFwiYmFyXCI6IDJcbn1cbiovXG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjgsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=).

```js
/*eslint multiline-comment-style: [error] */

/*
{
    "foo": 1,
    "bar": 2
}
*/
```

**What did you expect to happen?**

ESLint fixes it to:

```js
/*eslint multiline-comment-style: [error] */

/*
 * {
 *     "foo": 1,
 *     "bar": 2
 * }
 */
```

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint fixed it to:

```js
/*eslint multiline-comment-style: [error] */

/*
 * {
 * "foo": 1,
 * "bar": 2
 * }
 */
```

The indentation in the comment is broken.

**Are you willing to submit a pull request to fix this bug?**

Yes.

### PR DESCRIPTION
**Pull request by kaicataldo**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

fixes #12312

**What changes did you make? (Give an overview)**

~~This PR preserves leading whitespace when converting a block comment to a "starred" block comment in the `multiline-comment-style` rule's autofixer. Since this rule doesn't know about indentation, I decided to take the strategy of checking if the leading whitespace matches the expected whitespace (i.e. the whitespace before the opening delimiter for the block comment) and, if it does, to use any remaining whitespace after the asterisk. I think this will work for the vast majority of cases (though it could get weird if folks mix tabs and spaces). If they don't match, it falls back to the current behavior and adds one space.~~

Apologies for the large diff - I ended up doing a lot of refactoring to try to make the code easier to follow. All the calculation of how much whitespace should be used to offset each line now gets calculated in `getCommentLines()`, which I think is a clearer separation of concerns between this module's internal functions.

I believe the autofix should be consistent across formats now. In the case of an easy to use delimiter (`*` for `starred-block` or `//` for `separate-lines`), calculating the whitespace is pretty straightforward. For `bare-block`, the check now iterates through the lines of the comment and checks if any lines are indented less than the opening line, and offsets all the lines by the difference. If it's indented more, it removes the appropriate amount of whitespace. Otherwise, if it's correct, it returns the line unchanged.

**Is there anything you'd like reviewers to focus on?**

1. ~~This only preserves whitespace if the the leading whitespace on the line matches the leading whitespace before the opening delimiter of the block comment (`/*`). Does this seem like a good way to go about this? In other cases, I'm not sure how you would know exactly how much to indent something (particularly if there's a mix of tabs and spaces).~~
1. ~~Not directly related to this change, but I think it's a bit strange that we don't push a space after the asterisk when we convert line comments to "starred" block comments. I have added a test to document this behavior.~~
1. I'm not sure how we would handle offsets in the case of code mixing tabs and spaces. If someone has an idea of how we could more gracefully check for this, I'm all ears!

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you for fixing.

Would you add tests for other options? For example,

```js
        {
            code: `
                /*
                 * {
                 *    "foo": 1,
                 *    "bar": 2
                 * }
                 */
            `,
            output: `
                // {
                //    "foo": 1,
                //    "bar": 2
                // }
            `,
            options: ["separate-lines"],
            errors: [
                { messageId: "expectedLines", line: 2 }
            ]
        }
```

**Comment by kaicataldo** [comment]
Updated this PR but added the "do not merge" label because I need to go back through and refactor/clean up the PR.

**Comment by kaicataldo** [comment]
This is ready for re-review!

File: tests/lib/rules/multiline-comment-style.js [hunk 1]
```diff
@@ -482,6 +712,348 @@ ruleTester.run("multiline-comment-style", rule, {
...
+                /* {
+                       "foo": 1,
+                       "bar": 2
+                   } */
+            `,
+            output: `
+                // {
+                //     "foo": 1,
+                //     "bar": 2
+                // }${" "}
```
Comment (kaicataldo) [inline tests/lib/rules/multiline-comment-style.js]: We could update the autofixer to not include trailing whitespace, but I wasn't sure it was worth the extra complexity. Thoughts?

I added this because many people configure their editors to remove trailing whitespace automatically, and that could lead to a frustratingly vague error when running the tests.

**Comment by kaicataldo** [comment]
@mysticatea This has been updated!

File: tests/lib/rules/multiline-comment-style.js [hunk 2]
```diff
@@ -482,6 +712,348 @@ ruleTester.run("multiline-comment-style", rule, {
...
+                {
+               \t"foo": 1,
+               \t"bar": 2
+                }
+                */
+            `,
+            output: `
+                /*
+                 * {
+                 * "foo": 1,
```
Comment (platinumazure) [inline tests/lib/rules/multiline-comment-style.js]: Should these lines also have tabs? Or are they ignored because the tabs in the input are aligned with the `/` rather than the `*` on the first line of the comment?

Comment (kaicataldo) [reply tests/lib/rules/multiline-comment-style.js]: The current autofixer moves any lines that have less indentation than the opening comment delimiter up to minimum indentation required to align with the `*` characters on each line (in other words, removing all leading whitespace and adding a space after the `*`). I don't know how we can can compare lines that have mixed tabs and spaces in their leading whitespace, so I just used the number of whitespace characters to compare. We could alternatively use all the whitespace from the beginning of the line to the first non-whitespace character, but I think the current behavior is more in line with what folks would expect. Definitely open to other options if someone has a better suggestion of how to handle this!

File: lib/rules/multiline-comment-style.js [hunk 3]
```diff
@@ -197,67 +302,68 @@ module.exports = {
...
+                }
+
+                context.report({
+                    loc: {
+                        start: firstComment.loc.start,
+                        end: { line: firstComment.loc.start.line, column: firstComment.loc.start.column + 2 }
+                    },
+                    messageId: "expectedLines",
+                    fix(fixer) {
+                        return fixer.replaceText(firstComment, convertToSeparateLines(firstComment, commentLines.filter(line => line.length)));
```
Comment (mysticatea) [inline lib/rules/multiline-comment-style.js]: I'm guessing this filter removes empty lines from the comment in autofix. I expect the below...

```js
        {
            code: `
                /*
                 * foo
                 *
                 * bar
                 */
            `,
            output: `
                // foo
                //${" "}
                // bar
            `,
            options: ["separate-lines"],
            errors: [{ messageId: "expectedLines", line: 2 }]
        },
        {
            code: `
                /*
                 * foo
                 *${" "}
                 * bar
                 */
            `,
            output: `
                // foo
                //${" "}
                // bar
            `,
            options: ["separate-lines"],
            errors: [{ messageId: "expectedLines", line: 2 }]
        },
```

File: lib/rules/multiline-comment-style.js [hunk 4]
```diff
@@ -197,67 +302,68 @@ module.exports = {
...
+                // prohibits block comments from having a * at the beginning of each line.
+                if (isStarredBlockComment(commentGroup)) {
+                    context.report({
+                        loc: {
+                            start: firstComment.loc.start,
+                            end: { line: firstComment.loc.start.line, column: firstComment.loc.start.column + 2 }
+                        },
+                        messageId: "expectedBareBlock",
+                        fix(fixer) {
+                            return fixer.replaceText(firstComment, convertToBlock(firstComment, commentLines.filter(line => line.length)));
```
Comment (mysticatea) [inline lib/rules/multiline-comment-style.js]: This is similar.

File: lib/rules/multiline-comment-style.js (hunk 3 above)
Comment (kaicataldo) [reply lib/rules/multiline-comment-style.js]: Thanks for catching this. Fixed!

File: lib/rules/multiline-comment-style.js (hunk 4 above)
Comment (kaicataldo) [reply lib/rules/multiline-comment-style.js]: This should be fixed now!

**Comment by kaicataldo** [comment]
I have two last failing tests to fix. Marking as do not merge until I do so.

**Comment by kaicataldo** [comment]
Sorry for the delay! This ended up being a much more complex change than I anticipated 😄 Thanks for the great reviews!

**Comment by kaicataldo** [comment]
@mysticatea Friendly ping :)
