### PR TITLE
Fix: fails the test case if autofix made syntax error (fixes #11615)

### LINKED ISSUE #11615: RuleTester should report syntax error of fixed code
**The version of ESLint you are using.**

- master

**The problem you want to solve.**

I found `RuleTester` doesn't report any errors even if autofix makes a syntax error in #11579.

image

I expected above test results to be "A fatal parsing error occurred in autofix: Parsing error: ..." rather than "Output is incorrect".

**Your take on the correct solution to problem.**

`RuleTester` makes failing if autofix made a syntax error.

**Are you willing to submit a pull request to implement this change?**

Yes.

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix #11615

**What changes did you make? (Give an overview)**

This PR fixes `RuleTester` to fail the test case if autofix made syntax errors.

Additionally,

- fixes some test cases that autofix made syntax errors.
- fixes the side-effect that overrides `RuleTester.describe` and `RuleTester.it` permanently in `tests/lib/rule-tester/rule-tester.js`. This side-effect had confused `tests/lib/rules/*.js` as using the stub functions to test rules.

I have noticed that `errors` property with a number allows syntax errors. Some of our tests depend on the behavior in order to use syntax error in rule's tests (E.g. [tests/lib/rules/spaced-comment.js#L577-L589](https://github.com/eslint/eslint/blob/cb1922bdc07e58de0e55c13fd992dd8faf3292a4/tests/lib/rules/spaced-comment.js#L577-L589)). I'm not sure if it's intentional, but I left it as is.

I wonder if we should deprecate the `errors` property with a number. It causes false negatives such as [tests/lib/rules/complexity.js#L84](https://github.com/eslint/eslint/blob/cb1922bdc07e58de0e55c13fd992dd8faf3292a4/tests/lib/rules/complexity.js#L84).

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: tests/lib/rules/quotes.js [hunk 1]
```diff
@@ -160,30 +160,35 @@ ruleTester.run("quotes", rule, {
             code: "var foo = 'bar';",
             output: "var foo = `bar`;",
             options: ["backtick"],
+            parserOptions: { ecmaVersion: 2015 },
```
Comment (aladdin-add) [inline tests/lib/rules/quotes.js]: what if the parserOptions is setting: `{ ecmaVersion: 5 }`. (I would suggest to report a linting error, but do not apply the fix.)

Comment (mysticatea) [reply tests/lib/rules/quotes.js]: It's the thing that this PR fixed -- the test case will fail as "A fatal parsing error occurred in autofix: Parsing error: unexpected token `"

Comment (aladdin-add) [reply tests/lib/rules/quotes.js]: to clarify, the parsing error will be reported in rule tester, but not to end users (since eslint don't verify the "fixed" code if I'm not misunderstanding)

Comment (mysticatea) [reply tests/lib/rules/quotes.js]: ESLint repeats autofix until all fixable problems are processed. In this case, ESLint encounters a syntax error while the loop, the syntax error will be reported to users.

Comment (aladdin-add) [reply tests/lib/rules/quotes.js]: well, I see. thanks!
