### PR TITLE
fix: `getFirstToken`/`getLastToken` on comment-only node

### LINKED ISSUE #16742: Bug: `filter` callback in `getFirstToken`/`getLastToken` is called with `undefined`
### Environment

Node version: v19.3.0
npm version: v9.2.0
Local ESLint version: v8.31.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 22.1.0

### What parser are you using?

Default (Espree)

### What did you do?

While working on a custom rule I noticed an edge case where the `filter` callback passed to `sourceCode.getFirstToken()` and `sourceCode.getLastToken()` was being called with an `undefined` argument instead of a `Token` object.

The following is a minimal example I created to illustrate the problem.

```js
const { RuleTester } = require('eslint');

function isCommaToken(token) {
    return token.type === 'Punctuator' && token.value === ',';
}

const rule = {
    meta: {
        docs: { description: 'Forbid commas' },
        messages: { fail: 'commas not allowed' },
    },
    create(context) {
        const sourceCode = context.getSourceCode();
        return {
            Program: node => {
                if (sourceCode.getFirstToken(node, { filter: isCommaToken })) {
                    context.report({ node, messageId: 'fail' });
                }
            }
        };
    }
};

new RuleTester().run(
    'no-commas',
    rule,
    {
        valid:
        [
            '// comment',
        ],
        invalid: [],
    },
);
```

### What did you expect to happen?

The sample test code should run without errors.

### What actually happened?

An error occurs, because the `filter` callback is called with `undefined`:

<pre>
TypeError: Cannot read properties of undefined (reading 'type')
Occurred while linting <input>:1
Rule: "no-commas"
    at isCommaToken (.../no-commas.js:4:18)
    at FilterCursor.moveNext (.../node_modules/eslint/lib/source-code/token-store/filter-cursor.js:37:17)
    at FilterCursor.getOneToken (.../node_modules/eslint/lib/source-code/token-store/cursor.js:49:21)
    at SourceCode.getFirstToken (.../node_modules/eslint/lib/source-code/token-store/index.js:264:11)
    at Program (.../no-commas.js:16:32)
    at ruleErrorHandler (.../node_modules/eslint/lib/linter/linter.js:1115:28)
    at .../node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (.../node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (.../node_modules/eslint/lib/linter/node-event-generator.js:297:26) {
  ruleId: 'no-commas',
  currentNode: Node {
    type: 'Program',
    loc: SourceLocation {
      start: Position { line: 1, column: 0 },
      end: Position { line: 1, column: 10 }
    },
    range: [ 0, 10 ],
    body: [],
    sourceType: 'script',
    comments: [
      {
        type: 'Line',
        value: ' comment',
        range: [ 0, 10 ],
        loc: {
          start: Position { line: 1, column: 0 },
          end: Position { line: 1, column: 10 }
        }
      }
    ],
    tokens: [],
    parent: null
  }
}
</pre>

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

The problem occurs when a file being linted <s>is empty or</s> contains only comments, which is not extremely uncommon in practice.

I checked the usages of `getFirstToken` and `getLastToken` in the code base and it seems that none of the core rule is affected by this problem, but since these methods are part of the public API, I am wondering if this issue should be fixed. If not, it would be great to have it documented that the callback argument could be undefined sometimes, although this does not seem to be the intended behavior.

### PR DESCRIPTION
**Pull request by fasttime**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

---

This PR fixes an issue with some `SourceCode` methods that is causing unexpected behavior when the source code contains no tokens but one or more comments. The [`SourceCode`](https://eslint.org/docs/latest/extend/custom-rules#contextgetsourcecode) type is part of the public API and is used by virtually all rules, although the issue described here should not affect any built-in rules.

The problem shows up when `sourceCode.getFirstToken()` or `sourceCode.getLastToken()` is called with the `Program` node (the AST object) of a source code than contains no tokens but one or more comments, i.e. a comment-only file.

The **expected** behavior is that `sourceCode.getFirstToken(ast)` or `sourceCode.getLastToken(ast)` should return `null` as per [documentation](https://github.com/eslint/eslint/blob/v8.35.0/lib/source-code/token-store/index.js#L253). If a `filter` callback is passed, the callback should never be called.

The **actual** case is that `sourceCode.getFirstToken(ast)` returns `undefined`. If a `filter` callback is passed, the callback is called with an `undefined` argument.

My original, incomplete analysis of this problem can be found in issue #16742.

Closes #16742 

#### What changes did you make? (Give an overview)

* Changed the handling of nodes without tokens in https://github.com/eslint/eslint/blob/main/lib/source-code/token-store/utils.js. In practice, this change only impacts `Program` nodes when the source code contains just comments.
* Added some unit tests to make sure that behavior does not change in other special cases.

#### Is there anything you'd like reviewers to focus on?

I am open to any suggestions.

### CODE REVIEW

**Comment by Rec0iL99** [comment]
Don't close. WIP: Looks like @fasttime is still working on this.

**Comment by fasttime** [comment]
Thanks @Rec0iL99! Actually I'm done with the fix, but I'm not particularly satisfied with my explanation of the problem and the solution. I realize it takes some patience to grasp how this code works and I would like to elaborate on my description and make it more accessible to reviewers.

File: lib/source-code/token-store/utils.js [hunk 1]
```diff
@@ -49,13 +49,13 @@ exports.getFirstIndex = function getFirstIndex(tokens, indexMap, startLoc) {
...
         const index = indexMap[startLoc - 1];
-        const token = (index >= 0 && index < tokens.length) ? tokens[index] : null;
+        const token = tokens[index];
 
         /*
          * For the map of "comment's location -> token's index", it points the next token of a comment.
          * In that case, +1 is unnecessary.
          */
-        if (token && token.range[0] >= startLoc) {
+        if (!token || token.range[0] >= startLoc) {
```
Comment (fasttime) [inline lib/source-code/token-store/utils.js:58]: If `token` is undefined, then `index` is already out of bounds, i.e. `index == tokens.length`. In this case, the returned cursor index should point after the last token, at `tokens.length`.
Refs:
- [ForwardTokenCursor](https://github.com/eslint/eslint/blob/27806358b5e1c4d37b63b1c61595e86ff03b5b42/lib/source-code/token-store/forward-token-cursor.js#L34)
- [ForwardTokenCommentCursor](https://github.com/eslint/eslint/blob/27806358b5e1c4d37b63b1c61595e86ff03b5b42/lib/source-code/token-store/forward-token-comment-cursor.js#L35)
- [BackwardTokenCursor](https://github.com/eslint/eslint/blob/27806358b5e1c4d37b63b1c61595e86ff03b5b42/lib/source-code/token-store/backward-token-cursor.js#L35)

File: lib/source-code/token-store/utils.js [hunk 2]
```diff
@@ -77,13 +77,13 @@ exports.getLastIndex = function getLastIndex(tokens, indexMap, endLoc) {
     }
     if ((endLoc - 1) in indexMap) {
         const index = indexMap[endLoc - 1];
-        const token = (index >= 0 && index < tokens.length) ? tokens[index] : null;
+        const token = tokens[index];
```
Comment (fasttime) [inline lib/source-code/token-store/utils.js:80]: Removed unnecessary check. As above, the program logic doesn't change.

File: lib/source-code/token-store/utils.js [hunk 3]
```diff
@@ -77,13 +77,13 @@ exports.getLastIndex = function getLastIndex(tokens, indexMap, endLoc) {
...
 
         /*
          * For the map of "comment's location -> token's index", it points the next token of a comment.
          * In that case, -1 is necessary.
          */
-        if (token && token.range[1] > endLoc) {
+        if (!token || token.range[1] > endLoc) {
```
Comment (fasttime) [inline lib/source-code/token-store/utils.js:86]: If `token` is undefined, then `tokens` is an empty list and `index` is `0`. In this case, the returned cursor index should point before the first token, at `-1`.
Refs:

- [BackwardTokenCursor](https://github.com/eslint/eslint/blob/27806358b5e1c4d37b63b1c61595e86ff03b5b42/lib/source-code/token-store/backward-token-cursor.js#L34)
- [BackwardTokenCommentCursor](https://github.com/eslint/eslint/blob/27806358b5e1c4d37b63b1c61595e86ff03b5b42/lib/source-code/token-store/backward-token-comment-cursor.js#L35)
- [ForwardTokenCursor](https://github.com/eslint/eslint/blob/27806358b5e1c4d37b63b1c61595e86ff03b5b42/lib/source-code/token-store/forward-token-cursor.js#L35)

File: lib/source-code/token-store/utils.js (hunk 1 above)
Comment (nzakas) [reply lib/source-code/token-store/utils.js:58]: I may be reading this wrong, but it seems like this change doesn't have any effect. I think it's just refactoring the boolean expression without changing the result. Can you double-check?

File: lib/source-code/token-store/utils.js (hunk 2 above)
Comment (nzakas) [reply lib/source-code/token-store/utils.js:80]: Same comment as above. :)

File: lib/source-code/token-store/utils.js (hunk 3 above)
Comment (nzakas) [reply lib/source-code/token-store/utils.js:86]: Same comment as above. :)

File: lib/source-code/token-store/utils.js [hunk 4]
```diff
@@ -49,13 +49,13 @@ exports.getFirstIndex = function getFirstIndex(tokens, indexMap, startLoc) {
     }
     if ((startLoc - 1) in indexMap) {
         const index = indexMap[startLoc - 1];
-        const token = (index >= 0 && index < tokens.length) ? tokens[index] : null;
+        const token = tokens[index];
```
[the remark this answers is not in the document]
Comment (fasttime) [reply lib/source-code/token-store/utils.js:52]: Probably that was the original idea, but `token` is not returned by this function, its value is only used once in the condition of an `if`-statement, where being `null` or `undefined` makes no difference.
This change was intended as an optimization, but we could revert it and the behavior would be still the same.

File: lib/source-code/token-store/utils.js (hunk 1 above)
Comment (fasttime) [reply lib/source-code/token-store/utils.js:58]: When `token` is `null` or `undefined`, the new expression evaluates to `true`, whereas the old expression would evaluate to a falsy (`null` or `undefined`) value. Other than this, the result is the same.

File: lib/source-code/token-store/utils.js (hunk 2 above)
Comment (fasttime) [reply lib/source-code/token-store/utils.js:80]: See https://github.com/eslint/eslint/pull/16889#discussion_r1127896093.

File: tests/lib/source-code/token-store.js [hunk 5]
```diff
@@ -654,6 +654,38 @@ describe("TokenStore", () => {
...
+
+        it("should retrieve a parent node's token if a node has no tokens", () => {
+            const code = "foo``";
+            const ast = espree.parse(code, { loc: true, range: true, tokens: true, comment: true, ecmaVersion: 6 });
+            const tokenStore = new TokenStore(ast.tokens, ast.comments);
+            const emptyTemplateElementNode = ast.body[0].expression.quasi.quasis[0];
+            const token = tokenStore.getFirstToken(emptyTemplateElementNode);
+
+            assert.strictEqual(token.value, "``");
+        });
```
Comment (mdjermanovic) [inline tests/lib/source-code/token-store.js:687]: If a node has no tokens, I think `getFirstToken` should return `null`. Either way, this doesn't seem to be a case where a node has no tokens, because that token does belong to the TemplateElement node (`ast.body[0].expression.quasi.quasis[0]` node).

File: tests/lib/source-code/token-store.js [hunk 6]
```diff
@@ -841,6 +873,38 @@ describe("TokenStore", () => {
...
+
+        it("should retrieve a parent node's token if a node has no tokens", () => {
+            const code = "foo``";
+            const ast = espree.parse(code, { loc: true, range: true, tokens: true, comment: true, ecmaVersion: 6 });
+            const tokenStore = new TokenStore(ast.tokens, ast.comments);
+            const emptyTemplateElementNode = ast.body[0].expression.quasi.quasis[0];
+            const token = tokenStore.getLastToken(emptyTemplateElementNode);
+
+            assert.strictEqual(token.value, "``");
+        });
```
Comment (mdjermanovic) [inline tests/lib/source-code/token-store.js:906]: Same as https://github.com/eslint/eslint/pull/16889#discussion_r1129299054

File: tests/lib/source-code/token-store.js (hunk 5 above)
Comment (nzakas) [reply tests/lib/source-code/token-store.js:687]: Agree.

File: lib/source-code/token-store/utils.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (nzakas) [reply lib/source-code/token-store/utils.js:52]: Ah gotcha. Makes sense.

**Review by nzakas — CHANGES_REQUESTED** [review]

File: tests/lib/source-code/token-store.js (hunk 5 above)
Comment (fasttime) [reply tests/lib/source-code/token-store.js:687]: @mdjermanovic you are correct! That node is not empty. I was fooled by [AST explorer](https://astexplorer.net/#/gist/02cd291223766f6e755f1208d5b137c2/117ef64f24b42ba58acb7c5cbc99b75a9cc43dd8) that shows the same value for both the `start` and `end` indices, probably because it uses an outdated version of Espree.
I added this test to make sure that I wouldn't inadvertently change the existing behavior, but now I think we can safely remove it because it's flawed.

File: tests/lib/source-code/token-store.js (hunk 6 above)
Comment (fasttime) [reply tests/lib/source-code/token-store.js:906]: Same as https://github.com/eslint/eslint/pull/16889#discussion_r1130033574.

File: lib/source-code/token-store/utils.js [hunk 7]
```diff
@@ -49,13 +49,18 @@ exports.getFirstIndex = function getFirstIndex(tokens, indexMap, startLoc) {
...
+
+        // If the mapped index is out of bounds, the returned cursor index will point after the end of the tokens array.
+        if (!token) {
```
Comment (fasttime) [inline lib/source-code/token-store/utils.js:55]: Alternatively, we could change this condition into `index >= tokens.length` and move the `const token` declaration after the `if`-block.

File: lib/source-code/token-store/utils.js [hunk 8]
```diff
@@ -77,13 +82,18 @@ exports.getLastIndex = function getLastIndex(tokens, indexMap, endLoc) {
     }
     if ((endLoc - 1) in indexMap) {
         const index = indexMap[endLoc - 1];
-        const token = (index >= 0 && index < tokens.length) ? tokens[index] : null;
+        const token = tokens[index];
+
+        // If the mapped index is out of bounds, the returned cursor index will point before the start of the tokens array.
+        if (!token) {
```
Comment (fasttime) [inline lib/source-code/token-store/utils.js:88]: Same as https://github.com/eslint/eslint/pull/16889/files#r1131283705. `index` can exceed the array length, but it should never be negative.

**Review by nzakas — APPROVED** [review]
LGTM, thanks! Just want @mdjermanovic to verify his suggestions.

File: lib/source-code/token-store/utils.js [hunk 9]
```diff
@@ -77,13 +82,18 @@ exports.getLastIndex = function getLastIndex(tokens, indexMap, endLoc) {
...
+            return -1;
+        }
```
Comment (mdjermanovic) [inline lib/source-code/token-store/utils.js:90]: Shouldn't we return `tokens.length - 1` (index of the last token) here? Hardcoded `-1` would always mean that there are no tokens before `endLoc`.

I couldn't construct an example where this would be observable with the default parser because it doesn't include trailing comments in the range of the Program node, but here's an example with `@typescript-eslint/parser`:

```js
const { RuleTester } = require('eslint');

const rule = {
    meta: {
        docs: { description: 'Require at least one token in the source code' },
        messages: { fail: 'no tokens found' },
    },
    create(context) {
        const sourceCode = context.getSourceCode();
        return {
            Program: node => {
                if (!sourceCode.getFirstToken(node)) {
                    context.report({ node, messageId: 'fail' });
                }
            }
        };
    }
};

new RuleTester().run(
    'must-have-tokens',
    rule,
    {
        valid:
        [
            {
                code: 'foo // comment',
                parser: require.resolve("@typescript-eslint/parser")
            }
        ],
        invalid: [],
    },
);

```

The expected result is that `sourceCode.getFirstToken` finds the token `foo`, but it doesn't because it looks for tokens between indexes `0` and `-1`.

Comment (fasttime) [reply lib/source-code/token-store/utils.js]: You are perfectly right @mdjermanovic, thanks for pointing me to a proper test case to disproof my incorrect assumption. I've applied the change you suggested and added a unit test to ensure the correct behavior when the root node includes a comment in its range.

It strikes me as a peculiarity of Espree that comments at the beginning and at the end of the source code are not included in the root node, while standalone comments are.

**Review by nzakas — APPROVED** [review]

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
