### PR TITLE
Fix: `indent` to not crash on empty files (fixes #3570)

### LINKED ISSUE #3570: Eslint 1.3.0 crashes on empty-ish file
You can reproduce this with the following tiny file:
```javascript
//
```
or
```javascript
/* */
```

I experimented a bit:
- No problem on empty file
- No problem if the file is just whitespace
- No problem if you add a single valid line of js
- Crash if the file consists only of comments

This is the stack trace
```
wli@oort:~/projects/activityhero$ ./node_modules/eslint/bin/eslint.js spec/javascripts/spec_helper.js 

/ah/activityhero/node_modules/eslint/lib/rules/indent.js:112
        var src = context.getSource(token, token.loc.start.column);
                                                ^
TypeError: Cannot read property 'loc' of undefined
    at getNodeIndent (/ah/activityhero/node_modules/eslint/lib/rules/indent.js:112:49)
    at EventEmitter.Program (/ah/activityhero/node_modules/eslint/lib/rules/indent.js:545:30)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (/ah/activityhero/node_modules/eslint/lib/eslint.js:815:25)
    at Controller.__execute (/ah/activityhero/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/ah/activityhero/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/ah/activityhero/node_modules/eslint/lib/eslint.js:808:24)
    at processText (/ah/activityhero/node_modules/eslint/lib/cli-engine.js:199:27)
    at processFile (/ah/activityhero/node_modules/eslint/lib/cli-engine.js:224:12)
    at /ah/activityhero/node_modules/eslint/lib/cli-engine.js:391:26
```

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

File: tests/lib/rules/indent.js [hunk 1]
```diff
@@ -46,6 +46,16 @@ ruleTester.run("indent", rule, {
     valid: [
         {
             code:
+            "// hi",
+            options: [2, {"VariableDeclarator": 1, "SwitchCase": 1}]
```
Comment (ilyavolodin) [inline tests/lib/rules/indent.js]: Why "SwitchCase"?

Comment (gyandeeps) [inline tests/lib/rules/indent.js]: I just copied the options. Doesnt make any different here.
