### PR TITLE
Fix: Extra paren check around object arrow bodies (fixes #5789)

### LINKED ISSUE #5789: Gratuitous parentheses in arrow function with object reference
**What version of ESLint are you using?** 2.7.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**
```js
  "eslintConfig": {
    "extends": "eslint:recommended",
    "parserOptions": { "ecmaVersion": 6 },
    "env": {
      "node": true,
      "es6": true
    },
    "rules": {
      "no-extra-parens": 2
    }
  }
```

**What did you do? Please include the actual source code causing the issue.**
`let test = a => ({ a: 1, b: 2, c: 3 }[a]);`

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
Gratuitous parentheses around expression (no-extra-parens)

### PR DESCRIPTION
**Pull request by btmills**

### CODE REVIEW

**Comment by platinumazure** [comment]
Since you called out a problem with nested member accesses in the issue, I would love to see a test for something like `() => {a:b}.a.c`.

**Comment by michaelficarra** [comment]
LGTM.

**Comment by btmills** [comment]
@platinumazure I just pushed an update that adds that test

**Comment by platinumazure** [comment]
Thanks. LGTM

File: lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -326,7 +326,7 @@ module.exports = function(context) {
 
         "ArrowFunctionExpression": function(node) {
             if (node.body.type !== "BlockStatement") {
-                if (node.body.type !== "ObjectExpression" && hasExcessParens(node.body) && precedence(node.body) >= precedence({type: "AssignmentExpression"})) {
+                if (sourceCode.getFirstToken(node.body).value !== "{" && hasExcessParens(node.body) && precedence(node.body) >= precedence({type: "AssignmentExpression"})) {
```
Comment (alberto) [inline lib/rules/no-extra-parens.js]: I'm not sure what the precedence part is supposed to warn on, but it's not covered by any test (I know because I was also implementing this).
