### PR TITLE
Fix: Make no-multi-spaces work for every case (fixes #1603, fixes #1659)

### LINKED ISSUE #1603: no-multi-spaces missed extra spaces between keywords, parens and brackets
I'm using `eslint v0.11.0-alpha.0` installed globally.

So far I identified these:

```javascript
fetchAsset: function•••••() {
    // ...
}

function receiveAsset ()•••••{
    // ...
}

if (asset)•••••{
    // ...
}
```

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7261907-no-multi-spaces-missed-extra-spaces-between-keywords-parens-and-brackets?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1659: no-multi-spaces does not allow non-last function param to be commented-out
Consider the following example:

```
function logAndCompare(a, b, c) {
    console.log(c);
    return a === b;
}
```
_listing 1.1 all params are used_

this is valid.
But if I want to temporarily comment-out the use of `c`, like this:

```
function logAndCompare(a, b, c) {
//    console.log(c);
    return a === b;
}
```
_listing 1.2: usage of the last param commented out_

I get noticed, that there's an unused param `c` and i get noticed by `no-unused-vars`. Reasonable.
Then I comment out the last param like this:

```
function logAndCompare(a, b/*, c*/) {
//    console.log(c);
    return a === b;
}
```
_listing 1.3: declaration of the last param commented out_

so I will remember what it was when I come back some days later to bring it back.

If I don't need `a` or `b` I will not get noticed by `no-unused-vars` since generally in JS the position of param does matter and it's required to define both `a` and `b` to be able to use `c`
If I ever wanted to comment out `b` the order of params will not be the same and when my function gets called `c` is now `b`.

For the AngularJS environment however position of function params is not as important as their names. With this in mind let's say my function is a service (i'm not using the annotated form on purpose - there's [ngAnnotate](https://github.com/olov/ng-annotate) for that):

```
angular.module('foo').service('fooService', function (aService, bService, cService) {
    aService.doAStuff();
    bService.doBStuff();
    cService.doCStuff();
})
```
_listing 2.1: all injected services used_

If I want to comment out `aService` I'm aware that 'no-unused-vars' won't warn me:

```
angular.module('foo').service('fooService', function (aService, bService, cService) {
//    aService.doAStuff();
    bService.doBStuff();
    cService.doCStuff();
})
```
_listing 2.2: not all injected services used_

What I'd like to do (to better emphasise that I'm aware service `aService` is no longer used but it's most probable it will be back) is to do this:

```
angular.module('foo').service('fooService', function (/*aService, */bService, cService) {
//    aService.doAStuff();
    bService.doBStuff();
    cService.doCStuff();
})
```
_listing 2.3: declaration of `aService` removed._

IT does not look like a good idea but if my `fooService` has many services with long names injected and I want to both have my diffs as small as they can be and have those injected services in a particular order but not exceed the limit of line length I get stuck.

```
angular.module('foo').service('fooService', function (aServiceWithLongerName, bServiceWithLongerName, 
                                                      cService) {
    aService.doAStuff();
    bService.doBStuff();
    cService.doCStuff();
})
```
_listing 2.4: multiline induced by line length limit_

```
angular.module('foo').service('fooService', function (bServiceWithLongerName, cService) {
//    aService.doAStuff();
    bService.doBStuff();
    cService.doCStuff();
})
```
_listing 2.4: service removed: longer and less meaningful diff_

In terms of "Vanilla" JS this gets all messed up - I know. But in AngularJS this is perfectly valid and can even be considered a good practice.
I cannot do this though because `no-multi-spaces` fails.

I created 3 cases: https://github.com/jrencz/eslint/blob/jrencz/issue/comment/tests/lib/rules/no-multi-spaces.js#L49-51
Only the last one passes the tests. I suppose this is a bug and all of them are valid in terms of syntax but such case only makes sense when AngularJS is used (or the order does not matter for some other reason)

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7797329-no-multi-spaces-does-not-allow-non-last-function-param-to-be-commented-out?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**
This was an absolute monster to work through and it's still not quite there. One edge case remaining. Just posting to share.

I had to create a map of where all tokens are, and that subsequently slowed things down a bit. I think the slowdown is worth it for the tradeoff.

$ npm run perf

> eslint@0.12.0 perf c:\Users\Nicholas\projects\personal\jscheck
> node Makefile.js perf

```
# Before

CPU Speed is 3093 with multiplier 7500000
Performance Run #1:  1501.513292ms
Performance Run #2:  1516.6144359999998ms
Performance Run #3:  1522.233913ms
Performance Run #4:  1537.468143ms
Performance Run #5:  1510.7205079999999ms
Performance budget ok:  1516.6144359999998ms (limit: 2424.8302618816683ms)

# After

CPU Speed is 3093 with multiplier 7500000
Performance Run #1:  1573.712675ms
Performance Run #2:  1545.923181ms
Performance Run #3:  1556.752278ms
Performance Run #4:  1558.050048ms
Performance Run #5:  1550.235287ms
Performance budget ok:  1556.752278ms (limit: 2424.8302618816683ms)
```

### CODE REVIEW

**Comment by gcochard** [comment]
This is exactly what I was thinking was needed, but I didn't have the time necessary for such a large refactor. Looks like a great start!

File: lib/eslint.js [hunk 1]
```diff
@@ -738,6 +743,10 @@ module.exports = (function() {
         return currentTextLines;
     };
 
+    api.getAllComments = function() {
```
Comment (nzakas) [inline lib/eslint.js]: Needs JSDoc comment

**Comment by nzakas** [comment]
Okay, should be working now.

File: lib/token-store.js [hunk 2]
```diff
@@ -64,6 +65,11 @@ module.exports = function(tokens) {
         range = tokens[index].range;
         starts[range[0]] = index;
         ends[range[1]] = index;
+
+        // allows fast lookup of any source index
+        for (var j = range[0]; j <= range[1]; j++) {
+            ranges[j] = index;
+        }
```
Comment (btmills) [inline lib/token-store.js]: is this the main source of the perf hit you're seeing? I'm going to look today or tomorrow into possibly storing tokens in a range tree.

File: lib/rules/no-multi-spaces.js [hunk 3]
```diff
@@ -7,191 +7,42 @@
...
-                    // of the node and the following comma or end brace.
-                    while (
-                        tokenIndex + 1 < tokens.length &&
-                        tokens[tokenIndex + 1].value !== ","
-                    ) {
-                        ++tokenIndex;
-                    }
-                }
-                ++elementIndex;
+            if (comment.range[0] <= index && index <= comment.range[1]) {
```
Comment (btmills) [inline lib/rules/no-multi-spaces.js]: Shouldn't the upper bound be exclusive?

**Comment by btmills** [comment]
Philosophical question, not about the code: since this should conflict with key-spacing in its "align" mode, if somebody asks, is the answer that these rules have become mutually exclusive? I'm not advocating exceptions here - that sounds excessively complex.

I have one concern in the code about an upper bound. Other than that, LGTM.

No need to hold this PR until I can investigate a range tree - I think the odds are low it'll be anything but slower. I'll file an issue if it turns out to be an improvement.

**Comment by nzakas** [comment]
Good question . We've always shied away from mutually exclusive rules because they are confusing. That said, I'm not sure how this rule could be made aware of exceptions in other rules. :-/

File: lib/rules/no-multi-spaces.js (hunk 3 above)
Comment (nzakas) [inline lib/rules/no-multi-spaces.js]: I'm not sure. I thought the range on nodes was inclusive, so I was mimicking that. Is the range exclusive?

File: lib/token-store.js (hunk 2 above)
Comment (nzakas) [inline lib/token-store.js]: Yeah, this is the source.

File: lib/rules/no-multi-spaces.js (hunk 3 above)
Comment (btmills) [inline lib/rules/no-multi-spaces.js]: Typically start is inclusive and right is exclusive. For example, in `a;`, the identifier would have a range of [0, 1), and the semicolon's range would be [1, 2).

Comment (nzakas) [inline lib/rules/no-multi-spaces.js]: Ah okay, I misunderstood. I'll change it.

**Comment by btmills** [comment]
Since mutual exclusivity is undesirable, I'll throw out an idea. What if there were a list of excepted node types, such that if the most recent ancestor containing a whitespace range is in the excepted list, it doesn't report? For example:

```js
({
	a: b
})
```
If `Property` were excepted, the space between the colon and the property value would be contained within the `Property` node, but not the key or value.

This is just a brainstorm. No idea how practical it is. But I think that would solve key-spacing at least.

**Comment by nzakas** [comment]
We're not really dealing with the AST in this rule, it's just strings and tokens. We'd need a way to match a range index with an AST node.

**Comment by btmills** [comment]
> We'd need a way to match a range index with an AST node.

Rather than throwing a bunch of pseudocode here, I built such a way in #1738 :smile:

File: lib/rules/no-multi-spaces.js [hunk 4]
```diff
@@ -7,191 +7,42 @@
 "use strict";
```
Comment (btmills) [inline lib/rules/no-multi-spaces.js]: I just noticed that your name doesn't appear here, even though you completely rewrote the rule.

Comment (nzakas) [inline lib/rules/no-multi-spaces.js]: Heh, you're right. :)

**Comment by nzakas** [comment]
@btmills want to give this one last once-over? I think I addressed all the comments.

File: lib/rules/no-multi-spaces.js (hunk 3 above)
Comment (btmills) [inline lib/rules/no-multi-spaces.js]: The upper bound is still inclusive here. However, since it's only off by one, and `index` is coming from `pattern.lastIndex`, and a match will have a length of at least two characters, it should still function as intended..

**Comment by btmills** [comment]
Aha! The ranges aren't necessary! I think. Does this logic hold?

A space sequence can end one of five ways:

1. It reaches the end of the line.
This rule is not designed to handle end-of-line spaces. Nothing should be reported.

1. It reaches the start of a comment.
The `isIndexInComment` check will find that `pattern.lastIndex` is the starting index of the comment. Nothing will be reported.

1. The space sequence is within a comment.
Again, `isIndexInComment` will prevent reporting.

1. The space sequence is within a string or template literal.
Nothing should be reported.

1. It encounters the start of a token.
In this case, `pattern.lastIndex` will be exactly the starting index of some token. The rule should report an error.

If I'm not missing anything, then the rule should only report when it encounters a token starting at `pattern.lastIndex`. Therefore, we replace `getTokenByRangeIndex` with a new method, `getTokenStartingAtIndex`, consisting simply of `return tokens[starts[index]] || null;`. The rule warns if and only if `getTokenStartingAtIndex(pattern.lastIndex)` returns a token. No more retrieval from the middle of a token's range, and no more need to assemble the map of ranges.

[I implemented exactly this strategy](https://github.com/eslint/eslint/commit/7fedd81fd087548d0a72be24da4d16eb98e6c0fc) on top of this PR and pushed it to [a new branch](https://github.com/eslint/eslint/tree/getTokenStartingAtIndex). The existing tests all pass. Can you think of any new ones that might cause it to fail?

**Comment by nzakas** [comment]
Nice, that's much simpler. Want to open a PR?
