### PR TITLE
Update: fix indent behavior on template literal arguments (fixes #9061)

### LINKED ISSUE #9061: Unintended indent for multiline template string argument combined with another multiline argument
**Tell us about your environment**

* **ESLint Version:** 4.3.0
* **Node Version:** 8.1.3
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?**

I tried both default and babel-eslint. They're giving me same result.

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

{
    "env": {
        "es6": true,
        "node": true
    },
    "extends": [
        "eslint:recommended"
    ],
    "rules": {
        "indent": ["error", 4]
    }
}

```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js

const f = (first, second) => {
    return second;
};

// works for multiline template strings
f(`
    multiline
    template
    string
`, `
    multiline
    template
    string
`);

// works for multiline objects
f({
    foo: 'foo',
    bar: 'bar',
}, {
    foo: 'foo',
    bar: 'bar',
});

// doesn't work for multiline template string and multiline object
f(`
    multiline
    template
    string
`, {
    foo: 'foo',
    bar: 'bar',
});


```

**What did you expect to happen?**

I expected all of the three examples will pass.

**What actually happened? Please include the actual, raw output from ESLint.**

```
  31:1  error  Expected indentation of 8 spaces but found 4  indent
  32:1  error  Expected indentation of 8 spaces but found 4  indent
  33:1  error  Expected indentation of 4 spaces but found 0  indent
```

I believe the eslint fix is incorrect

```diff
 const f = (first, second) => {
     return second;
 };
 
 // works for multiline template strings
 f(`
     multiline
     template
     string
 `, `
     multiline
     template
     string
 `);

 // works for multiline objects
 f({
     foo: 'foo',
     bar: 'bar',
 }, {
     foo: 'foo',
     bar: 'bar',
 });

 // doesn't work for multiline template string and multiline object
 f(`
     multiline
     template
     string
 `, {
-    foo: 'foo',
-    bar: 'bar',
-});
+        foo: 'foo',
+        bar: 'bar',
+    });
```

Could you please confirm this is an unintended behaviour? Thank you.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/9061)

**What changes did you make? (Give an overview)**

This updates the `indent` rule to handle multiline template arguments correctly to fix the issue described in https://github.com/eslint/eslint/issues/9061.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: lib/rules/indent.js [hunk 1]
```diff
@@ -442,6 +442,7 @@ class OffsetStorage {
                 const offset = (
                     offsetInfo.from &&
                     offsetInfo.from.loc.start.line === token.loc.start.line &&
+                    !/^\s*?\n/.test(token.value) &&
```
Comment (not-an-aardvark) [inline lib/rules/indent.js]: This addition was necessary due to JSX behavior. When parsing code like this:

```js
<a>
    <b>
    </b>
</a>
```

There is a hidden `JSXText` (or `Literal`) token between `<a>` and `<b>`, containing a newline followed by whitespace. The `indent` rule had previously been relying on the old template literal behavior to ensure that the `<b>` tag would get indented properly.

In other words, the `indent` rule would previously indent the above code in effectively the same manner as the below code:

```js
a(`
    `, { // (this object is like the `b` tag)
    }, `
`);
```

However, by fixing this bug it would no longer possible to treat the two pieces of code in the same way anymore. The fix is to modify the token collapsing behavior (which checks whether two tokens are on the same line) to consider two tokens to be on separate lines if the second token starts with a newline character.
