### PR TITLE
Fix: Allowing u flag in regex to properly lint no-empty-character-class rule (Fixes #2679)

### LINKED ISSUE #2679: no-empty-character-class rule not working well with unicode flag (ES6)
The `no-empty-character-class` rule gives a very confusing error whenever it encounters a regular expression using the ES6 `u` flag. (for unicode support)

To be clear, my regular expression does _not_ have an empty character class, and if I remove the `u` flag, it is not treated as an error anymore.

It looks like this is caused by the fact that the only recognized flags are `gimy`. (see [code](https://github.com/eslint/eslint/blob/master/lib/rules/no-empty-character-class.js#L21)) I presume adding `u` to the list would fix this problem, but not sure if that should be conditionally added with ES6 support.

This is using the latest version of ESLint. (ie: `0.22.1`)

### PR DESCRIPTION
**Pull request by dominicbarnes**
This adds `u` to the list of allowed flags used by the regex that tests the `no-empty-character-class` rule. (since `y` is already in the list, adding `u` was trivial)

A test has been included as well. (which also bumps the "coverage" to include the `y` flag as well)

I've already signed the CLA, so I think I've done everything I need to do. Let me know if there's anything else you need from me!

(fixes #2679)

### CODE REVIEW

**Comment by nzakas** [comment]
Yup, this looks good. Thanks!

File: lib/rules/no-empty-character-class.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ plain-English description of the following regexp:
 4. `[gimy]*`: optional regexp flags
```
Comment (michaelficarra) [inline lib/rules/no-empty-character-class.js]: This description needs to be updated.
