### PR TITLE
fix: load plugins in the CLI in flat config mode

### LINKED ISSUE #18159: Bug: CLI option `--plugin` cannot load CommonJS plugin in flat config mode
### Environment

Node version: v21.6.2
npm version: v10.2.4
Local ESLint version: v9.0.0-beta.1 (Currently used)
Global ESLint version: Not found
Operating System: darwin 23.3.0

### What parser are you using?

Default (Espree)

### What did you do?

In the eslint repo directory, I used the CLI to run a single rule from a plugin on a file:

```shell
npx eslint --no-config-lookup --plugin n --rule 'n/no-sync: error' --parser-options 'sourceType: commonjs' Makefile.js
```

### What did you expect to happen?

The command should report problems in the specified file.
For comparison, this is the output I see in a zsh terminal when using eslintrc config:

```console
$ ESLINT_USE_FLAT_CONFIG=false npx eslint --no-eslintrc --plugin n --rule 'n/no-sync: error' --parser-options 'ecmaVersion: latest, sourceType: commonjs' Makefile.js

.../Makefile.js
   77:49  error  Unexpected sync method: 'readFileSync'   n/no-sync
  103:22  error  Unexpected sync method: 'readFileSync'   n/no-sync
  296:5   error  Unexpected sync method: 'writeFileSync'  n/no-sync
  401:30  error  Unexpected sync method: 'readFileSync'   n/no-sync
  424:28  error  Unexpected sync method: 'readdirSync'    n/no-sync
  821:13  error  Unexpected sync method: 'execFileSync'   n/no-sync
  821:13  error  Unexpected sync method: 'execFileSync'   n/no-sync
  825:9   error  Unexpected sync method: 'execFileSync'   n/no-sync

✖ 8 problems (8 errors, 0 warnings)

(node:10816) ESLintRCWarning: You are using an eslintrc configuration file, which is deprecated and support will be removed in v10.0.0. Please migrate to an eslint.config.js file. See https://eslint.org/docs/latest/use/configure/migration-guide for details.
(Use `node --trace-warnings ...` to show where the warning was created)
```

### What actually happened?

The command fails with an error for not finding the specified rule:

```console
$ npx eslint --no-config-lookup --plugin n --rule 'n/no-sync: error' --parser-options 'sourceType: commonjs' Makefile.js

(node:3528) ESLintIgnoreWarning: The ".eslintignore" file is no longer supported. Switch to using the "ignores" property in "eslint.config.js": https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files
(Use `node --trace-warnings ...` to show where the warning was created)

Oops! Something went wrong! :(

ESLint: 9.0.0-beta.1

TypeError: Key "rules": Key "n/no-sync": Could not find "no-sync" in plugin "n". Did you mean "@/no-sync"?
    at throwRuleNotFoundError (.../eslint/lib/config/rule-validator.js:66:11)
    at RuleValidator.validate (.../eslint/lib/config/rule-validator.js:147:17)
    at [finalizeConfig] (.../eslint/lib/config/flat-config-array.js:211:23)
    at FlatConfigArray.getConfig (.../eslint/node_modules/@humanwhocodes/config-array/api.js:938:55)
    at FlatConfigArray.isFileIgnored (.../eslint/node_modules/@humanwhocodes/config-array/api.js:962:15)
    at .../eslint/lib/eslint/eslint-helpers.js:514:38
    at Array.forEach (<anonymous>)
    at findFiles (.../eslint/lib/eslint/eslint-helpers.js:503:11)
    at async ESLint.lintFiles (.../eslint/lib/eslint/eslint.js:834:27)
    at async Object.execute (.../eslint/lib/cli.js:442:23)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-h9q29a?file=index.js

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

This issue only occurs when a CommonJS plugin is loaded from the CLI in flat config. In my understanding, the problem is that when a CommonJS module is loaded with the dynamic `import` syntax, it gets transpiled into an ESM module which is only guaranteed to have a `default` export.

https://github.com/eslint/eslint/blob/bde51055530d4a71bd9f48c90ed7de9c0b767d86/lib/cli.js#L162

So the rules exported by the CommonJS plugin will be accessible as `default.rules` from the resolved module object. This is in contrast with the way ESM modules are loaded, where all exports are made available as top level properties.

### PR DESCRIPTION
**Pull request by fasttime**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #18159 

#### What changes did you make? (Give an overview)

The changes in this PR relate to how the CLI option `--plugin` works in flat config mode:

* When a plugin is loaded, the `default` property of the imported module is now used. This aligns the plugin loading behavior with eslintrc and with the recommendations for creating a custom plugin.
* A specific error message is printed if a plugin has no default export.
* Multiple plugins are loaded concurrently.

This PR also adds unit tests and a new note to the custom plugins docs.

#### Is there anything you'd like reviewers to focus on?

Some of the new unit tests in this PR, the ones with CommonJS plugins, can be generalized to cover the eslintrc case. Do we want to add tests for eslintrc to make sure that the behavior in flat config mode is similar?

### CODE REVIEW

File: lib/cli.js [hunk 1]
```diff
@@ -47,6 +48,30 @@ const mkdir = promisify(fs.mkdir);
...
+ * @param {{ "import": (name: string) => Promise<any> }} importer An object with an `import` method called once for each plugin.
+ * @param {string[]} pluginNames The names of the plugins to be loaded, with or without the "eslint-plugin-" prefix.
+ * @returns {Promise<Record<string, Plugin>>} A mapping of plugin short names to implementations.
+ */
+async function loadPlugins(importer, pluginNames) {
+    const plugins = {};
+
+    await Promise.all(pluginNames.map(async pluginName => {
+
+        const shortName = naming.getShorthandName(pluginName, "eslint-plugin");
```
Comment (JoshuaKGoldberg) [inline lib/cli.js:62]: [Style] Small thing: `shortName` isn't used until after the `if`. I think it'd make the code just a bit more clear to move the variable down a few lines. (Is this too nitpicky a comment?)

File: lib/cli.js [hunk 2]
```diff
@@ -47,6 +48,30 @@ const mkdir = promisify(fs.mkdir);
...
+        const longName = naming.normalizePackageName(pluginName, "eslint-plugin");
+        const module = await importer.import(longName);
+
+        if (!("default" in module)) {
+            throw Error(`"${longName}" cannot be imported because it does not provide a default export`);
```
Comment (JoshuaKGoldberg) [inline lib/cli.js:67]: [Question] Elsewhere outside of `.md` files and `tests/`, it's always `throw new Error` - not `throw Error`. I.e. [`no-throw-literal`](https://eslint.org/docs/latest/rules/no-throw-literal) has been adhered to. Is it intentional that this doesn't?

```suggestion
            throw new Error(`"${longName}" cannot be imported because it does not provide a default export`);
```

**Review by JoshuaKGoldberg — DISMISSED** [review]
LGTM! Just a few small questions/suggestions, nothing blocking IMO.

+1 on the tests, nice and thorough!

File: docs/src/extend/plugins.md [hunk 3]
```diff
@@ -36,6 +36,8 @@ export default plugin;
 module.exports = plugin;
 ```
 
+If you plan to distribute your plugin as an npm package, make sure that the module that exports the plugin object is the default export of your package. This will enable ESLint to import the plugin when it is specified in the command line in the `--plugin` option.
```
Comment (JoshuaKGoldberg) [inline docs/src/extend/plugins.md:39]: [Docs] Maybe wrap <code>`--plugin` option</code> in a link to https://eslint.org/docs/latest/use/command-line-interface#--plugin?

File: lib/cli.js (hunk 2 above)
Comment (fasttime) [reply lib/cli.js]: I think it's just a matter of style. `throw Error()` is the same as `throw new Error()`. `no-throw-literal` does not flag it ([playground](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXRocm93LWxpdGVyYWw6IFwiZXJyb3JcIiAqL1xuXG50aHJvdyBFcnJvcihcImZvb1wiKTsiLCJvcHRpb25zIjp7ImVudiI6e30sInJ1bGVzIjp7fSwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9LCJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJtb2R1bGUifX19)). In my repos, I have a rule that reports unnecessary `new` expressions, so I have a tendency to write just `Error()`. `eslint-plugin-unicorn` has [this rule](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/throw-new-error.md) that requires `new Error` in throw statements.

File: docs/src/extend/plugins.md (hunk 3 above)
Comment (fasttime) [reply docs/src/extend/plugins.md]: Thanks for the suggestions, it's all done in b138d4682abaeb313e74c4ef22ffc3477a7310cf.

File: lib/cli.js [hunk 4]
```diff
@@ -47,6 +48,32 @@ const mkdir = promisify(fs.mkdir);
 const stat = promisify(fs.stat);
 const writeFile = promisify(fs.writeFile);
 
+/**
+ * Loads plugins with the specified names.
+ * @param {{ "import": (name: string) => Promise<any> }} importer An object with an `import` method called once for each plugin.
+ * @param {string[]} pluginNames The names of the plugins to be loaded, with or without the "eslint-plugin-" prefix.
```
Comment (aladdin-add) [inline lib/cli.js:54]: It's fine to allow both, but we start recommending using the full package name. In the long run, eslintrc will go away and plugin names are not enforced to be `eslint-plugin-xxx`.

**Comment by mdjermanovic** [comment]
> Some of the new unit tests in this PR, the ones with CommonJS plugins, can be generalized to cover the eslintrc case. Do we want to add tests for eslintrc to make sure that the behavior in flat config mode is similar?

I think there's no need to add more tests for eslintrc since there are already some tests and the way the `--plugin` option is used and the plugins are loaded in eslintrc mode is entirely different.

File: tests/lib/cli.js [hunk 5]
```diff
@@ -1649,6 +1649,105 @@ describe("cli", () => {
             });
         });
 
+        describe("flat Only", () => {
```
Comment (mdjermanovic) [inline tests/lib/cli.js:1652]: This was probably accidentally inserted in "eslintrc Only".

```
  cli
    eslintrc Only
      flat Only
        `--plugin` option
          √ should load a plugin from a CommonJS package (41ms)
          √ should load a plugin from an ESM package
          √ should load multiple plugins
          √ should resolve plugins specified with 'eslint-plugin-'
          √ should resolve plugins in the parent directory's node_module subdirectory
          √ should fail if a plugin is not found
          √ should fail if a plugin throws an error while loading
          √ should fail to load a plugin from a package without a default export
```

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks! 👍

File: lib/cli.js [hunk 6]
```diff
@@ -47,6 +48,32 @@ const mkdir = promisify(fs.mkdir);
...
+async function loadPlugins(importer, pluginNames) {
+    const plugins = {};
+
+    await Promise.all(pluginNames.map(async pluginName => {
+
+        const longName = naming.normalizePackageName(pluginName, "eslint-plugin");
+        const module = await importer.import(longName);
+
+        if (!("default" in module)) {
+            throw new Error(`"${longName}" cannot be imported because it does not provide a default export`);
```
Comment (mdjermanovic) [inline lib/cli.js:66]: This sounds like the package doesn't provide a default export, but it does while the problem is that its default export doesn't have "default" name exported. Maybe something like this?

```suggestion
            throw new Error(`"${longName}" cannot be used with the `--plugin` option because its default module does not provide `default` export`);
```

File: tests/lib/cli.js (hunk 5 above)
Comment (fasttime) [reply tests/lib/cli.js]: Missed that, thanks! It's fixed in 34e02cb09ca0bb23d584f3ba2487715f653dd78f.

File: lib/cli.js (hunk 6 above)
Comment (fasttime) [reply lib/cli.js]: Updated in e6a5f4e142d0f54807c34bf0ac7fb18a2e5c4e8e.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
