### PR TITLE
Breaking: ignore absolute paths relative to .eslintignore (fixes #2365)

### LINKED ISSUE #2365: Make .eslintignore work like .gitignore [$100]
The project tree looks like
```
/home/user/my-project
├── .eslintignore
└── foo.js
```

.eslintignore
```
*/
*.js
```

File `foo.js` is expectedly ignored when running `eslint foo.js`
```
/home/user/my-project $ eslint foo.js 

foo.js
  0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override

✖ 1 problem (0 errors, 1 warning)
```

However, file `foo.js` is unexpectedly linted when running with full path specified: `eslint /home/user/my-project/foo.js`
```
/home/user/my-project $ eslint /home/user/my-project/foo.js

/home/user/my-project/foo.js
  1:0  error  Infix operators must be spaced                 space-infix-ops
  1:0  error  "a" is not defined                             no-undef
  1:1  error  Newline required at end of file but not found  eol-last
  1:5  error  Missing semicolon                              semi

✖ 4 problems (4 errors, 0 warnings)
```

Expected behavior: `/home/user/my-project/foo.js` is also ignored.

<bountysource-plugin>
---
There is a **[$100 open bounty](https://www.bountysource.com/issues/11908402-make-eslintignore-work-like-gitignore?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gronke**
fixes #2365 

When a `.eslintignore` file is loaded by `IgnoredPaths` lib the absolute path of the file is stored as `IgnoredPaths.baseDir`, that is later used for absolute path prefix for file matches.

### CODE REVIEW

**Comment by domenic** [comment]
Does this fix all the other issues that were rolled in to #2365, e.g.  #3707 or #3898? My understanding of #2365 was that the intent was to switch to [ignore](https://www.npmjs.com/package/ignore).

**Comment by gronke** [comment]
- Will add more tests for the other related issues. They'll also help replacing minimatch with ignore.
- changing PR status to work-in-progress

**Comment by domenic** [comment]
Awesome, thank you!!

**Comment by gronke** [comment]
Looks like both other issues can be fixed with a tiny modification.

Switching to [ignore](https://www.npmjs.com/package/ignore) looks straightforward, but would be nice to use as replacement for the whole [ignored-paths.js](https://github.com/eslint/eslint/blob/master/lib/ignored-paths.js) library. But that would cause a bigger interface change and affect more files than this bugfix. 

@domenic are you sure with the switch to ignore?

Would be great if somebody reviews the tests.

**Comment by domenic** [comment]
> are you sure with the switch to ignore?

I'm just the bounty person, not the maintainer. Hopefully one of them will comment. I was basing that impression on https://github.com/eslint/eslint/issues/2365#issuecomment-135823297 (which says it's a goal to make eslintignore act just like gitnigore) and https://github.com/eslint/eslint/issues/2365#issuecomment-135981128 (which implies the ignore package is a good way of doing that).

**Comment by nzakas** [comment]
Thanks, a few notes:

1. This is a breaking change, so please update the commit message to say "Breaking:" instead of "Fix:"
1. Can you please sign our CLA? http://ESLint.org/cla
1. This issue was already being worked on by @julianlaval (see comments on the issue), so I'd like to make sure he's OK with this.
1. The goal of this issue is to fully replace `ignored-paths` with `ignore`, so we'd need to have that to accept this PR to close the issue.

**Comment by JulianLaval** [comment]
Am currently swamped and haven't begun any work on the issue. Feel free to take over! :+1:

**Comment by gronke** [comment]
- [x] CLA signed
 - [x] branch renamed
 - [x] receive Julian's blessing
 - [x] replace minimatch with node-ignore

Note: `lib/ignored-paths.js` still exists and is used to wrap an interface for tests and cli-utils around node-ignore.

**Comment by gronke** [comment]
Added a compatibility warning when using `**` globstars to ignore files.

**Comment by gronke** [comment]
There is [a branch that fixes the issues, but still uses minimatch](https://github.com/eslint/eslint/compare/master...gronke:issue-2365-minmatch) in case you prefer patching the absolute path handling first and doing the migration from `minimatch` to `ignore` later, since it can break the globstars syntax.

File: lib/ignored-paths.js [hunk 1]
```diff
@@ -21,42 +22,18 @@ debug = debug("eslint:ignored-paths");
 //------------------------------------------------------------------------------
 
 var ESLINT_IGNORE_FILENAME = ".eslintignore";
+var DEFAULT_IGNORE_PATTERNS = [
+    "/node_modules/",
+    ".git/",
```
Comment (nzakas) [inline lib/ignored-paths.js]: Can't we just ignore all dot-directories and files by default? Otherwise, this becomes a maintenance issue as we need to keep updating.

File: lib/ignored-paths.js [hunk 2]
```diff
@@ -92,21 +69,81 @@ function IgnoredPaths(patterns) {
...
-    return new IgnoredPaths(patterns);
+    return this;
+
+};
+
+/**
+ * Get list ignore rules
+ * @returns {IgnoreRule} array, list of ignore patterns
+ */
+IgnoredPaths.prototype.getRules = function() {
```
Comment (nzakas) [inline lib/ignored-paths.js]: What's the purpose of this method?

File: lib/ignored-paths.js [hunk 3]
```diff
@@ -92,21 +69,81 @@ function IgnoredPaths(patterns) {
...
-        patterns = loadIgnoreFile(options.ignorePath || findIgnoreFile());
-    } else {
-        patterns = [];
-    }
+/**
+ * Load wrapper for IgnorePaths instances
+ * @param {Object} options object containing 'ignore' and 'ignorePath' properties
+ * @returns {void}
+ */
+IgnoredPaths.prototype.loadFile = function(options) {
```
Comment (nzakas) [inline lib/ignored-paths.js]: Why is this method exposed?

File: lib/ignored-paths.js [hunk 4]
```diff
@@ -92,21 +69,81 @@ function IgnoredPaths(patterns) {
...
+    ignoredPaths.loadFile(options);
+    return ignoredPaths;
+};
 
-    options = options || {};
+/**
+ * Reset IgnoredPaths
+ * @returns {void}
+ */
+IgnoredPaths.prototype.reset = function() {
```
Comment (nzakas) [inline lib/ignored-paths.js]: Why is this method necessary?

Comment (gronke) [inline lib/ignored-paths.js]: Will remove. It was used in a unit test once, but instead of a reset creating a new instance is the better way.

File: lib/ignored-paths.js (hunk 2 above)
Comment (gronke) [inline lib/ignored-paths.js]: The list of rules was [used by cli-engine as ignore pattern](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L510) to reduce the number of `executeOnFile` calls. My concern was to expose an interface [similar to direct access to the pattern list](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L499). Using an object with `name` property looked reasonable, so only one line had to be changed in external files.

The better approach in my opinion would be to use ignore's `ig.filter(paths);` method on all glob matches at once (without passing in an ignore list) and then [run executeOnFile without using IgnoredPaths](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L558).

The second reason this method is exposed are unit tests. We need access to the raw rules for testing, but the linter complains about the _ in `this.ig._rules` :smirk_cat: That's why the next two lines exist.

If we go with the changes to `cli-engine.js`, this method can be moved to a function in the tests file.

File: lib/ignored-paths.js (hunk 3 above)
Comment (gronke) [inline lib/ignored-paths.js]: Creating a new instance of IgnoredPaths can be achieved without loading a file. Will replace `IgnoredPaths.load(options)` (that returns a new instance) with always using `new IgnoredPath(options)` instead, so that this function can stay private.

File: lib/ignored-paths.js (hunk 1 above)
Comment (gronke) [inline lib/ignored-paths.js]: Good call! Will do.

**Comment by gronke** [comment]
@nzakas [your comment about DEFAULT_IGNORE_PATTERNS](https://github.com/eslint/eslint/pull/3948#discussion_r40691649) was not addressed yet. What's your opinion on just ignoring `node_modules/` like in the current default ignore patterns?

**Comment by nzakas** [comment]
I'd prefer to only hardcode node_modules as it is today. However, we should also ignore dot files and directories as we do today.

**Comment by ilyavolodin** [comment]
@nzakas We have a pending commit to also ignore `bower_components` as well. That should probably be included.

**Comment by gronke** [comment]
@ilyavolodin I use eslint in a subdirectory of `bower_components` myself, so enforcing this directory to be ignored would break my setup. I'd feel comfortable with an eslint option that overrides default ignores. Otherwise there is no way of bypassing them in special cases.

**Comment by gronke** [comment]
- always ignore `node_modules/`
- dotfiles are ignored [only when the IgnoredPaths.dotfiles option is not set to true](https://github.com/gronke/eslint/blob/issue-2365/lib/ignored-paths.js#L63) (that is used by cli-engine to [differentiate between explicitly passed in files](https://github.com/gronke/eslint/blob/issue-2365/tests/lib/cli-engine.js#L317-L332))

**Comment by nzakas** [comment]
@gronke adding bower_components has been on the roadmap for a while now. Please comment on #3550 if that's a problem.

**Comment by gronke** [comment]
@nzakas https://github.com/eslint/eslint/blob/master/tests/lib/cli-engine.js#L317 test if a file that has an absolute path as pattern will be linted, but https://github.com/gronke/eslint/blob/issue-2365/tests/lib/cli-engine.js#L326 adds a test that this does not apply to glob matches.

I can merge https://github.com/JulianLaval/eslint/commit/0fa37d84cd497d2f058239f5509dbb10b8ccf0e9 that adds `/bower_components/` to the default ignores to this branch, but then the code checks will complain about more than one commit in this PR. Squashing would eat @JulianLaval 's credit on the tests and docs.

**Comment by JulianLaval** [comment]
Fine by me if squashing is preferred!

**Comment by nzakas** [comment]
We really should have those two commits separate as there are two different issues. Squashing isn't preferred here.

@gronke maybe I'm misunderstanding, but it doesn't seem like you answered my question in my previous comment. Can you?

**Comment by gronke** [comment]
Sorry for the delay. There was [an issue with loading the projects `.eslintignore` by the tests](https://github.com/eslint/eslint/issues/4041) that prevented adding more advanced tests for default ignore patterns.

The behavior in this branch can be described as:
* ignore `node_modules/` and `bower_components/` without `--no-ignore` flag as
  * sibling directory of the loaded `.eslintignore` file
  * sub-directory of the current work dir, when no `.eslintignore` file was loaded
* ignore dotfiles when not passed explicitly to CLI

Not sure if differentiating between top-level and subdirectories when ignoring `bower_components/` and `node_modules/` doen't make it over-complicated.

**Comment by keithamus** [comment]
I was just about to file an issue saying gitignore lines beginning with `!` such as `!foobar` don't work, and in fact break all linting. This looks like it'll fix the issue though (haven't tested but `ignore` claims to support the `!` pattern).

**Comment by gronke** [comment]
@keithamus you could file that issue anyway. Once it's approved as bug, I can go ahead and add tests according to it.

**Comment by gronke** [comment]
@nzakas did the added tests answer your question from the previous comments? I'm happy to answer any question by adding more tests.

What's your opinion on handling relative ignore patterns?
- Should ignore patterns be relative to `process.cwd()` when no `.eslintignore` was loaded?
- Should ignore patterns be relative to the loaded configuration file?
- Should the relative path change from the previous question apply to patterns from `.eslintignore` only when combined with rules from cli arguments? *(Not implemented)*
- Should the default pattern be `/node_modules/` (only top-level) or `node_modules/`?

**Comment by gronke** [comment]
Does it make sense to keep this branch rebased? I'm not aware of any plans which include the migration to node-ignore, so some information on the status would be nice. :neckbeard:

**Comment by nzakas** [comment]
Yes, it makes sense to rebase. Since this is a breaking change, it must wait for the 2.0.0 release, so we can't merge into we are prepping for that.

**Comment by gronke** [comment]
allright, will act like a cronjob and keep the branch in sync then

**Comment by nzakas** [comment]
We just branched for 2.0.0, we if you can rebase once, we should be good.

**Comment by nzakas** [comment]
Oops, I just realized I totally missed your questions. Sorry about that. Some answers:

> Should ignore patterns be relative to process.cwd() when no .eslintignore was loaded?

Yes

> Should ignore patterns be relative to the loaded configuration file?

I think so. We want to mimic what .gitignore does, and I think that's the case.

> Should the relative path change from the previous question apply to patterns from .eslintignore only when combined with rules from cli arguments? (Not implemented)

Can you explain what you mean here? I'm not clear on the question.

Should the default pattern be /node_modules/ (only top-level) or node_modules/?

only top level

**Comment by gronke** [comment]
>> Should the relative path change from the previous question apply to patterns from .eslintignore only when combined with rules from cli arguments? (Not implemented)

> Can you explain what you mean here? I'm not clear on the question.

When passing in ignore patterns as `--ignore-pattern` option, I'd expect that to be relative to `process.cwd()`. The current implementation in this PR would override the base dir when it found an `.eslintignore` file that would affect the patterns passed via CLI argument. The rest of this PR matches with your answers.

Rebased shortly before your comment - did I miss to rebase against the right branch?

**Comment by nzakas** [comment]
> When passing in ignore patterns as --ignore-pattern option, I'd expect that to be relative to process.cwd(). 

Yes, that's correct. Me too.

> Rebased shortly before your comment - did I miss to rebase against the right branch?

Nope, you should be good.

**Comment by gronke** [comment]
@nzakas Please excuse the delay before updating and rebasing the branch this time. The PR is ready for another review now.

I'm happy to answer open questions with more unit tests.

File: lib/cli-engine.js [hunk 5]
```diff
@@ -391,12 +393,14 @@ function getCacheFile(cacheFile, cwd) {
  */
 function CLIEngine(options) {
 
+    options = (options || {});
+    options.cwd = options.cwd || process.cwd();
```
Comment (nzakas) [inline lib/cli-engine.js]: Be careful - this could be modifying the `options` object that is passed in. Best to use `assign()` to create a copy before modifying (like line 403).

File: lib/cli-engine.js [hunk 6]
```diff
@@ -575,11 +585,27 @@ CLIEngine.prototype = {
...
          * unsupported file extensions and any files that are already linted.
          * @param {string} filename The resolved filename of the file to be linted
+         * @param {boolean} warnIgnored always warn when a file is ignored
          * @returns {void}
          */
-        function executeOnFile(filename) {
+        function executeOnFile(filename, warnIgnored) {
             var hashOfConfig;
 
+            if ((options.ignore !== false) && ignoredPaths.contains(filename, "custom")) {
```
Comment (nzakas) [inline lib/cli-engine.js]: Can you combine this and the `if` on 601 into a single block that checks for `options.ignore !== false`.

File: lib/ignored-paths.js [hunk 7]
```diff
@@ -21,55 +22,139 @@ debug = debug("eslint:ignored-paths");
...
+ * @param {object} options Options to merge with DEFAULT_OPTIONS constant
+ * @returns {object} Merged options
  */
-function findIgnoreFile(cwd) {
-    if (!ignoreFileFinder) {
-        ignoreFileFinder = new FileFinder(ESLINT_IGNORE_FILENAME, cwd);
+function mergeDefaultOptions(options) {
+    options = (options || {});
+    Object.keys(DEFAULT_OPTIONS).forEach(function(key) {
+        if (typeof (options[key]) === "undefined") {
```
Comment (nzakas) [inline lib/ignored-paths.js]: You can do this a bit more clearly using:

```
return assign({}, DEFAULT_OPTIONS, options);
```

File: lib/ignored-paths.js [hunk 8]
```diff
@@ -21,55 +22,139 @@ debug = debug("eslint:ignored-paths");
...
+    });
+    return options;
+}
+
+/**
+ * Merge options with defaults
+ * @param {string} message Hint to print with the compatibility warning
+ * @returns {void}
+ */
+function printOsCompatibilityWarning(message) {
```
Comment (nzakas) [inline lib/ignored-paths.js]: We need to find a better way to do this - this file shouldn't be outputting to the console.

File: lib/ignored-paths.js [hunk 9]
```diff
@@ -81,64 +166,99 @@ function findIgnoreFile(cwd) {
...
+
+        addPattern(this.ig.default, this.defaultPatterns);
+
+        var ignorePath;
+
+        if (options.ignorePattern) {
+            addPattern(this.ig.custom, options.ignorePattern);
+        }
+
+        options.ignorePath = (options.ignorePath === "false") ? false : options.ignorePath;
```
Comment (nzakas) [inline lib/ignored-paths.js]: Why would ignorePath be "false"?

File: lib/ignored-paths.js [hunk 10]
```diff
@@ -81,64 +166,99 @@ function findIgnoreFile(cwd) {
...
-    return this.patterns.reduce(function(ignored, pattern) {
-        var negated = pattern[0] === "!",
-            matches;
+    var result = false;
+    filepath = normalizeAndResolveFilepath(filepath, this.baseDir);
 
-        if (negated) {
-            pattern = pattern.slice(1);
-        }
+    if ((typeof (category) === "undefined") || (category === "default")) {
```
Comment (nzakas) [inline lib/ignored-paths.js]: no parens around `category`, please

File: tests/lib/cli-engine.js [hunk 11]
```diff
@@ -53,21 +54,30 @@ describe("CLIEngine", function() {
...
     before(function() {
-        fixtureDir = os.tmpdir() + "/eslint/fixtures";
+        fixtureDir = path.join(os.tmpdir(), "/eslint/fixtures");
         mkdir("-p", fixtureDir);
         cp("-r", "./tests/fixtures/.", fixtureDir);
+        fixtureDir = fs.realpathSync(fixtureDir);
     });
 
     beforeEach(function() {
+        process.chdir(path.join(fixtureDir, ".."));
```
Comment (nzakas) [inline tests/lib/cli-engine.js]: Can you set the `cwd` option instead of changing the directory?

File: tests/lib/cli-engine.js [hunk 12]
```diff
@@ -226,8 +237,9 @@ describe("CLIEngine", function() {
 
         it("should report zero messages when given a config file and a valid file", function() {
 
+            process.chdir(originalDir);
```
Comment (nzakas) [inline tests/lib/cli-engine.js]: Same comment about using `cwd` instead of changing the directory.

File: lib/ignored-paths.js (hunk 9 above)
Comment (gronke) [inline lib/ignored-paths.js]: ignorePath set to `false` will result in no `.eslintignore` file being loaded. That's necessary in case you want to only use the patterns from cli flags while being in a directory with `.eslintignore` file. 

see the [Unit Test](https://github.com/eslint/eslint/pull/3948/files#diff-e0207692da5bc610c18bec3dbc54481dR128)

File: tests/lib/cli-engine.js (hunk 11 above)
Comment (gronke) [inline tests/lib/cli-engine.js]: Sure, but that would affect all tests in this file. We actually have tests that check if the `cwd` option works as expected. IMO changing the directory for the whole process is closer to the later usage where the user runs the eslint cli tool from a given work directory.

File: lib/ignored-paths.js (hunk 8 above)
Comment (gronke) [inline lib/ignored-paths.js]: Function for handling the warning now passed as option `onOsCompatibilityIssue` to IgnorePaths, so that the decision to print a warning is made by `CLIEngine`. Does that address your concerns properly?

File: lib/ignored-paths.js (hunk 9 above)
Comment (nzakas) [inline lib/ignored-paths.js]: I mean, why is it a string?

File: tests/lib/cli-engine.js (hunk 11 above)
Comment (nzakas) [inline tests/lib/cli-engine.js]: not sure I understand what you mean. We have the ability to manually specify `cwd`, and that defaults to `process.cwd` unless otherwise specified. Why is setting it here any different?

Comment (gronke) [inline tests/lib/cli-engine.js]: Just meant that we rely on this `cwd` option if we set it instead of changing the process work directory. If that feature breaks, all the tests will also fail. Do you expect any disadvantage from changing the work directory like done here?

Comment (nzakas) [inline tests/lib/cli-engine.js]: These are already integration tests rather than unit tests, so I don't mind cascading breaking tests related to `cwd`.

Actually changing the directory can have side effects if a test fails and the directory is incorrectly set for another test as a result.

Comment (gronke) [inline tests/lib/cli-engine.js]: Agreed. Will change to use `cwd` option instead.

File: lib/ignored-paths.js (hunk 9 above)
Comment (gronke) [inline lib/ignored-paths.js]: `ignorePath` should be a string by default (containing the path to the `.eslintignore` file to load). In some tests we set this option to `"false"`, so that no ignore file is loaded. Will remove that cases and ensure that test fixtures do not have an `.eslintignore` file in their parent directories.

@nzakas Would you like to have an option (e.g. `--no-ignore-file`) that disables `.eslintignore` lookups in parent directories anyway?

File: lib/cli-engine.js [hunk 13]
```diff
@@ -97,7 +98,9 @@ var defaultOptions = {
         cacheFile: ".eslintcache",
         fix: false,
         allowInlineConfig: true,
-        cwd: process.cwd()
+        warnIgnoredByDefault: true,
+        cwd: process.cwd(),
+        onOsCompatibilityIssue: logging.info
```
Comment (nzakas) [inline lib/cli-engine.js]: I'd prefer not to change this interface - I don't see any good reason to expose these two new options.

File: lib/ignored-paths.js [hunk 14]
```diff
@@ -81,64 +124,139 @@ function findIgnoreFile(cwd) {
...
+    /**
+     * add ignore file to node-ignore instance
+     * @param {object} ig, instance of node-ignore
+     * @param {string} filepath, file to add to ig
+     * @returns {array} raw ignore rules
+     */
+    function addIgnoreFile(ig, filepath) {
+        var fileContent = fs.readFileSync(filepath, "utf8");
+        if (fileContent.indexOf("**") !== -1) {
+            printOsCompatibilityWarning("source: " + filepath);
```
Comment (nzakas) [inline lib/ignored-paths.js]: It seems like we're jumping through a lot of hoops to output a message here. If this is a real problem, then we should throw an error. If it's not a real problem, then we should do nothing or try to fix it. In any case, we should be sure to mention this in the docs.

Comment (gronke) [inline lib/ignored-paths.js]: Fixing by replacing all occurrences `**` with a single star is obvious. Will remove the compatibility warnings.

File: lib/cli-engine.js (hunk 13 above)
Comment (gronke) [inline lib/cli-engine.js]: The `onOsCompatibilityIssue` will be removed. `warnIgnoredByDefault` is used to suppress warnings when ignoring files looked up by glob pattern, but not when passed the names explicitly. If I pass in a file to lint explicitly, I would expect a warning when this file is ignored for some reason.  We could get rid of this when explicitly specified files override ignore patterns.

File: lib/ignored-paths.js (hunk 14 above)
Comment (domenic) [inline lib/ignored-paths.js]: Wait. Why is this PR changing the syntax to not require **? I wanted eslintignore to be more like gitignore, not less!!

File: docs/user-guide/configuring.md [hunk 15]
```diff
@@ -557,13 +557,15 @@ You can tell ESLint to ignore specific files and directories by creating an `.es
 
 When ESLint is run, it looks in the current working directory to find an `.eslintignore` file before determining which files to lint. If this file is found, then those preferences are applied when traversing directories. Only one `.eslintignore` file can be used at a time, so `.eslintignore` files other than the one in the current working directory will not be used.
 
-Globs are matched using [minimatch](https://github.com/isaacs/minimatch), so a number of features are available:
+Globs are matched using [node-ignore](https://github.com/kaelzhang/node-ignore), so a number of features are available:
 
 * Lines beginning with `#` are treated as comments and do not affect ignore patterns.
+* Paths are relative to `.eslintignore` location or the current working directory.
+* Ignore patterns behave according to the `.gitignore` [specification](http://git-scm.com/docs/gitignore)
```
Comment (domenic) [inline docs/user-guide/configuring.md]: Except apparently they do not behave according to the gitignore specification; the gitignore specification requires **s for many of the cases here.

Comment (gronke) [inline docs/user-guide/configuring.md]: The OS compatibility warnings are gone now. The updated implementation just relies on the [behavior of node-ignore](https://github.com/kaelzhang/node-ignore/blob/master/test/ignore.js#L33-L56).

File: lib/ignored-paths.js (hunk 14 above)
Comment (nzakas) [inline lib/ignored-paths.js]: @gronke an I correct that now `**` works correctly?

File: .eslintignore [hunk 16]
```diff
@@ -1,12 +1,12 @@
-bin/**
```
Comment (domenic) [inline .eslintignore]: Could you revert all these changes? They are incorrect according to the gitignore specification and do not match [the behavior of node-ignore](https://github.com/kaelzhang/node-ignore/blob/master/test/ignore.js#L33-L56).

Comment (domenic) [inline .eslintignore]: Also the changes to the readme and the test fixtures.

Comment (gronke) [inline .eslintignore]: done

**Comment by gronke** [comment]
@domenic we entirely rely on `node-ignore` for handling the glob patterns now. Haven't seen any issues with the `**` patterns on Mac OS and Linux, so the changes to the project's `.eslintignore` patterns and docs were be reverted too.

@nzakas Tests do no longer change the processes work directory, but set the `cwd` option when necessary instead.

**Comment by domenic** [comment]
Thanks, I was confused because the changes mentioned seemed to imply that the gitignore spec wasn't being followed. But now that you've reverted them it's probably fine.

File: lib/cli-engine.js [hunk 17]
```diff
@@ -391,12 +392,14 @@ function getCacheFile(cacheFile, cwd) {
...
+    options = (options instanceof Object) ? assign(options) : {};
+    options.cwd = options.cwd || process.cwd();
+
     /**
      * Stored options for this instance
      * @type {Object}
      */
-    this.options = assign(Object.create(defaultOptions), options || {});
-
+    this.options = assign(defaultOptions, options);
```
Comment (gyandeeps) [inline lib/cli-engine.js]: By doing this a lot of default values will be overwritten by undefined.
Also you can remove line 395-396 and revert this change, you will get what you are looking for here. Basically you don need these changes.

File: lib/ignored-paths.js [hunk 18]
```diff
@@ -21,57 +23,97 @@ debug = debug("eslint:ignored-paths");
...
 }
 
-var ignoreFileFinder;
+/**
+ * Remove a prefix from a filepath
+ * @param {string} filepath Path to remove the prefix from
+ * @param {string} prefix Prefix to remove from filepath
+ * @returns {string} Normalized filepath
+ */
+function removePrefixFromFilepath(filepath, prefix) {
```
Comment (gyandeeps) [inline lib/ignored-paths.js]: are we doing this to be backward compatible to some patterns?

Comment (gronke) [inline lib/ignored-paths.js]: This function is used to ensure patterns are relative to the `base` directory. When an absolute path is specified as pattern, the `base` prefix will be removed and with that the pattern is converted to a relative pattern instead. Btw. the `fs.realPathSync` call is necessary to resolve symlinks.

File: lib/cli-engine.js (hunk 17 above)
Comment (gronke) [inline lib/cli-engine.js]: `Object.create(defaultOptions)` was always empty. Does the following change address your comment?
```
this.options = assign(defaultOptions, options || {});
```

Under which circumstances do you expect undefined values? The examples from [object-assign](https://github.com/sindresorhus/object-assign/blob/master/readme.md) show that an undefined value would just be ignored.

Comment (gyandeeps) [inline lib/cli-engine.js]: try running some cli tests and observe the values getting set. It will happen when the call come from cli into cli-engine. I have to try myself to make sure I am 100% correct.

Comment (nzakas) [inline lib/cli-engine.js]: @gronke the first argument of `assign()` receives the properties from the other arguments, so you are overwriting `defaultOptions` each time this is called. 

`Object.create(default Options)` creates a new object that inherits from defaultOptions`, so it's a new copy each time. 

Unless you were seeing a bug with how this was, please revert this change. If you were saying a bug, please describe it.

File: tests/lib/cli-engine.js [hunk 19]
```diff
@@ -1457,12 +1535,13 @@ describe("CLIEngine", function() {
...
                 engine.executeOnFiles([file]);
 
-                assert.isTrue(fs.existsSync(path.resolve(".eslintcache")), "the cache for eslint was created");
+                assert.isTrue(fs.existsSync(cacheFile), "the cache for eslint was created");
 
                 engine = new CLIEngine({
                     useEslintrc: false,
                     // specifying cache true the cache will be created
                     cache: false,
+                    cacheFile: cacheFile,
```
Comment (gronke) [inline tests/lib/cli-engine.js]: @nzakas @gyandeeps this setting was missing, so CLIEngine did not remember which file to delete. Will open an issue for that feature, because it might not be intuitive that disabling the cache still needs `cacheFile` to be set or it just deletes the file when `cache` is false.

File: lib/cli-engine.js (hunk 17 above)
Comment (gronke) [inline lib/cli-engine.js]: Fixing that resulted in [breaking another unit test](https://github.com/eslint/eslint/pull/3948#discussion_r48753826) that caused some confusion.

`Object.create(defaultOptions)` does not create an object with the same enumerable properties
```
> var a,b;
undefined
> a = { foo: 'bar' };
{ foo: 'bar' }
> b = Object.create(a);
{}
> b.foo
'bar'
> a.propertyIsEnumerable('foo')
true
> b.propertyIsEnumerable('foo')
false
```

The workaround is to to pass `Object.create(null)` as first argument to `object-assign`.

File: lib/cli-engine.js [hunk 20]
```diff
@@ -391,12 +392,14 @@ function getCacheFile(cacheFile, cwd) {
  */
 function CLIEngine(options) {
 
+    options = assign(Object.create(null), defaultOptions, options);
+    options.cwd = options.cwd || process.cwd();
```
Comment (gyandeeps) [inline lib/cli-engine.js]: You dont have to do this as defaults already have the `cwd` in it.

Comment (gronke) [inline lib/cli-engine.js]: Removed! :smirk_cat:

File: tests/lib/cli-engine.js (hunk 19 above)
Comment (nzakas) [inline tests/lib/cli-engine.js]: It would be best not to make this change here, since it's unrelated to the ignore file work. We like to keep pull requests as focused as possible in case there's a problem later.

Comment (gronke) [inline tests/lib/cli-engine.js]: @nzakas It was a bug we did not detect before, because the default `.eslintignore` file was the right one until we switched the `cwd` for the tests. We could also not see the test fail after my first changes, because during the tests the default options got overwritten - @gyandeeps [pointed that out in an earlier comment](https://github.com/eslint/eslint/pull/3948#discussion_r48548239). IMO the change belongs here, but I can move that line to another PR if you prefer.

Comment (nzakas) [inline tests/lib/cli-engine.js]: Ah OK, makes sense then. Please be sure to open an issue as well so we can look further into it.

File: package.json [hunk 21]
```diff
@@ -50,6 +50,8 @@
     "glob": "^5.0.14",
     "globals": "^8.17.0",
     "handlebars": "^4.0.5",
+    "handlebars": "^4.0.0",
```
Comment (nzakas) [inline package.json]: Duplicate dependency

**Comment by nzakas** [comment]
@domenic do you want to check this out and see if it works for your use case?

**Comment by domenic** [comment]
Sure, I can try to do that today or tomorrow; thanks for checking in.

**Comment by nzakas** [comment]
@domenic just wanted to follow-up to see if you have some time to check this out? This is the last feature we need to merge for our first beta (tentatively scheduled for tomorrow), so if you have time to take a look, I'd greatly appreciate it.

**Comment by domenic** [comment]
I was able to verify that this does fix my use case, which was an eslintignore file containing

```
lib/jsdom/living/generated/**

# Buggy: https://github.com/eslint/eslint/issues/3707
!lib/jsdom/living/generated/**/*-impl.js
```

However upgrading to ESLint 2.0 is going to be quite a burden due to #4641 (even more than I thought); very frustrating. Oh well, 1.x is fine for now.

**Comment by nzakas** [comment]
Thanks for the feedback on this PR, I'm going to merge this in. 

If you have further thoughts on how we can make #4641 an easier change, please feel free to open an issue to discuss.

@gronke Thank you so much for sticking with us and working to get this finished. It's really appreciated. Please be sure to claim the bounty on this issue, you've earned it!

**Comment by gronke** [comment]
Awesome, that's nice to hear. In return I have to thank everybody following the discussion and iterations of this commit for always giving valuable feedback almost instantaneously.
