### PR TITLE
Fix: `no-dupe-args` had been wrong for nested destructuring

### LINKED ISSUE #3867: no-dupe-args error thrown for nested array destructuring
I get the following:

```
  8:12  error  Duplicate param 'undefined'  no-dupe-args
```

for the following code.

```js
import React, { Component, PropTypes } from 'react';
import { geo } from 'd3';

const path = geo.path();

export default class SVGNode extends Component {

    viewBox([
        [left, top],
        [right, bottom]
    ]) {

        return [
            left,
            top,
            right - left, // width
            bottom - top // height
        ].join(' ');

    }

    render() {

        const { data } = this.props;

        return (
            <svg viewBox={this.viewBox(path.bounds(data))}>
                {data.features.map((feat, i) => (
                    <path key={i} d={path(feat.geometry)} />
                ))}
            </svg>
        );

    }
}

SVGNode.propTypes = {
    data: PropTypes.object
};
```

The code functions exactly as I expect it to.

I'm using eslint 1.5.0 and eslint-plugin-react 3.4.2.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26812035-no-dupe-args-error-thrown-for-nested-array-destructuring?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #3867.

I changed the check process with using `escope.Variable`.

### CODE REVIEW

File: lib/rules/no-dupe-args.js [hunk 1]
```diff
@@ -17,62 +19,43 @@ module.exports = function(context) {
...
-                    });
-                    break;
-
-                // no default
+            keyMap[key] = true;
+
+            // Checks and reports duplications.
+            var defs = variable.defs.filter(isParameter);
+            if (defs.length >= 2) {
+                context.report(
```
Comment (gyandeeps) [inline lib/rules/no-dupe-args.js]: Can you please use the new API for context report: http://eslint.org/docs/developer-guide/working-with-rules#contextreport

Comment (mysticatea) [inline lib/rules/no-dupe-args.js]: Thanks, done!

**Comment by nzakas** [comment]
Lgtm
