### PR TITLE
Fix: Load .eslintrc in $HOME only if no other .eslintrc is found (fixes #2279)

### LINKED ISSUE #2279: Allow ~.eslintrc to be ignored
I have a `.eslintrc` in my home directory as a default linter for small experiments, and different `.eslintrc` files in a number of projects. Those projects run eslint as part of a git commit hook.

My problem is that when I lint my project files, I inherit additional rules from my personal `.eslintrc` (which is technically in a parent directory). This means that code which is proper by the standards of the project is still causing lint tasks in the projects to fail.

I've searched the documentation for some option to disable my persional `~/.eslintrc`, or designate a certain `.eslintrc` as the root one (which would mean eslint should start cascading from that file). So far I haven't been able to find anything. Have I overlooked something?

### PR DESCRIPTION
**Pull request by jwoudenberg**

### CODE REVIEW

File: lib/config.js [hunk 1]
```diff
@@ -141,6 +141,11 @@ function getLocalConfig(thisConfig, directory) {
         localConfigFile = localConfigFiles[i];
         localConfig = loadConfig(localConfigFile);
 
+        // Don't consider the personal config file in the home directory.
```
Comment (nzakas) [inline lib/config.js]: Maybe move before `localConfig =`? No sense in reading the file just to throw it away.

Comment (jwoudenberg) [inline lib/config.js]: Yeah, makes sense. I made the change.

**Comment by nzakas** [comment]
Thanks.
