### PR TITLE
Fix: `no-useless-return` false positive on conditionals (fixes #7477)

### LINKED ISSUE #7477: False positive for no-useless-return
So I decided to give a try to the new rule `no-useless-return` and I stumbled on what looks to me like _too much of goodness_.

Here is a minimal example to illustrate the issue (actual code is here: https://github.com/fasttime/JScrewIt/blob/b3cce7dbc33628c184a1d39bf827c5b5bb52877e/src/lib/encoder-base.js#L363).

``` js
function returnValidValueOrUndefined(value)
{
    if (!isValidValue(value))
        return; // Unnecessary return statement   no-useless-return
    return value;
}
```

Granted, there are plenty of ways to get rid of the expressionless `return;`, but it seems unfair to call it useless when the next statement would potentially return something different.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

See https://github.com/eslint/eslint/issues/7477

**What changes did you make? (Give an overview)**

This ensures that if a `return` statement has an argument, and it's on the same code path as another return statement, the first return statement is not considered to be a useless return.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: tests/lib/rules/no-useless-return.js [hunk 1]
```diff
@@ -305,28 +350,10 @@ ruleTester.run("no-useless-return", rule, {
...
-                } catch (err) {
-                  return 5;
-                }
-              }
-            `
-        },
+
+        // FIXME: Re-add this case (removed due to https://github.com/eslint/eslint/issues/7481):
+        // https://github.com/eslint/eslint/blob/261d7287820253408ec87c344beccdba2fe829a4/tests/lib/rules/no-useless-return.js#L308-L329
+
```
Comment (not-an-aardvark) [inline tests/lib/rules/no-useless-return.js]: This fix caused this test case to fail due to https://github.com/eslint/eslint/issues/7481. However, the fix for https://github.com/eslint/eslint/issues/7481 will be semver-minor, so I think it's best to remove this case for now, and then re-add it when https://github.com/eslint/eslint/issues/7481 is fixed.
