### PR TITLE
Fix: ObjectRestSpread throws error in key-spacing rule (fixes #4763)

### LINKED ISSUE #4763: Bug: ObjectRestSpread throws error in key-spacing rule
**What version are you using?**
`eslint@1.10.3`

**What did you do?**
```sh
echo "({...x})" | eslint --stdin
```
**.eslintrc**
```json
{
  "ecmaFeatures": {
    "experimentalObjectRestSpread": true
  },
  "env": {
    "es6": true
  },
  "rules": {
    "key-spacing": [2, { "align": "colon" }]
  }
}
```

**What happened?**
```
/tmp/test/node_modules/eslint/lib/rules/key-spacing.js:176
        return endToken.range[1] - startToken.range[0];
                       ^

TypeError: Cannot read property 'range' of undefined
    at getKeyWidth (/tmp/test/node_modules/eslint/lib/rules/key-spacing.js:176:24)
    at Array.map (native)
    at verifyGroupAlignment (/tmp/test/node_modules/eslint/lib/rules/key-spacing.js:228:33)
    at /tmp/test/node_modules/eslint/lib/rules/key-spacing.js:262:13
    at Array.forEach (native)
    at verifyAlignment (/tmp/test/node_modules/eslint/lib/rules/key-spacing.js:261:28)
    at EventEmitter.ObjectExpression (/tmp/test/node_modules/eslint/lib/rules/key-spacing.js:303:21)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/tmp/test/node_modules/eslint/lib/util/node-event-generator.js:42:22)
```
**What did you expect to happen?**

No errors

**Note**

I have already written a fix (will send PR after this issue gets accepted).
But since support for object rest spread is still "experimental", you might consider its too early for it.
So let me know if should propose it at https://github.com/babel/eslint-plugin-babel

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29292563-bug-objectrestspread-throws-error-in-key-spacing-rule?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by zaygraveyard**

### CODE REVIEW

File: lib/rules/key-spacing.js [hunk 1]
```diff
@@ -99,6 +99,16 @@ module.exports = function(context) {
         afterColon = +!(options.afterColon === false); // Defaults to true
 
     /**
+     * Determines if the given property is not a spread property.
+     * @param {ASTNode} property Property node to check.
+     * @returns {Boolean} false if the property is a spread property.
+     */
+    function isNonSpreadProperty(property) {
```
Comment (nzakas) [inline lib/rules/key-spacing.js]: Seems like this should be named `isProperty`?

**Comment by btmills** [comment]
@zaygraveyard check out the part in `getKeyWidth` where we're currently ignoring ES6 shorthand properties and methods. I like your approach of `filter`ing the group's properties better. Can you move those checks into your `isNonSpreadProperty` method and rename it to something like `isKeyValueProperty`?

File: tests/lib/rules/key-spacing.js [hunk 2]
```diff
@@ -313,6 +313,81 @@ ruleTester.run("key-spacing", rule, {
...
+            "    e: 0,",
+            "    ...y,",
+            "    /* group b */",
+            "    f: 0",
+            "})"
+        ].join("\n"),
+        options: [{
+            align: "colon"
+        }],
+        parserOptions: { ecmaVersion: 6, ecmaFeatures: { experimentalObjectRestSpread: true } }
```
Comment (btmills) [inline tests/lib/rules/key-spacing.js]: Can you add an invalid test as well to verify that it will warn if a normal property that comes after a spread property in a group doesn't match the alignment of the rest of the group before the spread property?

File: lib/rules/key-spacing.js (hunk 1 above)
Comment (zaygraveyard) [inline lib/rules/key-spacing.js]: I liked @btmills suggestion for `isKeyValueProperty`, do you find it suitable?

File: tests/lib/rules/key-spacing.js (hunk 2 above)
Comment (zaygraveyard) [inline tests/lib/rules/key-spacing.js]: Yeah, sure

**Comment by zaygraveyard** [comment]
I like your suggestion @btmills, and I will implement it asap (tonight in GMT+1)

File: lib/rules/key-spacing.js (hunk 1 above)
Comment (nzakas) [inline lib/rules/key-spacing.js]: Fine by me

**Comment by gyandeeps** [comment]
@btmills do u think this is good to go?

**Comment by btmills** [comment]
Yep! LGTM
