### PR TITLE
Fix: no-multiple-empty-lines and template strings (fixes #2605)

### LINKED ISSUE #2605: no-multiple-empty-lines should ignore template strings
Right now I'm getting warnings from this rule if I have the following:

```js
const str = (
`first


second`);
```

But because that's essentially a string, I'd think the rule should ignore that, allow whitespace to be arbitrary there as it would ignore `"first\n\n\n\nsecond"`, right?

### PR DESCRIPTION
**Pull request by xjamundx**
A simple fix for the `no-multiple-empty-lines` bug with template strings.

Happy to receive suggestions on making this better.

### CODE REVIEW

**Comment by gyandeeps** [comment]
LGTM :+1:

File: lib/rules/no-multiple-empty-lines.js [hunk 1]
```diff
@@ -34,6 +46,12 @@ module.exports = function(context) {
                 trimmedLines = lines.map(function(str) {
                     return str.trim();
                 });
+
+            // add the notEmpty lines in there with a placeholder
+            notEmpty.forEach(function(x, i) {
```
Comment (ilyavolodin) [inline lib/rules/no-multiple-empty-lines.js]: I wonder if it would be easier to take trimmedLines and get nodes for corresponding location, and check if node is TemplateLiteral instead of doing those two loops. I think in the end it doesn't matter a whole lot, but it would probably take big o down by a few n's.

Comment (xjamundx) [inline lib/rules/no-multiple-empty-lines.js]: Yeah, I was kind of thinking the same thing, mostly wasn't fully following the logic below so I didn't want to risk it :) I can take another stab in a few hours

Comment (ilyavolodin) [inline lib/rules/no-multiple-empty-lines.js]: I would just see if adding a line into the map function above to get node for current location and check if it's not TemplateLiteral would work. If it does, it feels like an easier solution.

Comment (gyandeeps) [inline lib/rules/no-multiple-empty-lines.js]: Do you think getting the node all the time would end up being expensive against what we have now? 
Tho it looks simpler.

**Comment by xjamundx** [comment]
Hey I couldn't really find a better way to do this. Nothing I tried helped perf much more either.

**Comment by ilyavolodin** [comment]
Sounds good to me. It was just a thought.
