### PR TITLE
Fix: Update sort-vars to ignore Array and ObjectPattern (fixes #2954)

### LINKED ISSUE #2954: Destructuring issue: Cannot call method 'toLowerCase' of undefined
When linting the following code:
```js
var p = {m: 'M'};

var {m} = p;
```
I get the following error:
```
TypeError: Cannot call method 'toLowerCase' of undefined
    at /Users/*******/node_modules/eslint/lib/rules/sort-vars.js:24:57
```

### PR DESCRIPTION
**Pull request by Aourin**
Ignores ArrayPattern and ObjectPattern on sorted-vars

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM

File: tests/lib/rules/sort-vars.js [hunk 1]
```diff
@@ -34,8 +34,37 @@ eslintTester.addRuleTest("lib/rules/sort-vars", {
...
+            ecmaFeatures: { blockBindings: true, destructuring: true }},
+        { code: "var {a, x: {b, c}} = {};", args: ignoreCaseArgs,
+            ecmaFeatures: { destructuring: true }},
+        { code: "var {a, x: [b, c]} = {};", args: ignoreCaseArgs,
+            ecmaFeatures: { destructuring: true }},
+        { code: "var [a, {b, c}] = {};", args: ignoreCaseArgs,
+            ecmaFeatures: { destructuring: true }},
+        { code: "var [a, {x: {b, c}}] = {};", args: ignoreCaseArgs,
+            ecmaFeatures: { destructuring: true }},
+        { code: "var a = 42, {b, c } = {};", args: ignoreCaseArgs, ecmaFeatures: { destructuring: true }}
```
Comment (btmills) [inline tests/lib/rules/sort-vars.js]: Right now all of the tests include sorted variables, even within destructuring. Can you include some valid tests with unsorted identifiers inside destructuring patterns?

Comment (Aourin) [inline tests/lib/rules/sort-vars.js]: Yes, sorry I thought I thought I added some.
