### PR TITLE
Fix: newBasePath should be an absolute path (fixes #12850)

### LINKED ISSUE #12850: AssertionError [ERR_ASSERTION]: 'newBasePath' should be an absolute path
Windows
Node v12.13.0
npm v6.13.6
eslint 6.8.0
Parser: @typescript-eslint/parser
Bash terminal

eslint config:
```
"use strict";
const allExtensions = [".ts", ".tsx", ".d.ts", ".js", ".jsx"];
module.exports = {
    env: {
        "browser": true,
        "es6": true,
    },
    parser: "@typescript-eslint/parser",
    parserOptions: {
        project: "./tsconfig.json",
        sourceType: "module",
    },
    plugins: [
        "import",
        "@typescript-eslint",
        "@typescript-eslint/tslint",
    ],
    settings: {
        "import/extensions": allExtensions,
        "import/parsers": {
            "@typescript-eslint/parser": [".ts", ".tsx", ".d.ts"],
        },
        "import/resolver": {
            "node": {
                "extensions": allExtensions,
            },
        },
    },
    rules: {
     
        "import/no-deprecated": "warn",
        "@typescript-eslint/no-unused-vars": "error",
        "@typescript-eslint/tslint/config": [
            "warn",
            {
                "rules": {
                    "deprecation": true,
                },
            },
        ],
    },
};
```

I'm currently using a globally installed npm package (call it foo cli) that wraps eslint. I have a workspace in c:\src\myproject. foo cli has an internal reference to eslint 6.8.0. When I run `ap lint` from c:\src\myproject, foo cli invokes eslint with some default parameters, and I get the error from the bug title. Here's the raw output:

```
/c/myproject (master)
$ ap lint
Running C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\.bin\eslint.cmd **/*.ts --ignore-path C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\lint\.eslintignore -c C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\lint\.eslintrc.json --resolve-plugins-relative-to C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\lint
AssertionError [ERR_ASSERTION]: 'newBasePath' should be an absolute path.
    at IgnorePattern.getPatternsRelativeTo (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\config-array\ignore-pattern.js:210:9)
    at C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\config-array\ignore-pattern.js:150:42
    at Array.map (<anonymous>)
    at Function.createIgnore (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\config-array\ignore-pattern.js:150:31)
    at createConfig (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\config-array\config-array.js:282:40)
    at ConfigArray.extractConfig (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\config-array\config-array.js:452:33)
    at FileEnumerator._isIgnoredFile (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\file-enumerator.js:479:24)
    at FileEnumerator._iterateFilesRecursive (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\file-enumerator.js:407:38)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\file-enumerator.js:251:49)
```

I believe the problem exists in ignore-pattern.js and was introduced in this pull request: https://github.com/eslint/eslint/pull/12274/files

If I add some debug logging to IgnorePattern.getCommonAncestorPath:
```
function getCommonAncestorPath(sourcePaths) {
    let result = sourcePaths[0];

    for (let i = 1; i < sourcePaths.length; ++i) {
        const a = result;
        const b = sourcePaths[i];

        // Set the shorter one (it's the common ancestor if one includes the other).
        result = a.length < b.length ? a : b;

        // Set the common ancestor.
        for (let j = 0, lastSepPos = 0; j < a.length && j < b.length; ++j) {
            if (a[j] !== b[j]) {
                result = a.slice(0, lastSepPos);
                break;
            }
            if (a[j] === path.sep) {
                lastSepPos = j;
            }
        }
    }
    console.log("**: ", { result: result, sep: path.sep, sourcePaths: sourcePaths }); // new line here
    return result || path.sep;
}
```

I see the following output:
```
/c/myproject (master)
$ ap lint
Running C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\.bin\eslint.cmd **/*.ts --ignore-path C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\lint\.eslintignore -c C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\lint\.eslintrc.json --resolve-plugins-relative-to C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\lint
**:  {
  result: 'C:\\src\\myproject',
  sep: '\\',
  sourcePaths: [ 'C:\\src\\myproject' ]
}
**:  {
  result: 'C:\\src\\myproject',
  sep: '\\',
  sourcePaths: [ 'C:\\src\\myproject' ]
}
**:  {
  result: 'C:',
  sep: '\\',
  sourcePaths: [
    'C:\\src\\myproject',
    'C:\\Users\\drkestel\\AppData\\Roaming\\npm\\node_modules\\@foocli\\lint'
  ]
}
AssertionError [ERR_ASSERTION]: 'newBasePath' should be an absolute path.
    at IgnorePattern.getPatternsRelativeTo (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\config-array\ignore-pattern.js:210:9)
    at C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\config-array\ignore-pattern.js:150:42
    at Array.map (<anonymous>)
    at Function.createIgnore (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\config-array\ignore-pattern.js:150:31)
    at createConfig (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\config-array\config-array.js:282:40)
    at ConfigArray.extractConfig (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\config-array\config-array.js:452:33)
    at FileEnumerator._isIgnoredFile (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\file-enumerator.js:479:24)
    at FileEnumerator._iterateFilesRecursive (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\file-enumerator.js:407:38)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\eslint\lib\cli-engine\file-enumerator.js:251:49)

/c/myproject (master)
$
```

Notice the `result: 'C:',` - that is not considered a valid absolute path.

Interestingly enough, I can mitigate the problem by using windows cmd.exe and setting my current prompt to `c:\` (lowercase, as opposed to `C:\`). Because `c:\ != C:\`, it works. See the output:

```
c:\src\myproject>ap lint
Running C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\node_modules\.bin\eslint.cmd **/*.ts --ignore-path C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\lint\.eslintignore -c C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\lint\.eslintrc.json --resolve-plugins-relative-to C:\Users\drkestel\AppData\Roaming\npm\node_modules\@foocli\lint
**:  {
  result: 'c:\\src\\myproject',
  sep: '\\',
  sourcePaths: [ 'c:\\src\\myproject' ]
}
**:  {
  result: 'c:\\src\\myproject',
  sep: '\\',
  sourcePaths: [ 'c:\\src\\myproject' ]
}
**:  {
  result: '',
  sep: '\\',
  sourcePaths: [
    'c:\\src\\myproject',
    'C:\\Users\\drkestel\\AppData\\Roaming\\npm\\node_modules\\@foocli\\lint'
  ]
}
**:  {
  result: '',
  sep: '\\',
  sourcePaths: [
    'c:\\src\\myproject',
    'C:\\Users\\drkestel\\AppData\\Roaming\\npm\\node_modules\\@foocli\\lint'
  ]
}

c:\src\myproject\Client\Index.ts
  66:5   warning  Missing return type on function                 @typescript-eslint/explicit-function-return-type
  67:17  error    'container' is assigned a value but never used  @typescript-eslint/no-unused-vars
  68:15  error    'id' is assigned a value but never used         @typescript-eslint/no-unused-vars

... more valid linting
```

I can also mitigate the problem by making the following code change to ignore-pattern.js:
```
function getCommonAncestorPath(sourcePaths) {
    let result = sourcePaths[0];

    for (let i = 1; i < sourcePaths.length; ++i) {
        const a = result;
        const b = sourcePaths[i];

        // Set the shorter one (it's the common ancestor if one includes the other).
        result = a.length < b.length ? a : b;

        // Set the common ancestor.
        for (let j = 0, lastSepPos = 0; j < a.length && j < b.length; ++j) {
            if (a[j] !== b[j]) {
                result = a.slice(0, lastSepPos);
                break;
            }
            if (a[j] === path.sep) {
                lastSepPos = j;
            }
        }
    }
    // this was the previous return statement
    // return result || path.sep;

    // new return statement
    let resolvedResult = result || path.sep;
    if (resolvedResult && resolvedResult.endsWith(":")) {
        resolvedResult = resolvedResult + path.sep;
    }
    return resolvedResult;
}
```

### PR DESCRIPTION
**Pull request by nickharris**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [ ] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
fixes #12850

### CODE REVIEW

File: tests/lib/cli-engine/config-array/ignore-pattern.js [hunk 1]
```diff
@@ -52,74 +52,79 @@ describe("IgnorePattern", () => {
...
+                it("should return true if '.dot/foo.js' and true were given.", () => {
+                    assert.strictEqual(ignores(path.join(cwd, ".dot/foo.js"), true), false);
+                });
+            };
 
-            it("should return true if '.dot/foo.js' and true were given.", () => {
-                assert.strictEqual(ignores(path.join(cwd, ".dot/foo.js"), true), false);
-            });
+            assertions(process.cwd());
+            // eslint-disable-next-line no-restricted-syntax
```
Comment (kaicataldo) [inline tests/lib/cli-engine/config-array/ignore-pattern.js]: Why is this disable comment needed?

File: tests/lib/cli-engine/config-array/ignore-pattern.js [hunk 2]
```diff
@@ -52,74 +52,79 @@ describe("IgnorePattern", () => {
...
-                ["abc/dir/b.js", true],
-                ["abc/dir/b.ts", false],
-                ["abc/dir/c.js", true],
-                ["abc/dir/c.ts", false]
-            ];
-
-            for (const [filename, expected] of patterns) {
-                it(`should return ${expected} if '${filename}' was given.`, () => {
-                    assert.strictEqual(ignores(path.join(cwd, filename)), expected);
+            // eslint-disable-next-line func-style
```
Comment (kaicataldo) [inline tests/lib/cli-engine/config-array/ignore-pattern.js]: Why is this disable comment needed?

File: tests/lib/cli-engine/config-array/ignore-pattern.js [hunk 3]
```diff
@@ -52,74 +52,79 @@ describe("IgnorePattern", () => {
...
-            });
+                it("should return true if '.dot/foo.js' and true were given.", () => {
+                    assert.strictEqual(ignores(path.join(cwd, ".dot/foo.js"), true), false);
+                });
+            };
 
-            it("should return true if '.dot/foo.js' and true were given.", () => {
-                assert.strictEqual(ignores(path.join(cwd, ".dot/foo.js"), true), false);
-            });
+            assertions(process.cwd());
```
Comment (kaicataldo) [inline tests/lib/cli-engine/config-array/ignore-pattern.js]: I think we should have an explicit test for the Windows-style path, either by mocking `process.cwd()` or passing in a hardcoded string.

File: tests/lib/cli-engine/config-array/ignore-pattern.js (hunk 1 above)
Comment (nickharris) [reply tests/lib/cli-engine/config-array/ignore-pattern.js]: assert.doesNotThrow was not allowed stating that comment should be made in the code...

Comment (kaicataldo) [reply tests/lib/cli-engine/config-array/ignore-pattern.js]: Understood. That lint rule is intentional, so we should update this to follow the recommendation there.

File: tests/lib/cli-engine/config-array/ignore-pattern.js (hunk 3 above)
Comment (nickharris) [reply tests/lib/cli-engine/config-array/ignore-pattern.js]: line 127 - I went with `path.parse(process.cwd()).root` which will return the Drive on your windows CI nodes and reproduces failure when ignore-pattern.js does not contain the fix.

Comment (nickharris) [reply tests/lib/cli-engine/config-array/ignore-pattern.js]: let me know your thoughts on this or if you need it all mocked out.

Comment (kaicataldo) [reply tests/lib/cli-engine/config-array/ignore-pattern.js]: I tend to lean towards actually mocking it so that the tests are consistent regardless of the environment they’re run in, but if others disagree I’m happy to defer to consensus.

Comment (nzakas) [reply tests/lib/cli-engine/config-array/ignore-pattern.js]: I agree with Kai — it’s best to have the data a test uses be consistent regardless of the platform we run on.

Comment (nickharris) [reply tests/lib/cli-engine/config-array/ignore-pattern.js]: i think the problem with mocking so that you can always supply both "C:\\" on both linux and windows in this case is as is that it results in mimicking windows behavior of path.isAbsolute on windows when passing C: into path.isAbsolute is what was raising the issue to begin with.

this is as close as i can get on windows. can either Of you take it for a spin on a linux box to debug the issue?
```
        let didThrow = false;

            try {
                if (process.platform !== "win32") {
                    sinon.stub(process, "platform").returns("win32");
                    sinon.stub(path, "sep").returns("\\");
                    sinon.replace(path, "isAbsolute", pth => {
                        if (pth === "C:") {
                            throw Error("getCommonAncestor should never return C:, it should instead return C:\\");
                        } else {
                            return true;
                        }
                    });
                }
                assertions("C:\\");
            } catch {
                didThrow = true;
            } finally {
                sinon.restore();
            }
```

IMHO i think this type of mock is providing little value and the original ` assertions(path.parse(process.cwd()).root);` with no stubbing provides coverage of root C:\\ on windows but also additionally covers / on linux.

in any case if you can try take the snippet above onto a linux box and see if you can get it going as you desire that would be appreciated.

Comment (nickharris) [reply tests/lib/cli-engine/config-array/ignore-pattern.js:131]: @kaicataldo @nzakas - I have added an additional a test at the bottom of this file that stubs required path and process Apis for Linux and tested on Windows Subsystem Linux - Ubuntu 18.04. The new test will fail on both Windows and Linux locally if the fix to getCommonAncestors is removed.  All CI Gates/Checks are also passed. I think this is done, let me know otherwise.

File: tests/lib/cli-engine/config-array/ignore-pattern.js [hunk 4]
```diff
@@ -52,74 +53,107 @@ describe("IgnorePattern", () => {
...
 
-            it("should return true if '.dot/foo.js' and true were given.", () => {
-                assert.strictEqual(ignores(path.join(cwd, ".dot/foo.js"), true), false);
-            });
+    describe("static createIgnore(ignorePatterns)", () => {
+        it("with common ancestor of drive root on windows should not throw", () => {
+            try {
+
+                // when not on windows return win32 values so local runs on linux produce the same issue as windows.
+                if (process.platform !== "win32") {
```
Comment (kaicataldo) [inline tests/lib/cli-engine/config-array/ignore-pattern.js:141]: Thanks for updating this. I think this is definitely an improvement. I still think it would be nice to ensure that execution is the same regardless of the platform the test is run on. Could we make this two tests - one for Windows-style paths and another for *nix-style paths - that don't conditionally stub these core Node APIs?

Comment (nickharris) [reply tests/lib/cli-engine/config-array/ignore-pattern.js:141]: line 141-145 - to be clear, with this the code execution of the module under test i.e ./tests/*/igore-pattern.js is the same when this test is run on linux and windows. The only portion of code that is not the same when running this test on linux/windows is the actual unit test i.e test/*/ignore-pattern.js. This is required to be this way as this is a platform specific bug and as such conditional platform specific stubs are required to ensure the tests exercises the same code path within the module under test irrespective of if you run the test on linux or windows.  If you don't stub these APIs to behave like windows then when running on linux then this test will not exercise the code path with the fix and will not catch future regressions.

line 132 - as for linux root path tests - / for *nix and C:\ for win32 they along with windows are still covered in line 132 with the original full set of ~40 assertions by `assertions(path.parse(process.cwd()).root);`.

I don't think there is more to do here. coverage has been increased to cover root path on linux and windows with line 132 by exercising the full original test suite against root path on linux./windows. and this new tests provides coverage and execution of the fix by exercising the same code path of the module under test when run on windows and linux with windows style paths.  if you believe there is more to do here please provide specific code example.

**Comment by nickharris** [comment]
@mysticatea thankyou for your feedback.  The scenario of adding tests across patterns starting with root of the drive and without stubbing is already covered in the code i added at line 132 -  `assertions(path.parse(process.cwd()).root);`  the function `assertions` is your original set of test patterns and since we pass the `.root` of the drive it that means means:

additional coverage  on Windows CI nodes has already been added for following paths by line 132:
c:\a.js
c:\a.ts
c:\b.js
c:\b.ts
c:\c.js
c:\c.ts
c:\dir\a.js
c:\dir\a.ts
c:\dir\b.js
c:\dir\b.ts
c:\dir\c.js
c:\dir\c.ts
c:\foo\bar\a.js
c:\foo\bar\a.ts
c:\foo\bar\b.js
c:\foo\bar\b.ts
c:\foo\bar\c.js
c:\foo\bar\c.ts
c:\foo\bar\dir\a.js
c:\foo\bar\dir\a.ts
c:\foo\bar\dir\b.js
c:\foo\bar\dir\b.ts
c:\foo\bar\dir\c.js
c:\foo\bar\dir\c.ts
c:\abc\a.js
c:\abc\a.ts
c:\abc\b.js
c:\abc\b.ts
c:\abc\c.js
c:\abc\c.ts
c:\abc\dir\a.js
c:\abc\dir\a.ts
c:\abc\dir\b.js
c:\abc\dir\b.ts
c:\abc\dir\c.js
c:\abc\dir\c.ts
c:\.dot.js
c:\.dot\foo.js

additional coverage on *nix CI nodes has already been added by line 132 for:
/a.js
/a.ts
/b.js
/b.ts
/c.js
/c.ts
/dir/a.js
/dir/a.ts
/dir/b.js
/dir/b.ts
/dir/c.js
/dir/c.ts
/foo/bar/a.js
/foo/bar/a.ts
/foo/bar/b.js
/foo/bar/b.ts
/foo/bar/c.js
/foo/bar/c.ts
/foo/bar/dir/a.js
/foo/bar/dir/a.ts
/foo/bar/dir/b.js
/foo/bar/dir/b.ts
/foo/bar/dir/c.js
/foo/bar/dir/c.ts
/abc/a.js
/abc/a.ts
/abc/b.js
/abc/b.ts
/abc/c.js
/abc/c.ts
/abc/dir/a.js
/abc/dir/a.ts
/abc/dir/b.js
/abc/dir/b.ts
/abc/dir/c.js
/abc/dir/c.ts
/.dot.js
/.dot/foo.js

I think this change has more then enough coverage added to both test the change and catch any future regressions.  From my point of view there is nothing more to be done here. Let me know if you think otherwise.

**Comment by kaicataldo** [comment]
My intention isn't to hold up this PR. If we have adequate coverage and others are okay with the current tests, I'll defer to them.

**Comment by nzakas** [comment]
@nickharris as it seems several team members are a bit confused about what is covered, could you add some comments in the test file reiterating what you’ve explained in the comments on this PR?

**Comment by nickharris** [comment]
@nzakas sure thing - done in latest commit. Thanks all!

**Comment by nickharris** [comment]
@kaicataldo no problems at all!

**Comment by nickharris** [comment]
anything else required from me here?

**Comment by nzakas** [comment]
@nickharris - not at this time. We tend to leave PRs open a bit just to make sure other teams members get a chance to chime in, too.
