### PR TITLE
Fix: sort-vars rule fails when memo is undefined

### LINKED ISSUE #3474: sort-vars rule fails when memo is undefined
[sort-vars](https://github.com/eslint/eslint/blob/v1.2.1/lib/rules/sort-vars.js#L19-L36) rule crashes when `memo` is `undefined`.

```js
node.declarations.reduce(function(memo, decl) {
    if (decl.id.type !== "ObjectPattern" && decl.id.type !== "ArrayPattern") {
        var lastVariableName,
            currenVariableName;

        lastVariableName = memo.id.name;
        currenVariableName = decl.id.name;

        if (ignoreCase) {
            lastVariableName = lastVariableName.toLowerCase();
            currenVariableName = currenVariableName.toLowerCase();
        }

        if (currenVariableName < lastVariableName) {
            context.report(decl, "Variables within the same declaration block should be sorted alphabetically");
            return memo;
        } else {
            return decl;
        }
    }
}, node.declarations[0]);
```

This affects tools such as `eslint-watch` and `gulp-eslint`, e.g.

https://github.com/adametry/gulp-eslint/issues/86

### PR DESCRIPTION
**Pull request by BYK**
Fixes #3474

Also, a good follow-up would be to add checking inside destructuring patterns.

### CODE REVIEW

File: lib/rules/sort-vars.js [hunk 1]
```diff
@@ -17,21 +17,23 @@ module.exports = function(context) {
...
-                        currenVariableName = currenVariableName.toLowerCase();
-                    }
-
-                    if (currenVariableName < lastVariableName) {
-                        context.report(decl, "Variables within the same declaration block should be sorted alphabetically");
-                        return memo;
-                    } else {
-                        return decl;
-                    }
+                if (decl.id.type === "ObjectPattern" || decl.id.type === "ArrayPattern") {
```
Comment (BYK) [inline lib/rules/sort-vars.js]: Alternatively I could have used

```js
node.declarations.filter(function (decl) { var type = decl.id.type; return type !== "ObjectPattern" && type !== "ArrayPattern"; }).reduce
```

But this version (the one without `filter`) seems a bit more efficient. What do you think?

Comment (nzakas) [inline lib/rules/sort-vars.js]: Seems fine to me.

**Comment by nzakas** [comment]
LGTM
