### PR TITLE
Update: Fix `no-useless-escape` false negative in regexes (fixes #7424)

### LINKED ISSUE #7424: no-useless-escape doesn't report unnecessary escaping in character classes
**Tell us about your environment**

* **ESLint Version:** 3.8.1
* **Node Version:** 6.9.1
* **npm Version:** 3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

(none)

**What did you do? Please include the actual source code causing the issue.**

```bash
echo '/[\?]/' | eslint --stdin --no-eslintrc --rule 'no-useless-escape: error'
```

**What did you expect to happen?**

`no-useless-escape` should report that the `?` in the regular expression was uselessly escaped, because `?` has no special meaning in a character class.

**What actually happened? Please include the actual, raw output from ESLint.**

No errors were reported.

A similar issue applies for characters like `-`, although it's a bit trickier because `-` is only sometimes a special character in a regex.

```js
/\-/; // useless escape
/[a\-]/; // useless escape
/[a\-b]/; // not a useless escape
```

`no-useless-escape` does not report useless escaping for any of the above examples.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

See https://github.com/eslint/eslint/issues/7424

**What changes did you make? (Give an overview)**

This updates `no-useless-escape` to verify whether a character needs to be escaped based on its position in a regular expression. Previously, `no-useless-escape` had a list of escapable characters for regexes, and it would never report cases where any of them were escaped. However, some characters only need to be escaped if they appear in a character class, and other characters only need to be escaped if they appear outside of a character class. This PR updates the rule to parse the regular expression to determine which characters are in character classes, and report the characters if they are escaped inside a character class and only need to be escaped outside a class (or vice versa).

**Is there anything you'd like reviewers to focus on?**

We should make sure that the `REGEX_GENERAL_ESCAPES`, `REGEX_CHARCLASS_ESCAPES`, and `REGEX_NON_CHARCLASS_ESCAPES` lists are correct.

### CODE REVIEW

File: lib/rules/no-useless-escape.js [hunk 1]
```diff
@@ -148,16 +208,32 @@ module.exports = {
...
-            }
+                parseRegExp(node.raw.slice(1, -1))
+
+                    /*
+                     * The '-' character is a special case, because it's only valid to escape it if it's in a character
+                     * class, and is not at either edge of the character class. To account for this, don't consider '-'
+                     * characters to be valid in general, and filter out '-' characters that appear in the middle of a
+                     * character class.
+                     */
+                    .filter((charInfo, index, array) => charInfo.text !== "-" || !charInfo.inCharClass || index === 0 || index === array.length - 1 || !array[index - 1].inCharClass || !array[index + 1].inCharClass)
```
Comment (platinumazure) [inline lib/rules/no-useless-escape.js]: I'd like to see this extracted to a function.

File: lib/rules/no-useless-escape.js [hunk 2]
```diff
@@ -9,6 +9,19 @@
 // Rule Definition
 //------------------------------------------------------------------------------
 
+/**
+* Returns the union of two sets.
+* @param {Set} setA The first set
+* @param {Set} setB The second set
+* @returns {Set} The union of the two sets
+*/
+function union(setA, setB) {
```
Comment (gyandeeps) [inline lib/rules/no-useless-escape.js]: This is so cool.. I never knew abt `yield*`.
Had to read up on couple of things to understand this but so awesome. 💯

File: lib/rules/no-useless-escape.js [hunk 3]
```diff
@@ -148,16 +208,32 @@ module.exports = {
...
+
+                while ((match = pattern.exec(value))) {
+                    validateString(VALID_STRING_ESCAPES, node, match);
+                }
             } else if (node.regex) {
-                nodeEscapes = VALID_REGEX_ESCAPES;
-            } else {
-                return;
-            }
+                parseRegExp(node.raw.slice(1, -1))
```
Comment (not-an-aardvark) [inline lib/rules/no-useless-escape.js]: Oops, I found a problem: `.slice(1, -1)` will be incorrect if the regex has flags, since the trailing slash won't be at index -1.

**Comment by not-an-aardvark** [comment]
@platinumazure Separated the complex behavior into its own function.

The number of linting errors this causes on the existing ESLint codebase is a bit concerning :confused:

File: lib/rules/no-useless-escape.js [hunk 4]
```diff
@@ -9,6 +9,19 @@
...
 //------------------------------------------------------------------------------
 
+/**
+* Returns the union of two sets.
+* @param {Set} setA The first set
+* @param {Set} setB The second set
+* @returns {Set} The union of the two sets
+*/
+function union(setA, setB) {
+    return new Set(function *() {
```
Comment (ljharb) [inline lib/rules/no-useless-escape.js]: not `function* (`?

File: lib/rules/no-useless-escape.js (hunk 2 above)
Comment (ljharb) [inline lib/rules/no-useless-escape.js]: this is a super clever way to merge Sets, i like it 💯

File: lib/rules/no-useless-escape.js (hunk 4 above)
Comment (not-an-aardvark) [inline lib/rules/no-useless-escape.js]: We have the [`generator-star-spacing`](http://eslint.org/docs/rules/generator-star-spacing) rule configured to enforce this spacing.

**Comment by not-an-aardvark** [comment]
CI is failing due to [this line](/eslint/eslint/blob/18ff70ff5db70beb1264eea1888401243a8f0129/lib/ast-utils.js#L24) and [this line](/eslint/eslint/blob/18ff70ff5db70beb1264eea1888401243a8f0129/lib/eslint.js#L110). Both of these seem to be valid linting errors, but why are they only getting reported on AppVeyor? Travis didn't report any issues, and I can't reproduce the linting error when running `npm test` locally.

File: lib/rules/no-useless-escape.js (hunk 4 above)
Comment (ljharb) [inline lib/rules/no-useless-escape.js]: ah, interesting choice

File: lib/rules/arrow-body-style.js [hunk 5]
```diff
@@ -105,7 +105,7 @@ module.exports = {
 
                             const tokenAfterArrowBody = sourceCode.getTokenAfter(arrowBody);
 
-                            if (tokenAfterArrowBody && tokenAfterArrowBody.type === "Punctuator" && /^[(\[\/`+-]/.test(tokenAfterArrowBody.value)) {
+                            if (tokenAfterArrowBody && tokenAfterArrowBody.type === "Punctuator" && /^[([\/`+-]/.test(tokenAfterArrowBody.value)) {
```
Comment (not-an-aardvark) [inline lib/rules/arrow-body-style.js]: Oh, looks like you're right; I had thought `/` always needed to be escaped, but apparently it only needs to be escaped in character classes.

Sidenote: This implies that `/[/]/` is a valid regex, but oddly, `/[/]/.toString()` returns `/[\/]/` (i.e. it auto-escapes the slash, at least in Chrome). It doesn't seem to do this for other escaped characters.

**Comment by platinumazure** [comment]
As we find new problems, there are concerns about ecosystem impact. The rule is correct in reporting all the new useless escapes, but there may be some cases where users might want to intentionally allow (or prefer) some useless escapes for readability/maintainability. So we may need to consider carefully how best to release this.

**Comment by not-an-aardvark** [comment]
I think we should do the following:

* Fix the default behavior by merging this PR. The current behavior is unambiguously a bug.
* Introduce an option such as `ignoreCharacterClasses: true` to revert to the previous behavior, for anyone that wants to allow *some* useless escapes. This option should be `false` by default.
* Ideally, it would be best if this bugfix and new option were both released in the same version, but I don't think this is a requirement; we can consider the bugfix and the new option independently.

File: lib/rules/no-useless-escape.js [hunk 6]
```diff
@@ -55,7 +55,71 @@ const VALID_REGEX_ESCAPES = [
...
+            }
+            if (char === "[" && !state.inCharClass) {
+                return Object.assign({}, state, {inCharClass: true, index});
+            }
+            if (char === "]" && state.inCharClass) {
+                return Object.assign({}, state, {inCharClass: false, index});
+            }
+        }
+        return {
+            charList: state.charList.concat({text: char, escaped: state.escapeNextChar, inCharClass: state.inCharClass, index}),
```
Comment (mysticatea) [inline lib/rules/no-useless-escape.js]: Does it need to create an array instance for each character? It looks to generate many useless copies.

File: lib/rules/no-useless-escape.js [hunk 7]
```diff
@@ -23,22 +36,9 @@ const VALID_STRING_ESCAPES = [
     "\r"
 ];
 
-const VALID_REGEX_ESCAPES = [
+const REGEX_GENERAL_ESCAPES = new Set([
     "\\",
-    ".",
-    "-",
     "^",
```
Comment (mysticatea) [inline lib/rules/no-useless-escape.js]: The escape of `^` in character class is unnecessary except the 1st character.

```js
/[\^a]/; // this escape is necessary; it becomes `not a` if the `\` is removed.
/[a\^]/; // this escape is unnecessary; the `^` is a character.
```

File: lib/rules/no-useless-escape.js [hunk 8]
```diff
@@ -23,22 +36,9 @@ const VALID_STRING_ESCAPES = [
...
-    "?",
-    "{",
-    "}",
-    "[",
-    "]",
-    "|",
-    "(",
-    ")",
     "b",
     "B",
```
Comment (mysticatea) [inline lib/rules/no-useless-escape.js]: The escape of `B` in character class is unnecessary.

```js
/[\B]/; // this escape is unnecessary; the `B` is a character.
```

On the other hand, the escape of `\b` is necessary. `\b` in character class is meaning backspace character. (`\b` outside of character class is a word boundary)

**Comment by not-an-aardvark** [comment]
TSC Summary: `no-useless-escape` currently has a false negative in regex character classes. This is clearly a bug in the rule, but there is reason to believe that the fix might have an unusually large impact on the ecosystem (there are 11 existing violations in the ESLint codebase that were not caught due to the bug). In addition, it's plausible that a user might be okay with useless escapes in character classes for readability, even though these escapes are useless according to the rule's definition. The current [proposal](https://github.com/eslint/eslint/pull/7425#issuecomment-255562026) is to accept this PR as a bugfix (since the rule is currently not working as intended), and add an opt-out option to ignore character classes (something like https://github.com/eslint/eslint/pull/7455).

TSC question: Should we merge this PR for the upcoming release and consider the opt-out option separately? If not, how should we handle this fix?

**Comment by alberto** [comment]
**TSC Resolution**: Merge as is. Opt-out option could be considered in the future.

**Comment by platinumazure** [comment]
@eslint/eslint-tsc @not-an-aardvark Thanks very much for taking the time to carefully deliberate this.
