### PR TITLE
fix: ignore files on a different drive on Windows

### LINKED ISSUE #18575: Bug: files on a different drive are not ignored on Windows
### Environment

Node version: v20.14.0
npm version: v10.7.0
Local ESLint version: v9.4.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.22631

### What parser are you using?

Default (Espree)

### What did you do?

On Windows, I tried to lint a file on a different drive than the working directory, and surprisingly, ESLint did not ignore that file.

---

Created a file **F:\foo.js**:

```js
foo();
```

Then in the PowerShell, from a directory on drive C:, run:

```shell
npx eslint --no-config-lookup F:\foo.js
```

### What did you expect to happen?

An warning message should be printed saying that file F:\foo.js is ignored.

### What actually happened?

The file was linted.

```console
C:\Project>npx eslint --no-config-lookup --rule "no-undef: error" F:\foo.js

F:\foo.js
  1:1  error  'foo' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```

### Link to Minimal Reproducible Example

https://github.com/fasttime/ESLint-Repro/actions/runs/9431260399/job/25979730143

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

The `Linter` class is also affected. For instance:

```js
// C:\test.mjs
import { Linter } from "eslint";

const linter = new Linter({ configType: "flat" });
const results = linter.verify("foo()", { rules: { "no-undef": "error" } }, "F:\\foo.js");

console.log(results);
```

Running the above code with `node test.mjs` prints:

```console
[
  {
    ruleId: 'no-undef',
    severity: 2,
    message: "'foo' is not defined.",
    line: 1,
    column: 1,
    nodeType: 'Identifier',
    messageId: 'undef',
    endLine: 1,
    endColumn: 4
  }
]
```

### PR DESCRIPTION
**Pull request by fasttime**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Update a dependency

fixes #18575

#### What changes did you make? (Give an overview)

This PR updates `@eslint/config-array` to version `^0.19.0` and adds unit tests to check that files on different drives are correctly ignored on Windows, which closes #18575.

The changes in `lib/eslint/eslint-helpers.js` remove unused logic that is probably a leftover of previous refactorings and is not necessary when paths (including glob patterns) are resolved to absolute paths. The changes in `RuleTester` should not be user-facing.

#### Is there anything you'd like reviewers to focus on?

Am I missing any unit tests?

### CODE REVIEW

File: tests/lib/rule-tester/rule-tester.js [hunk 1]
```diff
@@ -1332,22 +1332,6 @@ describe("RuleTester", () => {
...
-                },
-                {
-                    code: "var foo = 'bar'",
-                    filename: "path/to/somefile"
-                }
-            ],
-            invalid: []
-        });
-    });
-
```
Comment (fasttime) [inline tests/lib/rule-tester/rule-tester.js:1350]: I integrated this test into another one with the same title further below.

File: tests/lib/linter/linter.js [hunk 2]
```diff
@@ -9256,6 +9258,147 @@ describe("Linter with FlatConfigArray", () => {
...
+
+        it("should ignore external files with Posix paths", () => {
+            const configs = createFlatConfigArray(
+                { files: ["**/*.js"] },
+                { basePath: "/foo" }
+            );
+
+            configs.normalizeSync();
+            const messages1 = linter.verify("foo", configs, "/foo/bar.js", true);
+            const messages2 = linter.verify("foo", configs, "/bar.js", true);
```
Comment (mdjermanovic) [inline tests/lib/linter/linter.js:9380]:
```suggestion
            const messages1 = linter.verify("foo", configs, "/foo/bar.js");
            const messages2 = linter.verify("foo", configs, "/bar.js");
```

`Linter#verify()` accepted only 3 arguments.

File: tests/lib/linter/linter.js [hunk 3]
```diff
@@ -9256,6 +9258,147 @@ describe("Linter with FlatConfigArray", () => {
...
+
+        it("should ignore external files with Windows paths", () => {
+            const configs = createFlatConfigArray(
+                { files: ["**/*.js"] },
+                { basePath: "C:\\foo" }
+            );
+
+            configs.normalizeSync();
+            const messages1 = linter.verify("foo", configs, "C:\\foo\\bar.js", true);
+            const messages2 = linter.verify("foo", configs, "D:\\foo\\bar.js", true);
```
Comment (mdjermanovic) [inline tests/lib/linter/linter.js:9395]:
```suggestion
            const messages1 = linter.verify("foo", configs, "C:\\foo\\bar.js");
            const messages2 = linter.verify("foo", configs, "D:\\foo\\bar.js");
```

File: tests/lib/linter/linter.js (hunk 2 above)
Comment (fasttime) [reply tests/lib/linter/linter.js]: Good catch! I fixed all usages in 4eb8d116895104b6c931c29328c60a3e58b06fc2.

**Review by mdjermanovic — DISMISSED** [review]
LGTM, thanks! Would like @nzakas to verify before merging.

File: tests/lib/eslint/eslint.js [hunk 4]
```diff
@@ -2937,6 +2967,117 @@ describe("ESLint", () => {
...
+                // https://github.com/eslint/eslint/issues/18575
+                describe("on Windows", () => {
+                    if (os.platform() !== "win32") {
+                        return;
+                    }
+
+                    let otherDriveLetter;
+                    const exec = util.promisify(require("node:child_process").exec);
+
+                    before(async () => {
```
Comment (nzakas) [inline tests/lib/eslint/eslint.js:2979]: Can you add a comment here explaining what's happening? I'm not quite sure I get it now, and I'm sure in another year I'll have no idea. :smile:

**Review by mdjermanovic — APPROVED** [review]

File: tests/lib/eslint/eslint.js (hunk 4 above)
Comment (fasttime) [reply tests/lib/eslint/eslint.js:2983]: I added comments in 31938bed6b11c61b18cbea9030c36da1fc8fa230. Hope it's clearer now.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks.
