### PR TITLE
Fix: Curly rule doesn't account for leading comment (fixes #7538)

### LINKED ISSUE #7538: `curly` and comments
**Tell us about your environment**

* **ESLint Version:** 3.9.1
* **Node Version:** 4.5.0
* **npm Version:** 2.15.11

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```
"curly": [2, "multi-or-nest", "consistent"]
```

**What did you do? Please include the actual source code causing the issue.**

```js
if (foo) {
  // some comment
  bar();
}
```

**What did you expect to happen?**
ESLint should not give an error for having a brace because the block is multi-line, however ESLint is treating it as a single-line statement and does not observe the comment.

**What actually happened? Please include the actual, raw output from ESLint.**
`Unnecessary { after 'if' condition.`

ESLint essentially wants no braces which is confusing to myself (and likely other JS readers):

```
if (foo)
  // some comment
  bar();
```

---

I'm happy to work on this bug as my project at work is interested in using this rule. I'm thinking it will be a fairly simple to fix, along the lines of https://github.com/eslint/eslint/pull/6396

### PR DESCRIPTION
**Pull request by wwwillchen**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes https://github.com/eslint/eslint/issues/7538

**What changes did you make? (Give an overview)**
Fixes the curly rule under the "multi-or-nest" setting, includes tests, and updates docs with an example

**Is there anything you'd like reviewers to focus on?**
This only addresses leading comments and not trailing comments, but I think trailing comment is a bit different because the intent is more ambiguous. For example:

```js
if (foo)
  baz();
  // line of comment
bar();
```

It's unclear if the comment is describing the line above or mis-indented and describing the line below. In my experience, intentional trailing comments are rare.

### CODE REVIEW

File: lib/rules/curly.js [hunk 1]
```diff
@@ -290,7 +290,7 @@ module.exports = {
                 }
             } else if (multiOrNest) {
                 if (hasBlock && body.body.length === 1 && isOneLiner(body.body[0])) {
-                    expected = false;
+                    expected = !!(body.body[0].leadingComments && body.body[0].leadingComments.length);
```
Comment (kaicataldo) [inline lib/rules/curly.js]: Can we use `sourceCode.getComments(body.body[0]).leading` instead of `body.body[0].leadingComments`. 

We have a few other cases of incorrectly using the `.leadingComments` property in the codebase, but as we are actively moving towards calculating location of comments relative to nodes in ESLint instead of the parser, this will save us having to change this down the road. Thanks!

Comment (kaicataldo) [inline lib/rules/curly.js]: Can we use sourceCode.getComments(body.body[0]).leading instead of body.body[0].leadingComments?

We have a few other cases of incorrectly using the .leadingComments property in the codebase, but as we are actively moving towards calculating location of comments relative to nodes in ESLint instead of the parser, this will save us having to change this down the road. Thanks!

Comment (wwwillchen) [inline lib/rules/curly.js]: I tried making my modification in `isOneLiner` but it caused unit tests to fail. I think the use of isOneLiner in L294 makes modifying the `isOneLiner` function different than my current change.

Comment (wwwillchen) [inline lib/rules/curly.js]: Done.

File: lib/rules/curly.js [hunk 2]
```diff
@@ -290,7 +290,9 @@ module.exports = {
                 }
             } else if (multiOrNest) {
                 if (hasBlock && body.body.length === 1 && isOneLiner(body.body[0])) {
-                    expected = false;
+                    const leadingComments = sourceCode.getComments(body.body[0]).leading;
+
+                    expected = !!(leadingComments && leadingComments.length);
```
Comment (kaicataldo) [inline lib/rules/curly.js]: This check should be able to just be `expected = !!(leadingComments.length)` now, since `sourceCode.getComments()` will return an empty array if none are found

Comment (wwwillchen) [inline lib/rules/curly.js]: Done

File: lib/rules/curly.js [hunk 3]
```diff
@@ -290,7 +290,9 @@ module.exports = {
                 }
             } else if (multiOrNest) {
                 if (hasBlock && body.body.length === 1 && isOneLiner(body.body[0])) {
-                    expected = false;
+                    const leadingComments = sourceCode.getComments(body.body[0]).leading;
+
+                    expected = !!leadingComments.length;
```
Comment (nzakas) [inline lib/rules/curly.js]: Can you use `leadingComments.length > 0` instead? I prefer to be explicit about the expectation here.

Comment (wwwillchen) [inline lib/rules/curly.js]: Done.
