### PR TITLE
Fix: Keyword "else" must not be followed by a newline (fixes #3226)

### LINKED ISSUE #3226: Keyword "else" must not be followed by a newline
The fix for #3198 has created a quirk in the way the `else` keyword is handled.

`"space-after-keywords": [2, "always"]` with the following code:

```js
if (a == null)
  doThing()
else
  doOtherThing()
```

Results in the error: `Keyword "else" must not be followed by a newline`

I believe this rule of strictly being a space is really intended to be applied to keywords where the next token is `(` or `{` – as in `if(something)` or `else{ whatever() }`

### PR DESCRIPTION
**Pull request by BYK**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM

File: lib/rules/space-after-keywords.js [hunk 1]
```diff
@@ -23,6 +23,10 @@ module.exports = function(context) {
      * @returns {void}
      */
     function checkTokens(node, left, right) {
+        if (right.type !== "Punctuator") {
```
Comment (btmills) [inline lib/rules/space-after-keywords.js]: This could cause duplicate warnings with brace-style. What happens on line 38 if we add a check whether the right token is an opening paren?

Comment (BYK) [inline lib/rules/space-after-keywords.js]: Not sure how this would increase the warnings created since it actually only filters any existing warnings. Any duplicate warnings should already be in the code and I'd argue fixing that is not in the scope of this issue/PR.

Comment (nzakas) [inline lib/rules/space-after-keywords.js]: Let's go with this and see what happens. We can always fix an extra message later if necessary.
