### PR TITLE
Fix: Improves perf of globbing by inheriting glob.GlobSync (fixes #6710)

### LINKED ISSUE #6710: .eslintignore patterns are not excluded from globbing, so performance can be very slow
**What version of ESLint are you using?**
v3.1.1

**What parser (default, Babel-ESLint, etc.) are you using?**
Default (espree?)

**Please show your full configuration:**

In .eslintignore:

    /some/folder/with/lots/of/files/**

**What did you do? Please include the actual source code causing the issue.**
run `eslint .`

**What did you expect to happen?**
eslint should be quick, since I've excluded folders via `.eslintignore`.

**What actually happened? Please include the actual, raw output from ESLint.**
eslint takes a long time, since it still globs all folders even if they're in .eslintignore.

This is a follow-on from #5679.  The fix for that one excluded "DEFAULT_IGNORE_DIRS" from globbing, which was a good start.

However, if your project has large folders outside of the default ones, globbing will still take a long time even if you specify them in .eslintignore.

Including all patterns from .eslintignore speeds things up a lot.  The goal is to exclude the patterns in .eslintignore from globbing, just like we do with DEFAULT_IGNORE_DIRS already.

### PR DESCRIPTION
**Pull request by kaelzhang**
**What issue does this pull request address?**
As #6710 discussed, I create a subclass of `glob.GlobSync` to skip certain glob process according to .gitignore rules.

**What changes did you make? (Give an overview)**
- inherits `glob.GlobSync` and overrides `_readdir`, special thanks to the good idea of @mysticatea. But there are several detail things we should aware of, see the inline comments of the commit.
- change `ignoredPaths.getIgnoredFoldersGlobPatterns()` -> `ignoredPaths.getIgnoredFoldersGlobChecker()`, and now it will return a function.

**Is there anything you'd like reviewers to focus on?**
Do I need to create a specific test cases file for `lib/glob.js`? Or just testing it with `glob-util.js` is ok? I did create a test file, because I thought there was much duplication with `tests/lib/glob-util.js`

If it is necessary, I will add one.

### CODE REVIEW

File: lib/util/glob.js [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+
+var Sync = require("glob").GlobSync,
+    path = require("path"),
+    util = require("util");
+
+//------------------------------------------------------------------------------
+// Private
+//------------------------------------------------------------------------------
+
+var IGNORE = typeof Symbol === "function" ? Symbol("ignore") : "_shouldIgnore";
```
Comment (mysticatea) [inline lib/util/glob.js]: Node.js supports symbols since 0.12. ESLint requires `>=Node 4`, so we can use symbols always.

> http://node.green/#Symbol

File: lib/util/glob.js [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+
+/**
+ * Subclass of `glob.GlobSync`
+ * @param {string}     pattern      Pattern to be matched.
+ * @param {Object}     options      `options` for `glob`
+ * @param {function()} shouldIgnore Method to check whether a directory should be ignored.
+ * @constructor
+ */
+function GlobSync(pattern, options, shouldIgnore) {
```
Comment (mysticatea) [inline lib/util/glob.js]: Also, we can use classes.

> http://node.green/#class

Comment (kaelzhang) [inline lib/util/glob.js]: We cant. `eslint` still targets node 4 which does not support es6 classes. 

Although I usually write packages for node 6 in es8, such as typed variables with the help of babel.  😃

Comment (kaelzhang) [inline lib/util/glob.js]: Yes, we use classes everyday. But eslint uses the code style of prototype. 😈

Comment (mysticatea) [inline lib/util/glob.js]: Those were written while eslint was supporting Node 0.10. Now we can rewrite those. Related to #6407.

**Comment by ilyavolodin** [comment]
This looks a lot better then previous attempt, @kaelzhang could you rebase please? @eslint/eslint-team Can you review this, since this is a pretty impactful change, I'd like to have as many eyes on this as we can? Especially @IanVS and @alberto since you've been dealing with this part of the code lately.

File: lib/ignored-paths.js [hunk 3]
```diff
@@ -192,34 +192,30 @@ IgnoredPaths.prototype.contains = function(filepath, category) {
...
-            return rule.negative;
-        }).map(function(rule) {
-            return rule.origin;
-        });
+    /**
+     * Adds `"*"` at the end of `"node_modules/"`,
+     * so that subtle directories could be re-included by .gitignore patterns
+     * such as `"!node_modules/should_not_ignored"`
+     */
+    var dirs = DEFAULT_IGNORE_DIRS.map(function(dir) {
```
Comment (IanVS) [inline lib/ignored-paths.js]: It looks like both times that `DEFAULT_IGNORE_DIRS` is used we are adding the `*` to the end, so how about just changing `DEFAULT_IGNORE_DIRS`?  Also, the other usage of `DEFAULT_IGNORE_DIRS` adds a leading slash, so maybe the final result should be:

```
 var DEFAULT_IGNORE_DIRS = [
     "/node_modules/*",
     "/bower_components/*"
 ];
```

I do like the note explaining why the `*` is needed, though!

File: lib/util/glob.js [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+
+     * There is a built-in cache about marked `File.Stat` in `glob`, so that we could not worry about the extra invocation of `this._mark()`
+     */
+    var marked = this._mark(abs);
+
+    /**
+     * `node-ignore` only accepts relative paths which are relative to the cwd,
+     * as well as .gitignore file does.
+     */
+    var relative = path.relative(this.cwd, marked);
```
Comment (IanVS) [inline lib/util/glob.js]: Question:

Would the change I proposed in https://github.com/eslint/eslint/issues/6759 have any effect here?  In other words, would `relative` need to be changed so that it is relative to the ignore file location rather than `cwd`?

File: tests/lib/ignored-paths.js [hunk 5]
```diff
@@ -529,50 +529,74 @@ describe("IgnoredPaths", function() {
...
-            var expected = ["node_modules/**", "bower_components/**"];
-            var actual = ignoredPaths.getIgnoredFoldersGlobPatterns();
+            var shouldIgnore = ignoredPaths.getIgnoredFoldersGlobChecker();
 
-            assert.sameMembers(actual, expected);
+            assert.isTrue(shouldIgnore("node_modules/a"));
+            assert.isTrue(shouldIgnore("node_modules/a/b"));
+            assert.isTrue(shouldIgnore("bower_components/a"));
+            assert.isTrue(shouldIgnore("bower_components/a/b"));
+            assert.isFalse(shouldIgnore(".hidden"));
```
Comment (IanVS) [inline tests/lib/ignored-paths.js]: I see these are all relative.  Will it work with absolute paths as well?

File: tests/lib/ignored-paths.js [hunk 6]
```diff
@@ -529,50 +529,74 @@ describe("IgnoredPaths", function() {
...
+
+            assert.isFalse(shouldIgnore("node_modules/package"));
+            assert.isFalse(shouldIgnore("bower_components/package"));
         });
 
-        it("should return dirs with unignored defaults in ignore file when ignore option is disabled", function() {
+        it("should ignore files which we try to re-include in ignore file when ignore option is disabled", function() {
```
Comment (IanVS) [inline tests/lib/ignored-paths.js]: :+1: for clearer test case names.  Well done.

**Comment by IanVS** [comment]
I tried to rebase and got bogged down, so I'm going to wait for @kaelzhang to rebase it.  Then I would like to see how it would play together with https://github.com/eslint/eslint/pull/6844/files.  I don't necessarily anticipate any problems, but it's all pretty related so it would be good to check.

From what I can tell just looking over the code and the tests, this all looks good (with the caveat that I don't fully understand the changes to the glob functionality).

File: tests/lib/ignored-paths.js (hunk 5 above)
Comment (kaelzhang) [inline tests/lib/ignored-paths.js]: gitignore always works with relative paths. 😄

**Comment by kaelzhang** [comment]
@IanVS Sorry that I have been away for a while. I will work on this asap.

**Comment by kaelzhang** [comment]
@IanVS This pr will not solve #6759 which I think should be fixed separately with the current issue.

File: lib/ignored-paths.js [hunk 7]
```diff
@@ -190,34 +190,46 @@ IgnoredPaths.prototype.contains = function(filepath, category) {
...
-    }
+    /**
+     * TODO
+     * 1.
+     * Actually, it should be `this.options.baseDir`, which is the base dir of `ignore-path`,
+     * as well as Line 177.
+     * But doing this leads to a breaking change and fails tests.
+     * Related to #6759
+     */
+    const base = this.options.cwd;
```
Comment (kaelzhang) [inline lib/ignored-paths.js]: In the near future, we need to change this.

File: lib/util/glob.js [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+GlobSync.prototype._readdir = function(abs, inGlobStar) {
+
+    /**
+     * `options.nodir` makes `options.mark` as `true`.
+     * Mark `abs` first
+     * to make sure `"node_modules"` will be ignored immediately with ignore pattern `"node_modules/"`.
+
+     * There is a built-in cache about marked `File.Stat` in `glob`, so that we could not worry about the extra invocation of `this._mark()`
+     */
+    const marked = this._mark(abs);
```
Comment (kaelzhang) [inline lib/util/glob.js]: @IanVS No longer do `path.relative()` here,  so that we could get relative paths to `ignorePath` in the future in `getIgnoredFoldersGlobChecker()`.

**Comment by kaelzhang** [comment]
@IanVS I've made some changes related to #6759 so that there won't be too much changes the day we want to fix the issue.

I also marked a few lines that should be altered later.

**Comment by kaelzhang** [comment]
Appveyor reached a timeout

> Build execution time has reached the maximum allowed time for your plan (60 minutes).

File: lib/ignored-paths.js [hunk 9]
```diff
@@ -190,34 +190,46 @@ IgnoredPaths.prototype.contains = function(filepath, category) {
...
-    let dirs = DEFAULT_IGNORE_DIRS;
+IgnoredPaths.prototype.getIgnoredFoldersGlobChecker = function() {
 
-    if (this.options.ignore) {
+    /**
+     * Adds `"*"` at the end of `"node_modules/"`,
+     * so that subtle directories could be re-included by .gitignore patterns
+     * such as `"!node_modules/should_not_ignored"`
+     */
+    const dirs = DEFAULT_IGNORE_DIRS.map(function(dir) {
```
Comment (IanVS) [inline lib/ignored-paths.js]: It seems my previous comment https://github.com/eslint/eslint/pull/6783#discussion_r73985714 was lost in the rebase.  I still think it would be cleaner to just make the `DEFAULT_IGNORE_DIRS` the way we want them.

**Comment by IanVS** [comment]
@kaelzhang I rebased my https://github.com/eslint/eslint/pull/6844 on top of this branch and it all still works fine.  The code of this PR looks great, but it looks like you need to sign the jQuery CLA before we could merge this.

Also, do you have any performance data to show that speed is improved as a result of these changes?

**Comment by kaelzhang** [comment]
@IanVS Seems that I can't change my full name of jQuery CLA signature, so I had to change my name in git config 😢 

I'll add some performance data later.

**Comment by IanVS** [comment]
Responding to your note from another issue: the code LGTM, but I'm not an official reviewer. Also, I think you were going to try to gather some performance data, is that still possible?  I think it would be helpful.

**Comment by kaelzhang** [comment]
I tested an npm package, [dat](https://npmjs.org/package/dat) which has dependencies (including subtle dependencies).

And the script is:

```
const spawn = require('cross-spawn').sync

const time1 = + new Date

// local eslint created with npm link
spawn('eslint', ['.'], { stdio: 'inherit' })
const time2 = + new Date

// eslint 3.3.0
spawn('./node_modules/.bin/eslint', ['.'], { stdio: 'inherit' })
const time3 = + new Date

console.log(`
eslint npm package, dat:

- eslint latest: ${time2 - time1} ms
- eslint branch: ${time3 - time2} ms
`)

```

Output:

```
eslint npm package, dat:

- eslint 3.3.0 : 1861 ms
- eslint branch: 2709 ms
```

**Comment by IanVS** [comment]
So, am I reading correctly that with this branch it took longer to lint? :-/

**Comment by kaelzhang** [comment]
@IanVS I made a mistake with the last `console.log()`. This branch lints much faster, and the result is not excluded with the lint part (CLI-Engine -> Lint)

**Comment by mysticatea** [comment]
:+1:

**Comment by alberto** [comment]
LGTM, thanks @kaelzhang!

**Comment by ilyavolodin** [comment]
LGTM. Thanks @kaelzhang for your work on this!
