### PR TITLE
Fix: Handle nested disable directive correctly (fixes #9318)

### LINKED ISSUE #9318: `//eslint-disable-line`'s behavior is changed in 4.7.0
**Tell us about your environment**

* **ESLint Version:** 4.7.0
* **Node Version:** 8.4.0
* **npm Version:** 5.4.2

**What parser (default, Babel-ESLint, etc.) are you using?**

- default

**Please show your full configuration:**

- nothing

**What did you do? Please include the actual source code causing the issue.**

```js
/* eslint-disable no-unused-vars */

var foo; // eslint-disable-line no-unused-vars
var bar;

/* eslint-enable no-unused-vars */
```

```
$ eslint test.js --rule no-unused-vars:error
```

**What did you expect to happen?**

No errors as same as `4.6.0`.

**What actually happened? Please include the actual, raw output from ESLint.**

```
~\dev\sandbox> eslint test.js --rule no-unused-vars:error

C:\Users\t-nagashima.MSS\dev\sandbox\test.js
  6:5  error  'bar' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

### PR DESCRIPTION
**Pull request by gyandeeps**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ x ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Fixed a bug where nested eslint disable directive created some issues. Please refer to the linked issue for examples.

**Is there anything you'd like reviewers to focus on?**

* Not very clean (I kinda think - not sure why) but it looks to solve the problem.
* Column calculation threw a 🔧 . 😄

### CODE REVIEW

File: lib/util/apply-disable-directives.js [hunk 1]
```diff
@@ -68,22 +68,38 @@ module.exports = options => {
...
         while (
             nextDirectiveIndex < processedDirectives.length &&
             compareLocations(processedDirectives[nextDirectiveIndex], problem) <= 0
         ) {
-            const directive = processedDirectives[nextDirectiveIndex++];
+            directive = processedDirectives[nextDirectiveIndex++];
 
             switch (directive.type) {
+                case "disable-line":
+                    tempDisabledByLine.add(directive.ruleId === null ? "all" : directive.ruleId);
```
Comment (not-an-aardvark) [inline lib/util/apply-disable-directives.js]: This will fail if someone creates a rule with the id `"all"`.

File: lib/util/apply-disable-directives.js [hunk 2]
```diff
@@ -104,11 +121,17 @@ module.exports = options => {
...
-            !globalDisableActive && !disabledRules.has(problem.ruleId)
+            enabledRules.has(problem.ruleId) ||
+            (!tempDisabledByLine.has("all") && !tempDisabledByLine.has(problem.ruleId) &&
+            !globalDisableActive && !disabledRules.has(problem.ruleId))
         ) {
             problems.push(problem);
         }
+
+        lineDisabledRules.set(problem.line, {
+            column: directive.column || 0,
```
Comment (not-an-aardvark) [inline lib/util/apply-disable-directives.js]: Why does the column matter here? `eslint-disable-line` comments should apply to the entire line, regardless of where they're placed on the line.

File: lib/util/apply-disable-directives.js [hunk 3]
```diff
@@ -68,22 +68,38 @@ module.exports = options => {
 
     // enabledRules is only used when there is an active global /* eslint-disable */ comment.
     const enabledRules = new Set();
+    const lineDisabledRules = new Map();
 
     for (const problem of options.problems) {
+        let tempDisabledByLine = new Set();
```
Comment (not-an-aardvark) [inline lib/util/apply-disable-directives.js]: I don't understand the name of this comment -- why is it `temp`?

File: lib/util/apply-disable-directives.js [hunk 4]
```diff
@@ -68,22 +68,38 @@ module.exports = options => {
...
+        let directive = {};
+        const lineDisabledRule = lineDisabledRules.get(problem.line);
```
Comment (not-an-aardvark) [inline lib/util/apply-disable-directives.js]: Why are `enable-line` directives needed if we are filtering by line here anyway?

Comment (gyandeeps) [reply lib/util/apply-disable-directives.js]: Because sometimes there would be no code on a disabled line and then next line would have code with violations. That would only for some unique scenarios like this one https://github.com/eslint/eslint/blob/22bf943548bc83553111814f1cddccd223b9a35f/tests/lib/util/apply-disable-directives.js#L352

**Comment by not-an-aardvark** [comment]
@gyandeeps I made a few modifications to your implementation in https://github.com/eslint/eslint/pull/9323, which makes the implementation a bit simpler. Feel free to merge that if you're okay with those changes (the base branch of https://github.com/eslint/eslint/pull/9323 is your `issue9318` branch).

**Comment by not-an-aardvark** [comment]
@gyandeeps I made another PR onto this branch: https://github.com/eslint/eslint/pull/9324

File: tests/lib/util/apply-disable-directives.js [hunk 5]
```diff
@@ -343,19 +388,6 @@ describe("apply-disable-directives", () => {
                 []
             );
         });
-
-        it("keeps problems on the next line if there is an eslint-enable comment before the problem on the next line", () => {
```
Comment (gyandeeps) [inline tests/lib/util/apply-disable-directives.js]: Sorry for the confusion... I dont think we should remove this test...
This behavior in this test does make sense....

Comment (not-an-aardvark) [reply tests/lib/util/apply-disable-directives.js]: Really? I think the behavior is sort of strange -- this is the only place where the "block" directives and the "line" directives interact with each other. I think it makes more sense for them to be separate, and people can just use `/* eslint-disable */` rather than `// eslint-disable-line` if they only want to disable part of a line.

Comment (not-an-aardvark) [reply tests/lib/util/apply-disable-directives.js]: We should probably decide about the correct behavior here. I think the version that's currently on this PR is the most reasonable choice (and at very least it's better than the version on master). If there is going to be a patch release tomorrow, then I think we should either decide this quickly or merge the PR as-is and decide it later.
