### PR TITLE
Fix: Make `no-implicit-coercion` smarter about numerical expressions

### LINKED ISSUE #3510: 1 * 1234 triggers no-implicit-coercion
I understand that `1 * 1234` is probably code smell, but `no-implicit-coercion` does not seem to be the right kind of warning to trigger, as `1234` is already a `Number`.

ESLint: `v1.1.0`
Configuration: `"no-implicit-coercion": 2`
Full error: `use 'Number(1234)' instead. (no-implicit-coercion)`

### PR DESCRIPTION
**Pull request by BYK**
Fixes #3510

### CODE REVIEW

**Comment by BYK** [comment]
If we're happy with this "smarter" (or more comprehensive to be accurate) approach, we should probably extend that to string concatenation too.

File: tests/lib/rules/no-implicit-coercion.js [hunk 1]
```diff
@@ -46,6 +51,15 @@ ruleTester.run("no-implicit-coercion", rule, {
         {code: "+foo.bar", errors: [{message: "use `Number(foo.bar)` instead.", type: "UnaryExpression"}]},
         {code: "1*foo", errors: [{message: "use `Number(foo)` instead.", type: "BinaryExpression"}]},
         {code: "foo*1", errors: [{message: "use `Number(foo)` instead.", type: "BinaryExpression"}]},
+        {code: "1234*foo*1", errors: [{message: "use `Number(foo)` instead.", type: "BinaryExpression"}]},
+        {code: "1234*1*foo", errors: [{message: "use `Number(foo)` instead.", type: "BinaryExpression"}]},
+        {code: "1234*bar*1*foo", errors: [
+            {message: "use `Number(bar)` instead.", type: "BinaryExpression"},
+            {message: "use `Number(foo)` instead.", type: "BinaryExpression"}
+        ]},
+        {code: "1234*1*foo*bar", errors: [{message: "use `Number(foo)` instead.", type: "BinaryExpression"}]},
```
Comment (BYK) [inline tests/lib/rules/no-implicit-coercion.js]: Not sure if this one not being reported is a bug or not since `bar` is not in direct contact with `1`. If we are okay with this one I should add one more valid test case for `1234 * Number(bar) * 1 * Number(foo)`.

**Comment by mysticatea** [comment]
Thank you!
I found my fault, `+1234` is warned by this rule...

File: tests/lib/rules/no-implicit-coercion.js [hunk 2]
```diff
@@ -28,6 +28,11 @@ ruleTester.run("no-implicit-coercion", rule, {
         {code: "~foo"},
         {code: "-foo"},
         {code: "2 * foo"},
+        {code: "1 * 1234"},
```
Comment (mysticatea) [inline tests/lib/rules/no-implicit-coercion.js]: I want to warn this pattern with a message like `This "1*" is no effect.`...
But I'm not sure it should do in this rule.

File: lib/rules/no-implicit-coercion.js [hunk 3]
```diff
@@ -56,17 +56,53 @@ function isBinaryNegatingOfIndexOf(node) {
...
 
 /**
+ * Checks whether the result of a node is numeric or not
+ * @param {ASTNode} node The node to test
+ * @returns {boolean} true if the node is a number literal or a `Number()` call
+ */
+function isNumeric(node) {
+    return (
+        node.type === "Literal" && typeof node.value === "number" ||
+        node.type === "CallExpression" && node.callee.name === "Number"
```
Comment (mysticatea) [inline lib/rules/no-implicit-coercion.js]: ...And there are `parseInt` and `parseFloat` in the spec.

Comment (BYK) [inline lib/rules/no-implicit-coercion.js]: Ah, correct. I should add those too!

File: tests/lib/rules/no-implicit-coercion.js (hunk 2 above)
Comment (BYK) [inline tests/lib/rules/no-implicit-coercion.js]: I think that can be in `no-useless-expression` or something. This is not a coercion so we shouldn't warn. What do you think?

**Comment by BYK** [comment]
@mysticatea - Updated per your suggestions and added some more tests.

File: tests/lib/rules/no-implicit-coercion.js (hunk 2 above)
Comment (mysticatea) [inline tests/lib/rules/no-implicit-coercion.js]: Sounds good to me.
`no-useless-expression` seems to include #3506.

File: tests/lib/rules/no-implicit-coercion.js (hunk 1 above)
Comment (nzakas) [inline tests/lib/rules/no-implicit-coercion.js]: These seem wrong to me. Multiplying by 1 might be unnecessary, but that's not really the point of this rule.

Comment (BYK) [inline tests/lib/rules/no-implicit-coercion.js]: It is not about being unnecessary. It is about casting the variable. Anywhere `1 * something` is a potential casting.

**Comment by ilyavolodin** [comment]
LGTM

File: tests/lib/rules/no-implicit-coercion.js (hunk 1 above)
Comment (nzakas) [inline tests/lib/rules/no-implicit-coercion.js]: Yes, in situations like `foo*1`. In situations like `1234*foo*1`, it's just unnecessary since the casting happens via `1234*` anyway. I'm saying I don't think this situation should be flagged by this rule because it's not casting.

Comment (BYK) [inline tests/lib/rules/no-implicit-coercion.js]: Okay, fair concern. I'll update the patch accordingly.
