### PR TITLE
Fix extending @scope/eslint/file

### LINKED ISSUE #4800: NPM scope not working when targeting files.
https://github.com/eslint/eslint/pull/3136 gave us support for user scoped npm packages but it doesn't support targeting specific files.

Consider the following eslint-config package structure:

```
rules/
   best-pratices.js
   errors.js
   ...
es5.js
es6.js
index.js
```

Using `"extends": "@satazor"` works great because it uses the `index.js` file but using `@satazor/es5` or `@satazor/eslint-config/es5` results in an error:

` Error: Cannot find module '@satazor/eslint-config-es5' `
` Error: Cannot find module '@satazor/eslint-config-eslint-config/es5' `

Is this expected or a bug? If it is expected how I am able to extend the `es5.js` configuration?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29382988-npm-scope-not-working-when-targeting-files?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by satazor**
Based on the master branch.
Fixes #4800

### CODE REVIEW

**Comment by satazor** [comment]
Not yet ready, do not merge.

**Comment by satazor** [comment]
All good, can be merged.

**Comment by gyandeeps** [comment]
In your commit message can you please mention the correct issue number and not 1234.

**Comment by satazor** [comment]
Oh sorry it was copy paste.. damn

**Comment by satazor** [comment]
Same fix but for the 1.x branch: https://github.com/eslint/eslint/pull/4804

**Comment by gyandeeps** [comment]
LGTM.

**Comment by satazor** [comment]
No problem, it is my Xmas gift for the project :)

File: lib/config/config-file.js [hunk 1]
```diff
@@ -360,8 +360,9 @@ function resolve(filePath) {
             var scopedPackageShortcutRegex = /^(@[^\/]+)(?:\/(?:eslint-config)?)?$/;
             if (scopedPackageShortcutRegex.test(filePath)) {
                 filePath = filePath.replace(scopedPackageShortcutRegex, "$1/eslint-config");
-            } else if (filePath.split("/")[1].indexOf("eslint-config-") !== 0) {
-                // for scoped packages, insert the eslint-config after the first /
+            } else if (!/^eslint-config(-|$)/.test(filePath.split("/")[1])) {
```
Comment (ilyavolodin) [inline lib/config/config-file.js]: Sorry, I'm not really up to date on scoped npm packages. Are you saying that scoped package should always be in format `@something/eslint-config/foo`? It can't be simply `@something/eslint-config`?

Comment (ljharb) [inline lib/config/config-file.js]: @ilyavolodin `@something/eslint-config` would be the package, `foo.js` would be a file inside it.

Comment (ljharb) [inline lib/config/config-file.js]: By default, you'd use `@something` or `@something/eslint-config` to point to that package's "main" file.

File: tests/lib/config.js [hunk 2]
```diff
@@ -884,6 +884,38 @@ describe("Config", function() {
...
+                expected = {
+                    rules: { "quotes": [2, "double"], "eqeqeq": 2, "valid-jsdoc": 0 },
+                    env: { "browser": false }
+                };
+
+            // Reason to override this function in this special case is that I don't want it to keep looking into the
+            // chain of parent directories for .eslintrc or package.json file for configs.
+            // If that is allowed then the expected outcome will change based on the machine you are running this test.
+            sinon.stub(configHelper, "findLocalConfigFiles").returns([
+                path.resolve(__dirname, "../fixtures/config-extends/scoped-package9/.eslintrc")
```
Comment (btmills) [inline tests/lib/config.js]: You should just be able to put `"root": true` in the fixture.

Comment (satazor) [inline tests/lib/config.js]: Agree, this was copy pasted from other test. Should I add root also to those or just mine?

Comment (btmills) [inline tests/lib/config.js]: Ah I see that this is duplicated from other tests. I'm guessing support for extending configs was written before we supported the root option. If it's as simple as adding the root option and deleting these stubs, can you update these?

Comment (btmills) [inline tests/lib/config.js]: Yeah if that will work, please do update them all.

**Comment by btmills** [comment]
@satazor did you sign the CLA? I don't have access to the responses to check.

@nzakas how hard would it be for the bot to update PRs when someone signs?

**Comment by satazor** [comment]
@btmills Yes I did but was after the PR.

File: tests/lib/config.js (hunk 2 above)
Comment (satazor) [inline tests/lib/config.js]: @btmills I can't find the reason for these tests to have `useEslintrc: true`.. if it was set to `false` neither `root` or that hackish stub need to be there..

Comment (btmills) [inline tests/lib/config.js]: That's a great point. Just to be sure: @eslint/eslint-team can you see any reason @satazor can't set `useEslintrc` to `false` and get rid of the `findLocalConfigFiles` stub for these tests?

Comment (nzakas) [inline tests/lib/config.js]: Nope, that should work.

**Comment by nzakas** [comment]
@btmills it's a bit tricky. To do it accurately, I'd need to get notified of a change from Google docs. I could also cheat and always check signatures every time a PR is updated with code or a comment.

File: tests/lib/config.js (hunk 2 above)
Comment (satazor) [inline tests/lib/config.js]: I've made the adjustments but not yet committed because of the test with the label "should extend package configuration with sub directories". The test appears to assert that when targeting a file, the config should look for the .eslintrc file in the parent directory automatically, which extends another config (hence `useEslintrc` is set to true there). Though, `configFile` is being passed explicitly which feels wrong and will make the test to pass, even if the config is not being loaded correctly. Am I missing something?

The test should be:

```js
        it("should extend package configuration with sub directories", function() {

            var configDeps = {};
            configDeps["./config/config-file"] = proxyquire("../../lib/config/config-file", {
                "eslint-config-foo": {
                    rules: {
                        "eqeqeq": 2
                    }
                }
            });

            var StubbedConfig = proxyquire("../../lib/config", configDeps);

            var configHelper = new StubbedConfig({ useEslintrc: true, cwd: process.cwd() }),
                expected = {
                    rules: { "quotes": [2, "double"], "eqeqeq": 2, "valid-jsdoc": 0 },
                    env: { "browser": false }
                },
                actual = configHelper.getConfig(path.resolve(__dirname, "../fixtures/config-extends/package2/subdir/foo.js"));

            assertConfigsEqual(actual, expected);
        });
```

Also the `root: true` should be added to package2.json.

*Note*: In fact, I think the `root:true` should be added to all fixtures by default, unless there's a specific reason no to.

Comment (satazor) [inline tests/lib/config.js]: @nzakas @btmills I've committed the changes, please take a look at my previous comment.

File: tests/fixtures/config-extends/package3/subdir/foo.js [hunk 3]
```diff
@@ -1 +0,0 @@
-var a = 1;
```
Comment (satazor) [inline tests/fixtures/config-extends/package3/subdir/foo.js]: This package was copied from package2.. this file was not being used in any test.

File: tests/lib/config.js (hunk 2 above)
Comment (nzakas) [inline tests/lib/config.js]: Looks like that test was added for https://github.com/eslint/eslint/issues/2487

@gyandeeps can you comment on this?

Comment (gyandeeps) [inline tests/lib/config.js]: Long time down the memory lane, to provide the config file as well have `.eslintrc` file is perfectly fine. As in that case it will again reload the same config path because of `.eslintrc` set to true. The line which said that its a noop is not noop as the unit test is trying to test the caching issue we had before. Thats why I call the `getConfig` function on the same object of class more than once.

Comment (satazor) [inline tests/lib/config.js]: I'm still a bit confused about the test, but this is out of the scope of this PR. I will revert the changes of that specific test so this can be merged.

Comment (satazor) [inline tests/lib/config.js]: Done!

File: tests/lib/config.js [hunk 4]
```diff
@@ -994,20 +1018,12 @@ describe("Config", function() {
...
-            // Reason to override this function in this special case is that I dont want it to keep looking into the
-            // chain of parent directries for .eslintrc or package.json file for configs.
-            // If that is allowed then the expected outcome will change based on the machine you are running this test.
-            sinon.stub(configHelper, "findLocalConfigFiles").returns([
-                path.resolve(__dirname, "../fixtures/config-extends/package3/.eslintrc")
-            ]);
-
-            var actual = configHelper.getConfig(configPath);
+                },
+                actual = configHelper.getConfig(configPath);
```
Comment (nzakas) [inline tests/lib/config.js]: Isn't this the one that should be reverted to its state on master?

Comment (satazor) [inline tests/lib/config.js]: No, this one is simply the ones that don't need `useEslintrc` at all as discussed before.

Comment (nzakas) [inline tests/lib/config.js]: Got it, thanks.

**Comment by nzakas** [comment]
Lgtm

**Comment by satazor** [comment]
@nzakas can we cherry-pick this PR's commit and (this one)[https://github.com/eslint/eslint/issues/4229#issuecomment-167324323] to 1.x as well and release a new version?

**Comment by satazor** [comment]
@nzakas Bump! It really need this fix without using an unstable 2.x version :( Is there any chance you could cherry-pick this to 1.x branch please?

**Comment by deepsweet** [comment]
+1 for porting this to 1.x. is it possible?

**Comment by nzakas** [comment]
Please open an issue for this request. I can't promise anything, but I'll look into it this week.

**Comment by spencerhakim** [comment]
Not sure if anyone opened an issue about it yet (didn't find one), but +1 to backporting, please.
