### PR TITLE
Fix: no-implicit-coercion should not fix ~. Fixes #7272

### LINKED ISSUE #7272: no-implicit-coercion autofixer can change logic
**Tell us about your environment**

* **ESLint Version:** 3.6.1
* **Node Version:** 6.7.0
* **npm Version:** 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```yaml
rules:
  no-implicit-coercion: error
```

**What did you do? Please include the actual source code causing the issue.**

Ran `eslint --fix` on:

```js
const catNoises = ["meow", "hiss", "purr"];

if (!~catNoises.indexOf("purr")) {
  console.log("no purr");
} else {
  console.log("yes purr");
}
```

**What did you expect to happen?**

Expected ESLint to autofix the code to:

```js
const catNoises = ["meow", "hiss", "purr"];

if (catNoises.indexOf("purr") === -1) {
  console.log("no purr");
} else {
  console.log("yes purr");
}
```

Or just report the problem without trying to autofix it.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint autofixed the code to:

```js
const catNoises = ["meow", "hiss", "purr"];

if (!catNoises.indexOf("purr") !== -1) {
  console.log("no purr");
} else {
  console.log("yes purr");
}
```

This autofix changes the logic of the code significantly.

### PR DESCRIPTION
**Pull request by TheSavior**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

https://github.com/eslint/eslint/issues/7272

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- [x] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**
no-implic-coercion now only makes recommendations and will not attempt to fix anything using the `~` operator.

**Is there anything you'd like reviewers to focus on?**
Nope

### CODE REVIEW

File: lib/rules/no-implicit-coercion.js [hunk 1]
```diff
@@ -224,7 +224,13 @@ module.exports = {
                 if (!operatorAllowed && options.boolean && isBinaryNegatingOfIndexOf(node)) {
                     const recommendation = `${sourceCode.getText(node.argument)} !== -1`;
 
-                    report(node, recommendation);
+                    context.report({
```
Comment (nzakas) [inline lib/rules/no-implicit-coercion.js]: This is a duplicate of lines 198 to 203. Instead of duplicating those lines, maybe just add an extra parameter to `report()` indicating if it should be fixed? (I just generally prefer to have messages centralized.)

Comment (TheSavior) [inline lib/rules/no-implicit-coercion.js]: That's a good call
