### PR TITLE
Fix: Comment configuration of rule doesn't work (fixes #1792)

### LINKED ISSUE #1792: Comment configuration of rule doesn't work
Thanks for bringing in the `indent` rule. :+1: 

It works perfectly fine in all scenarios except when I activate the rule like this 
`/* eslint indent: [2, 4, {indentSwitchCase: true}] */`
And this is when I declare this rule on top of the file. Then it doesn't work.

It also breaks my inline eslint config.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8386158-comment-configuration-of-rule-doesn-t-work?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ilovejary**
Added errors to messages queue if parsing fails. Also, JSON parse-function actually checks for whether or not double quotes are used and adds them if not, however, camel-cased rule-names wouldn't be recognized.

### CODE REVIEW

File: tests/lib/eslint.js [hunk 1]
```diff
@@ -1741,10 +1741,14 @@ describe("eslint", function() {
...
 
             var messages = eslint.verify(code, config, filename);
-            assert.equal(messages.length, 1);
-            assert.equal(messages[0].ruleId, "no-alert");
-            assert.equal(messages[0].message, "Unexpected alert.");
-            assert.include(messages[0].nodeType, "CallExpression");
+            assert.equal(messages.length, 2);
+
+            // The incorrectly formatted comment triggered a warning
+            assert.equal(messages[0].severity, 2);
```
Comment (nzakas) [inline tests/lib/eslint.js]: You should check the error message and location to be sure it's the one you're expecting

File: lib/eslint.js [hunk 2]
```diff
@@ -265,13 +272,29 @@ function modifyConfigsFromComments(ast, config, reportingConfig) {
...
                     case "eslint":
-                        var items = parseJsonConfig(value);
-                        Object.keys(items).forEach(function(name) {
-                            var ruleValue = items[name];
-                            if (typeof ruleValue === "number" || (Array.isArray(ruleValue) && typeof ruleValue[0] === "number")) {
-                                commentRules[name] = ruleValue;
-                            }
-                        });
+                        try {
+
```
Comment (nzakas) [inline lib/eslint.js]: Maybe move all this info parseJsonConfig? This is the only case that does more than a single function call.

**Comment by ilovejary** [comment]
Made changes but Travis is failing now; local npm test is OK. Did I miss something? Looks like related to this:

Error loading resource file:///home/travis/build/eslint/eslint/node_modules/sinon/pkg/sinon-1.12.2.js (203). Details: Error opening /home/travis/build/eslint/eslint/node_modules/sinon/pkg/sinon-1.12.2.js: No such file or directory

**Comment by lo1tuma** [comment]
See #1947

**Comment by nzakas** [comment]
Can you rebase? That should fix it.

File: lib/eslint.js [hunk 3]
```diff
@@ -54,18 +54,40 @@ function parseBooleanConfig(string) {
...
+        commentRules = {};
+    comments = comments.replace(/([a-zA-Z0-9\-\/]+):/g, "\"$1\":").replace(/(\]|[0-9])\s+(?=")/, "$1,");
     try {
-        items = JSON.parse("{" + string + "}");
-    } catch(e) { }
 
-    return items;
+        items = JSON.parse("{" + comments + "}");
+
+        Object.keys(items).forEach(function(name) {
```
Comment (nzakas) [inline lib/eslint.js]: Why was this moved to here? It doesn't seem to fit with the rest of the function (this isn't "parsing").

Comment (ilovejary) [inline lib/eslint.js]: Thought that's what was suggested in previous commit. Maybe misunderstood. You mean to keep the function that does actual parsing separate still?

Comment (nzakas) [inline lib/eslint.js]: Ah sorry, I can see how my comment on the previous commit was unclear. What I meant was to move the `try-catch` and creation of the error message into `parseJsonConfig()`, so that at this spot, you could just use the result.

Comment (ilovejary) [inline lib/eslint.js]: Got it. Will do.

**Comment by ilovejary** [comment]
Let me know if I got it right.

**Comment by nzakas** [comment]
Looks great, thanks!
