### PR TITLE
Fix: Cache file error handling on read-only file system.

### LINKED ISSUE #11945: Trying to delete non-existent .eslintcache on read-only file system
**Tell us about your environment**

* **ESLint Version:** 6.0.1
* **Node Version:** 8.9.4
* **npm Version:** 4.6.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    "extends": "eslint:recommended"
};
```

</details>

**What did you do?**
Wanted to try out ESLint 6.* by running it on a simple file within Docker.

However it's trying to delete a non-existent file on a read-only part of the system (root directory of the project). While **build/node_modules** and **src/** do have both read/write permissions.

Pretty sure this would be the case for any other restricted permission file system, for me it just happened to be in Docker.

```js
function hello(){
  console.log('world')
}

hello();
```

```bash
build/node_modules/.bin/eslint --config .eslintrc.js src/test.js
```

**What actually happened?**
It seems that it tries to delete the **.eslintcache** file, which does not exist, on a read-only file system.

```
Error: EROFS: read-only file system, unlink '/project/.eslintcache'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at CLIEngine.executeOnFiles (/project/build/node_modules/eslint/lib/cli-engine/cli-engine.js:735:20)
    at Object.execute (/project/build/node_modules/eslint/lib/cli.js:209:111)
    at Object.<anonymous> (/project/build/node_modules/eslint/bin/eslint.js:78:28)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
```

**What did you expect to happen?**
For it to run the linter on the specified file. It should not bother trying to delete a file which does not exist.

### PR DESCRIPTION
**Pull request by cuki**
**What is the purpose of this pull request?**

[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

Fixes #11945.

**What changes did you make?**
Add additional exception for `EROFS` (when cache file does not exist) next to the already existing `ENOENT` exception upon trying to delete cache file.

### CODE REVIEW

File: lib/cli-engine/cli-engine.js [hunk 1]
```diff
@@ -730,14 +730,8 @@ class CLIEngine {
...
         // Delete cache file; should this do here?
-        if (!cache) {
-            try {
-                fs.unlinkSync(cacheFilePath);
-            } catch (error) {
-                if (!error || error.code !== "ENOENT") {
-                    throw error;
-                }
-            }
+        if (!cache && fs.existsSync(cacheFilePath)) {
```
Comment (ilyavolodin) [inline lib/cli-engine/cli-engine.js]: I'm not sure this is sufficient enough to eliminate try/cache. File might exist, for example, but it might be locked. Or the process might not have permissions to delete a file. So I think try/cache is still needed.

Comment (mysticatea) [reply lib/cli-engine/cli-engine.js]: I like to make it ignoring more kinds of errors rather than checking something before the removing because file access is essentially parallel (I.e. other processes can manipulate the file while ESLint is doing).

**Comment by kaicataldo** [comment]
@ilyavolodin @mysticatea Are you confirming this is a bug (you've both commented here but we haven't accepted the issue yet)? Just want to make sure we're all on the same page.

**Comment by ilyavolodin** [comment]
No, I haven't been able to verify it, but I also don't have an environment to verify it in. I'm going purely on code changes.

**Comment by mysticatea** [comment]
Same (I have not reproduced it). But because the current code re-throws IO errors except `ENOENT`, so I think that that's possible. I'm okay if the fix is to ignore more kinds of IO errors.

**Comment by cuki** [comment]
@mysticatea @ilyavolodin I've changed to code to make an exception for `EROFS` (when cache file does not exist) next to the already existing `ENOENT` exception within the catch block.

**Comment by ilyavolodin** [comment]
@cuki Thanks, that looks better to me. But I still don't know how to verify this to mark it accepted. I don't have an environment to do so.

**Comment by cuki** [comment]
@ilyavolodin Here are the steps to reproduce the `EROFS: read-only file system, unlink '/src/.eslintcache'` error and how to test proposed changes.

### 1. Create a "project" directory
Which consists out of the following files:
<details>
<summary>Dockerfile</summary>

```bash
FROM node:8-stretch

RUN mkdir /src

RUN npm install -g eslint@6.0.1

WORKDIR /src

ENTRYPOINT ["/usr/local/bin/eslint"]
```
</details>

<details>
<summary>docker-compose.yml</summary>

```yaml
version: '3.4'
services:
  eslint:
    build: .
    read_only: true
    volumes:
    - .:/src:ro,cached
```
</details>

<details>
<summary>.eslintrc.js</summary>

```js
module.exports = {
    "extends": "eslint:recommended"
};
```

</details>

<details>
<summary>test.js</summary>

```js
function hello(){
  console.log('world')
}

hello();
```
</details>

### 2. Build Docker image
Execute following command inside your "project" directory:
```bash
docker-compose build
```

### 3. Run ESLint in Docker
Stay in your "project" directory and run:
```
docker-compose run --rm eslint --config .eslintrc.js test.js
```

Now you should see something like the following as output:
```
Error: EROFS: read-only file system, unlink '/src/.eslintcache'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at CLIEngine.executeOnFiles (/usr/local/lib/node_modules/eslint/lib/cli-engine/cli-engine.js:735:20)
    at Object.execute (/usr/local/lib/node_modules/eslint/lib/cli.js:209:111)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint/bin/eslint.js:78:28)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

### 4. Test proposed changes
Change **Dockerfile** in your "project" directory to be as followed:

```bash
FROM node:8-stretch

RUN mkdir /src

RUN npm install -g eslint@6.0.1

# Override relevant file with proposed changes
RUN git clone --single-branch -b patch-1 https://github.com/cuki/eslint /tmp/eslint/ && \
    cp /tmp/eslint/lib/cli-engine/cli-engine.js /usr/local/lib/node_modules/eslint/lib/cli-engine/cli-engine.js

WORKDIR /src

ENTRYPOINT ["/usr/local/bin/eslint"]
```

Run ESLint again in Docker:
```
docker-compose run --rm eslint --config .eslintrc.js test.js
```

And notice the output, which threw out an error before, now should be:
```
/src/test.js
  2:3  error  'console' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```

**Comment by cuki** [comment]
@ilyavolodin @mysticatea Did either one of you managed to reproduce the issue (and test proposed changes) using the steps from the above (previous) comment? Would be greatly appreciated to get some feedback to see whether this is an issue with my environment or in general. Thanks!

**Comment by ilyavolodin** [comment]
Sorry, I was not able to test this, I do not have docker installed, and I currently do not have time to go through installation and configuration of a new environment. Maybe somebody else on the team can do it?

**Comment by mysticatea** [comment]
OK, I confirmed it. Thank you!

**Comment by cuki** [comment]
@mysticatea @ilyavolodin Thanks for the quick response and confirming the issue/fix!
