### PR TITLE
Fix: `no-unmodified-loop-condition` false positive (fixes #5445)

### LINKED ISSUE #5445: no-unmodified-loop-condition false positive
Using ESLint 2.2.0, the following code causes a false positive:

```js
/*eslint no-unmodified-loop-condition: 2 */
var a = [1, 2, 3];
var len = a.length;
for (var i = 0; i < len - 1; i++) {}
// produces: `len` is not modified in this loop. (no-unmodified-loop-condition)
```

This is a false positive because `i` is modified in the loop condition. If you replace `len - 1` with `len`, the error disappears.

Reproducible in the [ESLint demo](http://eslint.org/demo/) too. The issue is similar to #5166, but not the same. cc @feross @mysticatea

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #5445.

Previously, this rule has been checking whether every BinaryExpression was modified or not. But this way has been reporting wrong warnings in chaining binary expression (e.g. `foo + bar < baz`).
Now, this rule came to check whether the chain of BinaryExpressions was modified or not.

### CODE REVIEW

File: lib/rules/no-unmodified-loop-condition.js [hunk 1]
```diff
@@ -67,13 +67,13 @@ function isUnmodified(condition) {
 
 /**
  * Checks whether or not a given loop condition info does not have the modified
- * flag and does not have any groups that this condition is belonging to.
+ * flag and does not have the group that this condition is belonging to.
```
Comment (BYK) [inline lib/rules/no-unmodified-loop-condition.js]: Slightly better version:

>flag and does not have the group this condition belongs to.

File: lib/rules/no-unmodified-loop-condition.js [hunk 2]
```diff
@@ -67,13 +67,13 @@ function isUnmodified(condition) {
...
  *
  * @param {LoopConditionInfo} condition - A loop condition info to check.
  * @returns {boolean} `true` if the loop condition info is "unmodified".
  */
 function isUnmodifiedAndNotBelongToGroup(condition) {
-    return !condition.modified && condition.groups.length === 0;
+    return !condition.modified && !condition.group;
```
Comment (BYK) [inline lib/rules/no-unmodified-loop-condition.js]: Now we can do
```js
!(condition.modified || condition.group);
```

**Comment by BYK** [comment]
Not sure if this is the best solution. The problematic part seems like

```js
         // Reports the conditions which are not belonging to groups.
         // Others will be reported after all variables are done.
         conditions
             .filter(isUnmodifiedAndNotBelongToGroup)
             .forEach(report);
```

to me since it goes through all conditions that are unmodified. Isn't a single modified condition is enough to not report?

**Comment by mysticatea** [comment]
If a variable belongs to a group, the variable is warned only when the result of the group isn't modified.
For example:

```js
for (let i = 0, end = list.length; i < end; ++i) {
    foo(list[i]);
}
```

In this case, `end` is not modified in the loop, but the result of `i < end` is modified in the loop, so the `end` isn't warned.
Due to that, a variable which belongs to a group should be evaluated after all variables were addressed.

There was a problem at the way of detecting group the variable is belonging to.
In the `i < end - 1` case, previously, `end` belongs to two group: `i < end - 1` and `end - 1`. Then the result of `end -1` was not modified, so `end` is warned wrongly.

**Comment by BYK** [comment]
Oh, gotcha. I think we should look into changing the name "group" in the future since that's what confused me.

Anyways, LGTM :)
