### PR TITLE
Fix: handle try/catch correctly in `no-return-await` (fixes #7581)

### LINKED ISSUE #7581: no-return-await must be aware of try/catch/finally
`no-return-await` currently doesn't consider if the `return` statement is inside a `try` block. In this case, the presence of `await` does meter.

Consider this:
```js
function asyncLog() {
  return new Promise((resolve) => {
    setTimeout(() => {
      console.log('first log');
      resolve(true);
    }, 1000);
  });
}

async function foo() {
  try {
    return await asyncLog();
    // I really need this await, but no-return-await is complaining about it :(
  } finally {
    console.log('second log');
  }
}

foo();
// first log
// second log


async function bar() {
  try {
    return asyncLog();
  } finally {
    console.log('second log');
  }
}

bar();
// second log
// first log


async function baz() {
  try {
    return asyncLog();
  } catch (error) {
    // if asyncLog() rejects, error will be swallowed because I missed await :(
  }
}
```

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

See https://github.com/eslint/eslint/issues/7581

**What changes did you make? (Give an overview)**

`no-return-await` is intended to flag redundant uses of `await` in returned values. However, if `return await` is used within a `try` block, the `await` is not redundant.

```js
function baz() {
  return Promise.reject('something bad happened');
}

async function foo() {
  try {
    return await baz();
  } catch (err) {
    // error handled
  }
}

async function bar() {
  try {
    return baz();
  } catch (err) {
    // the error won't end up here
  }
}
```

In the above example, `foo()` will return a fulfilled Promise, and `bar()` will return a rejected Promise.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: lib/rules/no-return-await.js [hunk 1]
```diff
@@ -23,6 +25,24 @@ module.exports = {
...
+        * @returns {boolean} `true` if a thrown error will be caught/handled in this function
+        */
+        function hasErrorHandler(node) {
+            if (astUtils.isFunction(node) || node.type === "Program") {
+                return false;
+            }
+            if (node.parent.type === "TryStatement" && (node === node.parent.block || node === node.parent.handler && node.parent.finalizer)) {
+                return true;
+            }
+            return hasErrorHandler(node.parent);
```
Comment (platinumazure) [inline lib/rules/no-return-await.js]: This doesn't really have to be recursive, does it?

Comment (not-an-aardvark) [inline lib/rules/no-return-await.js]: Correct, it could also use a `while` loop. Personally I think recursion is better than a loop in cases like this, but I'm fine with changing it if you feel otherwise.

Comment (platinumazure) [inline lib/rules/no-return-await.js]: If Javascript engines commonly supported tail call optimization or if writing a loop is a pain, I would agree. In this case, though, it seems like a trivial change.

Comment (not-an-aardvark) [inline lib/rules/no-return-await.js]: Well, if the AST's depth is too large, it looks like the parser causes a stack overflow before the rule does anyway:

```js
valid: [
  "(async function() { return await bar; })" + " + 1".repeat(10000)
]

// Parsing error: Maximum call stack size exceeded
```

But I agree it's probably better to just use a `while` loop since we don't have proper tail calls.

**Comment by reywood** [comment]
Looks like the docs need to be updated to include info about this case?
