### PR TITLE
Fix: Exit init early if guide is chosen w/ no package.json (fixes #6476)

### LINKED ISSUE #6476: eslint --init Error
**What version of ESLint are you using?**
v2.13.0
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

**What did you do? Please include the actual source code causing the issue.**
eslint --init
**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? AirBnB
? What format do you want your config file to be in? JSON
Could not find a package.json file. Run 'npm init' to create one.
Error: Could not find a package.json file. Run 'npm init' to create one.
    at check (/usr/local/lib/node_modules/eslint/lib/util/npm-util.js:76:15)
    at Object.checkDevDeps (/usr/local/lib/node_modules/eslint/lib/util/npm-util.js:124:12)
    at installModules (/usr/local/lib/node_modules/eslint/lib/config/config-initializer.js:86:29)
    at getConfigForStyleGuide (/usr/local/lib/node_modules/eslint/lib/config/config-initializer.js:289:5)
    at .completed (/usr/local/lib/node_modules/eslint/lib/config/config-initializer.js:353:26)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/eslint/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.Rx.Subject.addProperties.onCompleted (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:5871:19)
    at Subject.tryCatcher (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:63:31)

### PR DESCRIPTION
**Pull request by kaicataldo**
The output if "guide" is selected without a package.json:
screen shot 2016-06-20 at 12 26 02 am

### CODE REVIEW

File: lib/config/config-initializer.js [hunk 1]
```diff
@@ -342,13 +342,18 @@ function promptUser(callback) {
...
             when: function(answers) {
-                return (answers.source === "guide" || answers.source === "auto");
+                return ((answers.source === "guide" && answers.packageJsonExists) || answers.source === "auto");
             }
         }
     ], function(earlyAnswers) {
 
         // early exit if you are using a style guide
         if (earlyAnswers.source === "guide") {
+            if (!earlyAnswers.packageJsonExists) {
```
Comment (kaicataldo) [inline lib/config/config-initializer.js]: Didn't add tests for this because of https://github.com/eslint/eslint/pull/6478/files#diff-da527c6839c0e6e4d343b5c77fcdd27cR293.

By logging and returning below it exits with a nice message and doesn't show the stack trace

File: lib/config/config-initializer.js [hunk 2]
```diff
@@ -46,7 +46,6 @@ function writeFile(config, format) {
         extname = ".json";
     }
 
-
```
Comment (kaicataldo) [inline lib/config/config-initializer.js]: Random extra line break

**Comment by IanVS** [comment]
LGTM

**Comment by kaicataldo** [comment]
Added do not merge label because the issue is not accepted yet

**Comment by nzakas** [comment]
Issue is accepted. LGTM
