### PR TITLE
Fix: No-shadow rule duplicating error messages (fixes #2706)

### LINKED ISSUE #2706: no-shadow: Duplicated error messages
Now it seems that `no-shadow` rule outputs several identical error messages if variable was shadowed several times:

```js
var a = function(a) {
    return function(a) {
        return function() {
            var a = 123;
            return a;
        };
    };
};

```

```
  4:17  error  a is already declared in the upper scope  no-shadow
  5:20  error  a is already declared in the upper scope  no-shadow
  5:20  error  a is already declared in the upper scope  no-shadow
  7:16  error  a is already declared in the upper scope  no-shadow
  7:16  error  a is already declared in the upper scope  no-shadow
  7:16  error  a is already declared in the upper scope  no-shadow
```

I suppose there should be only three non-duplicated messages

### PR DESCRIPTION
**Pull request by roadhump**

### CODE REVIEW

File: lib/rules/no-shadow.js [hunk 1]
```diff
@@ -109,18 +124,24 @@ module.exports = function(context) {
      * Checks if the given variables are shadowed in the given scope.
      * @param {Array} variables The variables to look for
      * @param {Object} scope The scope to be checked.
-     * @returns {void}
+     * @returns {Array} Variables which are already declared in the given scope.
      */
     function checkShadowsInScope(variables, scope) {
+
+        var shadowVars = [];
```
Comment (gcochard) [inline lib/rules/no-shadow.js]: Might be faster to use a hash, e.g.:

```js
function checkShadowsInScope(variables, scope, reported) {
    //snip...
    if (!reported[variable.name]){
        reported[variable.name] = true;
        context.report(...);
    }
    //snip...
}
```
And then calling this via:
```js
var reported = Object.create(null);
while (upper) {
    checkShadowsInScope(variables, upper, reported);
    upper = upper.upper.
}
```

You'd probably need to attach the location to the `variable.name` value to ensure that you're reporting each location, but you're not diffing two arrays in each scope.

Comment (michaelficarra) [inline lib/rules/no-shadow.js]: Just be careful around variables named `__proto__`, `toString`, etc.

Comment (roadhump) [inline lib/rules/no-shadow.js]: @gcochard I think I just should return passed variables from `checkShadowsInScope` instead of non-passed. I still need list of passed variables in `while` statement to check if any left and interrupt otherwise. Then I can get rid of `diff`.

**Comment by nzakas** [comment]
Lgtm
