### PR TITLE
Fix: no-plusplus allow comma operands in for afterthought (fixes #13005)

### LINKED ISSUE #13005: `no-plusplus` with `'allowForLoopAfterthoughts': true` fails if the afterthought contains multiple `++` or `--` statements
**Tell us about your environment**

* **ESLint Version:** 6.8.0
* **Node Version:** 10.15.3
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
`babel-eslint`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  env: {
    browser: true,
    es6: true,
    jest: true,
    node: true,
    mocha: true,
  },
  extends: [
    'airbnb',
    'eslint:recommended',
    'google',
    'plugin:react/recommended',
    'prettier',
    'prettier/react',
    'plugin:prettier/recommended',
    'plugin:flowtype/recommended',
  ],
  parser: 'babel-eslint',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
      modules: true,
    },
  },
  plugins: ['babel', 'react', 'prettier', 'sort-imports-es6-autofix', 'flowtype'],
  rules: {
    // specifically allowing no-plusplus for for loop afterthoughts
    'no-plusplus': ['error', { 'allowForLoopAfterthoughts': true }],

    // ...all the other rules that aren't relevant to this example
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/* eslint no-plusplus: ["error", { "allowForLoopAfterthoughts": true }] */
// (actually specified in the project's .eslintrc.js, but here for visibility)

const example = [1, 2, 3, 4, 5];

// eslint errors at `i++` and `j++` here
for (let i = 0, j = i + 1; j < example.length; i++, j++) {
  // ...do stuff with example[i] and example[j]
}
```

```bash
$ eslint --ext .js src
```

**What did you expect to happen?**
Expected eslint not to error on `i++` and `j++` because `{ 'allowForLoopAfterthoughts': true }` is specified

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
/path/to/example
  7:48  error  Unary operator '++' used  no-plusplus
  7:53  error  Unary operator '++' used  no-plusplus
```

I was able to fix the warning by changing `i++, j++` -> `i += 1, j += 1`, but this is something of an antipattern.

Yes, there are other ways to write this, i.e.
```js
const example = [1, 2, 3, 4, 5];

// eslint does not fail at `i++` here
for (let i = 0; i < example.length - 1; i++) {
  // ...do stuff with example[i] and example[i + 1]
}

// or

// eslint does not fail at `i++` here
for (let i = 1; i < example.length; i++) {
  // ...do stuff with example[i - 1] and example[i]
}
```
work just fine, but:
a) I'm updating eslint on a large codebase, so I'd prefer to make as few changes as possible.
b) refactors for this simple example aside, this feels like a bug to me.

If this is the intended behaviour because as touched on in the [no-plusplus docs](https://eslint.org/docs/rules/no-plusplus) there are unintended consequences, then I'd suggest updating that doc to specifically call out that you can only override this rule if the for loop afterthought consists _only_ of one single `++` or `--`. (for example, changing the for loop to the hideous `...; i += 1, j++)` as an experiment still errors on `j++` because the afterthought is a larger expression)

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Bug fix

fixes #13005

#### What changes did you make? (Give an overview)

`allowForLoopAfterthoughts` in the `no-plusplus` rule will now additionally allow `++` and `--` in sequence expressions:

```js
/*eslint no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]*/

for (i = 0, j = 0; i < l; i++, j++); // ok
```

Also fixed false negatives when the node isn't the `update` node:

```js
for (i++;;);

for (; i++;);
```

### CODE REVIEW

File: tests/lib/rules/no-plusplus.js [hunk 1]
```diff
@@ -81,6 +85,61 @@ ruleTester.run("no-plusplus", rule, {
...
+            errors: [{
+                messageId: "unexpectedUnaryOp",
+                data: {
+                    operator: "++"
+                },
+                type: "UpdateExpression"
+            }]
+        },
+        {
+            code: "for (;; i++, f(--j));",
```
Comment (yeonjuan) [inline tests/lib/rules/no-plusplus.js]: non-blocking questions for understanding the proper behavior of this option.

It seems the option`{allowForLoopAfterthoughts: true}` changed to allow `update expression`s in `sequence expression`, which has exactly one depth from `for-loop update`.

so the case like ` f(--j)` is warned.

And can I understand the below case(nested sequence expression ) in the same manner?

```js
for (;; (++a, (++b, ++c) ) {}  // it's warned in the PR version. no-plusplus for `b` and `c`
```

File: lib/rules/no-plusplus.js [hunk 2]
```diff
@@ -6,6 +6,34 @@
...
+    return parent.type === "ForStatement" && parent.update === node;
+}
+
+/**
+ * Determines whether the given node is considered to be a for loop "afterthought" by the logic of this rule.
+ * In particular, if it is the update node of a `ForStatement`, or an operand of a sequence expression that is the update node.
+ * @param {ASTNode} node The node to check.
+ * @returns {boolean} `true` if the node is a for loop afterthought.
+ */
+function isForLoopAfterthought(node) {
```
Comment (nzakas) [inline lib/rules/no-plusplus.js]: As @yeonjuan mentioned, it appears that this check only looks up one level, which could mean some patterns will still be flagged as incorrect.

```js
for (;; (++a, (++b, ++c) ) {}  // it's warned in the PR version. no-plusplus for `b` and `c`
```

It may be an unlikely case, but for the sake of completeness, it probably makes sense to continue looking up the AST if the parent is a `SequenceExpression`.

File: tests/lib/rules/no-plusplus.js (hunk 1 above)
Comment (mdjermanovic) [reply tests/lib/rules/no-plusplus.js]: Didn't think of that. It's done now, thanks!

File: lib/rules/no-plusplus.js (hunk 2 above)
Comment (mdjermanovic) [reply lib/rules/no-plusplus.js]: It's done now! It makes sense to me, too.

**Comment by kaicataldo** [comment]
LGTM, thanks!
