### PR TITLE
Fix: Call expression consistency in variable declaration (fixes #8607)

### LINKED ISSUE #8607: Indent is inconsistent when call expression is used as variable initial value
**Tell us about your environment**

* **ESLint Version:**
master
* **Node Version:**
4
* **npm Version:**
4

**What parser (default, Babel-ESLint, etc.) are you using?**
typescript

**Please show your full configuration:**

```
module.exports = {
    "env": {
        "es6": true,
        "node": true,
        "mocha": true
    },
    "parser": "typescript-eslint-parser",
    "parserOptions": {
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "indent": [
            "error",
            4,
            {
                MemberExpression: 1,
                SwitchCase: 1,
                FunctionDeclaration: {
                    body: 1,
                    parameters: 1
                },
                FunctionExpression: {
                    body: 1,
                    parameters: 1
                },
                CallExpression: {
                    arguments: 1
                },
                VariableDeclarator: 1
            }
        ]
    }
};

```

**What did you do? Please include the actual source code causing the issue.**

```js
// Invalid
const foo = a.b(),
    longName
        = memberFunction(
            'bar'
        );
```

**What did you expect to happen?**
Should be a valid indent. If I move the equal operator to the same line as the variable identifier it is consider valid indentation.
```js
// Valid
const foo = a.b(),
    longName =
        memberFunction(
            'bar'
        );
```

**What actually happened? Please include the actual, raw output from ESLint.**
Invalid indentation.
```
/home/reyad/Workspace/eslint-test/test-indent.ts
  4:1  error  Expected indentation of 8 spaces but found 12  indent
  5:1  error  Expected indentation of 4 spaces but found 8   indent
```

### PR DESCRIPTION
**Pull request by soda0289**
**What is the purpose of this pull request? (put an "X" next to item)**
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

**What changes did you make? (Give an overview)**
Variable Declaration initial value should now be indented the same way as Assignment Expressions. We ignore the equal operator token and the token after it instead of just ignoring the initial value. By ignoring both of these token we can allow for an optional indent whether the equal operator is on a new line or not. Since a parenthesis token is not part of the initial value node it needs to be ignored in case it appears on a new line. We must also match indent of the first token after the equal since it might be a parenthesis that should have the same indentation of the equal when they are on the same line.

**Is there anything you'd like reviewers to focus on?**
Any test cases missing?

### CODE REVIEW

File: tests/lib/rules/indent.js [hunk 1]
```diff
@@ -3424,6 +3424,133 @@ ruleTester.run("indent", rule, {
                 )
             `
         },
+        {
+            code: unIndent`
+                const foo = a.b(),
+                    longName =
+                        (memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js [hunk 2]
```diff
@@ -3424,6 +3424,133 @@ ruleTester.run("indent", rule, {
...
+                            'bar',
+                            'bar'
+                        ));
+            `
+        },
+        {
+            code: unIndent`
+                const foo = a.b(),
+                    longName =
+                    (memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js [hunk 3]
```diff
@@ -3424,6 +3424,133 @@ ruleTester.run("indent", rule, {
...
+                        'bar',
+                        'bar'
+                    ));
+            `
+        },
+        {
+            code: unIndent`
+                const foo = a.b(),
+                    longName =
+                        memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js [hunk 4]
```diff
@@ -3424,6 +3424,133 @@ ruleTester.run("indent", rule, {
...
+                            'bar',
+                            'bar'
+                        );
+            `
+        },
+        {
+            code: unIndent`
+                const foo = a.b(),
+                    longName =
+                    memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js [hunk 5]
```diff
@@ -3424,6 +3424,133 @@ ruleTester.run("indent", rule, {
...
+                        'bar',
+                        'bar'
+                    );
+            `
+        },
+        {
+            code: unIndent`
+                const foo = a.b(),
+                    longName
+                        = memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js [hunk 6]
```diff
@@ -3424,6 +3424,133 @@ ruleTester.run("indent", rule, {
...
+                            'bar',
+                            'bar'
+                        );
+            `
+        },
+        {
+            code: unIndent`
+                const foo = a.b(),
+                    longName
+                    = memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js [hunk 7]
```diff
@@ -7633,6 +7760,80 @@ ruleTester.run("indent", rule, {
             `,
             errors: expectedErrors([[2, 4, 2, "Identifier"], [3, 4, 6, "Identifier"]])
         },
+        {
+            code: unIndent`
+                const foo = a.b(),
+                    longName
+                    = (memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js [hunk 8]
```diff
@@ -7633,6 +7760,80 @@ ruleTester.run("indent", rule, {
...
+                            'bar',
+                            'bar'
+                        ));
+            `,
+            output: unIndent`
+                const foo = a.b(),
+                    longName
+                    = (memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js [hunk 9]
```diff
@@ -7633,6 +7760,80 @@ ruleTester.run("indent", rule, {
...
+                        'bar'
+                    ));
+            `,
+            errors: expectedErrors([[4, 8, 12, "String"], [5, 8, 12, "String"], [6, 4, 8, "Punctuator"]])
+        },
+        {
+            code: unIndent`
+                const foo = a.b(),
+                    longName =
+                    (memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js [hunk 10]
```diff
@@ -7633,6 +7760,80 @@ ruleTester.run("indent", rule, {
...
+                            'bar',
+                            'bar'
+                        ));
+            `,
+            output: unIndent`
+                const foo = a.b(),
+                    longName =
+                    (memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js [hunk 11]
```diff
@@ -7633,6 +7760,80 @@ ruleTester.run("indent", rule, {
...
+                        'bar'
+                    ));
+            `,
+            errors: expectedErrors([[4, 8, 12, "String"], [5, 8, 12, "String"], [6, 4, 8, "Punctuator"]])
+        },
+        {
+            code: unIndent`
+                const foo = a.b(),
+                    longName
+                        =memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js [hunk 12]
```diff
@@ -7633,6 +7760,80 @@ ruleTester.run("indent", rule, {
...
+                            'bar',
+                            'bar'
+                    );
+            `,
+            output: unIndent`
+                const foo = a.b(),
+                    longName
+                        =memberFunction(
```
Comment (platinumazure) [inline tests/lib/rules/indent.js]: I think this function name might be confusing since the function callee is just an identifier, not part of a MemberExpression (either with this as the object, or some other object). Could we change it just to like `func` or `doSomething` or something else?

File: tests/lib/rules/indent.js (hunk 1 above)
Comment (soda0289) [inline tests/lib/rules/indent.js]: I agree. When I first found this issue it was with a member function `foo.bar()` but after more testing it also happened with call expressions. I will update the test.

**Comment by soda0289** [comment]
@platinumazure Changed the test name to `baz` from `memberFunction`. Thanks for the review
