### PR TITLE
fix: switch away from Node.js node:assert and AssertionError

### LINKED ISSUE #19040: Change Request: Indicate the impacted file when AssertionError is thrown by report-translator.js
### ESLint version

9.13.0

### What problem do you want to solve?

When `lib/linter/report-translator.js` throws an `AssertionError`, it doesn't explicitly indicate which file is being linted. You instead get a complaint like:

```plaintext

Oops! Something went wrong! :(

ESLint: 9.13.0

AssertionError [ERR_ASSERTION]: Fix objects must not be overlapped in a report.
    at mergeFixes (/Users/josh/repos/ts-api-utils/node_modules/.pnpm/eslint@9.13.0_jiti@2.3.3/node_modules/eslint/lib/linter/report-translator.js:165:9)
    at normalizeFixes (/Users/josh/repos/ts-api-utils/node_modules/.pnpm/eslint@9.13.0_jiti@2.3.3/node_modules/eslint/lib/linter/report-translator.js:197:16)
    at /Users/josh/repos/ts-api-utils/node_modules/.pnpm/eslint@9.13.0_jiti@2.3.3/node_modules/eslint/lib/linter/report-translator.js:371:49
    at FileContext.report (/Users/josh/repos/ts-api-utils/node_modules/.pnpm/eslint@9.13.0_jiti@2.3.3/node_modules/eslint/lib/linter/linter.js:1048:41)
    at file:///Users/josh/repos/ts-api-utils/node_modules/.pnpm/eslint-plugin-perfectionist@3.9.1_eslint@9.13.0_jiti@2.3.3__typescript@5.6.3/node_modules/eslint-plugin-perfectionist/dist/rules/sort-switch-case.mjs:146:21
    at pairwise (file:///Users/josh/repos/ts-api-utils/node_modules/.pnpm/eslint-plugin-perfectionist@3.9.1_eslint@9.13.0_jiti@2.3.3__typescript@5.6.3/node_modules/eslint-plugin-perfectionist/dist/utils/pairwise.mjs:7:9)
    at SwitchStatement (file:///Users/josh/repos/ts-api-utils/node_modules/.pnpm/eslint-plugin-perfectionist@3.9.1_eslint@9.13.0_jiti@2.3.3__typescript@5.6.3/node_modules/eslint-plugin-perfectionist/dist/rules/sort-switch-case.mjs:109:9)
    at ruleErrorHandler (/Users/josh/repos/ts-api-utils/node_modules/.pnpm/eslint@9.13.0_jiti@2.3.3/node_modules/eslint/lib/linter/linter.js:1084:48)
    at /Users/josh/repos/ts-api-utils/node_modules/.pnpm/eslint@9.13.0_jiti@2.3.3/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
```

Only after running with a debug verbosity like `DEBUG=*` or `DEBUG=eslint:linter` do you see:

```plaintext
...
  eslint:linter Verify +0ms
  eslint:linter With flat config: /Users/josh/repos/ts-api-utils/src/usage/getUsageDomain.ts +0ms
  eslint:linter An error occurred while traversing +10ms
  eslint:linter Filename: /Users/josh/repos/ts-api-utils/src/usage/getUsageDomain.ts +0ms
  eslint:linter Line: 22 +0ms
  eslint:linter Parser Options: {
  projectService: { allowDefaultProject: [ '*.*s', 'eslint.config.js' ] },
  tsconfigRootDir: '/Users/josh/repos/ts-api-utils'
} +0ms
  eslint:linter Settings: {} +0ms
```

### What do you think is the correct solution?

As a small convenience for users, it'd be nice to have the violating file be mentioned. Perhaps:

```plaintext
Oops! Something went wrong! :(

ESLint: 9.13.0
File: /Users/josh/repos/ts-api-utils/src/usage/getUsageDomain.ts

AssertionError [ERR_ASSERTION]: Fix objects must not be overlapped in a report.
    at mergeFixes (/Users/josh/repos/ts-api-utils/node_modules/.pnpm/eslint@9.13.0_jiti@2.3.3/node_modules/eslint/lib/linter/report-translator.js:165:9)...
```

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

Example reproduction: https://github.com/JoshuaKGoldberg/ts-api-utils/pull/531/commits/9ee03183986e93e573fa11ed7643b440603439a9 -> https://github.com/JoshuaKGoldberg/ts-api-utils/actions/runs/11464047451/job/31899346641?pr=531.

Related to: https://github.com/azat-io/eslint-plugin-perfectionist/issues/335

~~Apologies I don't have a more isolated reproduction, I ran out of time trying to set one up. It's tricky. 🙂~~ Edit: https://github.com/JoshuaKGoldberg/repros/tree/eslint-assertion-error-no-rule

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #19040.

#### What changes did you make? (Give an overview)

Switches from [`node:assert`](https://nodejs.org/api/assert.html) to equivalent hand-written function `ok`.

`strictEqual` and `notStrictEqual` are also used in the project, but only by the development-time `RuleTester`. We'd like to keep that as-is.

### CODE REVIEW

File: lib/linter/report-translator.js [hunk 1]
```diff
@@ -9,10 +9,11 @@
 // Requirements
 //------------------------------------------------------------------------------
 
-const assert = require("node:assert");
+const assert = require("../shared/assert");
 const { RuleFixer } = require("./rule-fixer");
 const { interpolate } = require("./interpolate");
 
+
```
Comment (JoshuaKGoldberg) [inline lib/linter/report-translator.js:16]:
```suggestion
```

File: lib/shared/assert.js [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+ */
+
+"use strict";
+
+/**
+ * Throws an error if the input is not truthy.
+ * @param {unknown} value The input that is checked for being truthy.
+ * @param {string} message Message to throw if the input is not truthy.
+ * @returns {void}
+ * @throws {Error}
```
Comment (amareshsm) [inline lib/shared/assert.js:13]:
```suggestion
 * @throws {Error} When the condition is not truthy.
```

File: lib/shared/assert.js [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+}
+
+/**
+ * Throws an error if the input is not strictly equal to expected.
+ * @template T
+ * @param {T} value The input that is checked for being strictly equal.
+ * @param {T} expected The expected value.
+ * @param {string} message Message to throw if the input is not strictly equal.
+ * @returns {void}
+ * @throws {Error}
```
Comment (amareshsm) [inline lib/shared/assert.js:28]:
```suggestion
 * @throws {Error} if the input is not strictly equal to the expected value.
```

File: lib/shared/assert.js [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+}
+
+/**
+ * Throws an error if the input is strictly equal to expected.
+ * @template T
+ * @param {T} value The input that is checked for being strictly equal.
+ * @param {T} expected The expected value.
+ * @param {string} message Message to throw if the input is strictly equal.
+ * @returns {void}
+ * @throws {Error}
```
Comment (amareshsm) [inline lib/shared/assert.js:43]:
```suggestion
 * @throws {Error}  if the input is strictly equal to the expected value.
```

File: lib/shared/assert.js [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+"use strict";
+
+/**
+ * Throws an error if the input is not truthy.
+ * @param {unknown} value The input that is checked for being truthy.
+ * @param {string} message Message to throw if the input is not truthy.
+ * @returns {void}
+ * @throws {Error}
+ */
+function ok(value, message) {
```
Comment (amareshsm) [inline lib/shared/assert.js:15]:
```suggestion
function ok(value, message) {
```
Can we give a default message?

File: lib/shared/assert.js (hunk 4 above)
Comment (nzakas) [reply lib/shared/assert.js:43]: @amareshsm I think you forgot the word "not" in the description

**Review by nzakas — COMMENTED** [review]
I don't see any references to `strictEqual` or `notStrictEqual`. Did you forget to include some files with changes?

**Comment by mdjermanovic** [comment]
We're using `assert.strictEqual` and `assert.notStrictEqual` in RuleTester. But I think it's good to keep using `node:assert` in RuleTester because it provides additional properties on errors, like `expected` and `actual`. Those properties are used for better output:

image


Other than RuleTester, I think we need just a simple `assert(value, message)`.

File: lib/shared/assert.js (hunk 5 above)
Comment (JoshuaKGoldberg) [reply lib/shared/assert.js:15]: We could, but that'd differ from the Node.js behavior. I feel odd forking in that way 🤔

File: lib/shared/assert.js (hunk 4 above)
Comment (JoshuaKGoldberg) [reply lib/shared/assert.js:43]:
```suggestion
 * @throws {Error}  if the input is not strictly equal to the expected value.
```

File: lib/shared/assert.js (hunk 5 above)
Comment (JoshuaKGoldberg) [reply lib/shared/assert.js:15]: Oh, also, I think it'd be good to force users to provide their own precise error message, no? I can't think of a good default that would apply to all the places this is used.

**Comment by JoshuaKGoldberg** [comment]
Browser tests pass locally for me with `node Makefile wdio`.

File: lib/shared/assert.js [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+
+module.exports = {
+    ok,
+
+    /*
+     * Intentionally mirroring the node:assert interface, instead of normal Knip CommonJS patterns.
+     * https://knip.dev/guides/working-with-commonjs
+     */
+    __esModule: true
+};
```
Comment (mdjermanovic) [inline lib/shared/assert.js:30]: Thoughts about simplifying this to export a function? I think all we need in production code is a simple `assert(value, message)` as a shorthand for `if (!value) { throw new Error(message); }`.

Comment (JoshuaKGoldberg) [reply lib/shared/assert.js:30]: I slightly prefer it as-is, since `node:assert` is a pretty common standard to build against. I don't like how a lot of projects have ended up with their own subtly different ad-hoc reimplementations of it. I've found it confusing to swap between projects, and inconvenient to migrate to more standard solutions. But I wouldn't push back hard if there's otherwise consensus to streamline.

Comment (mdjermanovic) [reply lib/shared/assert.js:30]: I'm not sure if the goal is to mimic the `node:assert` API, but even if it is, it supports `assert(value, message)`:

https://nodejs.org/api/assert.html#assertvalue-message

Comment (JoshuaKGoldberg) [reply lib/shared/assert.js]: Good point, done!

File: lib/shared/assert.js (hunk 5 above)
Comment (mdjermanovic) [reply lib/shared/assert.js:15]: Maybe we can set `"Unspecified assertion error"` as the default message, and at some later point figure out what should be passed as a concrete message in places where the second argument is missing.

Comment (nzakas) [reply lib/shared/assert.js:15]: Remember, "users" in this case is just people contributing to this code base. :smile:

Most custom `assert()` functions specify `"Assertion failed."` as the default message.

If we want to enforce a message be passed, then `assert()` should throw an error when `message` is undefined. Personally, I'm fine with a custom message as a default.

Comment (mdjermanovic) [reply lib/shared/assert.js:15]: `"Assertion failed."` default message sounds good to me.

**Comment by mdjermanovic** [comment]
@JoshuaKGoldberg I think https://github.com/eslint/eslint/pull/19082#discussion_r1823354292 hasn't been addressed yet.

**Comment by JoshuaKGoldberg** [comment]
Ah, sorry missed that - updated now.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! I've verified that errors thrown for overlapping fixes now show the filename as requested in the original issue.

```
Oops! Something went wrong! :(

ESLint: 9.14.0

Error: Fix objects must not be overlapped in a report.
Occurred while linting C:\projects\eslint\Makefile.js:7
Rule: "no-multi-spaces"
    at ok (C:\projects\eslint\lib\shared\assert.js:17:15)
    at mergeFixes (C:\projects\eslint\lib\linter\report-translator.js:165:9)
    at normalizeFixes (C:\projects\eslint\lib\linter\report-translator.js:197:16)
    at C:\projects\eslint\lib\linter\report-translator.js:371:49
    at FileContext.report (C:\projects\eslint\lib\linter\linter.js:1048:41)
    at C:\projects\eslint\lib\rules\no-multi-spaces.js:129:29
    at Array.forEach (<anonymous>)
    at Program (C:\projects\eslint\lib\rules\no-multi-spaces.js:84:46)
    at ruleErrorHandler (C:\projects\eslint\lib\linter\linter.js:1084:48)
    at C:\projects\eslint\lib\linter\safe-emitter.js:45:58
```
