### PR TITLE
Fix: make `no-unused-vars` ignore for-in loops (fixes #2342)

### LINKED ISSUE #2342: no-unused-vars incorrectly raised when variable is used with for…in
The no-unused-vars error is incorrectly triggered when a variable is only used in a `for in` statement.

The following snippet gives the error `no-unused-vars`:

```JavaScript
(function () {
  "use strict";
  var key;
  for (key in this) return;
})();
```
```
3:6  error  key is defined but never used  no-unused-vars
```

However, the variable is clearly used in `for (key in this)`.
Furthermore, omitting the declaration also results in an error:

```JavaScript
(function () {
  "use strict";
  for (key in this) return;
})();
```
```
3:7  error  "key" is not defined  no-undef
```

The expected behavior is that the first snippet does not yield any error; the second error is correct.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11508714-no-unused-vars-incorrectly-raised-when-variable-is-used-with-for-in?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by markelog**
Also clean jsdocs for internal helpers

### CODE REVIEW

**Comment by markelog** [comment]
I assume phantom issue is known problem

**Comment by ilyavolodin** [comment]
Yes, phantom issue has been screwing our builds for a while now...

**Comment by alberto** [comment]
@markelog I think the agreed-upon change was to ignore only `for (x in y) return;`, not any for..in/of loop

**Comment by markelog** [comment]
@ilyavolodin

Is there ticket about this? Downloading phantom binary is known bottleneck and that's syntactic environment, since alternative would be to actually make ci run tests in real browsers, i would propose to do that instead.

@alberto

mm, i was under impression `for (x in y) return;` example was to illustrate the point.

Otherwise we would need to inspect body of the loop, which would introduce it seems unnecessary complexity. I'm not sure what kind of disadvantages we would try to avoid by doing that, i could see though breaking a use-case of object getters on which that loop could be iterated upon if we would be specific with `return` keyword.

**Comment by nzakas** [comment]
Agree with @alberto - the resolution of #2342 is to explicitly exempt for-in when it's body is just `return` (see https://github.com/eslint/eslint/issues/2342#issuecomment-163789979). We definitely don't want to exempt all loops. 

@markelog can you update this PR accordingly? Also, can you update the commit message to begin with "Update" instead of "Fix"? (The issue is labeled as an enhancement, so we use " Update" for that.)

**Comment by markelog** [comment]
ok-ok, so we targeting only loops with one statement which should be `return`, correct?

**Comment by nzakas** [comment]
Only for-in loops with `return`, yes.

**Comment by markelog** [comment]
Sorry to keep asking about this, but i want to be clear about it - only one statement with `return` is not violation? Like this - 
```js
for (var key in obj) {
 i++;
 return false;
}
```
Is violation or not? Also your last comment was https://github.com/eslint/eslint/issues/2342#issuecomment-163789979 yeah, but then there was https://github.com/eslint/eslint/issues/2342#issuecomment-182697596

which includes 

> and same pattern for for..of

Those confuse a bit

**Comment by nzakas** [comment]
Just `for-in` and only when the loop body just has a `return` statement. So your example would still be flagged as a problem.

**Comment by markelog** [comment]
ok, thank you for clarification

**Comment by platinumazure** [comment]
@markelog @nzakas Hard to tell if this is ready for merge- if not, can we put "do not merge" on here?

**Comment by markelog** [comment]
Done, thank you

File: lib/rules/no-unused-vars.js [hunk 1]
```diff
@@ -99,7 +99,6 @@ module.exports = {
          * Determines if a given variable is being exported from a module.
          * @param {Variable} variable - EScope variable object.
          * @returns {boolean} True if the variable is exported, false if not.
-         * @private
```
Comment (nzakas) [inline lib/rules/no-unused-vars.js]: Why did you remove `@private` everywhere?

File: lib/rules/no-unused-vars.js [hunk 2]
```diff
@@ -153,9 +150,32 @@ module.exports = {
         }
 
         /**
+         * Determine if an identifier is used either in for...of or for...in loops.
+         * @param {Reference} ref - The reference to check.
+         * @returns {Boolean} whether reference is used in the for...of or for...in loops
```
Comment (nzakas) [inline lib/rules/no-unused-vars.js]: `boolean` (lowercase, `Boolean` is for boolean objects)

File: lib/rules/no-unused-vars.js [hunk 3]
```diff
@@ -153,9 +150,32 @@ module.exports = {
...
+         */
+        function isForRef(ref) {
```
Comment (nzakas) [inline lib/rules/no-unused-vars.js]: Maybe `isForInRef()` now that it only checks `for-in`?

File: lib/rules/no-unused-vars.js [hunk 4]
```diff
@@ -153,9 +150,32 @@ module.exports = {
         }
 
         /**
+         * Determine if an identifier is used either in for...of or for...in loops.
```
Comment (nzakas) [inline lib/rules/no-unused-vars.js]: Looks like this doesn't check `for-of`.

File: lib/rules/no-unused-vars.js (hunk 1 above)
Comment (markelog) [inline lib/rules/no-unused-vars.js]: There is a lot of rules that do use this keyword and there is a lot of rules that don't, some of the helpers of this particular rule also do and do not.

So it seems we have to choose with or without it, since in my view it is already obvious they are private, i choice the latter.

Trying to make it consistent, what way seems better to you?

File: lib/rules/no-unused-vars.js (hunk 2 above)
Comment (markelog) [inline lib/rules/no-unused-vars.js]: What spec, are we talking about? I looked at http://usejsdoc.org/tags-returns.html.

Is there a ticket to include this in http://eslint.org/docs/rules/valid-jsdoc ?

**Comment by markelog** [comment]
Will make a fix for other remarks after clarification, so it could be done in one move

**Comment by markelog** [comment]
Added, "do not merge" label, since there is a questions about this pull, not sure if it was required though

**Comment by nzakas** [comment]
We usually only add "do not merge" if the issue isn't accepted or if there's a significant problem that might not otherwise be obvious. Basically, we want to prevent accidental merges. In this case, where we're having normal back-and-forth of feedback and update, so you don't need to add it.

**Comment by markelog** [comment]
I see, thanks for explanation

File: lib/rules/no-unused-vars.js (hunk 1 above)
Comment (markelog) [inline lib/rules/no-unused-vars.js]: So what should i do?

Comment (nzakas) [inline lib/rules/no-unused-vars.js]: I'd prefer to have `@private`, as it will prevent JSDoc from generating docs for them if we ever get that working again. :)

File: lib/rules/no-unused-vars.js (hunk 2 above)
Comment (nzakas) [inline lib/rules/no-unused-vars.js]: This is the convention we've used throughout to distinguish between boolean primitive values and boolean object values. It's the difference between:

```js
// boolean
var found = true;

// Boolean
var found = new Boolean(true);
```

File: lib/rules/no-unused-vars.js (hunk 1 above)
Comment (markelog) [inline lib/rules/no-unused-vars.js]: ok-ok, also, i think it would the right move to do this everywhere else, how about creating a ticket about this?

File: lib/rules/no-unused-vars.js (hunk 2 above)
Comment (markelog) [inline lib/rules/no-unused-vars.js]: Oh, so this is house rule not specified in any standard, got it

**Comment by markelog** [comment]
Will make appropriate changes in couple of days

**Comment by nzakas** [comment]
@markelog we'd really like to get this fix in. Do you think you can get to it soon? Or would you rather sometime else take over?

**Comment by markelog** [comment]
Done, sorry for the delay

**Comment by ilyavolodin** [comment]
@markelog It looks like there's a still merge conflict in this PR. Could you rebase please?

**Comment by markelog** [comment]
Donzo, there is a lot of interesting code in there.

File: lib/rules/no-unused-vars.js [hunk 5]
```diff
@@ -220,10 +220,35 @@ module.exports = {
...
+            // "for (...) { return; }"
+            if (target.body.type === "BlockStatement") {
+                target = target.body.body[0];
+
+            // "for (...) return;"
+            } else {
+                target = target.body;
+            }
+
+            return target.type === "ReturnStatement";
```
Comment (mysticatea) [inline lib/rules/no-unused-vars.js]: I guess this may cause null dereference error at empty block body.

Comment (markelog) [inline lib/rules/no-unused-vars.js]: mm, could you elaborate with some code?

Comment (mysticatea) [inline lib/rules/no-unused-vars.js]: (function(obj) { var name; for ( name in obj ) { } })({});

File: lib/rules/no-unused-vars.js [hunk 6]
```diff
@@ -220,10 +220,35 @@ module.exports = {
...
+        function isForInRef(ref) {
+            var target = ref.identifier.parent;
+
+            if (target.type !== "ForInStatement") {
+                return false;
+            }
+
+            // "for (...) { return; }"
+            if (target.body.type === "BlockStatement") {
+                target = target.body.body[0];
```
Comment (alberto) [inline lib/rules/no-unused-vars.js]: I think @mysticatea is talking about this line.

File: lib/rules/no-unused-vars.js (hunk 5 above)
Comment (markelog) [inline lib/rules/no-unused-vars.js]: Fixed thanks, btw, was about to cc you here and there you are :)

File: lib/rules/no-unused-vars.js (hunk 6 above)
Comment (markelog) [inline lib/rules/no-unused-vars.js]: Just pushed a fix there

**Comment by mysticatea** [comment]
I'd like to see a test for the following code:

    for (const key in obj) return true;

**Comment by markelog** [comment]
You mean for `const`? I guess it also makes sense to add similar test for `let` too?

**Comment by mysticatea** [comment]
I'm seeing that this is checking whether the parent node of an identifier is a ForInStatement or not.
My example is that the parent node is a VariableDeclarator.

**Comment by markelog** [comment]
@mysticatea done

**Comment by mysticatea** [comment]
Thank you very much!
Looks good to me.

**Comment by markelog** [comment]
Okay, so it seems i have addressed all concerns, so if no one objects, i would like to land this today

**Comment by nzakas** [comment]
@markelog why was the commit message changed from "Fix" to "Update" here?

Note that as soon as it becomes "Update", a TSC member needs to merge the code (because it causes a minor semver bump).

**Comment by nzakas** [comment]
FYI: We changed the commit message back to "Fix" as it seems like that is what is appropriate given the semver policy.

**Comment by alberto** [comment]
Thanks @markelog for keeping up!

**Comment by markelog** [comment]
@nzakas Probably is, on https://github.com/eslint/eslint/issues/2342 it has label `enhancement` that is why i change commit tag, should we change label on that issue?

> Note that as soon as it becomes "Update", a TSC member needs to merge the code (because it causes a minor semver bump).

Ok-ok, i understand correlation now
