### PR TITLE
Update: Fix false negative of `no-multiple-empty-lines` (fixes #7312)

### LINKED ISSUE #7312: no-multiple-empty-lines does not report any errors if file contains interpolated strings
**Tell us about your environment**

* **ESLint Version:** 3.7.1
* **Node Version:** 6.4.0
* **npm Version:** 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**

Babel, see full configuration

**Please show your full configuration:**

```json
{
    "parserOptions": {
        "ecmaVersion": 6,
        "ecmaFeatures": {
            "jsx": true,
            "impliedStrict": true
        },
        "sourceType": "module"
    },
    "rules": {
        "no-multiple-empty-lines": ["warn", {"max": 1}]
    },
    "plugins": [
        "react"
    ]
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
import './baz';


function foo() {
  `${s}-foo`;
}

function bar() {
  `${x} bar`;
}
```

I ran eslint as follows:

```bash
$ eslint static/dodgy_direct.jsx --ext .jsx -c .eslint.format.json --no-eslintrc --fix
```

**What did you expect to happen?**

Duplicate blank line should be removed, so the correct output should be:

```js
import './baz';

function foo() {
  `${s}-foo`;
}

function bar() {
  `${x} bar`;
}
```

**What actually happened? Please include the actual, raw output from ESLint.**

File was unchanged, with no errors reported.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

See https://github.com/eslint/eslint/issues/7312

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- (n/a) I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**

This commit is intended to change as little of the rule's logic as possible in order to fix the issue. I think this rule could use refactoring, which I plan to do afterwards (edit: see https://github.com/eslint/eslint/pull/7314). I made this commit based on the old logic to allow for an easier revert if the refactoring goes wrong somehow.

Bug explanation: The rule stores a list of strings containing the lines of a file, with whitespace trimmed from the start and end of each line. It detects an empty line by checking whether the trimmed line in its list is an empty string.

The rule also has to account for empty lines in template literals (see https://github.com/eslint/eslint/issues/2605). In order to do this, for each line in the file that overlaps a template literal, the rule tries to overwrite the corresponding value in its list of lines with something other than an empty string, to prevent it from detected as an empty line.

Due to a logical error, the rule was overwriting the strings at the *beginning* of its list of lines, rather than the lines that actually contained template literals.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: tests/lib/rules/no-multiple-empty-lines.js [hunk 1]
```diff
@@ -286,6 +286,22 @@ ruleTester.run("no-multiple-empty-lines", rule, {
...
+            code:
+            "'foo';\n" +
+            "\n" +
+            "\n" +
+            "`bar`;\n" +
+            "`baz`;",
+            output:
+            "'foo';\n" +
+            "\n" +
+            "`bar`;\n" +
```
Comment (gcochard) [inline tests/lib/rules/no-multiple-empty-lines.js]: I'd include a multi-line template literal here as well, to ensure that it is working properly.

File: lib/rules/no-multiple-empty-lines.js [hunk 2]
```diff
@@ -113,8 +113,10 @@ module.exports = {
                 });
 
                 // add the notEmpty lines in there with a placeholder
-                notEmpty.forEach(function(x, i) {
-                    trimmedLines[i] = x;
+                notEmpty.forEach(function(nonEmptyLineNumber) {
+
+                    // FIXME: (not-an-aardvark) Use a better strategy after refactoring this rule
+                    trimmedLines[nonEmptyLineNumber] = "non-empty placeholder string";
```
Comment (gcochard) [inline lib/rules/no-multiple-empty-lines.js]: :+1: on this. You probably don't need to modify this strategy unless the logic to search trimmedLines changes.

File: tests/lib/rules/no-multiple-empty-lines.js (hunk 1 above)
Comment (not-an-aardvark) [inline tests/lib/rules/no-multiple-empty-lines.js]: Good idea. How does the test in https://github.com/eslint/eslint/pull/7314 look?

File: lib/rules/no-multiple-empty-lines.js (hunk 2 above)
Comment (not-an-aardvark) [inline lib/rules/no-multiple-empty-lines.js]: I disagree; in my opinion, overwriting the list with a bogus value is confusing for other people reading the code. Ideally, I think those lines would be marked explicitly (e.g. in a separate list/set), and then the separate set would be checked again when determining whether a line was empty.

Comment (gcochard) [inline lib/rules/no-multiple-empty-lines.js]: Agreed that this is confusing and definitely could be refactored.

File: tests/lib/rules/no-multiple-empty-lines.js (hunk 1 above)
Comment (gcochard) [inline tests/lib/rules/no-multiple-empty-lines.js]: Looks good, do we also want to add something like `foo\n\nbar\n\n\n${foo\n}` for newlines in the template itself?

Comment (not-an-aardvark) [inline tests/lib/rules/no-multiple-empty-lines.js]: I think there already are tests for that (specifically [these](/eslint/eslint/blob/ac3504d4f7542329bd271db369660099e2211e90/tests/lib/rules/no-multiple-empty-lines.js#L127-L147)). Am I misunderstanding the type of test you're referring to?

Comment (gcochard) [inline tests/lib/rules/no-multiple-empty-lines.js]: Yes, somehow I missed them. :facepalm:

**Comment by not-an-aardvark** [comment]
(Corrected the commit message -- it previously had `no-multi-empty-lines` instead of `no-multiple-empty-lines`.)
