### PR TITLE
Fix: object-shorthand rule should not warn for NFEs (fixes #2748)

### LINKED ISSUE #2748: object-shorthand should have an exception for named functions
In general, I want to enforce `object-shorthand` rule in all my code.

However, I also care about proper function names (`.name` property) and would like to have a [configurable] exception for cases when function name is explicitly set and is different from property name like in following case:

```javascript
Object.create(proto, {
	toString: {
		writable: true,
		configurable: true,
		// should not warn here, as I explicitly want name `toString`:
		value: function toString() {
			return this[PROXY_TARGET].toString();
		}
	}
});
```

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #2748.

### CODE REVIEW

File: lib/rules/object-shorthand.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ module.exports = function(context) {
                 return;
             }
 
-            if (node.value.type === "FunctionExpression" && APPLY_TO_METHODS) {
+            if (node.value.type === "FunctionExpression" && node.value.id == null && APPLY_TO_METHODS) {
```
Comment (gyandeeps) [inline lib/rules/object-shorthand.js]: why not `===`?

Comment (michaelficarra) [inline lib/rules/object-shorthand.js]: I never distinguish between null and undefined values unless it is necessary.

**Comment by nzakas** [comment]
Lgtm
