### PR TITLE
Fix: `prefer-const` false positive in a loop condition (fixes #5024)

### LINKED ISSUE #5024: prefer-const rule seems to be confused by expressions in a while condition
**What version are you using?**
2.0.0-beta.1

**What did you do?**
I use this code:
```javascript
  let parsed;
  let result = '';
  while ((parsed = re.exec(str)) !== null) {
    const [, count, letter] = parsed;
    result += letter.repeat(count);
  }
```
With the "prefer-const" rule, I get `'parsed' is never modified, use 'const' instead. (prefer-const)` which seems incorrect, because it is indeed modified in the while condition.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30098354-prefer-const-rule-seems-to-be-confused-by-expressions-in-a-while-condition?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #5024

If the singular `WriteReference` of a variable is being in a condition of a loop, this rule came to skip the variable.

### CODE REVIEW

File: lib/rules/prefer-const.js [hunk 1]
```diff
@@ -37,6 +41,51 @@ function getWriteReferenceIfOnce(variable) {
...
+        }
+
+        // VariableDeclaration can be at ForInStatement.left
+        // This is catching the code like `for (const {b = ++a} of foo()) { ... }`
+        if (assignment &&
+            parent.type === "VariableDeclaration" &&
+            FOR_IN_OF_TYPES.test(parent.parent.type) &&
+            parent.parent.left === parent
+        ) {
+            return true;
```
Comment (mysticatea) [inline lib/rules/prefer-const.js]: This `a` should be caught:

```js
for (let a of foo()) { ... }
```

But this `a` should not be caught:

```js
let a;
for (let {b = a++} of foo()) { ... }
```

So the test of `ForInStatement.left` and `ForOfStatement.left` is complexity a bit.

Comment (ilyavolodin) [inline lib/rules/prefer-const.js]: Wait, don't you mean the opposite? In the first case you should use const, and this rule should suggest it, but in the second case, you can't use const. Right?

Comment (mysticatea) [inline lib/rules/prefer-const.js]: Yes, I meant "caught" is "warned".

File: lib/rules/prefer-const.js [hunk 2]
```diff
@@ -37,6 +41,51 @@ function getWriteReferenceIfOnce(variable) {
...
+        if (SENTINEL_TYPES.test(parent.type)) {
+            return false;
+        }
+
+        node = parent;
+        parent = parent.parent;
+    }
+
+    /* istanbul ignore next: unreachable */
+    return false;
```
Comment (ilyavolodin) [inline lib/rules/prefer-const.js]: This should be reachable, right? If your variable is not part of the loop header or Variable Declaration/Assignment Pattern.

Comment (mysticatea) [inline lib/rules/prefer-const.js]: This is unreachable. If it encountered any statement node (e.g. ExpressionStatement) then returns at L77.

Comment (mysticatea) [inline lib/rules/prefer-const.js]: Ah, I can rewrite L77 with just `break;`.

File: lib/rules/prefer-const.js (hunk 1 above)
Comment (mysticatea) [inline lib/rules/prefer-const.js]: I updated it!

File: lib/rules/prefer-const.js (hunk 2 above)
Comment (mysticatea) [inline lib/rules/prefer-const.js]: I updated it!

**Comment by ilyavolodin** [comment]
LGTM
