### PR TITLE
Fix: eslint --init installs wrong dependencies of popular styles (fixes #7338)

### LINKED ISSUE #7338: 'eslint --init' installs wrong versions of depencies for AirBnB
**Tell us about your environment**
Windows 10
- **ESLint Version:** 3.7.1
- **Node Version:** 5.3.0
- **npm Version:** 3.3.12

**What parser (default, Babel-ESLint, etc.) are you using?**
N/A
**Please show your full configuration:**
AirBnB style guide
**What did you do? Please include the actual source code causing the issue.**

```
npm init
Use a popular style guide
Airbnb
JSON
```

**What did you expect to happen?**
I expected the node modules to install correctly.
**What actually happened? Please include the actual, raw output from ESLint.**
Eslint failed to correctly install dependencies as seen at the bottom of this output:

```
C:\SWDev\job-frontend>eslint --init                                                                                                                                                          
? How would you like to configure ESLint? Use a popular style guide                                                                                                                          
? Which style guide do you want to follow? Airbnb                                                                                                                                            
? What format do you want your config file to be in? JSON                                                                                                                                    
Installing eslint-plugin-react, eslint-plugin-jsx-a11y, eslint-plugin-import, eslint-config-airbnb                                                                                           
npm WARN install Couldn't install optional dependency: Unsupported                                                                                                                           
job-frontend@0.0.0 C:\SWDev\job-frontend                                                                                                                                                     
├─┬ eslint@3.7.1                                                                                                                                                                             
│ └── doctrine@1.3.0                                                                                                                                                                         
├─┬ eslint-config-airbnb@12.0.0                                                                                                                                                              
│ ├── eslint-config-airbnb-base@8.0.0                                                                                                                                                        
│ └── UNMET PEER DEPENDENCY eslint-plugin-import@^1.16.0                                                                                                                                     
├─┬ UNMET PEER DEPENDENCY eslint-plugin-import@2.0.0                                                                                                                                         
│ ├── contains-path@0.1.0                                                                                                                                                                    
│ ├── eslint-import-resolver-node@0.2.3   
│ ├─┬ eslint-module-utils@1.0.0                                                                                                                                                              
│ │ └── pkg-dir@1.0.0                                                                                                                                                                        
│ ├── lodash.cond@4.5.2                                                                                                                                                                      
│ └── pkg-up@1.0.0                                                                                                                                                                           
├─┬ eslint-plugin-jsx-a11y@2.2.3                                                                                                                                                             
│ └── damerau-levenshtein@1.0.3                                                                                                                                                              
└── eslint-plugin-react@6.4.1                                                                                                                                                                

npm WARN EPEERINVALID eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.                                                                    
npm WARN EPEERINVALID eslint-config-airbnb-base@8.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.                                                                
npm WARN EPACKAGEJSON job-frontend@0.0.0 No license field.
```

**Workaround**
The AirBnB style guide for standard javascript is actually eslint-config-airbnb-base, the one used by the wizard is for react. So I swapped out that package and chose the versions of the decencies that would work (with either react or standard AirBnB).

Initialized package.json:

```
    "eslint-config-airbnb": "^12.0.0",
    "eslint-plugin-import": "^2.0.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
```

Updated package.json:

```
    "eslint-config-airbnb-base": "^8.0.0",
    "eslint-plugin-import": "^1.16.0",
    "eslint-plugin-jsx-a11y": "^2.2.2",
```

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

Fixes #7338.

In `eslint --init`, if people select a popular style guide, it installs wrong versions of eslint and plugins.

- `airbnb` and `airbnb-base` requires ESLint 3 but it installs ESLint 4.
- `standard` requires `eslint-plugin-standard` and `eslint-plugin-node` but it does not install those plugins.

**What changes did you make? (Give an overview)**

This PR improve `eslint --init`.
If people select a popular style guide, it checks the `peerDependencies` of the shareable config, then installs the correct dependencies.

To install correct versions, this PR's `eslint --init` installs all dependencies even if those have been installed already. This behavior is different to the current master branch.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: tests/lib/config/config-initializer.js [hunk 1]
```diff
@@ -209,13 +209,13 @@ describe("configInitializer", () => {
...
                 assert(npmInstallStub.calledOnce);
-                assert.deepEqual(npmInstallStub.firstCall.args[0][1], "eslint-config-google");
+                assert(npmInstallStub.firstCall.args[0].some(name => name.startsWith("eslint-config-google@")));
             });
 
             it("should install ESLint if not installed locally", () => {
                 init.getConfigForStyleGuide("google");
                 assert(npmInstallStub.calledOnce);
-                assert.deepEqual(npmInstallStub.firstCall.args[0][0], "eslint");
+                assert(npmInstallStub.firstCall.args[0].some(name => name.startsWith("eslint@")));
```
Comment (not-an-aardvark) [inline tests/lib/config/config-initializer.js]: Maybe it would be a good idea to assert that the `peerDependencies` are also installed.

**Comment by mysticatea** [comment]
Thank you for the review, @not-an-aardvark .
I have added tests for this. Also, I added `(fixes #7338)` to the issue title.

File: lib/config/config-initializer.js [hunk 2]
```diff
@@ -62,42 +62,46 @@ function writeFile(config, format) {
...
+
+        log.info(`Checking peerDependencies of ${moduleName}`);
+        modules[moduleName] = "latest";
+        Object.assign(
+            modules,
+            npmUtil.fetchPeerDependencies(`${moduleName}@latest`)
+        );
     }
 
     // Determine which modules are already installed
```
Comment (kaicataldo) [inline lib/config/config-initializer.js]: This pre-existing comment seems incorrect

**Comment by mysticatea** [comment]
Thank you for the review. I updated code comments.
