### PR TITLE
Fix: Prefer-const rule crashing on array destructuring (fixes #10520)

### LINKED ISSUE #10520: 5.0.0 - Crash with prefer-const rule where code contains array destructuring assignment with 'ignored values'
This is a minimal reproduction for a bug I've found in `eslint@5.0.0`. As far as I can tell the example code below is valid JavaScript (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Ignoring_some_returned_values).

**Tell us about your environment**

* **ESLint Version:** 5.0.0
* **Node Version:** 8.11.0
* **npm Version:** 5.6.0
* **yarn Version:** 1.7.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```json
{
    "parserOptions": {
        "ecmaVersion": 2018
    },
    "rules": {
      "prefer-const": 1
    }
}

```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const b = [1, 2];
let a;

[, a] = b;

```

```bash
cd eslint-5-array-destructuring-assignment-bug
yarn eslint .
```

**What did you expect to happen?**
eslint would lint my project

**What actually happened? Please include the actual, raw output from ESLint.**
eslint did not lint my project and threw a TypeError from one of its built-in rules (`prefer-const`)
```
Cannot read property 'name' of null
TypeError: Cannot read property 'name' of null
    at elements.map.element (/node_modules/eslint/lib/rules/prefer-const.js:173:49)
    at Array.map (<anonymous>)
    at getIdentifierIfShouldBeConst (/node_modules/eslint/lib/rules/prefer-const.js:173:26)
    at groupByDestructuring (/node_modules/eslint/lib/rules/prefer-const.js:227:28)
    at Program:exit (/node_modules/eslint/lib/rules/prefer-const.js:362:17)
    at listeners.(anonymous function).forEach.listener (/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/node_modules/eslint/lib/util/node-event-generator.js:280:22)
```

### PR DESCRIPTION
**Pull request by mjmasn**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes https://github.com/eslint/eslint/issues/10520

**What changes did you make? (Give an overview)**
* Added tests for array destructuring assignment where the array has ignored / empty elements.
* Fixed a bug where trying to read the `name` property of the `null` elements

**Is there anything you'd like reviewers to focus on?**
First PR here so let me know if I should do anything differently. <s>The bug fix code is slightly more verbose than originally described in #10520 due to some circular lint rules in the eslint repo (`no-confusing-arrow` / `arrow-body-style`) when using the ternary operator.</s>

### CODE REVIEW

File: lib/rules/prefer-const.js [hunk 1]
```diff
@@ -170,7 +170,12 @@ function getIdentifierIfShouldBeConst(variable, ignoreReadBeforeAssign) {
                     const elements = leftNode.elements;
 
                     hasOuterVariables = elements
-                        .map(element => element.name)
```
Comment (ljharb) [inline lib/rules/prefer-const.js]: `element && element.name`? or `.filter(Boolean).map(element => element.name)`?

Comment (mjmasn) [reply lib/rules/prefer-const.js]: @ljharb :man_facepalming: yep makes sense!

**Comment by mjmasn** [comment]
@ljharb any idea why the commit-message check is failing on `PR title doesn't follow commit message guidelines`? Per the contributing document it starts with `Fix:`, is less than 72 chars and ends with `(fixes #issuenumber)`

**Comment by platinumazure** [comment]
Weird, the PR title looks good to be as well. Just in case the bot is stuck, I'm going to close and reopen this PR to try to force it to rerun.

**Comment by platinumazure** [comment]
Figured out the commit-message issue: The PR title had a leading space, which didn't render as a space in HTML but which showed up when I went to edit the PR title. So we're good to go on that front!

File: lib/rules/prefer-const.js (hunk 1 above)
Comment (Aladdin-ADD) [reply lib/rules/prefer-const.js]: or it can be in one iteration, like:
```js
elements.some(element => element && element.name && isOuterVariableInDestructing(element.name, variable.scope) );
```

**Comment by mjmasn** [comment]
Travis isn't doing well :disappointed: I've re-run it a few times but at least 1 build has stalled around the npm install stage each time.

**Comment by Aladdin-ADD** [comment]
agreed! seems it's failing, but not related to the this change. (https://github.com/eslint/eslint/issues/10541)
