### PR TITLE
Fix: Ignore single lines for vertical alignment (fixes #2018)

### LINKED ISSUE #2018: key-spacing align colon plus one-line: true
I like the rule `"key-spacing": [2, { "align": "colon" }]` for most times, especially when yo create bigger objects, but it would also be great to have some option, to still allow an object to be created in one line.

So that this:
```js
spawn(cmd, cmdOptions, { cwd: clientName, stdio: 'inherit' });
```
and this
```js
var obj = {
    foobar  : 42,
    bat     : (2 * 2),
    default : fn()
};
```

would pass, but nothing else. Does that make sense? Is that in any way currently possible or could that be added?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9517716-key-spacing-align-colon-plus-one-line-true?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by IanVS**
Previously, if an `align` option was passed to key-spacing, the rule
would test alignment on any object with more than one property on a single line.

The changes in this commit first check if an object is a single line,
and if it is, only performs checks against `beforeColon` and `afterColon` of the properties.

### CODE REVIEW

File: lib/rules/key-spacing.js [hunk 1]
```diff
@@ -197,13 +207,17 @@ module.exports = function(context) {
             }
 
             width = widths[i];
-
-            if (align === "value") {
+            if (isSingleLine(context.getSource(node))) { // Only one line
```
Comment (btmills) [inline lib/rules/key-spacing.js]: `if (node.loc.start.line === node.loc.end.line) {` will be much faster.

File: lib/rules/key-spacing.js [hunk 2]
```diff
@@ -197,13 +207,17 @@ module.exports = function(context) {
...
                 report(property, "key", whitespace.beforeColon, beforeColon);
-                report(property, "value", whitespace.afterColon, targetWidth - width);
-            } else { // align = "colon"
-                report(property, "key", whitespace.beforeColon, targetWidth - width);
                 report(property, "value", whitespace.afterColon, afterColon);
```
Comment (btmills) [inline lib/rules/key-spacing.js]: This logic for checking only spacing is identical to [lines 252-3](https://github.com/IanVS/eslint/blob/52fa9e15ad83812256dc409045eddf6c36cb0448/lib/rules/key-spacing.js#L252-253) below.

File: docs/rules/key-spacing.md [hunk 3]
```diff
@@ -67,7 +67,7 @@ foo = { thisLineWouldBeTooLong:
 
 ### 2. Vertically align values `"align": "value"`
 
-Use the `align` option to enforce vertical alignment of values in an object literal. This mode still respects `beforeColon` and `afterColon` where possible, but it will pad with spaces after the colon where necessary. Groups of properties separated by blank lines are considered distinct and can have different alignment than other groups.
+Use the `align` option to enforce vertical alignment of values in an object literal. This mode still respects `beforeColon` and `afterColon` where possible, but it will pad with spaces after the colon where necessary. Groups of properties separated by blank lines are considered distinct and can have different alignment than other groups. Single lines of code will not be checked for vertical alignment, but will still be checked for `beforeColon` and `afterColon`.
```
Comment (btmills) [inline docs/rules/key-spacing.md]: Replacing "Single lines of code" with "Single-line object literals" or something similar would make this less ambiguous.

File: lib/rules/key-spacing.js [hunk 4]
```diff
@@ -224,7 +238,7 @@ module.exports = function(context) {
 
                     return groups;
                 }, [[]]).forEach(function(group) {
-                    verifyAlignment(group);
+                    verifyAlignment(group, node);
```
Comment (btmills) [inline lib/rules/key-spacing.js]: Since `node` is available at the very beginning, we don't need to go through the expense of assembling property groups unless we already know the object contains multiple lines. Passing `node` into `verifyAlignment` and implementing the exception there confuses the method's purpose. To avoid the duplicated code I mentioned in another comment and keep the two verification types single-purpose, I would recommend:

1. Rename `verifyAlignment` to `verifyGroupAlignment`.
1. Extract the existing contents of the `ObjectExpression` handler into a new `verifyAlignment` function.
1. Extract the existing contents of the `Property` handler into a new `verifySpacing` function.
1. Supply `verifySpacing` as the handler for `Property` nodes.
1. Within the `ObjectExpression` handler, if `node.loc.start.line === node.loc.end.line`, then `verifySpacing`, else `verifyAlignment`.

**Comment by btmills** [comment]
Thanks for putting this together! I suggested a minor refactoring in the comments that would simplify the control flow a bit. After that this looks pretty solid.

**Comment by IanVS** [comment]
Thanks for the thorough review.  I'll make the recommended changes tonight.

File: lib/rules/key-spacing.js (hunk 1 above)
Comment (IanVS) [inline lib/rules/key-spacing.js]: This was the first method I tried (actually it has to be `node.loc.end.line - node.loc.start.line === 1`),  but I seemed to have some trouble with it not always working. I'll try it again, maybe it was because of other problems in my code at that point.

Comment (IanVS) [inline lib/rules/key-spacing.js]: Nevermind, you were right of course.  I must have had some other problem in my code when I first tried that.

**Comment by IanVS** [comment]
I needed to split `verifySpacing` out a little more than you suggested, because a single `ObjectExpression` node can have multiple properties, all of which need to be checked for spacing.

While I was at it, I split up some of the other functions in a way which seemed logical to me and may promote future reuse.  Hopefully I didn't go to wild with it, let me know if you want me to combine some of them back together.

Thanks again for making me re-evaluate my approach, I think it turned out much cleaner now (and hopefully faster too).

**Comment by btmills** [comment]
The refactored code looks good, nice work! Since you mentioned it, the need for `verifyListSpacing` could be avoided by changing its call site to `node.properties.forEach(verifySpacing);`, but I expect the current implementation incurs less performance overhead. I'm happy with this. :+1: :ship:

**Comment by nzakas** [comment]
Looks good! @IanVS can you please sign our CLA? http://eslint.org/cla

**Comment by IanVS** [comment]
@nzakas I'm pretty sure I already signed for previous contributions, but I went ahead and signed again just to be sure.

**Comment by nzakas** [comment]
Sorry about that...I completely missed it. Really need to get this automated.
