### PR TITLE
Update: fix `no-unused-vars` false negative (fixes #7124)

### LINKED ISSUE #7124: "no-unused-vars" reports only the last function parameter
With the following code:
```javascript
const func = (req, res, next) => {};
```
only `next` is reported with the rule `no-unused-vars`.

This would not be an big issue but this actually triggers another bigger issue.

With the following code:
```javascript
const func = (req, res, _next) => {};
```
and the following configuration:
```
"no-unused-vars": [ 2, { "argsIgnorePattern": "^_" }]
```
nothing is reported at all ! Which is IMO more serious.

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

```
[ ] Documentation update
[x] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:
```

See #7124.

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- ~~I've updated documentation for my change (if appropriate)~~

**What changes did you make? (Give an overview)**

This PR solves a problem in combination of `{args: "after-used"}` and `argsIgnorePattern`.
If the last parameter was ignored, `{args: "after-used"}` ignored all parameters even if those are not used.

This PR changes the behavior. The new behavior is that `{args: "after-used"}` warns the last parameter in the non-ignored parameters.
If the last parameter is destructuring, this handles the parameter as ignored if all variables in the destructuring are ignored.

This might be a bit slow if `argsIgnorePattern` exists.

*semver-minor*: this is a bug fix which increases errors.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: lib/rules/no-unused-vars.js [hunk 1]
```diff
@@ -415,6 +415,33 @@ module.exports = {
         }
 
         /**
+         * Checks whether the given variable is the last parameter in the non-ignored parameters.
+         *
+         * @param {espree.Variable} variable - The variable to check.
```
Comment (nzakas) [inline lib/rules/no-unused-vars.js]: `escope.Variable`?

**Comment by nzakas** [comment]
LGTM, just one note on the comments.

File: lib/rules/no-unused-vars.js (hunk 1 above)
Comment (mysticatea) [inline lib/rules/no-unused-vars.js]: Oops, thank you!
