### PR TITLE
Fix: Object spread throws error in key-spacing rule. (fixes #5724)

### LINKED ISSUE #5724: TypeError in key-spacing rule when using object rest spread
**What version of ESLint are you using?**
`v2.5.3`

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```json
{
  "parserOptions": {
    "ecmaVersion": 6,
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  },
  "rules": {
    "key-spacing": [1, {"align": "colon"}]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
```js
var x = {...object};
```

**What did you expect to happen?**
The linting passes with no errors.

**What actually happened? Please include the actual, raw output from ESLint.**
```
$ eslint test.js                                                                                                                                                                                                                         
Cannot read property 'range' of undefined
TypeError: Cannot read property 'range' of undefined
    at getPropertyWhitespace (/home/zkhoury/tmp/eslint-tests/node_modules/eslint/lib/rules/key-spacing.js:242:25)
    at verifySpacing (/home/zkhoury/tmp/eslint-tests/node_modules/eslint/lib/rules/key-spacing.js:333:22)
    at verifyListSpacing (/home/zkhoury/tmp/eslint-tests/node_modules/eslint/lib/rules/key-spacing.js:349:13)
    at EventEmitter.ObjectExpression (/home/zkhoury/tmp/eslint-tests/node_modules/eslint/lib/rules/key-spacing.js:362:21)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/home/zkhoury/tmp/eslint-tests/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/home/zkhoury/tmp/eslint-tests/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/home/zkhoury/tmp/eslint-tests/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.traverser.traverse.enter (/home/zkhoury/tmp/eslint-tests/node_modules/eslint/lib/eslint.js:869:36)
```

### PR DESCRIPTION
**Pull request by zaygraveyard**

### CODE REVIEW

File: tests/lib/rules/key-spacing.js [hunk 1]
```diff
@@ -499,6 +499,15 @@ ruleTester.run("key-spacing", rule, {
                 mode: "minimum"
             }
         }]
+    },
+
+    // https://github.com/eslint/eslint/issues/5724
+    {
+        code: "({...object})",
```
Comment (btmills) [inline tests/lib/rules/key-spacing.js]: Can you add an invalid test similar to this for `({ a:b, ...object, c : d })` (still `align: "colon"`) with failures for the missing space before `b` and the extra space after `c` as a sanity check to make sure we don't accidentally break this in the future?

Comment (zaygraveyard) [inline tests/lib/rules/key-spacing.js]: Sure, I'm on it

**Comment by btmills** [comment]
LGTM, thanks @zaygraveyard! Just waiting for CI.
