### PR TITLE
Fix: captialized-comments fatal error fixed (fixes #7663)

### LINKED ISSUE #7663: capitalized-comments causes eslint to terminate with error on comment with just a space
**Tell us about your environment**

* **ESLint Version: 3.11.0
* **Node Version: 7.2.0
* **npm Version: 3.10.9

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

No configuration file.
```




```

**What did you do? Please include the actual source code causing the issue.**

With this file:

```js
// 
```

Note that there is a single space after the `//`.

I ran: `eslint --rule 'capitalized-comments: 2'`

**What did you expect to happen?**
Expected lint to be successful.

**What actually happened? Please include the actual, raw output from ESLint.**
```console
Cannot read property 'toLocaleLowerCase' of undefined
TypeError: Cannot read property 'toLocaleLowerCase' of undefined
    at isCommentValid (/Users/trott/.nvm/versions/node/v7.2.0/lib/node_modules/eslint/lib/rules/capitalized-comments.js:242:64)
    at processComment (/Users/trott/.nvm/versions/node/v7.2.0/lib/node_modules/eslint/lib/rules/capitalized-comments.js:262:32)
    at Array.forEach (native)
    at EventEmitter.Program (/Users/trott/.nvm/versions/node/v7.2.0/lib/node_modules/eslint/lib/rules/capitalized-comments.js:287:26)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/trott/.nvm/versions/node/v7.2.0/lib/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/trott/.nvm/versions/node/v7.2.0/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/Users/trott/.nvm/versions/node/v7.2.0/lib/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Users/trott/.nvm/versions/node/v7.2.0/lib/node_modules/eslint/lib/eslint.js:925:36)

```

### PR DESCRIPTION
**Pull request by Trott**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

https://github.com/eslint/eslint/issues/7663

**What changes did you make? (Give an overview)**
Added a test to confirm that `// ` would cause `capitalized-comments` to terminate `eslint` with a `TypeError`.

Added code to make sure that `firstWordChar` is an empty string rather than `undefined` in that case, thus avoiding the `TypeError`.

**Is there anything you'd like reviewers to focus on?**

Nope, nothing in particular.

Fix issue where comments containing a single space would cause eslint to
terminate with a TypeError.

### CODE REVIEW

File: tests/lib/rules/capitalized-comments.js [hunk 1]
```diff
@@ -40,6 +40,7 @@ ruleTester.run("capitalized-comments", rule, {
         "//\xDCber",
         "//\u03A0",
         "/* Uppercase\nsecond line need not be uppercase */",
+        "// ",
```
Comment (kaicataldo) [inline tests/lib/rules/capitalized-comments.js]: Mind adding some more test cases? My thoughts:

```
 // No options: Skips comments that only contain whitespace
"// ",
"//\t",
"/* */",
"/*\t*/",
"/*\n*/",
```

Comment (Trott) [inline tests/lib/rules/capitalized-comments.js]: Sounds good to me. Added. Thanks. (I have the branch set up so that ESLint Members can push directly to it, so if other desirable whitespace tests come to mind, feel free to add them yourself if that's easier/faster.)

File: lib/rules/capitalized-comments.js [hunk 2]
```diff
@@ -232,7 +232,7 @@ module.exports = {
             const commentWordCharsOnly = commentWithoutAsterisks
                 .replace(WHITESPACE, "");
 
-            const firstWordChar = commentWordCharsOnly[0];
+            const firstWordChar = commentWordCharsOnly[0] || "";
```
Comment (not-an-aardvark) [inline lib/rules/capitalized-comments.js]: I think it would be better to put an explicit `length` check above this line, rather than defaulting to an empty string. In all other cases `firstWordChar` will be exactly one character long. Setting it to an empty string in this case might cause confusion/unexpected behavior if the code below this line is refactored and someone forgets to account for the empty-string case.

**Comment by platinumazure** [comment]
Cripes, sorry for missing this case.

**Comment by platinumazure** [comment]
My review comment was unclear- I'm requesting test cases for other line terminators, just in case.

**Comment by Trott** [comment]
@platinumazure Do you mean add these test cases?

```js
        "/*\r*/",
        "/*\r\n*/",
        "/*\u2028*/",
        "/*\u2029*/",
```

**Comment by Trott** [comment]
Added additional tests as requested by reviewers. Anything else?

**Comment by kaicataldo** [comment]
LGTM. Thanks for contributing!
