### PR TITLE
Fix: Fix path errors in windows (fixes #4888)

### LINKED ISSUE #4888: Test failures
In preparing to do the release, I found a large number of test failures. This appears to be related to the ignore file changes (https://github.com/eslint/eslint/pull/3948). The full log is at https://gist.github.com/nzakas/4ef85b9c8b0de95e4976. There's 81 failures in total that need to be resolved before we can do a release.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29710941-test-failures?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM

File: tests/lib/cli-engine.js [hunk 1]
```diff
@@ -828,7 +828,7 @@ describe("CLIEngine", function() {
                     }
                 });
 
-                var report = engine.executeOnFiles([fixtureDir + "/fixmode"]);
+                var report = engine.executeOnFiles([path.resolve(fixtureDir, fixtureDir + "/fixmode")]);
```
Comment (mysticatea) [inline tests/lib/cli-engine.js]: `fixtureDir` seems to be twice.

Comment (gyandeeps) [inline tests/lib/cli-engine.js]: lol. yeah. hahaha it was so intense time i dint even see.
