### PR TITLE
fix: don't crash when `fs.readFile` returns promise from another realm

### LINKED ISSUE #18407: Bug: An error occurs when invoking `ESLint#lintFiles()` in Jest
### Environment

Node version: 20.12.2
npm version: 10.5.0
Local ESLint version: 9.1.1
Global ESLint version: 9.1.1
Operating System: macOS

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

* eslint.config.js

  ```js
  'use strict'
  
  module.exports = [
    {
      languageOptions: {
        parserOptions: {
          ecmaVersion: 'latest',
        },
      },
      ignores: [
        '**/node_modules/**',
      ],
      rules: {
        indent: ['error', 2],
        quotes: ['error', 'single'],
        semi: ['error', 'never'],
      },
    },
  ]
  ```
</details>

* Actual code

  ```js
  'use strict'
  
  const {
    ESLint,
  } = require('eslint')
  
  describe('ESLint Bug', () => {
    test('should not throw an error', async () => {
      const eslint = new ESLint()
      const filePaths = [
        'tests/resources',
      ]
      const expectedLength = 3
  
      const results = await eslint.lintFiles(filePaths)
  
      expect(results)
        .toHaveLength(expectedLength)
    })
  })
  ```

* Test Resources
  
  * tests/resources/indent.js
  
    ```js
    'use strict'
    
    module.exports = function doubleValue (
      value,
      ignore
    ) {
      if (ignore) {
        return value
        }
    
      return value + value
    }
    ```
  
  * tests/resources/quotes.js
  
    ```js
    'use strict'
    
    module.exports = "quotes"
    ```
  
  * tests/resources/semi.js
  
    ```js
    'use strict'
    
    global.semi = 111;
    ```

### What did you expect to happen?

* I expect that Jest shows the log below

  ```sh
   PASS  tests/__tests__/eslint-bug.js
    ESLint Bug
      ✓ should not throw an error (121 ms)
  
  Test Suites: 1 passed, 1 total
  Tests:       1 passed, 1 total
  Snapshots:   0 total
  Time:        1.221 s, estimated 2 s
  Ran all test suites.
  ```

### What actually happened?

* An error `Result is not a promise.` is thrown.

  ```sh
   FAIL  tests/__tests__/eslint-bug.js
    ESLint Bug
      ✕ should not throw an error (105 ms)
  
    ● ESLint Bug › should not throw an error
  
      Result is not a promise.
  
        13 |     const expectedLength = 3
        14 |
      > 15 |     const results = await eslint.lintFiles(filePaths)
           |                     ^
        16 |
        17 |     expect(results)
        18 |       .toHaveLength(expectedLength)
  
        at Retrier.retry (node_modules/@humanwhocodes/retry/dist/retrier.cjs:200:35)
            at Array.map (<anonymous>)
        at Object.<anonymous> (tests/__tests__/eslint-bug.js:15:21)
  
  Test Suites: 1 failed, 1 total
  Tests:       1 failed, 1 total
  Snapshots:   0 total
  Time:        1.195 s
  Ran all test suites.
  ```

### Link to Minimal Reproducible Example

https://github.com/StewEucen/eslint-bug-with-jest

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

* I wrote details as the problem in `README.md` of this repository
https://github.com/StewEucen/eslint-bug-with-jest

  - Background
  - Steps to Reproduce
  - Cause
  - Mechanism
  - How to Fix
  - Result
  - Side Effect
  - Note

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #18407

#### What changes did you make? (Give an overview)

Updated `@humanwhocodes/retry` dependency to the latest v0.2.4 that includes the fix for #18407 and added a test that fails with v0.2.3.

Also updates `lib/eslint/eslint.js` to use `require("fs/promises")` instead of `require("fs").promises`.

### CODE REVIEW

File: tests/lib/eslint/eslint.js [hunk 1]
```diff
@@ -1057,6 +1057,61 @@ describe("ESLint", () => {
             await assert.rejects(async () => await eslint.lintFiles(["lib/cli.js"]), /Expected object with parse\(\) or parseForESLint\(\) method/u);
         });
 
+        // https://github.com/eslint/eslint/issues/18407
+        it("should work in case when `fs.readFile()` returns an object that is not an instance of Promise from this realm", async () => {
```
Comment (fasttime) [inline tests/lib/eslint/eslint.js:1061]: Maybe `fs.promises.readFile()` or `fsp.readFile()`?

Comment (mdjermanovic) [reply tests/lib/eslint/eslint.js]: Updated to `fsp.readFile()` in https://github.com/eslint/eslint/pull/18416/commits/0b8b96b3a4d2388ee103bb9e589380b4425892e0.

**Review by nzakas — APPROVED** [review]
LGTM. Just waiting for the patch release period to pass.

**Review by aladdin-add — APPROVED** [review]
