### PR TITLE
Fix: `indent` param function on sameline (fixes #4174)

### LINKED ISSUE #4174: incorrect `indent` behavior for anonymous function
Code:
```
             showUpdateContactModal(
               contactType, contactId, function() {
                 selectContact(contactType, contactId); // 339
                 refreshEmergencyForm(); // 340
               }); // 341
```

What eslint wants:
```
             showUpdateContactModal(
               contactType, contactId, function() {
               selectContact(contactType, contactId); // 1339
               refreshEmergencyForm(); // 1340
             }); // 1341
```

Errors:
```
line 1339, col 17, Error - Expected indentation of 14 space characters but found 16. (indent)
line 1340, col 17, Error - Expected indentation of 14 space characters but found 16. (indent)
line 1341, col 15, Error - Expected indentation of 12 space characters but found 14. (indent)
```

Version: eslint 1.7.1

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27476649-incorrect-indent-behavior-for-anonymous-function?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

File: lib/rules/indent.js [hunk 1]
```diff
@@ -284,15 +284,16 @@ module.exports = function(context) {
...
      * @returns {boolean} True if arguments are multi-line
      */
-    function isCallArgsMultiline(node) {
-        var lastArg = node.arguments.length > 0 ? node.arguments[node.arguments.length - 1] : null;
+    function isArgBeforeCalleeNodeMultiline(node) {
+        var parent = node.parent;
 
-        if (lastArg) {
-            return lastArg.loc.end.line > node.loc.start.line;
+        if (parent.arguments.length >= 2 && parent.arguments[1] === node) {
```
Comment (nzakas) [inline lib/rules/indent.js]: Should this be `parent.arguments[parent.arguments.length-1]`?  Not sure about the hardcoded numbers.

Comment (gyandeeps) [inline lib/rules/indent.js]: This for the scenario where the second argument is a function and first argument is checking for multi-line.
Basically to solve this scenario: https://github.com/eslint/eslint/issues/4174#issuecomment-149344533

Comment (nzakas) [inline lib/rules/indent.js]: Is that too specific? Can't the same thing be applied regardless of the argument count?

Comment (gyandeeps) [inline lib/rules/indent.js]: it will not work for this scenario
```js
require('http').request({hostname: 'localhost',
                         port: 80}, 
                         "test",
                         function(res) {
                           res.end();
});
```

In this case i have 2 arguments and 1 of them is multi-line. Secondly, even if both are then also as individual arguments they are on 2 separate lines. like this
```js
require('http').request({hostname: 'localhost',
                         port: 80}, 
                         {"hi": 1,
                          "bye": 2},
                         function(res) {
                           res.end();
});
```

Comment (nzakas) [inline lib/rules/indent.js]: Ok, thanks for explaining.
