### PR TITLE
Fix: location of new-cap error messages (fixes #2025)

### LINKED ISSUE #2025: new-cap  incorrect position in the error message
I'm using 0.16.2. This code:
```
'use strict';
var Immutable = require('immutable');
var foo = Immutable.List();
```
triggers a ```new-cap``` warning, ```A function with a name starting with an uppercase letter should only be used as a constructor```, but the position is incorrect, ```Immutable``` is the word being selected (```9 characters selected```) and highlighted, instead of ```List```.

Thank you
(per @ilyavolodin suggestion in #2023)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9543089-new-cap-incorrect-position-in-the-error-message?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lo1tuma**

### CODE REVIEW

File: lib/rules/new-cap.js [hunk 1]
```diff
@@ -144,6 +144,22 @@ module.exports = function(context) {
...
+     * @returns {void}
+     */
+    function report(node, message) {
+        var callee = node.callee;
+
+        if (callee.type === "MemberExpression") {
+            callee = callee.property;
+        }
+
+        context.report(node, callee.loc.start, message);
```
Comment (ilyavolodin) [inline lib/rules/new-cap.js]: Why not just pass callee instead of node and not specify custom start location?

Comment (lo1tuma) [inline lib/rules/new-cap.js]: That would change the reported node type.

Comment (nzakas) [inline lib/rules/new-cap.js]: It's fine either way - no one sees the node type except in tests. :) Since I'd like to get a new release out today, I'd say leave as-is.

Comment (lo1tuma) [inline lib/rules/new-cap.js]: Formatters can use those types as well. I think, for this rule, it makes more sense to have the type of a `NewExpression` or `CallExpression` reported.

Comment (nzakas) [inline lib/rules/new-cap.js]: They can, but none actually do at this point. As I said, I think this is fine.
