### PR TITLE
Fix: no-unneded-ternary change code behavior after fix (fixes #8507)

### LINKED ISSUE #8507: Auto fix `no-unneeded-ternary` changes code behavior
**Tell us about your environment**

* **ESLint Version:** 3.19.0
* **Node Version:** 7.9.0
* **npm Version:** 4.5.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```
    "no-unneeded-ternary": ["error", { "defaultAssignment": false }],
```

**What did you do? Please include the actual source code causing the issue.**

The following code (line 3) is considered an error by the `no-unneeded-ternary` rule.

```js
var value = 'a'
var canSet = true
var result = value ? value : canSet ? 'unset' : 'can not set'
// NOTE: `result` is 'a'
```

When `--fix` is used, it is corrected to code that has different behavior. See:

```js
var value = 'a'
var canSet = true
var result = value || canSet ? 'unset' : 'can not set'
// NOTE: `result` is 'unset'
```

**What did you expect to happen?**

Parens should probably be added in this situation. This code would have maintained the same behavior:

```js
var result = value || (canSet ? 'unset' : 'can not set')
```

Related issue: https://github.com/feross/standard/issues/866

### PR DESCRIPTION
**Pull request by JPeer264**
**What is the purpose of this pull request? (put an "X" next to item)**
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

All Information available in #8507 

**What changes did you make? (Give an overview)**
In the `fixer` I checked if the nodestring is an `ConditionalExpression`. If so it will be surrounded by parentheses.

**Is there anything you'd like reviewers to focus on?**
Any more tests? I couldn't think of one.

### CODE REVIEW

**Comment by platinumazure** [comment]
Is there an existing test that covers the test already being parenthesize

File: tests/lib/rules/no-unneeded-ternary.js [hunk 1]
```diff
@@ -26,6 +26,7 @@ ruleTester.run("no-unneeded-ternary", rule, {
         "var a = x === 2 ? 'Yes' : false;",
         "var a = x === 2 ? 'true' : 'false';",
         "var a = foo ? foo : bar;",
+        "var value = 'a';var canSet = true;var result = value || (canSet ? 'unset' : 'can not set')",
```
Comment (JPeer264) [inline tests/lib/rules/no-unneeded-ternary.js]: @platinumazure you mean like that?

Comment (platinumazure) [inline tests/lib/rules/no-unneeded-ternary.js]: Sorry, I did a lot of fat fingering in that comment.

Your fix logic potentially parenthesizes both the node's `test` and `alternate`. I only see a new test for the `alternate`. Is there a test that covers parenthesizing of the `test`?

File: tests/lib/rules/no-unneeded-ternary.js [hunk 2]
```diff
@@ -167,6 +168,25 @@ ruleTester.run("no-unneeded-ternary", rule, {
...
+                var canSet = true
+                var result = value || (canSet ? 'unset' : 'can not set')
+            `,
+            options: [{ defaultAssignment: false }],
+            errors: [{
+                message: "Unnecessary use of conditional expression for default assignment.",
+                type: "ConditionalExpression",
+                line: 4,
+                column: 38
+            }]
```
Comment (not-an-aardvark) [inline tests/lib/rules/no-unneeded-ternary.js]: Can you add a test where `node.alternate` is already parenthesized? For example:

```js
foo ? foo : (bar ? baz : qux)
```

This should get fixed to

```js
foo || (bar ? baz : qux)
```

At the moment, I think this will result in `bar ? baz : qux` getting parenthesized twice, which isn't correct.

File: lib/rules/no-unneeded-ternary.js [hunk 3]
```diff
@@ -134,7 +134,20 @@ module.exports = {
...
                         loc: node.consequent.loc.start,
                         message: "Unnecessary use of conditional expression for default assignment.",
-                        fix: fixer => fixer.replaceText(node, `${astUtils.getParenthesisedText(sourceCode, node.test)} || ${astUtils.getParenthesisedText(sourceCode, node.alternate)}`)
+                        fix: fixer => {
+                            let nodeTest = astUtils.getParenthesisedText(sourceCode, node.test);
+                            let nodeAlternate = astUtils.getParenthesisedText(sourceCode, node.alternate);
+
+                            if (node.test.type === "ConditionalExpression") {
+                                nodeTest = `(${nodeTest})`;
+                            }
```
Comment (not-an-aardvark) [inline lib/rules/no-unneeded-ternary.js]: This is similar to @platinumazure's comment, but I'm not sure checking for `node.test` is necessary here. If it is necessary, please add a test for it; otherwise, it's fine to remove it.

Comment (JPeer264) [inline lib/rules/no-unneeded-ternary.js]: Ah yes, I thought the same and played around, but it seems it will never happen.

File: tests/lib/rules/no-unneeded-ternary.js (hunk 1 above)
Comment (JPeer264) [inline tests/lib/rules/no-unneeded-ternary.js]: Yes, I thought the same after pushing. There is actually no such case. I removed it.

File: lib/rules/no-unneeded-ternary.js [hunk 4]
```diff
@@ -134,7 +134,17 @@ module.exports = {
                         node,
                         loc: node.consequent.loc.start,
                         message: "Unnecessary use of conditional expression for default assignment.",
-                        fix: fixer => fixer.replaceText(node, `${astUtils.getParenthesisedText(sourceCode, node.test)} || ${astUtils.getParenthesisedText(sourceCode, node.alternate)}`)
+                        fix: fixer => {
```
Comment (not-an-aardvark) [inline lib/rules/no-unneeded-ternary.js]: Nitpick: It might be better to use 

```js
const nodeAlternateText = node.alternate.type === "ConditionalExpression"
    ? `(${sourceCode.getText(node.alternate)})`
    : sourceCode.getText(node.alternate);
```

That way, `nodeAlternate` doesn't need to be reassigned several times.

Comment (JPeer264) [inline lib/rules/no-unneeded-ternary.js]: That doesn't work for some elements. I also thought about using `sourceCode.getText`. But some testcases will fail, as they already have parentheses included. The only possible thing I made, to avoid reassignes is following:

```js
const nodeAlternateText = node.alternate.type === "ConditionalExpression" &&
    !astUtils.isParenthesised(sourceCode, node.alternate) ?
    `(${astUtils.getParenthesisedText(sourceCode, node.alternate)})` :
    astUtils.getParenthesisedText(sourceCode, node.alternate);
```

But it is definitely harder to read.

Comment (not-an-aardvark) [inline lib/rules/no-unneeded-ternary.js]: I see. The current version looks good to me, then. :+1:

Comment (gyandeeps) [inline lib/rules/no-unneeded-ternary.js]: or maybe something like this

```js
const nodeAlternateText = getNodeAlternateText(node, sourceCode, astUtils.getParenthesisedText(sourceCode, node.alternate));
    
function getNodeAlternateText(node, sourceCode, parenText) {
    return node.alternate.type === "ConditionalExpression" && !astUtils.isParenthesised(sourceCode, node.alternate) ?
        `(${parenText})` : parenText;
}
```

Comment (JPeer264) [inline lib/rules/no-unneeded-ternary.js]: Hm, a return like this is not really possible, as it should return the `fixer`

Comment (not-an-aardvark) [inline lib/rules/no-unneeded-ternary.js]: I think it's fine as-is.

**Comment by not-an-aardvark** [comment]
Thanks for contributing!
