### PR TITLE
Fix: dot notation rule failing to catch string template (fixes #9350)

### LINKED ISSUE #9350: dot-notation doesn't work if backtick is used
**Tell us about your environment**
macOS 10.12.6, VS Code

* **ESLint Version:** 4.7.2
* **Node Version:** 8.4.0
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
	"env": {
		"browser": true,
		"commonjs": true,
		"es6": true,
		"node": false
	},
	"parserOptions": {
		"ecmaVersion": 6,
		"sourceType": "module",
		"ecmaFeatures": {
			"modules": true,
			"jsx": true
		}
	},
	"rules": {
		"no-undef": "error",
		"react/jsx-uses-react": "error",
		"react/jsx-uses-vars": "error",
		"babel/no-undef": "off",
		"no-var": "off",
		"no-use-before-define": "off",
		"curly": "off"
	},
	"plugins": [
		"react",
		"babel"
	],
	"parser": "babel-eslint",
	"extends": "dimitarnestorov/warn"
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
const features = {};
features[`time`] = true;
```

**What did you expect to happen?**
dot-notation warning

**What actually happened? Please include the actual, raw output from ESLint.**
No warning

### PR DESCRIPTION
**Pull request by philquinn**
Fixes #9350

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

I added a check for `TemplateLiteral` and if it is the case then it checks the quasi associated as long as no expression is found, as if it has an expression is not a valid dot notation.

As the fix would be reused in my chance I pulled that into a function.

Added a few test cases.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: lib/rules/dot-notation.js [hunk 1]
```diff
@@ -70,27 +101,28 @@ module.exports = {
...
+                }
+                if (
+                    node.computed &&
+                    node.property.type === "TemplateLiteral" &&
+                    node.property.expressions.length === 0 &&
+                    node.property.quasis.length === 1 &&
+                    validIdentifier.test(node.property.quasis[0].value.raw) &&
+                    (allowKeywords || keywords.indexOf(String(node.property.quasis[0].value.raw)) === -1)
+                ) {
+                    if (!(allowPattern && allowPattern.test(node.property.quasis[0].value.raw))) {
```
Comment (not-an-aardvark) [inline lib/rules/dot-notation.js]: In general I think it would be better to use the `.cooked` property of the template literal in these cases, rather than the `.raw` property. The difference is that if a template literal contains escape sequences like `\n`, the `.cooked` property will contain the "computed" escape sequence (in this case, a newline) whereas the `.raw` property will contain the raw escape sequence that was present in the string (in this case, a backslash followed by an `n`).

In this case, using `cooked` would ensure that the rule reports an error when linting strange code like ``foo[`b\ar`]``, which is equivalent to `foo.bar`.

File: lib/rules/dot-notation.js [hunk 2]
```diff
@@ -70,27 +101,28 @@ module.exports = {
...
-                                return fixer.replaceTextRange(
-                                    [leftBracket.range[0], rightBracket.range[1]],
-                                    `${textBeforeDot}.${node.property.value}${textAfterProperty}`
-                                );
+                                return fixDotNotationWithValue(fixer, node, node.property.value);
+                            }
+                        });
+                    }
+                }
+                if (
```
Comment (not-an-aardvark) [inline lib/rules/dot-notation.js]: It seems like there's some duplicated code here relating to checking keywords, checking valid identifiers, and reporting. I think that could be avoided by doing something like this:
```js
function checkComputedProperty(node, value) {
    if (validIdentifier.test(value) && /* ... */ ) {
        // ...
    }
}

return {
    MemberExpression(node) {
        if (node.computed && node.property.type === "Literal") {
            checkComputedProperty(node, node.property.value);
        } else if (node.computed && node.property.type === "TemplateLiteral" && node.property.expressions.length === 0) {
            checkComputedProperty(node, node.property.quasis[0].value.cooked);
        }

    }
};
```

This would also make `fixDotNotationWithValue` unnecessary, since there would only be one `context.report` call in the file. In other words, this would extract all of the value-checking logic into a function rather than only extracting the autofix logic.

File: lib/rules/dot-notation.js [hunk 3]
```diff
@@ -70,27 +101,28 @@ module.exports = {
...
+                    node.computed &&
+                    node.property.type === "TemplateLiteral" &&
+                    node.property.expressions.length === 0 &&
+                    node.property.quasis.length === 1 &&
```
[the remark this answers is not in the document]
Comment (philquinn) [reply lib/rules/dot-notation.js]: Really fair, I was being a bit defensive with checking here

File: lib/rules/dot-notation.js (hunk 2 above)
Comment (philquinn) [reply lib/rules/dot-notation.js]: Yeah agree thats cleaner. Will change now.

**Comment by philquinn** [comment]
@not-an-aardvark Updated PR there. Thanks for the review.

**Comment by philquinn** [comment]
Thanks for the reviews

**Comment by kaicataldo** [comment]
LGTM. Thanks for contributing to ESLint!
