### PR TITLE
Fix: `indent` on variable declaration with separate array (fixes #5237)

### LINKED ISSUE #5237: eslint (2.0) erroneously complains about correct spacing
Test files (renamed to have ending .txt for github to accept them as issue attachment):

[test.js.txt](https://github.com/eslint/eslint/files/129084/test.js.txt)
[.eslintrc.js.txt](https://github.com/eslint/eslint/files/129085/default.eslintrc.js.txt)

The code 

```
const runImapServer = function (imapAccountSettingsHash) {
    return Promise.resolve()
    .then(() => {
        [
            'APPEND', 'CREATE', 'RENAME', 'COPY', 'UID COPY', 'EXPUNGE', 'STORE', 'DELETE'
        ].forEach(command => {
            // ...
        });
    });
};
```

causes warnings/errors of the type

    Expected indentation of 12 space characters but found 8   indent

for the lines containing the (strings) array. **However**, not only is the spacing correct, what's even more telling that this is a bug is that if I change the function expression from being assigned to a `const` to instead assigning it to `module.exports.someVar` the complaining stops and the spaces are accepted! See the attached file for the full example.

This is what I get when I run `eslint test.js`:
```

$ eslint test.js

C:\Users\Michael\OneDrive\Projects\One\test.js
  6:9   warning  Expected indentation of 12 space characters but found 8   indent
  7:13  warning  Expected indentation of 16 space characters but found 12  indent
  8:9   warning  Expected indentation of 12 space characters but found 8   indent

✖ 3 problems (0 errors, 3 warnings)
```

### PR DESCRIPTION
**Pull request by BYK**
Indent was behaving incorrectly when there's an array on a separate deep
inside a variable declaration with an expression node wrapping it as the
parent.

### CODE REVIEW

**Comment by BYK** [comment]
Hi @gyandeeps! - Back to my glorious days of working on the awesome `indent` rule :D

File: lib/rules/indent.js [hunk 1]
```diff
@@ -429,13 +429,11 @@ module.exports = function(context) {
...
                 if (parent.type !== "VariableDeclarator" || parentVarNode === parentVarNode.parent.declarations[0]) {
-                    if (options.VariableDeclarator[parentVarNode.parent.kind] === 0 && (parent.type === "ObjectExpression" || parent.type === "ArrayExpression")) {
-                        nodeIndent = nodeIndent + indentSize;
-                    } else {
+                    if (parentVarNode.loc.start.line === effectiveParent.loc.start.line) {
                         nodeIndent = nodeIndent + (indentSize * options.VariableDeclarator[parentVarNode.parent.kind]);
+                    } else if (parent.type === "ObjectExpression" || parent.type === "ArrayExpression") {
+                        nodeIndent = nodeIndent + indentSize;
                     }
-                } else if (parent.loc.start.line !== node.loc.start.line && parentVarNode === parentVarNode.parent.declarations[0]) {
```
Comment (BYK) [inline lib/rules/indent.js]: This block was redundant since it would never be hit due to the repeated condition in the original `if` block.

**Comment by platinumazure** [comment]
Gaaaaah stop updating indent and making me rebase :grinning:

**Comment by BYK** [comment]
@platinumazure - welcome to the dark world of `indent`. I'm actually planning to rewrite it from scratch since the current version became a collection of hacks. You'll probably beat me to it with your `--fix` enhancement though so you can take your revenge with that :D

**Comment by gyandeeps** [comment]
LGTM. Thanks @BYK and welcome to the dark side.
