### PR TITLE
Fix: tests failing due to differences in temporary paths (fixes #4324)

### LINKED ISSUE #4324: Test failing on OSX due to differences in temporary folder paths.
Running `npm test` from head on OSX:

```
1) globUtil listFilesToProcess() should return an array with a resolved (absolute) filename:

      AssertionError: expected [ Array(1) ] to deeply equal [ Array(1) ]
      + expected - actual

       [
      -  "/private/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/one-js-file/baz.js"
      +  "/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/one-js-file/baz.js"
       ]

      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:32)
      at Context.<anonymous> (tests/lib/util/glob-util.js:123:20)

  2) globUtil listFilesToProcess() should return all files matching a glob pattern:

      AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ]
      + expected - actual

       [
      -  "/private/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/two-js-files/bar.js"
      -  "/private/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/two-js-files/foo.js"
      +  "/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/two-js-files/bar.js"
      +  "/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/two-js-files/foo.js"
       ]

      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:32)
      at Context.<anonymous> (tests/lib/util/glob-util.js:134:20)

  3) globUtil listFilesToProcess() should return all files matching multiple glob patterns:

      AssertionError: expected [ Array(3) ] to deeply equal [ Array(3) ]
      + expected - actual

       [
      -  "/private/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/two-js-files/bar.js"
      -  "/private/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/two-js-files/foo.js"
      -  "/private/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/one-js-file/baz.js"
      +  "/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/two-js-files/bar.js"
      +  "/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/two-js-files/foo.js"
      +  "/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/one-js-file/baz.js"
       ]

      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:32)
      at Context.<anonymous> (tests/lib/util/glob-util.js:149:20)

  4) globUtil listFilesToProcess() should return hidden files if included in glob pattern:

      AssertionError: expected [ Array(1) ] to deeply equal [ Array(1) ]
      + expected - actual

       [
      -  "/private/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/hidden/.foo.js"
      +  "/var/folders/_q/001g73y56vl24brvfcv0tl6m0000gn/T/eslint/fixtures/glob-util/hidden/.foo.js"
       ]

      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:32)
      at Context.<anonymous> (tests/lib/util/glob-util.js:166:20)
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27904519-test-failing-on-osx-due-to-differences-in-temporary-folder-paths?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

File: tests/lib/util/glob-util.js [hunk 1]
```diff
@@ -29,7 +30,7 @@ var fixtureDir;
  */
 function getFixturePath() {
     var args = Array.prototype.slice.call(arguments);
-    args.unshift(fixtureDir);
```
Comment (IanVS) [inline tests/lib/util/glob-util.js]: This code is also in https://github.com/eslint/eslint/blob/master/tests/lib/cli-engine.js#L53-L57.  Should this same change be made there?

Comment (alberto) [inline tests/lib/util/glob-util.js]: Those tests aren't failing because they already use `fs.realpathSync` inside the tests where needed. Maybe it could be refactored there instead, though.
