### PR TITLE
Update: Remove workaround for espree and escope bugs (fixes #5852)

### LINKED ISSUE #5852: Remove workarounds for espree and escope issues from codebase
There are a number of places where we have workarounds for bugs in `espree` and `escope` that have been fixed.

This are the files:
```
lib/rules/comma-dangle.js
lib/rules/no-dupe-args.js
lib/rules/prefer-arrow-callback.js
tests/lib/eslint.js
tests/lib/rules/no-self-assign.js
tests/lib/rules/no-unused-vars.js
```

I think in this case it's easier to see the code, so I'll do a PR.

### PR DESCRIPTION
**Pull request by alberto**
Issue is still pending approval, but I'm opening this so you can see the proposed changes.

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you very much!

**Comment by alberto** [comment]
@mysticatea since most if not all comments were yours, can you review this?

File: lib/rules/comma-dangle.js [hunk 1]
```diff
@@ -26,20 +26,7 @@ var lodash = require("lodash");
...
-            );
-
-        // TODO(t-nagashima): Remove this case after https://github.com/eslint/espree/issues/195 was fixed.
-        case "ArrayExpression":
-            return (
-                node.parent.type !== "ForOfStatement" ||
-                node.parent.left !== node ||
-                lastItem.type !== "SpreadElement"
-            );
+            return (lastItem.type !== "RestElement");
```
Comment (mysticatea) [inline lib/rules/comma-dangle.js]: I think this can be changed to 1 statement.

```js
return node.type !== "ArrayPattern" || lastItem.type !== "RestElement";
```

**Comment by mysticatea** [comment]
Others look good to me.
Could you rebase this?

**Comment by nzakas** [comment]
@alberto can you rebase?

**Comment by alberto** [comment]
Yeah, sorry, I was waiting for the CLA issue to get fixed first.

Thanks for the review @mysticatea. PR updated with suggestions and rebased.
