### PR TITLE
Fix: allow references to external globals in id-blacklist (fixes #12567)

### LINKED ISSUE #12567: id-blacklist catches calls to Number
**Tell us about your environment**

* **ESLint Version:** 6.1.0
* **Node Version:** 10.16.3
* **npm Version:** 6.13.0

**What parser (default, Babel-ESLint, etc.) are you using?**
@typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "extends": [],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "tsconfig.json",
    "sourceType": "module"
  },
  "plugins": [
    "@typescript-eslint",
    "@typescript-eslint/tslint",
    "import",
    "s2-app"
  ],
  "rules": {
    "s2-app/no-template-literals": 1,
    "s2-app/no-first": 1,
    "strict": [
      2,
      "safe"
    ],
    "no-var": "error",
    "prefer-const": "error",
    "no-shadow": [
      "error",
      {
        "hoist": "all"
      }
    ],
    "no-shadow-restricted-names": [
      2
    ],
    "@typescript-eslint/no-unused-vars": [
      2,
      {
        "vars": "all",
        "args": "after-used"
      }
    ],
    "no-use-before-define": [
      0,
      "nofunc"
    ],
    "comma-dangle": [
      2,
      "always-multiline"
    ],
    "no-cond-assign": "off",
    "no-console": [
      "error",
      {
        "allow": [
          "dirxml",
          "warn",
          "error",
          "dir",
          "timeLog",
          "assert",
          "clear",
          "count",
          "countReset",
          "group",
          "groupCollapsed",
          "groupEnd",
          "table",
          "Console",
          "markTimeline",
          "profile",
          "profileEnd",
          "timeline",
          "timelineEnd",
          "timeStamp",
          "context"
        ]
      }
    ],
    "no-debugger": "error",
    "no-alert": [
      1
    ],
    "no-constant-condition": [
      1
    ],
    "no-dupe-keys": [
      2
    ],
    "no-duplicate-case": [
      2
    ],
    "no-empty": "error",
    "no-ex-assign": [
      2
    ],
    "no-extra-boolean-cast": [
      0
    ],
    "no-extra-semi": [
      2
    ],
    "no-func-assign": [
      2
    ],
    "no-inner-declarations": [
      2,
      "both"
    ],
    "no-invalid-regexp": [
      2
    ],
    "no-irregular-whitespace": [
      2
    ],
    "no-obj-calls": [
      2
    ],
    "no-sparse-arrays": [
      2
    ],
    "no-unreachable": [
      2
    ],
    "use-isnan": "error",
    "block-scoped-var": [
      0
    ],
    "consistent-return": [
      2
    ],
    "curly": "error",
    "default-case": "off",
    "dot-notation": "off",
    "eqeqeq": [
      "error",
      "smart"
    ],
    "guard-for-in": "error",
    "no-caller": "error",
    "no-else-return": [
      2
    ],
    "no-eq-null": [
      2
    ],
    "no-eval": "error",
    "no-extra-bind": [
      2
    ],
    "no-fallthrough": "error",
    "no-floating-decimal": [
      2
    ],
    "no-implied-eval": [
      2
    ],
    "no-lone-blocks": [
      2
    ],
    "no-loop-func": [
      2
    ],
    "no-multi-str": [
      2
    ],
    "no-native-reassign": [
      2
    ],
    "no-new": [
      2
    ],
    "no-new-func": [
      2
    ],
    "no-new-wrappers": "error",
    "no-octal": [
      2
    ],
    "no-octal-escape": [
      2
    ],
    "no-param-reassign": [
      2
    ],
    "no-proto": [
      2
    ],
    "no-redeclare": "error",
    "no-return-assign": [
      2
    ],
    "no-script-url": [
      2
    ],
    "no-self-compare": [
      2
    ],
    "no-sequences": [
      2
    ],
    "no-throw-literal": [
      2
    ],
    "no-with": [
      2
    ],
    "radix": "error",
    "vars-on-top": [
      2
    ],
    "wrap-iife": [
      2,
      "any"
    ],
    "yoda": [
      2
    ],
    "indent": [
      2,
      2
    ],
    "brace-style": [
      2,
      "1tbs",
      {
        "allowSingleLine": true
      }
    ],
    "quotes": [
      2,
      "single",
      "avoid-escape"
    ],
    "camelcase": "error",
    "comma-spacing": [
      2,
      {
        "before": false,
        "after": true
      }
    ],
    "comma-style": [
      2,
      "last"
    ],
    "eol-last": "error",
    "func-names": [
      0
    ],
    "key-spacing": [
      2,
      {
        "beforeColon": false,
        "afterColon": true
      }
    ],
    "keyword-spacing": [
      2
    ],
    "max-len": [
      "error",
      {
        "code": 150
      }
    ],
    "new-cap": [
      2,
      {
        "newIsCap": true,
        "capIsNew": false,
        "properties": true
      }
    ],
    "no-multiple-empty-lines": "error",
    "no-nested-ternary": [
      2
    ],
    "no-new-object": [
      2
    ],
    "no-spaced-func": [
      2
    ],
    "no-trailing-spaces": "error",
    "no-extra-parens": [
      2,
      "functions"
    ],
    "no-underscore-dangle": "error",
    "no-warning-comments": [
      0
    ],
    "object-curly-spacing": [
      2,
      "always"
    ],
    "one-var": [
      "error",
      "never"
    ],
    "padded-blocks": [
      2,
      "never"
    ],
    "semi": [
      2,
      "always"
    ],
    "semi-spacing": [
      2,
      {
        "before": false,
        "after": true
      }
    ],
    "space-before-blocks": [
      2
    ],
    "space-before-function-paren": [
      2,
      {
        "anonymous": "always",
        "named": "never",
        "asyncArrow": "always"
      }
    ],
    "space-infix-ops": [
      2
    ],
    "spaced-comment": "error",
    "@typescript-eslint/adjacent-overload-signatures": "error",
    "@typescript-eslint/ban-types": "error",
    "@typescript-eslint/class-name-casing": "error",
    "@typescript-eslint/consistent-type-assertions": "error",
    "@typescript-eslint/explicit-member-accessibility": [
      "error",
      {
        "accessibility": "no-public"
      }
    ],
    "@typescript-eslint/indent": "off",
    "@typescript-eslint/interface-name-prefix": "error",
    "@typescript-eslint/member-delimiter-style": ["error", {
      "multiline": {
        "delimiter": "semi",
        "requireLast": true
      },
      "singleline": {
        "delimiter": "semi",
        "requireLast": false
      }
    }],
    "@typescript-eslint/member-ordering": "error",
    "@typescript-eslint/no-empty-function": "error",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-inferrable-types": "error",
    "@typescript-eslint/no-namespace": "error",
    "@typescript-eslint/no-non-null-assertion": "error",
    "@typescript-eslint/no-require-imports": "off",
    "@typescript-eslint/no-use-before-declare": "off",
    "@typescript-eslint/no-var-requires": "off",
    "@typescript-eslint/prefer-namespace-keyword": "error",
    "@typescript-eslint/quotes": [
      "error",
      "single"
    ],
    "@typescript-eslint/restrict-plus-operands": "off",
    "@typescript-eslint/semi": [
      "error",
      "always"
    ],
    "@typescript-eslint/triple-slash-reference": "error",
    "@typescript-eslint/type-annotation-spacing": "error",
    "arrow-parens": [
      "off",
      "as-needed"
    ],
    "capitalized-comments": "error",
    "constructor-super": "error",
    "id-blacklist": [
      "error",
      "any",
      "Number",
      "number",
      "String",
      "string",
      "Boolean",
      "boolean",
      "Undefined",
      "undefined"
    ],
    "id-match": "error",
    "import/no-default-export": "error",
    "import/order": "off",
    "linebreak-style": "off",
    "max-classes-per-file": [
      "error",
      1
    ],
    "max-lines": "off",
    "new-parens": "error",
    "no-bitwise": "error",
    "no-duplicate-imports": "error",
    "no-invalid-this": "error",
    "no-null/no-null": "off",
    "no-unsafe-finally": "error",
    "no-unused-expressions": "error",
    "no-unused-labels": "error",
    "prefer-arrow/prefer-arrow-functions": "off",
    "unicorn/filename-case": [
      "error",
      {
        "case": "kebabCase"
      }
    ],
    "@typescript-eslint/tslint/config": [
      "error",
      {
        "rules": {
          "ban": [
            true,
            {
              "name": "Boolean",
              "message": "Use '!!' to determine a value's truthy value."
            }
          ],
          "component-class-suffix": true,
          "component-selector": [
            true,
            "element",
            [
              "ps"
            ],
            "kebab-case"
          ],
          "directive-class-suffix": true,
          "directive-selector": [
            true,
            "attribute",
            [
              "ps"
            ],
            "kebab-case"
          ],
          "import-destructuring-spacing": true,
          "jsdoc-format": true,
          "max-interfaces-per-file": [
            true,
            1
          ],
          "no-analytics-on-ng-tags": true,
          "no-attribute-parameter-decorator": true,
          "no-event-id-on-ng-tags": true,
          "no-forward-ref": true,
          "no-input-rename": true,
          "no-mergeable-namespace": true,
          "no-output-rename": true,
          "one-line": [
            true,
            "check-catch",
            "check-else",
            "check-finally",
            "check-open-brace",
            "check-whitespace"
          ],
          "origin-ordered-imports": true,
          "rxjs-no-unsafe-catch": true,
          "rxjs-no-unsafe-first": true,
          "rxjs-no-unsafe-switchmap": true,
          "rxjs-no-unsafe-takeuntil": true,
          "trailing-comma": [
            true,
            {
              "multiline": "never",
              "singleline": "never"
            }
          ],
          "typedef": [
            true,
            "call-signature"
          ],
          "use-input-property-decorator": true,
          "use-life-cycle-interface": true,
          "use-output-property-decorator": true,
          "use-pipe-transform-interface": true,
          "whitespace": [
            true,
            "check-branch",
            "check-decl",
            "check-operator",
            "check-module",
            "check-separator",
            "check-type"
          ]
        }
      }
    ]
  },
  "settings": {}
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
isSessionOverrideProvided(): boolean {
    return !isNaN(Number.parseInt(this.sessionForm.value.accessCount, 10));
  }
```

Run via VSCode ESLint plugin, should be something like:
```bash
eslint ./src/**/*.ts -c .eslintrc.js
```

VSCode ESLint settings:
```json
{
  "eslint.lintTask.options": "./src/**/*.ts",
  "eslint.lintTask.enable": true,
  "eslint.options": {
    "configFile": ".eslintrc.js"
  },
  "eslint.validate": [
    "javascript",
    "typescript"
  ],
  "eslint.enable": true
}
```

**What did you expect to happen?**
The call to `Number.parseInt()` would not be caught by the ESLint `id-blacklist` rule.

**What actually happened? Please include the actual, raw output from ESLint.**
The call to `Number.parseInt()` is caught by eslint - `Identifier 'Number' is blacklisted.`

**Are you willing to submit a pull request to fix this bug?**
No

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Bug fix

Fixes #12567

#### What changes did you make? (Give an overview)

`id-blacklist` will now ignore identifiers that represent a reference to an external global variable:

```js
/* eslint id-blacklist: ["error", "Number", "undefined"] */

const foo = Number.parseInt(bar); // ok

let baz = undefined; // ok
```

Global variables declared in the same source code will be still invalid:

```js
/* eslint id-blacklist: ["error", "foo"] */

var foo = 1; // error

foo = 2; // error
```

#### Is there anything you'd like reviewers to focus on?

This will be still invalid although it is a reference to a global variable, because it also represents a property name:

```js
/* eslint id-blacklist: ["error", "undefined"] */

var foo = { undefined };
```

### CODE REVIEW

File: lib/rules/id-blacklist.js [hunk 1]
```diff
@@ -35,88 +134,64 @@ module.exports = {
...
-         */
-        function shouldReport(node) {
-            const parent = node.parent;
+            /*
+             * Member access has special rules for checking property names.
+             * Read access to a property with a blacklisted name is allowed, because it can be on an object that user has no control over.
+             * Write access isn't allowed, because it potentially creates a new property with a blacklisted name.
+             */
+            if (
+                parent.type === "MemberExpression" &&
```
Comment (yeonjuan) [inline lib/rules/id-blacklist.js]: maybe, Is it intended to ignore an identifier in assignment without declaration?

I tested it and recognized it pass the blacklist identifier with assignment in destructuring.

This is the case which I tested.
```js
({a: parseInt} = a); // no warning in this pr version.

// but it warns with the declaration.
var paseInt; ({a: parseInt} = a); 
```
And it is warned in v6.8.0 event without declaraion.
* [online demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgaWQtYmxhY2tsaXN0OiBbXCJlcnJvclwiLCBcInBhcnNlSW50XCJdICovXG5cbnBhcnNlSW50ID0gXCJkb29cIjtcblxuKHthOiBwYXJzZUludH0gPSBmb28pOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnsiYnJvd3NlciI6ZmFsc2UsIm5vZGUiOmZhbHNlfX19)

```js
/*eslint id-blacklist: ["error", "parseInt"] */
({a: parseInt} = foo);
```

Comment (mdjermanovic) [reply lib/rules/id-blacklist.js]: > maybe, Is this PR intended to ignoring check an identifier in an assignment that has no declaration?

Only if it is a global variable that isn't declared in the same source code. The logic is: if it is declared, then we can assume it's a user-controlled name. Otherwise, it's a built-in/env- specific/third-party global so user can't change the name. 

It could be also indeed a user-controlled name declared elsewhere, but in that case `id-blacklist` will warn in the file where it is declared.

This shouldn't be a warning because `parseInt` is a [global variable](https://github.com/sindresorhus/globals/blob/92bbb85fc797e03465fbf6e69fb881be4f07e23d/globals.json#L92) that isn't declared in this code:

```js
/*eslint id-blacklist: ["error", "parseInt"] */

({a: parseInt} = a);
```

This should be warning (2 warnings, one for each `Identifier` node) because `parseInt` is declared:

```js
/*eslint id-blacklist: ["error", "parseInt"] */

var parseInt; ({a: parseInt} = a);
```

This should be also a warning because foo isn't defined in the configuration as a global variable:

```js
/*eslint id-blacklist: ["error", "foo"] */

({a: foo} = a);
```

Comment (yeonjuan) [reply lib/rules/id-blacklist.js]: @mdjermanovic 
> Only if it is a global variable that isn't declared in the same source code. The logic is: if it is declared, then we can assume it's a user-controlled name. Otherwise, it's a built-in/env- specific/third-party global so user can't change the name.

Thanks for the explanation. 👍 it makes sense to me.

File: tests/lib/rules/id-blacklist.js [hunk 2]
```diff
@@ -855,6 +921,431 @@ ruleTester.run("id-blacklist", rule, {
...
+            errors: [
+                {
+                    messageId: "blacklisted",
+                    data: { name: "Number" },
+                    type: "Identifier"
+                }
+            ]
+        },
+        {
+            code: "var foo = [Map];", // this actually isn't a disabled global: it was never enabled because es6 environment isn't enabled
```
Comment (kaicataldo) [inline tests/lib/rules/id-blacklist.js]: :+1:
