### PR TITLE
Fix: fix no-extra-parens ignores some nodes

### LINKED ISSUE #11893: no-extra-parens ignores param and destructuring defaults
**Tell us about your environment**

* **ESLint Version:**  6.0.0 (same with 5.16.0)
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 6,
  },
  rules: {
    "no-extra-parens": "error",
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
function foo(a = (b)) {}

const bar = (a = (b)) => a;

const [a = (b)] = [];

const {c = (d)} = {};
```

```bash
eslint index.js
```

**What did you expect to happen?**

4 errors.

**What actually happened? Please include the actual, raw output from ESLint.**

Nothing, no errors.

**Are you willing to submit a pull request to fix this bug?**

Yes, I'll do it.

Inner expressions are fine (e.g. `((b * c) + d))` would be reported), only the top level is missing.

Found this while working on [#11848](https://github.com/eslint/eslint/pull/11848), the `"AssignmentPattern"` handler is missing. It should check its `.right`.

Just need help with the analysis:

`comma` operator (`"SequenceExpression"`) inside should be checked for sure.

Is there any other case where these parens could be necessary?

### LINKED ISSUE #11906: no-extra-parens ignores template literal's expressions
**Tell us about your environment**

* **ESLint Version:**  6.0.0 (same with 5.16.0)
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 6,
  },
  rules: {
    "no-extra-parens": "error",
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
let foo = `${(a)}`
```

```bash
eslint index.js
```

**What did you expect to happen?**

1 error.

**What actually happened? Please include the actual, raw output from ESLint.**

Nothing, no errors.

**Are you willing to submit a pull request to fix this bug?**

Yes, I'll do it.

Inner expressions are fine (e.g. `((b * c) + d)` would be reported as one error), only the top level is missing.

Found this while working on [#11848](https://github.com/eslint/eslint/pull/11848), the `"TemplateLiteral"` handler is missing. It should check its `expressions`.

Is there a single case where these parens could be necessary?

### PR DESCRIPTION
**Pull request by g-plane**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix 

**What changes did you make? (Give an overview)**
Fixes #11893 .
Fixes #11906 .

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by mdjermanovic** [comment]
I'm not sure but maybe `${(a, b)}`  should be an error?

```js
`${(1, 2)}` === "2"

`${1, 2}` === "2"
```

**Comment by g-plane** [comment]
This shouldn't be reported.

**Comment by kaicataldo** [comment]
@g-plane For the sake of discussion, can you share why you believe that shouldn’t be reported?

**Comment by g-plane** [comment]
@kaicataldo Oh sorry, I misread it since I read it on my phone at that time.

File: tests/lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -466,7 +466,9 @@ ruleTester.run("no-extra-parens", rule, {
         "for ((let) in foo);",
         "for ((let[foo]) in bar);",
         "for ((let)[foo] in bar);",
-        "for ((let[foo].bar) in baz);"
+        "for ((let[foo].bar) in baz);",
+
+        "let s = `${(a, b)}`"
```
Comment (platinumazure) [inline tests/lib/rules/no-extra-parens.js]: This set of parentheses seems unnecessary. Am I missing something?

Comment (g-plane) [reply tests/lib/rules/no-extra-parens.js]: Good catch.

Comment (g-plane) [reply tests/lib/rules/no-extra-parens.js]: However, `SequenceExpression` has been checked: https://github.com/eslint/eslint/blob/e5f1ccc9e2d07ad0acf149027ffc382021d54da1/lib/rules/no-extra-parens.js#L683 .

Comment (g-plane) [reply tests/lib/rules/no-extra-parens.js]: Fixed.

Comment (mdjermanovic) [reply tests/lib/rules/no-extra-parens.js]: Actually, maybe these parentheses should stay, just to avoid conflicts with the `no-sequences` rule which allows only explicitly parenthesized sequences (and some exceptions, like for-loop).

See [no-sequences docs](https://eslint.org/docs/rules/no-sequences) and #561 , the idea is that these parentheses might mean _intent_. So perhaps this rule should never warn/remove parentheses around a `SequenceExpression`? These parens will usually stay because of its lowest precedence, but there are already examples where the parens would be removed.

With all that said, I believe the last commit is correct, this logic should be in one place, like `ruleApplies()`, not in the handlers.

If this makes any sense I could open an issue?

Comment (platinumazure) [reply tests/lib/rules/no-extra-parens.js]: That's a tough one. I wonder if this rule needs to have an option to support removing parentheses around sequence expressions (because not everyone would use no-sequences and expect the parentheses behavior).

I'm okay with having this fix not worry about sequence expressions for now and discussing in a separate issue. I think there are a few other useful changes in this PR already.

@g-plane @mdjermanovic What do you think?

Comment (mdjermanovic) [reply tests/lib/rules/no-extra-parens.js]: Completely agree. My post was confusing, I believe that in [47829be](https://github.com/eslint/eslint/pull/11909/commits/47829be39d1515838fa4c2143eb875b4915bde5f) both rule and the test case are correctly representing the current rule's logic regarding this matter.

Comment (g-plane) [reply tests/lib/rules/no-extra-parens.js]: Whether adding an option or not is OK but this should be discussed at another new issue. Let's focus on: should SequenceExpression be reported and be fixed?

Comment (platinumazure) [reply tests/lib/rules/no-extra-parens.js]: I think we should preserve the old behavior for now. I think that means don't report (or fix) SequenceExpression nodes.

Comment (mdjermanovic) [reply tests/lib/rules/no-extra-parens.js]: I apologize for the confusion, my post turned out to be completely irrelevant for this PR.

SequenceExpression nodes are already being reported and fixed wherever the removal does not break syntax or semantics, i.e. wherever the parens are not necessary, for example:

* `(a, b);`
* `if ((a, b));`
* `while ((a, b));`
* `for ((a, b); (a, b); (a, b));` - all three

So I guess that this should be reported and fixed too:

```js
`${(a, b)}`
```

Comment (g-plane) [reply tests/lib/rules/no-extra-parens.js]: So keep the latest commit?

Comment (mdjermanovic) [reply tests/lib/rules/no-extra-parens.js]: > So keep the latest commit?

I would agree with that.

**Comment by g-plane** [comment]
Done.

**Comment by platinumazure** [comment]
Merged. Thanks for contributing and sorry for the delay!
