### PR TITLE
Fix: id-blacklist should ignore ObjectPatterns (fixes #12787)

### LINKED ISSUE #12787: Rule id-blacklist incorrectly flags object property reassignments
**Tell us about your environment**

* **ESLint Version:** 6.8.0
* **Node Version:** 10.15.3
* **npm Version:** 6.11.3

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
extends: airbnb
parser: babel-eslint
rules:
  space-before-function-paren: 2
  brace-style: [2, 'stroustrup']
  arrow-body-style: 0
  no-underscore-dangle: 0
  class-methods-use-this: 1
  consistent-return: 0
  no-unused-vars: 1
  no-bitwise: 0
  no-plusplus: 0
  linebreak-style: 0
  arrow-parens: [2, 'always']
  no-useless-escape: 0
  curly: [2, 'all']
  no-lonely-if: 1
  semi: 2
  max-len: [1, { code: 120, ignoreComments: true }]
  prefer-destructuring: 1
  lines-between-class-members: 0
  object-curly-newline: 0
  indent: 1
  jsx-a11y/anchor-is-valid: [ 'error', {
    components: [ 'Link' ],
    specialLink: [ 'to' ]
  }]
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/no-noninteractive-tabindex: 0
  react/prefer-stateless-function: 1
  react/no-unused-state: 1
  react/state-in-constructor: [1, "never"]
  react/jsx-one-expression-per-line: 0
  react/prop-types: 0 # This should be enabled at some point
  react/jsx-indent: 1
  import/no-extraneous-dependencies: ["error", {"devDependencies": ["test/**/*.js"]}]
  jsx-a11y/label-has-associated-control: [ 2, {
    depth: 1,
  }]
  react/forbid-component-props: ["error", {"forbid": ["style", "className"]}]
  react/forbid-dom-props: ["error", {"forbid": ["style", "className"]}]
  react/jsx-sort-props: ["error", {"callbacksLast": true, "reservedFirst": true, "shorthandFirst": true, "noSortAlphabetically": true}]
  id-blacklist: [1, "data", "err", "e", "cb", "callback"]
env:
  browser: true
  node: true
  es6: true
```

</details>

Highlight:
```yaml
id-blacklist: [1, "data", "err", "e", "cb", "callback"]
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const { data: user } = await axios.post('/api/auth', loginCredentials);
if (!user) {
  throw new Error('Error fetching authentication data');
}
```

```bash
npx eslint --ext .js --ext .jsx src/
```

**What did you expect to happen?**
The `data` property shouldn't be flagged here because it's coming _from_ the axios request and there's nothing I can do about it. I'm converting the value `response.data` to the variable `user`. However it highlights it as being as if I were assigning the data variable.

**What actually happened? Please include the actual, raw output from ESLint.**
```
45:15  warning  Identifier 'data' is blacklisted  id-blacklist
```

**Are you willing to submit a pull request to fix this bug?**
I would but I'm not sure how as I've never delved into the eslint source!

### PR DESCRIPTION
**Pull request by jpramassini**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

https://github.com/eslint/eslint/issues/12787

**What changes did you make? (Give an overview)**
I modified the should report logic to check that the `effectiveParent`'s `parent` is a block statement and added tests for the case.

**Is there anything you'd like reviewers to focus on?**
Thoughts on any potentially cleaner ways to accomplish this? This is my first PR to ESLint so I want to make sure it's up to snuff.

### CODE REVIEW

**Comment by yeonjuan** [comment]
@jpramassini 
Hello.
I'm not an eslint member but leave some comments.
Issue #12787 is related to the [Destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), while the codes in your test cases are [Labeled statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label).
https://github.com/eslint/eslint/blob/ec3983c9d1fbc65185065d235f627a43d8cf9a1e/tests/lib/rules/id-blacklist.js#L69

**Comment by jpramassini** [comment]
@yeonjuan This is a very good point, dumb mistake on my part. I'll update my test cases later today.

**Comment by kaicataldo** [comment]
I also want to note that the fix should be to not warn on destructured assignments at all. From the [rule docs](https://eslint.org/docs/rules/id-blacklist#rule-details) (emphasis my own):

> It will not catch blacklisted identifiers that are:
>
> * function calls (so you can still use functions you do not have control over)
> * **object properties (so you can still use objects you do not have control over)**

Ideally, I do think the rule should warn when a property is renamed to a blacklisted identifier name in destructuring assignment, but I also think that can (and probably should) be done in a separate PR as a separate bug fix.

**Comment by jpramassini** [comment]
@kaicataldo Thanks for the help on the AST! I'll take another crack at this.

**Comment by jpramassini** [comment]
@kaicataldo Updated to ignore in Object Pattern nodes, and removed the error test case as we want to ignore it for this PR.

**Comment by kaicataldo** [comment]
You got it! Feel free to reach out with any questions you have :)

File: lib/rules/id-blacklist.js [hunk 1]
```diff
@@ -85,6 +88,8 @@ module.exports = {
         return {
 
             Identifier(node) {
+
+                // if (node.name === 'food') console.log(node)
```
Comment (kaicataldo) [inline lib/rules/id-blacklist.js]: Looks like this might have been left in accidentally 😄

File: tests/lib/rules/id-blacklist.js [hunk 2]
```diff
@@ -65,6 +65,11 @@ ruleTester.run("id-blacklist", rule, {
             code: "var obj = { key: foo.bar };",
             options: ["f", "fo", "fooo", "b", "ba", "barr", "bazz", "bingg"]
         },
+        {
+            code: "const {foo: bar} = baz",
```
Comment (kaicataldo) [inline tests/lib/rules/id-blacklist.js]: Can we also add tests for nested destructuring assignments? Example:

```js
const { foo: { bar: baz } } = baz;
```

Comment (kaicataldo) [reply tests/lib/rules/id-blacklist.js]: Would also be good to add tests for destructured function parameters (including nested `ObjectPattern`s):

```js
function foo({ bar: baz }) {}
```

**Comment by kaicataldo** [comment]
We're getting closer! Thanks for working on this.

**Comment by jpramassini** [comment]
Do we want a failing test case for `function foo({ bar: baz }) {}`? I.e. testing to make sure we're still getting the function name if `foo` is illegal?

**Comment by kaicataldo** [comment]
Sorry, that wasn't a great example. I think a test for the destructured parameters is sufficient. In the example above, that would be having `bar` blacklisted and not warning.

**Comment by kaicataldo** [comment]
That being said, additional tests are always welcome :)

**Comment by jpramassini** [comment]
I think between the existing function name tests and the added nested and destructured arguments we should be covered, so I left it out.

**Comment by kaicataldo** [comment]
One last thing from me: do you mind updating the PR title to more accurately reflect the current iteration of this PR?

File: lib/rules/id-blacklist.js [hunk 3]
```diff
@@ -101,21 +104,21 @@ module.exports = {
...
-                        effectiveParent.left.property.name === node.name)) {
+                            effectiveParent.left.type === "MemberExpression" &&
+                            effectiveParent.left.property.name === node.name)) {
                         if (isInvalid(name)) {
                             report(node);
                         }
                     }
 
-                // Properties have their own rules
+                    // Properties have their own rules
```
Comment (kaicataldo) [inline lib/rules/id-blacklist.js]: Mind undoing this? This is referring to the follow block and I think it's clearer to have it indented as it was.

File: lib/rules/id-blacklist.js [hunk 4]
```diff
@@ -101,21 +104,21 @@ module.exports = {
...
                 } else if (node.parent.type === "Property") {
 
                     if (shouldReport(effectiveParent, name)) {
                         report(node);
                     }
 
-                // Report anything that is a match and not a CallExpression
+                    // Report anything that is a match and not a CallExpression
```
Comment (kaicataldo) [inline lib/rules/id-blacklist.js]: Mind undoing this? This is referring to the follow block and I think it's clearer to have it indented as it was.

**Comment by kaicataldo** [comment]
Re the commit message check that's failing now: How about changing it to `Fix: id-blacklist should ignore ObjectPatterns (fixes #12787)`?

**Comment by kaicataldo** [comment]
You're doing great. We really appreciate the contribution!

File: lib/rules/id-blacklist.js (hunk 4 above)
Comment (kaicataldo) [reply lib/rules/id-blacklist.js]: Yeah, I see that. Strange :/ Seems like something on GitHub's end?

Comment (jpramassini) [reply lib/rules/id-blacklist.js]: Seems like it. This is the first time I've had this happen. 🤷‍♂

**Comment by jpramassini** [comment]
Awesome, thanks again for all of your help!

File: tests/lib/rules/id-blacklist.js [hunk 5]
```diff
@@ -65,6 +65,26 @@ ruleTester.run("id-blacklist", rule, {
...
+            options: ["foo", "bar"],
```
Comment (yeonjuan) [inline tests/lib/rules/id-blacklist.js]: @jpramassini 
Hi, In my opinion, this case should be included in `invalid` because it makes a new identifier `bar,` which is in the id-blacklist.

Comment (jpramassini) [reply tests/lib/rules/id-blacklist.js]: Yeah, this should definitely be invalid at some point due to the spirit of the rule. I added that to try and illustrate for now that that's intended behavior for now. Should I make a separate issue to make sure that gets tracked?

Comment (yeonjuan) [reply tests/lib/rules/id-blacklist.js]: > Should I make a separate issue to make sure that gets tracked?    

Maybe it would be welcomed, but it is up to you. :)

Comment (kaicataldo) [reply tests/lib/rules/id-blacklist.js]: An issue would be great!

**Comment by jpramassini** [comment]
@kaicataldo Unsure of where to put this, this seems like the best place to follow up. For the issue to track the reassignment identifier warning for this rule, should that issue be categorized as a bug fix, or is it a rule change proposal?

**Comment by kaicataldo** [comment]
I think it should be categorized as a semver-minor bug fix (reported as a bug fix).

**Comment by jpramassini** [comment]
@kaicataldo New issue here: https://github.com/eslint/eslint/issues/12807
