### PR TITLE
Fix: false positive new with member in no-extra-parens (fixes #12740)

### LINKED ISSUE #12740: no-extra-parens false positives with new and member expressions
**Tell us about your environment**

* **ESLint Version:** v6.8.0
* **Node Version:** v12.14.0
* **npm Version:** v6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    parserOptions: {
        ecmaVersion: 2015
    },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczogXCJlcnJvclwiICovXG5cbm5ldyAoYSgpKS5iLmM7XG5cbm5ldyAoYSgpLmIpLmM7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo4LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

```js
/* eslint no-extra-parens: "error" */

new (a()).b.c;

new (a().b).c;
```

```bash
eslint index.js --fix
```

**What did you expect to happen?**

No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

2 errors, and auto-fixed to:

```js
/* eslint no-extra-parens: "error" */

new a().b.c;

new a().b.c;
```

The original expressions are both equivalent to `new (a().b.c)`

The expressions produced in the fix are equivalent to `(new a()).b.c`, which is a different thing.

**Are you willing to submit a pull request to fix this bug?**

Yes, but please verify is this a bug.

It seems that `MemberExpression(node)` should do a better check for both `object` and `parent`.

(also, this is not a regression from #12302, it's unrelated).

### PR DESCRIPTION
**Pull request by yeonjuan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Fixes #12740 

I changed it to allow one parens if there is a "CallExpression" node in "MemberExpression" and when it used as a "NewExpression"'s callee.

### CODE REVIEW

**Comment by mdjermanovic** [comment]
@yeonjuan I think it might be good to rebase this, #12895 changed this function (and unfortunately some same lines).

File: lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -927,7 +955,8 @@ module.exports = {
             LogicalExpression: checkBinaryLogical,
 
             MemberExpression(node) {
-                const nodeObjHasExcessParens = hasExcessParens(node.object);
+                const shouldAllowWrapOnce = isMemberExpInNewCallee(node) && hasCallExpInMemberExp(node);
+                const nodeObjHasExcessParens = shouldAllowWrapOnce ? hasDoubleExcessParens(node.object) : hasExcessParens(node.object);
 
                 if (
                     nodeObjHasExcessParens &&
```
Comment (mdjermanovic) [inline lib/rules/no-extra-parens.js:962]: I think this flow might miss some extra double parens:

```js
((a + b)).length;
```

Comment (yeonjuan) [reply lib/rules/no-extra-parens.js]: @mdjermanovic 
Yes it seems a false positive in current(v7.2.0) "no-extra-parens" - [online-demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczogXCJlcnJvclwiICovXG5cbigoYSArIGIpKS5sZW5ndGg7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)
I'll try to fix it:) Thanks

File: lib/rules/no-extra-parens.js [hunk 2]
```diff
@@ -710,6 +710,20 @@ module.exports = {
...
+         * @returns {boolean} True if the node is a MemberExpression at NewExpression's callee. false otherwise.
+         */
+        function isMemberExpInNewCallee(node) {
+            if (node.type === "MemberExpression") {
+                return node.parent.type === "NewExpression" && node.parent.callee === node
+                    ? true
+                    : isMemberExpInNewCallee(node.parent);
+            }
+            return false;
+        }
```
Comment (mdjermanovic) [inline lib/rules/no-extra-parens.js:725]: I think this should go up the tree only if it's `object` child of another `MemberExpression`, otherwise this would be a false negative:

```js
"new a[(b()).c]"
```

Comment (yeonjuan) [reply lib/rules/no-extra-parens.js]: @mdjermanovic 
Thanks! 👍  I added a checking about that and test case.
