### PR TITLE
Fix: `consistent-as-needed` mode with `keyword: true` (fixes #3636)

### LINKED ISSUE #3636: Unexpected behavior using `consistent-as-needed` mode with `keyword: true` in `quote-props`
Rule `quote-props` using `consistent-as-needed` with `keyword` option enabled doesn't work as expected. As [ESLint docs](http://eslint.org/docs/rules/quote-props.html#consistent-as-needed) reflects, using `eslint` with the following code should return an error:

```js
/*eslint quote-props: [2, "consistent-as-needed", {"keywords": true}]*/
var x = {
    while: 1,
    volatile: "foo"
};
```
But instead ESLint validation pass without errors.

I know [how to implement the solution](https://github.com/eslint/eslint/pull/3554#issuecomment-137272544) to this bug and I think I can fix it without problems. But first, following the advice of one of the mantainers of this repo, I've created this issue to let other people review it.

I'm using the latest(`1.3.1`) version of ESLint with only the configuration comment of the example as configuration.

### PR DESCRIPTION
**Pull request by guerrero**
Changes made:

- Crete a test to check if the following code returns an error as described in [ESLint docs][1]:
```js
/*eslint quote-props: [2, "consistent-as-needed", {"keywords": true}]*/

var x = {
    while: 1, // `while` is a reserved word. This should return an error but it doesn't.
    volatile: "foo"
};
```
- Implement behavior to return an error if previous case occurs

[1]: http://eslint.org/docs/rules/quote-props.html#consistent-as-needed

Fixes #3636

### CODE REVIEW

File: lib/rules/quote-props.js [hunk 1]
```diff
@@ -141,6 +141,8 @@ module.exports = function(context) {
 
                     necessaryQuotes = necessaryQuotes || !areQuotesRedundant(tokens) || KEYWORDS && isKeyword(tokens[0].value);
                 }
+            } else if (KEYWORDS && checkQuotesRedundancy && key.type === "Identifier" && isKeyword(key.name)) {
+                context.report(node, "Properties should be quoted as `{{property}}` is a reserved word.");
```
Comment (BYK) [inline lib/rules/quote-props.js]: I think you should report the property node to be consistent with rule's other warnings around this.

File: tests/lib/rules/quote-props.js [hunk 2]
```diff
@@ -156,6 +156,12 @@ ruleTester.run("quote-props", rule, {
             message: "Properties shouldn't be quoted as all quotes are redundant.", type: "ObjectExpression"
         }]
     }, {
+        code: "({ while: 0, b: 0 })",
+        options: ["consistent-as-needed", {keywords: true}],
+        errors: [{
+            message: "Properties should be quoted as `{{property}}` is a reserved word.", type: "ObjectExpression"
+        }]
+    }, {
```
Comment (BYK) [inline tests/lib/rules/quote-props.js]: I'd add one more test case here for

    ({ while: 0, 'b': 0 })

**Comment by guerrero** [comment]
@BYK I've added the test you've mentioned and it generates a case not covered by `quote-props.js` implementation so I've made a little change to fix it and now it works.

Sorry for the error in my previous implementation and thanks for your support.

**Comment by BYK** [comment]
No problem, thanks for the quick fix :) I'll do the refactor anyways but this stops the bleeding for now ;)

LGTM @nzakas
