### PR TITLE
Fix: `no-unused-expressions` with `allowShortCircuit` false positive if left has no effect

### LINKED ISSUE #3675: `no-unused-expressions` behavior does not match docs for `allowShortCircuit: true`
According to the docs, this should not cause warnings:

```js
/*eslint no-unused-expressions: [2, { allowShortCircuit: true }]*/

a && b()
```

But, it gives:

```
3:1  error  Expected an assignment or function call and instead saw an expression  no-unused-expression
```

The second example given, (`a() || (b = c)`) behaves correctly.

### PR DESCRIPTION
**Pull request by mysticatea**
Fixed #3675.

### CODE REVIEW

File: lib/rules/no-unused-expressions.js [hunk 1]
```diff
@@ -64,6 +64,7 @@ module.exports = function(context) {
      * @returns {boolean} whether the given node is a valid expression
      */
     function isValidExpression(node) {
+        /* istanbul ignore if */ // ExpressionStatement.expression is never null.
         if (!node) {
```
Comment (ilyavolodin) [inline lib/rules/no-unused-expressions.js]: If it's never null should we remove this check all together?

Comment (mysticatea) [inline lib/rules/no-unused-expressions.js]: Yeah, I removed.
