### PR TITLE
Fix: Apply plugin given in CLI (fixes #3383)

### LINKED ISSUE #3383: Cannot load plugins via command line
Going by the [plugin option docs](http://eslint.org/docs/user-guide/command-line-interface#plugin), any plugins I specify with the `--plugin` option are ignored. On the other hand, if I specify a plugins property in `.eslintrc`, they are loaded.

Digging into the `lib/cli-engine` and `lib/config` modules, it seems that `config.plugins` is undefined [here](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L181):

```javascript
    config = configHelper.getConfig(filePath);
    loadPlugins(config.plugins);
```

Using v1.1.0

### PR DESCRIPTION
**Pull request by IanVS**

### CODE REVIEW

File: lib/config.js [hunk 1]
```diff
@@ -407,8 +407,14 @@ Config.prototype.getConfig = function(filePath) {
     // Step 8: Merge in command line globals
     config = util.mergeConfigs(config, { globals: this.globals });
 
+    // Step 9: Merge in command line plugins
+    if (this.options.plugins) {
```
Comment (nzakas) [inline lib/config.js]: Can you add a test for the config object as well?

Comment (IanVS) [inline lib/config.js]: Sorry, not sure I understand. Won't `config` always exist because of https://github.com/eslint/eslint/pull/3389/files#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9L378?

Comment (nzakas) [inline lib/config.js]: I mean, I'd like to see a test in tests/lib/config.js for this. You added a test for CLI, but that only transitively tests the change. You should also test it directly.

Comment (IanVS) [inline lib/config.js]: Ah yes, I see now, I can do something like https://github.com/eslint/eslint/blob/master/tests/lib/config.js#L433-L456.  I'll add it in tonight.

**Comment by IanVS** [comment]
@nzakas let me know if there are any other changes I need to make or tests I should add.

**Comment by ilyavolodin** [comment]
LGTM
