### PR TITLE
Fix: Update optionator, --no in help (fixes #1134)

### LINKED ISSUE #1134: Add --no-eslintrc to eslint -h
The `--no-eslintrc` flag is undiscoverable from `eslint -h`; I was looking for a way to disable eslintrc and only stumbled upon it by searching the docs.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/3452059-add-no-eslintrc-to-eslint-h?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gkz**
- Updated optionator to 0.5.0
Boolean options with 'default: true' now display their negated variant
in help. eg. --no-eslintrc, --no-ignore, --no-color
- Updated help messages work with that eg. 'disable' rather than
  'enable'
- Updated command line interface docs with new help output
- Rearrange docs to be in alphabetical order
- Fixed various formatting issues with the docs
- Added option 'color' to docs, was missing before

### CODE REVIEW

**Comment by gkz** [comment]
How is this looking?

File: lib/options.js [hunk 1]
```diff
@@ -86,13 +87,14 @@ module.exports = optionator({
         option: "ignore",
         type: "Boolean",
         default: "true",
-        description: "Use .eslintignore"
+        description: "Disable use of .eslintignore"
     },
     {
         option: "color",
+        alias: "colour",
         type: "Boolean",
```
Comment (nzakas) [inline lib/options.js]: This is incorrect, the default is false. `--color` is handled directly by node, we just pass it through.

File: lib/options.js [hunk 2]
```diff
@@ -17,6 +17,7 @@ var optionator = require("optionator");
 // exports "parse(args)", "generateHelp()", and "generateHelpForOption(optionName)"
 module.exports = optionator({
     prepend: "eslint [options] file.js [file.js] [dir]",
+    append: "Options are off by default.",
```
Comment (nzakas) [inline lib/options.js]: This seems pretty vague, I don't think we need it.

**Comment by nzakas** [comment]
Still missing comments for the removed default values?

**Comment by gkz** [comment]
I added the comment at the end aboutall of them being off by default. You want me to add the default to all options?

File: lib/options.js (hunk 1 above)
Comment (gkz) [inline lib/options.js]: Using `eslint` by default gives me coloured output, and passing in `--no-color` gives me non-coloured output.
However, I see that because you are passing stuff through that the aliasing doesn't work.

**Comment by nzakas** [comment]
Yes, I think it makes more sense close to the definition.

**Comment by gkz** [comment]
@nzakas looks like we're good

**Comment by nzakas** [comment]
Looks good, thanks!
