### PR TITLE
fix: strict removed formatters check

### LINKED ISSUE #20240: Bug: ESLint hides underlying formatter errors (misleading message)
### Environment

Node version: v22.18.0
npm version: -
Local ESLint version: v9.37.0
Global ESLint version: -
Operating System: Debian GNU/Linux 12 (bookworm)

### What parser are you using?

Default (Espree)

### What did you do?

When a formatter fails to load due to an internal error (such as a missing file in a third-party formatter), ESLint’s `loadFormatter` swallows the original exception and shows a misleading message:

```bash
The checkstyle formatter is no longer part of core ESLint. Install it manually with `npm install -D eslint-formatter-checkstyle`
```

### What did you expect to happen?

ESLint should differentiate between:

- A missing formatter module (`MODULE_NOT_FOUND` for the formatter itself), and
- A runtime error within the formatter.

It should only show the “no longer part of core” message for the former, and re-throw or surface the actual error for the latter.

### What actually happened?

Instead of surfacing the actual error (missing file in the formatter), ESLint catches all exceptions in the `try/catch` block and assumes the formatter simply isn’t installed.

### Link to Minimal Reproducible Example

-

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by ntnyq**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #20240

#### What changes did you make? (Give an overview)

This PR adds a check to make it only reporting the removed formatter message when the error code equals to `ERR_MODULE_NOT_FOUND`.

### CODE REVIEW

**Comment by mdjermanovic** [comment]
The original issue is already assigned to @githrdw. Per our policies, we should wait for the assignee to submit a PR.

https://eslint.org/docs/latest/contribute/work-on-issue#starting-work

File: lib/eslint/eslint.js [hunk 1]
```diff
@@ -1237,7 +1237,10 @@ class ESLint {
 			formatter = (await import(pathToFileURL(formatterPath))).default;
 		} catch (ex) {
 			// check for formatters that have been removed
-			if (removedFormatters.has(name)) {
+			if (
+				removedFormatters.has(name) &&
+				ex.code === "ERR_MODULE_NOT_FOUND"
+			) {
```
Comment (mdjermanovic) [inline lib/eslint/eslint.js]: As for the solution, at this point we already know whether we are trying to load a built-in formatter or an external module.

https://github.com/eslint/eslint/blob/2584187e4a305ea7a98e1a5bd4dca2a60ad132f8/lib/eslint/eslint.js#L1211-L1232

Somewhere in the above code we could set a flag that we're trying to load a built-in module, and only in that case throw an error with the `... formatter is no longer part of core ESLint` message. I think that would be more reliable than error code.

**Comment by ntnyq** [comment]
> The original issue is already assigned to @githrdw. Per our policies, we should wait for the assignee to submit a PR.
> 
> [eslint.org/docs/latest/contribute/work-on-issue#starting-work](https://eslint.org/docs/latest/contribute/work-on-issue#starting-work)

Sorry, I didn't notice that the issue has been assigned to the poster.

Should we keep this PR open and wait for the issue poster or should I close this immediately?

**Comment by lumirlumir** [comment]
@ntnyq I've left a comment on https://github.com/eslint/eslint/issues/20240#issuecomment-3466149031. 

Let's wait a bit for the original authors to reply :)

**Comment by lumirlumir** [comment]
It seems there hasn't been a reply from the original author in over two weeks.

I am wondering what's the policy here. Should we proceed with this one, or wait a bit longer?

**Comment by githrdw** [comment]
Sorry, I was not aware that I assigned myself to the issue and I cannot remove myself from it :(
Your PR looks good so if someone can approve it, that would be nice

**Comment by snitin315** [comment]
@ntnyq Are you still working on this issue? If yes, can you implement this suggestion https://github.com/eslint/eslint/pull/20241#discussion_r2463717790

**Comment by mdjermanovic** [comment]
@ntnyq you can continue working on this PR, but in the future please follow our [contributor guidelines](https://eslint.org/docs/latest/contribute/work-on-issue#starting-work) and claim the issue first.

**Review by mdjermanovic — CHANGES_REQUESTED** [review]
Just a reminder that https://github.com/eslint/eslint/pull/20241#discussion_r2463717790 hasn't been addressed yet.

**Comment by ntnyq** [comment]
> @ntnyq you can continue working on this PR, but in the future please follow our [contributor guidelines](https://eslint.org/docs/latest/contribute/work-on-issue#starting-work) and claim the issue first.

Thanks for your advice.

I was working over the weekend and just resolved the feedback.

File: tests/lib/eslint/eslint.js [hunk 2]
```diff
@@ -9824,6 +9824,39 @@ describe("ESLint", () => {
...
+				error => {
+					assert.ok(
+						!error.message.includes(
+							"no longer part of core ESLint",
+						),
+					);
+					return true;
+				},
+			);
+		});
```
Comment (mdjermanovic) [inline tests/lib/eslint/eslint.js:9859]: These tests are already passing without the code change, which is fine and we should keep them (it seems we were missing tests for this behavior), but we'll need to add another one if we want to make sure https://github.com/eslint/eslint/issues/20240 is fixed.

Comment (mdjermanovic) [reply tests/lib/eslint/eslint.js:9859]: For the new test, we could add a fixture formatter `tests/fixtures/cli-engine/node_modules/eslint-formatter-checkstyle/index.js` that throws on loading.

File: tests/lib/eslint/eslint.js [hunk 3]
```diff
@@ -9824,6 +9824,39 @@ describe("ESLint", () => {
...
+				},
+				error => {
+					assert.ok(
+						!error.message.includes(
+							"no longer part of core ESLint",
+						),
+					);
+					return true;
+				},
+			);
```
Comment (mdjermanovic) [inline tests/lib/eslint/eslint.js]:
```suggestion
			// Ensure it doesn't contain the "no longer part of core" message
			await assert.rejects(
				async () => {
					await engine.loadFormatter("table-external");
				},
				error => {
					assert.ok(
						error.message.includes(
							"There was a problem loading formatter",
						) &&
							!error.message.includes(
								"no longer part of core ESLint",
							),
						`Unexpected error message: ${error.message}`,
					);
					return true;
				},
			);
```

I think we can merge these two checks into one since they're both running the same code and checking the error message.

File: tests/lib/eslint/eslint.js (hunk 2 above)
Comment (ntnyq) [reply tests/lib/eslint/eslint.js:9859]: > For the new test, we could add a fixture formatter `tests/fixtures/cli-engine/node_modules/eslint-formatter-checkstyle/index.js` that throws on loading.

New test case added.

**Comment by ntnyq** [comment]
CI failed for knip check, https://github.com/eslint/eslint/pull/20389 is fixing it.

File: tests/lib/eslint/eslint.js [hunk 4]
```diff
@@ -9824,6 +9824,50 @@ describe("ESLint", () => {
...
+
+		it("should throw if a removed formatter from node_modules throws on loading", async () => {
+			const engine = new ESLint();
+			const formatterPath = getFixturePath(
+				"cli-engine/node_modules/eslint-formatter-checkstyle/index.js",
+			);
+
+			await assert.rejects(async () => {
+				await engine.loadFormatter(formatterPath);
+			}, /There was a problem loading formatter.*Error: Formatter loading failed/su);
```
Comment (mdjermanovic) [inline tests/lib/eslint/eslint.js]:
```suggestion
			const engine = new ESLint({
				cwd: getFixturePath("cli-engine"),
			});

			await assert.rejects(async () => {
				await engine.loadFormatter("checkstyle");
			}, /There was a problem loading formatter.*Error: Formatter loading failed/su);
```

We should pass just the formatter name to verify that the problem is fixed. With the full path, the test was passing without the code change.

Comment (ntnyq) [reply tests/lib/eslint/eslint.js]: Hmm, now I got it. Thank you very much for you help.
