### PR TITLE
Fix: `object-curly-spacing` shows the incorrect column for opening brace

### LINKED ISSUE #3438: `object-curly-spacing` shows the incorrect column for opening brace
The column number points to before `{` where as it should point right after when an error occurs. Example:

```js
var a = { a: 1};  // 1:9 - There should be no space after '{' (object-curly-spacing)
```

Column number here should be `10` instead since that is where the unexpected space is.

### PR DESCRIPTION
**Pull request by BYK**
Fixes #3438

### CODE REVIEW

File: lib/rules/object-curly-spacing.js [hunk 1]
```diff
@@ -67,7 +67,7 @@ module.exports = function(context) {
     * @returns {void}
     */
     function reportRequiredBeginningSpace(node, token) {
-        context.report(node, token.loc.start,
+        context.report(node, token.loc.end,
```
Comment (gyandeeps) [inline lib/rules/object-curly-spacing.js]: I think we should not make the change here. Because at that time it will actually show the wrong location to put space.

File: tests/lib/rules/object-curly-spacing.js [hunk 2]
```diff
@@ -229,7 +229,7 @@ ruleTester.run("object-curly-spacing", rule, {
                     message: "A space is required after '{'",
                     type: "ImportDeclaration",
                     line: 1,
-                    column: 11
+                    column: 12
```
Comment (gyandeeps) [inline tests/lib/rules/object-curly-spacing.js]: Based on my top comment, this message tells me that I need a space after letter `b` which is incorrect.
Correct: I need a space after `{`

**Comment by BYK** [comment]
@gyandeeps - Per our discussion on Gitter, I think we're good to go, right?

**Comment by gyandeeps** [comment]
LGTM
