### PR TITLE
Fix: `radix` rule false positive at shadowed variables (fixes #5639)

### LINKED ISSUE #5639: Incorrect error when using LoDash' parseInt via destructuring
**What version of ESLint are you using?**

2.4.0. I'm using the latest `gulp-eslint`.

**What parser (default, Babel-ESLint, etc.) are you using?**

"babel-eslint": "^4.0.5",

**Please show your full configuration:**

```
"radix": [ 2 ],
```

**What did you do? Please include the actual source code causing the issue.**

```
import { parseInt } from 'lodash';
const result = parseInt('10');
```

**What did you expect to happen?**

Linting should pass. LoDash' `parseInt` implicitly uses base 10 as radix.

**What actually happened? Please include the actual, raw output from ESLint.**

I receive error message: `error    Missing radix parameter    radix`

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #5639.

I made this rule relying on escope's variables to handle shadowings.

### CODE REVIEW

File: lib/rules/radix.js [hunk 1]
```diff
@@ -6,67 +6,159 @@
...
+ * @param {escope.Variable} variable - A variable to check.
+ * @returns {boolean} `true` if the variable is shadowed.
+ */
+function isShadowed(variable) {
+    return variable.defs.length >= 1;
+}
 
-    var mode = context.options[0] || MODE_ALWAYS;
+/**
+ * Checks whether a given node is a callee.
```
Comment (BYK) [inline lib/rules/radix.js]: We may wanna move this helper into ast-tools in a follow-up PR.

File: lib/rules/radix.js [hunk 2]
```diff
@@ -6,67 +6,159 @@
...
+}
 
-            var radix;
+/**
+ * Checks whether a given node is a default value of radix or not.
+ *
+ * @param {ASTNode} radix - A node of radix to check.
+ * @returns {boolean} `true` if the node is the literal node of `10`.
+ */
+function isDefaultRadix(radix) {
```
Comment (BYK) [inline lib/rules/radix.js]: Isn't this the case only in strict mode?

File: lib/rules/radix.js [hunk 3]
```diff
@@ -6,67 +6,159 @@
...
                     context.report({
                         node: node,
                         message: "Invalid radix parameter."
                     });
                 }
+                break;
+        }
+    }
+
+    return {
```
Comment (BYK) [inline lib/rules/radix.js]: Can't we use `CallExpression:exit` instead? (after setting the scope in `Program:exit`?)

Comment (platinumazure) [inline lib/rules/radix.js]: You could set scope in `Program`, right?

File: lib/rules/radix.js (hunk 2 above)
Comment (mgol) [inline lib/rules/radix.js]: No, it applies to sloppy as well. `parseInt('010') === 10`

File: lib/rules/radix.js (hunk 3 above)
Comment (mysticatea) [inline lib/rules/radix.js]: We need `:exit` because of `node.parent`.

File: lib/rules/radix.js (hunk 1 above)
Comment (mysticatea) [inline lib/rules/radix.js]: Ah, yeah, I had forgotten it: https://github.com/eslint/eslint/blob/master/lib/ast-utils.js#L205

**Comment by mysticatea** [comment]
Thank you for the review.

I updated this PR:

- Use `astUtils.isCallee` instead of local `isCallee`.

File: lib/rules/radix.js (hunk 3 above)
Comment (BYK) [inline lib/rules/radix.js]: @mysticatea - I'm still unhappy about us doing our own traversal but I can't find a better way for this :(

Comment (mysticatea) [inline lib/rules/radix.js]: `variable.references` includes only references of `parseInt`. If we don't use `parseInt`, `variable.references` is empty. So this might be more efficient than checking every `CallExpression` :)

Comment (BYK) [inline lib/rules/radix.js]: Ah, good point!

**Comment by BYK** [comment]
LGTM
