### PR TITLE
Fix: `prefer-const` false negative about `eslintUsed` (fixes #5837)

### LINKED ISSUE #5837: `prefer-const` not triggered (regression from 2.4.0)
**What version of ESLint are you using?**
2.7.0

**What parser (default, Babel-ESLint, etc.) are you using?**
>  "babel-eslint": "~6.0.0"

**Please show your full configuration:**
```
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "rules": {
      "semi": [2, "never"],
      "arrow-body-style": 0
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
```
import React, { PropTypes } from 'react'

const innerStyle = {
  color: '#343434',
  color2: 'white',
}

const ToolBar = ({ style, draw }) => {
  let dynStyle = {
    ...innerStyle,
    ...style,
  }

  dynStyle.color = draw ? dynStyle.color2 : dynStyle.color

  return (
    <div style={dynStyle} />
  )
}

ToolBar.propTypes = {
  style: PropTypes.object,
  draw: PropTypes.bool,
}

export default ToolBar
```

**What did you expect to happen?**
`prefer-const` should trigger and ask me to change `let dynStyle` to `const dynStyle`

**What actually happened? Please include the actual, raw output from ESLint.**
ESLint don't trigger the `prefer-const` rule.

---

Note I tried these versions :
 - `~2.4.0` : **Works** 
 - `~2.5.0` : **Doesn't** work
 - `~2.6.0` : **Doesn't** work
 - `~2.7.0` : **Doesn't** work

---

Commits that are related to `prefer-const` (maybe I miss some) :
 - `2.6`: 9b73ffd Update: destructuring option of prefer-const rule (fixes #5594) (Toru Nagashima)
 - `2.5`: 9a22625 Fix: prefer-const false positive at non-blocked if (fixes #5610) (Toru Nagashima)
 - `2.5`: 87d74b2 Fix: prefer-const got to not change scopes (refs #5284) (Toru Nagashima)

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #5837.

This PR makes `prefer-const` warning used variables by `context.markVariableAsUsed(name)` API, **on except global scope**.

`/*exported*/` comments also are using `eslintUsed`.
I thought `prefer-const` should not warn `foo` in the following code.

```js
/*exported foo*/
let foo = 1
```

`prefer-const` still ignore used global variables by `context.markVariableAsUsed(name)` API (since `/*exported*/` comment is applied to only global variables).
But this PR will improve the issue.
In most cases, the variables that `react/jsx-use-vars` marks are on Node.js/CommonJS scope or Module scope.

**EDIT:** This needs **minor** bump since this will increase warnings.

### CODE REVIEW

File: lib/rules/prefer-const.js [hunk 1]
```diff
@@ -82,7 +82,7 @@ function canBecomeVariableDeclaration(identifier) {
  *      Otherwise, null.
  */
 function getIdentifierIfShouldBeConst(variable, ignoreReadBeforeAssign) {
-    if (variable.eslintUsed) {
+    if (variable.eslintUsed && variable.scope.type === "global") {
```
Comment (nzakas) [inline lib/rules/prefer-const.js]: Can you add a comment in the JSDoc to explain why you're checking for global scope?

**Comment by nzakas** [comment]
Lgtm, just one note about updating a comment to explain this change.

**Comment by ilyavolodin** [comment]
LGTM
