### PR TITLE
Fix: Handle parentheses correctly in `yoda` fixer (fixes #7326)

### LINKED ISSUE #7326: Automatic fix for yoda causes parsing error
**Tell us about your environment**

* **ESLint Version:** 3.7.1
* **Node Version:** 6.7.0
* **npm Version:** 3.7.4

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```
eslint --fix --no-eslintrc --rule 'yoda: 2' test.js
```

**What did you do? Please include the actual source code causing the issue.**

```js
while (0 === (a)) {}

while (0 === (a = b)) {}
```

**What did you expect to happen?**

```js
while ((a) === 0) {}

while ((a = b) === 0) {}
```

**What actually happened? Please include the actual, raw output from ESLint.**

```js
while (a === (0) {}

while (a = b === (0) {}
```

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

See https://github.com/eslint/eslint/issues/7326

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- (n/a) I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**

This updates the fixer for `yoda` to correctly handle expressions where the operands are parenthesized. Previously, the location of parentheses was not swapped when the fixer swapped the order of operands.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: tests/lib/rules/yoda.js [hunk 1]
```diff
@@ -383,6 +383,63 @@ ruleTester.run("yoda", rule, {
...
+            errors: [
+                {
+                    message: "Expected literal to be on the left side of ===.",
+                    type: "BinaryExpression"
+                }
+            ]
+        },
+        {
+            code: "if (((((((((((foo)))))))))) === ((((((5)))))));",
+            output: "if (((((((5)))))) === ((((((((((foo)))))))))));",
```
Comment (mysticatea) [inline tests/lib/rules/yoda.js]: It's funny :smile:
