### PR TITLE
Fix: fix inconsistently works option in no-extra-parens (fixes #12717)

### LINKED ISSUE #12717: no-extra-parens options work inconsistently
**Tell us about your environment**

* **ESLint Version:** v.6.8.0
* **Node Version:** v12.13.0
* **npm Version:** v6.12.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default(espree)

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

* The `enforceForArrowConditionals: false` option doesn't allow extra parentheses more than one pair. - [demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczogW1wiZXJyb3JcIiwgXCJhbGxcIiwgeyBcImVuZm9yY2VGb3JBcnJvd0NvbmRpdGlvbmFsc1wiOiBmYWxzZSB9XSAqL1xuXG5jb25zdCBiID0gYSA9PiAxID8gMiA6IDM7XG5jb25zdCBlID0gYyA9PiAoMSA/IDIgOiAzKTtcbmNvbnN0IGYgPSBjID0+ICgoKDEgPyAyIDogMykpKTsgLy8gVW5uZWNlc3NhcnkgcGFyZW50aGVzZXMgZXhwcmVzc2lvbi5cbmNvbnN0IGcgPSBjID0+ICgoKCgxID8gMiA6IDMpKSkpOyAvLyBVbm5lY2Vzc2FyeSBwYXJlbnRoZXNlcyBleHByZXNzaW9uLiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7ImJyb3dzZXIiOnRydWV9fX0=)
```js
/* eslint no-extra-parens: ["error", "all", { "enforceForArrowConditionals": false }] */

const b = a => 1 ? 2 : 3;
const e = c => (1 ? 2 : 3);
const f = c => (((1 ? 2 : 3))); // Unnecessary parentheses expression.
const g = c => ((((1 ? 2 : 3)))); // Unnecessary parentheses expression.
```
 * On the other hand, the other options allow extra parentheses without limit. - [demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczogW1wiZXJyb3JcIiwgXCJhbGxcIiwge1xuXHRcImNvbmRpdGlvbmFsQXNzaWduXCI6IGZhbHNlLFxuXHRcIm5lc3RlZEJpbmFyeUV4cHJlc3Npb25zXCI6IGZhbHNlLFxuICAgICAgICBcImlnbm9yZUpTWFwiOiBcImFsbFwiLFxuICAgICAgICBcImVuZm9yY2VGb3JTZXF1ZW5jZUV4cHJlc3Npb25zXCI6IGZhbHNlLFxuICAgICAgICBcImVuZm9yY2VGb3JOZXdJbk1lbWJlckV4cHJlc3Npb25zXCI6IGZhbHNlXG59XSAqL1xuXG53aGlsZSAoKCgoZm9vID0gYmFyKCkpKSkpIHt9XG5cbnggPSBhIHx8ICgoKCgoYiAmJiBjKSkpKSk7XG5cbmNvbnN0IGJheiA9ICgoKCg8ZGl2Lz4pKSkpO1xuXG4oKChhLCBiKSkpO1xuKChhLCBiKSk7XG4oYSwgYik7XG5cbnZhciBmb28gPSAoKChuZXcgQmFyKCkpKSkuYmF6O1xudmFyIGZvbyA9ICgobmV3IEJhcigpKSkuYmF6O1xudmFyIGZvbyA9IChuZXcgQmFyKCkpLmJhejsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7ImpzeCI6dHJ1ZX19LCJydWxlcyI6e30sImVudiI6eyJicm93c2VyIjp0cnVlfX19)
```js
/* eslint no-extra-parens: ["error", "all", {
	"conditionalAssign": false,
	"nestedBinaryExpressions": false,
        "ignoreJSX": "all",
        "enforceForSequenceExpressions": false,
        "enforceForNewInMemberExpressions": false
}] */

while ((((foo = bar())))) {}

x = a || (((((b && c)))));

const baz = ((((<div/>))));

(((a, b)));
((a, b));
(a, b);

var foo = (((new Bar()))).baz;
var foo = ((new Bar())).baz;
var foo = (new Bar()).baz;
```

**What did you expect to happen?**

I think the options should work consistently.
By the docs, the option `enforceForArrowConditionals: false` should allow all extra parentheses without limitation in matched cases with the option.
>...
"enforceForArrowConditionals": false allows extra parentheses around ternary expressions which are the body of an arrow function
...

**What actually happened? Please include the actual, raw output from ESLint.**

  

**Are you willing to submit a pull request to fix this bug?**

Yes. If this issue is a bug.  After #12697 merged.

### PR DESCRIPTION
**Pull request by yeonjuan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [x] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md)) fixes #12717
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

1. Removed `!isParenthesisedTwice(node.body)` for fixing #12717.
   - It will make this rule to ignore checking "double extra parens" if the option (`enforceForNewInMemberExpressions : false`) is specified.

2. Added some tests for checks whether they ignore "double extra parens" when the option is specified.
   - Other options which not added test in this PR already have test cases ensuring it.
   - returnAssign, nestedBinaryExpressions, enforceForSequenceExpressions, enforceForNewInMemberExpressions.
#### Is there anything you'd like reviewers to focus on?

In my understanding, an arrow function's block statement body can't be parenthesized`()`, because it will change the body's type `BlockStatement` to `ObjectExpression`.

```js
var a = () => {  }; // BlockStatement
var a = () => ({ }); // ObjectExpression
```
And there is a checking about "double extra parens" when body type is not a `BlockStatement`.
```
if (node.body.type !== "BlockStatement") {
   // ...
    if (hasExcessParensWithPrecedence()) { 
 
   }
   // ...
```
So, I think `!isParenthesisedTwice(node.body)` can be removed without another effect.

### CODE REVIEW

File: tests/lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -1122,12 +1153,10 @@ ruleTester.run("no-extra-parens", rule, {
                 }
             ]
         },
-
-        // ["all", { enforceForArrowConditionals: false }]
         {
             code: "var a = (b) => ((1 ? 2 : 3))",
             output: "var a = (b) => (1 ? 2 : 3)",
-            options: ["all", { enforceForArrowConditionals: false }],
+            options: ["all", { enforceForArrowConditionals: true }],
```
Comment (kaicataldo) [inline tests/lib/rules/no-extra-parens.js]: Just to double check I'm understanding all these test changes correctly, this is the only test covering the code change in this PR, correct? All the others look to be covering existing behavior.

Comment (yeonjuan) [reply tests/lib/rules/no-extra-parens.js]: @kaicataldo 
Oh, it seems needs more test cases, I'll do that. Thanks:)

File: tests/lib/rules/no-extra-parens.js [hunk 2]
```diff
@@ -459,13 +488,15 @@ ruleTester.run("no-extra-parens", rule, {
         // ["all", { enforceForArrowConditionals: false }]
         { code: "var a = b => 1 ? 2 : 3", options: ["all", { enforceForArrowConditionals: false }] },
         { code: "var a = (b) => (1 ? 2 : 3)", options: ["all", { enforceForArrowConditionals: false }] },
+        { code: "var a = (b) => ((1 ? 2 : 3))", options: ["all", { enforceForArrowConditionals: false }] },
```
Comment (yeonjuan) [inline tests/lib/rules/no-extra-parens.js]: @kaicataldo 
> Just to double check I'm understanding all these test changes correctly, this is the only test covering the code change in this PR, correct? All the others look to be covering existing behavior.

This case is also covering the change because it warned in the actual version. -[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczogW1wiZXJyb3JcIiwgXCJhbGxcIiwgeyBcImVuZm9yY2VGb3JBcnJvd0NvbmRpdGlvbmFsc1wiOiBmYWxzZSB9XSAqL1xuXG5jb25zdCBmID0gYyA9PiAoKDEgPyAyIDogMykpOyAvLyBVbm5lY2Vzc2FyeSBwYXJlbnRoZXNlcyBleHByZXNzaW9uLiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7ImJyb3dzZXIiOmZhbHNlfX19)

File: tests/lib/rules/no-extra-parens.js (hunk 1 above)
Comment (kaicataldo) [reply tests/lib/rules/no-extra-parens.js]: Oh no, sorry, I just wanted to make sure I understood why all the test cases were added!

**Comment by mdjermanovic** [comment]
It's interesting that the non-optional exception for IIFE doesn't allow parens around IIFE if the function expression has parens:

```js
/* eslint no-extra-parens: ["error", "all"] */

((function foo() {return 1;})()) // error
```

This is actually the example from the documentation where it says that the rule always ignores extra parentheses around the immediately-invoked function expressions.

But it seems to be intentional: [#3667 (comment)](https://github.com/eslint/eslint/pull/3667#discussion_r38810646)

So I'm not sure should we change this now, or leave it as is (but fix the example in the documentation).

The rule also doesn't allow double parens around IIFE even if the function expression doesn't have parens.

File: tests/lib/rules/no-extra-parens.js [hunk 3]
```diff
@@ -1122,12 +1153,10 @@ ruleTester.run("no-extra-parens", rule, {
                 }
             ]
         },
-
-        // ["all", { enforceForArrowConditionals: false }]
         {
             code: "var a = (b) => ((1 ? 2 : 3))",
             output: "var a = (b) => (1 ? 2 : 3)",
-            options: ["all", { enforceForArrowConditionals: false }],
```
Comment (mdjermanovic) [inline tests/lib/rules/no-extra-parens.js]: This was definitely intentional ([#8439 comment](https://github.com/eslint/eslint/pull/8439#discussion_r115153519)). Unfortunately, other options don't work like this, so it's better to align.
