### PR TITLE
Fix: check template literal in prefer-numeric-literals (fixes #13045)

### LINKED ISSUE #13045: `prefer-numeric-literals` overlooks template literal
**Tell us about your environment**

* **ESLint Version:** v7.0.0-alpha.2
* **Node Version:** v11.15.0
* **npm Version:** 6.7.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

* [online-demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgcHJlZmVyLW51bWVyaWMtbGl0ZXJhbHM6IFwiZXJyb3JcIiovXG5cbnBhcnNlSW50KGAxMTExMTAxMTFgLCAyKSA9PT0gNTAzOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7ImJyb3dzZXIiOmZhbHNlLCJub2RlIjpmYWxzZX19fQ==)
```js
/*eslint prefer-numeric-literals: "error"*/

parseInt(`111110111`, 2) === 503;
```

**What did you expect to happen?**

1 error. 

**What actually happened? Please include the actual, raw output from ESLint.**

No error

**Are you willing to submit a pull request to fix this bug?**

Yes.

### PR DESCRIPTION
**Pull request by yeonjuan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [x] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

I changed it to check literal with using `astUtils.getStaticValue` and `astUtils.isStringLiteral`

#### Is there anything you'd like reviewers to focus on?

This PR will Fixes #13045

### CODE REVIEW

File: tests/lib/rules/prefer-numeric-literals.js [hunk 1]
```diff
@@ -49,9 +50,17 @@ ruleTester.run("prefer-numeric-literals", rule, {
...
+            code: "parseInt(`11`, 16n);",
+            parserOptions: { ecmaVersion: 2020 }
+        },
         {
             code: "parseInt(1n, 2);",
             parserOptions: { ecmaVersion: 2020 }
+        },
+        {
+            code: "parseInt(`11${foo}`, 2);",
+            parserOptions: { ecmaVersion: 2016 }
```
Comment (mdjermanovic) [inline tests/lib/rules/prefer-numeric-literals.js]: I think that `ecmaVersion: 2016` isn't necessary here?

Comment (yeonjuan) [reply tests/lib/rules/prefer-numeric-literals.js]: @mdjermanovic it is unnecessary. Thanks! I changed it

**Comment by kaicataldo** [comment]
Thanks for contributing!
