### PR TITLE
fix: object-shorthand loses type parameters when auto-fixing

### LINKED ISSUE #18429: Bug: object-shorthand loses type parameters when auto-fixing
### Environment

Node version: v18.19.0
npm version: v10.7.0
Local ESLint version: v8.57.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 23.4.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "object-shorthand": [
      "error",
      "always",
      { avoidExplicitReturnArrows: true },
    ],
  },
};
```
</details>

Run auto-fix on this:

```js
const testObj = {
  myMethod: <T>(obj: T): T => {
    return obj;
  },
};
```

### What did you expect to happen?

```ts
const testObj = {
  myMethod<T>(obj: T): T {
    return obj;
  },
};
```

### What actually happened?

```ts
const testObj = {
  myMethod(obj: T): T {
    return obj;
  },
};
```

### Link to Minimal Reproducible Example

https://typescript-eslint.io/play/#ts=5.4.5&fileType=.ts&code=MYewdgzgLgBFCm0DyAjAVjAvDA3gKBhgFsBPAWXigAsQATALhgB4AVAPgAoR1GWBKXlja4ChGACdKAV3FgY3NAG5RAXwA0eFcqA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQPYCMArRAYwBcBaZAC12jOoEMA7AE3TAG1xsdFpodSABoevSI3gB3RgE9Uo3hCxKcjAG64AlqwCiADwAO8LSS1kASojKxozAIIDcU1BjJxEY7AF8vAXR5fbyA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

First reported [here](https://github.com/typescript-eslint/typescript-eslint/issues/9008).

### PR DESCRIPTION
**Pull request by shulaoda**
Fixes #18429

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Fix object-shorthand loses type parameters when auto-fixing

### CODE REVIEW

File: lib/rules/object-shorthand.js [hunk 1]
```diff
@@ -285,17 +285,11 @@ module.exports = {
...
 
             let shouldAddParensAroundParameters = false;
-            let tokenBeforeParams;
-
-            if (node.value.params.length === 0) {
-                tokenBeforeParams = sourceCode.getFirstToken(node.value, astUtils.isOpeningParenToken);
-            } else {
-                tokenBeforeParams = sourceCode.getTokenBefore(node.value.params[0]);
-            }
+            const tokenBeforeParams = sourceCode.getFirstToken(node.value, token => astUtils.isOpeningAngleToken(token) || astUtils.isOpeningParenToken(token));
```
Comment (aladdin-add) [inline lib/rules/object-shorthand.js:288]: can we not explicitly check `<`/`>`(it's a ts-specific token that eslint not officially supported)?

possible just find the first token after `:`?

Comment (shulaoda) [reply lib/rules/object-shorthand.js:288]: Perhaps considering this special case? `{ case: ( async () => {}) }`
I followed the original logic. If the `<>` token is removed, it may require some changes to the original logic. Is that okay?

Comment (aladdin-add) [reply lib/rules/object-shorthand.js:288]: good point! The easiest way I've seen to do this is to check if the character is expected, e.g `function`/`async`, if not we can return `null`, so the code won't be fixed. wdyt?

Comment (shulaoda) [reply lib/rules/object-shorthand.js:288]: But this case `{ case: ( async () => {}) }` should be fixed as `{ async  case() {} }` in the original logic.
And the original logic used `methodPrefix` for `async` or `*`, instead of directly using `async () => {}` after the colon.

Comment (aladdin-add) [reply lib/rules/object-shorthand.js:288]: Well, given the complexity of the change, I'm fine with the current one. 😄

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks! Would like another review before merging.

File: lib/rules/object-shorthand.js (hunk 1 above)
Comment (shulaoda) [reply lib/rules/object-shorthand.js:288]: But I think the easiest way is to use `node.value.typeParameters` directly，I will show u.

**Comment by shulaoda** [comment]
This way, wdyt? @aladdin-add

File: lib/rules/object-shorthand.js [hunk 2]
```diff
@@ -285,24 +285,18 @@ module.exports = {
...
+                const hasParen = astUtils.isOpeningParenToken(sourceCode.getTokenBefore(node.value.params[0]));
+                const isTokenOutsideNode = tokenBeforeParams && tokenBeforeParams.range[0] < node.range[0];
 
                 shouldAddParensAroundParameters = !hasParen || isTokenOutsideNode;
             }
 
             const sliceStart = shouldAddParensAroundParameters
                 ? node.value.params[0].range[0]
-                : tokenBeforeParams.range[0];
+                : (node.value.typeParameters || tokenBeforeParams).range[0];
```
Comment (mdjermanovic) [inline lib/rules/object-shorthand.js:299]: In core rules, we only use properties defined in [the ESTree Spec](https://github.com/estree/estree/tree/master), so we shouldn't use `typeParameters`.

**Comment by mdjermanovic** [comment]
Could we fix this by getting the range from the first token of `node.value` to the first token before `=>` (including both tokens in the range)? If the arrow function is async, then `async` must be the first token (is that always the case?) so in that case we'd get the first token after the `async` token as the range start. A special case would be only a single-param function without parens of params, in which case we'd wrap it in `()`.

File: lib/rules/object-shorthand.js (hunk 2 above)
Comment (shulaoda) [reply lib/rules/object-shorthand.js:299]: Okay, I will try your suggestions.

File: lib/rules/object-shorthand.js [hunk 3]
```diff
@@ -284,20 +284,20 @@ module.exports = {
...
 
             if (node.value.params.length === 1) {
-                const hasParen = astUtils.isOpeningParenToken(tokenBeforeParams);
-                const isTokenOutsideNode = tokenBeforeParams.range[0] < node.range[0];
-
-                shouldAddParensAroundParameters = !hasParen || isTokenOutsideNode;
+                shouldAddParensAroundParameters = !astUtils.isOpeningParenToken(
+                    sourceCode.getTokenBefore(node.value.params[0])
+                );
             }
```
Comment (mdjermanovic) [inline lib/rules/object-shorthand.js:301]: The range check was intended to determine whether the opening paren is a paren of params or a grouping paren around the key.

Now, for example, if the code looks like this:

```js
const obj = {
    method: (foo => {})
};
```

The autofix would be wrong:

```js
const obj = {
    methodfoo {}
};

```

Apparently, a test case that would have caught this was missing.

**Review by mdjermanovic — CHANGES_REQUESTED** [review]

File: lib/rules/object-shorthand.js (hunk 3 above)
Comment (mdjermanovic) [reply lib/rules/object-shorthand.js:301]: And the original code wasn't good, it should have been `< node.value.range[0]`, not `< node.range[0]`.

Comment (shulaoda) [reply lib/rules/object-shorthand.js:301]: I got what's your mean.

**Review by aladdin-add — APPROVED** [review]

File: lib/rules/object-shorthand.js [hunk 4]
```diff
@@ -284,18 +284,21 @@ module.exports = {
...
 
-            if (node.value.params.length === 0) {
-                tokenBeforeParams = sourceCode.getFirstToken(node.value, astUtils.isOpeningParenToken);
+            // First token should not be `async`
+            if (node.value.async) {
+                tokenBeforeParams = sourceCode.getFirstToken(node.value, token => !(token.type === "Identifier" && token.value === "async"));
             } else {
-                tokenBeforeParams = sourceCode.getTokenBefore(node.value.params[0]);
+                tokenBeforeParams = sourceCode.getFirstToken(node.value);
             }
```
Comment (mdjermanovic) [inline lib/rules/object-shorthand.js:295]: I think this works correctly, but is a bit difficult to follow as `tokenBeforeParams` can be the first token before params, but also the first token of `node.value` that isn't the first token before params, or the first token of params, or even the arrow token (e.g., `async async => {}`) depending on the code encountered.

Could we maybe simplify the code this way:

```js
// First token should not be `async`
const firstValueToken = sourceCode.getFirstToken(node.value, { skip: node.value.async ? 1 : 0 });

const sliceStart = firstValueToken.range[0];
const sliceEnd = sourceCode.getTokenBefore(arrowToken).range[1];

const oldParamText = sourceCode.text.slice(sliceStart, sliceEnd);
const newParamText = node.value.params.length === 1 && node.value.params[0].range[0] === sliceStart
    ? `(${oldParamText})`
    : oldParamText;

return fixer.replaceTextRange(
    fixRange,
    methodPrefix + newParamText + fnBody
);
```

Comment (shulaoda) [reply lib/rules/object-shorthand.js]: Very nice, thanks!

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Leaving open for @aladdin-add to re-review.

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks!
