### PR TITLE
Update: fix multiline binary operator/parentheses indentation

### LINKED ISSUE #8666: The indent complains about correctly indented expressions with parentheses
**Tell us about your environment**

* **ESLint Version:** v4.0.0-beta.0
* **Node Version:** v6.4.0
* **npm Version:** yarn v0.21.3

**What parser (default, Babel-ESLint, etc.) are you using?**

The default parser.

**Please show your full configuration:**

```
// .eslintrc.js
module.exports = {
  root: true,
  extends: "eslint:recommended",
  rules: {indent: ["warn", 2]},
}
```

**What did you do? Please include the actual source code causing the issue.**

Consider the following code, which uses parentheses to group some math which is up-indented
at the opening parenthesis. `eslint` says that the expression with the parentheses is not correctly indented.

```js
(
  1
  + (
    2  // eslint says 2 more spaces are needed here...
    - 3
  )  // ... and here.
)
```

If you apply `--fix`, you will get the following:

```js
(
  1
  + (
      2
    - 3
    )
)
```

If you write this, `eslint` doesn't complain at all:

```js
(
  1
  + 
  (
    2
    - 3
  )
)
```

**What did you expect to happen?**

These results don't make sense. The expressions inside the parentheses should be indented with only one extra level of indentation, not 2. You should be able to add a closing parenthesis on the same level of indentation as the level you opened it on. The second line which starts with an operator seemed to be ignored.

This bug doesn't exist in the alpha version, so it seems to have been introduced between the alpha and beta versions.

**What actually happened? Please include the actual, raw output from ESLint.**

`eslint` complained about what appears to be valid indentation.

### LINKED ISSUE #8710: [4.0.0] indent with flatTernaryExpressions
**Tell us about your environment**

* **ESLint Version:** 4.0.0
* **Node Version:** 8.1.0
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?**

- default

**Please show your full configuration:**

```
{
    "extends": ["mysticatea", "mysticatea/node"],
    "rules": {
        "indent": ["error", 4, {"SwitchCase": 1, "flatTernaryExpressions": true}]
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

- [no-unsupported-features.js#L94-L98](https://github.com/mysticatea/eslint-plugin-node/blob/5634718d468a69e2aea53988341721a37e8fcb4c/lib/rules/no-unsupported-features.js#L94-L98)

```js
    return (
        a == null ? b :
        semver.lt(a, b) ? a :
        /* otherwise */ b
    )
```

**What did you expect to happen?**

No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

```
C:\Users\starc\Documents\GitHub\eslint-plugin-node\lib\rules\no-unsupported-features.js
   96:1  error  Expected indentation of 4 spaces but found 8  indent
   97:1  error  Expected indentation of 4 spaces but found 8  indent
  110:1  error  Expected indentation of 4 spaces but found 8  indent
  111:1  error  Expected indentation of 4 spaces but found 8  indent
```

### LINKED ISSUE #8717: [4.0.0] indent multiline expression interacting poorly with ArrayExpression/ObjectExpression
**Tell us about your environment**

* **ESLint Version:** 4.0.0
* **Node Version:** 6.9.1
* **npm Version:** 4.6.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
https://github.com/Pyrolistical/eslint-4-indent-inline-members

```
{
  "rules": {
    "indent": [
      "error",
      2
    ]
  },
  "env": {
    "es6": true
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
a([
  b
]) || [
  c
]

a({
  b
}) || {
  c
}
```

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
```
   4:1  error  Expected indentation of 4 spaces but found 2  indent
   5:1  error  Expected indentation of 2 spaces but found 0  indent
  10:1  error  Expected indentation of 4 spaces but found 2  indent
  11:1  error  Expected indentation of 2 spaces but found 0  indent

✖ 4 problems (4 errors, 0 warnings)
  4 errors, 0 warnings potentially fixable with the `--fix` option.
```

This is related to the indent rewrite. This worked fine in eslint 3.x.

I want MemberExpression to remain at 1 to enforce this:
```
foo
  .bar
  .baz();
```

I believe this is a bug, because if you set ArrayExpression to zero, then line 2 will error.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/8666, https://github.com/eslint/eslint/issues/8717, https://github.com/eslint/eslint/issues/8710)

**What changes did you make? (Give an overview)**

Fixes #8666, fixes #8717, fixes #8710

Previously, the logic for indenting multiline parenthesized expressions assumed that the indentation of every token in the expression other than the first was dependent on the first token. However, this assumption is not always correct. This led to bugs with multiline parenthesized expressions (#8710). Additionally, the BinaryExpression listener attempted to account for this assumption by always linking its tokens' indentation to the first token's indentation, even when it didn't make sense to do so. This led to other bugs (#8666, #8717). This commit updates the parenthesis logic to avoid making that assumption and check the indentation of all the tokens properly.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: lib/rules/indent.js [hunk 1]
```diff
@@ -816,7 +816,6 @@ module.exports = {
 
             offsets.ignoreToken(operator);
             offsets.ignoreToken(tokensAfterOperator[0]);
-            offsets.setDesiredOffset(tokensAfterOperator[0], sourceCode.getFirstToken(node), 1);
```
Comment (not-an-aardvark) [inline lib/rules/indent.js]: I think this line was a holdover from when the behavior of `ignoreToken` was different and tokens that weren't the first on their line could still be "ignored".
