### PR TITLE
Fix: `prefer-arrow-callback` had been wrong at arguments

### LINKED ISSUE #4095: prefer-arrow-callback should not be triggered when a function uses the arguments object.
Arrow functions [do not have their own lexical arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_arguments), instead inheriting it from the enclosing scope.

A simple example:

```javascript
function getSomeData(callback) {
  callback(1, 2, 3);
}

getSomeData(function() {
  console.log(arguments);
});
```

This triggers the prefer-arrow-callback rule. If the switch to the arrow function is made:

```javascript
getSomeData(() => {
  console.log(arguments); // Arrow functions have no arguments object.
});
```

the value of `arguments` is not that which was intended, and will even throw an error in the global scope.

tl;dr The prefer-arrow-callback rule should also check for the use of `arguments`.

This behaviour seen in v1.6.0.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27282915-prefer-arrow-callback-should-not-be-triggered-when-a-function-uses-the-arguments-object?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #4095.

The rule should not warn function expressions if these are use of implicit `arguments`, `super`, or `new.target`.

### CODE REVIEW

File: lib/rules/prefer-arrow-callback.js [hunk 1]
```diff
@@ -81,42 +101,62 @@ function getCallbackInfo(node) {
...
+                info.this = true;
+            }
+        },
+        Super: function() {
+            var info = stack[stack.length - 1];
+            if (info) {
+                info.super = true;
+            }
+        },
+        MetaProperty: function() {
```
Comment (michaelficarra) [inline lib/rules/prefer-arrow-callback.js]: This should test specifically for `new.target`.

Comment (mysticatea) [inline lib/rules/prefer-arrow-callback.js]: Yes, I thought so, but I determined I does not test finally.
Because:

- There are not other meta properties in ES2015.
- https://github.com/eslint/espree/issues/206

Comment (michaelficarra) [inline lib/rules/prefer-arrow-callback.js]: The former is not a good excuse. It will just need updating in the near future. The latter seems like it should just be considered a blocker for this issue. You can't do this right until that bug is fixed.

Comment (nzakas) [inline lib/rules/prefer-arrow-callback.js]: Just use `getSource()` and ensure its `new.target ` for now.

Comment (michaelficarra) [inline lib/rules/prefer-arrow-callback.js]: `new.target` can be spaced like `new  .  target`.

Comment (nzakas) [inline lib/rules/prefer-arrow-callback.js]: Good point. I'm not doing further updates to Espree until it's converted to Acorn, so I think in the meantime it's okay to use the nonstandard properties on `MetaProperty` to verify that it's `new.target`. We can update the rule when we update Espree.

Comment (mysticatea) [inline lib/rules/prefer-arrow-callback.js]: I added a check for `new.target`.

**Comment by nzakas** [comment]
LGTM
