### PR TITLE
Fix: valid-jsdoc correctly checks type union (fixes #5260)

### LINKED ISSUE #5260: TypeError: Cannot read property 'name' of undefined
**What version are you using?**
eslint 2.0.0 (for node.js 5.6 code using ES 2015)

**What did you do?**
Create a test file with this code:

```
'use strict';

/**
 * @returns {Promise.<string|Buffer>}
 */
function test () {

}
```

The eslintrc is the same as the one I attached to this issue: https://github.com/eslint/eslint/issues/5237 (linked in the first comment)

**What happened?**

The JSDoc syntax `@returns {Promise.<type1|type2>}` causes an error:

```
C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:111
            currentType = type.expression.name;
                                         ^

TypeError: Cannot read property 'name' of undefined
    at getCurrentExpectedTypes (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:111:42)
    at C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:153:35
    at Array.forEach (native)
    at validateTagType (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:150:18)
    at C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:272:21
    at Array.forEach (native)
    at EventEmitter.checkJSDoc (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:208:24)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.leaveNode (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:51:22)

```

I checked the file causing the error, line 111: https://github.com/eslint/eslint/blob/master/lib/rules/valid-jsdoc.js#L110

When I add a `console.log` statement I can see that it is not safe to assume that `type.expression` exists, this is what `type` looks like when the error occurs:

```
{                                       
    "type": "UnionType",
    "elements": [
        {
            "type": "NameExpression",
            "name": "string"
        },
        {
            "type": "NameExpression",
            "name": "Buffer"
        }
    ]
}
```

Independent of if that is the correct syntax for documenting promises - and at least WebStorm interprets this exact syntax correctly and offers the correct auto-completion results for `then(...)` chains on this promise, with methods for the two types on the result - it should not throw.

### PR DESCRIPTION
**Pull request by kaicataldo**

### CODE REVIEW

File: lib/rules/valid-jsdoc.js [hunk 1]
```diff
@@ -137,7 +137,7 @@ module.exports = function(context) {
         var elements = [];
 
         if (tag.type.type === "TypeApplication") { // {Array.<String>}
-            elements = tag.type.applications;
+            elements = tag.type.applications[0].type === "UnionType" ? tag.type.applications[0].elements : tag.type.applications;
```
Comment (BYK) [inline lib/rules/valid-jsdoc.js]: I thought this required a larger refactor to handle nested structures but looks like this simple fix does it :)

Nice job!

Comment (kaicataldo) [inline lib/rules/valid-jsdoc.js]: Easier than I expected it to bee :smile:
