### PR TITLE
Fix: prefer-const produces invalid autofix (fixes #11699)

### LINKED ISSUE #11699: prefer-const produces invalid autofix when using destructuring with multiple declarators
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 12.1.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
rules:
  prefer-const: error
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
let {a, b} = c, d;
```

```bash
eslint --fix
```

**What did you expect to happen?**

I expected ESLint to not create a syntax error.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint produced the following autofixed code, which has a syntax error:

```js
const {a, b} = c, d;
```

[Demo link](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1jb25zdDogZXJyb3IgKi9cblxubGV0IHthLCBifSA9IGMsIGQ7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo5LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

This was discovered when running the fuzzer locally.

**Are you willing to submit a pull request to fix this bug?**

Yes, but I'm not sure when I'll have time.

### PR DESCRIPTION
**Pull request by mdjermanovic**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix

[issue #11699 ](https://github.com/eslint/eslint/issues/11699)

**What changes did you make? (Give an overview)**

Fixed the autofix for the following cases:

```js
let {a, b} = c, d;
```

```js
let {a, b, c} = {}, e, f;
```
```
let {a, b} = {}, c = 0;
c = 1;
```

by moving and modifying logic from `checkGroup()` to `VariableDeclaration()`

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

File: lib/rules/prefer-const.js [hunk 1]
```diff
@@ -361,109 +343,57 @@ module.exports = {
...
+                                shouldFix = false;
+                            }
+                        });
+
+                    // Don't do a fix unless all variables are initialized (or it's in a for-in or for-of loop)
+                    shouldFix = shouldFix &&
+                        (node.parent.type === "ForInStatement" || node.parent.type === "ForOfStatement" ||
+                            node.declarations.every(declaration => declaration.init));
+
+                    const declarationKindToken = sourceCode.getFirstToken(node);
```
Comment (platinumazure) [inline lib/rules/prefer-const.js]: It would probably be better to use a predicate here, in case of Typescript `declare let` or other potential token prefixes:

```suggestion
                    const declarationKindToken = sourceCode.getFirstToken(node, t => t.value === node.kind);
```

Comment (mdjermanovic) [reply lib/rules/prefer-const.js]: I'll fix this, it was inherited from `checkGroup`, as well as the autofix for each variable which isn't necessary now when we have the whole declaration.

Speaking of TypeScript, it seems that `@typescript-eslint/parser` allows `let let = 1`, so one fix without the other might produce changing several tokens.

Comment (mdjermanovic) [reply lib/rules/prefer-const.js]: It's fixed now within the second commit (multiple autofixes are also removed).

While it is most likely good to support potential prefixes, this particular example shouldn't produce a problem (like [#11441](https://github.com/eslint/eslint/issues/11441)), because only initialized variables are auto-fixed and the following is not a valid TypeScript:

```ts
declare let x = 1; // tsc error `Initializers are not allowed in ambient contexts`
```

Nevertheless, `@typescript-eslint/parser` treats this as a valid code, so the autofix without this correction would indeed replace `declare`.

**Comment by mdjermanovic** [comment]
Actually, I believe the refactoring is ** **not good** **, please **do not merge** this fix yet.

Although the tests are passing, after rereading the original code I realized I didn't fully understand intended functionality, in particular cases when destructuring happens outside of the declaration.

For instance, with the option `{"destructuring": "all"}`, this code was correct (no warnings):

```js
let a; 
let b;
({a, b} = {});
b = 1;
```

After this refactoring, this code would be incorrect.

**Comment by platinumazure** [comment]
Hi @mdjermanovic, based on your last comment I've edited "WIP:" into the PR title. This helps our PR checks to show that there's more to do before we can merge. When you're ready for us to review and merge, simply edit the PR title to remove the WIP prefix.

Thanks for your diligence, we really appreciate it!

**Comment by mdjermanovic** [comment]
I rolled back the original code and made a small fix just to address the original issue + the TypeScript fix.

As a summary, with this PR the following is done:

* Don't fix (`let` -> `const`) a declaration if there is at least one uninitialized variable in the declaration.
* Don't break TypeScript, i.e. don't replace the wrong token.

If you agree, this could close the original issue and I can open a new one:

* It would be good to clarify the intended behavior with more test cases. The first version of this fix was wrong, but the tests didn't catch it.
* There are still other bugs (e.g. `let {a, b} = {}, c = 0; c = 1;`). The code probably needs to be refactored, I'm not sure but it seems that the logic to fix or not to fix is in a place/time where there is not enough information.

**Comment by mdjermanovic** [comment]
Just a note that this is ready for a new review, and that the existing 2 approvals are no longer valid since it's a completely different code now.
