### PR TITLE
Fix: estraverse/escope to work with unknowns (fixes #5476)

### LINKED ISSUE #5476: eslint 2.3.0 has a missing dependency of estraverse
**What version of ESLint are you using?**
2.3.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**
babel-eslint

**What did you do? Please include the actual source code causing the issue.**
Out of the box configuration is throwing an error:
```sh
Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at monkeypatch (/project/node_modules/babel-eslint/index.js:59:32)
    at Object.exports.parse (/project/node_modules/babel-eslint/index.js:385:5)
    at parse (/project/node_modules/eslint/lib/eslint.js:578:27)
    at EventEmitter.module.exports.api.verify (/project/node_modules/eslint/lib/eslint.js:716:19)
    at processText (/project/node_modules/eslint/lib/cli-engine.js:187:27)
    at processFile (/project/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/project/node_modules/eslint/lib/cli-engine.js:603:23)
```

### PR DESCRIPTION
**Pull request by nzakas**
Not quite ready yet, but putting here for early feedback.

Still waiting on a new esrecurse release to npm.

### CODE REVIEW

File: lib/util/traverser.js [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+ */
+function Traverser() {
+
+    var controller = Object.create(new estraverse.Controller()),
+        originalTraverse = controller.traverse;
+
+    // intercept call to traverse() and add the fallback key to the visitor
+    controller.traverse = function(node, visitor) {
+        visitor.fallback = Traverser.getKeys;
+        return originalTraverse.call(this, node, visitor);
```
Comment (BYK) [inline lib/util/traverser.js]: Isn't this expensive? Did you run `perf` to see how this affects the performance?

Comment (nzakas) [inline lib/util/traverser.js]: Why do you think this is expensive?

Comment (platinumazure) [inline lib/util/traverser.js]: I can't comment on expensive, but I am curious why you're using composition instead of prototype inheritance here (which might allow the call stack to shrink by one level if you override traverse rather than wrap it).

Comment (nzakas) [inline lib/util/traverser.js]: I am using prototypal inheritance (line 32 is doing just that). The call stack would be the same regardless because I'd always need to call the base implementation inside my own.

**Comment by nzakas** [comment]
Looks like perf is just about even if not a bit better.

Before:

```
Single File:
  CPU Speed is 3093 with multiplier 13000000
  Performance Run #1:  4824.679365ms
  Performance Run #2:  4719.578955ms
  Performance Run #3:  4776.918791ms
  Performance Run #4:  4551.900144ms
  Performance Run #5:  4530.163554ms

  Performance budget exceeded: 4719.578955ms (limit: 4203.039120594892ms)


Multi Files (450 files):
  CPU Speed is 3093 with multiplier 39000000
  Performance Run #1:  14429.456481ms
  Performance Run #2:  14119.118036ms
  Performance Run #3:  14838.534102ms
  Performance Run #4:  40187.292232ms
  Performance Run #5:  13989.529158ms

  Performance budget exceeded: 14429.456481ms (limit: 12609.117361784674ms)
```

After:

```
Single File:
  CPU Speed is 3093 with multiplier 13000000
  Performance Run #1:  4598.792312ms
  Performance Run #2:  4618.367989ms
  Performance Run #3:  4389.600934ms
  Performance Run #4:  4566.863975ms
  Performance Run #5:  4447.044066ms

  Performance budget exceeded: 4566.863975ms (limit: 4203.039120594892ms)


Multi Files (450 files):
  CPU Speed is 3093 with multiplier 39000000
  Performance Run #1:  13736.515981ms
  Performance Run #2:  13696.480994ms
  Performance Run #3:  14025.821698ms
  Performance Run #4:  13909.789924ms
  Performance Run #5:  13746.484917ms

  Performance budget exceeded: 13746.484917ms (limit: 12609.117361784674ms)
```

File: lib/util/traverser.js (hunk 1 above)
Comment (platinumazure) [inline lib/util/traverser.js]: I had meant, why not have `Traverser` itself have a prototype equal to `Object.create(estraverse.Controller.prototype)` and override. But you are right about needing to have the extra call stack layer. For some reason I was thinking the visitor keys logic could be set on the prototype rather than passed to the `controller.traverse` function. Thanks for the clarification.

**Comment by platinumazure** [comment]
Nice work!

File: lib/util/traverser.js (hunk 1 above)
Comment (BYK) [inline lib/util/traverser.js]: @nzakas - I feared `.call` being expensive but turns out I was wrong, or this method was not called enough to see an actual difference.

**Comment by marco-c** [comment]
The error is still happening for us: https://github.com/mozilla/platatus/pull/374.

**Comment by ilyavolodin** [comment]
@marco-c This PR provides facility for `babel-eslint` to fix this error. You'll need to wait for `babel-eslint` to update.
