### PR TITLE
Fix: catastrophic backtracking in astUtils linebreak regex (fixes #7893)

### LINKED ISSUE #7893: no-multiple-empty-lines performance issue (hang?)
**Tell us about your environment**

* **ESLint Version:**
3.13.1
* **Node Version:**
6.9.2
* **npm Version:**
3.10.9

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
```
{
  "rules": {
    "no-multiple-empty-lines": [2, { "max": 1 }]  
  }
}
```

**What did you do** 
Linted a large file: [app.txt](https://github.com/eslint/eslint/files/696032/app.txt)
(I have changed the extension to .txt in order to attach it to this issue. It is obviously a js file and you should change the extension to the original .js).

**What did you expect to happen?**
Expected ESLint to produce output in a reasonable amount of time.

**What actually happened? Please include the actual, raw output from ESLint.**
ESLint did not produce any output after 10 minutes while consuming 100% of 1 CPU core.

<br>
The file is a file generated by WebPack. I am aware that linting generated files makes no sense and have added the generated files dir to .eslintignore so that performance on large files per se is not a problem for me.

The reason I would like to see some fix (a timeout? if improving the performance is not possible?) is that I was using ESLint from inside an IDE that became unresponsive while waiting for linting to complete. It took me a while to figure out what file and combination of rules was causing the behavior and it would be great if others would not have to spend more time only to figure out that they forgot to exclude their build output folder.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (see https://github.com/eslint/eslint/issues/7893)

**What changes did you make? (Give an overview)**

This fixes an issue where `astUtils.getLocationFromRangeIndex` and `astUtils.getRangeIndexFromLocation` were using a regular expression susceptible to catastrophic backtracking. The match would take quadratic time in the length of the last line of the file. Since the file in https://github.com/eslint/eslint/issues/7893 contains a 1.5 million character source map URL on the last line, rules like `no-multiple-empty-lines` would hang when using ast-utils to split the file into lines.

This issue only applies to files without trailing newlines, and is only noticable when the last line of the file contains more than 30000 characters or so. Since only a few rules use these `astUtils` functions, this would only appear when either `no-useless-escape` or `no-multiple-empty-lines` reports an error for the file.

Simplified example: Node 7.4.0 hangs when evaluating this expression.

```js
/[^\n]*\n/.test('A'.repeat(1000000))
```

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: tests/lib/rules/no-multiple-empty-lines.js [hunk 1]
```diff
@@ -309,6 +309,11 @@ ruleTester.run("no-multiple-empty-lines", rule, {
             errors: [getExpectedError(1)],
             options: [{ max: 1 }],
             parserOptions: { ecmaVersion: 6 }
+        },
+        {
```
Comment (vitorbal) [inline tests/lib/rules/no-multiple-empty-lines.js]: Perhaps we could link to the related issue here, to make sure we don't forget about it?

File: lib/ast-utils.js [hunk 2]
```diff
@@ -290,8 +290,13 @@ const lineIndexCache = new WeakMap();
 function getLineIndices(sourceCode) {
 
     if (!lineIndexCache.has(sourceCode)) {
-        const lineIndices = (sourceCode.text.match(/[^\r\n\u2028\u2029]*(\r\n|\r|\n|\u2028|\u2029)/g) || [])
-            .reduce((indices, line) => indices.concat(indices[indices.length - 1] + line.length), [0]);
+        const lineIndices = [0];
```
Comment (nzakas) [inline lib/ast-utils.js]: Can you add a comment here explaining why it's done this way? I can see some well-meaning dev thinking they can simplify this and reverting accidentally.
