### PR TITLE
Fix: remove typo that caused a crash (fixes #1963)

### LINKED ISSUE #1963: escope throws error when import is used
Maybe this is a duplicate of https://github.com/eslint/espree/issues/10 if that is the case, please feel free to close this issue :)

Here is a simple js file:

```es6
import foo from 'foo';
```

When I run eslint (0.16.0 or master) with the default parser and this .eslintrc config:

```
{
    "rules": {
        "quotes": [1, "single"],
        "no-unused-vars": 1
    },
    "ecmaFeatures": {
        "modules": true,
    },
}
```

I get the following error:

```
 
/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:73
            throw new Error(text);
                  ^
Error
    at assert (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:73:19)
    at Referencer.extend.ImportDeclaration (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:1383:13)
    at Referencer.Visitor.visit (/home/fabricio/bug/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (/home/fabricio/bug/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
    at Referencer.extend.Program (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:1236:18)
    at Referencer.Visitor.visit (/home/fabricio/bug/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Object.analyze (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:1430:20)
    at EventEmitter.module.exports.api.verify (/home/fabricio/bug/node_modules/eslint/lib/eslint.js:651:35)
    at processFile (/home/fabricio/bug/node_modules/eslint/lib/cli-engine.js:193:27)
    at /home/fabricio/bug/node_modules/eslint/lib/cli-engine.js:293:26

```

The same happens if the .eslintrc is:

```
{
    "rules": {
        "quotes": [1, "single"],
        "no-unused-vars": 1
    },
    "env":{
        "es6": true
    },
    "ecmaFeatures": {
        "modules": true
    }
}
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9306547-escope-throws-error-when-import-is-used?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by fczuardi**

### CODE REVIEW

**Comment by fczuardi** [comment]
the commit message was wrong on my branch but right on the pull request, is that a problem, https://github.com/eslint/eslint/issues/1963 is the number of the issue

**Comment by fczuardi** [comment]
Also, regarding the tests, I didn't wrote a test to test the actual crash because that should be filed as a different bug. A bug about escope crashing when a code with imports is asked to be analysed as a source type script…

**Comment by nzakas** [comment]
The message is fine. I'm not sure what you mean about a different bug. There is just one issue here.

**Comment by fczuardi** [comment]
I will create a testcase, file the proper bug on the escope code and 
then send you the link :)

File: tests/lib/eslint.js [hunk 1]
```diff
@@ -2193,6 +2193,11 @@ describe("eslint", function() {
             assert.equal(messages.length, 0);
         });
 
+        it("should send sourceType \"module\" to escope when there is an ecmaFeatures.modules (plural) and ecmaFeatures.blockBindings attributes in the config", function() {
```
Comment (nzakas) [inline tests/lib/eslint.js]: This test name is incorrect. escope isn't being tested here - you are just testing that the code parses correctly. escope is an implementation detail that is completely hidden from this test.

The test name should be something like "should properly parse import statements when ecmaFeatures.modules is true"

Comment (fczuardi) [inline tests/lib/eslint.js]: should properly parse import statements when ecmaFeatures.modules AND 
blockBindings are true

**Comment by nzakas** [comment]
If you're talking about filing a bug on escope, I don't think it's a bug. There's an asset we are hitting that is intentional. https://github.com/estools/escope/blob/master/src/referencer.js#L552

File: tests/lib/eslint.js (hunk 1 above)
Comment (fczuardi) [inline tests/lib/eslint.js]: unless we are ok with one failing test, because with only the modules attribute the ecmaVersion is not changed to 6

File: lib/eslint.js [hunk 2]
```diff
@@ -652,7 +652,7 @@ module.exports = (function() {
                 ignoreEval: true,
                 nodejsScope: currentConfig.ecmaFeatures.globalReturn,
                 ecmaVersion: currentConfig.ecmaFeatures.blockBindings ? 6 : 5,
```
Comment (nzakas) [inline lib/eslint.js]: This should be `ecmaFeatures.blockBindings || ecmaFeatures.modules`

File: tests/lib/eslint.js (hunk 1 above)
Comment (nzakas) [inline tests/lib/eslint.js]: No. We should make it work just with `modules`. See my other note.

Comment (fczuardi) [inline tests/lib/eslint.js]: yep!

Comment (fczuardi) [inline tests/lib/eslint.js]: I've pushed the suggestions on this pull request branch

**Comment by fczuardi** [comment]
regarding the original escope throw, what you are saying that escope throwing for a code like that when in es5 mode is the expected behavior, so not a bug… I think I get it

**Comment by nzakas** [comment]
Looks good. Can you squash your commits into one and just keep the original commit message? See: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by fczuardi** [comment]
squashed! :)

**Comment by nzakas** [comment]
Thanks for your patience, this looks good!
