### PR TITLE
Update: Fix && vs || short-circuiting false negatives (fixes #13634)

### LINKED ISSUE #13634: False negatives in 3 rules when right side of && expression is a literal
**Tell us about your environment**

* **ESLint Version:** 7.7.0
* **Node Version:** 14.9.0
* **npm Version:** 6.14.7

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    parserOptions: {
        ecmaVersion: 2020
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/* eslint constructor-super: "error",
   no-throw-literal: "error",
   prefer-promise-reject-errors: "error"
 */
let anything;

// If anything is a constructor, it'll be truthy, we'll evaluate the
// right side of the &&, and we'll extend 42.
class Subclass extends (anything && 42) {
    constructor() {
        super();
    }
}

// If anything is an Error instance, it'll be truthy, we'll evaluate
// the right side of the &&, and we'll throw 42.
throw anything && 42;

// If anything is an Error instance, it'll be truthy, we'll evaluate
// the right side of the &&, and we'll reject with 42.
Promise.reject(anything && 5);
```

[Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGNvbnN0cnVjdG9yLXN1cGVyOiBcImVycm9yXCIsXG4gICBuby10aHJvdy1saXRlcmFsOiBcImVycm9yXCIsXG4gICBwcmVmZXItcHJvbWlzZS1yZWplY3QtZXJyb3JzOiBcImVycm9yXCJcbiAqL1xubGV0IGFueXRoaW5nO1xuXG4vLyBJZiBhbnl0aGluZyBpcyBhIGNvbnN0cnVjdG9yLCBpdCdsbCBiZSB0cnV0aHksIHdlJ2xsIGV2YWx1YXRlIHRoZVxuLy8gcmlnaHQgc2lkZSBvZiB0aGUgJiYsIGFuZCB3ZSdsbCBleHRlbmQgNDIuXG5jbGFzcyBTdWJjbGFzcyBleHRlbmRzIChhbnl0aGluZyAmJiA0Mikge1xuICAgIGNvbnN0cnVjdG9yKCkge1xuICAgICAgICBzdXBlcigpO1xuICAgIH1cbn1cblxuLy8gSWYgYW55dGhpbmcgaXMgYW4gRXJyb3IgaW5zdGFuY2UsIGl0J2xsIGJlIHRydXRoeSwgd2UnbGwgZXZhbHVhdGVcbi8vIHRoZSByaWdodCBzaWRlIG9mIHRoZSAmJiwgYW5kIHdlJ2xsIHRocm93IDQyLlxudGhyb3cgYW55dGhpbmcgJiYgNDI7XG5cbi8vIElmIGFueXRoaW5nIGlzIGFuIEVycm9yIGluc3RhbmNlLCBpdCdsbCBiZSB0cnV0aHksIHdlJ2xsIGV2YWx1YXRlXG4vLyB0aGUgcmlnaHQgc2lkZSBvZiB0aGUgJiYsIGFuZCB3ZSdsbCByZWplY3Qgd2l0aCA0Mi5cblByb21pc2UucmVqZWN0KGFueXRoaW5nICYmIDUpOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**What did you expect to happen?**

We should report errors in each of the above cases. All three are looking for a specific type of truthy value from the expression. Because the expression uses `&&`, any possibly-valid value would evaluate to the right side of the expression, which would not be a valid value in these examples.

This was originally discovered in https://github.com/eslint/eslint/pull/13618#discussion_r479584827. Because it relates to existing behavior that existed prior to that pull request, we decided to split it into its own issue that can be fixed after the pull request is merged. This bug is a false negative in the 3 rules above, and fixing it would cause them to report more errors. Does anyone object to fixing this in a semver-minor change as allowed by our semver policy?

The fix would update both [`astUtils.couldBeError()`](https://github.com/eslint/eslint/blob/a32032430a0779a4e3b2d137d4d0682844084b82/lib/rules/utils/ast-utils.js#L1587-L1588) and [`constructor-super`'s `isPossibleConstructor()`](https://github.com/eslint/eslint/blob/a32032430a0779a4e3b2d137d4d0682844084b82/lib/rules/constructor-super.js#L65-L69) to only check the right side of `&&` `LogicalExpression`s.

**What actually happened? Please include the actual, raw output from ESLint.**

No errors are reported.

**Are you willing to submit a pull request to fix this bug?**

Yes, if @mdjermanovic doesn't get to it first.

### PR DESCRIPTION
**Pull request by btmills**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

---

*Bug report copied from #13634.*

**Tell us about your environment**

* **ESLint Version:** 7.7.0
* **Node Version:** 14.9.0
* **npm Version:** 6.14.7

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    parserOptions: {
        ecmaVersion: 2020
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/* eslint constructor-super: "error",
   no-throw-literal: "error",
   prefer-promise-reject-errors: "error"
 */
let anything;

// If anything is a constructor, it'll be truthy, we'll evaluate the
// right side of the &&, and we'll extend 42.
class Subclass extends (anything && 42) {
    constructor() {
        super();
    }
}

// If anything is an Error instance, it'll be truthy, we'll evaluate
// the right side of the &&, and we'll throw 42.
throw anything && 42;

// If anything is an Error instance, it'll be truthy, we'll evaluate
// the right side of the &&, and we'll reject with 42.
Promise.reject(anything && 5);
```

[Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGNvbnN0cnVjdG9yLXN1cGVyOiBcImVycm9yXCIsXG4gICBuby10aHJvdy1saXRlcmFsOiBcImVycm9yXCIsXG4gICBwcmVmZXItcHJvbWlzZS1yZWplY3QtZXJyb3JzOiBcImVycm9yXCJcbiAqL1xubGV0IGFueXRoaW5nO1xuXG4vLyBJZiBhbnl0aGluZyBpcyBhIGNvbnN0cnVjdG9yLCBpdCdsbCBiZSB0cnV0aHksIHdlJ2xsIGV2YWx1YXRlIHRoZVxuLy8gcmlnaHQgc2lkZSBvZiB0aGUgJiYsIGFuZCB3ZSdsbCBleHRlbmQgNDIuXG5jbGFzcyBTdWJjbGFzcyBleHRlbmRzIChhbnl0aGluZyAmJiA0Mikge1xuICAgIGNvbnN0cnVjdG9yKCkge1xuICAgICAgICBzdXBlcigpO1xuICAgIH1cbn1cblxuLy8gSWYgYW55dGhpbmcgaXMgYW4gRXJyb3IgaW5zdGFuY2UsIGl0J2xsIGJlIHRydXRoeSwgd2UnbGwgZXZhbHVhdGVcbi8vIHRoZSByaWdodCBzaWRlIG9mIHRoZSAmJiwgYW5kIHdlJ2xsIHRocm93IDQyLlxudGhyb3cgYW55dGhpbmcgJiYgNDI7XG5cbi8vIElmIGFueXRoaW5nIGlzIGFuIEVycm9yIGluc3RhbmNlLCBpdCdsbCBiZSB0cnV0aHksIHdlJ2xsIGV2YWx1YXRlXG4vLyB0aGUgcmlnaHQgc2lkZSBvZiB0aGUgJiYsIGFuZCB3ZSdsbCByZWplY3Qgd2l0aCA0Mi5cblByb21pc2UucmVqZWN0KGFueXRoaW5nICYmIDUpOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**What did you expect to happen?**

We should report errors in each of the above cases. All three are looking for a specific type of truthy value from the expression. Because the expression uses `&&`, any possibly-valid value would evaluate to the right side of the expression, which would not be a valid value in these examples.

This was originally discovered in https://github.com/eslint/eslint/pull/13618#discussion_r479584827. Because it relates to existing behavior that existed prior to that pull request, we decided to split it into its own issue that can be fixed after the pull request is merged. This bug is a false negative in the 3 rules above, and fixing it would cause them to report more errors. Does anyone object to fixing this in a semver-minor change as allowed by our semver policy?

The fix would update both [`astUtils.couldBeError()`](https://github.com/eslint/eslint/blob/a32032430a0779a4e3b2d137d4d0682844084b82/lib/rules/utils/ast-utils.js#L1587-L1588) and [`constructor-super`'s `isPossibleConstructor()`](https://github.com/eslint/eslint/blob/a32032430a0779a4e3b2d137d4d0682844084b82/lib/rules/constructor-super.js#L65-L69) to only check the right side of `&&` `LogicalExpression`s.

**What actually happened? Please include the actual, raw output from ESLint.**

No errors are reported.

---

#### What changes did you make? (Give an overview)

When `constructor-super`, `no-throw-literal`, and `prefer-promise-reject-errors` are looking for plausible constructor or error values, they fail to consider the short-circuiting behavior differences between the `&&` and `||` operators. This results in a false negative where these rules allow `foo && 42` when that expression cannot be a constructor or error. If the left side is falsy, the expression short-circuits with the falsy value. If the left side is truthy, the result of the expression is the right side value. All three rules already report the right side value in isolation but currently incorrectly allow it when on the right side of an `&&` expression.

When @mdjermanovic added support for logical assignment operators in #13618, [we decided](https://github.com/eslint/eslint/pull/13618#discussion_r479584827) to ship with the corrected behavior for `&&=` by only checking the right side of the expression, accepting that treatment of `&&=` would be inconsistent with existing treatment of `&&`. This PR then fixes the `&&` treatment in what we believe can be a semver-minor bug fix.

#### Is there anything you'd like reviewers to focus on?

Does everyone else agree with @mdjermanovic and me that this is can be a semver-minor bug fix?

A future improvement could detect statically falsy values on the left side of `&&` expressions and report those as well. Such a change could also update the `||` treatment to ignore plausibly-(constructor|error) values on the right side if the left side is statically truthy but not plausibly a constructor or error, so `42 || foo` should fail.

### CODE REVIEW

File: tests/lib/rules/utils/ast-utils.js [hunk 1]
```diff
@@ -1099,7 +1099,10 @@ describe("ast-utils", () => {
             "(1, 2, foo)": true,
             "1 && 2": false,
             "1 && foo": true,
-            "foo && 2": true,
+            "foo && 2": false,
+
+            // A future improvement could detect the left side as statically falsy, making this false.
+            "false && foo": true,
```
Comment (mdjermanovic) [inline tests/lib/rules/utils/ast-utils.js:1105]: :+1: 

We are already doing that in `no-constant-condition` for some basic cases [here](https://github.com/eslint/eslint/blob/b5e011c865e95d700d29cb9a4ba71c671d99e423/lib/rules/no-constant-condition.js#L66), and it's going to be improved by #13245.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

File: lib/rules/constructor-super.js [hunk 2]
```diff
@@ -79,6 +79,17 @@ function isPossibleConstructor(node) {
             return false;
 
         case "LogicalExpression":
+
+            /*
+             * If the && operator shortcuts, the left side was falsy and therefore not a constructor, and if
```
Comment (nzakas) [inline lib/rules/constructor-super.js:84]:
```suggestion
             * If the && operator short-circuits, the left side was falsy and therefore not a constructor, and if
```

File: lib/rules/constructor-super.js [hunk 3]
```diff
@@ -79,6 +79,17 @@ function isPossibleConstructor(node) {
...
+             * it doesn't shortcut, it takes the value from the right side, so the right side must always be a
```
Comment (nzakas) [inline lib/rules/constructor-super.js:85]:
```suggestion
             * it doesn't short-circuit, it takes the value from the right side, so the right side must always be a
```

File: lib/rules/utils/ast-utils.js [hunk 4]
```diff
@@ -1611,6 +1611,17 @@ module.exports = {
             }
 
             case "LogicalExpression":
+
+                /*
+                 * If the && operator shortcuts, the left side was falsy and therefore not an error, and if it
```
Comment (nzakas) [inline lib/rules/utils/ast-utils.js:1616]:
```suggestion
                 * If the && operator short-circuits, the left side was falsy and therefore not an error, and if it
```

File: lib/rules/utils/ast-utils.js [hunk 5]
```diff
@@ -1611,6 +1611,17 @@ module.exports = {
...
+                 * doesn't shortcut, it takes the value from the right side, so the right side must always be
```
Comment (nzakas) [inline lib/rules/utils/ast-utils.js:1617]:
```suggestion
                 * doesn't short-circuit, it takes the value from the right side, so the right side must always be
```

**Review by nzakas — APPROVED** [review]

**Comment by mdjermanovic** [comment]
> Does everyone else agree with @mdjermanovic and me that this is can be a semver-minor bug fix?

There were no concerns expressed, so marking as accepted and merging for a minor version.
