### PR TITLE
fix: fix regression of global mode report range in `strict` rule

### LINKED ISSUE #20451: Bug: In-line disabling of the strict rule requires the comment to be the first line of the file (regression in ESLint v10)
### Environment

Node version: v25.3.0
npm version: 11.7.0
Local ESLint version: 10.0.0-rc.0
Global ESLint version: N/A
Operating System: Mac 26.2

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```js
export default [
  {
    files: ["*.js"],
    languageOptions: {
      sourceType: "script",
    },
    rules: {
      strict: ["error", "global"],
    }
  }
]
```
</details>

```js
/* Copyright message, or comment explaning why strict is disabled. */
/* eslint-disable strict */

function foo() {
  console.log(foo);
}
```

### What did you expect to happen?

No errors

### What actually happened?

```
  1:1  error    Use the global form of 'use strict'                                        strict
  2:1  warning  Unused eslint-disable directive (no problems were reported from 'strict')
```

### Link to Minimal Reproducible Example

https://github.com/Standard8/eslint-strict-mode-comment-location

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

If the `/* eslint-disable strict */` line is on the very first line of the file, then it works. However, if it is not on the very first line then it fails, even if it is before any code.

This prevents situations like shown in the example, where we want to have a copyright message at the start of the file, or even a comment as to why strict mode is being disabled in the file.

This is a regression in the Eslint 10.0.0 series (I checked the alpha & beta and they failed also). Eslint 9.39.2 works fine.

### PR DESCRIPTION
**Pull request by ntnyq**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #20451

#### What changes did you make? (Give an overview)

This PR updates the strict rule global mode report behavior, to report the range from the first node start to the last node end as v9 does and adds test cases for it.

### CODE REVIEW

File: lib/rules/strict.js [hunk 1]
```diff
@@ -268,6 +268,7 @@ module.exports = {
 			}
 		}
 
+		/** @type {import('../types').Rule.RuleListener} */
 		const rule = {
```
[the remark this answers is not in the document]
Comment (ntnyq) [reply lib/rules/strict.js:272]: Currently the repo mixed use the single and double quotes in type annotation.

**Comment by mdjermanovic** [comment]
Not sure why some CI checks didn't run, going to close & reopen to try again.

File: tests/lib/rules/strict.js [hunk 2]
```diff
@@ -397,6 +401,20 @@ ruleTester.run("strict", rule, {
 				},
 			],
 		},
+		{
+			code: "/* license */\nfunction bar() {}\nfunction bar() {}",
```
Comment (mdjermanovic) [inline tests/lib/rules/strict.js]:
```suggestion
			code: "/* license */\nfunction bar() {}\nfunction bar() {}\n/* end */",
```

To also verify the behavior of loc.end.

Comment (ntnyq) [reply tests/lib/rules/strict.js]: Resolved. Thanks.

**Comment by lumirlumir** [comment]
Okay, I think I’ve found the reason the CI isn’t working. I’m going to close and reopen it to try again.

**Comment by lumirlumir** [comment]
Good, everything seems to be working correctly.

**Comment by mdjermanovic** [comment]
Great! I'll leave this open until the release (later today) if anyone would like to take another look.
