### PR TITLE
Fix: no-unused-vars updated location to last reference (fixes #13181)

### LINKED ISSUE #13181: [no-unused-vars]: reporter should report the last reference instead of declaration
**What rule do you want to change?**
`no-unused-vars`

**Does this change cause the rule to produce more or fewer warnings?**
same

**How will the change be implemented? (New option, new default behavior, etc.)?**
default

**Please provide some example code that this change will affect:**
Currently, the reporter reports the location in a declaration of a variable which is fine but not for all cases. 

`case 1`
```js
const unusedVar = 1; // reporting here is ok
```

`case2`
```js
let a = 1 // currently its reporting here,  reporting here is not ok as `a` has references though its being self referred 
a = a + 1;
a = a + 2;
a = a + 3; // it should report here
```

In this way, it makes easy to track the error if any.
Another advantage of reporting this way is many editors do provide shortcut keys to jump to the declaration of any variable/function but the opposite is not true for some. 

ref : https://github.com/eslint/eslint/issues/12871, https://github.com/eslint/eslint/issues/13172

**What does the rule currently do for this code?**
reports in the variable declaration

**What will the rule do after it's changed?**
reports in the last reference of the variable if the variable is being self-referred

**Are you willing to submit a pull request to implement this change?**
Yes

### PR DESCRIPTION
**Pull request by anikethsaha**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
fixes #13181
Updated the location for `no-unused-vars` to report at the last reference of a variable when not being used.

image
image

#### Is there anything you'd like reviewers to focus on?
Should this be `Update` instead of `Fix` ?

### CODE REVIEW

File: lib/rules/no-unused-vars.js [hunk 1]
```diff
@@ -618,13 +618,26 @@ module.exports = {
...
                     // Report the first declaration.
                     if (unusedVar.defs.length > 0) {
-                        context.report({
-                            node: unusedVar.identifiers[0],
-                            messageId: "unusedVar",
-                            data: unusedVar.references.some(ref => ref.isWrite())
-                                ? getAssignedMessageData(unusedVar)
-                                : getDefinedMessageData(unusedVar)
-                        });
+                        if (unusedVar.references.length > 0) {
```
Comment (nzakas) [inline lib/rules/no-unused-vars.js:621]: It looks like all of the arguments are the same except for node. Instead of duplicating all the other properties, can you maybe use a ternary expression ( foo ? bar : baz ) when assigning a value to “node”?
