### PR TITLE
Fix: func-call-spacing does not recognize all line terminators (fixes #7923)

### LINKED ISSUE #7923: func-call-spacing does not recognize all line terminators
**Tell us about your environment**

* **ESLint Version:** 3.13.1
* **Node Version:** 7.4.0
* **npm Version:** 4.0.5

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```
{ }
```

**What did you do? Please include the actual source code causing the issue.**

```js
/*eslint func-call-spacing: ["error", "always"]*/

fn
();
```

**What did you expect to happen?**

In the snippet above, when the line terminator character between `fn` and `()` is one of `"\r"`, `"\u2028"` or `"\u2029"`, an error should be reported.

**What actually happened? Please include the actual, raw output from ESLint.**

An error is only reported when the line terminator character between `fn` and `()` is `"\n"`.

### PR DESCRIPTION
**Pull request by fasttime**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (see #7923)

**What changes did you make? (Give an overview)**

Updated a regular expression in the `func-call-spacing` rule source to match the line terminator characters `"\r"`, `"\u2028"` and `"\u2029"` along with `"\n"`. This has the effect of disallowing those characters as separators when the option `"always"` is used without `"allowNewlines"`.

**Is there anything you'd like reviewers to focus on?**

Nothing that shouldn't be clear.

### CODE REVIEW

**Comment by fasttime** [comment]
@platinumazure Thanks for the review. If I understand, you are suggesting to extend the test cases for #7787 to other line terminators. Is this correct?

**Comment by platinumazure** [comment]
You got it!

**Comment by fasttime** [comment]
I've added some tests for the base case `"f\n();"` with all line terminator variants. If this is not sufficient, I was thinking to combine the more complex tests with different line terminators `"(0, foo).bar()\r(0, foo).bar()\u2028..."`.

File: lib/rules/func-call-spacing.js [hunk 1]
```diff
@@ -86,9 +86,9 @@ module.exports = {
                 return;
             }
 
-            const hasWhitespace = sourceCode.isSpaceBetweenTokens(prevToken, parenToken);
-            const hasNewline = hasWhitespace &&
-                /\n/.test(text.slice(prevToken.range[1], parenToken.range[0]).replace(/\/\*.*?\*\//g, ""));
+            const textBetweenTokens = text.slice(prevToken.range[1], parenToken.range[0]).replace(/\/\*.*?\*\//g, "");
+            const hasWhitespace = /\s/.test(textBetweenTokens);
+            const hasNewline = hasWhitespace && /[\n\r\u2028\u2029]/.test(textBetweenTokens);
```
Comment (gyandeeps) [inline lib/rules/func-call-spacing.js]: I am not expert in regex but I think we should use the regex present in [linebreak-style](https://github.com/eslint/eslint/blob/master/lib/rules/linebreak-style.js#L63) rule. 
Even better to store this pattern somewhere central and make both the rule consume that.

Comment (fasttime) [inline lib/rules/func-call-spacing.js]: Thanks! Unfortunately, the regexp in `linebreak-style` cannot be centralized in a way that leaves it safe to reuse in recursion: it has a `g` flag, which means, it has a `lastIndex` property that changes every time the `exec` method is called on it to keep track of the last matching position.

We could centralize the pattern as a string and then create the regexp with the `RegExp` constructor. I'd note anyway that those regexes are for slightly different purposes. The one in `func-call-spacing` is meant to match a *LineTerminator*, while the regexp in `line-break-style` finds *LineTerminatorSequences*. Both are defined in http://www.ecma-international.org/ecma-262/6.0/#sec-line-terminators.

Comment (btmills) [inline lib/rules/func-call-spacing.js]: > I think it would be a very good idea to centralize part of the code in question to make it reusable, although it should be probably done in a different issue.

:+1: Agreed. Will you create an issue to keep track of that?

**Comment by fasttime** [comment]
@platinumazure I also thought of that. Both "never" and "always" disallow newlines, and I'm not sure why autofixing newlines should only happen with "always".

**Comment by fasttime** [comment]
@btmills I added some more tests. Now there should be valid or invalid tests for every line terminator sequence with every option. Give me one day and I'll open an issue about the repeated regexp code. Thanks for the feedback.

File: lib/rules/func-call-spacing.js (hunk 1 above)
Comment (fasttime) [inline lib/rules/func-call-spacing.js]: This can be now discussed in #7949.
