### PR TITLE
Fix: Avoid fixing objects containing comments (fixes #8484)

### LINKED ISSUE #8484: object-curly-newline --fix  erroneously removes comment
ESLint Version: v3.19.0
Node Version: v7.9.0

```js
module.exports = {
  'env': {
    'browser': true,
    'es6': true
  },
  'extends': 'eslint:recommended',
  'rules': {
    'object-curly-newline': ['error', {multiline: true}],
    'no-unused-vars': 'off',
  }
```

**Before**
```js
var a = {
  // Nothing here yet, but comment should not be removed.
};
```

**After invoking ESLint with the --fix flag the file is modified as follows**
```js
var a = {};
```

**What did you expect to happen?**
The comment should have been preserved.

**What actually happened?**
The comment was removed.

### PR DESCRIPTION
**Pull request by schempy**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Avoid fixing objects containing comments proposed by @not-an-aardvark in PR #8487

### CODE REVIEW

File: tests/lib/rules/object-curly-newline.js [hunk 1]
```diff
@@ -586,6 +586,38 @@ ruleTester.run("object-curly-newline", rule, {
         },
         {
             code: [
+                "var a = {",
+                " /* comment */ ",
+                "};"
+            ].join("\n"),
+            output: [
+                "var a = {",
```
Comment (not-an-aardvark) [inline tests/lib/rules/object-curly-newline.js]: Nitpick: Can you use `output: null` for these test cases to indicate that no output is produced, rather than making `output` the same as `code`?

File: lib/rules/object-curly-newline.js [hunk 2]
```diff
@@ -144,6 +144,9 @@ module.exports = {
                 )
             );
 
+            const allTokens = sourceCode.getTokens(node, { includeComments: true });
+            const hasComments = allTokens.some(token => astUtils.isCommentToken(token));
```
Comment (not-an-aardvark) [inline lib/rules/object-curly-newline.js]: Nitpick: I think these lines could be replaced with

```js
const hasComments = !!sourceCode.getFirstToken(node, astUtils.isCommentToken);
```

Comment (schempy) [inline lib/rules/object-curly-newline.js]: That change did not work. I'll be happy to make other changes if you'd like. Also, I updated the test files as suggested.

Comment (not-an-aardvark) [inline lib/rules/object-curly-newline.js]: Oops, sorry about that. Does this work?

```js
const hasComments = sourceCode.commentsExistBetween(
    sourceCode.getFirstToken(node),
    sourceCode.getLastToken(node)
);
```

The reason I bring this up is because I'm a bit concerned about the performance impact of iterating through every token of every object literal in a file. (In most cases it should probably be fine, but one can imagine a worst-case file that has many very large object literals.) The `hasComments` variable is currently declared outside all of the `if` statements here, so the comments will be enumerated in all files, not just files .

`sourceCode.commentsExistBetween` uses binary search to find comments (since it has access to all the comment locations beforehand).

**Comment by not-an-aardvark** [comment]
By the way, is it intentional that no fix is performed even when the comment is between properties? For example, no fix will be performed for this object:

```js
/* eslint object-curly-newline: [error, always] */

({ foo: 1,
  bar: 2,
  // comment
  baz: 3
});
```

But it seems like such a fix would clearly be safe. Maybe it would be better to explicitly check between the `{` and the first token in the object, rather than checking for comments anywhere in the object.

**Comment by schempy** [comment]
@not-an-aardvark I made updates to check between the  ```{``` and the first token in the object for comments. Updated tests as well.  Do you think I should update the commit message since this is not avoiding fixing objects containing comments?

File: lib/rules/object-curly-newline.js [hunk 3]
```diff
@@ -172,6 +177,10 @@ module.exports = {
                         node,
                         loc: closeBrace.loc.start,
                         fix(fixer) {
+                            if (hasComments) {
```
Comment (not-an-aardvark) [inline lib/rules/object-curly-newline.js]: For this check, I think it would matter whether the *last* token of the object is a comment, not the first.

File: lib/rules/object-curly-newline.js [hunk 4]
```diff
@@ -206,6 +219,10 @@ module.exports = {
...
```
Comment (not-an-aardvark) [inline lib/rules/object-curly-newline.js]: For this check, I think it would matter whether the *last* token of the object is a comment, not the first.

**Comment by not-an-aardvark** [comment]
> Do you think I should update the commit message since this is not avoiding fixing objects containing comments?

Sure, feel free. It might be good to mention `object-curly-spacing` in the commit message as well.

**Comment by schempy** [comment]
Thanks for the feedback! Code updates and commit message have been made.
