### PR TITLE
fix: ignore spacing before `]` and `}` in comma-spacing

### LINKED ISSUE #16100: Bug: comma-spacing is conflicting with array-bracket-spacing
### Environment

Node version: v16.15.1
npm version: v8.11.0
Local ESLint version: v8.18.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 21.4.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

You can see an ESLint demo [here](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IHF1b3RlczogW1wiZXJyb3JcIiwgXCJkb3VibGVcIl0gKi9cbmxldCBhID0gWzEsIDIsIDMsIDQsIF07XG5sZXQgYiA9IFsxLCAyLCAzLCA0LF07Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJhcnJheS1icmFja2V0LXNwYWNpbmciOlsid2FybiIsIm5ldmVyIl0sImNvbW1hLXNwYWNpbmciOlsid2FybiIseyJiZWZvcmUiOmZhbHNlLCJhZnRlciI6dHJ1ZX1dfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==)

<details>
<summary>Configuration</summary>

```json
{
    "env": {
        "browser": true,
        "es2020": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
    "plugins": ["@typescript-eslint"],
    "rules": {
        "comma-spacing": ["warn", { "before": false, "after": true }],
        "array-bracket-spacing": ["warn", "never"],
        "comma-dangle": "off",
    }
}

```
</details>

```js
tsts = [1, 2, 3, 4,];  // A space is required after ','. eslint(comma-spacing)
tsts = [1, 2, 3, 4, ];  // There should be no space before ']'. eslint(array-bracket-spacing)
```

### What did you expect to happen?

I was expecting the `array-bracket-spacing` rule to take over the `comma-spacing` rule and allow the first line as linted

### What actually happened?

- `array-bracket-spacing` requires there to be no space before the close bracket
- `comma-spacing` requires there to be a space after the final comma

Therefore, we have a conflict.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This issue is related to this [issue (#9760)](https://github.com/eslint/eslint/issues/9760) which was closed due to lack of interest.

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #16100

Updates the `comma-spacing` rule to ignore spacing before `]` and spacing before `}` in order to avoid conflicts with `array-bracket-spacing` and `object-curly-spacing` rules.

For example, the current version of `comma-spacing` reports an error on each of the following lines, but fixing them triggers errors from `array-bracket-spacing` and `object-curly-spacing` rules:

```js
/* eslint comma-spacing: "error" */
/* eslint array-bracket-spacing: "error" */
/* eslint object-curly-spacing: "error" */

[a,]; // comma-spacing reports missing space after `,` but fixing it triggers array-bracket-spacing

[a,] = foo; // comma-spacing reports missing space after `,` but fixing it triggers array-bracket-spacing

obj = {a,}; // comma-spacing reports missing space after `,` but fixing it triggers object-curly-spacing

var {a,} = obj; // comma-spacing reports missing space after `,` but fixing it triggers object-curly-spacing

import {b,} from "mod"; // comma-spacing reports missing space after `,` but fixing it triggers object-curly-spacing
```

[Playground link](https://eslint.org/play#eyJ0ZXh0IjoiLyogZXNsaW50IGNvbW1hLXNwYWNpbmc6IFwiZXJyb3JcIiAqL1xuLyogZXNsaW50IGFycmF5LWJyYWNrZXQtc3BhY2luZzogXCJlcnJvclwiICovXG4vKiBlc2xpbnQgb2JqZWN0LWN1cmx5LXNwYWNpbmc6IFwiZXJyb3JcIiAqL1xuXG5bYSxdOyAvLyBjb21tYS1zcGFjaW5nIHJlcG9ydHMgbWlzc2luZyBzcGFjZSBhZnRlciBgLGAgYnV0IGZpeGluZyBpdCB0cmlnZ2VycyBhcnJheS1icmFja2V0LXNwYWNpbmdcblxuW2EsXSA9IGZvbzsgLy8gY29tbWEtc3BhY2luZyByZXBvcnRzIG1pc3Npbmcgc3BhY2UgYWZ0ZXIgYCxgIGJ1dCBmaXhpbmcgaXQgdHJpZ2dlcnMgYXJyYXktYnJhY2tldC1zcGFjaW5nXG5cbm9iaiA9IHthLH07IC8vIGNvbW1hLXNwYWNpbmcgcmVwb3J0cyBtaXNzaW5nIHNwYWNlIGFmdGVyIGAsYCBidXQgZml4aW5nIGl0IHRyaWdnZXJzIG9iamVjdC1jdXJseS1zcGFjaW5nXG5cbnZhciB7YSx9ID0gb2JqOyAvLyBjb21tYS1zcGFjaW5nIHJlcG9ydHMgbWlzc2luZyBzcGFjZSBhZnRlciBgLGAgYnV0IGZpeGluZyBpdCB0cmlnZ2VycyBvYmplY3QtY3VybHktc3BhY2luZ1xuXG5pbXBvcnQge2IsfSBmcm9tIFwibW9kXCI7IC8vIGNvbW1hLXNwYWNpbmcgcmVwb3J0cyBtaXNzaW5nIHNwYWNlIGFmdGVyIGAsYCBidXQgZml4aW5nIGl0IHRyaWdnZXJzIG9iamVjdC1jdXJseS1zcGFjaW5nIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

Note that this rule already ignores spacing after `[` (https://github.com/eslint/eslint/issues/3392) and spacing before `)` (https://github.com/eslint/eslint/issues/11295).

#### What changes did you make? (Give an overview)

* Merged `validateCommaItemSpacing` into the loop in `"Program:exit"()` because the logic of what to check and what to ignore was unnecessarily scattered.
* Removed `JSXText` check. We are checking if it's a comma punctuator token just a line before, so it can't be JSXText.
* Added new checks for `]` and `}`.
* Updated the docs accordingly.

#### Is there anything you'd like reviewers to focus on?

I also wanted to replace `addNullElementsToIgnoreList` and all related code with a simple `[` token check, but it turned out that the existing logic has possibly unintentional side effects of ignoring spacing between a comment and ending comma of a hole/elision.

### CODE REVIEW

File: tests/lib/rules/comma-spacing.js [hunk 1]
```diff
@@ -198,17 +240,6 @@ ruleTester.run("comma-spacing", rule, {
...
-            code: "var arr = [1 , ];",
-            output: "var arr = [1 ,];",
-            options: [{ before: true, after: false }],
-            errors: [
-                {
-                    message: "There should be no space after ','.",
-                    type: "Punctuator"
-                }
-            ]
-        },
```
Comment (mdjermanovic) [inline tests/lib/rules/comma-spacing.js:211]: This was conflicting with `array-bracket-spacing` option `"always"` on the right side of `,`.

[Playground link](https://eslint.org/play#eyJ0ZXh0IjoiLyogZXNsaW50IGNvbW1hLXNwYWNpbmc6IFtcImVycm9yXCIsIHsgYmVmb3JlOiB0cnVlLCBhZnRlcjogZmFsc2UgfV0gKi9cbi8qIGVzbGludCBhcnJheS1icmFja2V0LXNwYWNpbmc6IFtcImVycm9yXCIsIFwiYWx3YXlzXCJdICovXG5cbnZhciBhcnIgPSBbMSAsIF07XG5cbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**Review by nzakas — APPROVED** [review]
LGTM.
