### PR TITLE
Fix: invalid syntax from prefer-arrow-callback autofixer (fixes #8541)

### LINKED ISSUE #8541: Eslint --fix is breaking code with ".bind(this, variable)".
**Tell us about your environment**
Windows 10
* **ESLint Version:**  v3.19.0
* **Node Version:** v6.10.2
* **npm Version:** 4.5.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
```js
module.exports = {
  "parser": "babel-eslint",
  "extends": [
    "airbnb"
  ],
  "plugins": [
    "babel",
    "react",
    "promise"
  ],
  "env": {
    "browser": true,
    "jest": true
  },
  "rules": {
    "arrow-parens": [1, "always"],
    "arrow-body-style": [1, "always"],
    "key-spacing": 0,
    "no-mixed-operators": 0,
    "no-param-reassign": 0,

    // Allow for-of loops. 
    "no-restricted-syntax": [
      'error',
      {
        selector: 'LabeledStatement',
        message: 'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.',
      },
      {
        selector: 'WithStatement',
        message: '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.',
      },
    ],

    // This rule requires that all class methods use this. 
    // Disabling this allows making class methods that do not reference "this", which is helpful for private helper functions. 
    "class-methods-use-this": 0,

    // This config disallows if(true) but allows while(true)
    "no-constant-condition": ["error", { "checkLoops": false }],
    "no-cond-assign": ["error", "except-parens"],
    "no-plusplus": [0, {
      "allowForLoopAfterthoughts": true
    }],

    // Prevents using variables before they are defined. 
    "no-use-before-define": 1,
    "jsx-quotes": [2, "prefer-single"],
    "max-len": [2, 300, 2],
    "object-shorthand": ["error", "never"],
    "object-curly-spacing": [2, "always"],
    "react/forbid-prop-types": 0,
    "react/no-danger": 1,
    "no-continue": 0,

    // This rule always triggers on Windows...
    "import/no-unresolved": Number(process.env.OS !== 'Windows_NT') * 2,
    "spaced-comment": 0,
    "react/prefer-stateless-function": [1],
    "react/jsx-filename-extension": [1, {
      "extensions": [".js", ".jsx"]
    }],
    "react/jsx-curly-spacing": [2, "always", {
      "spacing": {
        "objectLiterals": "never"
      }
    }],
    "no-console": "off"
  }
}

```

**What did you do? Please include the actual source code causing the issue.**

I was converting some ES5 code to ES6 and `eslint --fix` broke some code. Here is a small example:

```js
let queue = require('d3-queue').queue
const attrName = 'hi';

let q = queue()

q.defer(function(attrName, callback) {

  // No mention of "this" anywhere in the body of the function

}.bind(this, attrName));

```

**What did you expect to happen?**
I expected the code to stay as valid Javascript. Here is one valid transformation:
```js
const queue = require('d3-queue').queue;
const attrName = 'hi';

const q = queue();

q.defer(((attrName, callback) => {

  // No mention of "this" anywhere in the body of the function

}).bind(this, attrName)); // This line is now valid because of the added parens. 

```

**What actually happened? Please include the actual, raw output from ESLint.**

```js
const queue = require('d3-queue').queue;
const attrName = 'hi';

const q = queue();

q.defer((attrName, callback) => {

  // No mention of "this" anywhere in the body of the function

}.bind(this, attrName)); // This line is now invalid because the function has been transformed into an arrow function. This now gives an Error: 10,2: Parsing error: Unexpected token, expected ,
```

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/8541)

**What changes did you make? (Give an overview)**

Previously, the `prefer-arrow-callback` autofixer would simply replace a function expression with an arrow function. However, arrow functions have a different precedence than regular functions, so this was sometimes creating invalid syntax. This commit updates the fixer to parenthesize the arrow functions if necessary to avoid a syntax error.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: lib/rules/prefer-arrow-callback.js [hunk 1]
```diff
@@ -277,15 +277,23 @@ module.exports = {
...
+                             * Otherwise, just replace the arrow function itself.
+                             */
+                            const replacedNode = callbackInfo.isLexicalThis ? node.parent.parent : node;
+
+                            /*
+                             * If the replaced node is part of a BinaryExpression, LogicalExpression, or MemberExpression, then
+                             * the arrow function needs to be parenthesized, because `foo || () => {}` is invalid syntax even
+                             * though `foo || function() {}` is valid.
+                             */
+                            const needsParens = replacedNode.parent.type !== "CallExpression" && replacedNode.parent.type !== "ConditionalExpression";
```
Comment (platinumazure) [inline lib/rules/prefer-arrow-callback.js]: Can we use [`astUtils.getPrecedence()`](https://github.com/eslint/eslint/blob/master/lib/ast-utils.js#L739) for consistency and future-proofing?

Comment (not-an-aardvark) [inline lib/rules/prefer-arrow-callback.js]: I don't think tha would work very well. The `needsParens` variable isn't based on precedence (in fact, arrow functions have lower precedence than all other node types here). The check is specific to the definition of what the rule considers a "callback":

```js
// all of these are callbacks

foo(function() {}) // parent is CallExpression
foo(function() {}.bind(this)) // parent is MemberExpression
foo(bar || function() {}) // parent is LogicalExpression
foo(bar ? function() {} : baz) // parent is ConditionalExpression
```

So when the parent is a CallExpression, it's not that the arrow function has higher precedence -- it's that due to the other logic in the rule, the function must already be surrounded by parentheses. Similarly, when the parent is a ConditionalExpression, the function is always in a location where parsing is unambiguous.
