### PR TITLE
fix: `use-isnan` doesn't report on `SequenceExpression`s

### LINKED ISSUE #18058: Bug: use-isnan doesn't report on `SequenceExpression`s
### Environment

Node version: v20.10.0
npm version: v10.2.3
Local ESLint version: v9.0.0-alpha.2 (Currently used)
Global ESLint version: Not found
Operating System: darwin 22.6.0

### What parser are you using?

Default (Espree)

### What did you do?

```js
/*eslint use-isnan: ["error", {"enforceForIndexOf": true}]*/

[1, NaN, 2].indexOf((1, NaN))
```

### What did you expect to happen?

The rule should report on this line

### What actually happened?

There is no report

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgdXNlLWlzbmFuOiBbXCJlcnJvclwiLCB7XCJlbmZvcmNlRm9ySW5kZXhPZlwiOiB0cnVlfV0qL1xuXG5bMSwgTmFOLCAyXS5pbmRleE9mKCgxLCBOYU4pKSIsIm9wdGlvbnMiOnsiZW52Ijp7fSwicnVsZXMiOnt9LCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e30sImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6Im1vZHVsZSJ9fX0=

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by StyleShit**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

The `use-isnan` rule didn't report `SequenceExpression`s, so I've added a short condition to check for that, plus some tests

Closes #18058

### CODE REVIEW

**Comment by nzakas** [comment]
@StyleShit can you please update your description and fill out the [pull request template](https://github.com/eslint/eslint/blob/main/.github/PULL_REQUEST_TEMPLATE.md)? This is required in every PR. Thanks!

**Comment by StyleShit** [comment]
@nzakas Sure, sorry for that (again... 😅)

I'm just used to opening a PR from my local machine without even opening Github, so it doesn't add the template.
Will make sure to use it next time 😄

**Comment by nzakas** [comment]
That's what I figured, no worries. :)

**Review by nzakas — CHANGES_REQUESTED** [review]
Code LGTM. Can you also add some examples to the docs?

**Comment by StyleShit** [comment]
That's a good idea!
Not sure what/where to put it though, added [this](https://github.com/eslint/eslint/pull/18059/commits/c5284953bb660f50c0697ba11ad3db70aadbec4c) for now, but we can probably do better, WDYT?

File: lib/rules/use-isnan.js [hunk 1]
```diff
@@ -21,9 +21,17 @@ const astUtils = require("./utils/ast-utils");
  * @returns {boolean} `true` if the node is 'NaN' identifier.
  */
 function isNaNIdentifier(node) {
```
Comment (mdjermanovic) [inline lib/rules/use-isnan.js:23]: This function is used in all checks, including those where the rule already provides suggestions, so the question now is should the rule provide suggestions when `NaN` is in a sequence expression, or should we also update the code that creates suggestions to skip those cases?

For example:

```js
/* eslint use-isnan: "error" */

x === (foo(), NaN);
```

After the suggestion is applied, the `foo()` call is lost:

```js
/* eslint use-isnan: "error" */

Number.isNaN(x);

```

Comment (StyleShit) [reply lib/rules/use-isnan.js:23]: Ooh, yeah yeah you're right, totally forgot about it.
Yes, I think we can skip those cases, which is what I've done [here](
https://github.com/eslint/eslint/pull/18063/files#diff-f85ca2d533ed63955015070ff4e1b8d0e61e8a3b9efb316ac556ec699858f0d6R178-R182) already.

I don't think there is a safe way to keep those side effects, WDYT?

Comment (mdjermanovic) [reply lib/rules/use-isnan.js:23]: > I don't think there is a safe way to keep those side effects, WDYT?

I agree, those cases should be fixed manually.

File: tests/lib/rules/use-isnan.js [hunk 2]
```diff
@@ -183,6 +194,10 @@ ruleTester.run("use-isnan", rule, {
         "foo.lastIndexOf(NaN)",
         "foo.indexOf(Number.NaN)",
         "foo.lastIndexOf(Number.NaN)",
+        "foo.indexOf((NaN, 1))",
+        "foo.lastIndexOf((NaN, 1))",
+        "foo.indexOf((Number.NaN, 1))",
+        "foo.lastIndexOf((Number.NaN, 1))",
```
Comment (mdjermanovic) [inline tests/lib/rules/use-isnan.js:200]: These tests should probably have `options: [{ enforceForIndexOf: true }]`? Otherwise, they would be valid regardless of the position of NaN, because the rule doesn't check indexOf by default.

Comment (StyleShit) [reply tests/lib/rules/use-isnan.js]: you're totally right, I somehow missed that. thanks!

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Leaving this open for @nzakas to verify.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!
