### PR TITLE
Fix: `space-before-keywords` fails to handle class keyword & object literal shorthand method (fixes #3756)

### LINKED ISSUE #3756: space-before-keywords misrecognizes shorthand methods as keywords
The `space-before-keywords` rule (in ESLint 1.4.1) misrecognizes shorthand methods as keywords:
```js
let x = {a() {}};
```
It claims `a` is a keyword and should be preceded by a space.

I want to not write spaces inside the parens in one-line blocks or arrays:
```js
const a = [1, 2, 3];
const o = {a: 2, b: 3};
```
but I still want spaces after & before keywords:
```js
if (x) {
  /* ... */
} else {
  /* ... */
}
```

### PR DESCRIPTION
**Pull request by mmrko**
Fixes #3756 (`class` keyword & object literal shorthand method).

### CODE REVIEW

File: lib/rules/space-before-keywords.js [hunk 1]
```diff
@@ -177,15 +177,15 @@ module.exports = function(context) {
         "FunctionExpression": function(node) {
 
             var left = context.getTokenBefore(node);
-            var right = null;
 
+            // Check to see if the function expression is
+            // an ES2015 object literal shorthand method
```
Comment (nzakas) [inline lib/rules/space-before-keywords.js]: Better to do if node.parent is Property and Node.parent. method is true

Comment (mmrko) [inline lib/rules/space-before-keywords.js]: Oh, true. Thanks :) fixed! 

https://github.com/mmrko/eslint/blob/cc9c230108f932d42aaf3a97eaf6e1644a6cd5fd/lib/rules/space-before-keywords.js#L181-L189

**Comment by nzakas** [comment]
LGTM
