### PR TITLE
fix: check cache file existence before deletion

### LINKED ISSUE #19647: Bug: ESLint crashes with ` --permission` when it tries to delete cache
### Environment

Node version: v22.13.1
npm version: 11.2.0
Local ESLint version: 9.25.1
Global ESLint version: no
Operating System: Ubuntu 22.04.5 LTS

### What parser are you using?

Default (Espree)

### What did you do?

- `package.json`

  ```json
  {
    "name": "testcase",
    "version": "0.0.0",
    "dependencies": {
      "eslint": "9.25.1"
    }
  }
  ```

- `index.js`

  ```javascript
  console.log("foo");
  ```

- `lint.js`

  ```javascript
  import { ESLint } from "eslint";

  const eslint = new ESLint({ overrideConfigFile: true });
  const results = await eslint.lintFiles(["index.js"]);
  ```

1. `npm install`
2. `node --permission --allow-fs-read '*' lint.js`

### What did you expect to happen?

ESLint doesn't crash.

### What actually happened?

```
node:internal/fs/promises:1064
  return await PromisePrototypeThen(
               ^

TypeError: Method Promise.prototype.then called on incompatible receiver undefined
    at then (<anonymous>)
    at Object.unlink (node:internal/fs/promises:1064:16)
    at ESLint.lintFiles (/home/regseb/testcase/node_modules/eslint/lib/eslint/eslint.js:706:14)
    at file:///home/regseb/testcase/lint.js:4:30
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v22.13.1
```

### Link to Minimal Reproducible Example

See _What did you do?_

~~[https://eslint.org/play/#eyJ0ZXh0Ij...I6e319fX19](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc29sZS5sb2coXCJmb29cIik7Iiwib3B0aW9ucyI6eyJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6WyJlcnJvciJdLCJmb3ItZGlyZWN0aW9uIjpbImVycm9yIl0sImdldHRlci1yZXR1cm4iOlsiZXJyb3IiXSwibm8tYXN5bmMtcHJvbWlzZS1leGVjdXRvciI6WyJlcnJvciJdLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6WyJlcnJvciJdLCJuby1jbGFzcy1hc3NpZ24iOlsiZXJyb3IiXSwibm8tY29tcGFyZS1uZWctemVybyI6WyJlcnJvciJdLCJuby1jb25kLWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb25zdC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tY29uc3RhbnQtY29uZGl0aW9uIjpbImVycm9yIl0sIm5vLWNvbnRyb2wtcmVnZXgiOlsiZXJyb3IiXSwibm8tZGVidWdnZXIiOlsiZXJyb3IiXSwibm8tZGVsZXRlLXZhciI6WyJlcnJvciJdLCJuby1kdXBlLWFyZ3MiOlsiZXJyb3IiXSwibm8tZHVwZS1jbGFzcy1tZW1iZXJzIjpbImVycm9yIl0sIm5vLWR1cGUtZWxzZS1pZiI6WyJlcnJvciJdLCJuby1kdXBlLWtleXMiOlsiZXJyb3IiXSwibm8tZHVwbGljYXRlLWNhc2UiOlsiZXJyb3IiXSwibm8tZW1wdHkiOlsiZXJyb3IiXSwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjpbImVycm9yIl0sIm5vLWVtcHR5LXBhdHRlcm4iOlsiZXJyb3IiXSwibm8tZXgtYXNzaWduIjpbImVycm9yIl0sIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6WyJlcnJvciJdLCJuby1leHRyYS1zZW1pIjpbImVycm9yIl0sIm5vLWZhbGx0aHJvdWdoIjpbImVycm9yIl0sIm5vLWZ1bmMtYXNzaWduIjpbImVycm9yIl0sIm5vLWdsb2JhbC1hc3NpZ24iOlsiZXJyb3IiXSwibm8taW1wb3J0LWFzc2lnbiI6WyJlcnJvciJdLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOlsiZXJyb3IiXSwibm8taW52YWxpZC1yZWdleHAiOlsiZXJyb3IiXSwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOlsiZXJyb3IiXSwibm8tbG9zcy1vZi1wcmVjaXNpb24iOlsiZXJyb3IiXSwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOlsiZXJyb3IiXSwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjpbImVycm9yIl0sIm5vLW5ldy1zeW1ib2wiOlsiZXJyb3IiXSwibm8tbm9ub2N0YWwtZGVjaW1hbC1lc2NhcGUiOlsiZXJyb3IiXSwibm8tb2JqLWNhbGxzIjpbImVycm9yIl0sIm5vLW9jdGFsIjpbImVycm9yIl0sIm5vLXByb3RvdHlwZS1idWlsdGlucyI6WyJlcnJvciJdLCJuby1yZWRlY2xhcmUiOlsiZXJyb3IiXSwibm8tcmVnZXgtc3BhY2VzIjpbImVycm9yIl0sIm5vLXNlbGYtYXNzaWduIjpbImVycm9yIl0sIm5vLXNldHRlci1yZXR1cm4iOlsiZXJyb3IiXSwibm8tc2hhZG93LXJlc3RyaWN0ZWQtbmFtZXMiOlsiZXJyb3IiXSwibm8tc3BhcnNlLWFycmF5cyI6WyJlcnJvciJdLCJuby10aGlzLWJlZm9yZS1zdXBlciI6WyJlcnJvciJdLCJuby11bmRlZiI6WyJlcnJvciJdLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6WyJlcnJvciJdLCJuby11bnJlYWNoYWJsZSI6WyJlcnJvciJdLCJuby11bnNhZmUtZmluYWxseSI6WyJlcnJvciJdLCJuby11bnNhZmUtbmVnYXRpb24iOlsiZXJyb3IiXSwibm8tdW5zYWZlLW9wdGlvbmFsLWNoYWluaW5nIjpbImVycm9yIl0sIm5vLXVudXNlZC1sYWJlbHMiOlsiZXJyb3IiXSwibm8tdW51c2VkLXZhcnMiOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1iYWNrcmVmZXJlbmNlIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtY2F0Y2giOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1lc2NhcGUiOlsiZXJyb3IiXSwibm8td2l0aCI6WyJlcnJvciJdLCJyZXF1aXJlLXlpZWxkIjpbImVycm9yIl0sInVzZS1pc25hbiI6WyJlcnJvciJdLCJ2YWxpZC10eXBlb2YiOlsiZXJyb3IiXX0sImxhbmd1YWdlT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19)~~

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

https://github.com/eslint/eslint/blob/3ed4b3652d9fe3dfa4017d22a6ddbd15e3c6cd7a/lib/eslint/eslint.js#L701-L718

I try to run linters with read-only [permissions](https://nodejs.org/docs/latest/api/permissions.html), but ESLint crashes. ESLint tries to delete the cache (which doesn't exist), but it doesn't have write access: so Node doesn't give it permission.

I think ESLint should delete the cache only if it exists. Or [check for permission](https://nodejs.org/docs/latest/api/permissions.html#permissionhasscope-reference) (need Node v20+): `process.permission.has("fs.write", cacheFilePath)`. Adding a condition to the catch seems difficult, as it's hard to identify this error. It's an instance of `TypeError` and has no `code`.

### PR DESCRIPTION
**Pull request by sethamus**
#### Prerequisites checklist

-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

This PR modifies the cache file deletion logic to check if the cache file exists before attempting to delete it.

Closes #19647

### CODE REVIEW

**Comment by mdjermanovic** [comment]
> CI is failing because of this [PR](https://github.com/webpack/schema-utils/pull/197)

It's passing now, seems like it has been fixed by another PR.

File: lib/eslint/eslint.js [hunk 1]
```diff
@@ -703,7 +703,9 @@ class ESLint {
 			debug(`Deleting cache file at ${cacheFilePath}`);
 
 			try {
-				await fs.unlink(cacheFilePath);
+				if (existsSync(cacheFilePath)) {
+					await fs.unlink(cacheFilePath);
+				}
 			} catch (error) {
```
Comment (fasttime) [inline lib/eslint/eslint.js:709]: I'm not sure if the try-catch is still necessary after this change. It looks like the situations the catch block was intended to address—when the cache file was missing on a writable file system or when it was missing on a read-only file system—are now both handled by the `existsSync` check.

Comment (mdjermanovic) [reply lib/eslint/eslint.js:709]: The first version of this code (in `cli-engine.js`) was actually a simple `if (!options.cache && fs.existsSync(cacheFile)) { fs.unlinkSync(cacheFile); }` without try-catch, but has been changed to the try-catch version in https://github.com/eslint/eslint/pull/11546, I believe for the reasons explained in https://github.com/eslint/eslint/pull/11946#discussion_r300627151 in a later PR (the original commit is gone, but it seems the comment is under code that was intending to remove try-catch). My understanding of the reasoning is that if it happens that the cache file disappears between two fs commands, this should not throw an error.

File: tests/lib/eslint/eslint.js [hunk 2]
```diff
@@ -12541,7 +12541,7 @@ describe("ESLint", () => {
 			await eslint.lintFiles([file]);
 
 			assert(
-				fsp.unlink.calledWithExactly(cacheFilePath),
+				fsp.unlink.notCalled,
```
[the remark this answers is not in the document]
Comment (mdjermanovic) [reply tests/lib/eslint/eslint.js]: Yes, it generally should throw an error, but when we set `unlink` to throw `EROFS`, we're simulating the case where the cache file has been removed in the meantime (assuming we want to keep supporting that scenario, as being discussed in https://github.com/eslint/eslint/pull/19648#discussion_r2055461691), in which case it shouldn't throw.

[the remark this answers is not in the document]
Comment (mdjermanovic) [reply tests/lib/eslint/eslint.js]: Ah, I see now. We should additionally make sure that the file has been removed if we want to test the code in `catch`.

File: lib/eslint/eslint.js (hunk 1 above)
Comment (fasttime) [reply lib/eslint/eslint.js:709]: > My understanding of the reasoning is that if it happens that the cache file disappears between two fs commands, this should not throw an error.

Yes, I also think that's what that comment is saying. I was actually considering that the `existsSync` check will skip nearly all cases where `unlink` would currently reject with an error, including, but not limited, to those tested in the try-catch block. So for example `existsSync` will return false if a user has no permission to read a directory, or if a network drive is not found on Windows, or if an I/O error (e.g. a hardware problem) occurs, etc. By contrast, `unlink` rejects with different [error codes](https://nodejs.org/api/errors.html#nodejs-error-codes) in all these cases. This means that by checking `existsSync` in advance as it's done in this PR, these cases will no longer produce an error. It seems redundant at this point to test for error codes `ENOENT` and `EROFS` specifically in the catch block, when other errors are supposed to be swallowed as well. If a concern is that the file system could change during `fs` calls then maybe we could repeat the `existsSync` in the catch block:

```js
			try {
				if (existsSync(cacheFilePath)) {
					await fs.unlink(cacheFilePath);
				}
			} catch (error) {
				if (existsSync(cacheFilePath)) {
					throw error;
				}
			}
```

**Review by fasttime — APPROVED** [review]
LGTM if we want to catch race conditions when attempting to delete the file. Leaving open for @mdjermanovic to review.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
