### PR TITLE
Fix: newline-after-var to ignore declare in for specifiers (fixes #2317)

### LINKED ISSUE #2317: newline-after-var declare in for loop
I like the new line after var feature how ever I was wondering if it would be possible to add an option to allow it to ignore values declared in a for loop. Currently when newline-after-var is enabled this is considered an error

```
for (let i = 0; i<10; i++) {
    console.log(i);
}
```

Obviously this is possible but it defeats the purpose of the "i" only being defined in the scope of the for using let

```
let i;

for (i = 0; i<10; i++) {
    console.log(i);
}
```

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

File: lib/rules/newline-after-var.js [hunk 1]
```diff
@@ -41,6 +41,16 @@ module.exports = function(context) {
     }
 
     /**
+     * Determine if provided keyword is a variant of for specifiers
+     * @private
+     * @param {String} keyword - keyword to test
```
Comment (nzakas) [inline lib/rules/newline-after-var.js]: Lowercase "string" and "boolean", to differentiate from objects.

**Comment by gyandeeps** [comment]
@nzakas I think now it should be good to go.

**Comment by nzakas** [comment]
Looks good. Thanks!
