### PR TITLE
fix: autofix recursive functions in no-var

### LINKED ISSUE #16610: Bug: `no-var` autofix is not working
### How to reproduce?

config:
```
'no-var': ['error']
```

code:
```js
var fx = function (i = 0) {
  if (i < 5) {
    return fx(i + 1);
  }
  console.log(i);
};

fx();
```

### What did you expect to happen?

`var fx` autofixed to `let fx`

I tried the code in a sandpit and it behaves the same.

### What actually happened?

not autofixed, `Unexpected var, use let or const instead  no-var` error is generated

(autofix of `var` -> `let` works in other cases, the problem is present only when the variable is referred in anonymous function in the same declaration)

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #16610

#### What changes did you make? (Give an overview)

In the `no-var` rule, I fixed the logic that checks whether a variable has a reference in TDZ to skip references in the variable initializer if the initializer is a function definition.

### CODE REVIEW

File: tests/lib/rules/no-var.js [hunk 1]
```diff
@@ -319,6 +319,74 @@ ruleTester.run("no-var", rule, {
             code: "function foo() { var { let } = {}; }",
             output: null,
             errors: [{ messageId: "unexpectedVar" }]
+        },
+
+        // https://github.com/eslint/eslint/issues/16610
+        {
+            code: "var fx = function (i = 0) { if (i < 5) { return fx(i + 1); } console.log(i); }; fx();",
```
Comment (amareshsm) [inline tests/lib/rules/no-var.js:326]:
```suggestion
            code: "var fx = function (i = 0) { if (i < 5) { return fx(i + 1); } }; fx();",
```
In code `console.log(i)` added intentionally?

Comment (mdjermanovic) [reply tests/lib/rules/no-var.js:326]: Yes, this is the the same code (except for whitepace) as in the original issue https://github.com/eslint/eslint/issues/16610, to confirm that the reported problem is fixed.

**Review by nzakas — APPROVED** [review]
LGTM.
