### PR TITLE
fix: update error message for unused suppressions

### LINKED ISSUE #20490: Change Request: Improve unusedSuppressionsCount error message
### ESLint version

9.39.2

### What problem do you want to solve?

The following message is misleading:
```
There are suppressions left that do not occur anymore. Consider re-running the command with `--prune-suppressions`.
--
🚨 Error: The command exited with status 2
```
Users are often confused as to why their lint step is failing when there are no errors.

### What do you think is the correct solution?

Remove the word `Consider` from the message. This makes the fix appear optional, when it isn't.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by DMartens**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Update the message of the CLI when there are excess suppressions.
Now it also mentions the flag `--pass-on-unpruned-suggestions`.
Fixes #20490.

#### Is there anything you'd like reviewers to focus on?
Should the message be multiline, for example:
```txt
Error message:
- `--prune-suggestions` ...
- `--pass-on-unpruned-suggestions` ...
```

### CODE REVIEW

File: lib/cli.js [hunk 1]
```diff
@@ -499,7 +499,7 @@ const cli = {
 
 				if (unusedSuppressionsCount > 0) {
 					log.error(
-						"There are suppressions left that do not occur anymore. Consider re-running the command with `--prune-suppressions`.",
+						"There are suppressions left that do not occur anymore. To resolve this either re-run this command with `--prune-suggestions` to remove excess suppressions or `--pass-on-unpruned-suppressions` to ignore this error.",
```
Comment (mdjermanovic) [inline lib/cli.js]:
```suggestion
						"There are suppressions left that do not occur anymore. To resolve this, re-run the command with `--prune-suggestions` to remove unused suppressions. To ignore unused suppressions, use `--pass-on-unpruned-suppressions`.",
```

To split ignoring the problem from resolving it.

File: lib/cli.js [hunk 2]
```diff
@@ -499,7 +499,7 @@ const cli = {
 
 				if (unusedSuppressionsCount > 0) {
 					log.error(
-						"There are suppressions left that do not occur anymore. Consider re-running the command with `--prune-suppressions`.",
+						"There are suppressions left that do not occur anymore. To resolve this, re-run the command with `--prune-suggestions` to remove unused suppressions. To ignore unused suppressions, use `--pass-on-unpruned-suppressions`.",
```
Comment (mdjermanovic) [inline lib/cli.js]:
```suggestion
						"There are suppressions left that do not occur anymore. To resolve this, re-run the command with `--prune-suppressions` to remove unused suppressions. To ignore unused suppressions, use `--pass-on-unpruned-suppressions`.",
```

Typo.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
