### PR TITLE
Fix: Supports Unicode BOM (fixes #4878)

### LINKED ISSUE #4878: Allow the Utf-8 BOM with no-irregular-whitespace
As suggested in https://groups.google.com/forum/#!topic/eslint/UKq91-aGycw

A file that has the UTF-8 BOM triggers an error with the no-irregular-whitespace rule:
line 1, col 1, Error - Irregular whitespace not allowed (no-irregular-whitespace)

So this is a request to be able (at least as an option) to ignore the BOM at the start of the file (but not in any other place).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29680432-allow-the-utf-8-bom-with-no-irregular-whitespace?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #4878.

- `eslint.verify()` API came to strip BOM before parsing.
- `hasBOM` property was added into `SourceCode` object.
- `SourceCodeFixer.applyFixes()` came to insert BOM to the head of output if `sourceCode.hasBOM` is `true`.

> This diff becomes more readable if you add `?w=1`.

### CODE REVIEW

File: lib/eslint.js [hunk 1]
```diff
@@ -818,6 +825,13 @@ module.exports = (function() {
             }
         });
 
+        // If there is BOM then it increases the column of the first line.
+        if (sourceCode && sourceCode.hasBOM) {
+            for (var i = 0; i < messages.length && messages[i].line === 1; ++i) {
+                messages[i].column += 1;
```
Comment (mysticatea) [inline lib/eslint.js]: I'm not sure this is needed.

File: tests/lib/eslint.js [hunk 2]
```diff
@@ -2112,6 +2112,113 @@ describe("eslint", function() {
...
+                assert.equal(messages.length, 2);
+                assert.equal(messages[0].line, 1);
+                assert.equal(messages[0].column, 1);
+                assert.equal(messages[1].line, 2);
+                assert.equal(messages[1].column, 1);
+            });
+        });
+
+        // Skip in browsers because we cannot use "fs".
+        (typeof window === "object" ? xdescribe : describe)("when it read a UTF-8 file (has BOM), SourceCode", function() {
```
Comment (mysticatea) [inline tests/lib/eslint.js]: Should I separate test file for this?

The purpose of this test is to confirm that it can handle UTF-8 BOM `[0xEF, 0xBB, 0xBF]` in a file.
In other tests, those are using UTF-16 BOM in a string literal.

File: lib/eslint.js [hunk 3]
```diff
@@ -673,10 +673,17 @@ module.exports = (function() {
...
+            // http://www.ecma-international.org/ecma-262/6.0/#sec-unicode-format-control-characters
+            var hasBOM = (text.charCodeAt(0) === 0xFEFF);
+            if (hasBOM) {
+                text = text.slice(1);
+            }
 
             // there's no input, just exit here
             if (text.trim().length === 0) {
-                sourceCode = new SourceCode(text, blankScriptAST);
+                sourceCode = new SourceCode(text, blankScriptAST, {hasBOM: hasBOM});
```
Comment (nzakas) [inline lib/eslint.js]: I think we need to keep the text as it was originally when we pass it in here sonthe BOM is present. Then, you can calculate `hasBOM` in the constructor.

File: lib/eslint.js (hunk 1 above)
Comment (nzakas) [inline lib/eslint.js]: I don't think so. The BOM is zero-width, so people won't see it in editors.

**Comment by mysticatea** [comment]
I updated this PR.

- Removed the third argument of `SourceCode` constructor.
- Added the code which calculates `hasBOM` into `SourceCode` constructor.
- Moved several tests from `tests/lib/eslint.js` to `tests/lib/util/source-code.js`.

`eslint.verify()` still is stripping BOM before parsing.

File: lib/eslint.js [hunk 4]
```diff
@@ -673,17 +686,22 @@ module.exports = (function() {
 
         // only do this for text
         if (text !== null) {
-
             // there's no input, just exit here
             if (text.trim().length === 0) {
-                sourceCode = new SourceCode(text, blankScriptAST);
+                sourceCode = new SourceCode(
+                    stripUnicodeBOM(text),
```
Comment (nzakas) [inline lib/eslint.js]: This should be `text`, so `SourceCode` has the original text.

File: lib/util/source-code.js [hunk 5]
```diff
@@ -87,19 +87,28 @@ function looksLikeExport(astNode) {
...
+     */
+    this.hasBOM = (text.charCodeAt(0) === 0xFEFF);
+
     /**
      * The original text source code.
+     * BOM was stripped from this text.
      * @type string
      */
-    this.text = text;
+    this.text = (this.hasBOM ? text.slice(1) : text);
```
Comment (nzakas) [inline lib/util/source-code.js]: Do we need to strip the BOM at all here? What if we just left this as `text`?

Comment (mysticatea) [inline lib/util/source-code.js]: But AST is created from the stripped text.
BOM is zero width character but 1 character.
So I guessed AST gets wrong `range` if this is original text.

File: lib/eslint.js (hunk 4 above)
Comment (mysticatea) [inline lib/eslint.js]: Oh this is a mistake!

**Comment by mysticatea** [comment]
I updated this PR.

- Fixed https://github.com/eslint/eslint/pull/4935#discussion_r49769347

File: lib/util/source-code.js (hunk 5 above)
Comment (nzakas) [inline lib/util/source-code.js]: Ah, I see. Thanks for explaining.

**Comment by nzakas** [comment]
Can you update the `SourceCode` docs? https://github.com/eslint/eslint/blob/master/docs/developer-guide/nodejs-api.md#sourcecode

**Comment by mysticatea** [comment]
Sure, I had been forgetting docs.

**Comment by mysticatea** [comment]
I updated docs.

If a given AST object was parsed from not stripped text, the source code object might get wrong range of AST. So I changed this commit tag to `Breaking`.

And I updated source-code-fixer.
Now `fixer.removeRange([-1, 0])` removes BOM, `fixer.insertBeforeRange([0, 0], "\uFEFF")` inserts BOM.

**Comment by nzakas** [comment]
Lgtm.

File: tests/lib/util/source-code-fixer.js [hunk 6]
```diff
@@ -242,6 +270,221 @@ describe("SourceCodeFixer", function() {
...
+        describe("BOM manipulations", function() {
+
+            it("should insert BOM with an insertion of '\uFEFF' at 0", function() {
+                var result = SourceCodeFixer.applyFixes(sourceCode, [ INSERT_BOM ]);
+                assert.equal(result.output, "\uFEFF" + TEST_CODE);
+                assert.isTrue(result.fixed);
+                assert.equal(result.messages.length, 0);
+            });
+
+            it("should insert BOM with an insertion of '\uFEFFfoobar' at 0", function() {
```
Comment (platinumazure) [inline tests/lib/util/source-code-fixer.js]: Seems the test description doesn't match what actually happens here... (foobar vs // start)

File: tests/lib/util/source-code-fixer.js [hunk 7]
```diff
@@ -242,6 +270,221 @@ describe("SourceCodeFixer", function() {
...
+            });
+
+            it("should remove BOM with a negative range", function() {
+                var result = SourceCodeFixer.applyFixes(sourceCode, [ REMOVE_BOM ]);
+                assert.equal(result.output, TEST_CODE);
+                assert.isTrue(result.fixed);
+                assert.equal(result.messages.length, 0);
+            });
+
+            it("should replace BOM with a negative range and 'foobar'", function() {
```
Comment (platinumazure) [inline tests/lib/util/source-code-fixer.js]: Seems the test description doesn't match what actually happens here... (foobar vs // start)

File: tests/lib/util/source-code-fixer.js (hunk 6 above)
Comment (mysticatea) [inline tests/lib/util/source-code-fixer.js]: My intention here, foobar is "any string".

Comment (platinumazure) [inline tests/lib/util/source-code-fixer.js]: Fair enough, but having foobar in the quotes makes it look like a string
literal so I assumed that was what you were aiming for. Maybe it could say
something like "... '\uxFEFF' plus any string..." so that only the BOM is
in the string literal? Then again maybe I'm overthinking it.

Comment (mysticatea) [inline tests/lib/util/source-code-fixer.js]: Thank you for the advice. I learnt it. I had not gotten that phrase before.
