### PR TITLE
Fix: indent for async arrow functions (fixes #13497)

### LINKED ISSUE #13497: Indent level (parameters: first) for async arrow functions
Probably the same as #10531 which was automatically closed due to inactivity 2 years ago.

**Tell us about your environment**

ESLint Version: **7.4.0**
Node Version: **14.5.0**
yarn Version: **1.22.4**
What parser (default, Babel-ESLint, etc.) are you using? **espree & @typescript-eslint/parser**

**Configuration**

```javascript
const indentOptions = {
  "FunctionDeclaration": { "parameters": "first" },
  "FunctionExpression": { "parameters": "first" },
};
const indent = ["error", 2, indentOptions];

module.exports = {
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: "module"
  },
  overrides: [
    {
      files: ["*.js"],
      parser: "espree",
      rules: {
        indent: indent
      }
    }
  ]
};
```

**What did you do?**

```javascript
const foo = async (arg1,
                   arg2) =>
{
  return arg1 + arg2;
}
```

```node_modules/.bin/eslint foo.js```

**What did you expect to happen?**

Run without errors

**What actually happened?**

```bash
/private/tmp/foo/foo.js
  2:1  error  Expected indentation of 2 spaces but found 19  indent

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Note:** if I remove the async then the error goes away (the "parameters": "first" is honoured).

### PR DESCRIPTION
**Pull request by anikethsaha**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
fixes #13497 

Indent for async arrow function was not working as the first token in the async arrow function node is the `async` not the opening paren. So the condition [here](https://github.com/eslint/eslint/blob/master/lib/rules/indent.js#L1089) would not be truthy. 
So I added one more check for simply checking the type as `Identifier` and value as `async`

#### Is there anything you'd like reviewers to focus on?
None

### CODE REVIEW

File: lib/rules/indent.js [hunk 1]
```diff
@@ -1094,6 +1094,17 @@ module.exports = {
                     parameterParens.add(closingParen);
                     addElementListIndent(node.params, openingParen, closingParen, options.FunctionExpression.parameters);
                 }
+
+                if (firstToken.type === "Identifier" && firstToken.value === "async") {
+                    const openingParen = sourceCode.getTokenAfter(firstToken);
```
Comment (mdjermanovic) [inline lib/rules/indent.js:1099]: What will happen if the first token after `async` isn't an opening paren, as in `async a => {}`

Comment (anikethsaha) [reply lib/rules/indent.js:1099]: Thanks for the input.

I added a check and tests for this. 

Let me know if there is anything else.

File: lib/rules/indent.js [hunk 2]
```diff
@@ -1094,6 +1094,19 @@ module.exports = {
...
```
Comment (kaicataldo) [inline lib/rules/indent.js:1099]: Can we change this variable name? Maybe `nextToken`?

Comment (anikethsaha) [reply lib/rules/indent.js]: done

File: lib/rules/indent.js [hunk 3]
```diff
@@ -1094,6 +1094,19 @@ module.exports = {
                     parameterParens.add(closingParen);
                     addElementListIndent(node.params, openingParen, closingParen, options.FunctionExpression.parameters);
                 }
+
+                if (firstToken.type === "Identifier" && firstToken.value === "async") {
+                    const nextToken = sourceCode.getTokenAfter(firstToken);
```
Comment (kaicataldo) [inline lib/rules/indent.js:1099]: Sorry, missed this the first time, but what happens if the next token is a comment? Could we add a test to ensure that this is behaving as expected?

Comment (anikethsaha) [reply lib/rules/indent.js:1099]: I added the tests.

File: lib/rules/indent.js [hunk 4]
```diff
@@ -1094,6 +1094,19 @@ module.exports = {
...
+
+                    if (astUtils.isOpeningParenToken(nextToken)) {
+                        const closingParen = sourceCode.getTokenBefore(node.body, astUtils.isClosingParenToken);
+
+                        parameterParens.add(nextToken);
+                        parameterParens.add(closingParen);
+                        addElementListIndent(node.params, nextToken, closingParen, options.FunctionExpression.parameters);
+                    }
```
Comment (mdjermanovic) [inline lib/rules/indent.js:1107]: This is basically the same code as the code for the first token, the only difference is that it's checking the second token instead of the first token. Could we maybe avoid duplicating these lines? 

Arrow function nodes have `async` boolean property, so maybe we can do something like this:

```js
const maybeOpeningParen = sourceCode.getFirstToken(node, node.async ? 1 : 0);

if (astUtils.isOpeningParenToken(maybeOpeningParen)) {
  // ...
}
```

Comment (anikethsaha) [reply lib/rules/indent.js]: Awesome !

Thanks a lot for sharing this.

File: tests/lib/rules/indent.js [hunk 5]
```diff
@@ -5724,6 +5724,111 @@ ruleTester.run("indent", rule, {
             `,
             options: [4, { MemberExpression: 2 }],
             parserOptions: { ecmaVersion: 2015 }
+        },
+        {
+            code: unIndent`
+const foo = async (arg1,
```
Comment (mdjermanovic) [inline tests/lib/rules/indent.js:5730]: Since we are using `unIndent`, code in newly added tests can be indented like the code in all previous tests?

File: tests/lib/rules/indent.js [hunk 6]
```diff
@@ -5724,6 +5724,105 @@ ruleTester.run("indent", rule, {
...
             parserOptions: { ecmaVersion: 2015 }
+        },
+        {
+            code: unIndent`
+                const foo = async (arg1,
+                                   arg2) =>
+                {
+                  return arg1 + arg2;
+                }
+    `,
```
Comment (mdjermanovic) [inline tests/lib/rules/indent.js:5735]: It would be nice to consistently align closing backticks with `code`/`output`, like in all previously existing tests.

File: tests/lib/rules/indent.js [hunk 7]
```diff
@@ -11473,6 +11572,41 @@ ruleTester.run("indent", rule, {
                 [6, 4, 0, "Punctuator"],
                 [7, 4, 0, "Punctuator"]
             ])
+        },
+        {
+            code: unIndent`
+const foo = async (arg1,
```
Comment (mdjermanovic) [inline tests/lib/rules/indent.js:11578]: Can we also indent `invalid` tests.

File: tests/lib/rules/indent.js [hunk 8]
```diff
@@ -11473,6 +11572,41 @@ ruleTester.run("indent", rule, {
...
+            ])
+        },
+        {
+            code: unIndent`
+                const a = async
+                 b => {}
+            `,
+            output: unIndent`
+            const a = async
+            b => {}
```
Comment (mdjermanovic) [inline tests/lib/rules/indent.js:11604]: It would be nice to align `output` with `code`

All others look good, thanks for formatting the tests!

File: lib/rules/indent.js [hunk 9]
```diff
@@ -1084,16 +1084,17 @@ module.exports = {
             },
 
             ArrowFunctionExpression(node) {
-                const firstToken = sourceCode.getFirstToken(node);
+                const maybeOpeningParen = sourceCode.getFirstToken(node, node.async ? 1 : 0);
```
Comment (aladdin-add) [inline lib/rules/indent.js:1087]: I've read the docs: 

> countOptions is an object which has 3 properties; count, includeComments, and filter. Default is {count: 0, includeComments: false, filter: null}.

Not sure a number(0/1) is allowed(maybe the docs need to be updated). or just using the "official" options:

```js
const maybeOpeningParen = sourceCode.getFirstToken(node, { count: node.async ? 1 : 0});
```

Comment (mdjermanovic) [reply lib/rules/indent.js:1087]: For `getFirstToken` it's `skipOptions`.

Short form for number [is supported](https://github.com/eslint/eslint/blob/488d1595aef43c4d52cccdb2c97977884f0375a8/lib/source-code/token-store/index.js#L249) and I think it's common in our codebase, but it may be indeed more readable to use the long `{ skip: node.async ? 1 : 0 }`.

Comment (aladdin-add) [reply lib/rules/indent.js:1087]: well, seems the [docs](https://eslint.org/docs/developer-guide/working-with-rules#contextgetsourcecode-1) did not mention short form.

Comment (kaicataldo) [reply lib/rules/indent.js:1087]: Yeah, it would be nice to get that documented! On the other hand, that part of the documentation is already pretty difficult to understand as it is...

Comment (kaicataldo) [reply lib/rules/indent.js:1087]: That being said, I like the readability of the long form :)

Comment (anikethsaha) [reply lib/rules/indent.js]: done
