### PR TITLE
fix: warn when `eslint-env` configuration comments are found

### LINKED ISSUE #20340: Rule Change: add warning on obsolete use of `eslint-env` configuration comments in 9.x
### What rule do you want to change?

https://github.com/eslint/eslint/blob/3383e7ec9028166cafc8ea7986c2f7498d0049f0/lib/languages/js/source-code/source-code.js#L1051-L1059

### What change do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new default behavior

### Example code

```js
/* eslint-env node */
```

### What does the rule currently do for this code?

In ESLint 10 alpha it produces an error message:

>   1:1  error  /* eslint-env */ comments are no longer supported

In ESLint 9.36.1 no error or warning is shown

### What will the rule do after it's changed?

It will cause a warning if an [`eslint-env` Configuration Comments](https://eslint.org/docs/latest/use/configure/migration-guide#eslint-env-configuration-comments) is used in ESLint 9.x in a flat configuration environment.

Edit: discussions led to the modified suggestion:

Emit a warning using `process.emitWarning()` to avoid a potential breaking change of using a lint warning, if [--max-warnings](https://eslint.org/docs/latest/use/command-line-interface#--max-warnings) were used.

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by sethamus**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[x] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

This PR adds a warning when `eslint-env` configuration comments are detected during linting with flat config. These comments are no longer recognized in the flat config system and will be reported as errors in ESLint v10.0.0.

Fixes #20340

### CODE REVIEW

File: lib/services/warning-service.js [hunk 1]
```diff
@@ -93,6 +93,17 @@ class WarningService {
...
+	/**
+	 * Emits a warning when eslint-env configuration comments are found.
+	 * @returns {void}
+	 */
+	emitESLintEnvWarning() {
+		this.emitWarning(
+			"/* eslint-env */ comments are no longer recognized when linting with flat config and will be reported as errors in v10.0.0. Replace them with /* global */ comments or define globals in your config file. See https://eslint.org/docs/latest/use/configure/migration-guide#eslint-env-configuration-comments for details.",
+			"ESLintEnvWarning",
+		);
+	}
```
Comment (mdjermanovic) [inline lib/services/warning-service.js]: I think the message should include the filename (full path) where the eslint-env comment was found.

Comment (MikeMcC399) [reply lib/services/warning-service.js]: A typical message would be:

```text
(node:9627) ESLintEnvWarning: /* eslint-env */ comments are no longer recognized when linting with flat config and will be reported as errors in v10.0.0. Replace them with /* global */ comments or define globals in your config file. See https://eslint.org/docs/latest/use/configure/migration-guide#eslint-env-configuration-comments for details.
(Use `node --trace-warnings ...` to show where the warning was created)
```

and the standard instruction "Use `node --trace-warnings ...` to show where the warning was created" is not helpful, so do please add the location of the file where the comment was found.

File: lib/services/warning-service.js [hunk 2]
```diff
@@ -93,6 +93,17 @@ class WarningService {
...
 		);
 	}
+
+	/**
+	 * Emits a warning when eslint-env configuration comments are found.
+	 * @returns {void}
+	 */
+	emitESLintEnvWarning() {
+		this.emitWarning(
+			"/* eslint-env */ comments are no longer recognized when linting with flat config and will be reported as errors in v10.0.0. Replace them with /* global */ comments or define globals in your config file. See https://eslint.org/docs/latest/use/configure/migration-guide#eslint-env-configuration-comments for details.",
```
Comment (MikeMcC399) [inline lib/services/warning-service.js]: Suggest to change `v10.0.0` to either `v10.x` or just `v10`, otherwise it sounds as though only the first release of ESLint v10 would show the error.

**Review by MikeMcC399 — CHANGES_REQUESTED** [review]
See in-line comments regarding reference to specific ESLint version `v10.0.0`

**Comment by mdjermanovic** [comment]
After https://github.com/eslint/eslint/pull/20382 is merged, we should run CI checks on this branch.

File: lib/services/warning-service.js (hunk 1 above)
Comment (mdjermanovic) [reply lib/services/warning-service.js]: It might be good to also include the line number, to help locate the comment.

**Comment by mdjermanovic** [comment]
> After #20382 is merged, we should run CI checks on this branch.

Okay, #20382 has been merged, so the next commit to this branch should automatically trigger CI checks.

File: lib/services/warning-service.js (hunk 1 above)
Comment (sethamus) [reply lib/services/warning-service.js]: I have included the filename and line number in the message.

File: lib/services/warning-service.js (hunk 2 above)
Comment (sethamus) [reply lib/services/warning-service.js]: We use `v10.0.0` in the other warnings. For example, when `ESLINT_USE_FLAT_CONFIG` is set to `false`, the warning says:

> You are using an eslintrc configuration file, which is deprecated and support will be removed in v10.0.0. Please migrate to an eslint.config.js file. See https://eslint.org/docs/latest/use/configure/migration-guide for details. An eslintrc configuration file is used because you have the ESLINT_USE_FLAT_CONFIG environment variable set to false. If you want to use an eslint.config.js file, remove the environment variable. If you want to find the location of the eslintrc configuration file, use the --debug flag.

Comment (MikeMcC399) [reply lib/services/warning-service.js]: That's not quite the same, as it's referring to an action that takes place in v10.0.0 "will be removed in v10.0.0", which implies that versions above will also not have support.

If you want to keep v10.0.0 in the error message for this PR, then you could change it to

"will be reported as errors in v10.0.0 and above" or
"will be reported as errors in v10.0.0+"

I'll defer to the ESLint team's opinion about this one. It's a minor comment from me as a user.

File: lib/linter/linter.js [hunk 3]
```diff
@@ -1921,6 +1921,20 @@ class Linter {
...
+							comment.value,
+						);
+						if (label === "eslint-env") {
+							slots.warningService.emitESLintEnvWarning(
+								options.filename,
+								comment.loc.start.line,
+							);
+						}
+					}
+				}
```
Comment (mdjermanovic) [inline lib/linter/linter.js]: I think this check should be in `SourceCode.applyInlineConfig`, similar to how it is implemented in ESLint v10 (we'd just emit a warning instead of returning an error) https://github.com/eslint/eslint/blob/5a4324f38e7ce370038351ef7412dcf8548c105e/lib/languages/js/source-code/source-code.js#L1051-L1059 because we warn about `eslint-env` comments that are used with JS Language as those are no longer supported. Custom languages can still support this kind of config comments (I doubt there are any, but still in theory a custom language can support any kind and form of config comments). Also, that would simplify the implementation and avoid duplicate parsing of configuration comments.

Comment (mdjermanovic) [reply lib/linter/linter.js]: Ah, it seems that `SourceCode` doesn't know `filename`? Then, we could leave this here but check if the language is `jslang`.

Comment (sethamus) [reply lib/linter/linter.js]: Done!

File: lib/services/warning-service.js (hunk 2 above)
Comment (nzakas) [reply lib/services/warning-service.js]: Agree with @MikeMcC399 here -- something like "as of v10.0.0" would make this clearer.

**Comment by mdjermanovic** [comment]
The CI failure should be fixed by https://github.com/eslint/eslint/pull/20391.

**Comment by MikeMcC399** [comment]
@mdjermanovic / @sethamus 

> The CI failure should be fixed by #20391.

#20391 is now merged. 

If this PR / branch could be rebased, it should then pass CI.

**Comment by mdjermanovic** [comment]
I'll close & reopen to sync the ref for CI and run checks again.

File: tests/tools/check-rule-examples.js
Comment (mdjermanovic) [inline tests/tools/check-rule-examples.js:1]: I think it would be better to simplify this by adding `--no-warnings` flag to the command, because in these tests we're not interested in emitted warnings and I'm not sure if the order and format of warnings is guaranteed.

https://github.com/eslint/eslint/blob/e7673ae096900330599680efe91f8a199a5c2e59/tests/tools/check-rule-examples.js#L25

```js
["--no-deprecation", "--no-warnings", "tools/check-rule-examples.js", ...filenames],
```

Comment (mdjermanovic) [reply tests/tools/check-rule-examples.js:1]: Actually, since deprecations fall under warnings, we can just replace the flag:

```js
["--no-warnings", "tools/check-rule-examples.js", ...filenames],
```

https://nodejs.org/api/cli.html#--no-warnings

**Comment by mdjermanovic** [comment]
Since this doesn't add new features, I changed the tag to `fix`.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Leaving open for @nzakas to verify.

**Review by SwetaTanwar — APPROVED** [review]
Looks good, thank you for your contribution!

**Review by fasttime — APPROVED** [review]
LGTM, thanks! This should be merged for the v9.39.2 release.
