### PR TITLE
Fix: Report better location for padded-blocks error (fixes #2224)

### LINKED ISSUE #2224: Block must not be padded by blank lines.
On the first line of this snippet, column 80:

```javascript
  it('should throw an exception when cache configuration is wrong', function () {
    var c = {                                                                                                                                                             
      store: {
        put: function () {}                                                                                                                                               
      }
    }
```

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

File: lib/rules/padded-blocks.js [hunk 1]
```diff
@@ -13,12 +13,15 @@
...
     var requirePadding = context.options[0] !== "never";
 
+    var ALWAYS_MESSAGE = "Block must be padded by blank lines.",
+        NEVER_MESSAGE = "Block must not be padded by blank lines.";
+
     /**
      * Checks if the given non empty block node has a blank line before its first child node.
      * @param {ASTNode} node The AST node of a BlockStatement.
-     * @returns {boolean} Whether or not the block starts with a blank line.
+     * @returns {Location} Whether or not the block starts with a blank line.
```
Comment (btmills) [inline lib/rules/padded-blocks.js]: This still returns a `boolean`.

**Comment by btmills** [comment]
One comment on the JSDoc for `isBlockTopPadded`. Other than that, looks good.

File: lib/rules/padded-blocks.js (hunk 1 above)
Comment (nzakas) [inline lib/rules/padded-blocks.js]: Oops, thanks!
