### PR TITLE
Fix: Normalizes messages so all end with a period (fixes #6762)

### LINKED ISSUE #6762: Dots at the end of many messages are omitted
**What version of ESLint are you using?**
3.1.1
**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
Example for `array-bracket-spacing` but this issue is not limited to this rule only - 

```json
{
	"rules": {
		"array-bracket-spacing": "error"
	}
}
```

**What did you do? Please include the actual source code causing the issue.**
```js
var foo = [ ]
```

**What did you expect to happen?**
Have a dot at the end - 
`  1:11  error  There should be no space after '['.  array-bracket-spacing`

**What actually happened? Please include the actual, raw output from ESLint.**
It doesn't have a dot at the end - 
`  1:11  error  There should be no space after '['  array-bracket-spacing`

--

I'm not sure if this is intentional or not, every message should have a dot at the end or there is a different policy in place? If so, I think it should be documented.

Beside that, if this is really a "bug" I think every rule should be fixed with one commit in order not to trash the commit history

### PR DESCRIPTION
**Pull request by pmcelhaney**
**What issue does this pull request address?**
Ensures that all messages end with a period, for consistency.

**What changes did you make? (Give an overview)**
Added periods to messages where they were missing, both the rules and the tests. 

**Is there anything you'd like reviewers to focus on?**
I'm concerned that there are 498 additions and 499 deletions. The extra deletion may be a mistake, but I can't find it.

### CODE REVIEW

File: lib/rules/no-restricted-globals.js [hunk 1]
```diff
@@ -77,4 +77,3 @@ module.exports = {
         };
     }
 };
-
```
Comment (mysticatea) [inline lib/rules/no-restricted-globals.js]: Fwiw, I found the deletion of just an empty line.

**Comment by ilyavolodin** [comment]
LGTM. I think we should try to merge this in as soon as possible to avoid merge conflicts.

**Comment by nzakas** [comment]
LGTM.
