### PR TITLE
Fix: `no-unused-vars` had been missing some parameters

### LINKED ISSUE #4047: Unused var error missing when using es6 modules and arrow function (no-unused-vars)
````
export default (a, b)=> {
  console.log(a);
};
````
This code yields no errors.
Expected output is to get a no-unused-vars error for b variable.
Version is eslint 1.6.1
Settings are:

````
{
  "env": {
    "es6": true
  },
  "ecmaFeatures": {
    "modules": true
  },
  "rules": {
    "no-unused-vars": 2
  }
}
````

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27173968-unused-var-error-missing-when-using-es6-modules-and-arrow-function-no-unused-vars?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #4047.

If function expressions or arrow function expressions were exported,
these parameters had been not reported by `no-unused-vars`.

### CODE REVIEW

File: tests/lib/rules/no-unused-vars.js [hunk 1]
```diff
@@ -233,5 +233,22 @@ ruleTester.run("no-unused-vars", rule, {
         //         {line: 1, column: 16, message: "\"𠮷\" is defined but never used" }
         //     ]
         // }
+
+        // https://github.com/eslint/eslint/issues/4047
```
Comment (nzakas) [inline tests/lib/rules/no-unused-vars.js]: Can you add a test with more than one parameter like what was reported?

Comment (mysticatea) [inline tests/lib/rules/no-unused-vars.js]: Sure, I have done.

**Comment by nzakas** [comment]
Lgtm
