### PR TITLE
Fix: `no-fallthrough` empty case with comment (fixes #5799)

### LINKED ISSUE #4799: About cli API
Good day!

What if I want to lint files and output results via ESLint's service but programmatically?

Why `cli` has been removed?

Thanks.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29380350-about-cli-api?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #5799: no-fallthrough doesn't seem to work
Maybe I am missing something, but the following code snippet lints successfully when I enter it into http://eslint.org/demo/. I expected it to fail with `no-fallthrough`.

```javascript
switch ("foo") {
case "foo":
case "bar":
    break;
default:
    throw new Error();
}
```

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

File: tests/lib/rules/no-fallthrough.js [hunk 1]
```diff
@@ -129,6 +129,14 @@ ruleTester.run("no-fallthrough", rule, {
             errors: errorsDefault
         },
         {
+            code: "switch(foo) { case 0: // comment\n default: b() }",
+            errors: errorsDefault
+        },
+        {
+            code: "switch(foo) { case 0: /* comment */ default: b() }",
+            errors: errorsDefault
+        },
```
Comment (platinumazure) [inline tests/lib/rules/no-fallthrough.js]: I'd feel better if there were test cases for what was initially reported (`case 0:\n    // comment\ncase 1: yay();`, that is, with a line break between the case and the comment). Would you mind terribly adding those cases?

**Comment by alberto** [comment]
PR updated with latest feedback from issue.

File: lib/rules/no-fallthrough.js [hunk 2]
```diff
@@ -39,6 +39,19 @@ function isReachable(segment) {
     return segment.reachable;
 }
 
+/**
+ * Checks whether a SwitchCase node is adjacent to the token after it
+ * @param {ASTNode} node - The case node to check
+ * @param {RuleContext} context - Rule context
+ * @returns {boolean} `true` if the case is adjacent to the next token
+ */
+function isAdjacentToNextToken(node, context) {
```
Comment (nzakas) [inline lib/rules/no-fallthrough.js]: I think the term "adjacent" is a bit misleading here. You only care about line numbers, correct? Should this be named something that better reflects what it's doing?

Also, it would better to just pass the SourceCode object in as the second argument rather than the context object.

File: lib/rules/no-fallthrough.js [hunk 3]
```diff
@@ -39,6 +39,19 @@ function isReachable(segment) {
...
+    var sourceCode = context.getSourceCode();
+    var nextToken = sourceCode.getTokenAfter(node);
+
+    return nextToken && nextToken.loc.start.line <= node.loc.end.line + 1;
```
Comment (nzakas) [inline lib/rules/no-fallthrough.js]: The start line for the next token can't actually be less than end line of the node can it? Would `===` be better?

Comment (alberto) [inline lib/rules/no-fallthrough.js]: They could be on the same line.

File: lib/rules/no-fallthrough.js (hunk 2 above)
Comment (alberto) [inline lib/rules/no-fallthrough.js]: Sorry I had missed this comment. I could come up with a good name since they could be on the same line, as mentioned below. What if I rewrite to `hasBlankLinesBetween(node, token)`?

File: lib/rules/no-fallthrough.js (hunk 3 above)
Comment (nzakas) [inline lib/rules/no-fallthrough.js]: Sorry, I'm not following. Can you explain why that would trigger `<` rather than `===`?

Comment (alberto) [inline lib/rules/no-fallthrough.js]: Here is an example:

```
case 0: case 1: 
  foo();
```

Comment (nzakas) [inline lib/rules/no-fallthrough.js]: Oh I see. This is very unclear, can you add some comments explaining this logic?

Comment (platinumazure) [inline lib/rules/no-fallthrough.js]: Why use `<=` and `+ 1`? Would it be more readable to use `<` without adding 1?

File: lib/rules/no-fallthrough.js [hunk 4]
```diff
@@ -39,13 +39,24 @@ function isReachable(segment) {
     return segment.reachable;
 }
 
+/**
+ * Checks whether a node and a token are separated by blank lines
+ * @param {ASTNode} node - The node to check
+ * @param {Token} token - The token to compare against
+ * @returns {boolean} `true` if there are blank lines between node and token
+ */
+function hasBlankLinesBetween(node, token) {
```
Comment (alberto) [inline lib/rules/no-fallthrough.js]: @nzakas Do you still find it unclear now that I rewrote it to this?

Comment (nzakas) [inline lib/rules/no-fallthrough.js]: This is a lot clearer, thanks!

**Comment by nzakas** [comment]
LGTM
