### PR TITLE
Fix: no-useless-rename handles ExperimentalRestProperty (fixes #6284)

### LINKED ISSUE #6284: `no-useless-rename` fails on spread operators in destructured statements
The new `no-useless-rename` rule will fail with:

```
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.checkDestructured (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/rules/no-useless-rename.js:96:26)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/eslint.js:886:36)
    at Controller.__execute (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/util/traverser.js:36:33)
```

When a spread operator is encountered, such as in this code:

```
const {...stuff} = myObject;
```

The issue is in the `checkDestructured` function which is expecting a `properties[i].key` to exist. But the ExperimentalSpread AST object does not have a `key` defined.

### PR DESCRIPTION
**Pull request by platinumazure**
I had a couple of options here-- either compare the type explicitly, or just look for the absence of a `key` property. I went with the former to be safe, but I can certainly amend to the latter if people think that is better.

At this point I've only handled destructuring-- not sure yet if this is an issue in import or export. I'll investigate that and update this PR if needed. (EDIT: Seems those use a `*` token instead. In addition, that seems to be standard ES2015. So I assume we're good-- speak up if I missed something.)

### CODE REVIEW

File: tests/lib/rules/no-useless-rename.js [hunk 1]
```diff
@@ -239,6 +260,30 @@ ruleTester.run("no-useless-rename", rule, {
             errors: ["Destructuring assignment foo unnecessarily renamed.", "Destructuring assignment bar unnecessarily renamed."]
         },
         {
+            code: "const {foo: foo, ...stuff} = myObject;",
+            parserOptions: {
```
Comment (kaicataldo) [inline tests/lib/rules/no-useless-rename.js]: We should check the fixed output here as well - check the other invalid tests for the `output` key to see what this looks like

Comment (platinumazure) [inline tests/lib/rules/no-useless-rename.js]: My bad, I didn't realize the rule was fixable. I will add that in a few
hours, when I get back home. Thanks!

**Comment by kaicataldo** [comment]
One quick comment - thanks for working on this!

**Comment by mysticatea** [comment]
I'm sorry, I had forgotten this option at that time.
Thank you.

**Comment by ilyavolodin** [comment]
Hmm.. I would rather check for absence of the `key`, then use `experimentalRestProperty`, since as the name implies, it's experimental and will change at some point in the future. Which will mean we'll have to modify this rule.

**Comment by kaicataldo** [comment]
To tag on to what @ilyavolodin suggested, I think I'd like to see a comment explaining why the change is there then (since it won't be explicitly guarding against `experimentalRestProperty`).

**Comment by platinumazure** [comment]
In all honesty, I'm not sure what's best here. It doesn't help that astexplorer.net (using its babel-eslint setting) shows a SpreadProperty which has a key and value and wouldn't have caused the rule to throw. I'm not even really sure what the spec is honestly supposed to look like here.

Until we get consensus on the approach to use in the rule itself, I will focus on adding `output` to my test cases.

**Comment by kaicataldo** [comment]
Seems to me to be more reason to go with the approach @ilyavolodin suggested. It might even work for babel-eslint users as an added bonus.

**Comment by platinumazure** [comment]
Should have mentioned I was able to reproduce the issue with babel-ESLint.
I think astexplorer only shows part of what babel-ESLint does. I only
mentioned it to show my confusion in this area. I'm happy to check for lack
of key and I can amend the PR soon to include that.

**Comment by kaicataldo** [comment]
Some weirdness with babel-eslint in astexplorer - it actually incorrectly labels `RestProperty` as `SpreadProperty`, even though babylon labels it correctly. Might be a bug with babel-eslint.

screen shot 2016-05-30 at 8 32 22 pm
screen shot 2016-05-30 at 8 32 54 pm

**Comment by platinumazure** [comment]
I did notice the upper right of astexplorer.net says "acorn-to-esprima
version 1.0.7", maybe that's a clue as to why it's inconsistent on that
site.

**Comment by kaicataldo** [comment]
Yeah, might be. Regardless, I'm a fan of @ilyavolodin's suggestion!

**Comment by platinumazure** [comment]
@kaicataldo @ilyavolodin Updated the PR per your suggestions. Please let me know if anything else needs fixing.

File: lib/rules/no-useless-rename.js [hunk 2]
```diff
@@ -87,7 +87,7 @@ module.exports = {
                     return;
                 }
 
-                if (properties[i].computed) {
+                if (properties[i].computed || !properties[i].key) {
```
Comment (kaicataldo) [inline lib/rules/no-useless-rename.js]: I think a comment here about why this guard is needed could be helpful for future contributors

**Comment by kaicataldo** [comment]
One small nit, but otherwise LGTM. Nice work!

**Comment by ilyavolodin** [comment]
LGTM! Thanks.

File: lib/rules/no-useless-rename.js (hunk 2 above)
Comment (platinumazure) [inline lib/rules/no-useless-rename.js]: I'll add that tomorrow. Thanks! Apologies for missing that.

**Comment by platinumazure** [comment]
The AppVeyor build failure is because AppVeyor still checks multiple commits (see #6292). Please let me know if there are any other issues I'm not aware of.

@kaicataldo Please let me know what you think of the comment I've added.

**Comment by kaicataldo** [comment]
Comment seems fine to me - what does the TODO mean? what's preventing us from checking that now?

**Comment by platinumazure** [comment]
It refers to if `babel-eslint` ever sends us a SpreadProperty (they do not at the moment) or if the object rest/spread proposal hits Stage 4 and thus espree would now parse that as SpreadProperty (the proposal is in Stage 2). There is nothing to do right now.

**Comment by kaicataldo** [comment]
I see - thanks for explaining. My inclination would be to remove the TODO line

**Comment by platinumazure** [comment]
@kaicataldo Can do- remove without replacement?

**Comment by kaicataldo** [comment]
That's my preference - I think it raises more questions than answers

**Comment by platinumazure** [comment]
Sorry - what I really meant is do you have a better way of expressing it?
If not, I can remove it.
On May 31, 2016 5:41 PM, "Kai Cataldo" <notifications@github.com> wrote:

That's my preference - I think it raises more questions than answers

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/eslint/eslint/pull/6288#issuecomment-222843108>, or mute
the thread
<https://github.com/notifications/unsubscribe/AARWej4tOiRKjKE5umTWTcEGsvAp-fMZks5qHLkMgaJpZM4Ip_rq>
.

**Comment by kaicataldo** [comment]
My vote is to remove it entirely and cross that bride if and when we get to it. Others might have a different opinion though!

**Comment by platinumazure** [comment]
@ilyavolodin Thoughts on how to handle the last comment issue here?

**Comment by ilyavolodin** [comment]
I'm fine with removing that comment all together. We don't really create any specific code-path in our rules for `babel-eslint`. If one of our rules conflicts with it, they usually clone the rule into `eslint-plugin-babel` and fix it.

**Comment by platinumazure** [comment]
@ilyavolodin So you believe no comment is necessary at all, even beyond removing the TODO? (Sorry for being dense, I just really want to make sure I'm understanding correctly.)

It'd be great to get consensus on this...

**Comment by ilyavolodin** [comment]
Sorry, I meant to remove TODO comment. The rest of the comments are fine.

**Comment by platinumazure** [comment]
Okay, I've removed the TODO. Let me know if there's anything else I need to do.

**Comment by kaicataldo** [comment]
LGTM, thanks!

**Comment by ilyavolodin** [comment]
LGTM
