### PR TITLE
Fix: Missing errors in space-in-parens (fixes #4257, fixes #3996)

### LINKED ISSUE #3996: `space-in-parens` warns multiline with a comment.
When there is a comment after an opening parenthesis, this rule warns spacing which is between the parenthesis and the comment.
This behavior is different from other spacing rules (`block-spacing`, `object-curly-spacing`, `computed-property-spacing`, `array-bracket-spacing`)
Is this intended behavior?

```js
/* eslint space-in-parens: 2 */
foobar( // some comment
    param,
    args,
    variables
);
```

v1.5.1

image

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27079267-space-in-parens-warns-multiline-with-a-comment?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #4257: Bug: Missing errors in space-in-parens with nested parens
In `space-in-parens`, with options: `never`

I would expect this code to produce 4 errors, but it produces just 2:
```js
( ( 1 + 2 ) )
```

For reference, this correctly produces 4 errors
```js
(  3 * ( 1 + 2 ) + 4 )
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27685729-bug-missing-errors-in-space-in-parens-with-nested-parens?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

File: tests/lib/rules/space-in-parens.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ ruleTester.run("space-in-parens", rule, {
         { code: "var foo = `(bar)`;", options: ["always"], ecmaFeatures: { templateStrings: "true" } },
         { code: "var foo = `(bar ${baz})`;", options: ["always"], ecmaFeatures: { templateStrings: "true" } },
         { code: "var foo = `(bar ${( 1 + 2 )})`;", options: ["always"], ecmaFeatures: { templateStrings: "true" } },
-
+        { code: "foo( //some comment\nbar\n)\n", options: ["never"] },
```
Comment (nzakas) [inline tests/lib/rules/space-in-parens.js]: Shouldn't this error because there's a space after `foo(`?

Comment (alberto) [inline tests/lib/rules/space-in-parens.js]: It's the behaviour detailed in #3996

Comment (nzakas) [inline tests/lib/rules/space-in-parens.js]: Ah right.
