### PR TITLE
Fix: comma-style accounts for parens in array (fixes #6006)

### LINKED ISSUE #6006: comma-style rule fails on parenthesized array item
**What version of ESLint are you using?**  `eslint@2.8.0`

**What parser (default, Babel-ESLint, etc.) are you using?**  `"parser": "babel-eslint",`

**Please show your full configuration:**
```
{
  "extends": "eslint-config-airbnb",
  "env": {
    "browser": true,
    "node": true,
    "mocha": true
  },
  "parser": "babel-eslint",
  "rules": {
    //
    // Safety
    //
    "no-unused-vars": 1,
    // Do not allow `alert` calls.
    "no-alert": 1,
    // Use the `eslint-disable-line no-console` comment for intentional console statements.
    "no-console": 1,
    // The `no-use-before-define` prevents variable and function use before definition.
    "no-use-before-define": 1,
    // The `no-var` enforces `const` and `let`.
    "no-var": 1,
    // The `block-scoped-var` warns about possibly invalid logic when `var` is declared in a block scope and used outside. We prefer `const` and `let` over `var` but keep this for now.
    "block-scoped-var": 1,
    // Disable `guard-for-in` because we use `Object.keys().forEach` and do not have to extend `Object.prototype` for older browsers.
    "guard-for-in": 0,
    // Disable `no-shadow` and `no-param-reassign` to avoid useless renaming. Be careful.
    "no-shadow": 0,
    "no-param-reassign": 0,

    //
    // Coding style
    //
    "indent": [ 1, 2, { "SwitchCase": 1 } ],
    "padded-blocks": 0,
    // The `spaced-comment` warns about the commented-out source code and dirty comments.
    "spaced-comment": 1,
    // The `comma-dangle` helps to keep version control clean if array or object items are added or removed - only the lines that are actually changed will be highlighted.
    "comma-dangle": 0,
    "space-in-parens": 0,
    // TODO(sompylasar): Re-enable `curly` and fix.
    "curly": [ 0, "all" ],
    "array-bracket-spacing": [ 1, "always" ],
    "object-curly-spacing": [ 1, "always" ],
    "computed-property-spacing": 0,
    "brace-style": [ 1, "stroustrup", { "allowSingleLine": true } ],
    "no-trailing-spaces": [ 1, { "skipBlankLines": true } ],
    "linebreak-style": [ 1, "unix" ],
    "no-multiple-empty-lines": [ 1, { "max": 3, "maxEOF": 1 } ],
    "eol-last": [ 2, "unix" ],
    "id-length": [ 1, { "min": 2, "exceptions": [ "_", "$", "i", "j", "k", "x", "y", "e" ] } ],
    "camelcase": 1,
    "func-names": 1,
    "keyword-spacing": 1,
    "space-before-blocks": 1,
    "space-before-function-paren": [ 1, { "anonymous": "always", "named": "never" } ],
    "quotes": [ 1, "single", "avoid-escape" ],
    "no-multi-spaces": [ 1, { "exceptions": { "VariableDeclarator": true, "ImportDeclaration": true } } ],
    "dot-notation": 0,
    "prefer-template": 0,
    "max-len": [ 1, 250, 4, { "ignoreComments": true } ],
    "arrow-body-style": 0,
    "object-shorthand": 0,
    "no-case-declarations": 1,

    //
    // React:
    //
    "react/prop-types": 1,
    "react/jsx-uses-react": 2,
    "react/jsx-uses-vars": 2,
    "react/react-in-jsx-scope": 2,
    "react/jsx-quotes": 0,
    "react/no-multi-comp": 0,
    "react/sort-comp": 0,
    "react/jsx-closing-bracket-location": 1,
    "react/prefer-stateless-function": 1,
    "react/jsx-space-before-closing": 1,
    "jsx-quotes": 2,
    "jsx-a11y/img-uses-alt": 0,

    //
    // ES6:
    //
    "import/default": 0,
    "import/no-duplicates": 0,
    "import/named": 0,
    "import/namespace": 0,
    "import/no-unresolved": 0,
    "import/no-named-as-default": 2,
  },
  "plugins": [
    "react",
    "import"
  ],
  "settings": {
    "import/ignore": [
      "node_modules",
      "\\.(scss|less|css)$"
    ],
    "import/resolver": {
      "webpack": {
        "config": "./webpack/configForEslintImportResolver.js"
      }
    }
  },
  "globals": {
    "__DEVELOPMENT__": true,
    "__SERVER__": true,
    "__SERVER_DEVTOOLS__": true,
    "__SERVER_DISABLE_SERVERSIDE_RENDERING__": true,
    "__CLIENT__": true,
    "__CLIENT_DEVTOOLS__": true,
    "__LOCALHOST__": true,
    "__FAST_DEVELOPMENT__": true
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
```js
// snippet 1
const def = {};
const abc = [
  (''
  ),
  def,
];
def.abc = abc;
```
```js
// snippet 2
const def = {};
const abc = [
  (''),
  def,
];
def.abc = abc;
```
```js
// snippet 3
const def = {};
const abc = [
  '',
  def,
];
  def.abc = abc;
```
```js
// snippet 4
const def = {};
const abc = {
  x: (''
  ),
  def,
};
def.abc = abc;
```

**What did you expect to happen?**
Validation passes on all 4 snippets.

**What actually happened? Please include the actual, raw output from ESLint.**
```js
// snippet 1
const def = {};
const abc = [
  (''
  ),  // error: Bad line breaking before and after ','. (comma-style)
  def,
];
def.abc = abc;
```
Other snippets pass.

### PR DESCRIPTION
**Pull request by kaicataldo**
Checks to see if the token right before the comma is a closing parens and uses that token if it is. ~~Also updated the calls on the context object to the current API.~~ Didn't realize @alberto was doing the same thing - his PR was merged today so I just rebased.

### CODE REVIEW

File: lib/rules/comma-style.js [hunk 1]
```diff
@@ -39,7 +39,6 @@ module.exports = {
     },
 
     create: function(context) {
-
```
Comment (kaicataldo) [inline lib/rules/comma-style.js]: Consistent with var declaration spacing in other parts of the file

**Comment by btmills** [comment]
LGTM

**Comment by sompylasar** [comment]
@nzakas Thanks! 
- How do I know in which version this gets released, to update dependencies accordingly?
- Does this fix #6007 as well?

**Comment by alberto** [comment]
@sompylasar 
- It will be included in 2.10
- No
