### PR TITLE
Fix: Replace Infinity with Number.MAX_SAFE_INTEGER (fixes #13427)

### LINKED ISSUE #13427: Config clone before validating kills Object data (7.3.0)
* **ESLint Version: 7.3.0**

The latest update breaks [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md) and I believe some other eslint plugins due to configuration cloning by `JSON.parse(JSON.stringify(Object))`
related PR: https://github.com/eslint/eslint/pull/13034

Any plugin that use any global property like "Infinity" wont work properly.

`JSON.parse(JSON.stringify(Infinity)) => null`

Configuration example https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L236

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

When cloning a rule's config, if `Infinity` is found, it will be replaced with `Number.MAX_SAFE_INTEGER`. This should result in the same effective config while preserving serialization.

Note: This only fixes the issue introduced in v7.3.0. Configs using `Infinity` will still fail in other areas (like caching and `--print-config`).

We can remove this change once `eslint-config-airbnb` updates their config.

### CODE REVIEW

File: lib/cli-engine/config-array-factory.js [hunk 1]
```diff
@@ -722,7 +722,12 @@ class ConfigArrayFactory {
          *
          * Refer https://github.com/eslint/eslint/issues/12592
          */
-        const clonedRulesConfig = rules && JSON.parse(JSON.stringify((rules)));
+        const clonedRulesConfig = rules && JSON.parse(
+            JSON.stringify(
+                rules,
+                (key, value) => (value === Infinity ? Number.MAX_SAFE_INTEGER : value)
```
Comment (ljharb) [inline lib/cli-engine/config-array-factory.js:728]:
```suggestion
                (key, value) => (value === Infinity ? Number.MAX_SAFE_INTEGER : (value === -Infinity : -Number.MAX_SAFE_INTEGER : value))
```
just in case?

Comment (nzakas) [reply lib/cli-engine/config-array-factory.js:728]: I'd prefer not to add any further exceptions here. This fix is to carve out a narrow hole for `eslint-config-airbnb` to fit through without allowing other exceptions through.

Comment (ljharb) [reply lib/cli-engine/config-array-factory.js:728]: I suppose we can just wait for bug reports from enterprise users, which upgrade eslint much more slowly than open source users. Either way JSON-cloning is a breaking change, so if you'd prefer to gamble that it won't come up, that's fine ¯\\\_(ツ)_/¯

Comment (eaviles) [reply lib/cli-engine/config-array-factory.js:728]: Has anybody considered using something like https://github.com/codeandcats/fast-clone instead of JSON cloning?

Comment (eaviles) [reply lib/cli-engine/config-array-factory.js:728]: (actually: https://github.com/davidmarkclements/rfdc)

Comment (kaicataldo) [reply lib/cli-engine/config-array-factory.js:728]: @eaviles See https://github.com/eslint/eslint/pull/13034 for the original (long 😆) discussion.

Comment (eaviles) [reply lib/cli-engine/config-array-factory.js:728]: Oh wow… thanks for pointing me to this @kaicataldo

Comment (nzakas) [reply lib/cli-engine/config-array-factory.js:728]: Just as a reminder (and for posterity): ESLint has never formally supported JS special values in rule configs, which originated as JSON configs and are validated with JSON Schema. A validation bug let people use Infinity and we only learned of that after implementing this change. We don’t want to open the door to more people using special values in the meantime, which is why we are not reverting the original change.

If other bugs are filed, we will handle them on a case-by-case basis. Keep in mind that a large number of users use JSON or YAML config files, and this issue only affects JS config files.

**Comment by SSANSH** [comment]
tags 7.3.1 with following airbnb fix is not available on npm registry is it normal?
