### PR TITLE
Fix: no-multiple-empty-lines crash on space after last \n (fixes #8401)

### LINKED ISSUE #8401: Error Thrown: Line number out of range
**Tell us about your environment**

* **ESLint Version:** 3.19.0
* **Node Version:** 7.7.3
* **npm Version:** 4.4.4

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```
module.exports = {
    "extends": "standard",
    "plugins": [
        "standard",
        "promise"
    ]
};
```

**What did you do? Please include the actual source code causing the issue.**

```
eslint --fix */**
```

**What did you expect to happen?**
Successful execution.

**What actually happened? Please include the actual, raw output from ESLint.**
```
Line number out of range (line 318 requested, but only 317 lines present).
RangeError: Line number out of range (line 318 requested, but only 317 lines present).
    at SourceCode.getIndexFromLoc (/usr/local/lib/node_modules/eslint/lib/util/source-code.js:389:19)
    at Object.fix (/usr/local/lib/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:116:52)
    at RuleContext.report (/usr/local/lib/node_modules/eslint/lib/rule-context.js:127:34)
    at Program:exit.allLines.reduce.concat.reduce (/usr/local/lib/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:108:37)
    at Array.reduce (native)
    at EventEmitter.Program:exit (/usr/local/lib/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:93:22)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:294:22)
```

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/8401)

**What changes did you make? (Give an overview)**

Previously, no-multiple-empty-lines would crash if it tried to remove a trailing newline followed by a space from the end of a file. This commit fixes the crash.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: lib/rules/no-multiple-empty-lines.js [hunk 1]
```diff
@@ -111,10 +111,19 @@ module.exports = {
...
+                                    const rangeStart = sourceCode.getIndexFromLoc({ line: lastLineNumber + 1, column: 0 });
+
+                                    /*
+                                     * The end of the removal range is usually the start index of the next line.
+                                     * However, at the end of the file there is no next line, so the end of the
+                                     * range is just the length of the text.
+                                     */
+                                    const lineNumberAfterRemovedLines = lineNumber - maxAllowed;
+                                    const rangeEnd = lineNumberAfterRemovedLines <= allLines.length
+                                        ? sourceCode.getIndexFromLoc({ line: lineNumber - maxAllowed, column: 0 })
```
Comment (gyandeeps) [inline lib/rules/no-multiple-empty-lines.js]: nit: but u can use the variable `lineNumberAfterRemovedLines` here also.

Comment (not-an-aardvark) [inline lib/rules/no-multiple-empty-lines.js]: Oops, fixed.
