### PR TITLE
Fix: no-param-reassign false positive on destructuring (fixes #8279)

### LINKED ISSUE #8279: False positive of no-param-reassign on destruction assigment
**Tell us about your environment**

* **ESLint Version:** 3.18
* **Node Version:** 7.7.3

**What parser (default, Babel-ESLint, etc.) are you using?** default

**What did you do? Please include the actual source code causing the issue.**

```js
/* eslint no-param-reassign: ["error", {"props": true}] */

const { hasOwnProperty: has } = Object.prototype;
module.exports.hasDeepProperty = (obj, propertyPath) => {
  if (!obj) return false;

  const properties = propertyPath.split('.');
  let o = obj;
  return !properties.some((propertyName) => {
    if (!has.call(o, propertyName)) return true;
    ({ [propertyName]: o } = o);
    return false;
  });
};
```

**What did you expect to happen?**
Nothing, no errors

**What actually happened? Please include the actual, raw output from ESLint.**
`no-param-reassign` thinks I'm reassigning `propertyName` at destruction

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/8279)

**What changes did you make? (Give an overview)**

This updates no-param-reassign to stop traversing up the AST if it encounters a Property node where the variable reference is part of the key.

This fix keeps the general strategy of the rule in place. However, while I haven't investigated it in depth, the rule strategy seems a bit fragile -- it reports any reference to a variable on the left side of an assignment, excluding some specific cases such as computed properties. It's possible there are more cases like this that cause false positives -- if so, we might want to rethink how this rule is implemented.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: tests/lib/rules/no-param-reassign.js [hunk 1]
```diff
@@ -82,6 +87,12 @@ ruleTester.run("no-param-reassign", rule, {
             parserOptions: { ecmaVersion: 6 },
             options: [{ props: true, ignorePropertyModificationsFor: ["a"] }],
             errors: [{ message: "Assignment to property of function parameter 'bar'." }]
+        },
+        {
+            code: "function foo(bar) { ({foo: bar.a} = {}); }",
+            parserOptions: { ecmaVersion: 6 },
+            options: [{ props: true }],
+            errors: [{ message: "Assignment to property of function parameter 'bar'." }]
         }
```
Comment (mysticatea) [inline tests/lib/rules/no-param-reassign.js]: I'd like to see the test `function foo(a) { ({a} = obj); }` as invalid.
