### PR TITLE
Update: fix no-self-compare false negative on non-literals (fixes #7677)

### LINKED ISSUE #7677: `no-self-compare` does not handle complex expressions correctly
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 7.2.0
* **npm Version:** 3.10.9

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

(none)

**What did you do? Please include the actual source code causing the issue.**

```js
/* eslint no-self-compare: error */

foo.bar === foo.bar;
```

**What did you expect to happen?**

I expected ESLint to report an error for the self-comparison.

**What actually happened? Please include the actual, raw output from ESLint.**

No errors were reported.

I'm marking this as "evaluating" since I'm not sure whether it's intended behavior.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/7677)

**What changes did you make? (Give an overview)**

Previously, the `no-self-compare` rule would only check comparisons between identifiers and did not check comparisons between more complex expressions. (I assume this is because the APIs that would allow comparing complex expressions didn't exist yet at the time the rule was implemented.) The rule is still applicable to non-literals, so this commit updates the rule to check comparisons that aren't between literals.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: tests/lib/rules/no-self-compare.js [hunk 1]
```diff
@@ -21,10 +21,9 @@ const ruleTester = new RuleTester();
 ruleTester.run("no-self-compare", rule, {
     valid: [
         "if (x === y) { }",
-        "if (f() === f()) { }",
-        "if (a[1] === a[1]) { }",
```
Comment (not-an-aardvark) [inline tests/lib/rules/no-self-compare.js]: These tests were added in https://github.com/eslint/eslint/commit/fdcabe5da38bf44f7b6b4a1fc73b5d3007e6e911. It looks like they were intended to address the bug described in https://github.com/eslint/eslint/pull/160#r5439185, which is a separate case from what this issue addresses.
