### PR TITLE
Fix: indent bug with AssignmentExpressions (fixes #7747)

### LINKED ISSUE #7747: indent rule can break on arrayExpression inside a CallExpression
* **ESLint Version:** 3.12.0
* **Node Version:** 7.2.1
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
no configuration

```




```

**What did you do? Please include the actual source code causing the issue.**

Running this:

```sh
eslint --no-eslintrc --rule='indent: [2, 2, {CallExpression: {arguments: first}, ArrayExpression: first}]' test.js
```

on file `test.js`:

```js
echo = spawn('cmd.exe',
             ['/c', 'echo', 'hello&&', 'echo',
              'node&&', 'echo', 'and&&', 'echo', 'world']);





```

**What did you expect to happen?**

No error

**What actually happened? Please include the actual, raw output from ESLint.**

```console
/Users/trott/test/test.js
  2:14  error  Expected indentation of 2 spaces but found 13  indent

✖ 1 problem (1 error, 0 warnings)
```

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix

**What changes did you make? (Give an overview)**

This updates `indent` to apply array/object offsets even when they don't have a VariableDeclarator parent.

**Is there anything you'd like reviewers to focus on?**

This builds off of https://github.com/eslint/eslint/pull/7734, so it should not be merged until that PR is merged. Since this bug is not a regression, it might be better to do a patch release with only https://github.com/eslint/eslint/pull/7734 rather than rushing this PR.

### CODE REVIEW

**Comment by platinumazure** [comment]
@not-an-aardvark I was going to label this but I'm not sure what to label it as since this is a "maybe patch candidate". When you get a chance, could you please label this PR?

**Comment by not-an-aardvark** [comment]
Labeled, sorry about that. To clarify, this is a patch candidate, but I don't think we should include it in today's patch release.

**Comment by platinumazure** [comment]
@not-an-aardvark Should we add "do not merge" in that case, to avoid accidental merge before today's patch release? (This isn't really covered in our maintainer guidelines, but I think "patch candidate" + "do not merge" will help flag that it should go in *a* patch release, just not *this* patch release.)

File: lib/rules/indent.js [hunk 1]
```diff
@@ -722,23 +722,39 @@ module.exports = {
                 const parent = node.parent;
 
                 nodeIndent = getNodeIndent(parent).goodChar;
-                if (parentVarNode && parentVarNode.loc.start.line !== node.loc.start.line) {
+                if (!parentVarNode || parentVarNode.loc.start.line !== node.loc.start.line) {
```
Comment (not-an-aardvark) [inline lib/rules/indent.js]: Previously, the `if` statement only applied if there was `VariableDeclarator` parent that started on a different line. For example, the first line of the following array should be indented:

```js
var foo =
    [
        1
    ];
```

But the following array should not be indented:

```js
var foo = [
    1
];
```

However, the result of this was that the rule would not add other necessary indentation (e.g. in `CallExpression` nodes) if it didn't have a `VariableDeclarator` parent. Since the `if` statement immediately below this one explicitly handles the `VariableDeclarator` case, it's not necessary for this check to be so strict.
