### PR TITLE
Fix: `no-unused-vars` false positive in loop (fixes #6646)

### LINKED ISSUE #6646: no-unused-vars confused when var is re-assigned with return value of function that takes it as argument
> **What version of ESLint are you using?**

3.0.1

> **What parser (default, Babel-ESLint, etc.) are you using?**

default

> **Please show your full configuration:**

https://github.com/openlayers/eslint-config-openlayers/blob/master/index.js

> **What did you do? Please include the actual source code causing the issue.**

https://github.com/openlayers/ol3/blob/9b3c4294c146dd929ecd4c8c0188dfc01580e30c/src/ol/render/canvas/canvasreplay.js#L1085-L1090

> **What did you expect to happen?**

Like in v2.x, I would expect that eslint does not complain, since `offset` is clearly used.

> **What actually happened? Please include the actual, raw output from ESLint.**

eslint complains about `offset` being defined but never used:
```
/home/travis/build/openlayers/ol3/src/ol/render/canvas/canvasreplay.js
  1085:7  error  'offset' is defined but never used  no-unused-vars
  1357:7  error  'offset' is defined but never used  no-unused-vars
```

This problem came up in openlayers/ol3#5569.

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #6646.

`no-unused-vars` comes to mark (as used) self-modification inside of a loop because the reference inside of a loop can be used in the next iteration.

### CODE REVIEW

File: lib/rules/no-unused-vars.js [hunk 1]
```diff
@@ -156,6 +158,27 @@ module.exports = {
         }
 
         /**
+         * Checks whether a given node is inside of a loop or not.
+         *
+         * @param {ASTNode} node - A node to check.
+         * @returns {boolean} `true` if the node is inside of a loop.
```
Comment (markelog) [inline lib/rules/no-unused-vars.js]: `@private` is missing

File: tests/lib/rules/no-unused-vars.js [hunk 2]
```diff
@@ -199,7 +199,20 @@ ruleTester.run("no-unused-vars", rule, {
         {code: "function foo(cb) { cb = function() { function something(a) { cb(1 + a); } register(something); }(); } foo();"},
         {code: "function* foo(cb) { cb = yield function(a) { cb(1 + a); }; } foo();", parserOptions: {ecmaVersion: 6}},
         {code: "function foo(cb) { cb = tag`hello${function(a) { cb(1 + a); }}`; } foo();", parserOptions: {ecmaVersion: 6}},
-        {code: "function foo(cb) { var b; cb = b = function(a) { cb(1 + a); }; b(); } foo();"}
+        {code: "function foo(cb) { var b; cb = b = function(a) { cb(1 + a); }; b(); } foo();"},
+
+        // https://github.com/eslint/eslint/issues/6646
+        {
+            code: [
+                "function someFunction() {",
```
Comment (markelog) [inline tests/lib/rules/no-unused-vars.js]: You now can use backticks right?

Comment (mysticatea) [inline tests/lib/rules/no-unused-vars.js]: #6570 have not been merged yet, so our `.eslintrc` is still es5. :)

File: lib/rules/no-unused-vars.js (hunk 1 above)
Comment (mysticatea) [inline lib/rules/no-unused-vars.js]: Oh, thank you!

File: lib/rules/no-unused-vars.js [hunk 3]
```diff
@@ -97,6 +97,8 @@ module.exports = {
         //--------------------------------------------------------------------------
 
         var STATEMENT_TYPE = /(?:Statement|Declaration)$/;
+        var LOOP_TYPE = /^(?:DoWhile|For|ForIn|ForOf|While)Statement$/;
```
Comment (markelog) [inline lib/rules/no-unused-vars.js]: Seems this kinda thing is needed among the rules, like - 

https://github.com/eslint/eslint/blob/b837c92cb239bbc90007118569c103c4d78c0235/lib/rules/indent.js#L616
https://github.com/eslint/eslint/blob/b837c92cb239bbc90007118569c103c4d78c0235/lib/rules/no-unmodified-loop-condition.js#L22
and so on

Can we move it in one place?

Comment (mysticatea) [inline lib/rules/no-unused-vars.js]: Right.

maybe `isLoop(node)` and `isFunction(node)` of `lib/ast-utils.js`.

Comment (markelog) [inline lib/rules/no-unused-vars.js]: Could work, but probably more appropriate to do this in the separate pr

File: lib/rules/no-unused-vars.js [hunk 4]
```diff
@@ -97,6 +97,8 @@ module.exports = {
...
+        var FUNCTION_TYPE = /^(?:Function(?:Expression|Statement)|ArrowFunctionExpression)$/;
```
Comment (mysticatea) [inline lib/rules/no-unused-vars.js]: I found `FunctionStatement` is wrong :D

File: lib/ast-utils.js [hunk 5]
```diff
@@ -551,5 +552,37 @@ module.exports = {
...
+     * - ForInStatement
+     * - ForOfStatement
+     * - ForStatement
+     * - WhileStatement
+     *
+     * @param {ASTNode|null} node - A node to check.
+     * @returns {boolean} `true` if the node is a loop node.
+     */
+    isLoopNode: function(node) {
+        return Boolean(node && anyLoopPattern.test(node.type));
```
Comment (markelog) [inline lib/ast-utils.js]: Probably worth to add tests for such methods?

Comment (mysticatea) [inline lib/ast-utils.js]: oops, I will add tomorrow (JST)

2016年7月11日(月) 22:05 Oleg Gaidarenko <notifications@github.com>:

Comment (mysticatea) [inline lib/ast-utils.js]: I added it.

Comment (nzakas) [inline lib/ast-utils.js]: Maybe just `isLoop`? (Not sure "node" is necessary)

File: lib/ast-utils.js [hunk 6]
```diff
@@ -551,5 +552,37 @@ module.exports = {
...
+     * The following types are function nodes:
+     *
+     * - ArrowFunctionExpression
+     * - FunctionDeclaration
+     * - FunctionExpression
+     *
+     * @param {ASTNode|null} node - A node to check.
+     * @returns {boolean} `true` if the node is a function node.
+     */
+    isFunctionNode: function(node) {
```
Comment (nzakas) [inline lib/ast-utils.js]: Maybe just `isFunction`?

**Comment by mysticatea** [comment]
I renamed those :pencil: :

- `isFunctionNode` → `isFunction`
- `isLoopNode` → `isLoop`

**Comment by markelog** [comment]
I would do this in two steps - one for #6646 and other for `ast-utils` module, but if this is acceptable practise then LGTM
