### PR TITLE
Fix: Return statement spacing. Fix for indent rule. (fixes #7164)

### LINKED ISSUE #7164: Return statement closing bracket position is not linted by indent rule
**Tell us about your environment**

* **ESLint Version: master, 3.5.0 the latest at this moment**
* **Node Version: v6.2.1**
* **npm Version: 3.9.3**

* **parser: default**

Code to test:

```js
function() {
  return (
     1
    );
}
```

Issue:
position of ");" is off by 2 extra spaces, but linter didn't raise an error

Raw output:
```
1 failing

  1) indent invalid function foo() {
  return (
    1
    );
}:

      AssertionError: Should have 1 error but had 0: []
      + expected - actual

      -0
      +1
```

### PR DESCRIPTION
**Pull request by eelyafi**
Fix: Return statement spacing. Fix for indent rule. (fixes: #7164)

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Please check each item to ensure your pull request is ready:**

- [X] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [X] I've included tests for my change
- [x] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**
indent rule won't check return statement spacing. Here is failing example:
```
function() {
  return (
     1
    );
}
```
More details in the issue #7164
**Is there anything you'd like reviewers to focus on?**
It's little bit tricky to check whether a statement ends with ')' or ');'. I had to create a new function named checkLastReturnStatementLineIndent in order to traverse back to the very first token. Also, I had to add a parameter in report function. lastNodeCheckEndOffset is an offset in case if a statement end with ');'. Please let me know if you have better ideas how to do this.

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks for the fix!

However, I think it's not just `return` statements that are affected by this issue; it's all nodes that are surrounded by multiline parens:

```js
var foo = (
  bar
             ); // this should also report an error
```

**Comment by eelyafi** [comment]
Is there a way to detect multiline parenthesis ?

**Comment by not-an-aardvark** [comment]
It's possible to detect, but I don't think there's a specific node for it (like there is with `ReturnStatement`). 

Instead, I think it would be possible to use the `byLastLine` parameter for [`getNodeIndent`](https://github.com/eelyafi/eslint/blob/cd0a55e8870a72436ec6ed09cd7b8fdf36ebcaf7/lib/rules/indent.js#L261).

**Comment by eelyafi** [comment]
@not-an-aardvark how should I use it ? 
In order to check return statement I've added a method ReturnStatement. In order to check all cases with multiline parenthesis where I should use getNodeIndent ?

**Comment by not-an-aardvark** [comment]
Unfortunately I'm not sure of all the specifics, since I haven't tried implementing it myself yet.

However, you might want to take a look at how `BlockStatement` indentation is currently checked; it seems a bit similar to the desired behavior here.

```js
if (foo) {
  // code
} // <-- This curly bracket needs to be at the same level as the `if` statement.
```

```js
var foo = (
  bar
); // <-- this closing paren needs to be at the same level as the `var` declaration.
```

**Comment by eelyafi** [comment]
@not-an-aardvark, I'm not sure how to catch '()' statements. 
This PR will address most of use cases. If there is some value in the PR and you guys think it's worth merging it then I can leave comments for future development to address cases like 
```
var foo = (
  bar
); // <-- this closing paren needs to be at the same level as the `var` declaration.
```
and let's merge it. Otherwise I'm not sure how to catch these cases

**Comment by not-an-aardvark** [comment]
Fair enough. (In case it wasn't clear, I'm not actually on the ESLint team, so that decision would be up to them. I was just trying to help out with the PR since I've done some work on the `indent` rule in the past.)

**Comment by ilyavolodin** [comment]
@BYK @gyandeeps Could you review and make a suggestion if this should be merged as is?

File: lib/rules/eqeqeq.js [hunk 1]
```diff
@@ -98,8 +98,9 @@ module.exports = {
          * @private
          */
         function isNullCheck(node) {
-            return (node.right.type === "Literal" && node.right.value === null) ||
```
Comment (gyandeeps) [inline lib/rules/eqeqeq.js]: Why is this change needed?
I fear that this bug fix will create issues of people based on this line

Comment (eelyafi) [inline lib/rules/eqeqeq.js]: the linter flagged it. If everything else looks good then I can follow up on that and fix this case.

Comment (eelyafi) [inline lib/rules/eqeqeq.js]: @gyandeeps ping

Comment (gyandeeps) [inline lib/rules/eqeqeq.js]: otherwise LGTM. Sorry for the delay.

**Comment by ilyavolodin** [comment]
@eelyafi Could you rebase please? Some other fixes were merged into indent rule. Sorry about that.

**Comment by eelyafi** [comment]
@ilyavolodin, no worries, rebased

**Comment by eelyafi** [comment]
@gyandeeps addressed the comments

**Comment by gyandeeps** [comment]
So currently if you have a `)` on the same line as some other code, it will require you to put it on the new line.

```js
return (
    a);
```
becomes
```js
return (
    a
);
```

But if the opening `(` is on the same line it doesnt require you to move the code to the next line, is that correct?

```js
// what happens in this case ?
return ( a
);
```

File: lib/rules/yoda.js [hunk 2]
```diff
@@ -209,7 +212,8 @@ module.exports = {
                 return ((tokenBefore = sourceCode.getTokenBefore(node)) &&
                     tokenBefore.value === "(" &&
                     (tokenAfter = sourceCode.getTokenAfter(node)) &&
-                    tokenAfter.value === ")");
+                    tokenAfter.value === ")"
```
Comment (not-an-aardvark) [inline lib/rules/yoda.js]: I'm a bit worried about this side-effect. Having a paren after the statement is valid indentation, and we will probably break peoples' builds if we report it as an issue. We should be sure to fix this before we merge this PR.

(This was also mentioned [here](https://github.com/eslint/eslint/pull/7197#pullrequestreview-1375065). I'm leaving this review to make sure we don't forget about it and merge the PR without fixing this.)

**Comment by eelyafi** [comment]
@not-an-aardvark sorry for skipping lib/rules/yoda.js 
It's hard to go through newly added commits in PR before pushing it. Is there a way to run something similar to `arc diff --only` in Phabricator ? 

Added a commit to my PR. It'll consider both of these cases as legit:
```
return ((bar === 1 || bar === 2) &&
  (z === 3 || z === 4)
);
```
```
return ((bar === 1 || bar === 2) &&
  (z === 3 || z === 4));
```

**Comment by not-an-aardvark** [comment]
@eelyafi Thanks! To answer your question, you can view the changes from a specific commit by starting at the ["Files changed" tab](https://github.com/eslint/eslint/pull/7197/files), then clicking the dropdown that says "all commits" and selecting a specific commit to view.

I'll take a look at the latest commit and let you know if there's anything else to change.

**Comment by eelyafi** [comment]
@not-an-aardvark  thanks ! Actually I used this tab many times. My question was how to view the changes before pushing them. Basically, before they'll appear under ["Files Changed tab"](https://github.com/eslint/eslint/pull/7197/files). Would be great to see the changes in a nice way, not in the terminal.

File: lib/rules/indent.js [hunk 3]
```diff
@@ -375,12 +376,25 @@ module.exports = {
...
-            if ((endIndent.goodChar !== lastLineIndent || endIndent.badChar !== 0) && isNodeFirstInLine(node)) {
+            /* we consider both of these cases legit:
+                return ((bar === 1 || bar === 2) &&
+                  (z === 3 || z === 4)
+                );
+                return ((bar === 1 || bar === 2) &&
+                  (z === 3 || z === 4));
+              */
+            if ((((endIndent.goodChar !== firstLineIndent && !textLenWithoutIndentation)
+                    || (textLenWithoutIndentation && endIndent.goodChar !== lastLineIndent))
```
Comment (not-an-aardvark) [inline lib/rules/indent.js]: This line seems redundant to me. `endIndent.goodChar` and `lastLineIndent` are both obtained by calling `getNodeIndent` on the last line of `node`, so I think `endIndent.goodChar !== lastLineIndent` will always be false. I think this check can simply be removed; the important thing is that the node is only reported if `)` is the first token in the line.

File: lib/rules/indent.js [hunk 4]
```diff
@@ -375,12 +376,25 @@ module.exports = {
                 lastToken = sourceCode.getTokenBefore(lastToken);
             }
 
+            const textBeforeClosingParenthesis = sourceCode.getText(lastToken, lastToken.loc.start.column).slice(0, -1);
+            const indentChar = indentType === "space" ? " " : "\t";
+            const replaceRegExp = new RegExp(indentChar, "g");
+            const textLenWithoutIndentation = textBeforeClosingParenthesis.replace(replaceRegExp, "").length;
```
Comment (not-an-aardvark) [inline lib/rules/indent.js]: Since we only care about whether `textBeforeClosingParenthesis` contains any non-whitespace characters, I think this logic can be simplified to just compare `textBeforeClosingParenthesis.trim()` to the empty string. For example:

```js
if (textBeforeClosingParenthesis.trim()) {

  // There are tokens before the closing paren, don't report this case
  return;
}
```

File: lib/rules/indent.js (hunk 3 above)
Comment (eelyafi) [inline lib/rules/indent.js]: @not-an-aardvark It looks like the rule works fine when if statement is:
`if (endIndent.goodChar !== firstLineIndent) {`
not sure how though :)

Comment (not-an-aardvark) [inline lib/rules/indent.js]: I think we could replace the check with:

```js
if (!sourceCode.getText().slice(lastToken.range[0] - lastToken.loc.start.column, lastToken.range[0]).trim()) {
  // report node
}
```

This will make sure that we only report the `)` token if it is first in the line (i.e. there are no other tokens before `)` that are on the same line).

Comment (eelyafi) [inline lib/rules/indent.js]: @not-an-aardvark the if statement failed one test:
```
  return ((bar === 1 || bar === 2) &&
    (z === 3 || z === 4)
  );
```

I think I will go with 
```
if (textBeforeClosingParenthesis.trim()) {
   // There are tokens before the closing paren, don't report this case
  return;
}
```
+
```
if (endIndent.goodChar !== firstLineIndent) {
  //report
}
```

**Comment by eelyafi** [comment]
ready to merge ?

**Comment by ilyavolodin** [comment]
Yes. Thanks @eelyafi for sticking with this!
