### PR TITLE
fix: Only pass node to JS lang visitor methods

### LINKED ISSUE #20272: Bug: Issues with `unified-signatures`
### Environment

Node version: v22.14.0
npm version: 11.5.2
Local ESLint version: 9.39.0
Global ESLint version: 9.39.0
Operating System: MacOS 15.7.1

### What parser are you using?

Default (Espree)

### package.json

```json
{
  "scripts": {
    "lint": "eslint src"
  },
  "devDependencies": {
    "@eslint/js": "9.39.0",
    "typescript": "5.9.3",
    "typescript-eslint": "8.46.2"
  }
}
```

### eslint.config.mjs

```js
import { defineConfig } from 'eslint/config';
import tseslint from 'typescript-eslint';

export default defineConfig(tseslint.configs.strict);
```

---

## Example 1: `./src/cannot-read.ts`

```ts
export const test: Record<string, { id: number }> = {
    alpha: { id: 1 },
    bravo: { id: 2 },
    charlie: { id: 3 },
}
```

Execute `npm run lint` and this is the error (ellipses to paraphrase):

```
Oops! Something went wrong! :(

ESLint: 9.39.0

TypeError: Cannot read properties of undefined (reading 'name')
Occurred while linting /.../src/cannot-read.ts:1
Rule: "@typescript-eslint/unified-signatures"
    at getIsTypeParameter...
```

## Example 2: `./src/not-iterable.ts`

```ts
export function wrap<T>(items: T[]): { item: T } {
    return { item: items[0] };
}
```

Execute `npm run lint` and this is the error (ellipses to paraphrase):

```
Oops! Something went wrong! :(

ESLint: 9.39.0

TypeError: typeParameters.params is not iterable
Occurred while linting /.../src/not-iterable.ts:1
Rule: "@typescript-eslint/unified-signatures"
    at getIsTypeParameter...
```

### What did you expect to happen?

I don't see any errors with the example codes, so I don't think eslint should generate an error. This only happened after upgrading to 9.39.0. Version 9.38.0 worked just fine so I think something in the update is broken.

### What actually happened?

See above.

### Link to Minimal Reproducible Example

Reproduction shown above.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Switched the JS language so it only passes one argument to visitor methods. This restores the previous behavior.

I also added tests to verify this behavior as we didn't have any such tests before.

fixes #20272
refs #20253

### CODE REVIEW

File: lib/languages/js/source-code/source-code.js [hunk 1]
```diff
@@ -1303,7 +1303,7 @@ class SourceCode extends TokenStore {
 					new VisitNodeStep({
 						target: node,
 						phase: 1,
-						args: [node, node.parent],
+						args: [node],
```
Comment (mdjermanovic) [inline lib/languages/js/source-code/source-code.js:1306]: Technically, this is breaking change since [`SourceCode` is public API](https://github.com/eslint/eslint/blob/61778f6ca33c0f63962a91d6a75a4fa5db9f47d2/lib/api.js#L49) and `traverse()` is a public method, though it's unlikely that it is used by anyone aside from ESLint core.

File: tests/lib/languages/js/source-code/source-code.js [hunk 2]
```diff
@@ -4817,4 +4817,355 @@ describe("SourceCode", () => {
...
+					`${nodeType} should have enter phase`,
+				);
+				assert.isTrue(
+					phases.includes(2),
+					`${nodeType} should have exit phase`,
+				);
+			});
+		});
+
+		it("should include parent reference in step args", () => {
```
Comment (mdjermanovic) [inline tests/lib/languages/js/source-code/source-code.js:4888]: Isn't it that it should _not_ include parent reference in step args?

File: tests/lib/languages/js/source-code/source-code.js [hunk 3]
```diff
@@ -4817,4 +4817,355 @@ describe("SourceCode", () => {
...
+			const code = "var foo = 1;";
+			const ast = espree.parse(code, DEFAULT_CONFIG);
+			const sourceCode = new SourceCode(code, ast);
+			const steps = sourceCode.traverse();
+
+			const visitSteps = steps.filter(step => step.kind === 1);
+
+			assert.strictEqual(visitSteps.length, 10);
+
+			// Every visit step should have exactly 2 arguments
```
Comment (mdjermanovic) [inline tests/lib/languages/js/source-code/source-code.js:5092]:
```suggestion
			// Every visit step should have exactly 1 argument
```

File: lib/languages/js/source-code/source-code.js (hunk 1 above)
Comment (fasttime) [reply lib/languages/js/source-code/source-code.js:1306]: I'm not sure. The documentation only says that the steps should implement the `VisitTraversalStep` or `CallTraversalStep` interface, which they do. I guess the exact contents of those structures are implementation details?

https://github.com/eslint/eslint/blob/b0674be94e4394401b4f668453a473572c321023/docs/src/extend/languages.md?plain=1#L48

File: tests/lib/languages/js/source-code/source-code.js [hunk 4]
```diff
@@ -4817,4 +4817,355 @@ describe("SourceCode", () => {
...
+				// First argument should be the node itself
+				assert.strictEqual(
+					node,
+					step.target,
+					`First argument should be the node (${step.target.type})`,
+				);
+			});
+		});
+
+		it("should provide parent as the actual parent node in the AST", () => {
```
Comment (mdjermanovic) [inline tests/lib/languages/js/source-code/source-code.js:5124]: This test also doesn't seem applicable as steps don't provide `parent`.

File: tests/lib/languages/js/source-code/source-code.js (hunk 3 above)
Comment (fasttime) [reply tests/lib/languages/js/source-code/source-code.js:5092]: The next test case already checks that each visit step has the node as its only argument:

https://github.com/eslint/eslint/blob/c8c462192b65741c57112d047809f75021efdf97/tests/lib/languages/js/source-code/source-code.js#L5102-L5122

File: lib/languages/js/source-code/source-code.js (hunk 1 above)
Comment (mdjermanovic) [reply lib/languages/js/source-code/source-code.js:1306]: It would still satisfy the interface required by ESLint, but for other direct consumers of this method this would be a breaking change in behavior because this particular implementation was returning the parent as `args[1]`.

If we don't think there are any other direct consumers of this method (i.e., only ESLint is using `SourceCode#traverse()`), then it's fine.

Comment (JoshuaKGoldberg) [reply lib/languages/js/source-code/source-code.js:1306]: FWIW typescript-eslint doesn't use it. I've searched around to try to find other consumers and the only usage I could find after a few minutes was [TSSLint, which passes no parameters](https://sourcegraph.com/github.com/johnsoncodehk/tsslint/-/blob/packages/eslint/index.ts?L552).

**Review by JoshuaKGoldberg — APPROVED** [review]
Modulo the comments around tests, this looks good to me 👍 thanks for hopping on this!

**Review by fasttime — APPROVED** [review]
LGTM, thanks! We should fix the unit tests in a follow-up PR and monitor the patch release for any problems related to the change in `VisitNodeStep`.
