### PR TITLE
Fix: Make MemberExpression option opt-in (fixes #6797)

### LINKED ISSUE #6797: MemberExpression option is currently breaking builds, needs to be made opt-in
**What version of ESLint are you using?**

3.2.0

**What parser (default, Babel-ESLint, etc.) are you using?**

n/a

**Please show your full configuration:**

n/a 

**What did you do? Please include the actual source code causing the issue.**

Code like this used to pass:

```
foo
  .bar
.baz;
```

Now it throws an error because the new `MemberExpression` option of `indent` is not opt-in

**What did you expect to happen?**

Code that wasn't broken would remain unbroken

**What actually happened? Please include the actual, raw output from ESLint.**

### PR DESCRIPTION
**Pull request by Trott**
**What issue does this pull request address?**

https://github.com/eslint/eslint/issues/6797

**What changes did you make? (Give an overview)**

Turn `MemberExpression` option of the `indent` rule to be off by default.

**Is there anything you'd like reviewers to focus on?**

The `MemberExpression` option should be opt-in as it is a breaking
change.

### CODE REVIEW

**Comment by markelog** [comment]
LGTM

**Comment by markelog** [comment]
But this should be for https://github.com/eslint/eslint/issues/6795? If I understand you correctly

**Comment by Trott** [comment]
Fix for 6795 is "ignore assignment statements". Fix for 6797 is "make it
opt in". These are not mutually exclusive fixes. I recommend doing both.

**Comment by markelog** [comment]
But both PRs are sent to fix one "breaking change", but okay, I understand the logic behind it

File: lib/rules/indent.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ module.exports = {
                 const: DEFAULT_VARIABLE_INDENT
             },
             outerIIFEBody: null,
-            MemberExpression: 1
+            MemberExpression: null
```
Comment (nzakas) [inline lib/rules/indent.js]: We like to keep options as all the same data type, so `null` isn't appropriate for this.

File: lib/rules/indent.js [hunk 2]
```diff
@@ -809,6 +809,10 @@ module.exports = {
             },
 
             MemberExpression: function(node) {
+                if (options.MemberExpression === null) {
```
Comment (nzakas) [inline lib/rules/indent.js]: Rather than checking for a null value, you can  check

```
if ("MemberExpression" in context.options[1]) {
```

**Comment by nzakas** [comment]
@Trott I appreciate the diligence, but it's confusing having two issues. Let's refocus on #6795 and add all relevant information there.

File: lib/rules/indent.js (hunk 1 above)
Comment (Trott) [inline lib/rules/indent.js]: Would `-1` be appropriate?

File: lib/rules/indent.js (hunk 2 above)
Comment (Trott) [inline lib/rules/indent.js]: If I do that, I have to do it like this:

    if (!context.options[1] || !("MemberExpression" in context.options[1])) {

Any reason not to go with this simpler formulation?:

    if (options.MemberExpression === undefined) {

Or, if you want to be more careful?:

    if (typeof options.MemberExpression === 'undefined') {

**Comment by Trott** [comment]
Comment from @nzakas addressed (I think), commit squashed, branch force pushed.

**Comment by nzakas** [comment]
Lgtm, just waiting to let others review.

**Comment by gyandeeps** [comment]
LGTM, waiting for others to review.

File: lib/rules/indent.js (hunk 1 above)
Comment (markelog) [inline lib/rules/indent.js]: @nzakas why there is a `null` value for `outerIIFEBody`? Should we change that too in another PR?

File: tests/lib/rules/indent.js [hunk 3]
```diff
@@ -1428,7 +1441,7 @@ ruleTester.run("indent", rule, {
         {
             code: fixture,
             output: fixedFixture,
-            options: [2, {SwitchCase: 1}],
+            options: [2, {SwitchCase: 1, MemberExpression: 1}],
```
Comment (markelog) [inline tests/lib/rules/indent.js]: Why there is sometimes spaces after `{`/`}` and sometimes not? 
--
This remark shouldn't block this PR

**Comment by markelog** [comment]
We usually need two "LGTM" right?

LGTM

File: tests/lib/rules/indent.js (hunk 3 above)
Comment (Trott) [inline tests/lib/rules/indent.js]: This inconsistency seems to exist throughout the file.

For example, `SwitchCase` without a space happens on lines [266](https://github.com/eslint/eslint/blob/288f7bf47279076e6b3f05814ebec3f6b7e5aeb6/tests/lib/rules/indent.js#L266), [537](https://github.com/eslint/eslint/blob/288f7bf47279076e6b3f05814ebec3f6b7e5aeb6/tests/lib/rules/indent.js#L537), [542](https://github.com/eslint/eslint/blob/288f7bf47279076e6b3f05814ebec3f6b7e5aeb6/tests/lib/rules/indent.js#L542), and ten additional places.

 But `SwitchCase` with a space occurs in lines [776](https://github.com/eslint/eslint/blob/288f7bf47279076e6b3f05814ebec3f6b7e5aeb6/tests/lib/rules/indent.js#L776) and [1897](https://github.com/eslint/eslint/blob/288f7bf47279076e6b3f05814ebec3f6b7e5aeb6/tests/lib/rules/indent.js#L1897).

If the inconsistency is something that should be fixed eventually, maybe I can leave as is for this PR and I or someone else can open up a separate issue about this? Might be a good one to apply the `beginner` label to.

Comment (platinumazure) [inline tests/lib/rules/indent.js]: The style guide seems to prefer object literals never being on one line in the first place, and so doesn't express an opinion about spaces after curly braces. I'll create an issue asking for clarification on that point. It might be that we can enable `object-curly-spacing` in this repository if we can reach consensus.

Comment (markelog) [inline tests/lib/rules/indent.js]: hm, could one of you create an issue about it? I think it would be good if our code should be as consistent as possible so it could be kinda of an example how things should look like?
