### PR TITLE
fix: ignore messages without a `ruleId` in `getRulesMetaForResults`

### LINKED ISSUE #16402: Bug: `FlatESLint` `getRulesMetaForResults` fails on messages without a `ruleId`
### Environment

Node version: v18.10.0
npm version: v8.19.2
Local ESLint version: v8.25.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 21.6.0

### What parser are you using?

Default (Espree)

### What did you do?

I was running some unit tests for a custom formatter against the new flat config API, and I noticed that `getRulesMetaForResults` is now throwing a `TypeError` for results that contain messages without a `ruleId`.

I found this to be the case for parser errors, for messages about unused `eslint-disable` directives and for warnings about ignored files. There could be other cases, too - my tests are not exhaustive.

#### Example 1: Parser error
```js
const { default: { FlatESLint } } = await import('eslint/use-at-your-own-risk');

const eslint = new FlatESLint({ overrideConfigFile: true });
const results = await eslint.lintText('syntax error');
eslint.getRulesMetaForResults(results); // throws TypeError
```

#### Example 2: Unused `eslint-disable` directive
```js
const { default: { FlatESLint } } = await import('eslint/use-at-your-own-risk');

const eslint = new FlatESLint({ overrideConfigFile: true, reportUnusedDisableDirectives: 'warn' });
const results = await eslint.lintText('// eslint-disable-line');
eslint.getRulesMetaForResults(results); // throws TypeError
```

#### Example 3: Ignored file
```js
const { default: { FlatESLint } } = await import('eslint/use-at-your-own-risk');

const eslint = new FlatESLint({ overrideConfigFile: true });
const results = await eslint.lintText('', { filePath: '/.ignored.js', warnIgnored: true });
eslint.getRulesMetaForResults(results); // throws TypeError
```

### What did you expect to happen?

`getRulesMetaForResults` should run without errors.

### What actually happened?

A `TypeError` was thrown (the same for all examples):

<pre>
.../node_modules/eslint/lib/config/flat-config-helpers.js:22
    if (ruleId.includes("/")) {
               ^

TypeError: Cannot read properties of null (reading 'includes')
    at parseRuleId (...node_modules/eslint/lib/config/flat-config-helpers.js:22:16)
    at getRuleFromConfig (.../node_modules/eslint/lib/config/flat-config-helpers.js:52:38)
    at FlatESLint.getRulesMetaForResults (.../node_modules/eslint/lib/eslint/flat-eslint.js:703:30)
    at file://.../example.mjs:5:8
</pre>

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by fasttime**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #16402

#### What changes did you make? (Give an overview)

* `FlatESLint.prototype.getRulesMetaForResults` will now ignore messages without a `ruleId` instead of crashing with a `TypeError`.
* Unit tests for `getRulesMetaForResults` added for both `FlatESLint` and `ESLint`.
* The unit test "should return one rule meta when there is a suppressed linting error" was ported to `FlatESLint`. This was originally introduced for `ESLint` in #15459.

### CODE REVIEW

File: tests/lib/eslint/flat-eslint.js [hunk 1]
```diff
@@ -3663,6 +3663,22 @@ describe("FlatESLint", () => {
...
+                    rules: {
+                        semi: 2
+                    }
+                }
+            });
+
+            const results = await engine.lintText("a // eslint-disable-line semi");
+            const rulesMeta = engine.getRulesMetaForResults(results);
+
+            assert.strictEqual(rulesMeta.semi, coreRules.get("semi").meta);
```
Comment (nzakas) [inline tests/lib/eslint/flat-eslint.js:3679]: Would it also make sense to ensure that there is only one key in `rulesMeta`? (Based on the name of this test.)

Comment (fasttime) [reply tests/lib/eslint/flat-eslint.js:3681]: I've added an assertion to make sure that there is only one key to the two unit tests that mention "one rule meta" in the title. Thanks @nzakas!

File: tests/lib/eslint/flat-eslint.js [hunk 2]
```diff
@@ -3707,6 +3723,36 @@ describe("FlatESLint", () => {
...
+                overrideConfig: { rules: { "no-var": "warn" } },
+                reportUnusedDisableDirectives: "warn"
+            });
+
+            const results = [
+                ...await engine.lintText("syntax error"),
+                ...await engine.lintText("// eslint-disable-line no-var"),
+                ...await engine.lintText("", { filePath: "/.ignored.js", warnIgnored: true })
+            ];
+            const rulesMeta = engine.getRulesMetaForResults(results);
```
[the remark this answers is not in the document]
Comment (fasttime) [reply tests/lib/eslint/flat-eslint.js]: Thanks @mdjermanovic, I see the point here. I've changed the test as you suggested. Now I'm calling `getRulesMetaForResults` once for each array returned by `lintText`. It would be also possible to split the code in three test if that seems clearer, but I haven't done so yet.

BTW, I hope that it will still be possible to use `getRulesMetaForResults` on a merged results array with the
new API, even if that won't be representative of canonical usage (because calling `getRulesMetaForResults` multiple times and merging the returned objects won't be considered better practice, I think).

File: tests/lib/eslint/flat-eslint.js [hunk 3]
```diff
@@ -3707,6 +3725,46 @@ describe("FlatESLint", () => {
...
+                assert.deepStrictEqual(rulesMeta, {});
+            }
+            {
+                const results = await engine.lintText("// eslint-disable-line no-var");
+                const rulesMeta = engine.getRulesMetaForResults(results);
+
+                assert.deepStrictEqual(rulesMeta, {});
+            }
+            {
+                const results = await engine.lintText("", { filePath: "/.ignored.js", warnIgnored: true });
```
Comment (mdjermanovic) [inline tests/lib/eslint/flat-eslint.js:3749]: Can we use some explicitly ignored file path instead of `/.ignored.js`? `/.ignored.js` will indeed most likely be treated as an ignored file due to being outside of `cwd`, but that still depends on how the environment where the tests are run is set up. It may also be ignored because it's a dotfile, but it is not yet certain how dotfiles will be treated. For the purposes of this test, I think it would be better to avoid these assumptions. We can, for example, add `ignorePatterns: ["ignored.js"]` to `new FlatESLint({ ... })` and use `filePath: "ignored.js"`.

(the same for the `eslint.js` test)

Comment (fasttime) [reply tests/lib/eslint/flat-eslint.js]: Updated as suggested, thanks!

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

Just waiting for @nzakas, and we should also fix CI (the errors are not related to the changes from this PR).

**Comment by mdjermanovic** [comment]
CI has been fixed and all checks on this PR are now passing.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!
