### PR TITLE
Fix: `object-curly-newline` multiline with comments (fixes #6381)

### LINKED ISSUE #6381: `object-curly-newline` and comments.
From https://twitter.com/ponko2_jp/status/741573129105854465

**What version of ESLint are you using?**

- 2.12.0

**What parser (default, Babel-ESLint, etc.) are you using?**

- default

**Please show your full configuration:**

- nothing

**What did you do? Please include the actual source code causing the issue.**

```js
var obj = {
    // comment.
    a: 1
}
```

    eslint test.js --fix --rule object-curly-newline:error --no-eslintrc --no-ignore

**What did you expect to happen?**

- The code isn't modified because the object literal is multiline with a comment and a property.

**What actually happened? Please include the actual, raw output from ESLint.**

- The code was modified to:

  ```js
  var obj = {a: 1}
  ```

----

Currently, this rule checks whether an object literal is multiline or not by comparing the following 2 tokens.

- The next token of the open brace.
- The previous token of the close brace.

So comments are ignored.
I think this rule should check comments as well.

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #6381.

I modified the rule to use comments also to check whether an object literal is multiline or not.

### CODE REVIEW

File: lib/rules/object-curly-newline.js [hunk 1]
```diff
@@ -139,6 +139,15 @@ module.exports = {
                 )
             );
 
+            // Use tokens or comments to check multiline or not.
+            // But use only tokens to check whether line breaks are needed.
+            // This allows:
+            //    var obj = { // eslint-disable-line foo
+            //        a: 1
+            //    }
```
Comment (platinumazure) [inline lib/rules/object-curly-newline.js]: The ESLint style guide favors the following for multiline comments:

```js
/**
 * First line of comment text here
 * Second goes here, etc.
 * Last line
 */
```

With the leading slash aligned with the code block below.

Comment (mysticatea) [inline lib/rules/object-curly-newline.js]: Thanks, I updated it.
I want to autofix this!

**Comment by nzakas** [comment]
Lgtm
