### PR TITLE
fix: EMFILE errors

### LINKED ISSUE #18301: Bug: Error: EMFILE: too many open files
### Environment

Environment Info:

Node version: v21.7.2
npm version: v10.5.0
Local ESLint version: v9.0.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.23606

### What parser are you using?

@typescript-eslint/parser

### What did you do?

I have migrated my web project to eslint 9 & flat configuration file.

### What did you expect to happen?

eslint should complete running without any error

### What actually happened?

eslint terminated with reporting the following error.

C:\S\eslint-emfile-repro git:[main]
npm run lint

> eslint-emfile-repro@1.0.0 lint
> eslint ./

Oops! Something went wrong! :(

ESLint: 9.0.0

Error: EMFILE: too many open files, open 'C:\S\eslint-emfile-repro\src\file_8367.tsx'
    at async open (node:internal/fs/promises:637:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at async Promise.all (index 8189)
    at async ESLint.lintFiles (C:\S\eslint-emfile-repro\node_modules\eslint\lib\eslint\eslint.js:863:25)
    at async Object.execute (C:\S\eslint-emfile-repro\node_modules\eslint\lib\cli.js:461:23)
    at async main (C:\S\eslint-emfile-repro\node_modules\eslint\bin\eslint.js:165:22)

### Link to Minimal Reproducible Example

https://github.com/last-Programmer/eslint-emfile-repro.git

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

It is already reported here but was closed https://github.com/eslint/eslint/issues/17249

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

File read operations that throw an EMFILE or ENFILE error will be automatically retried.

I also added a test that runs only in CI to save us time locally. There was an error with the abort handling that I had to fix in order to make the test pass.

fixes #18301

### CODE REVIEW

File: lib/eslint/eslint.js [hunk 1]
```diff
@@ -950,10 +953,13 @@ class ESLint {
 
                         return result;
                     }).catch(error => {
-                        controller.abort(error);
-                        throw error;
-                    });
 
+                        if (error.name !== "AbortError" && !retryCodes.has(error.code)) {
```
Comment (fasttime) [inline lib/eslint/eslint.js:957]: Normally it shouldn't be necessary to exclude `AbortError`s explicitly. Those errors will only pop up after the `AbortController` has been signaled abort, and at that point, calling the `abort` method one more time will have no effect anyway.

Did you add the `error.name` check because of some failing tests?

Comment (nzakas) [reply lib/eslint/eslint.js]: Good call out. I was having some trouble with aborted requests when I was writing the tests, but I just realized it's because the `catch` is in the wrong place. Moving it means I can remove all of this check.

**Comment by nzakas** [comment]
Looks like a bug in `eslint-plugin-n`:
https://github.com/eslint-community/eslint-plugin-n/issues/242

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Leaving open for a couple of days if anyone else would like to review it before merging.

**Comment by fasttime** [comment]
When the EMFILE test runs locally, it will create 100000 files in `tests/fixtures/emfile`. If I run `npm test` afterwards, the whole `tests/fixture` directory, including the new 100000 files, will be copied to a temporary directory multiple times, because some unit tests run on a temporary copy of the fixtures directory:

https://github.com/eslint/eslint/blob/09675e153169d4d0f4a85a95007dcd17d34d70c7/tests/lib/eslint/eslint.js#L120

https://github.com/eslint/eslint/blob/09675e153169d4d0f4a85a95007dcd17d34d70c7/tests/lib/eslint/legacy-eslint.js#L105

https://github.com/eslint/eslint/blob/29c359599c2ddd168084a2c8cbca626c51d0dc13/tests/lib/cli-engine/cli-engine.js#L96

https://github.com/eslint/eslint/blob/ae8103de69c12c6e71644a1de9589644e6767d15/tests/lib/cli.js#L100

This seems unnecessary, even if that test will mostly run only in CI.

Would it be possible to delete the test files after the EMFILE test runs? Alternatively, we could create the files for the EMFILE test in a different directory or a temporary directory and run the test there.

**Comment by nzakas** [comment]
Moved the file creation to `tmp/emfile-check`.

File: .gitignore [hunk 2]
```diff
@@ -33,3 +33,6 @@ pnpm-lock.yaml
 # Docs site
 _site
 /docs/src/assets/css
+
+# EMFILE test files
+/tests/fixtures/emfile/file*.js
```
Comment (fasttime) [inline .gitignore:38]:
```suggestion
```

This is no longer needed.

**Review by fasttime — COMMENTED** [review]
Just a note about .gitignore, then LGTM.

**Comment by nzakas** [comment]
@fasttime @mdjermanovic can you re-approve please?

**Review by aladdin-add — APPROVED** [review]

**Review by fasttime — APPROVED** [review]
LGTM, thanks!

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
