### PR TITLE
Fix: no-control-regex literal handling fixed. (fixes #5737)

### LINKED ISSUE #5737: no-control-regex: Invalid example in documentation doesn't trigger a warning on the demo page
**What version of ESLint are you using?**
2.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
Here's my `.eslintrc.js`:

```javascript
module.exports = {
    "rules": {
        "no-control-regex": "error"
    }
};
```

**What did you do? Please include the actual source code causing the issue.**

```javascript
var pattern1 = /\\x1f/;
```

**What did you expect to happen?**
I expected this code to cause a linting error. This code snippet is the first incorrect example in [the documentation](http://eslint.org/docs/rules/no-control-regex).  The second example (`var pattern2 = new RegExp("\x1f");` throws an error as expected.

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
PS C:\temp> eslint .\test.js
PS C:\temp>
```

### PR DESCRIPTION
**Pull request by efegurkan**
Regex'es defined with literal syntax were not handled as expected.
During the check we get the the regex from node and turn it to string,
then check if it contains control characters as in it. But
`regex.toString()` produces different outputs for literals and regexp
objects. Added another check, now it works as expected.

New check also interfered with the rule itself during `npm run lint`, I
had to use disable-line in the rule itself. I am not very proud of it.

### CODE REVIEW

File: lib/rules/no-control-regex.js [hunk 1]
```diff
@@ -58,7 +58,9 @@ module.exports = {
 
                 if (regex) {
                     computedValue = regex.toString();
-                    if (/[\x00-\x1f]/.test(computedValue)) {
+
+                    // literal regexes interpreted as actual strings instead of characters.
+                    if (/[\x00-\x1f]/.test(computedValue) || /\\x[0-1][0-f]/.test(computedValue)) { // eslint-disable-line no-control-regex
```
Comment (michaelficarra) [inline lib/rules/no-control-regex.js]: Replace `/\\x[0-1][0-f]/` with `/\\x[01][0-9a-f]/i`.

File: tests/lib/rules/no-control-regex.js [hunk 2]
```diff
@@ -28,6 +28,7 @@ ruleTester.run("no-control-regex", rule, {
         "new (function foo(){})('\\x1f')"
     ],
     invalid: [
+        { code: "var regex = /\\x1f/", errors: [{ message: "Unexpected control character in regular expression.", type: "Literal"}] },
         { code: "var regex = /\\\x1f/", errors: [{ message: "Unexpected control character in regular expression.", type: "Literal"}] },
```
Comment (michaelficarra) [inline tests/lib/rules/no-control-regex.js]: You should remove this test. Or move it to the passing side.

Comment (efegurkan) [inline tests/lib/rules/no-control-regex.js]: Actually I am not sure about this. `/\\x1f/` is the same from the [rules documentation](http://eslint.org/docs/rules/no-control-regex). Or am I missing something ?

File: lib/rules/no-control-regex.js (hunk 1 above)
Comment (efegurkan) [inline lib/rules/no-control-regex.js]: Oops. its a dumb mistake, sorry about that.

File: tests/lib/rules/no-control-regex.js (hunk 2 above)
Comment (michaelficarra) [inline tests/lib/rules/no-control-regex.js]: The extra unnecessary backslash should be removed from the documentation.

Comment (efegurkan) [inline tests/lib/rules/no-control-regex.js]: Oh you are right, double backslash will make it escaped. I will move it to the valid list. Need to rework on the checks too. Thanks for feedback.

**Comment by efegurkan** [comment]
I did pushed the last changes btw. Thanks.

File: lib/rules/no-control-regex.js [hunk 3]
```diff
@@ -51,14 +51,43 @@ module.exports = {
             return null;
         }
 
+        /**
+         * Check the regex expression
+         * @param {String} regexStr regex as string to check
+         * @returns {Boolean} returns true if finds control characters on regex
+         * @private
+         */
+        function checkRegExp(regexStr) {
```
Comment (michaelficarra) [inline lib/rules/no-control-regex.js]: This is a bad name and the jsdoc has a bad description. How about `hasControlChars`? Protip: when choosing a name for a function, look to the returned expression for suggestions.

**Comment by michaelficarra** [comment]
It's strange that you have a blank line between every other line of code. That doesn't fit with the style used elsewhere.

File: lib/rules/no-control-regex.js [hunk 4]
```diff
@@ -51,14 +51,43 @@ module.exports = {
...
+
+            // check control characters, if RegExp object used
```
Comment (nzakas) [inline lib/rules/no-control-regex.js]: We generally have a blank line before comments, but no blank line after.

File: lib/rules/no-control-regex.js [hunk 5]
```diff
@@ -51,14 +51,43 @@ module.exports = {
...
+
+            var hasControlChars = /[\x00-\x1f]/.test(regexStr); // eslint-disable-line no-control-regex
```
Comment (nzakas) [inline lib/rules/no-control-regex.js]: Can you combine these two `var` statements? Then you can use `eslint-disable no-control-regex` around both

File: lib/rules/no-control-regex.js [hunk 6]
```diff
@@ -51,14 +51,43 @@ module.exports = {
...
+
+            // check substr, if regex literal used
+
+            var subStrIndex = regexStr.search(/\\x[01][0-9a-f]/i); // eslint-disable-line no-control-regex
```
Comment (michaelficarra) [inline lib/rules/no-control-regex.js]: This line doesn't need the eslint comment anyway.

**Comment by efegurkan** [comment]
@nzakas as @michaelficarra mentioned only one of the regex'es given, So I don't think we need to merge two var statements you mentioned.

Also thanks for the protip @michaelficarra , I will be more careful next time.

**Comment by nzakas** [comment]
Lgtm

@michaelficarra all set?

**Comment by michaelficarra** [comment]
:shipit:
