### PR TITLE
Fix: refactor RuleContext to not modify report locations (fixes #8980)

### LINKED ISSUE #8980: End location inference doesn't work for rules using the new-style context.report API
**Tell us about your environment**

* **ESLint Version:** 4.3.0
* **Node Version:** 8.2.0
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
rules:
  no-whitespace-before-property: error
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```
echo 'foo .bar' | eslint --stdin --no-eslintrc --rule 'no-whitespace-before-property: error' --format json
```

**What did you expect to happen?**

I expected the resulting problem to have an `endLine` and `endColumn`, because the `no-whitespace-before-property` rule [reports a node](https://github.com/eslint/eslint/blob/2874d75ed8decf363006db25aac2d5f8991bd969/lib/rules/no-whitespace-before-property.js#L48).

**What actually happened? Please include the actual, raw output from ESLint.**

```
[{"filePath":"<text>","messages":[{"ruleId":"no-whitespace-before-property","severity":2,"message":"Unexpected whitespace before property bar.","line":1,"column":1,"nodeType":"MemberExpression","source":"foo .bar","fix":{"range":[3,5],"text":"."}}],"errorCount":1,"warningCount":0,"fixableErrorCount":1,"fixableWarningCount":0,"source":"foo .bar\n"}]
```

Note that there is no `endLine` and `endColumn`.

The issue is that the change in https://github.com/eslint/eslint/commit/b0c63f0a928cceff7cf6f060262dd7ac4bc0f8dc was incomplete. It modifies the logic in `lib/eslint.js` (which has now been renamed to `lib/linter.js`) to correctly handle the case where no location is provided. However, the report conversion logic for the object-based `context.report` API in [`rule-context.js`](https://github.com/eslint/eslint/blob/2874d75ed8decf363006db25aac2d5f8991bd969/lib/rule-context.js#L199) incorrectly passes the `start` of a node as an explicit location. The result is that `lib/linter.js` does not add an end location because it thinks an explicit start location was already provided.

The quick fix would be to replace `descriptor.node.loc.start` on [this line](https://github.com/eslint/eslint/blob/2874d75ed8decf363006db25aac2d5f8991bd969/lib/rule-context.js#L199) with `descriptor.node.loc`. As a potentially separate fix, I think we should refactor the interaction between `Linter#report` and `RuleContext#report`. This bug occurred because the two methods don't have a clear separation of responsibilities with regard to handling locations that weren't provided by the rule.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/8980)

**What changes did you make? (Give an overview)**

This refactors `RuleContext` and updates it to simply pass report locations directly to `Linter`, rather than modifying them beforehand. `Linter` already contains all the necessary functionality for handling locations, so it's not necessary to duplicate any logic in `RuleContext`. The duplication caused a bug where `Linter` was modified and `RuleContext` was not.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: lib/rule-context.js [hunk 1]
```diff
@@ -161,22 +162,14 @@ class RuleContext {
         this.parserServices = Object.freeze(Object.assign({}, parserServices));
 
         // private.
-        this.eslint = eslint;
-        this.severity = severity;
+        this._linter = linter;
```
Comment (not-an-aardvark) [inline lib/rule-context.js]: @mysticatea Will this break `eslint-plugin-eslint-comments`? I recall it was relying on `context.eslint` at one point.

(Ideally, I think it would be better if rules didn't have access to the `linter` instance, because it allows them to interfere with other rules. But I'm not sure there's a better way to implement `eslint-plugin-eslint-comments`, except possibly by running the rules with a separate `Linter` instance).

File: lib/rule-context.js [hunk 2]
```diff
@@ -192,38 +185,57 @@ class RuleContext {
...
-PASSTHROUGHS.forEach(function(name) {
-    this[name] = function(a, b, c, d, e) {
-        return this.eslint[name](a, b, c, d, e);
-    };
-}, RuleContext.prototype);
+// Copy over passthrough methods.
+PASSTHROUGHS.forEach(name => {
+    Object.defineProperty(RuleContext.prototype, name, {
+        value() {
+            return this._linter[name].apply(this._linter, arguments);
```
Comment (platinumazure) [inline lib/rule-context.js]: Any reason for using `arguments` here? Will this introduce a deoptimization on any critical methods of RuleContext?

Comment (not-an-aardvark) [inline lib/rule-context.js]: The previous solution (assuming all methods had at most 5 arguments) seemed like it was a bug hazard, because it would cause subtle issues if a new method was added that accepted more than 5 arguments.

I don't think `arguments` causes deoptimization when used with `Function.prototype.apply` ([link](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#what-is-safe-arguments-usage)), so I think this should be fine.

Comment (platinumazure) [inline lib/rule-context.js]: I appreciate the citation. LGTM but would like another set of eyes on this.
