### PR TITLE
Fix: yoda left string fix for exceptRange (fixes #12883)

### LINKED ISSUE #12883: yoda rule exceptRange false positives
**Tell us about your environment**

* **ESLint Version:** 7.0.0-alpha.0
* **Node Version:** v12.14.0
* **npm Version:** v6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    parserOptions: {
        ecmaVersion: 2015
    },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

These are two different issues.

1. Possible inconsistency between `"never"` and `"always"`.

[Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHlvZGE6IFtcImVycm9yXCIsIFwibmV2ZXJcIiwgeyBleGNlcHRSYW5nZTogdHJ1ZSB9XSAqL1xuXG5pZiAoMCA8IHggJiYgeCA8IHNvbWV0aGluZykge30gLy8gbm8gZXJyb3IiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

```js
/* eslint yoda: ["error", "never", { exceptRange: true }] */

if (0 < x && x < something) {} // no error
```

[Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHlvZGE6IFtcImVycm9yXCIsIFwiYWx3YXlzXCIsIHsgZXhjZXB0UmFuZ2U6IHRydWUgfV0gKi9cblxuaWYgKHNvbWV0aGluZyA8IHggJiYgeCA8IDEwMCApIHt9IC8vIGVycm9yIG9uIHggPCAxMDAiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

```js
/* eslint yoda: ["error", "always", { exceptRange: true }] */

if (something < x && x < 100 ) {} // error on x < 100
```

2. Possible inconsistency between how the rule treats numbers and strings.

[Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHlvZGE6IFtcImVycm9yXCIsIFwibmV2ZXJcIiwgeyBleGNlcHRSYW5nZTogdHJ1ZSB9XSAqL1xuXG5pZiAoMSA8IHggJiYgeCA8IE1BWCApIHt9IC8vIG5vIGVycm9yXG5cbmlmIChcImFcIiA8IHggJiYgeCA8IE1BWCApIHt9IC8vIGVycm9yIG9uIFwiYVwiIDwgeCIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

```js
/* eslint yoda: ["error", "never", { exceptRange: true }] */

if (1 < x && x < MAX ) {} // no error

if ("a" < x && x < MAX ) {} // error on "a" < x
```

```bash
eslint index.js
```

**What did you expect to happen?**

Maybe no errors.

**What actually happened? Please include the actual, raw output from ESLint.**

Two errors noted in the comments.

**Are you willing to submit a pull request to fix this bug?**

Yes.

### PR DESCRIPTION
**Pull request by anikethsaha**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

fixing the second issue in https://github.com/eslint/eslint/issues/12883

#### What changes did you make? (Give an overview)

as mentioned in https://github.com/eslint/eslint/issues/12883, when having a string in `exceptRange` in left, it was throwing error. So, I added a string check in `isBetwwenTest` method for `leftLiteral.value`

#### Is there anything you'd like reviewers to focus on?
fixes https://github.com/eslint/eslint/issues/12883

### CODE REVIEW

**Comment by anikethsaha** [comment]
@mdjermanovic I would like to apologize as I forgot to comment on the issue that I am picking this! my bad !

**Comment by mdjermanovic** [comment]
No problem, thanks for the PR!

File: lib/rules/yoda.js [hunk 1]
```diff
@@ -248,7 +248,7 @@ module.exports = {
                 return (node.operator === "&&" &&
                     (leftLiteral = getNormalizedLiteral(left.left)) &&
                     (rightLiteral = getNormalizedLiteral(right.right, Number.POSITIVE_INFINITY)) &&
-                    leftLiteral.value <= rightLiteral.value &&
+                    (typeof leftLiteral.value === "string" || leftLiteral.value <= rightLiteral.value) &&
```
Comment (mdjermanovic) [inline lib/rules/yoda.js]: This would introduce false negatives:

```js
/*eslint yoda: ["error", "never", { "exceptRange": true }]*/

if ("b" <= x && x < "a") {
    // ...
}
```

Looks like we should rather replace the `Number.POSITIVE_INFINITY` logic with something else?

Comment (anikethsaha) [reply lib/rules/yoda.js]: > This would introduce false negatives:
> 
> ```js
> /*eslint yoda: ["error", "never", { "exceptRange": true }]*/
> 
> if ("b" <= x && x < "a") {
>     // ...
> }
> ```
> 


Should I give a check for rightLiteral as well ? like this 

```js
(typeof rightLiteral.value === "string" || rightLiteral.value <= leftLiteral.value)
```

??

Comment (anikethsaha) [reply lib/rules/yoda.js]: > Looks like we should rather replace the `Number.POSITIVE_INFINITY` logic with something else?

I would give a range options with `Number.MAX_SAFE_INTEGER` and `Number.MIN_SAFE_INTEGER`

Comment (mdjermanovic) [reply lib/rules/yoda.js]: The problem is: `"b" <= x && x < "a"` should be reported as an error, similar to how the rule already reports `2 <= x && x < 1`. Both are invalid range checks, because the right value isn't greater than the left value.

The issue is when one of these values is unknown (e.g., an identifier `foo`).

The actual logic handles this by treating unknown values as positive or negative infinity values, so the comparison works well for numbers, but it fails for strings.

Comment (mdjermanovic) [reply lib/rules/yoda.js]: Example from #12883:

```js
/* eslint yoda: ["error", "never", { exceptRange: true }] */

if (1 < x && x < MAX ) {} // no error

if ("a" < x && x < MAX ) {} // error on "a" < x
```

The different behavior is caused by:

```js
1 < Number.POSITIVE_INFINITY; // true

"a" < Number.POSITIVE_INFINITY; // false
```

Comment (anikethsaha) [reply lib/rules/yoda.js]: I am pretty sure js engine uses the product of char's ASCII value their position for comparing strings like [`they are compared letter-by-letter`](https://javascript.info/comparison#string-comparison).

image

so for this 

` ("b" <= x && x < "a")`, we can compare the left right literals with this algorithm
 

but not sure about this as they are of different data types. So not sure what to do for this. 
It is either to allow them or not !

`("a" < x && x < MAX )`

Comment (mdjermanovic) [reply lib/rules/yoda.js]: `("a" < x && x < MAX )` should be allowed (it isn't in the actual master version), but not in a way that would also allow `("b" <= x && x < "a")` which correctly isn't allowed in the actual master version.

Comment (anikethsaha) [reply lib/rules/yoda.js]: > but not in a way that would also allow `("b" <= x && x < "a")` which correctly isn't allowed in the actual master version.


@mdjermanovic  can we use `eval` for `("b" <= x && x < "a")` (when both left and right literals are `string`) ?

image


also just to summarise few things  (let me know which point is wrong)

when
- **`rightLiteral` is `string` but not `leftLiteral`:** 

  it should allow (it does in master [`demo`](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHlvZGE6IFtcImVycm9yXCIsIFwibmV2ZXJcIiwgeyBleGNlcHRSYW5nZTogdHJ1ZSB9XSAqL1xuXG5cbmlmICggeCA8IE1BWCAmJiB4IDwgXCJhXCIgKSB7fSAiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=))
  no changes require for this

- **`leftLiteral` is  `string` but not `rightLiteral` is not a `string`:** 
  it should allow but in `master` its not allowing [`demo`](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHlvZGE6IFtcImVycm9yXCIsIFwibmV2ZXJcIiwgeyBleGNlcHRSYW5nZTogdHJ1ZSB9XSAqL1xuXG5cbmlmIChcImFcIiA8IHggJiYgeCA8IE1BWCApIHt9IC8vIGVycm9yIG9uIFwiYVwiIDwgeCIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==) and this is from the original issue
  allowing in this PR

- **when both `leftLiteral` and `rightLiteral` are `string`:** 
   it should compare them and then allow or disallow based on the result  solution I proposed is to use 
   ```js
    eval(`${leftLiteral} ${operator} ${rightLiteral}`)
    ```

Comment (mdjermanovic) [reply lib/rules/yoda.js]: > * **`rightLiteral` is `string` but not `leftLiteral`:**
>   it should allow (it does in master [`demo`](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHlvZGE6IFtcImVycm9yXCIsIFwibmV2ZXJcIiwgeyBleGNlcHRSYW5nZTogdHJ1ZSB9XSAqL1xuXG5cbmlmICggeCA8IE1BWCAmJiB4IDwgXCJhXCIgKSB7fSAiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=))
>   no changes require for this

Example in the demo is lint-free because there are no "yoda" conditions. It would be lint-free with `{ exceptRange: false }`, too.

An example where `rightLiteral` is string and `leftLiteral` isn't string would be something like:

```js
if (MIN < x && x < "a" ) {}
```

This also isn't error with `"never"`, regardless of `exceptRange`. It would be error with `"always"`, and that's point `1.  Possible inconsistency between "never" and "always"` from #12883 (it isn't a problem with strings only, numbers would also cause error).

> * **`leftLiteral` is  `string` but not `rightLiteral` is not a `string`:**
>   it should allow but in `master` its not allowing [`demo`](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHlvZGE6IFtcImVycm9yXCIsIFwibmV2ZXJcIiwgeyBleGNlcHRSYW5nZTogdHJ1ZSB9XSAqL1xuXG5cbmlmIChcImFcIiA8IHggJiYgeCA8IE1BWCApIHt9IC8vIGVycm9yIG9uIFwiYVwiIDwgeCIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==) and this is from the original issue
>   allowing in this PR

:+1: that's point `2.` from #12883.

> * **when both `leftLiteral` and `rightLiteral` are `string`:**
>   it should compare them and then allow or disallow based on the result  solution I proposed is to use
>   ```js
>    eval(`${leftLiteral} <= ${rightLiteral}`)
>   ```

Why is `eval` necessary here, `leftLiteral.value <= rightLiteral.value` already works well if both literals are strings or any other literals.

Comment (anikethsaha) [reply lib/rules/yoda.js]: cc @mdjermanovic can you check the latest commit I did some changes to fix both the issues mentioned in the original issue.

File: tests/lib/rules/yoda.js [hunk 2]
```diff
@@ -992,6 +1017,110 @@ ruleTester.run("yoda", rule, {
...
+                    type: "BinaryExpression"
+                }
+            ]
+        },
+        {
+            code: "if (x < -1n || 1n <= x) {}",
+            output: "if (x < -1n || x >= 1n) {}",
+            options: ["never", { exceptRange: true }],
+            parserOptions: { ecmaVersion: 2020 },
+            errors: [
```
Comment (yeonjuan) [inline tests/lib/rules/yoda.js]: I think cases like these should be warned.
There are also other false-positive cases that use the operator `||`.
I think the `isOutsideTest()` didn't check it properly.

File: tests/lib/rules/yoda.js [hunk 3]
```diff
@@ -134,23 +134,50 @@ ruleTester.run("yoda", rule, {
...
+        },
+        {
+            code: "if (`blue` < x.y && x.y < `green`) {}",
+            options: ["never", { exceptRange: true }],
+            parserOptions: { ecmaVersion: 2015 }
+        },
+        {
+            code: "if ('a' < x && x < MAX ) {}",
+            options: ["never", { exceptRange: true }],
+            parserOptions: { ecmaVersion: 2015 }
```
Comment (yeonjuan) [inline tests/lib/rules/yoda.js]: I think we don't need to specify the `parserOptions` in these cases (non-template literals).

File: tests/lib/rules/yoda.js (hunk 2 above)
Comment (anikethsaha) [reply tests/lib/rules/yoda.js]: > `(x < -1n || 1n <= x)`

this is not a `yoda` and I think `never` with `exceptRange` only accepts `Yoda` for range.

File: tests/lib/rules/yoda.js (hunk 3 above)
Comment (anikethsaha) [reply tests/lib/rules/yoda.js]: ops....forgot to remove this. 

i will change it 👍

**Comment by yeonjuan** [comment]
@anikethsaha 
Thanks for the PR. I didn't check the code part thoroughly, but I could find some false positive in test cases. I commented at one of them.

**Comment by anikethsaha** [comment]
@yeonjuan can you point those false positive. It would be better for me to solve them

**Comment by anikethsaha** [comment]
will it help for reviewing if I comment along with the `invalid` cases with why they are invalid?

**Comment by yeonjuan** [comment]
@anikethsaha 
> can you point those false positive. It would be better for me to solve them

Yes :)
Some of the cases which use the operator `||` with the option `expectRange: true` seem like false positive. The blow cases are not be warned in the actual version(`master`) but warned in this PR.
- [Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgeW9kYTogW1wiZXJyb3JcIiwgXCJuZXZlclwiLCB7IFwiZXhjZXB0UmFuZ2VcIjogdHJ1ZSB9XSovXG5cbmlmICh4IDwgLTFuIHx8IDFuIDw9IHgpIHt9XG5cbmlmICh4IDwgLTEgfHwgMSA8IHgpIHt9XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==)
```js
/*eslint yoda: ["error", "never", { "exceptRange": true }]*/
if (x < -1n || 1n <= x) {}
if (x < -1 || 1 <= x) {}
```
In my understanding, those cases should not be warned because they using the option `expectRange: true` and they check about ranges.



> Examples of correct code for the "never", { "exceptRange": true } options:
/*eslint yoda: ["error", "never", { "exceptRange": true }]*/
// ...
if (x < -1 || 1 < x) {
    // ...
}

And, we can find about the proper behavior of the option `exceptRange: true` in the [docs](https://eslint.org/docs/rules/yoda).

**Comment by anikethsaha** [comment]
@yeonjuan , thanks for pointing. 

`(x < -1n || 1n <= x)`

I think the docs is wrong about this, cause this is not a `yoda` condition, right ! , so with `never` options (which allows non-yoda only) it will be lint-free but when using `exceptRange` it will only allow `yoda` for range condition, so this why it  is invalid

let me know if I am wrong about this. !

File: tests/lib/rules/yoda.js [hunk 4]
```diff
@@ -159,7 +186,18 @@ ruleTester.run("yoda", rule, {
         { code: "if (x < `2` && x !== `-3`) {}", options: ["always", { onlyEquality: true }], parserOptions: { ecmaVersion: 2015 } }
     ],
     invalid: [
-
+        {
+            code: "if (x <= 'bar' || 'foo' < x) {}",
```
Comment (anikethsaha) [inline tests/lib/rules/yoda.js]: this is invalid because `"foo"` is greater than `"bar"` 

image

File: tests/lib/rules/yoda.js [hunk 5]
```diff
@@ -992,6 +1017,110 @@ ruleTester.run("yoda", rule, {
                     type: "BinaryExpression"
                 }
             ]
+        },
+        {
+            code: "if (`green` < x.y && x.y < `blue`) {}",
```
Comment (anikethsaha) [inline tests/lib/rules/yoda.js]: this is invalid as `"green"` is greater than `"blue"`

image

File: tests/lib/rules/yoda.js [hunk 6]
```diff
@@ -992,6 +1017,110 @@ ruleTester.run("yoda", rule, {
...
+            errors: [
+                {
+                    messageId: "expected",
+                    data: { expectedSide: "right", operator: "<=" },
+                    type: "BinaryExpression"
+                }
+            ]
+        },
+        {
+            code: "if('a' <= x && x < 'b') {}",
```
Comment (anikethsaha) [inline tests/lib/rules/yoda.js]: ok this is a false negative. It should be allowed. 

I will take a look in this 👍

File: tests/lib/rules/yoda.js [hunk 7]
```diff
@@ -992,6 +1017,110 @@ ruleTester.run("yoda", rule, {
...
+            errors: [
+                {
+                    messageId: "expected",
+                    data: { expectedSide: "right", operator: "<=" },
+                    type: "BinaryExpression"
+                }
+            ]
+        },
+        {
+            code: "if ('b' <= x && x < 'a') {}",
```
Comment (anikethsaha) [inline tests/lib/rules/yoda.js]: 'b' > 'a'

thats why invalid

File: tests/lib/rules/yoda.js [hunk 8]
```diff
@@ -992,6 +1017,110 @@ ruleTester.run("yoda", rule, {
...
+            errors: [
+                {
+                    messageId: "expected",
+                    data: { expectedSide: "left", operator: "<" },
+                    type: "BinaryExpression"
+                }
+            ]
+        },
+        {
+            code: "if (x < -1n || 1n <= x) {}",
```
Comment (anikethsaha) [inline tests/lib/rules/yoda.js]: false negative . 

I will take a look 👍

File: tests/lib/rules/yoda.js [hunk 9]
```diff
@@ -992,6 +1017,110 @@ ruleTester.run("yoda", rule, {
...
+            errors: [
+                {
+                    messageId: "expected",
+                    data: { expectedSide: "left", operator: "<" },
+                    type: "BinaryExpression"
+                }
+            ]
+        },
+        {
+            code: "if (x < 0 || 1 <= x) {}",
```
Comment (anikethsaha) [inline tests/lib/rules/yoda.js]: this is not a `yoda` condition but with `never` and `exceptRange` options , it allows only `yoda` for range

File: tests/lib/rules/yoda.js (hunk 6 above)
Comment (anikethsaha) [reply tests/lib/rules/yoda.js]: this is invalid currently as well in master 

[`demo`](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHlvZGE6IFtcImVycm9yXCIsIFwiYWx3YXlzXCJdICovXG5cbmlmKCdhJyA8PSB4ICYmIHggPCAnYicpIHt9Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

File: tests/lib/rules/yoda.js (hunk 8 above)
Comment (anikethsaha) [reply tests/lib/rules/yoda.js]: > `if (x < -1n || 1n <= x) {}`

this is not a `yoda` and `always` allows only yoda but with `exceptRange` options it should be valid (lint free)


_looking into it 👍 _

**Comment by anikethsaha** [comment]
@mdjermanovic @yeonjuan I have added a comment for why some code should be invalid which is currently showing valid (in `master`), do let me know if anything else is required.

File: tests/lib/rules/yoda.js (hunk 4 above)
Comment (mdjermanovic) [reply tests/lib/rules/yoda.js]: This is a valid range test. It checks if `x` is not between `bar` and `foo`.

File: tests/lib/rules/yoda.js (hunk 5 above)
Comment (mdjermanovic) [reply tests/lib/rules/yoda.js]: :+1:

File: tests/lib/rules/yoda.js (hunk 4 above)
Comment (anikethsaha) [reply tests/lib/rules/yoda.js]: @mdjermanovic 

I think it's in invalid because `(x <= 'bar' || 'foo' < x)` is `yoda` and `always` expects only `yoda` but `exceptRange` with `always` expects `non yoda` conditions. 

right !

**Comment by mdjermanovic** [comment]
> `(x < -1n || 1n <= x)`
> 
> I think the docs is wrong about this, cause this is not a `yoda` condition, right ! , so with `never` options (which allows non-yoda only) it will be lint-free but when using `exceptRange` it will only allow `yoda` for range condition, so this why it is invalid.

`1n <= x` is a yoda condition. This would be an error with `"never", { "exceptRange": false }`.

This isn't an error with `"never", { "exceptRange": true }` because it's used in a valid range test.

**Comment by yeonjuan** [comment]
@anikethsaha  
reply for the [comment](https://github.com/eslint/eslint/pull/13052#issuecomment-601322386)
> I think the docs is wrong about this,

I don't think so. I think the documentation is right.
```
if (x < -1n || 1n <= x) {}
```
> cause this is not a yoda condition

Yes, this is not a yoda condition but its range test is valid. so when the option `exceptRange` is set to `true` it should not be warned.

> so with never options (which allows non-yoda only) it will be lint-free 

No. as you mentioned it enforce non-yoda with the `never` option. but there is a `yoda` condition (`1n < x`) on the right-side so it would be warned if the `exceptRange: false`

**Comment by anikethsaha** [comment]
let me clarify if I get this rule correctly !

- when , the range is in `yoda`, eg `(x < -1n || 1n <= x)`,  - yoda : `1n <= x`
   - with `never` , it should be an error
   - with `never` and `exceptRange : true` , it wont be an error right ? cause it expects the range to be in `yoda`
   - with `always`, it should not be an error
   - with `always` and `exceptRange : true` , it will be an error as it expects the condition to be `non - yoda`

- when the range is not in `yoda` , eg `(x <= -1n || x > 1n)`
  - with `never`, it is lint free
  - with `never` and `exceptRange : true` , it is error as it expects the range condition to be in `yoda`
  - with `always`, it is error
  - with `always` and `exceptRange : true`, it should not be an error as it expects the range condition to be `non-yoda`

After these checks, the rule can still show a linting error if the condition does not returns `true`

like this 

| input | `left` | `right` | checking | result | rule options |
|-|-|-|-|-|-|
|`(1 < a && a <= 2)`|`1`|`2`|`1 <= 2`|`true`|`never, exceptRange : true `|
|`('bar' < a && a <= 'foo')`|`bar`|`foo`|`'bar' <= 'foo'`|`true`|`never, exceptRange : true `|
| `(2 < a && a <= 1)`|`2`|`1`|`2 <= 1`|`false`|`never , exceptRange : true `|
|`(x < -1 !! 1 < x)`|`-1`|`1`|`-1<1`|`true`|`never, exceptRange : true`|




Please let me know if any of this wrong !

File: tests/lib/rules/yoda.js (hunk 3 above)
Comment (anikethsaha) [reply tests/lib/rules/yoda.js]: done

File: tests/lib/rules/yoda.js (hunk 2 above)
Comment (anikethsaha) [reply tests/lib/rules/yoda.js]: fixed

File: tests/lib/rules/yoda.js (hunk 4 above)
Comment (anikethsaha) [reply tests/lib/rules/yoda.js]: fixed

File: tests/lib/rules/yoda.js (hunk 8 above)
Comment (anikethsaha) [reply tests/lib/rules/yoda.js]: fixed

**Comment by yeonjuan** [comment]
@anikethsaha 
Thanks for changing. I think the false-positives I mentioned before are fixed. 👍 

But this change seems to make some new false-negative cases which not occurred in the current version.

* current version - [Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgeW9kYTogW1wiZXJyb3JcIiwgXCJuZXZlclwiLCB7IFwiZXhjZXB0UmFuZ2VcIjogdHJ1ZX1dKi9cblxuaWYoJ2EnIDw9IHggJiYgeCA8IDEpIHt9Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6eyJlczYiOnRydWV9fX0=)
```js
/*eslint yoda: ["error", "never", { "exceptRange": true}]*/

if('a' <= x && x < 1) {} // Error, And It's right because it is not a valid range test
```
But in the PR version, this case is not warned. but it should be warned because it is not a valid range test
* PR version 
```js
/*eslint yoda: ["error", "never", { "exceptRange": true}]*/

if('a' <= x && x < 1) {} // No Error
```

**Comment by anikethsaha** [comment]
@yeonjuan I changed that based on @mdjermanovic 's [comment](https://github.com/eslint/eslint/pull/13052#discussion_r394720900)

> `("a" < x && x < MAX )` should be allowed (it isn't in the actual master version), but not in a way that would also allow `("b" <= x && x < "a")` which correctly isn't allowed in the actual master version.

should  I change it ?

**Comment by anikethsaha** [comment]
@yeonjuan fixed !

Let me know if any else is required. 

Also, need suggestions for better approach than [**this**](https://github.com/eslint/eslint/pull/13052/files#diff-0bcd61f7e5d8bd75dab88c16de6d10d2R259-R262)

**Comment by mdjermanovic** [comment]
> Also, need suggestions for better approach than [**this**](https://github.com/eslint/eslint/pull/13052/files#diff-0bcd61f7e5d8bd75dab88c16de6d10d2R259-R262)

I believe the best approach would be to remove `defaultValue` parameter from the `getNormalizedLiteral` function, and handle those cases in a different way. Consequently, I think we shouldn't use `Number.POSITIVE_INFINITY`  and `Number.NEGATIVE_INFINITY` at all.

**Comment by mdjermanovic** [comment]
`{ "exceptRange": true }` can never produce errors in a code that is lint-free with `{ "exceptRange": false }`.

> when , the range is in `yoda`, eg `(x < -1n || 1n <= x)`, - yoda : `1n <= x`
> 
> * with `never` , it should be an error
> * with `never` and `exceptRange : true` , it wont be an error right ? cause it expects the range to be in `yoda`
> * with `always`, it should not be an error
> * with `always` and `exceptRange : true` , it will be an error as it expects the condition to be `non - yoda`

There are two conditions and this rule checks both of them:

* `x < -1n`
* `1n <= x`

Also, by the logic of this rule, `(x < -1n || 1n <= x)` has a form of a range test ("outside" test).

Expected behavior with `"never", { "exceptRange": false }`:

* `x < -1n` - ok, because this is a not-yoda condition
* `1n <= x` - error, because this is a yoda condition

Expected behavior with `"never", { "exceptRange": true }`:

* `x < -1n` - ok, because this is a not-yoda condition
* `1n <= x` - ok despite of the fact that this is a yoda condition, because it's in a range test

Expected behavior with `"always", { "exceptRange": false }`:

* `x < -1n` - error, because this is a not-yoda condition
* `1n <= x` - ok, because this is a yoda condition

Expected behavior with `"always", { "exceptRange": true }`:

* `x < -1n` - ok despite of the fact that this is a not-yoda condition, because it's in a range test
* `1n <= x` - ok, because this is a yoda condition

> when the range is not in `yoda` , eg `(x <= -1n || x > 1n)`
> 
> * with `never`, it is lint free
> * with `never` and `exceptRange : true` , it is error as it expects the range condition to be in `yoda`
> * with `always`, it is error
> * with `always` and `exceptRange : true`, it should not be an error as it expects the range condition to be `non-yoda`

There are two conditions and this rule checks both of them:

* `x <= -1n`
* `x > 1n`

By the logic of this rule, `(x <= -1n || x > 1n)` does **not** have a _form_ of a range test, so it isn't considered to be a range test, i.e. "exceptRange" does not apply here.

Expected behavior with `"never", { "exceptRange": false }`:

* `x <= -1n`  - ok, because this is a not-yoda condition
* `x > 1n`  - ok, because this is a not-yoda condition

Expected behavior with `"never", { "exceptRange": true }`:

* `x <= -1n`  - ok, because this is a not-yoda condition
* `x > 1n`  - ok, because this is a not-yoda condition

Expected behavior with `"always", { "exceptRange": false }`:

* `x <= -1n`  - error, because this is a not-yoda condition
* `x > 1n`- error, because this is a not-yoda condition

Expected behavior with `"always", { "exceptRange": true }`:

* `x <= -1n` - error, because this is a not-yoda condition
* `x > 1n` - error, because this is a not-yoda condition

**Comment by anikethsaha** [comment]
> I believe the best approach would be to remove `defaultValue` parameter from the `getNormalizedLiteral` function and handle those cases in a different way. Consequently, I think we shouldn't use `Number.POSITIVE_INFINITY` and `Number.NEGATIVE_INFINITY` at all.

@mdjermanovic  I think, in that case, if the `node.type` is `Identifier` then it should get the value of that variable and compare it just like usual js does. return the `value` from `getNormalizedLiteral` as the value of that variable. In this way, we don't need any default. 

image


But the downside is it **may** affect the performance and might lead to a bit of messy code! unless there is a better way to get the value of a variable by simply searching with its name. Here also, we need to consider the scope details as well.


This is what the new `getNormalizedLiteral` function will look like  (roughly)

image


here tests output 

image

we need to pass the values of `Identifier` in order to pass or fail them else they will fail
also, there are other cases like `memberExpression` etc whose values need to be evaluated as well.
else they will fail. And this becomes more complex as there can be run-time values as well.

Otherwise , I think we can go with the `defaultValue` approach ? 
thoughts ?

**Comment by yeonjuan** [comment]
@anikethsaha 
> @yeonjuan fixed !
> Let me know if any else is required.

 But still, there are some false-negative cases which not occurred in the actual version. (maybe it is minor edge case)
* [Online demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgeW9kYTogW1wiZXJyb3JcIiwgXCJuZXZlclwiLCB7IFwiZXhjZXB0UmFuZ2VcIjogdHJ1ZX1dKi9cblxuaWYoJ2EnIDw9IHggJiYgeCA8IEluZmluaXR5KSB7fSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnsiZXM2Ijp0cnVlfX19)
```js
/*eslint yoda: ["error", "never", { "exceptRange": true}]*/

if('a' <= x && x < Infinity) {} // Error, And It's right because it is not a valid range test
```
* This PR.

```js
/*eslint yoda: ["error", "never", { "exceptRange": true}]*/

if('a' <= x && x < Infinity) {} // No Error
```


> Also, need suggestions for better approach than this

I agree with [this approach](https://github.com/eslint/eslint/pull/13052#issuecomment-601925113)

**Comment by anikethsaha** [comment]
@yeonjuan I think this was as intended from the issue 

@mdjermanovic 's comment in  https://github.com/eslint/eslint/pull/13052#discussion_r394720900

> `("a" < x && x < MAX )` should be allowed (it isn't in the actual master version), but not in a way that would also allow `("b" <= x && x < "a")` which correctly isn't allowed in the actual master version.

`("a" <= x && x < MAX )` ↔️ `('a' <= x && x < Infinity)`

**Comment by yeonjuan** [comment]
@anikethsaha 
Well .. I don't think so 🤔.
In my understanding, we should treat the `MAX` in `("a" < x && x < MAX )` as a some string value which satisfy a valid range test, but `Infinity` is a `number`

**Comment by anikethsaha** [comment]
@yeonjuan  `("a"<= MAX)` will be tested as `("a"<= 'MAX')` or how else can we test it ? or simply return true ?

**Comment by mdjermanovic** [comment]
In my opinion, that check whether range boundaries make sense is already overly complex for this rule. I'd argue that it wasn't even necessary: an invalid range is a bug that isn't related to yoda conditions.

We should probably keep it since it's already there, but I'd suggest that we don't add more complexity with evaluating identifier values or any expressions other than those already implemented (literal, negated numeric literal, and static template literal), meaning that this would be valid:

```js
/*eslint yoda: ["error", "never", { "exceptRange": true}]*/

if('a' <= x && x < Infinity) {}
```

Regarding the implementation, I think that `getNormalizedLiteral`  should return `null` if the node isn't literal, negated numeric or static template (i.e. we should just remove `if (defaultValue) {}` from the code).

**Comment by yeonjuan** [comment]
Agreed about most of @mdjermanovic [mentioned](https://github.com/eslint/eslint/pull/13052#issuecomment-602120137).

> meaning that this would be valid:
/*eslint yoda: ["error", "never", { "exceptRange": true}]*/
if('a' <= x && x < Infinity) {}

Yes, It would be valid along with implementation, but I think it would be better if we change `yoda` with keeping its current behavior at most.

> Regarding the implementation, I think that getNormalizedLiteral should return null if the node isn't literal, negated numeric or static template (i.e. we should just remove if (defaultValue) {} from the code).

And maybe, it can be done by the way you mentioned. Below is one of the solutions that I thought. (it needs some test)

1. delete `defaultVaue` and related logic in `getNormalizedLiteral `

2. make `getNormalizedLiteral` to return null when the node is not literal.

3. In `isBetweenTest`, ` isOutsideTest` check whether one of ` getNormalizedLiteral(leftLiteral),  getNormalizedLiteral(rightLiteral)` is `null` or not.
   1.  if one of  them is null, we treat it as a valid range
   1. if not, compare the literal values in the way at the master version(leftLiteral.value <= rightLiteral.value)

**Comment by anikethsaha** [comment]
@yeonjuan , @mdjermanovic thanks for the input 💯 and suggestions

it worked as expected it seems 👍 

my bad that I made those checks more complicated!

File: lib/rules/yoda.js [hunk 10]
```diff
@@ -245,11 +235,23 @@ module.exports = {
...
+                    leftLiteral = getNormalizedLiteral(left.left);
+                    rightLiteral = getNormalizedLiteral(right.right);
+
+                    if (leftLiteral === null && rightLiteral === null) {
+                        return false;
+                    }
+
+                    if (leftLiteral !== null && rightLiteral === null || rightLiteral !== null && leftLiteral === null) {
+                        return true;
+                    }
```
Comment (mdjermanovic) [inline lib/rules/yoda.js]: This could produce a false negative:

```js
/* eslint "yoda": ["error", "never", { "exceptRange": true }] */

if (0 < a && b < max) {} // this should be error
```

This function can return `true` only when `same(left.right, right.left)` is `true`, so we should probably move the `same` condition to the main `if (node.operator === "&&)`, as it was before.

(the same applies to `isOutsideTest`)

File: lib/rules/yoda.js [hunk 11]
```diff
@@ -89,7 +87,7 @@ function looksLikeLiteral(node) {
  *  4. The Literal node which has the `defaultValue` argument if it exists.
  *  5. Otherwise `null`.
  */
-function getNormalizedLiteral(node, defaultValue) {
+function getNormalizedLiteral(node) {
```
Comment (yeonjuan) [inline lib/rules/yoda.js]: > 4. The Literal node which has the `defaultValue` argument if it exists.

Could you please edit the comments? I think it should be removed.

Comment (anikethsaha) [reply lib/rules/yoda.js]: thanks for pointing . 
Fixed 👍

File: lib/rules/yoda.js (hunk 10 above)
Comment (anikethsaha) [reply lib/rules/yoda.js]: done 👍

**Comment by anikethsaha** [comment]
test for `yoda` are passing but not sure why tests for other rules (`prefer-regex-literals`, `prefer-exponentiation-operator` etc) is failing

**Comment by anikethsaha** [comment]
> test for `yoda` are passing but not sure why tests for other rules (`prefer-regex-literals`, `prefer-exponentiation-operator` etc) is failing

cc @mdjermanovic @yeonjuan any suggestion for fixing this? I think its not related to this changes.

**Comment by mdjermanovic** [comment]
> > test for `yoda` are passing but not sure why tests for other rules (`prefer-regex-literals`, `prefer-exponentiation-operator` etc) is failing
> 
> cc @mdjermanovic @yeonjuan any suggestion for fixing this? I think its not related to this changes.

It looks like you don't have the new version of `eslint-utils` installed.

CI is failing for a different reason (#13076)

**Comment by anikethsaha** [comment]
cc @mdjermanovic  I was behind upstream master ! CI is clean

File: lib/rules/yoda.js [hunk 12]
```diff
@@ -245,11 +234,23 @@ module.exports = {
...
-                    same(left.right, right.left));
+                if (node.operator === "&&" && same(left.right, right.left)) {
+                    leftLiteral = getNormalizedLiteral(left.left);
+                    rightLiteral = getNormalizedLiteral(right.right);
+
+                    if (leftLiteral === null && rightLiteral === null) {
+                        return false;
+                    }
+
+                    if (leftLiteral !== null && rightLiteral === null || rightLiteral !== null && leftLiteral === null) {
```
Comment (mdjermanovic) [inline lib/rules/yoda.js]: With this change, the rule will now allow:

```js
/* eslint yoda: ["error", "always", { exceptRange: true }] */

if (x < 1 && 1 < 2) {}
```

which looks good, given that the actual master version already allows this:

```js
/* eslint yoda: ["error", "never", { exceptRange: true }] */

if (1 < 2 && 2 < x) {}
```

I'm not sure if it was the original intention to allow the second example, but the behavior will be at least consistent after this PR.

Comment (anikethsaha) [reply lib/rules/yoda.js]: But as per `exceptRange` is considered, it should be lint free right . !

Comment (mdjermanovic) [reply lib/rules/yoda.js]: Nothing to do. I just wanted to leave a note that this PR also changes the behavior of this rule in the first example (which actually makes it consistent with the second example).

Comment (anikethsaha) [reply lib/rules/yoda.js]: ohh ok cool 👍

File: tests/lib/rules/yoda.js [hunk 13]
```diff
@@ -134,23 +139,72 @@ ruleTester.run("yoda", rule, {
             options: ["never", { exceptRange: true }],
             parserOptions: { ecmaVersion: 2018 }
         }, {
-            code: "if (x <= `bar` || `foo` < x) {}",
```
[the remark this answers is not in the document]
Comment (anikethsaha) [reply tests/lib/rules/yoda.js:137]: thanks a lot for the catch. 
done 👍
