### PR TITLE
Breaking: fix plugin resolver in extends (fixes #9904)

### LINKED ISSUE #9904: Wrongly resolving plugins in extends
Here:

https://github.com/eslint/eslint/blob/084351bedb1001fc460e9acea4952b0b6139ec23/lib/config/config-file.js#L466

This is the code to resolve the plugin that `extends: "plugin:foo/recommended"` specified. That code looks to use the same logic as shareable config's.

However, the logic to resolve plugins is different to shareable config's. It's:

https://github.com/eslint/eslint/blob/084351bedb1001fc460e9acea4952b0b6139ec23/lib/config/plugins.js#L106

We should fix the resolving logic of plugins in `extends`.

----

Should we address this change as a breaking change?

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

Fixes #9904.

**What changes did you make? (Give an overview)**

This PR fixes plugin resolver in `extends` setting.

ESLint can handle `plugin:` prefix in `extends` setting, but it had resolved `plugin:` path with shareable config's resolver rather than plugin resolver. So it could load different plugin entity between `extends` setting and `rules` setting.

Now ESLint handle `plugin:` prefix with plugin resolver correctly.

This PR doesn't add any new test, but fixes some existing tests.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: tests/lib/config/config-file.js [hunk 1]
```diff
@@ -127,6 +128,28 @@ function createStubModuleResolver(mapping) {
...
+ * Overrides the native module resolver to resolve with the given mappings.
+ * @param {Object<string,string>} mapping A mapping of module name to path.
+ * @returns {void}
+ * @private
+ */
+function overrideNativeResolve(mapping) {
+    const originalFindPath = Module._findPath; // eslint-disable-line no-underscore-dangle
+
+    beforeEach(() => {
+        Module._findPath = function(request, paths, isMain) { // eslint-disable-line no-underscore-dangle
```
Comment (platinumazure) [inline tests/lib/config/config-file.js]: This feels a little risky to me. If someone writes `overrideNativeResolve(mapping)` more than once in a given describe block, then we could have two levels of overriding of `Module._findPath`.

I think it would make more sense to just override `Module._findPath` unconditionally to try to look up within the mappings and fallback to the original `Module._findPath` as a fallback, and then `overrideNativeResolve` would just set up and remove the mappings.
