### PR TITLE
Fix: updates category of no-restricted-properties to Best Practices (…

### LINKED ISSUE #6731: indent expects wrong indentation for logical/arithmetic expressions
**What version of ESLint are you using?**

3.1.1

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```js
indent: [
    'error',
    4,
    {
        SwitchCase: 1
    }
]
```

**What did you do? Please include the actual source code causing the issue.**

```js
(function() {
    var x = 0 ||
        {
            a: 1,
            b: 2
        };

    var y = x ||
        true;
})();
```

**What did you expect to happen?**

I expected it not to have an error about the indentation on lines 3-6

**What actually happened? Please include the actual, raw output from ESLint.**

```sh
/home/user/test.js
  3:13  error  Expected indentation of 4 space characters but found 8   indent
  4:17  error  Expected indentation of 8 space characters but found 12  indent
  5:17  error  Expected indentation of 8 space characters but found 12  indent
  6:13  error  Expected indentation of 4 space characters but found 8   indent
  8:9   error  'y' is defined but never used                            no-unused-vars

✖ 5 problems (5 errors, 0 warnings)
```

### LINKED ISSUE #7112: `no-restricted-properties` is in the wrong category
https://github.com/eslint/eslint/blob/master/lib/rules/no-restricted-properties.js#L18 is in http://eslint.org/docs/rules/#nodejs-and-commonjs and I'm not sure why - this is a generic rule and has nothing to do with node and commonJS. It seems like "best practices" or "stylistic" is a better category for it?

### PR DESCRIPTION
**Pull request by alecharmon**
**What is the purpose of this pull request? (put an "X" next to item)**

```
[ ] Documentation update
[X] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:
```

*If the item you've check above has a template, please paste the template questions here and answer them.*

**Please check each item to ensure your pull request is ready:**

- [X] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [X] I've included tests for my change
- [X] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**
Changed the category of no-restricted-properties to Best Practices from Node and Common JS

**Is there anything you'd like reviewers to focus on?**
Nope.

…fixes #7112)

### CODE REVIEW

**Comment by TheSavior** [comment]
LGTM

File: lib/rules/no-restricted-properties.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ module.exports = {
     meta: {
         docs: {
             description: "disallow certain properties on certain objects",
-            category: "Node.js and CommonJS",
+            category: "Best Practice",
```
Comment (vitorbal) [inline lib/rules/no-restricted-properties.js]: This should say "Best Practices", with an "s" at the end.

**Comment by vitorbal** [comment]
LGTM. For the record, this should be a "Docs" commit instead of "Fix", but we'll take care of that while merging. Thanks for your contribution, @alecharmon! 🎉
