### PR TITLE
Fix: no-extra-parens autofix with `in` in a for-loop init (fixes #11706)

### LINKED ISSUE #11706: no-extra-parens produces invalid autofix with an `in` expression in a for-loop initializer
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 12.1.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
rules:
  no-extra-parens: error
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
for (let a = (b in c); ;);
```

```bash
eslint --fix
```

**What did you expect to happen?**

I expected ESLint to not produce an error because removing the parentheses would cause a syntax error.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint produced the following invalid autofix:

```js
for (let a = b in c; ;);
```

This is interpreted as an initializer in a for-in loop, which is a syntax error in most cases (and is not the intended semantics of the code).

[Demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczogZXJyb3IgKi9cblxuZm9yIChsZXQgYSA9IChiIGluIGMpOyA7KTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjksInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

This issue was detected by running the fuzzer locally.

**Are you willing to submit a pull request to fix this bug?**

Yes, but not sure when I'll have time.

### PR DESCRIPTION
**Pull request by mdjermanovic**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix: [#11706](https://github.com/eslint/eslint/issues/11706)

**What changes did you make? (Give an overview)**

In the `no-extra-parens` rule, keep parens if necessary when an `in` expression is in a for-loop initializer.

For example, the following will be treated as a correct code (not reported):

```js
for (let a = (b in c); ;);

for (let a = (b in c && d); ;);

for (let a = b => (b in c); ;);
```

Removing parens would produce SyntaxError. Each line would be treated as an invalid for-in loop.

Also, this change is trying to minimize false negatives, i.e. to remove really 'extra' parens.

For example, the following:

```js
for (let a = ((b in c) && (d in e)); ;);
```

would be fixed to:

```js
for (let a = (b in c && d in e); ;);
```

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

File: lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -602,17 +653,79 @@ module.exports = {
...
+
+                let { reports } = forStatementInitInfo;
+
+                if (reports.length) {
+
+                    const { inExpressionNodes } = forStatementInitInfo;
+
+                    inExpressionNodes.forEach(inExpressionNode => {
+                        for (const pathNode of pathToAncestor(inExpressionNode, node).reverse()) {
+                            if (isParenthesised(pathNode)) {
```
Comment (mysticatea) [inline lib/rules/no-extra-parens.js]: I guess any of the following nodes should `break` this loop because wrapping by any of `()`, `[]`, `{}`, and `?:` allows `in` operators.

- Wrapping by `()`
    - `ArrowFunctionExpression` if the child is in `params`.
    - `CallExpression` if the child is in `arguments`.
    - `FunctionExpression` if the child is in `params`.
    - `NewExpression` if the child is in `arguments`.
- Wrapping by `[]`
    - `ArrayExpression`
    - `ArrayPattern`
    - `MemberExpression` if the child is `property` and `computed` is `true`.
- Wrapping by `{}`
    - `BlockStatement`
    - `ObjectExpression`
    - `ObjectPattern`
    - `TemplateLiteral`
- Wrapping by `?:`
    - `ConditionalExpression` if the child is `consequent`.

Comment (mdjermanovic) [reply lib/rules/no-extra-parens.js]: I was aware of this, but eventually decided it might be better not to implement this check, and left a comment at the end of the loop:

```js
 /*
  * Other enclosing punctuators such as {} are omitted from this check,
  * in order to avoid dependencies with other rules.
  *
  * For example, these parentheses might be safe for removal:
  *      for (let a = b => { return (b in c) }; ;);
  * However, arrow-body-style could remove braces as well, and produce an invalid for-in loop:
  *      for (let a = b => b in c; ;);
  */
```

Though now I'm not sure about this particular example because the ranges overlap, perhaps the fixing algorithm would have already removed the braces in the previous iteration (while blocking the parens fix in that iteration).

Also, this additional check might be too much code for an edge case with not-so-terrible consequences (one pair of unnecessary parens will stay) of an already edge case ('in' in a for-loop).

Of course, if this additional check can't produce subsequent errors, and you think it's worth of implementing, I'll do it.

Comment (mysticatea) [reply lib/rules/no-extra-parens.js]: ESLint doesn't apply two fixes which have overlapped range each other at the same time. So I think this will not conflict with `arrow-body-style` rule.

Comment (mdjermanovic) [reply lib/rules/no-extra-parens.js]: Ok, I'll do it by the list you provided

**Comment by mdjermanovic** [comment]
The following is done in this commit:

* The loop now checks `{}`, `[]` etc. by the provided list.
* The logic for twice parenthesized nodes is added.
* The old loop was missing cases like `(!(b in c))` - necessary parens inside the unnecessary ones. This is fixed now.
* A small refactoring to support more cases like this, if they occur.

While doing this I've also found two possible bugs (missing checks) on `master`, I'll open the issues.
