### PR TITLE
fix: reporting variable used in catch block in `no-useless-assignment`

### LINKED ISSUE #19245: Bug: no-useless-assignment false positive in try-catch block
### Environment

Node version: v22.11.0
npm version: v10.9.0
Local ESLint version: v9.17.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 24.1.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
// eslint.config.js
export default [
  {
    rules: {
      "no-useless-assignment": "warn"
    },
  },
];
```
</details>

```js
async function fn() {
  let intermediaryValue;
  try {
    intermediaryValue = 42;
    unsafeFn();
    return { error: undefined };
  } catch {
    return { intermediaryValue };
  }
}

function unsafeFn() {
  throw new Error();
}
```

### What did you expect to happen?

The `intermediaryValue = 42` statement shouldn’t be flagged by the 'no-useless-assignment' rule, as it’s being used in the `catch` block.

### What actually happened?

`intermediaryValue = 42` was flagged as ‘not used in subsequent statements’ by mistake.

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tdXNlbGVzcy1hc3NpZ25tZW50OiBcIndhcm5cIiAqL1xuXG5hc3luYyBmdW5jdGlvbiBmbigpIHtcbiAgbGV0IGludGVybWVkaWFyeVZhbHVlO1xuICB0cnkge1xuICAgIGludGVybWVkaWFyeVZhbHVlID0gNDI7XG4gICAgdW5zYWZlRm4oKTtcbiAgICByZXR1cm4geyBlcnJvcjogdW5kZWZpbmVkIH07XG4gIH0gY2F0Y2gge1xuICAgIHJldHVybiB7IGludGVybWVkaWFyeVZhbHVlIH07XG4gIH1cbn1cblxuZnVuY3Rpb24gdW5zYWZlRm4oKSB7XG4gIHRocm93IG5ldyBFcnJvcigpO1xufVxuIiwib3B0aW9ucyI6eyJydWxlcyI6e30sImxhbmd1YWdlT3B0aW9ucyI6eyJzb3VyY2VUeXBlIjoibW9kdWxlIiwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by Tanujkanti4441**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Tell us about your environment (`npx eslint --env-info`):**

* **Node version:** latest
* **npm version:** latest 
* **Local ESLint version:** latest
* **Global ESLint version:** latest
* **Operating System:** windows

**What parser are you using (place an "X" next to just one item)?**

[x] `Default (Espree)`
[ ] `@typescript-eslint/parser`
[ ] `@babel/eslint-parser`
[ ] `vue-eslint-parser`
[ ] `@angular-eslint/template-parser`
[ ] `Other`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
// eslint.config.js
export default [
  {
    rules: {
      "no-useless-assignment": "warn"
    },
  },
];
```

</details>

**What did you do? Please include the actual source code causing the issue.**\
```js
async function fn() {
  let intermediaryValue;
  try {
    intermediaryValue = 42;
    unsafeFn();
    return { error: undefined };
  } catch {
    return { intermediaryValue };
  }
}

function unsafeFn() {
  throw new Error();
}
```

**What did you expect to happen?**
`intermediaryValue` won't get reported as it is used in `catch` block.

**What actually happened? Please include the actual, raw output from ESLint.**
it reports the `intermediaryValue` as unused variable.

#### Is there anything you'd like reviewers to focus on?
fixes #19245

### CODE REVIEW

**Review by nzakas — APPROVED** [review]
LGTM. Would like @mdjermanovic to review before merging.

File: lib/rules/no-useless-assignment.js [hunk 1]
```diff
@@ -555,6 +555,26 @@ module.exports = {
...
+                    const isUsedInCatchClause = variable.references.some(reference => {
+                        let currentNode = reference.identifier.parent;
+
+                        if (currentNode.type !== "AssignmentExpression") {
+                            while (currentNode) {
+                                if (currentNode.type === "CatchClause") {
+                                    return true;
+                                }
+                                currentNode = currentNode.parent;
+                            }
```
Comment (mdjermanovic) [inline lib/rules/no-useless-assignment.js:568]: This search up to the root increases the timing for this rule by around 20% when linting this project. Can we maybe store `CatchClause` nodes in `scopeStack`, and at some later point check whether a reference is in the range of some of them?

Comment (mdjermanovic) [reply lib/rules/no-useless-assignment.js:568]: Can you push the changes with a test case that doesn't work due to this so I can take a look?

File: lib/rules/no-useless-assignment.js [hunk 2]
```diff
@@ -6,6 +6,7 @@
 "use strict";
 
 const { findVariable } = require("@eslint-community/eslint-utils");
+const { cat } = require("shelljs");
```
Comment (mdjermanovic) [inline lib/rules/no-useless-assignment.js:9]:
```suggestion
```

This seems accidentally added.

File: lib/rules/no-useless-assignment.js (hunk 1 above)
Comment (mdjermanovic) [reply lib/rules/no-useless-assignment.js]: Catch clauses are stored when they're traversed, but we're checking them before they're traversed, so we'd need to move the check somewhere inside `function verify`.

File: lib/rules/no-useless-assignment.js [hunk 3]
```diff
@@ -445,7 +447,8 @@ module.exports = {
                     scope,
                     segments: Object.create(null),
                     currentSegments: new Set(),
-                    assignments: new Map()
+                    assignments: new Map(),
+                    catchClauses: new Set()
```
Comment (mdjermanovic) [inline lib/rules/no-useless-assignment.js:451]: Can this be an array instead of Set, since we're only using it as an array?

Comment (Tanujkanti4441) [reply lib/rules/no-useless-assignment.js]: Done!

File: lib/rules/no-useless-assignment.js [hunk 4]
```diff
@@ -229,6 +230,22 @@ module.exports = {
              */
             function verifyAssignmentIsUsed(targetAssignment, allAssignments) {
 
+                // Check if the variable is used in a catch clause
+                const isUsedInCatchClause = targetAssignment.variable.references.some(reference => {
+                    const id = reference.identifier;
+
+                    if (id.parent.type !== "AssignmentExpression") {
```
Comment (mdjermanovic) [inline lib/rules/no-useless-assignment.js:237]: I think this case would remain a false negative:

```js
function foo(){
    let bar, baz;
    try {
        bar = 2;
        unsafeFn();
        return { error: undefined };
    } catch {
        baz = bar;
    }
    return baz;
}
function unsafeFn() {
    throw new Error();
}
```

If the check for `AssignmentExpression` is intended to skip write-only references, we can use `reference.isRead()` instead.

File: tests/lib/rules/no-useless-assignment.js [hunk 5]
```diff
@@ -370,6 +370,35 @@ ruleTester.run("no-useless-assignment", rule, {
...
+            throw new Error();
+        }`,
+        `function foo(){
+            let bar, baz;
+            try {
+                bar = 2;
+                unsafeFn();
+                return { error: undefined };
+            } catch {
+                bar = baz;
```
Comment (mdjermanovic) [inline tests/lib/rules/no-useless-assignment.js:395]:
```suggestion
                baz = bar;
```

File: lib/rules/no-useless-assignment.js [hunk 6]
```diff
@@ -229,6 +230,22 @@ module.exports = {
              */
             function verifyAssignmentIsUsed(targetAssignment, allAssignments) {
 
+                // Check if the variable is used in a catch clause
+                const isUsedInCatchClause = targetAssignment.variable.references.some(reference => {
+                    const id = reference.identifier;
+
+                    if (reference.isRead()) {
+                        return [...scopeStack.catchClauses].some(catchClause =>
```
Comment (mdjermanovic) [inline lib/rules/no-useless-assignment.js:238]:
```suggestion
                        return [...target.catchClauses].some(catchClause =>
```

Since this function checks the given `target` ScopeStack.

**Comment by mdjermanovic** [comment]
After thinking about this more, the problem is not only when variables are used in catch blocks. For example, this would still be a false positive:

```js
/*eslint no-useless-assignment: "error" */

function fn() {
    let intermediaryValue;
    try {
        intermediaryValue = 42; // false positive
        unsafeFn();
        intermediaryValue = 55;
    } catch {
        // handle error
    }

    return intermediaryValue;
}

function unsafeFn() {
    throw new Error();
}

console.log(fn()); // 42
```

So, I think instead of ignoring variables that are used in catch blocks, the rule should ignore assignments in try blocks.

**Comment by Tanujkanti4441** [comment]
> So, I think instead of ignoring variables that are used in catch blocks, the rule should ignore assignments in try blocks.

Done! should we document it also?

**Comment by mdjermanovic** [comment]
> > So, I think instead of ignoring variables that are used in catch blocks, the rule should ignore assignments in try blocks.
> 
> Done! should we document it also?

I think it's a good idea to add a Known Limitations section with this detail.

File: lib/rules/no-useless-assignment.js [hunk 7]
```diff
@@ -229,6 +230,22 @@ module.exports = {
...
+                        return target.tryStatementBlocks.some(tryBlock =>
+                            tryBlock.range[0] <= id.range[0] && id.range[1] <= tryBlock.range[1]);
+                    }
+
+                    return false;
+                });
+
+                if (isAssignedInTryBlock) {
+                    return;
+                }
```
Comment (mdjermanovic) [inline lib/rules/no-useless-assignment.js:247]: Instead of entirely ignoring a variable if it has an assignment in a try block, can we just ignore that assignment (i.e., skip checking `targetAssignment` if it's in a try block)? I think that would restore now-removed `invalid` test cases.

Comment (Tanujkanti4441) [reply lib/rules/no-useless-assignment.js]: Done!

**Review by mdjermanovic — DISMISSED** [review]
LGTM, thanks! Leaving open for @nzakas to re-review.

File: docs/src/rules/no-useless-assignment.md [hunk 8]
```diff
@@ -151,6 +151,41 @@ function fn() {
 
 :::
 
+## Known Limitations
+
+This rule does not report certain variable reassignments when they occur inside `try` block. This is intentional because such assignments may still be observed within the corresponding `catch` block or after the `try-catch` structure, due to potential early exits or error handling logic.
```
Comment (snitin315) [inline docs/src/rules/no-useless-assignment.md:156]:
```suggestion
This rule does not report certain variable reassignments when they occur inside the `try` block. This is intentional because such assignments may still be observed within the corresponding `catch` block or after the `try-catch` structure, due to potential early exits or error handling logic.
```

**Review by snitin315 — APPROVED** [review]
LGTM, thanks!

**Review by nzakas — APPROVED** [review]
LGTM. Thanks, and nice work on this.
