### PR TITLE
Fix: id-length rule incorrectly firing on member access (fixes #6475)

### LINKED ISSUE #6475: id-length rule not firing on a ternary
**What version of ESLint are you using?**

2.11.1

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>
```yaml
---

# Use babel-eslint parser in order to support babel plugins
# necessary to e.g. strip Flowtype annotations

parser: babel-eslint

parserOptions:
  ecmaVersion: 6
  impliedStrict: true
  ecmaFeatures:
    arrowFunctions: true
    blockBindings: true
    classes: true
    defaultParams: true
    destructuring: true
    forOf: true
    generators: false
    modules: true
    objectLiteralComputedProperties: true
    objectLiteralDuplicateProperties: false
    objectLiteralShorthandMethods: true
    objectLiteralShorthandProperties: true
    spread: true
    superInFunctions: true
    templateStrings: true
    jsx: true

env:
  browser: true
  mocha: true

globals:
  expect: false

plugins:
  - react

extends:
  - eslint:recommended
  - plugin:react/recommended

rules:

  # Babel inserts 'use strict' for us already
  strict:
    - error
    - never


  # Best Practices

  array-callback-return: error
  complexity:
    - error
    - 5
  curly: error
  default-case: error
  dot-notation: error
  eqeqeq: error
  no-alert: error
  no-div-regex: error
  no-empty-function: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-multi-spaces: error
  no-multi-str: error
  no-native-reassign: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-param-reassign:
    - error
    - props: true
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-void: error
  no-warning-comments: warn
  no-with: error
  wrap-iife: error
  yoda: error


  # Variables

  init-declarations: error
  no-shadow:
    - error
    - hoist: all
  no-shadow-restricted-names: error
  no-use-before-define: error


  # Stylistic

  array-bracket-spacing:
    - error
    - always
  brace-style: error
  camelcase: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing:
    - error
    - always
  consistent-this: error
  eol-last: error
  id-length: error
  indent:
    - error
    - 2
    - SwitchCase: 1
  key-spacing: error
  keyword-spacing: error
  linebreak-style: error
  max-depth:
    - error
    - 5
  max-len:
    - error
    - 120
  max-nested-callbacks:
    - error
    - 4
  max-params:
    - error
    - 4
  max-statements:
    - error
    - 14
  max-statements-per-line: error
  new-cap: error
  new-parens: error
  newline-after-var: error
  newline-before-return: error
  newline-per-chained-call: error
  no-array-constructor: error
  no-bitwise: error
  no-continue: error
  no-inline-comments: error
  no-lonely-if: error
  no-mixed-spaces-and-tabs: error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
      maxBOF: 0
  no-negated-condition: error
  no-new-object: error
  no-plusplus: error
  no-restricted-syntax:
    - error
    - TryStatement
    - FunctionDeclaration
  no-spaced-func: error
  no-trailing-spaces:
    - error
    - skipBlankLines: true
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
    - allowMultiplePropertiesPerLine: true
  one-var:
    - error
    - never
  operator-assignment: error
  operator-linebreak:
    - error
    - before
  padded-blocks:
    - error
    - blocks: never
      switches: always
      classes: always
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
  semi:
    - error
    - never
  space-before-blocks: error
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
  space-unary-ops: error
  spaced-comment: error
  unicode-bom: error


  # ESerror015

  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-var: error
  object-shorthand: error
  prefer-const: error
  prefer-spread: error
  prefer-template: error
  template-curly-spacing:
    - error
    - always


  # React

  react/jsx-boolean-value: error
  react/jsx-curly-spacing:
    - error
    - always
  react/jsx-equals-spacing: error
  react/jsx-handler-names: error
  # react/jsx-indent:
  #   - error
  #   - 2
  react/jsx-indent-props:
    - error
    - 2
  react/jsx-key: error
  react/jsx-no-bind: error
  react/jsx-no-target-blank: error
  react/jsx-pascal-case: error
  react/jsx-space-before-closing: error
  react/no-multi-comp: error
  react/prefer-stateless-function: error
  react/prop-types: off
  #react/require-optimization: error
  react/self-closing-comp: error
  react/sort-comp: error
  react/wrap-multilines: error
```
</details>

**What did you do? Please include the actual source code causing the issue.**

Note line 12 of this file, marked with "Issue":
```js
// @flow

import { RESULTS_ROUTE } from '/routes'

import { fetchDetails, setQuery, setAndFetchQuery } from '/actions'

export const onDetailsEnter = (dispatch) =>
  ({ params }) => dispatch(fetchDetails(params.id))

export const onLocationChange = (dispatch) =>
  (location) => {
    const query = location.query.q ? location.query.q : ''  // Issue

    if (location.pathname === RESULTS_ROUTE) {
      dispatch(setAndFetchQuery(query))
    } else {
      dispatch(setQuery(query))
    }
  }
```

**What did you expect to happen?**

The id-length rule to fire due to the `.q` property access.

**What actually happened? Please include the actual, raw output from ESLint.**

The id-length rule did not fire - there was no output from ESLint, no warnings or errors. This happens in both my editor which runs it on the one file, and when running ESLint from the project level.

If I change that line to instead use a boolean operator like so:
```js
    const query = location.query.q || ''
```

Then the rule *does* fire.

### PR DESCRIPTION
**Pull request by BYK**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Corrected the `MemberExpression` check on the parent node when determining assignment to an object property.

**Is there anything you'd like reviewers to focus on?**

Nope.

### CODE REVIEW

File: lib/rules/id-length.js [hunk 1]
```diff
@@ -61,7 +61,7 @@ module.exports = {
                 return !parent.computed && (
 
                     // regular property assignment
-                    (parent.parent.left === parent || // or the last identifier in an ObjectPattern destructuring
+                    (parent.parent.left === parent && parent.parent.type === "AssignmentExpression" ||  // or the last identifier in an ObjectPattern destructuring
```
Comment (kaicataldo) [inline lib/rules/id-length.js]: I know this isn't something you changed, but the location of this comment is weird - maybe add it to the comment above?

File: tests/lib/rules/id-length.js [hunk 2]
```diff
@@ -35,6 +35,7 @@ ruleTester.run("id-length", rule, {
         "var xyz = new ΣΣ();",
         "unrelatedExpressionThatNeedsToBeIgnored();",
         "var obj = { 'a': 1, bc: 2 }; obj.tk = obj.a;",
+        "var query = location.query.q || '';",
```
Comment (kaicataldo) [inline tests/lib/rules/id-length.js]: I don't see any pre-existing tests with a ternary - maybe we should add some?

Comment (BYK) [inline tests/lib/rules/id-length.js]: I don't think we need a ternary-specific test but I can add if you feel strongly about it.

File: lib/rules/id-length.js (hunk 1 above)
Comment (BYK) [inline lib/rules/id-length.js]: Can do. Probably I was the one who added this comment earlier :)

File: tests/lib/rules/id-length.js (hunk 2 above)
Comment (kaicataldo) [inline tests/lib/rules/id-length.js]: It does seem valuable as a regression test to me, since we're trying to ensure that both this case and ternaries are treated similarly

Comment (BYK) [inline tests/lib/rules/id-length.js]: Done
