### PR TITLE
Update: fix false positive/negative of yoda rule (fixes #7676)

### LINKED ISSUE #7676: yoda's exceptRange option has false positive
**Tell us about your environment**

* **ESLint Version:** 3.11.1
* **Node Version:** chrome 55 (our online demo)
* **npm Version:** -

**What parser (default, Babel-ESLint, etc.) are you using?**

- default

**Please show your full configuration:**

- nothing

**What did you do? Please include the actual source code causing the issue.**

```js
/*eslint yoda: [error, never, {exceptRange: true}] */

function get(list, index) {
    if (0 <= index && index < list.length) {
        return list[index]
    }
}
```

**What did you expect to happen?**

No errors since the condition is a range check.

**What actually happened? Please include the actual, raw output from ESLint.**

[yoda](http://eslint.org/docs/rules/yoda) rule is warning the code.

image

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

See #7676 for the template.

**What changes did you make? (Give an overview)**

The `yoda` rule has a false positive and a false negative.
This PR fixes those bugs.

- c62b847c9d84363663d267c6804700735ffe29b4 fixed the false negative about computed properties in the range check.

  ```js
  /*eslint yoda: [error, never, {exceptRange: true}] */
  if (0 <= a.b && a[b] < 10) {}
  ```

  The `yoda` rule has been handling `a.b` and `a[b]` as the same then it determines the condition is a range check wrongly. As the result, it should warn the `0 <= a.b` but does not warn it. After this PR is applied, the `yoda` rule will warn the `0 <= a.b` correctly. (semver-minor)

- bf9982f71f47488d9d165bf88722c34ee28d933e fixed the false positive about variables in the range check.

  ```js
  /*eslint yoda: [error, never, {exceptRange: true}] */
  if (0 <= index && index < list.length) {}
  ```

  The `yoda` rule has not been handling `0 <= index && index < list.length` as a range check wrongly. As the result, it should not warn `0 <= index` but warns it. After this PR is applied, the `yoda` rule will ignore the `0 <= index && index < list.length` correctly. (semver-patch)

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

**Comment by mysticatea** [comment]
@platinumazure Thank you!
I updated this PR for it.

File: lib/rules/yoda.js [hunk 1]
```diff
@@ -54,13 +54,15 @@ function looksLikeLiteral(node) {
 /**
  * Attempts to derive a Literal node from nodes that are treated like literals.
  * @param {ASTNode} node Node to normalize.
+ * @param {number} [defaultValue] The default value to be returned if the node
+ *                                is not a Literal.
  * @returns {ASTNode} The original node if the node is already a Literal, or a
  *                    normalized Literal node with the negative number as the
  *                    value if the node represents a negative number literal,
  *                    otherwise null if the node cannot be converted to a
  *                    normalized literal.
```
Comment (btmills) [inline lib/rules/yoda.js]: Can you update the return value description to note when it will return the default value?

Comment (mysticatea) [inline lib/rules/yoda.js]: Thank you, I updated the JSDoc comment.
