### PR TITLE
Fix: implicit-arrow-linebreak adds extra characters (fixes #11268)

### LINKED ISSUE #11268: implicit-arrow-linebreak autofixer sometimes adds extra characters
**Tell us about your environment**

* **ESLint Version:** 5.12.0
* **Node Version:** 10.15.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**

`babel-eslint` (but i dont believe it matters)

<br />
<details>
<summary>Configuration</summary>

```json
{
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module"
  },
  "env": {
    "node": true
  },
  "rules": {
    "implicit-arrow-linebreak": "error"
  }
}
```

</details>
<br />

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

* [Demo](https://eslint.org/demo/#eyJ0ZXh0Ijoic3RhcnQoKVxuICAudGhlbigoKSA9PiBcbiAgICAvKiBJZiBJIHB1dCBhIGNvbW1lbnQgaGVyZSwgZXNsaW50IC0tZml4IGJyZWFrcyBiYWRseSAqL1xuICAgIHByb2Nlc3MgJiYgdHlwZW9mIHByb2Nlc3Muc2VuZCA9PT0gJ2Z1bmN0aW9uJyAmJiBwcm9jZXNzLnNlbmQoJ3JlYWR5JylcbiAgKVxuICAuY2F0Y2goZXJyID0+IHtcbiAgXHQvKiBjYXRjaCBzZWVtcyB0byBiZSBuZWVkZWQgaGVyZSAqL1xuICBcdGNvbnNvbGUubG9nKCdFcnJvcjogJywgZXJyKTtcbiAgfSlcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6MiwiZm9yLWRpcmVjdGlvbiI6MiwiZ2V0dGVyLXJldHVybiI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbnNvbGUiOjIsIm5vLWNvbnN0LWFzc2lnbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZHVwZS1hcmdzIjoyLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLWR1cGUta2V5cyI6Miwibm8tZHVwbGljYXRlLWNhc2UiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZW1wdHkiOjIsIm5vLWV4LWFzc2lnbiI6Miwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjoyLCJuby1leHRyYS1zZW1pIjoyLCJuby1mYWxsdGhyb3VnaCI6Miwibm8tZnVuYy1hc3NpZ24iOjIsIm5vLWdsb2JhbC1hc3NpZ24iOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1zZWxmLWFzc2lnbiI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjIsImltcGxpY2l0LWFycm93LWxpbmVicmVhayI6Mn0sImVudiI6eyJicm93c2VyIjp0cnVlLCJub2RlIjp0cnVlLCJjb21tb25qcyI6dHJ1ZSwic2hhcmVkLW5vZGUtYnJvd3NlciI6dHJ1ZSwid29ya2VyIjp0cnVlLCJhbWQiOnRydWUsIm1vY2hhIjp0cnVlLCJqYXNtaW5lIjp0cnVlLCJqZXN0Ijp0cnVlLCJwaGFudG9tanMiOnRydWUsImpxdWVyeSI6dHJ1ZSwicXVuaXQiOnRydWUsInByb3RvdHlwZWpzIjp0cnVlLCJzaGVsbGpzIjp0cnVlLCJtZXRlb3IiOnRydWUsIm1vbmdvIjp0cnVlLCJwcm90cmFjdG9yIjp0cnVlLCJhcHBsZXNjcmlwdCI6dHJ1ZSwibmFzaG9ybiI6dHJ1ZSwic2VydmljZXdvcmtlciI6dHJ1ZSwiYXRvbXRlc3QiOnRydWUsImVtYmVydGVzdCI6dHJ1ZSwid2ViZXh0ZW5zaW9ucyI6dHJ1ZSwiZXM2Ijp0cnVlLCJncmVhc2Vtb25rZXkiOnRydWV9fX0=)

```js
start()
  .then(() => 
    /* If I put a comment here, eslint --fix breaks badly */
    process && typeof process.send === 'function' && process.send('ready')
  )
  .catch(err => {
  	/* catch seems to be needed here */
       console.log('Error: ', err)
  })

```

```bash
eslint --fix
```

**What did you expect to happen?**

Code that it "fixes" should not be invalid javascript

**What actually happened? Please include the actual, raw output from ESLint.**

It creates broken code

```javascript
start()
  .then(() => ( 
    /* If I put a comment here, eslint --fix breaks badly */
    process && typeof process.send === 'function' && process.send('ready')
         )
        )
  )
  .catch(err => ( {
  	/* catch seems to be needed here */
       console.log('Error: ', err)
  })
```

> Notice that it broke the catch as it seems to assume its an implicit object return 

**Are you willing to submit a pull request to fix this bug?**

not really, wouldnt know where to start

---

This can get REALLY bad and is especially an issue since its part of `eslint-config-airbnb`, granted this file is crazy, but the bug ends up filling the entire file up with thousands of invalid lines

image

### PR DESCRIPTION
**Pull request by peanutenthusiast**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ x ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes [11268](https://github.com/eslint/eslint/issues/11268)

**What changes did you make? (Give an overview)**
The original auto-fix calculated white spaces into formatting comments and parentheses, which was the cause for extra characters.

The cause for extra parentheses was due to [this line](https://github.com/eslint/eslint/pull/11407/files#diff-6c1dbab61fffc096eef30d3fdaf8219cR122), which searched for arrow functions that followed the evaluated arrow function within the source code.

This PR removes the calculation of white spaces, and [more accurately](https://github.com/eslint/eslint/pull/11407/files#diff-6c1dbab61fffc096eef30d3fdaf8219cR122) finds nested arrow functions within the evaluated node.

**Is there anything you'd like reviewers to focus on?**
Please provide/suggest any other test cases if necessary.

### CODE REVIEW

File: tests/lib/rules/implicit-arrow-linebreak.js [hunk 1]
```diff
@@ -201,24 +201,24 @@ ruleTester.run("implicit-arrow-linebreak", rule, {
             errors: [UNEXPECTED_LINEBREAK]
         }, {
             code: `
-                (foo) =>
-                  // test comment
-                  bar
```
Comment (not-an-aardvark) [inline tests/lib/rules/implicit-arrow-linebreak.js]: Could these tests use something like the [`unIndent`](https://github.com/eslint/eslint/blob/af9688b7c4f6a3afe1b0ca5ba2f475c545e0309b/tests/lib/rules/indent.js#L57-L69) function that the `indent` tests use, rather than being aligned all the way to the left?

File: lib/rules/implicit-arrow-linebreak.js [hunk 2]
```diff
@@ -161,7 +155,9 @@ module.exports = {
                     ) {
 
                         // If any arrow functions follow, return the necessary parens fixes.
-                        if (sourceCode.getTokenAfter(arrowToken, isArrowToken) && arrowBody.parent.parent.type !== "VariableDeclarator") {
+                        if (sourceCode.getTokenAfter(arrowToken, isArrowToken) &&
```
Comment (not-an-aardvark) [inline lib/rules/implicit-arrow-linebreak.js]: I know this code was here before, but I'm confused about what it's doing. Wouldn't this condition be true if there is any following arrow token anywhere, even if it's in a different part of the file?

File: lib/rules/implicit-arrow-linebreak.js [hunk 3]
```diff
@@ -109,18 +108,13 @@ module.exports = {
             let followingBody = arrowBody;
             let currentArrow = arrow;
 
-            while (currentArrow) {
+            while (currentArrow && followingBody.value !== "{") {
```
Comment (not-an-aardvark) [inline lib/rules/implicit-arrow-linebreak.js]: I'm confused by this line. According to the JSDoc comment, isn't `arrowBody` an AST node rather than a token? I don't understand how it would have a `value` property.

File: tests/lib/rules/implicit-arrow-linebreak.js (hunk 1 above)
Comment (peanutenthusiast) [reply tests/lib/rules/implicit-arrow-linebreak.js]: @not-an-aardvark Just used the linked `unIndent` function and all tests are passing. I see that the `tests` folder doesn't have a `testhelpers.js` file. Would it be alright to move the above linked `unIndent` function into such a file? Otherwise, I will copy paste this into the tests for this rule.

File: lib/rules/implicit-arrow-linebreak.js (hunk 2 above)
Comment (peanutenthusiast) [reply lib/rules/implicit-arrow-linebreak.js]: Good point. With this in mind, the upcoming commit uses `getFirstTokenBetween` to check between the `arrowToken` and last token of the evaluated node to avoid checking different parts of the file.

File: tests/lib/rules/implicit-arrow-linebreak.js (hunk 1 above)
Comment (peanutenthusiast) [reply tests/lib/rules/implicit-arrow-linebreak.js]: The upcoming commit does not do this, but can do so if agreed upon.

File: lib/rules/implicit-arrow-linebreak.js (hunk 3 above)
Comment (peanutenthusiast) [reply lib/rules/implicit-arrow-linebreak.js]: Changed the `arrowBody` param type to be `{ASTNode|Token}`. Thank you for clarifying!

File: tests/lib/rules/implicit-arrow-linebreak.js (hunk 1 above)
Comment (not-an-aardvark) [reply tests/lib/rules/implicit-arrow-linebreak.js]: I'd be fine with moving it to a separate file, but I think copy-pasting it is probably fine for now too.

File: lib/rules/implicit-arrow-linebreak.js (hunk 3 above)
Comment (not-an-aardvark) [reply lib/rules/implicit-arrow-linebreak.js]: Thanks for making that change. I suppose my question is a bit more general -- what are `followingBody` and `arrowBody` actually supposed to be? From the name `arrowBody` I would expect it to be the `body` of the AST node for the arrow function, or perhaps the first token of that AST node. But if I'm understanding correctly, the value might be something before the body, and `followingBody` only reaches the first token of the body (`{`) at the end of the loop. Is `arrowBody` actually just the first token after the arrow token?

**Comment by not-an-aardvark** [comment]
Thanks for continuing to work on this!

I'm probably missing something given that the tests are passing, but could you clarify which part of the change prevents the extra closing parentheses from being added? I would have guessed the change happens due to one fewer loop iteration on line 111, but it seems like that only applies to nodes containing nested arrow functions, which isn't the case for the example from https://github.com/eslint/eslint/issues/11268.

File: lib/rules/implicit-arrow-linebreak.js (hunk 3 above)
Comment (peanutenthusiast) [reply lib/rules/implicit-arrow-linebreak.js]: `followingBody` and `arrowBody` _should_ refer to the body of the arrow function. Prior to the new changes, this wasn't the case -- thank you for asking these questions, as the new changes ensure they are as expected.

**Comment by peanutenthusiast** [comment]
@not-an-aardvark [This line](https://github.com/eslint/eslint/pull/11407/files#diff-6c1dbab61fffc096eef30d3fdaf8219cR122) in the code prevents extra closing parentheses from being added by navigating to the body of the arrow function, and [this line](https://github.com/eslint/eslint/pull/11407/files#diff-6c1dbab61fffc096eef30d3fdaf8219cR111) prevents the appending of extra parentheses.

**Comment by not-an-aardvark** [comment]
Both of those lines are in the `addParentheses` function. Is the JSDoc comment for that function out of date? The comment says that the function only applies to code containing nested arrow functions, but the example code from https://github.com/eslint/eslint/issues/11268 doesn't contain nested arrow functions.

**Comment by peanutenthusiast** [comment]
@not-an-aardvark Thanks for clarifying! Given the example code from #11268 
```js
start()
  .then(() => 
    /* If I put a comment here, eslint --fix breaks badly */
    process && typeof process.send === 'function' && process.send('ready')
  )
  .catch(err => {
  	/* catch seems to be needed here */
       console.log('Error: ', err)
  })

```
when `eslint --fix` is applied, the output becomes
```
  /* If I put a comment here, eslint --fix breaks badly */
start()
   .then(() => process && typeof process.send === 'function' && process.send('ready')
    )
   .catch(err => {
    /* catch seems to be needed here */
   console.log('Error: ', err)
    })
```
And the output for this test case
```js
hello(response =>
  // comment
  response, param => param)
```
becomes
```js
// comment
hello(response => response, param => param)
```
Prior to this PR, The JSDoc for `addParentheses` was incorrect in finding any arrow functions that followed. The above linked line as well [this one](https://github.com/eslint/eslint/pull/11407/files#diff-6c1dbab61fffc096eef30d3fdaf8219cR157) in `autoFixBesides` ensure that only nested arrow functions are targeted. Please let me know if any other test cases should be handled.
