### PR TITLE
Fix: clone config before validating (fixes #12592)

### LINKED ISSUE #12592: Schema validation modifies exported config object in .eslintrc.js
**Tell us about your environment**

* **ESLint Version:** 6.7.0
* **Node Version:** 12.13.1
* **npm Version:** 6.12.1

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
// .eslintrc.basic.js
module.exports = {
  plugins: [],

  extends: [
    'eslint:all'
  ],

  parser: 'espree',

  parserOptions: {
    ecmaVersion: 7,
    sourceType: 'module'
  },

  settings: {},

  env: {
    es6: true
  },

  rules: {
    'camelcase': ['warn', {properties: 'never'}]
  }
}

// .eslintrc.babel.js
let _basic = require('./.eslintrc.basic');

module.exports = {
  parser: 'babel-eslint',

  parserOptions: {
    sourceType: 'module'
  },

  plugins: [
    'babel'
  ],

  rules: {
    camelcase: 'off',
    'babel/camelcase': _basic.rules.camelcase
  }
};

// .eslintrc.js
module.exports: {
  extends: [
    './.eslintrc.basic.js',
    './.eslintrc.babel.js'
  ]
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
N/A
```

```bash
N/A
```

**What did you expect to happen?**

I expected no errors.

**What actually happened? Please include the actual, raw output from ESLint.**

```
	Configuration for rule "babel/camelcase" is invalid:
	Value {"properties":"never","ignoreDestructuring":false,"ignoreImports":false} should NOT have additional properties.
```

This happens because of https://github.com/eslint/eslint/pull/12528 adding `ignoreImports` with default value `failse`, and because the defaults of `camelcase` are merged into the same object in `.eslintrc.basic.js:rules.camelcase`, which is also the same reference in `.eslintrc.babel.js:rules.@babel/camelcase`.

**Are you willing to submit a pull request to fix this bug?**

Sure.

### PR DESCRIPTION
**Pull request by anikethsaha**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Cloning the rule config and other configs before validating them as they get mutated with default values when used `useDefault : true`  in `agv`. 
I couldn't find any other entry point for this issue other than this, do let me know if any!

#### Is there anything you'd like reviewers to focus on?

fixes https://github.com/eslint/eslint/issues/12592

### CODE REVIEW

**Comment by kaicataldo** [comment]
Thanks for working on this!

**Comment by anikethsaha** [comment]
> Can we clone the config at a higher level and then pass that to the validator function?

By higher level, you meant where we are reading/getting the config? then I think it needs to pass two configs to the validator one cloned and one original. cause only the cloned one will be validated. the original one will be passed to the rules

**Comment by kaicataldo** [comment]
Is there a reason we can't clone the config as soon as we have the full resolved config and use that for validation and then pass that to the rules?

**Comment by anikethsaha** [comment]
i will try that  👍

**Comment by anikethsaha** [comment]
@kaicataldo I updated the cloning to a higher level.
I think I might have missed some other entry points for configs.

Also, do you think it would be helpful to add a clone [`here`](https://github.com/eslint/eslint/blob/76324ace67893c3d7e38a369114d6128df9ffb65/lib/cli-engine/config-array-factory.js#L803-L809) instead

https://github.com/eslint/eslint/blob/76324ace67893c3d7e38a369114d6128df9ffb65/lib/cli-engine/config-array-factory.js#L803-L809

Like this

```js
if (configData) {
  const clonedConfigData = lodash.cloneDeep(configData);
  return this._normalizeConfigData(
    clonedConfigData,
    plugin.filePath,
    `${importerName} » plugin:${plugin.id}/${configName}`
  );
}
```

**Comment by anikethsaha** [comment]
@aladdin-add can you check if the current one is fine ?

let me know if this has to be changed. after that, I will add some tests

**Comment by aladdin-add** [comment]
I'd suggest it in something like `linter.js`, than in `getRuleOptions` -- it could be cloned multi-times.

**Comment by anikethsaha** [comment]
> I'd suggest it in something like `linter.js`, than in `getRuleOptions`

I think the current one in this PR is something like this. 

earlier I planned to have it clone and validate in `config-validator.js` alone. In this way, it will clone every config irrespective of where they are coming from.

But I think the current one is the entry point for the config (not for the directives,)

**Comment by anikethsaha** [comment]
@kaicataldo can you please take a look if this is the fine place to clone?

**Comment by nzakas** [comment]
@kaicataldo can you take a look at this again?

**Comment by kaicataldo** [comment]
Apologies for the delay! I've been sick the last few weeks and am just getting caught up.

File: lib/linter/linter.js [hunk 1]
```diff
@@ -393,7 +393,9 @@ function getDirectiveComments(filename, ast, ruleMapper, warnInlineConfig) {
                         }
 
                         try {
-                            validator.validateRuleOptions(rule, name, ruleValue);
+                            const cloneRuleValue = lodash.cloneDeep(ruleValue);
```
Comment (kaicataldo) [inline lib/linter/linter.js:396]: Since this configuration exists in a comment that is parsed, do we need to do this? It doesn't seem like it we'll ever be in danger of modifying anything by reference.

File: lib/linter/linter.js [hunk 2]
```diff
@@ -584,10 +586,17 @@ function stripUnicodeBOM(text) {
 /**
  * Get the options for a rule (not including severity), if any
  * @param {Array|number} ruleConfig rule configuration
+ * @param {string} ruleId rule id
+ * @param {Object} rule rule schema
  * @returns {Array} of rule options, empty Array if none
  */
-function getRuleOptions(ruleConfig) {
+function getRuleOptions(ruleConfig, ruleId = "", rule = {}) {
```
Comment (kaicataldo) [inline lib/linter/linter.js:593]: I agree with [this comment](https://github.com/eslint/eslint/pull/13034#pullrequestreview-386547863). Would it be possible to clone any config files we read from the file system at the time we read them, rather than only cloning `rules` key? Seems like it would be safest to never reference the original config object from within ESLint itself.

Comment (anikethsaha) [reply lib/linter/linter.js:593]: [here](https://github.com/eslint/eslint/blob/master/lib/cli-engine/config-array-factory.js#L625) ?

or in you want to clone while loading then may be [here](https://github.com/eslint/eslint/blob/master/lib/cli-engine/config-array-factory.js#L493-L496) ?

File: lib/linter/linter.js (hunk 1 above)
Comment (anikethsaha) [reply lib/linter/linter.js:396]: if we are cloning in the CLI scope (either of these https://github.com/eslint/eslint/pull/13034#discussion_r413592713) then I  think no need to cloning here or anywhere which is currently done in this PR.  
So as you mentioned (https://github.com/eslint/eslint/pull/13034#discussion_r413486744) it would be better to clone while reading the config .

File: lib/linter/linter.js (hunk 2 above)
Comment (kaicataldo) [reply lib/linter/linter.js:593]: Thanks, this is more along the lines of what I was thinking of. I'm not terribly familiar with this part of our codebase and will have to make sure this covers all of our use cases, but I think [this spot](https://github.com/eslint/eslint/blob/6b7030b1a1e1e3d1a3953cfa9722074d6a6fc1a9/lib/cli-engine/config-array-factory.js#L625) makes sense!

Comment (anikethsaha) [reply lib/linter/linter.js]: done

File: lib/cli-engine/config-array-factory.js [hunk 3]
```diff
@@ -623,7 +624,9 @@ class ConfigArrayFactory {
      * @private
      */
     _normalizeConfigData(configData, ctx) {
-        validateConfigSchema(configData, ctx.name || ctx.filePath);
+        const clonedConfig = lodash.cloneDeep(configData);
+
+        validateConfigSchema(clonedConfig, ctx.name || ctx.filePath);
```
Comment (aladdin-add) [inline lib/cli-engine/config-array-factory.js:629]: 👍 it seems a better place!

File: tests/lib/rules/camelcase.js [hunk 4]
```diff
@@ -790,6 +794,25 @@ ruleTester.run("camelcase", rule, {
...
+        },
+        {
+            code: "var obj = { mem_var: 1 };",
+            options: [{}],
+            errors: [{
+                messageId: "notCamelCase",
+                data: { name: "mem_var" },
+                type: "Identifier"
+            }]
+        },
```
Comment (aladdin-add) [inline tests/lib/rules/camelcase.js:815]: the test looks good to have, but not to test the change?

Comment (anikethsaha) [reply tests/lib/rules/camelcase.js:815]: this issue was originated because `babel/camelcase` has less option than the base rule so it was mutating with the option of the base rule while validating. So I can try integration testing with `eslint-plugin-babel` which will need this package as devdependency. 
Any other suggestions? cause with core rule, it seems working fine. It would be great to check with the core rules itself re-create this case. any input would be appreciated 💯 !

Comment (aladdin-add) [reply tests/lib/rules/camelcase.js:815]: I see,  can you add a test like [this comment](https://github.com/eslint/eslint/issues/12592#issuecomment-557825506)?

Comment (anikethsaha) [reply tests/lib/rules/camelcase.js:815]: after testing the above mentioned config (which was the original issue) with the current change implemented, the issue still exists. 

image


So, I think the current change (PR) is not correct change. 

After I cloned the rule option here in [config-validator](https://github.com/eslint/eslint/blob/master/lib/shared/config-validator.js#L186)

like this 

```js
 Object.keys(rulesConfig).forEach(id => {
        const rule = getAdditionalRule(id) || BuiltInRules.get(id) || null;
        const clonedRulesConfigForId = _.cloneDeep(rulesConfig[id])
        validateRuleOptions(rule, id, clonedRulesConfigForId, source);
    });
```

it is passing the test 

image

Comment (anikethsaha) [reply tests/lib/rules/camelcase.js:815]: cc @kaicataldo @aladdin-add should I implement the change mentioned above ?

Comment (aladdin-add) [reply tests/lib/rules/camelcase.js:815]: can you refactor the code to: cloning the config after loading?

Comment (anikethsaha) [reply tests/lib/rules/camelcase.js:815]: you meant somewhere [here](https://github.com/eslint/eslint/blob/fdfa364c1b0d88689d02cbe8ae848a3e323209aa/lib/cli-engine/config-array-factory.js#L492) , in this case we need to send the clonedconfig to the normalizer which will return the mutated clonedconfig and that mutated one will be returned from here. so, IMO this might not be the correct place. 

let me push the latest commit.

Comment (anikethsaha) [reply tests/lib/rules/camelcase.js:815]: @aladdin-add can you check the latest commit!

I think the current change is working as expected in order to fix the issue

**Comment by nzakas** [comment]
@kaicataldo can you check if your concerns have been addressed?

File: tests/lib/rules/use-isnan.js [hunk 5]
```diff
@@ -280,16 +280,6 @@ ruleTester.run("use-isnan", rule, {
             code: "switch(foo) { case NaN: break; }",
             errors: [{ messageId: "caseNaN", type: "SwitchCase", column: 15 }]
         },
-        {
```
Comment (kaicataldo) [inline tests/lib/rules/use-isnan.js:283]: Why were these tests removed?

File: tests/lib/rules/computed-property-spacing.js [hunk 6]
```diff
@@ -782,7 +782,7 @@ ruleTester.run("computed-property-spacing", rule, {
         {
             code: "A = class { [ a ](){} get [ b ](){} set [ c ](foo){} static [ d ](){} static get [ e ](){} static set [ f ](bar){} }",
             output: "A = class { [a](){} get [b](){} set [c](foo){} static [d](){} static get [e](){} static set [f](bar){} }",
-            options: ["never", {}],
```
Comment (kaicataldo) [inline tests/lib/rules/computed-property-spacing.js:785]: Why did this test need to modified?

File: tests/lib/rules/camelcase.js [hunk 7]
```diff
@@ -790,6 +794,25 @@ ruleTester.run("camelcase", rule, {
                 }
             ]
         },
+        {
+            code: "const {mem_var = 1} = obh",
```
Comment (kaicataldo) [inline tests/lib/rules/camelcase.js:798]: It's great to get test coverage here, but I'm concerned about testing a bug fix in core using an individual rule's test suite. It would be very easy for us to unintentionally lose coverage of this behavior and cause a regression. Can we test this in the config-validator or ESLint class's tests?

File: tests/fixtures/config-file/cloned-config/eslintConfig.js [hunk 8]
```diff
@@ -0,0 +1,4 @@
+let errorConfig = ["error", {}];
+module.exports = {
+    rules: { camelcase: errorConfig, "default-case": errorConfig }
```
Comment (aladdin-add) [inline tests/fixtures/config-file/cloned-config/eslintConfig.js:3]: @kaicataldo I think this is to cover the reported issue.

File: tests/lib/rules/use-isnan.js (hunk 5 above)
Comment (aladdin-add) [inline tests/lib/rules/use-isnan.js:283]: why removing this?

File: tests/lib/rules/computed-property-spacing.js [hunk 9]
```diff
@@ -1040,7 +1040,7 @@ ruleTester.run("computed-property-spacing", rule, {
         {
             code: "class A { [a](){} get [b](){} set [c](foo){} static [d](){} static get [e](){} static set [f](bar){} }",
             output: "class A { [ a ](){} get [ b ](){} set [ c ](foo){} static [ d ](){} static get [ e ](){} static set [ f ](bar){} }",
-            options: ["always", {}],
```
Comment (aladdin-add) [inline tests/lib/rules/computed-property-spacing.js:1043]: why removing this?

File: tests/lib/cli.js [hunk 10]
```diff
@@ -1160,4 +1161,29 @@ describe("cli", () => {
         });
     });
 
+    describe("testing the cloned config", () => {
+        describe("config file and input file", () => {
+            it("should execute without any errors", async () => {
+                const configPath = getFixturePath("config-file", "cloned-config", "eslintConfig.js");
+                const filePath = getFixturePath("config-file", "cloned-config", "index.js");
+                const code = `--config ${configPath} ${filePath}`;
```
Comment (kaicataldo) [inline tests/lib/cli.js:1169]: This variable name is a bit confusing to me, since this isn't code, but CLI arguments.

File: tests/lib/cli.js [hunk 11]
```diff
@@ -1160,4 +1161,29 @@ describe("cli", () => {
...
+                const exit = await cli.execute(code);
+
+                assert.strictEqual(exit, 0);
+            });
+        });
+
+        describe("inline config and input file", () => {
+            it("should execute without any errors", async () => {
+                const filePath = getFixturePath("config-file", "cloned-config", "inlineText.js");
+                const code = `${filePath}`;
```
Comment (kaicataldo) [inline tests/lib/cli.js:1180]: This variable name is a bit confusing to me, since this isn't code, but CLI arguments.

File: tests/lib/cli.js [hunk 12]
```diff
@@ -1160,4 +1161,29 @@ describe("cli", () => {
         });
     });
 
+    describe("testing the cloned config", () => {
```
Comment (kaicataldo) [inline tests/lib/cli.js:1164]: It's still not exactly clear to me how this is testing this change. Do you mind explaining to me?

File: tests/lib/rules/camelcase.js (hunk 7 above)
Comment (anikethsaha) [reply tests/lib/rules/camelcase.js:798]: I have added a config fixture for the reported issue. https://github.com/eslint/eslint/pull/13034/files#diff-3cbbbe2ccfd802293e0184c6ce75fea7R2. 

let me know if that's the one you are looking for.

File: tests/lib/cli.js [hunk 13]
```diff
@@ -1160,4 +1161,29 @@ describe("cli", () => {
...
+        describe("config file and input file", () => {
+            it("should execute without any errors", async () => {
```
Comment (kaicataldo) [inline tests/lib/cli.js:1166]: Can we change this `it` description to describe what we're actually testing (i.e. "should not modify original configuration object")?

File: lib/shared/config-validator.js [hunk 14]
```diff
@@ -183,8 +184,9 @@ function validateRules(
 
     Object.keys(rulesConfig).forEach(id => {
         const rule = getAdditionalRule(id) || BuiltInRules.get(id) || null;
+        const clonedRulesConfigForId = _.cloneDeep(rulesConfig[id]);
```
Comment (kaicataldo) [inline lib/shared/config-validator.js:187]: Sorry to keep coming back to this, but what is the limitation that is stopping us from cloning the contents from any configuration files read when they're read, rather than only doing this for rule validation? Apologies if I'm just missing something here, and appreciate your patience :)

Comment (anikethsaha) [reply lib/shared/config-validator.js:187]: I did tried the implementation earlier and it was not fixing the issue as it was sending the cloned config forward. 

https://github.com/eslint/eslint/pull/13034#discussion_r415295775.

File: tests/lib/cli.js (hunk 12 above)
Comment (anikethsaha) [reply tests/lib/cli.js:1164]: here the fixture being tested is the same as the one mentioned in the issue. I tried to reproduce the same here. 

let me know if you want me to add it somewhere else.

File: tests/lib/cli.js (hunk 13 above)
Comment (anikethsaha) [reply tests/lib/cli.js:1166]: sure 👍

File: tests/lib/cli.js (hunk 11 above)
Comment (anikethsaha) [reply tests/lib/cli.js:1180]: opps, totally missed it. sorry I will change it .

File: tests/lib/cli.js (hunk 10 above)
Comment (anikethsaha) [reply tests/lib/cli.js:1169]: I will change it 👍

File: tests/lib/rules/computed-property-spacing.js (hunk 6 above)
Comment (anikethsaha) [reply tests/lib/rules/computed-property-spacing.js:785]: with having `{}`, this code was valid cause it was being mutated with its default value which is set to true in [schema](https://github.com/eslint/eslint/blob/master/lib/rules/computed-property-spacing.js#L33). 

With this change, configs are not being mutated so when user passed an empty object it will not mutate the config with default one. It will only pass an empty object. 


let me know if this is the behavior you want for the linter ?

File: tests/lib/rules/computed-property-spacing.js (hunk 9 above)
Comment (anikethsaha) [reply tests/lib/rules/computed-property-spacing.js:1043]: same as https://github.com/eslint/eslint/pull/13034/files#r420341953
the with `{}` this is a valid case. 

perhaps I should add a valid case with same object. ?

this has become valid because there is no mutation is being done for an empty object `{}`

File: tests/lib/rules/computed-property-spacing.js (hunk 6 above)
Comment (mdjermanovic) [reply tests/lib/rules/computed-property-spacing.js:785]: Rule should get the mutated object, that's the purpose of default values in schema.

Comment (anikethsaha) [reply tests/lib/rules/computed-property-spacing.js:785]: but if we are passing an empty object as an option, should it mutate then too?

Comment (mdjermanovic) [reply tests/lib/rules/computed-property-spacing.js:785]: Yes. In this particular rule, we have `boolean` property `enforceForClassMembers`. If the options object is present, the rule expects this property to be set to either `true` or `false`. It doesn't check for `undefined` in order to apply default value (`true`), so if user didn't specify `enforceForClassMembers` in the object, then it should be automatically set to `true`.

This change would also negatively affect non-empty objects. For example, code like this would be now `valid` in the `use-isnan` rule:

```js
{
    code: "switch(NaN) { case foo: break; }",
    options: [{ enforceForIndexOf: true }],
},
```

we didn't specify `enforceForSwitchCase`, so the rule should behave as if `enforceForSwitchCase` was set to `true` (default), meaning that this code should be `invalid`.

Comment (anikethsaha) [reply tests/lib/rules/computed-property-spacing.js:785]: I got your point,

I was thinking then what would be the difference between `[ ]` vs `[ {} ]` ?

I did tried cloning in [these](https://github.com/eslint/eslint/pull/13034#discussion_r413592713) location, it was not fixing the issue.

Comment (mdjermanovic) [reply tests/lib/rules/computed-property-spacing.js:785]: > I was thinking then what would be the difference between `[ ]` vs `[ {} ]` ?

That should be the same.
 
> I did tried cloning in [these](https://github.com/eslint/eslint/pull/13034#discussion_r413592713) location, it was not fixing the issue.

I'm guessing there might be a problem with how `lodash.cloneDeep` works:

```js
var _ = require("lodash");

var nested = {};

var obj = { x: nested, y: nested };

var clone = _.cloneDeep(obj);

console.log(clone.x === clone.y); // true
```

Maybe we should somehow clone config per rule?

Comment (anikethsaha) [reply tests/lib/rules/computed-property-spacing.js:785]: > ```js
> var _ = require("lodash");
> 
> var nested = {};
> 
> var obj = { x: nested, y: nested };
> 
> var clone = _.cloneDeep(obj);
> 
> console.log(clone.x === clone.y); // true
> ```

ummm.. 🤔 . maybe I should try `JSON.parse(JSON.stringify(obj))` instead. I will check this in the mentioned place. 


> Maybe we should somehow clone config per rule?

[here ?](https://github.com/eslint/eslint/blob/master/lib/shared/config-validator.js#L121)

File: tests/lib/rules/use-isnan.js (hunk 5 above)
Comment (anikethsaha) [reply tests/lib/rules/use-isnan.js:283]: this was removed because i removed the `[{}]` option and it was duplicate case to when I ran the linter, it removed them. 

I am fixing this now 👍

File: tests/lib/rules/computed-property-spacing.js (hunk 6 above)
Comment (anikethsaha) [reply tests/lib/rules/computed-property-spacing.js]: > ummm.. 🤔 . maybe I should try `JSON.parse(JSON.stringify(obj))` instead. I will check this in the mentioned place.

it worked I guess. Thanks, @mdjermanovic for pointing the lodash issue

File: tests/lib/rules/array-bracket-newline.js [hunk 15]
```diff
@@ -40,6 +40,14 @@ ruleTester.run("array-bracket-newline", rule, {
...
         "var foo = [/* single line multiline comment for no real reason */];",
         "var foo = [[1,2]]",
+        {
+            code: "var foo = [[1,2]]",
+            options: [{ }]
+        },
+        {
+            code: "var foo = [[1,2]]",
+            options: []
+        },
```
Comment (aladdin-add) [inline tests/lib/rules/array-bracket-newline.js:50]: just to confirm: this is not to test the change, but to improve the test coverage?
(as the tester will not throw error, even if the `options` was modified)

Comment (anikethsaha) [reply tests/lib/rules/array-bracket-newline.js:50]: ops, i think it might dup by mistake I will remove this case. 

I have added `[{}]` cases for those which have default values in properties

Comment (aladdin-add) [reply tests/lib/rules/array-bracket-newline.js:46]: `"added [{}] cases "` to improve the test coverage?

Comment (anikethsaha) [reply tests/lib/rules/array-bracket-newline.js:46]: > `"added [{}] cases "` to improve the test coverage?

true, 

should I add some more [here](https://github.com/anikethsaha/eslint/tree/fixes-12592/tests/fixtures/config-file/cloned-config) ?

Comment (aladdin-add) [reply tests/lib/rules/array-bracket-newline.js:46]: it's great to improve the test coverage, but it seems out the scope of this PR. maybe another PR, thoughts?

Comment (anikethsaha) [reply tests/lib/rules/array-bracket-newline.js:46]: sorry for not getting, can you mention which one you are suggesting ?

I think [this one](https://github.com/anikethsaha/eslint/tree/fixes-12592/tests/fixtures/config-file/cloned-config) is in the scope of this PR right ?

Comment (aladdin-add) [reply tests/lib/rules/array-bracket-newline.js:46]: sure, I mean the new added tests in rules.

Comment (anikethsaha) [reply tests/lib/rules/array-bracket-newline.js]: done 👍

File: lib/cli-engine/config-array-factory.js [hunk 16]
```diff
@@ -623,8 +623,11 @@ class ConfigArrayFactory {
      * @private
      */
     _normalizeConfigData(configData, ctx) {
+
         validateConfigSchema(configData, ctx.name || ctx.filePath);
-        return this._normalizeObjectConfigData(configData, ctx);
+        const clonedConfig = JSON.parse(JSON.stringify(configData));
```
Comment (aladdin-add) [inline lib/cli-engine/config-array-factory.js:628]: nits(non-blocker): better to have a comment explaining why it is needed. 😄

Comment (anikethsaha) [reply lib/cli-engine/config-array-factory.js:628]: should I add a link to https://github.com/eslint/eslint/pull/13034#discussion_r420688527 ?.

File: tests/fixtures/config-file/cloned-config/eslintConfig.js (hunk 8 above)
Comment (kaicataldo) [inline tests/fixtures/config-file/cloned-config/eslintConfig.js:3]: This test currently assumes that `camelcase` and `default-case` have different default configurations. This will most likely always be true, but should the rules be removed or their configuration options made identical, this test could pass even if the cloning behavior regresses.

Is there any way we could make custom rules and run this same test with those? That way we can guarantee that this test won’t be affected by unrelated rule changes.

File: lib/cli-engine/config-array-factory.js (hunk 16 above)
Comment (kaicataldo) [inline lib/cli-engine/config-array-factory.js:628]: 🎉

File: tests/lib/cli.js (hunk 12 above)
Comment (kaicataldo) [inline tests/lib/cli.js:1164]: Can we add a comment linking to the issue? I think that will provide enough context. :)

File: lib/cli-engine/config-array-factory.js (hunk 16 above)
Comment (aladdin-add) [reply lib/cli-engine/config-array-factory.js:628]: a link to the original issue, and the above comment?

File: tests/fixtures/config-file/cloned-config/eslintConfig.js (hunk 8 above)
Comment (anikethsaha) [reply tests/fixtures/config-file/cloned-config/eslintConfig.js:3]: when I removed the clone statement,  the fixture which uses [rule's config from config file](https://github.com/anikethsaha/eslint/blob/fixes-12592/tests/lib/cli.js#L1164-L1175) is failing.

image


> Is there any way we could make custom rule fixtures that have different default configuration values and run this same test with those?

I do think this would be a much stronger test. by different, you meant different from the properties mentioned in the schema ?

File: tests/lib/cli.js (hunk 12 above)
Comment (anikethsaha) [reply tests/lib/cli.js:1164]: sure 👍

File: lib/cli-engine/config-array-factory.js (hunk 16 above)
Comment (anikethsaha) [reply lib/cli-engine/config-array-factory.js:628]: ok cool 👍

File: tests/fixtures/config-file/cloned-config/eslintConfig.js (hunk 8 above)
Comment (kaicataldo) [reply tests/fixtures/config-file/cloned-config/eslintConfig.js:3]: I was suggesting we do the same test but with fixture custom rules that are guaranteed to stay the same over time. Does that make sense?

**Comment by mdjermanovic** [comment]
Do we have documented restrictions on what can be an option's value?

In the current version, a custom rule might expect something like a function, Date instance, RegExp instance, etc. to be defined in `.eslintrc.js` as a rule's option. JSON schema doesn't support those types, but the `schema` property and thus the validation is optional for rules.

After this change, values will be limited to JSON data types only.

**Comment by kaicataldo** [comment]
This is a good point and is probably worth having a separate discussion about before we merge this in (or alternately find a different deep merge algorithm). Up until now, we’ve wanted config to be JSON-serializable (or at least JSON-compatible) because we support JSON configs. That being said, we don’t know what custom plugins are currently doing, and it’s looking likely we will be implementing a new config file format that will not have this limitation (see [RFC](https://github.com/eslint/rfcs/pull/9)).

**Comment by anikethsaha** [comment]
> In the current version, a custom rule might expect something like a function, Date instance, RegExp instance, etc. to be defined in `.eslintrc.js` as a rule's option.

agreed, this change might break the option of this type. 

I think we can discuss in a separate issue and hold this PR. or wait till the RFC is finalized/implemented?

**Comment by kaicataldo** [comment]
Is there a reason we can't use use `lodash.cloneDeep`?

**Comment by anikethsaha** [comment]
there was an issue with it [ref this](https://github.com/eslint/eslint/pull/13034#discussion_r420688527)

I am not sure why is that behavior.

**Comment by kaicataldo** [comment]
Huh, strange. Might be worth filing a bug report with `lodash`, as that seems like an easy pitfall.

**Comment by anikethsaha** [comment]
> orth filing a bug report with `lodash`, as that seems like an easy pitfall.

not sure whether it's intentional or not. though I couldn't find anything on the docs about this.

**Comment by mdjermanovic** [comment]
By lodash/lodash#2725 it seems to be intentional, as probably the only way to support circular references.

As suggested in the issue, perhaps we could explore `cloneDeepWith`? Maybe to start a new (independent) deep cloning whenever it encounters an object.

**Comment by anikethsaha** [comment]
> As suggested in the issue, perhaps we could explore `cloneDeepWith`?

I will check this

> Maybe to start a new (independent) deep cloning whenever it encounters an object.

I didn't get this one. did you mean custom cloning implementation?

**Comment by mdjermanovic** [comment]
> > Maybe to start a new (independent) deep cloning whenever it encounters an object.
> 
> I didn't get this one. did you mean custom cloning implementation?

Partially custom: maybe we could call  `cloneDeepWith` again from its `customizer` function when it gets an object, or something like that if it makes sense.

**Comment by anikethsaha** [comment]
@mdjermanovic @kaicataldo I have changed the cloning logic with [this](https://stackoverflow.com/a/1042676/9339537). I seem working out. 
let me know if any more specific case I am missing or any suggestion would be great 👍

**Comment by mdjermanovic** [comment]
I was thinking about something like this, instead of maintaining our own deep cloning:

```js
const lodash = require("lodash");

function getCustomizer() {
    let root = true;

    return function customizer(value) {
        if (!root && typeof value === "object" && value !== null) {

            // start new lodash.cloneDeepWith
            return lodash.cloneDeepWith(value, getCustomizer());
        }

        root = false;

        // return `undefined` for the default lodash.cloneDeepWith behavior
        return void 0;
    }
}

// test

const nested = {};

const obj = { x: nested, y: nested };

const clonedObj = lodash.cloneDeepWith(obj, getCustomizer());

console.log(clonedObj.x === clonedObj.y); // false
```

This is just an idea, I'm not sure about the performance. Also, this would cause "Maximum call stack size exceeded" if there are circular references.

**Comment by anikethsaha** [comment]
@mdjermanovic 
The solution you mentioned is working as well 👍 

I think both logic is nearly the same in terms of speed. 

The one you mention might be ~0.10s faster (avg) - from tests


- Result of `perf` script with current clone logic

image

- Result of using `cloneDeepWith` customizer (https://github.com/eslint/eslint/pull/13034#issuecomment-629796697)

image


I did run the `perf` three times, and the result seems relative to this one.

>  Also, this would cause "Maximum call stack size exceeded" if there are circular references.

any way to reproduce this?


Let me know which one to keep 👍 .

IMO, as performance-wise, it seems `lodash.cloneDeepWith` has a bit of better result.

**Comment by kaicataldo** [comment]
I agree with @mdjermanovic that it would be better to use lodash instead of maintaining our own full deep cloning algorithm. If it's also more performant, it seems like the clear winner!

**Comment by anikethsaha** [comment]
I was thinking if there was some way to test/fix this `Also, this would cause "Maximum call stack size exceeded" if there are circular references.` issue.

**Comment by kaicataldo** [comment]
Are there any practical cases where someone would want to include a circular reference? I'm having trouble coming up with any...

**Comment by kaicataldo** [comment]
@anikethsaha To test it, you could add a circular reference inside [settings](https://eslint.org/docs/user-guide/configuring#adding-shared-settings), since this can contain arbitrary data.

**Comment by mdjermanovic** [comment]
> I was thinking if there was some way to test/fix this Also, this would cause "Maximum call stack size exceeded" if there are circular references. issue.

It isn't fixable. It might be nice to report a meaningful error, but the amount of code and complexity to do that is most likely too high for something that normally shouldn't happen in the configuration.

> Are there any practical cases where someone would want to include a circular reference? I'm having trouble coming up with any...

Probably not, just had to mention a possible downside (which also exists with the custom cloning algorithm in the actual iteration of this PR).

**Comment by anikethsaha** [comment]
ok cool, I will change the current logic with `cloneDeepWith` 👍

**Comment by anikethsaha** [comment]
I changed clone logic to the one @mdjermanovic suggested. 

Working as expected 👍 

I did run a test for circular ref with both logic and both are failing. Should add test for the circular ref ? I didn't add them because I thought it doesn't belong to the scope of this change! 


let me know if that needs to be added

**Comment by kaicataldo** [comment]
> I did run a test for circular ref with both logic and both are failing. Should add test for the circular ref ? I didn't add them because I thought it doesn't belong to the scope of this change!

Can you clarify what you mean by this? Do you mean that you wrote a test that tried to clone a config that had circular references and it led to an infinite loop?

My preference would be to add some kind of safeguard for this. I don't feel comfortable knowingly adding a memory leak that could wreak havoc on automated CI boxes that might accidentally be implementing a config with a circular reference. One other thought I had - could we add a safeguard by somehow implementing detection of circular references that could allow us to break out of the cloning logic and use the original config instead (maybe with a warning message)? This would allow us to not break anyone's builds who might be accidentally relying on this behavior.

@nzakas @btmills @mysticatea Thoughts on this? 

In summary, we currently run `ajv` on the imported configuration, which can have the unintended consequence of mutating the configuration by reference when it sets the default values. 

I suggested we try to clone the entire config object when it is imported so that there was no chance of ESLint's internals mutating the config object. We have a working fix for this in this PR, but this solution has the caveat of trying to clone circular refs leading to an infinite loop.

The alternative to this would be to just deep clone the rules configuration, but I suppose this problem could _technically_ occur there too.

**Comment by anikethsaha** [comment]
> Can you clarify what you mean by this? Do you mean that you wrote a test that tried to clone a config that had circular references and it led to an infinite loop?

I added the following eslint config and it was failing.

```js
let errorConfig = ["error", {}];

class CircularRef {
  constructor() {
    this.self = this;
  }
}

module.exports = {
  settings: {
    sharedData: new CircularRef()
  },

  rules: { camelcase: errorConfig, "default-case": errorConfig }
};
```

I couldn't see the error message as the stack was big and my ide (I am not using my local setup, though I can try ) didn't able to display the whole.

>  I don't feel comfortable knowingly adding a memory leak that could wreak havoc on automated CI boxes that might accidentally be implementing a config with a circular reference. 

agreed 💯 


> could we add a safeguard by somehow implementing detection of circular references that could allow us to break out of the cloning logic and use the original config instead (maybe with a warning message)? 

try-catch ?

Also,  it looks like https://github.com/eslint/eslint/issues/13324 can be affected with this as well. 
?

**Comment by mdjermanovic** [comment]
> My preference would be to add some kind of safeguard for this. I don't feel comfortable knowingly adding a memory leak that could wreak havoc on automated CI boxes that might accidentally be implementing a config with a circular reference. One other thought I had - could we add a safeguard by somehow implementing detection of circular references that could allow us to break out of the cloning logic and use the original config instead (maybe with a warning message)? This would allow us to not break anyone's builds who might be accidentally relying on this behavior.

Maybe something like this:

```js
const lodash = require("lodash");

function clone(val) {
    const seenObjects = new Set();
    let forceDefault = false;

    function customizer(value) {
        if (typeof value === "object" && value !== null) {
            if (forceDefault) {
                forceDefault = false;
            } else {
                if (seenObjects.has(value)) {
                    throw new Error("Cannot clone circular structure");
                }
    
                seenObjects.add(value);
                forceDefault = true;
                const clonedValue = lodash.cloneDeepWith(value, customizer);
                seenObjects.delete(value);
    
                return clonedValue;
            }
        }

        // return `undefined` for the default lodash.cloneDeepWith behavior
        return void 0;
    };

    return lodash.cloneDeepWith(val, customizer);
}
```

We call this with `try-catch` and use the original config if it throws, maybe with a warning message.

**Comment by anikethsaha** [comment]
@mdjermanovic @kaicataldo  I used `debug` for logging the warning though it won't be visible by default. 

an alternative can be `console.log` (not ideal) or `process.stdout.write` .

let me know if the current one is fine

**Comment by kaicataldo** [comment]
Maybe I'm missing something, but won't this not actually fix the specific specific problem we're trying to solve here, since it would silently reuse the original config object if there are any objects that are referenced more than once in the config (even if they're not necessarily nested within each other)? Seems like we need to actually do a full traversal of the finalized config object to check specifically for nested circular references before running the cloning algorithm. I'm not sure of the performance hit here, though, particularly for complex configurations.

Alternatives I can think of:

1. Go back to just cloning the rules before running `ajv`. While this issue could potentially still exist if a rule configuration had a nested circular reference, it's a lot less likely since we're dealing with a smaller subset of the full config. Apologies if we do end up doing this, because I know this was the original fix implemented and I suggested we go down the path of trying to clone the entire config.
1. Stick with this current iteration but actually throw an error and disallow rereferencing objects in configs entirely. This would be a breaking change, and feels like a bit of a kludge to me. I would like to avoid this.


@anikethsaha Sorry for all the back and forth. Feel free to wait until we finalize the design before continuing to make changes.

**Comment by anikethsaha** [comment]
> 2\. Stick with this current iteration but actually throw an error and disallow rereferencing objects in configs entirely. This would be a breaking change, and feels like a bit of a kludge to me. I would like to avoid this.

agreed. 

> Seems like we need to actually do a full traversal of the finalized config object to check specifically for nested circular references before running the cloning algorithm. I'm not sure of the performance hit here,

yea, it would be a bit of heavy as what I understood it would mean traversing it twice. 

maybe the solution of #13324 can be helpful here. 




> @anikethsaha Sorry for all the back and forth. Feel free to wait until we finalize the design before continuing to make changes.

Cool 😄

**Comment by mdjermanovic** [comment]
Maybe there's something missing in the algorithm, but this `cloneDeep` was supposed to throw only if there are circular references. Otherwise, it should create multiple copies of the same object if it was referenced more than once.

**Comment by anikethsaha** [comment]
I added the try-catch to not throw an error and just log (debug log) the error and continue with an un-cloned config. 


> Otherwise, it should create multiple copies of the same object if it was referenced more than once.

Should I change it to use the object returning from `cloneDeep`  instead of the original one ?
I would replace the throw when there is circular ref with a debug log !


```diff
const lodash = require("lodash");

function cloneDeep(val) {
    const seenObjects = new Set();
    let forceDefault = false;

    function customizer(value) {
        if (typeof value === "object" && value !== null) {
            if (forceDefault) {
                forceDefault = false;
            } else {
                if (seenObjects.has(value)) {
-                   throw new Error("Cannot clone circular structure");
+                    debug("Cannot clone circular structure")
                }
    
                seenObjects.add(value);
                forceDefault = true;
                const clonedValue = lodash.cloneDeepWith(value, customizer);
                seenObjects.delete(value);
    
                return clonedValue;
            }
        }

        // return `undefined` for the default lodash.cloneDeepWith behavior
        return void 0;
    };

    return lodash.cloneDeepWith(val, customizer);
}

```


thoughts ?

**Comment by mdjermanovic** [comment]
Just to clarify what's the problem with the current iteration - would it fix the original issue?

**Comment by anikethsaha** [comment]
> Just to clarify what's the problem with the current iteration - would it fix the original issue?

yes , but if there is circular ref then it will use the original config instead of the cloned one so in that case it wont be fixed if there is a circular ref

**Comment by mdjermanovic** [comment]
> > Just to clarify what's the problem with the current iteration - would it fix the original issue?
> 
> yes , but if there is circular ref then it will use the original config instead of the cloned one so in that case it wont be fixed if there is a circular ref

I thought that was the goal - fallback to previous behavior only if there are circular refs, in order to avoid breaking builds with such configurations.

Additionally, we could improve the algorithm to return the already cloned object when it detects a circular reference (instead of throwing), while still creating multiple copies of objects that were referenced multiple times but are not part of any cycles.

**Comment by anikethsaha** [comment]
> I thought that was the goal - fallback to previous behavior only if there are circular refs, in order to avoid breaking builds with such configurations.

yeah, that was the idea.

@kaicataldo from https://github.com/eslint/eslint/pull/13034#issuecomment-632283007, it seems like the current is working as it was suggested right?


Even if the config is not cloned and the original conifg is passed on, user can notice the behavior and with this change using `--debug` they can find out the reason for not working as intended as their config has a circular refs (which is ideally not recommendable unless there is some kind of tool like bundlers that handles that. ).

**Comment by aladdin-add** [comment]
TBH, I have never seen some devs writing such a config, so I'm wondering if it was worthy to fix it, by adding a lot of complexity(and probably loss perf)!

what if we just:
* document the behavior, and tell users not to do so; ╮(￣▽￣)╭
* report the issue in `ajv`, to see if it can be fixed  in the upstream.

**Comment by nzakas** [comment]
I think @aladdin-add has a point here: it seems like Ajv modifying the object it’s validating is the root cause, so asking them to fix it might be the best path forward. We are a sponsor after all. :)

**Comment by nzakas** [comment]
Pinged the Ajv creator on the issue: https://github.com/eslint/eslint/issues/12592#issuecomment-633759796

**Comment by anikethsaha** [comment]
Yeah that would be an easy win 👍

**Comment by mdjermanovic** [comment]
@kaicataldo just to clarify, in the case that we eventually decide to clone the entire config:

> Maybe I'm missing something, but won't this not actually fix the specific specific problem we're trying to solve here, since it would silently reuse the original config object if there are any objects that are referenced more than once in the config (even if they're not necessarily nested within each other)?

It should fix the specific problem (the original issue) since it does create multiple clones of objects that were referenced more than once. It will silently reuse the original config only if there are circular references.

Anyway, this code certainly adds some complexity and probably needs more tests.

There is also [clone](https://www.npmjs.com/package/clone) package as an alternative to lodash's clone, but I'm not sure if we want to add another dependency.

**Comment by nzakas** [comment]
Can we simplify this a bit? Since rule configs are JSON-serializable, can we do JSON.parseJSON.stringify(ruleConfig)). I believe doing so will automatically throw for circular references.

**Comment by anikethsaha** [comment]
We tried this earlier https://github.com/eslint/eslint/pull/13034/commits/2260565f3a129ab31cb6c70dd44b580338b6bc1f

But there can be issue with this https://github.com/eslint/eslint/pull/13034#issuecomment-625620799

**Comment by kaicataldo** [comment]
One other possibility is to use a custom replacer/reviver function for JSON.parse/stringify that transforms properties that aren't JSON-serializable into an intermediate data structure and then back, but that also seems like a lot of overhead.

**Comment by anikethsaha** [comment]
>  that aren't JSON-serializable

umm, those values which are not `object` (array included ), `string` and `number` ?

>  into an intermediate data structure and then back,

is it something like appending at the end ?

**Comment by nzakas** [comment]
Unless I’m missing something (which is possible - the config system changed so much in the past year!), our configs are serializable, which is why we can use JSON and YAML to represent them. It stands to reason that at some point where we consume those configs, we should be able to create a copy using the method I described. Maybe it needs to happen right after loading rather than during validation, but it seems possible.

**Comment by mysticatea** [comment]
@nzakas We can use non-JSON values (function, bigint, or regex) in the `settings` property because we have `.eslintrc.js` format and we don't validate the `settings` object.

---

I feel that we don't need to clone the whole config object. Instead, I wonder good enough if we clone only the `rules` object in `factory._normalizeObjectConfigDataBody()` method. If so, because we validate the `rules` object by ajv, we can assume it's JSON serializable.

**Comment by mysticatea** [comment]
A side note: because we are shifting config files to JS (RFC9), maybe we should consider supporting for non-JSON values such as bigint and regex in rule options. So exploring another validator may make sense for bigint, regex, and default values without mutations.

**Comment by kaicataldo** [comment]
I agree with @mysticatea on both points above.

> I feel that we don't need to clone the whole config object. Instead, I wonder good enough if we clone only the rules object in factory._normalizeObjectConfigDataBody() method. If so, because we validate the rules object by ajv, we can assume it's JSON serializable.

After exploring these other options, this seems like the most low-touch way to solve this problem without adding a lot of complexity. :+1:

> A side note: because we are shifting config files to JS (RFC9), maybe we should consider supporting for non-JSON values such as bigint and regex in rule options.

Agreed. I think it makes sense to support these values (and possibly functions) as we move towards a world where we use JS files for configuration.

**Comment by kaicataldo** [comment]
@anikethsaha Thanks for your patience as we discuss this :)

**Comment by nzakas** [comment]
Yes, I was suggesting we do JSON cloning for rule configs in this PR; apologies if that was unclear. 

I think in the short term we should keep rule configs as JSON serializable even with RFC9. We can evaluate other options later.

**Comment by mdjermanovic** [comment]
> I feel that we don't need to clone the whole config object. Instead, I wonder good enough if we clone only the rules object in factory._normalizeObjectConfigDataBody() method. If so, because we validate the rules object by ajv, we can assume it's JSON serializable.

Validation is optional, it happens only if `meta.schema` is specified, so could it be possible that someone has already made a custom rule that expects a non-serializable option value? Such a rule would be probably broken if it gets its config from `JSON.parse(JSON.stringify(rules))`, even if that didn't throw. Maybe we could do `JSON.parse(JSON.stringify(ruleConfig))` at a place where it's certain that the particular `ruleConfig`  will be ajv-validated?

**Comment by nzakas** [comment]
I think the chances of having a non-serializable option value is pretty low, but if there’s a way we can only clone when a schema is present, I’m for it both for safety and for performance.

**Comment by mysticatea** [comment]
Oh....

If `{ type: "object" }` schema is present, the validator doesn't validate the inside of the object.

As far as I know, there are no rules which use non-serializable option values, but I don't know all rules.

**Comment by nzakas** [comment]
@anikethsaha are you still working on this? If not, I can pick it up and try to finish.

**Comment by anikethsaha** [comment]
@nzakas feel free to finish this or I can try to finish this as well if the final direction has been set whether to use `JSON.parse(JSON.stringify(rules))` or not. 

Either way works for me.

**Comment by nzakas** [comment]
The direction has been set. If you're able to update this, that would be great as I don't have a lot of time. But if you can't finish it, then I can take it over. It just might take some time for me to finish.

**Comment by anikethsaha** [comment]
> The direction has been set.

@nzakas  So are we moving forward with `JSON.parse(JSON.stringify(rules))` ?

> If you're able to update this, that would be great as I don't have a lot of time. But if you can't finish it, then I can take it over. It just might take some time for me to finish.

ok cool, I will try to finish this weekend then.

**Comment by nzakas** [comment]
Correct, and thanks :+1:

**Comment by anikethsaha** [comment]
Done 👍

File: lib/cli-engine/config-array-factory.js [hunk 17]
```diff
@@ -623,8 +623,12 @@ class ConfigArrayFactory {
      * @private
      */
     _normalizeConfigData(configData, ctx) {
+
         validateConfigSchema(configData, ctx.name || ctx.filePath);
-        return this._normalizeObjectConfigData(configData, ctx);
+
+        const clonedConfig = JSON.parse(JSON.stringify(configData));
```
Comment (mysticatea) [inline lib/cli-engine/config-array-factory.js:629]: As I mentioned in https://github.com/eslint/eslint/pull/13034#issuecomment-635098648, would you move the cloning process to the `factory._normalizeObjectConfigDataBody()` method and clone the `rules` object only? Cloning only parts that Ajv touches, so it reduces the impact of this change (we can continue to use non-JSON values in the `settings` field.).

Comment (anikethsaha) [reply lib/cli-engine/config-array-factory.js:629]: oh, I might have missed that comment. 

Let me check .

Comment (anikethsaha) [reply lib/cli-engine/config-array-factory.js:629]: I added `const clonedRulesConfig = JSON.parse(JSON.stringify((rules)));` [here](https://github.com/eslint/eslint/blob/master/lib/cli-engine/config-array-factory.js#L704)
and returning [here](https://github.com/eslint/eslint/blob/master/lib/cli-engine/config-array-factory.js#L734) as `rules: clonedRulesConfig`
It is giving the following error as

image


So I changed it to `const clonedRulesConfig = JSON.parse(JSON.stringify(({...rules})));`

but then it is failing the tests of [config-array-factory](https://github.com/eslint/eslint/blob/master/tests/lib/cli-engine/config-array-factory.js) like [this one](https://github.com/eslint/eslint/blob/master/tests/lib/cli-engine/config-array-factory.js#L923) and other similar ones
as this

image

As with this change, even if `rules` is undefined, it will create an empty object because of `{..rules}` 

image

 so that means those fixtures needs to changed. 

WDYT ?

Comment (mysticatea) [reply lib/cli-engine/config-array-factory.js:629]: How about `rules && JSON.parse(JSON.stringify(rules))`?

File: lib/cli-engine/config-array-factory.js [hunk 18]
```diff
@@ -697,6 +699,8 @@ class ConfigArrayFactory {
             ctx.matchBasePath
         );
 
+        const clonedRulesConfig = rules && JSON.parse(JSON.stringify((rules)));
```
Comment (mysticatea) [inline lib/cli-engine/config-array-factory.js:702]: Would you add a comment with the reason we clone it?

File: tests/fixtures/config-file/cloned-config/circularRefEslintConfig.js [hunk 19]
```diff
@@ -0,0 +1,15 @@
+let errorConfig = ["error", {}];
```
Comment (mysticatea) [inline tests/fixtures/config-file/cloned-config/circularRefEslintConfig.js:1]: This file looks like unused. Do you forget something?

File: lib/cli-engine/config-array-factory.js [hunk 20]
```diff
@@ -623,7 +623,9 @@ class ConfigArrayFactory {
      * @private
      */
     _normalizeConfigData(configData, ctx) {
+
         validateConfigSchema(configData, ctx.name || ctx.filePath);
+
```
Comment (mysticatea) [inline lib/cli-engine/config-array-factory.js:628]: Nitpick: would you remove extra diffs?

File: lib/cli-engine/config-array-factory.js (hunk 18 above)
Comment (anikethsaha) [reply lib/cli-engine/config-array-factory.js:725]: Can you check if the description [here](https://github.com/eslint/eslint/pull/13034/files#diff-91937c0f974645b62296ca160b952f7eR700-R724) is fine or not. ?

Comment (mysticatea) [reply lib/cli-engine/config-array-factory.js:725]: Awesome. It's very detailed!

**Comment by anikethsaha** [comment]
@nzakas @mysticatea I think we need to revert this ? https://github.com/eslint/eslint/commit/7fb45cf13e9908d489bd6d5fba3b7243c01508b9#r40036492

Cause I guess users are using non serialized data for the config

File: lib/cli-engine/config-array-factory.js [hunk 21]
```diff
@@ -697,6 +697,33 @@ class ConfigArrayFactory {
...
+         *      }
+         * }
+         *
+         * And if these rules have default values in their schema, their
+         * config will be mutated with default values, the mutated `commonRuleConfig` will be used for `b` as well and it probably
+         * throw schema voilation errors.
+         *
+         * Refer https://github.com/eslint/eslint/issues/12592
+         */
+        const clonedRulesConfig = rules && JSON.parse(JSON.stringify((rules)));
```
Comment (ljharb) [inline lib/cli-engine/config-array-factory.js:725]: unfortunately i never saw this PR; JSON cloning should never be used, especially since eslint config values can be regexes, Infinity, NaN, and other things that don't survive JSON serialization.

Comment (anikethsaha) [reply lib/cli-engine/config-array-factory.js:725]: @ljharb We did tried to avoid json cloning using this. But we tried using lodash cloneDeepWith with customizer but that had different issues like circular ref issue,

Comment (JounQin) [reply lib/cli-engine/config-array-factory.js:725]: This is a BREAKING CHANGE for a lot of plugins which support options via

> regexes, Infinity, NaN, and other things that don't survive JSON serialization

For example: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/filename-case.md#ignore
