### PR TITLE
Fix: Ignore hidden folders when resolving globs (fixes #8259)

### LINKED ISSUE #8259: Regression: ESLint is slow generating file lists for directories with large dot folders, e.g. Mercurial repositories, even when not including dot files
**Tell us about your environment**

* **ESLint Version:** 3.12.2 / 3.4.0
* **Node Version:** 7.7.2
* **npm Version:** 4.1.2
MacBook Pro Mid 2015.

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

Please see https://dxr.mozilla.org/mozilla-central/source/

**What did you do? Please include the actual source code causing the issue.**

Run eslint on the repository, and compared the timings. For a full run on our repository, a git cinnabar checkout runs in 2m 13. For a Mercurial checkout it runs in 3m 45.

**What did you expect to happen?**

The repositories should take about the same time - the repository format shouldn't matter.

This seemed to be regressed in version 3.5.0 by #6844.

**What actually happened? Please include the actual, raw output from ESLint.**

The Mercurial has a large `.hg` folder (320268 files on my checkout). Whereas a git checkout has a much smaller `.git` folder (3857 files).

If the repository is checked out via Mercurial, then for an eslint run, the start of the debug looks like:

```
$ ./tools/lint/eslint/node_modules/.bin/eslint --debug .
  eslint:cli Running on files +0ms
  eslint:glob-util Creating list of files to process. +26ms
  eslint:ignored-paths Looking for ignore file in /Users/mark/dev/mozilla-central +3ms
  eslint:ignored-paths Loaded ignore file /Users/mark/dev/mozilla-central/.eslintignore +0ms
  eslint:ignored-paths Adding /Users/mark/dev/mozilla-central/.eslintignore +0ms
  eslint:cli-engine Processing /Users/mark/dev/mozilla-central/accessible/jsat/content-script.js +52s
```

If the repository is checked out into a git repository (via git-cinnabar), then the eslint run looks like:

```
$ ./tools/lint/eslint/node_modules/.bin/eslint --debug .
  eslint:cli Running on files +0ms
  eslint:glob-util Creating list of files to process. +24ms
  eslint:ignored-paths Looking for ignore file in /Users/mark/dev/gecko +3ms
  eslint:ignored-paths Loaded ignore file /Users/mark/dev/gecko/.eslintignore +0ms
  eslint:ignored-paths Adding /Users/mark/dev/gecko/.eslintignore +0ms
  eslint:cli-engine Processing /Users/mark/dev/gecko/accessible/jsat/content-script.js +7s
```

The +52s -> +7s is quite a big difference. If I include all the extensions that we process via `--ext` then this gets even worse (2m vs 12s).

#6844 enabled parsing of dot files, and enabled searching for them via `GlobSync`. If, as a temporary test, I change the glob options to set `dot` to `false`, then the timings are about the same for both repositories.

https://github.com/eslint/eslint/blob/d6150e300e86e2e55a6a3d048dfb6072ac2b6489/lib/util/glob-util.js#L167

### PR DESCRIPTION
**Pull request by IanVS**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

This is a performance improvement, but should not be a change to linting functionality.  This is similar to avoiding glob resolution within `node_modules`.  With this change, `node-glob` will not attempt to  find all files within `.dotfolder` folders.  Similar to `node_modules`, this can be overridden in a user’s ignore file or in an ignore-pattern, and is also prevented if the `dotfiles` option is `true`.

**Is there anything you'd like reviewers to focus on?**

It would be good to double-check our tests around hidden files and folders, as well as perhaps manually trying a few situations.  From everything I tested, this works exactly like before, except faster. 🐎

### CODE REVIEW

File: lib/ignored-paths.js [hunk 1]
```diff
@@ -201,6 +201,12 @@ class IgnoredPaths {
 
         const ig = ignore().add(DEFAULT_IGNORE_DIRS);
 
+        if (this.options.dotfiles !== true) {
+
+            // Ignore hidden folders.  (This cannot be ".*", or else it's not possible to unignore hidden files)
+            ig.add([".*/*", "!../"]);
```
Comment (alberto) [inline lib/ignored-paths.js]: I think it could be `.*/`. It's just that you would have to unignore the folder you want to lint e.g `.foo/`. Unless the issue is with glob syntax, which I am not so familiar with.

Comment (IanVS) [inline lib/ignored-paths.js]: That's right, it's not possible to unignore an ignored folder, which is why I needed it this way.

**Comment by IanVS** [comment]
It might be good for @kaelzhang to double-check this as well.

File: lib/ignored-paths.js (hunk 1 above)
Comment (not-an-aardvark) [inline lib/ignored-paths.js]: As a separate issue (probably for a different PR) maybe we should name this variable to something other than `ig`. I was having trouble understanding what this code was doing because it's hard to tell what `ig.add` means conceptually.

Comment (kaelzhang) [inline lib/ignored-paths.js]: I think it is not good to `ig.add('!../')`, because .gitignore only cares about the current directory and subtle directories.

Even if it works to do this, it is the side effect of `node-ignore` however.

Comment (kaelzhang) [inline lib/ignored-paths.js]: I think it is not good to `ig.add('!../')`, because .gitignore only cares about the current directory and subtle directories.

Even if it works to do this, it is the side effect of `node-ignore` however.

Comment (kaelzhang) [inline lib/ignored-paths.js]: There might be a better workaround to make sure `../` is excluded in the glob result.

Comment (IanVS) [inline lib/ignored-paths.js]: Yeah, I added that pattern a while ago because the patterns in `.eslintignore` currently are applied against the CWD, not the file's directory (until https://github.com/eslint/eslint/pull/7678 is merged). I think we could consider removing that pattern in that PR, since you're right, from then on, the patterns will be relative to the ignore file's location, and the ignore file must be at the project root (unless we make changes for https://github.com/eslint/eslint/issues/8090).

It might be interesting to do a search for `.eslintignore` files on github which contain `../`.  Seems like that should be possible, but I'm not exactly sure how.

Comment (IanVS) [inline lib/ignored-paths.js]: By the way, thanks for reviewing, @kaelzhang!
