### PR TITLE
fix: Prevent `no-var` autofix when a variable is used before declaration

### LINKED ISSUE #20209: Bug: [no-var] Fix causes ReferenceError
### Environment

ESLint Playground (eslint version v9.37.0).

Also locally tested on eslint v8.57.1 with similar change of `var` to `let` without moving its location (tested on a more complicated setup though, not this minimised example).

### What parser are you using?

Default (Espree)

### Playground Code
```js
export function a() {
    console.log(o);
    var o;
    return o;
}
```

### ESLint Configuration 
<details> 
 <summary> Tap to see full config </summary> 

```js
undefined
export default [
    {
        "rules": {
            "no-var": [
                "error"
            ]
        }
    }
];
```
 </details>

### ESLint Output
```
3:5 Unexpected var, use let or const instead. (no-var)
```

Now press "Fix".

### What did you expect to happen?

```js
export function a() {
    let o;
    console.log(o);
    return o;
}
```

### What actually happened?

```js
export function a() {
    console.log(o);
    let o;
    return o;
}
```

This code leads to a ReferenceError as the `let` is not moved above the usage point of `o`.

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiZXhwb3J0IGZ1bmN0aW9uIGEoKSB7XG4gICAgY29uc29sZS5sb2cobyk7XG4gICAgdmFyIG87XG4gICAgcmV0dXJuIG87XG59Iiwib3B0aW9ucyI6eyJydWxlcyI6eyJuby12YXIiOlsiZXJyb3IiXX0sImxhbmd1YWdlT3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Similar old closed issue: https://github.com/eslint/eslint/issues/7950

### PR DESCRIPTION
**Pull request by amareshsm**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Fixes a bug in the no-var rule where it incorrectly provided an autofix to convert var to let/const when a variable was referenced before its declaration. This autofix was unsafe because it would cause a ReferenceError at runtime due to the TDZ.
The fix prevents the rule from suggesting an autofix in these unsafe cases - the rule still reports the error, but does not fix.
Fixes #20209
#### Is there anything you'd like reviewers to focus on?
Please check the tests to confirm that all edge/tricky scenarios are covered.

### CODE REVIEW

File: lib/rules/no-var.js [hunk 1]
```diff
@@ -191,6 +191,31 @@ function hasNameDisallowedForLetDeclarations(variable) {
...
+	return variable.references.some(reference => {
+		const referenceStart = reference.identifier.range[0];
+
+		/*
+		 * Only check references that are in the same scope as the declaration
+		 * and occur before the declaration
+		 */
+		return (
+			!reference.init &&
+			reference.from === declarationScope &&
```
Comment (mdjermanovic) [inline lib/rules/no-var.js]: With this condition, cases like this would still be autofixable although that causes a ReferenceError:

```js
function a() {
	if (something) {
		console.log(o);
	}
	var o;
	return o;
}
```

Comment (mdjermanovic) [reply lib/rules/no-var.js]: Also cases like this:

```js
function a() {
	if (something) {
		console.log(o);
		var o;
		return o;
	}
}
```

Comment (amareshsm) [reply lib/rules/no-var.js]: thanks for the review. I think this condition is the problem `reference.from === declarationScope` only checks if the reference is in the exact same scope. I will take look.

**Comment by amareshsm** [comment]
This slipped past me for a while it is ready for review now.
