### PR TITLE
Fix: indent false positive with multi-line await expression.

### LINKED ISSUE #8815: [v4] indent: false positive with multi-line async function call + destructuring assignment
**Tell us about your environment**

* **ESLint Version:** 4.1.1
* **Node Version:** 4.3.1
* **npm Version:** 2.14.12

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint 7.2.3

**Please show your full configuration:**

```
{
    "env": {
        "node": true,
        "es6": true,
    },
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaFeatures": {
            "arrowFunctions": true,
            "forOf": true,
            "defaultParams": true,
            "destructuring": true,
            "objectLiteralShorthandProperties": true,
            "restParams": true,
            "spread": true,
        },
    },
    "rules": {
        "indent": ["warn", 4, {"SwitchCase": 1}],
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
async function test() {
    const {
        foo,
        bar,
    } = await doSomethingAsync(
        1,
        2,
        3,
    );
}
```

**What did you expect to happen?**

No errors

**What actually happened? Please include the actual, raw output from ESLint.**
```
  6:1  warning  Expected indentation of 12 spaces but found 8  indent
  7:1  warning  Expected indentation of 12 spaces but found 8  indent
  8:1  warning  Expected indentation of 12 spaces but found 8  indent
  9:1  warning  Expected indentation of 8 spaces but found 4   indent
```

NOTES:
- It works if I remove the `async` keyword
- It works if I don't use destructuring assignment
- It works if I don't split the function arguments into multiple lines

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
…tructuring assignment

**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

**What changes did you make? (Give an overview)**
fixes #8815 

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

File: lib/rules/indent.js [hunk 1]
```diff
@@ -896,7 +896,11 @@ module.exports = {
 
             parameterParens.add(openingParen);
             parameterParens.add(closingParen);
-            offsets.matchIndentOf(sourceCode.getTokenBefore(openingParen), openingParen);
+
+            // https://github.com/eslint/eslint/issues/8815
+            const tokenBefore = sourceCode.getTokenBefore(openingParen, node.parent.type === "AwaitExpression" ? astUtils.isKeywordToken : void 0);
```
Comment (Aladdin-ADD) [inline lib/rules/indent.js]: I see `tokenBefore` is not a good name, someone help me~~ 🆘

**Comment by not-an-aardvark** [comment]
Hi @Aladdin-ADD, sorry about the delay in reviewing this. I'm planning to test it out tonight or tomorrow and give some feedback then.

File: tests/lib/rules/indent.js [hunk 2]
```diff
@@ -3895,6 +3895,22 @@ ruleTester.run("indent", rule, {
...
+                        bar,
+                    } = await doSomethingAsync(
+                        1,
+                        2,
+                        3,
+                    );
+                }
+            `
+        },
+
```
Comment (not-an-aardvark) [inline tests/lib/rules/indent.js]: Can you add tests for these cases too?

```js
        {
            code: unIndent`
                function* test() {
                    const {
                        foo,
                        bar,
                    } = yield doSomethingAsync(
                        1,
                        2,
                        3,
                    );
                }
            `
        },
        {
            code: unIndent`
                ({
                    a: b
                } = +foo(
                    bar
                ));
            `
        },
        {
            code: unIndent`
                const {
                    foo,
                    bar,
                } = typeof foo(
                    1,
                    2,
                    3,
                );
            `
        },
        {
            code: unIndent`
                const {
                    foo,
                    bar,
                } = +(
                    foo
                );
            `
        },
```

File: lib/rules/indent.js (hunk 1 above)
Comment (not-an-aardvark) [inline lib/rules/indent.js]: I don't think this fix is quite correct. I think the problem is actually with the logic for `AssignmentExpression` and `VariableDeclaration` nodes, not with `CallExpression` nodes -- the from the report in https://github.com/eslint/eslint/issues/8815 is just a special case that happens to include `AwaitExpression` and a `CallExpression`.

For example, the following code is also an error due to this bug, but it's not fixed:

```js
const {
    foo
} = typeof foo(
    1
);
```

Instead of modifying the logic for `CallExpression`s, I think the following fix solves the problem:

```diff
diff --git a/lib/rules/indent.js b/lib/rules/indent.js
index 6babe29c..fafd1292 100644
--- a/lib/rules/indent.js
+++ b/lib/rules/indent.js
@@ -1030,7 +1030,7 @@ module.exports = {
                 const nodeTokens = getTokensAndComments(node);
                 const tokensFromOperator = nodeTokens.slice(lodash.sortedIndexBy(nodeTokens, operator, token => token.range[0]));

-                offsets.setDesiredOffsets(tokensFromOperator, sourceCode.getFirstToken(node.left), 1);
+                offsets.setDesiredOffsets(tokensFromOperator, sourceCode.getLastToken(node.left), 1);
                 offsets.ignoreToken(tokensFromOperator[0]);
                 offsets.ignoreToken(tokensFromOperator[1]);
             },
@@ -1325,12 +1325,12 @@ module.exports = {
             VariableDeclarator(node) {
                 if (node.init) {
                     const equalOperator = sourceCode.getTokenBefore(node.init, astUtils.isNotOpeningParenToken);
-                    const tokenAfterOperator = sourceCode.getTokenAfter(equalOperator);
+                    const tokensAfterOperator = sourceCode.getTokensAfter(equalOperator, token => token.range[1] <= node.range[1]);

                     offsets.ignoreToken(equalOperator);
-                    offsets.ignoreToken(tokenAfterOperator);
-                    offsets.matchIndentOf(equalOperator, tokenAfterOperator);
-                    offsets.matchIndentOf(sourceCode.getFirstToken(node), equalOperator);
+                    offsets.ignoreToken(tokensAfterOperator[0]);
+                    offsets.setDesiredOffsets(tokensAfterOperator, equalOperator, 1);
+                    offsets.matchIndentOf(sourceCode.getLastToken(node.id), equalOperator);
                 }
             },

```

There are two parts to the fix:

1. With `AssignmentExpression` nodes, the equals sign should be offset from the last token of the `AssignmentExpression`, not the first token. This prevents token-collapsing bugs like [this one](https://github.com/eslint/eslint/blob/5c3ac8ed3c1d8f4b8f4cd82d7c5d79d88de26ec5/lib/rules/indent.js#L270-L291).
1. With `VariableDeclarator` nodes, all tokens should be indented from the `=` token, not just the first token after the `=` token. The problem before was that in a case like this:

    ```js
    var {
    } = await foo(
    )
    ```

    Only the `await` token's indentation was getting set to be aligned with the `}`, but the `foo` token's indentation was not getting aligned properly, so the `foo()` expression was offset from `}` when it should have been aligned instead.

**Comment by not-an-aardvark** [comment]
Thanks for contributing!
