### PR TITLE
Update: Implement auto fix for `space-infix-ops` rule (fixes #3801)

### LINKED ISSUE #3801: Implement auto fix functionality for space-infix-ops rule
Implement auto fix functionality for space-infix-ops rule

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

File: lib/rules/space-infix-ops.js [hunk 1]
```diff
@@ -48,7 +48,28 @@ module.exports = function(context) {
...
      */
     function report(mainNode, culpritToken) {
-        context.report(mainNode, culpritToken.loc.start, "Infix operators must be spaced.");
+        context.report({
+            node: mainNode,
+            loc: culpritToken.loc.start,
+            message: "Infix operators must be spaced.",
+            fix: function(fixer) {
+                var previousToken = context.getTokensBefore(culpritToken, 1);
+                var afterToken = context.getTokensAfter(culpritToken, 1);
```
Comment (lo1tuma) [inline lib/rules/space-infix-ops.js]: Why not using `getTokenBefore` and `getTokenAfter`?

File: lib/rules/space-infix-ops.js [hunk 2]
```diff
@@ -48,7 +48,28 @@ module.exports = function(context) {
...
+                var fixString = "";
+
+                if (culpritToken.range[0] - previousToken[0].range[1] === 0) {
+                    fixString = " ";
```
Comment (lo1tuma) [inline lib/rules/space-infix-ops.js]: I know we’ve already implemented autofixing for some whitespace rules, but I wonder if a whitespace is always correct here, it could be also a linebreak, right? Another problem would be that this fix could possible create errors for the `max-len` rule.

Comment (nzakas) [inline lib/rules/space-infix-ops.js]: I think given a choice between the two, inserting/removing whitespace is the more painful manual operation, so I'm not too worried about triggering `max-len` at this point.

File: lib/rules/space-infix-ops.js (hunk 1 above)
Comment (nzakas) [inline lib/rules/space-infix-ops.js]: Agree. let's keep it simple

File: lib/rules/space-infix-ops.js [hunk 3]
```diff
@@ -48,7 +48,28 @@ module.exports = function(context) {
...
+                }
+
+                fixString += culpritToken.value;
+
+                if (afterToken[0].range[0] - culpritToken.range[1] === 0) {
+                    fixString += " ";
+                }
+
+                return fixer.replaceTextRange(culpritToken.range, fixString);
```
Comment (nzakas) [inline lib/rules/space-infix-ops.js]: You can just do `replaceText(culpritToken, fixString)`

**Comment by gyandeeps** [comment]
@nzakas changes have been made. Thanks

**Comment by nzakas** [comment]
LGTM
