### PR TITLE
Fix: trailing spaces auto fix to check for line breaks (fixes #3940)

### LINKED ISSUE #3940: Incorrect autofixing with key-spacing rule
Given the rule: `"key-spacing": [2, {"align": "value"}]`

And an object literal in the form:
```javascript
  const attributes = {
    visible: ['email'],
    
    articles () {
      return this.hasMany('Article')
    }
  }
```

Autofix will rewrite the literal as:
```javascript
  const attributes = {
    visible: ['emai
    
    articles () {
      return this.hasMany('Article')
    }
  }
```

If the properties with shorthand notation are grouped with properties with regular notation, the key-spacing rule will always fail but autofix will do nothing (i.e. leave it unchanged).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26948433-incorrect-autofixing-with-key-spacing-rule?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

File: tests/lib/rules/no-trailing-spaces.js [hunk 1]
```diff
@@ -67,6 +67,26 @@ ruleTester.run("no-trailing-spaces", rule, {
     invalid: [
         {
             code:
+            "var short2 = true;\n" +
```
Comment (nzakas) [inline tests/lib/rules/no-trailing-spaces.js]: Can you add a test case with shorthand properties and methods to match the issue?

Comment (gyandeeps) [inline tests/lib/rules/no-trailing-spaces.js]: done.
