### PR TITLE
Fix: no-else-return autofix produces name collisions (fixes #11069)

### LINKED ISSUE #11069: no-else-return fixed to incorrect code
**Tell us about your environment**

* **ESLint Version:** 5.8.0/master
* **Node Version:** n/a
* **npm Version:** n/a

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  rules: {"no-else-return": 2}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
function foo(){
    let bar = 0;
    if(cond) {
        return bar;
    } else {
        let bar = 1;
        return bar;
    }
}
```

```bash

```

**What did you expect to happen?**
not fix to incorrect code.

**What actually happened? Please include the actual, raw output from ESLint.**

fixed code:
```js
function foo(){
    let bar = 0;
    if(cond) {
        return bar;
    } 
        let bar = 1;
        return bar;
    
}
```

```bash
7:13  error  Parsing error: Identifier 'bar' has already been declared
```

**Are you willing to submit a pull request to fix this bug?**
yes, but I don't have time to do it in the following days. please feel free to take it if someone else have interests.

### PR DESCRIPTION
**Pull request by mdjermanovic**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix [#11069](https://github.com/eslint/eslint/issues/11069)

**What changes did you make? (Give an overview)**

Disable `no-else-return` auto-fix in cases where it would cause name collisions.

This prevents syntax errors:

```js
function foo(){
    let bar = 0;
    if (cond) {
        return bar;
    } else {
        let bar = 1; // redeclaration, if the rule removes else and braces
        return bar;
    }
}
```

and reference changes:

```js
function bar() {
  return 0;
}

function foo(){
    if (cond) {
        return bar(); // reference to the variable below, if the rule removes else and braces
    } else {
        let bar = 1;
        return bar;
    }
}
```

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

File: tests/lib/rules/no-else-return.js [hunk 1]
```diff
@@ -182,6 +182,342 @@ ruleTester.run("no-else-return", rule, {
...
             options: [{ allowElseIf: false }],
             errors: [{ messageId: "unexpected", type: "IfStatement" }]
+        },
+
+        // https://github.com/eslint/eslint/issues/11069
+        {
+            code: "function foo() { var a; if (bar) { return true; } else { var a; } }",
+            output: "function foo() { var a; if (bar) { return true; }  var a;  }",
+            errors: [{ messageId: "unexpected", type: "BlockStatement" }]
+        },
```
Comment (aladdin-add) [inline tests/lib/rules/no-else-return.js]: I'm not sure we should fix this case -- vars will be hoisted.

**Comment by platinumazure** [comment]
Just wanted to call out that I really appreciated the depth of the test cases, and in general the diligence of this PR. Really solid work, @mdjermanovic, and I hope to see more from you in the future (the project will be all the better for it). Thanks again for your contribution!

**Comment by mdjermanovic** [comment]
Thank you for the kind words, I really appreciate it,  This was a very interesting PR for me, and I like the whole project of course.

I really enjoy working on it.
