### PR TITLE
Fix: Handle forbidden LineTerminators in no-extra-parens (fixes #4229)

### LINKED ISSUE #4229: JSX possible issue with either no-extra-parens or indent
Dears,

It seems like either one of these two rules is mistaken. I'm new to JSX so I'm not sure which one, if any.

**Attempt 1**
image

**Attempt 2**
image

**Attempt 3** this fixes it actually. But I liked the first two best as style.
image

Your thoughts?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27617265-jsx-possible-issue-with-either-no-extra-parens-or-indent?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by btmills**
Previously, this rule would warn about excess parentheses even when they were syntactically significant and removing them would alter the meaning of a program. There are three applicable productions in the grammar with the restriction `[no LineTerminator here]`:

```
ReturnStatement[Yield]:
  return [no LineTerminator here] Expression;
  return [no LineTerminator here] Expression[In, ?Yield];

ThrowStatement[Yield]:
  throw [no LineTerminator here] Expression[In, ?Yield];

YieldExpression[In]:
  yield [no LineTerminator here] * AssignmentExpression[?In, Yield]
  yield [no LineTerminator here] AssignmentExpression[?In, Yield]
```

If the expression following a `return`, `throw`, or `yield` is on a new line, it must be wrapped in parentheses, and this rule should not warn. It should, however, still check for double parentheses, since the second set would be unnecessary.

Thanks to @michaelficarra for pasting the relevant portions of the spec.

### CODE REVIEW

**Comment by btmills** [comment]
Rebased on `master`, CI passed, ready for review.

File: lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -422,7 +438,10 @@ module.exports = function(context) {
             });
         },
         "ReturnStatement": function(node) {
```
Comment (nzakas) [inline lib/rules/no-extra-parens.js]: You can call `context.getSourceCode()` once before all of these functions and then just use the reference in each function rather than repeating this in each function.

Comment (btmills) [inline lib/rules/no-extra-parens.js]: Fixed.

**Comment by nzakas** [comment]
Lgtm
