### PR TITLE
Update: Display errors closer to the place where fix should go 

### LINKED ISSUE #4470: Display errors closer to the place where fix should go
`space-after-keywords` and  `no-sequences` rules display errors on wrong lines for the following snippet
```js
/*eslint "space-after-keywords": 2, "no-sequences": 2 */
do { // error for while is here
    
} while(true)

a( // error for , is here
{
}
),
b
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28351671-display-errors-closer-to-the-place-where-fix-should-go?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nightwing**
(fixes #4470)

### CODE REVIEW

File: tests/lib/rules/no-sequences.js [hunk 1]
```diff
@@ -15,10 +15,20 @@ var rule = require("../../../lib/rules/no-sequences"),
...
+ * Create error message object for failure cases
+ * @param {int} column column of the error
+ * @returns {object} returns the error messages collection
+ * @private
+ */
+function errors(column) {
+    return [{
+        message: "Unexpected use of comma operator.",
+        type: "SequenceExpression",
+        line: 1,
```
Comment (ilyavolodin) [inline tests/lib/rules/no-sequences.js]: I don't think this is right. This will always report an error on the first line. Your unit tests are passing, because you only have 1 line in all of them.

**Comment by nzakas** [comment]
Lgtm
