### PR TITLE
fix: unsafe report for `no-lonely-if`

### LINKED ISSUE #19033: Bug: `no-lonely-if` has incorrect fix when nested inside parent `if` without `BlockStatement`
### Environment

Local ESLint version: 9.12.0

### What parser are you using?

Default (Espree)

### What did you do?

```js
/* eslint no-lonely-if: "error" */
if (true)
	if (false) {}
	else { if (false) {} }
	//     ^ Unexpected if as the only statement in an else block.
else throw Error('This `else` should have been unreachable!');
```

### What did you expect to happen?

Autofix should not be unsafe.

Should it maybe autofix by adding curly braces to the outer `if`? Not sure.

### What actually happened?

```js
/* eslint no-lonely-if: "error" */
if (true)
	if (false) {}
	else if (false) {}
else throw Error('This `else` should have been unreachable!');
```

The `else` block is now reachable when it used to be unreachable.

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWxvbmVseS1pZjogXCJlcnJvclwiICovXG5pZiAodHJ1ZSlcblx0aWYgKGZhbHNlKSB7fVxuXHRlbHNlIHsgaWYgKGZhbHNlKSB7fSB9XG5lbHNlIHRocm93IEVycm9yKCdUaGlzIGBlbHNlYCBzaG91bGQgaGF2ZSBiZWVuIHVucmVhY2hhYmxlIScpOyIsIm9wdGlvbnMiOnsicnVsZXMiOnt9LCJsYW5ndWFnZU9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

FYI, this case is already handled correctly by the `curly` rule:

```js
/* eslint curly: ["error", "multi"] */
if (true) {
	//^ Unnecessary { after 'if' condition.
	if (false) {}
	else { if (false) {} }
	//   ^ Unnecessary { after 'else'
}
else throw Error('This `else` should have been unreachable!');
```

Two errors are reported by the `curly` rule, but autofixing either one results in the other error no longer being reported.

https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IGN1cmx5OiBbXCJlcnJvclwiLCBcIm11bHRpXCJdICovXG5pZiAodHJ1ZSkge1xuXHRpZiAoZmFsc2UpIHt9XG5cdGVsc2UgeyBpZiAoZmFsc2UpIHt9IH1cbn1cbmVsc2UgdGhyb3cgRXJyb3IoJ1RoaXMgYGVsc2VgIHNob3VsZCBoYXZlIGJlZW4gdW5yZWFjaGFibGUhJyk7Iiwib3B0aW9ucyI6eyJydWxlcyI6e30sImxhbmd1YWdlT3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19

### PR DESCRIPTION
**Pull request by abrahamguo**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #19033

#### What changes did you make? (Give an overview)

Extract some shared logic from the `curly` rule that also applies here.

### CODE REVIEW

File: lib/rules/utils/ast-utils.js [hunk 1]
```diff
@@ -2311,6 +2311,114 @@ module.exports = {
         return node.type === "TemplateLiteral" && node.expressions.length === 0;
     },
 
+    /**
+     * Determines whether the existing curly braces around the single statement are necessary to preserve the semantics of the code.
+     * The braces, which make the given block body, are necessary in either of the following situations:
+     *
+     * 1. The statement is a lexical declaration.
```
Comment (mdjermanovic) [inline lib/rules/utils/ast-utils.js:2318]: This isn't checked by this function. We could either get the check back here (although it isn't necessary for the `no-lonely-if` rule) to make the function more generic, or remove this comment and rename this function to better describe that it only checks for one specific case (if-else pairing). I'd vote for the former. What do you think?

Comment (abrahamguo) [reply lib/rules/utils/ast-utils.js:2318]: Sounds good, done!

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Leaving it open for a day in case anyone else wants to take a look before merging.
