### PR TITLE
Fix: no-multiple-empty-lines errors when no line breaks (fixes #6449)

### LINKED ISSUE #6449: 2.13 regression: no-multiple-empty-lines breaks on files without line breaks
**What version of ESLint are you using?**
2.13.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```js
{
  "rules": {
    "no-multiple-empty-lines": [2, { max: 2, maxEOF: 1 }]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
Run eslint against a file with no line breaks.
```js
var a = 5;
```

**What did you expect to happen?**
Run without error

**What actually happened? Please include the actual, raw output from ESLint.**
```
Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at /Users/strawbrary/projects/chell/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:101:47
    at Array.forEach (native)
    at EventEmitter.checkBlankLines (/Users/strawbrary/projects/chell/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:100:23)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.leaveNode (/Users/strawbrary/projects/chell/node_modules/eslint/lib/util/node-event-generator.js:49:22)
    at CodePathAnalyzer.leaveNode (/Users/strawbrary/projects/chell/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:627:23)
    at CommentEventGenerator.leaveNode (/Users/strawbrary/projects/chell/node_modules/eslint/lib/util/comment-event-generator.js:110:23)
    at Controller.traverser.traverse.leave (/Users/strawbrary/projects/chell/node_modules/eslint/lib/eslint.js:908:36)
    at Controller.__execute (/Users/strawbrary/projects/chell/node_modules/estraverse/estraverse.js:397:31)
```

Submitted #6451 as a fix.

### PR DESCRIPTION
**Pull request by strawbrary**

### CODE REVIEW

**Comment by nzakas** [comment]
LGTM. Leaving open to get some other eyes on it.

**Comment by ilyavolodin** [comment]
LGTM

File: lib/rules/no-multiple-empty-lines.js [hunk 1]
```diff
@@ -98,7 +98,7 @@ module.exports = {
 
                 linesRangeStart.push(0);
                 lines.forEach(function(str, i) {
-                    var length = i < fullLines.length ? fullLines[i].length : 0,
+                    var length = Array.isArray(fullLines) && i < fullLines.length ? fullLines[i].length : 0,
```
Comment (ljharb) [inline lib/rules/no-multiple-empty-lines.js]: Could an alternative fix be to add `|| []` on line 81 above, so that it's always an array, and you don't have to check if it is one N times?

Comment (nzakas) [inline lib/rules/no-multiple-empty-lines.js]: Oh yeah, good call.

Comment (strawbrary) [inline lib/rules/no-multiple-empty-lines.js]: Updated the pull with change from @ljharb.

**Comment by alberto** [comment]
LGTM
