### PR TITLE
Fix: no-invalid-meta crashes for non Object values (fixes #10750)

### LINKED ISSUE #10750: Internal consistent-docs-url rule crashes if meta isn't present
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** n/a
* **npm Version:** n/a

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

According to the internal ESLint config around rules:

```
rules:
    rulesdir/consistent-docs-url: "error"
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
module.exports = {
};
```

```js
module.exports = {
  meta: undefined
};
```

```bash
npm run lint
```

**What did you expect to happen?**

Either a lint error about the lack of meta or nothing if that is covered by another rule.

**What actually happened? Please include the actual, raw output from ESLint.**

For configuration 1:
ESLint crashes, with an error message from context.report that the node location must be passed if the node is not passed.

For configuration 2:
ESLint throws an exception that it is trying to access property `length` of `undefined`

This happened when I was trying to fix #10722 

As mentioned in [this comment](https://github.com/eslint/eslint/pull/10749/comment#issuecomment-411744730),

Case 1: meta property is not defined on the exports object.

This crashes eslint and curiously, the `exportsNode` is of type `functionExpression`.

Case 2: meta property is defined with a value of `undefined`

This creates an exception in `getPropertyFromObject` method where it tries to access `length` of `undefined`.

### PR DESCRIPTION
**Pull request by s4san**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Issue ( #10750 )

**What changes did you make? (Give an overview)**

- Added a check to prevent `getPropertyFromObject` trying to access the `length` property of `undefined`

**Is there anything you'd like reviewers to focus on?**

- Changed the `getPropertyFromObject` function across all internal rule files.

### CODE REVIEW

File: tests/tools/internal-rules/no-invalid-meta.js [hunk 1]
```diff
@@ -126,6 +126,24 @@ ruleTester.run("no-invalid-meta", rule, {
                 column: 18
             }]
         },
+        {
+            code: [
+                "module.exports = {",
+                "    meta: [],",
```
Comment (Aladdin-ADD) [inline tests/tools/internal-rules/no-invalid-meta.js]: meta could be an object. is the `[]` intentional?

Comment (s4san) [reply tests/tools/internal-rules/no-invalid-meta.js]: Yes. In case of an emtpy object, `node.properties` is `[]` but for any other type it is `undefined` resulting in a crash. I intentionally declared `meta` as an `array` to elicit this case

Comment (Aladdin-ADD) [reply tests/tools/internal-rules/no-invalid-meta.js]: I see.thanks for the clarification!
