### PR TITLE
Fix: arrow-body-style fixer for `in` wrap (fixes #11849)

### LINKED ISSUE #11849: arrow-body-style autofix with 'in' in a for-loop init
**Tell us about your environment**

* **ESLint Version:** 5.16.0 (same behaviour with 6.0.0-rc.0)
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 6,
  },
  rules: {
    "arrow-body-style": "error",
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
for (let a = b => { return b in c; }; ;);
```

```bash
eslint index.js --fix
```

**What did you expect to happen?**

Not a SyntaxError in the fixed code.

**What actually happened? Please include the actual, raw output from ESLint.**

```js
for (let a = b => b in c; ;);
```

The fix changed semantics and produced an error: 

> `SyntaxError: for-in loop variable declaration may not have an initializer.`

This is similar to [#11706](https://github.com/eslint/eslint/issues/11706)

**Are you willing to submit a pull request to fix this bug?**

Yes, when PR [#11848](https://github.com/eslint/eslint/pull/11848) is finished, since it might be a similar fix.

**Note**

The fixed code is SyntaxError in Node/Chrome and Firefox (with a bit different message).

However, it's a valid ForStatement for acorn, babel-eslint and other parsers (e.g. not esprima).

Check: [AST Explorer](https://astexplorer.net/#/gist/f2099b9c9d5e5d2637e94c619ce207b8/816578b963086b257121fa089b00940f9762be27)

Reported [acorn #838](https://github.com/acornjs/acorn/issues/838)

### PR DESCRIPTION
**Pull request by anikethsaha**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Fixed the fixer for `in` operator being wrongly fixed. wrapping the whole body when there is an `in` operator. `inIn` method will check if the body has `in` operator or not. wrapping the whole as mentioned in the issue was decided.

#### Is there anything you'd like reviewers to focus on?

fixes #11849

### CODE REVIEW

File: tests/lib/rules/arrow-body-style.js [hunk 1]
```diff
@@ -45,6 +45,77 @@ ruleTester.run("arrow-body-style", rule, {
...
+        },
+        {
+            code: "const fn = (a, b) => { return a + x in Number(b) };",
+            output: "const fn = (a, b) => (a + x in Number(b));",
+            errors: [{
+                line: 1,
+                column: 22,
+                messageId: "unexpectedSingleBlock"
+            }]
+        },
```
[the remark this answers is not in the document]
Comment (anikethsaha) [reply tests/lib/rules/arrow-body-style.js:118]: I added wrap if `in` operator is found just to be safe if there is any kind of issue. It will add wrap even if it's valid just to minimize the complexity otherwise we need to validate the code (I am not sure how to do so for a particular block).

File: lib/rules/arrow-body-style.js [hunk 2]
```diff
@@ -99,6 +99,24 @@ module.exports = {
             return sourceCode.getTokenAfter(node);
         }
 
+        /**
+         * check if node has `in` operator or not
```
[the remark this answers is not in the document]
Comment (anikethsaha) [reply lib/rules/arrow-body-style.js:103]: should `capitalized-comments`  be added in `.eslintrc.js` in this repo ?
I think `eslint-config-eslint` doesn't have it.

[the remark this answers is not in the document]
Comment (yeonjuan) [reply lib/rules/arrow-body-style.js:103]: @anikethsaha 
> should capitalized-comments be added in .eslintrc.js in this repo ?
I think eslint-config-eslint doesn't have it.

I'm not sure. It's just a non-blocking, suggestion :)

[the remark this answers is not in the document]
Comment (anikethsaha) [reply lib/rules/arrow-body-style.js]: done

File: tests/lib/rules/arrow-body-style.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (yeonjuan) [reply tests/lib/rules/arrow-body-style.js:118]: @anikethsaha 
> I added wrap if in operator is found just to be safe if there is any kind of issue.

IMO, the `arrow-body-style` fixer should not add extra parentheses. (except for within "for", because it's not extra parentheses)

+ Adding extra parenthesis in the `arrow-body-style` can make conflict with `no-extra-parens`.

```js
/* eslint no-extra-parens: ["error", "all"] */

for (let a = (b, c, d) => (c in d); ;); // No Error, because these are not extra parentheses 
 
do{
  let a = () => (f in ff) // Error
}while(true){}

scores.map(score => (x in +(score / maxScore).toFixed(2))); // Error
 
const fn = (a, b) => (a + x in Number(b)); // Error
```

[the remark this answers is not in the document]
Comment (anikethsaha) [reply tests/lib/rules/arrow-body-style.js]: @yeonjuan can you check the latest commit, if it's fine by you

**Comment by anikethsaha** [comment]
@yeonjuan thanks for pointing. 

I think , [this check](https://github.com/eslint/eslint/pull/13228/commits/6b6aab7b693c46108a2e37d19aada78cc4c56548#diff-c2240f0cdfc25e416753260c2a767fdeR212) needs to be changed. 



I think there will be conflict to solve this 👇 

> ```js
> // input
> for ( a = (b) => { return (c in d) }; ;);
> 
> // expected
> for ( a = (b) => (c in d); ;);
> 
> // result of the auto fix -  PR 
> for ( a = (b) => ((c in d)); ;);
> ```

and the one you mentioned in https://github.com/eslint/eslint/pull/13228#pullrequestreview-417263271 ?


What I am thinking is to track the opening braces and closing braces, if all opening braces are closed then the next token should be `;` .

Not sure though.

**Comment by yeonjuan** [comment]
@anikethsaha 
> What I am thinking is to track the opening braces and closing braces, if all opening braces are closed then the next token should be ; 
> ...
> or we can keep this ?

Well, I'm not sure how we can treat it.
Maybe just checks whether the node to fix already wrapped by parens?
Let's hear other's thought

**Comment by anikethsaha** [comment]
> Maybe just checks whether the node to fix already wrapped by parens?

@yeonjuan this is what I am trying to do by checking the leading `(` ,

What I can do it to check if they are with `)` or not. 

but then this case might be conflicting.

```js
for ( a = (b) => { return c in (d+c) }; ;);
```

do you have any other way to check for wrapped or not.? maybe I am missing something here.

**Comment by nzakas** [comment]
@yeonjuan looks like there's a question for you on this PR

**Comment by mdjermanovic** [comment]
There are many cases where those parens wouldn't be necessary:

```js
for (a = b => { return (c in d) } ;;) {}

for (a = b => { return [c in d] } ;;) {}

for (a = b => { return c || (d in e) } ;;) {}

for (a = b => { return c || (d && e in f) } ;;) {}

for (a = (b => { return c in d }) ;;) {}

for (a = [b => { return c in d }] ;;) {}
```

A similar problem (`in` in for-loop initializer) with `no-extra-parens` rule was fixed in #11848, and it handles all these cases, but that's the rule about extra parens, so such complexity to avoid extra parens makes sense there

In my opinion, `arrow-body-style` should just always add those parens if the arrow function is in a for-loop initializer and there's `in` inside the arrow function. That combination is an edge case anyway, and those parens will be removed by `no-extra-parens` if they're unnecessary.

File: lib/rules/arrow-body-style.js [hunk 3]
```diff
@@ -99,6 +99,24 @@ module.exports = {
...
 
+        /**
+         * Checks if a node has `in` operator or not
+         * @param {Node} node The argument node which needs to be checked
+         * @returns {boolean} `true` if there is an `in` operator else `false`.
+         */
+        function isIn(node) {
+            if (
+                node.type === "BinaryExpression" ||
+                node.type === "LogicalExpression"
```
Comment (mdjermanovic) [inline lib/rules/arrow-body-style.js:110]: I think this wouldn't catch:

```js
/*eslint arrow-body-style: ["error", "as-needed"]*/

for (a = b => { return c in d ? e : f } ;;);

for (a = b => { return c = d in e } ;;);
```

Could we maybe add `"BinaryExpression[operator='in']"(node)` listener and store the info, instead of traversing the node manually?

File: lib/rules/arrow-body-style.js [hunk 4]
```diff
@@ -174,15 +194,28 @@ module.exports = {
                                 );
                             }
 
+                            let n = node;
+
+                            if (isInOp) {
+                                while (n.type !== "ForStatement" && n.parent && (n.parent.type !== "BlockStatement" || n.parent.type !== "Program")) {
+                                    n = n.parent;
```
Comment (mdjermanovic) [inline lib/rules/arrow-body-style.js:201]: It would be nice to extract this to a function.

Maybe `IsInForLoopInitializer(node)`, returns `true` or `false`.

**Comment by yeonjuan** [comment]
@anikethsaha 

> do you have any other way to check for wrapped or not.? Maybe I am missing something here.

maybe we can do it by checking whether the whole returned node is wrapped by parenthesis (not only checking the first token of the node) -but not sure cause I didn't try it.

> In my opinion, arrow-body-style should just always add those parens if the arrow function is in a for-loop initializer and there's in inside the arrow function. That combination is an edge case anyway, and those parens will be removed by no-extra-parens if they're unnecessary.

But, as the @mdjermanovic 's comment, it might be reasonable not to check extra parens in here strictly. Sorry if you got a confusion.

File: lib/rules/arrow-body-style.js (hunk 3 above)
Comment (anikethsaha) [reply lib/rules/arrow-body-style.js:110]: @mdjermanovic here is the output for the cases you mentioned. 

```js
/*eslint arrow-body-style: ["error", "as-needed"]*/

for (a = b => { return c in d ? e : f } ;;);
// output : for (a = b => c in d ? e : f ;;);

for (a = b => { return c = d in e } ;;);
// output : for (a = b => c = d in e ;;);

```

Comment (anikethsaha) [reply lib/rules/arrow-body-style.js:110]: > Could we maybe add `"BinaryExpression[operator='in']"(node)` listener and store the info, instead of traversing the node manually?

I added the following

```js
     "BinaryExpression[operator='in']": function(node){
                isIn = false;
            },
      "BinaryExpression[operator='in']:exit": function(node){
                isIn = true;
            }
```
`isIn` is a initialized as `false` inside the `create` method. 
Now in [this line](https://github.com/eslint/eslint/pull/13228/files#diff-c2240f0cdfc25e416753260c2a767fdeR199), checking  
```js
if(isIn){
...
``` 

Is passing all the test cases but not the one you mentioned here https://github.com/eslint/eslint/pull/13228/files#r439331716

```js
/*eslint arrow-body-style: ["error", "as-needed"]*/

for (a = b => { return c in d ? e : f } ;;);
// output : for (a = b => (c in d ? e : f) ;;);

for (a = b => { return c = d in e } ;;);
// output : for (a = b => (c = d in e) ;;);
```

Comment (mdjermanovic) [reply lib/rules/arrow-body-style.js:110]: We should probably have some sort of stack with one "info" element per arrow function, see for example how it is done in `require-await` rule.

Comment (anikethsaha) [reply lib/rules/arrow-body-style.js:110]: @mdjermanovic can you recommend what should be the output for the cases you mentioned?

Like I changed the code to a similar one like `require-await` and the behavior is like this 

```js
// Input 
for (let a = (b, c, d) => { return vb && c in d; }; ;);

// This PR change
for (let a = (b, c, d) => (vb && c in d); ;);

// After similar change to `require-await`
for (let a = (b, c, d) => vb && c in d; ;);
```

Comment (mdjermanovic) [reply lib/rules/arrow-body-style.js:110]: Output with parens is correct, it's syntax error without parens.

I can't tell what's wrong without the code :) it would be easier if you'd push some version that looks good to you so we could see how to fix those cases that still don't work.

File: lib/rules/arrow-body-style.js [hunk 5]
```diff
@@ -245,6 +257,9 @@ module.exports = {
         }
 
         return {
+            "BinaryExpression[operator='in']:exit"() {
+                isInOp = true;
+            },
```
[the remark this answers is not in the document]
Comment (mdjermanovic) [reply lib/rules/arrow-body-style.js:262]: We can do something like this:

```js
let funcInfo = null;

// ....

"BinaryExpression[operator='in']"() {
    let info = funcInfo;
    while (info) {
        info.hasInOperator = true;
        info = info.upper;
    }
},
ArrowFunctionExpression() {
    funcInfo = {
        upper: funcInfo,
        hasInOperator: false
    };
},
"ArrowFunctionExpression:exit"(node) {
    validate(node);
    funcInfo = funcInfo.upper;
}
```

so we can use `funcInfo.hasInOperator` in `function validate`

File: lib/rules/arrow-body-style.js [hunk 6]
```diff
@@ -174,15 +175,26 @@ module.exports = {
...
                              * enclose the return value by parentheses to avoid syntax error.
                              */
-                            if (astUtils.isOpeningBraceToken(firstValueToken) || blockBody[0].argument.type === "SequenceExpression") {
-                                fixes.push(
-                                    fixer.insertTextBefore(firstValueToken, "("),
-                                    fixer.insertTextAfter(lastValueToken, ")")
-                                );
+                            if (astUtils.isOpeningBraceToken(firstValueToken) || blockBody[0].argument.type === "SequenceExpression" || (n.type === "ForStatement" && isInOp)) {
+
+                                if (firstValueToken.value !== "(") {
```
Comment (mdjermanovic) [inline lib/rules/arrow-body-style.js:192]:
```suggestion
                                if (!astUtils.isParenthesised(sourceCode, blockBody[0].argument)) {
```

**Comment by anikethsaha** [comment]
@mdjermanovic I changed the code to a bit different, It seems working though, Let me know if this needs to be changed if so I will check with the approach you mentioned.

**Comment by mdjermanovic** [comment]
It still doesn't work well in this case (we should probably add this as a test case):

```js
/*eslint arrow-body-style: ["error", "as-needed"]*/

a in b;

for (var f = () => { return c };;);
```

auto-fixes to:

```js
/*eslint arrow-body-style: ["error", "as-needed"]*/

a in b;

for (var f = () => (c);;);
```

This is the order of events for this example:

```
BinaryExpression[operator='in'] > *:exit (a)
BinaryExpression[operator='in'] > *:exit (b)
BinaryExpression[operator='in']:exit
ArrowFunctionExpression
ArrowFunctionExpression:exit
```

**Comment by anikethsaha** [comment]
@mdjermanovic I did add a test case for the mentioned code here https://github.com/eslint/eslint/pull/13228/files#diff-a5a55cb049da483c38e374fd2af60fecR62 , is this what you were referring?

not sure about `a in b;` .

> BinaryExpression[operator='in'] > *:exit (a)
> BinaryExpression[operator='in'] > *:exit (b)
> BinaryExpression[operator='in']:exit
> ArrowFunctionExpression
> ArrowFunctionExpression:exit

cool, I will check this

> ```js
> /*eslint arrow-body-style: ["error", "as-needed"]*/
> 
> a in b;
> 
> for (var f = () => { return c };;);
> ```

in this, are these two separate test cases or same ?

**Comment by mdjermanovic** [comment]
> in this, are these two separate test cases or same ?

1 test, something like:

```js
code: "a in b; for (var f = () => { return c };;);"
output: "a in b; for (var f = () => c;;);"
```

(no parens in output)

File: lib/rules/arrow-body-style.js [hunk 7]
```diff
@@ -245,6 +257,15 @@ module.exports = {
...
         return {
+            "BinaryExpression[operator='in'] > *:exit"() {
+                isInOp = false;
+            },
+            "BinaryExpression[operator='in']:exit"() {
+                isInOp = true;
+            },
+            "ArrowFunctionExpression"() {
+                isInOp = false;
+            },
```
Comment (mdjermanovic) [inline lib/rules/arrow-body-style.js:268]: This:

```js
/*eslint arrow-body-style: ["error", "as-needed"]*/

for (var foo = () => { return a in b ? bar : () => {} } ;;);
```

would be auto-fixed to:

```js
/*eslint arrow-body-style: ["error", "as-needed"]*/

for (var foo = () => a in b ? bar : () => {} ;;);
```

which is a syntax error.

Maybe we could try with [this approach](https://github.com/eslint/eslint/pull/13228/files#r443803994)?

File: tests/lib/rules/arrow-body-style.js [hunk 8]
```diff
@@ -45,6 +46,191 @@ ruleTester.run("arrow-body-style", rule, {
...
+            output: "scores.map(score => (x in +(score / maxScore).toFixed(2)));",
+            errors: [{
+                line: 1,
+                column: 21,
+                messageId: "unexpectedSingleBlock"
+            }]
+        },
+        {
+            code: "const fn = (a, b) => { return a + x in Number(b) };",
+            output: "const fn = (a, b) => (a + x in Number(b));",
```
Comment (mdjermanovic) [inline tests/lib/rules/arrow-body-style.js:227]: We should check whether or not the arrow function is in a for-loop initializer, because that's the only case that causes problems with the `in` keyword (it makes the loop being interpreted as a `for-in` loop).

Maybe a function `IsInsideForLoopInitializer(node)` which returns `true` or `false`.

Comment (anikethsaha) [reply tests/lib/rules/arrow-body-style.js]: done

File: lib/rules/arrow-body-style.js [hunk 9]
```diff
@@ -99,6 +100,19 @@ module.exports = {
...
+         * @param {ASTNode} node node is inside for loop
+         * @returns {boolean} `true` if the node is inside of a for loop, else `false`
+         */
+        function isInsideForLoopInitializer(node) {
+            if (node.type !== "ForStatement" && node.parent && (node.parent.type !== "BlockStatement" || node.parent.type !== "Program")) {
+                return isInsideForLoopInitializer(node.parent);
+            }
+
+            return node.type === "ForStatement";
+        }
```
Comment (mdjermanovic) [inline lib/rules/arrow-body-style.js:114]: Looks good, can we just additionally make sure that it's in `ForStatement#init` (since this function now also returns `true` if it's in `test`, `update`, or `body`).

Comment (anikethsaha) [reply lib/rules/arrow-body-style.js]: done

File: lib/rules/arrow-body-style.js [hunk 10]
```diff
@@ -245,7 +263,24 @@ module.exports = {
         }
 
         return {
-            "ArrowFunctionExpression:exit": validate
+            "BinaryExpression[operator='in']"() {
+                let info = funcInfo;
```
Comment (anikethsaha) [inline lib/rules/arrow-body-style.js:267]: @mdjermanovic just a doubt. 

why referring `funcInfo` to `info` is working but instead using `funcInfo` alone in the while loop is not working.

Comment (mdjermanovic) [reply lib/rules/arrow-body-style.js:267]: I'm not sure I understand, what would the code look like?

Comment (anikethsaha) [reply lib/rules/arrow-body-style.js:267]: my doubt is like why without the `info` variable , using `funcInfo` instead in the while loop is not working. 
I tried changing that and most of the test cases failed.

Comment (mdjermanovic) [reply lib/rules/arrow-body-style.js:267]: `funcInfo` is data about the arrow function that's being traversed at the given moment. If we change it before `"ArrowFunctionExpression:exit"`, `function validate` will have wrong data (or no data if it's `null`).

Comment (anikethsaha) [reply lib/rules/arrow-body-style.js:267]: I meant , changing this https://github.com/eslint/eslint/pull/13228/files#diff-c2240f0cdfc25e416753260c2a767fdeR267-R273

with

```js
"BinaryExpression[operator='in']"() {
         while (funcInfo) {
                    funcInfo.hasInOperator = true;
                    funcInfo= funcInfo.upper;
                }
            },
```

is producing wrong result, just curious to know why !

Comment (mdjermanovic) [reply lib/rules/arrow-body-style.js:267]: It will become `null` at the end of the loop, so `if (astUtils.isOpeningBraceToken(firstValueToken) || blockBody[0].argument.type === "SequenceExpression" || (funcInfo.hasInOperator && isInsideForLoopInitializer(node)))` in `function validate` will throw error.

Comment (anikethsaha) [reply lib/rules/arrow-body-style.js:267]: Okk, 
so we are using the temp variable to change the property of the `funcInfo` as it is being referred there and even if `info` becomes `null`, `funcInfo` will have the non `null` value of the previous iteration of the while loop .

something like this right ?

Comment (mdjermanovic) [reply lib/rules/arrow-body-style.js:267]: yes, it's just a temp variable that helps to set `hasInOperator = true` for all currently "active" arrow functions, without changing anything else.

Comment (anikethsaha) [reply lib/rules/arrow-body-style.js:267]: cool, thanks a lot 💯

**Comment by kaicataldo** [comment]
@yeonjuan Have your concerns been addressed?

**Comment by nzakas** [comment]
@yeonjuan just checking in to see if you're ready to approve this latest version?
