### PR TITLE
Breaking: check unnamed default export in func-names (fixes #12194)

### LINKED ISSUE #12194: func-names does not report default exported function
**Tell us about your environment**

* **ESLint Version:** 6.3.0
* **Node Version:** 12

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
`func-names: [2, "always"]` or
`func-names: [2, "as-needed"]`

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/* eslint func-names: [2, 'as-needed'] */
// or  'always'

export default function () {}
```
https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGZ1bmMtbmFtZXM6IFsyLCAnYXMtbmVlZGVkJ10gKi9cbi8vIG9yICAnYWx3YXlzJ1xuXG5leHBvcnQgZGVmYXVsdCBmdW5jdGlvbiAoKSB7fVxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo5LCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19

**What did you expect to happen?**
Unnamed function to be reported.

**What actually happened? Please include the actual, raw output from ESLint.**
No error is reported.

**Are you willing to submit a pull request to fix this bug?**
Yes please.

**Notes**
The main purpose of func-names is to avoid unhelpful names like "anonymous" popping up in stack trace or profiling chart. In the case of unnamed default export, the function names will be `_default` for babel transformed code, or `default` for node 12 experimental modules. These names are uninformative for debugging. So func-names should report this case.

### PR DESCRIPTION
**Pull request by golopot**
fixes #12194

**What is the purpose of this pull request? (put an "X" next to item)**
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

**What changes did you make? (Give an overview)**
Start report code like `export default function() {}` when `always` or `as-needed`.

**Is there anything you'd like reviewers to focus on?**
Yes.

### CODE REVIEW

File: tests/lib/rules/func-names.js [hunk 1]
```diff
@@ -127,6 +119,28 @@ ruleTester.run("func-names", rule, {
...
+            options: ["always"],
+            parserOptions: { sourceType: "module", ecmaVersion: 6 }
+        },
+        {
+            code: "export default function foo() {}",
+            options: ["as-needed"],
+            parserOptions: { sourceType: "module", ecmaVersion: 6 }
+        },
+        {
+            code: "export default function foo() {}",
```
Comment (platinumazure) [inline tests/lib/rules/func-names.js]: How is this valid? The option is `"never"` but the function has a name.

Comment (mdjermanovic) [reply tests/lib/rules/func-names.js]: That would require more checks, `foo` is here a declaration and can be used from within the module. And even if that's not the case, I believe this would break some builds

**Comment by mdjermanovic** [comment]
Just to note that this PR at the moment also changes how the rule works with function expressions when the option is `as-needed`.

Also, all 3 changes would be 'false negatives' if this is seen as a bug, and the message should certainly start with `Update:`

File: tests/lib/rules/func-names.js (hunk 1 above)
Comment (golopot) [reply tests/lib/rules/func-names.js]: The reasoning is that, under option never, function f() is allowed, export function f() is allowed, so likewise export default function f() should be allowed.

I understand in some perspective this should be reported, so this case is controvesial. Not reporting in this case would make both sides happy.

**Comment by kaicataldo** [comment]
How do we want to proceed here? It looks like this was marked as a breaking change rather than a semver-minor bug fix, but it's not entirely clear why.

**Comment by kaicataldo** [comment]
@mdjermanovic Can we merge this?

**Comment by mdjermanovic** [comment]
An overview of the new behavior after this PR:

```js
/*eslint func-names: ["error", "always"]*/

export default function () {} // error (*)

export default function foo() {} // ok

export default (function (){}); // error

export default (function foo(){}); // ok
```

```js
/*eslint func-names: ["error", "as-needed"]*/

export default function () {} // error (*)

export default function foo() {} // ok

export default (function (){}); // error (*)

export default (function foo(){}); // ok
```

```js
/*eslint func-names: ["error", "never"]*/

export default function () {} // ok

export default function foo () {} // ok!

export default (function (){}); // ok

export default (function foo(){}); // error
```

`(*)` marks changes in behavior made in this PR.

There are three `(*)`, caused by these **two** different changes in logic:

* `export default function () {}` will be treated as function expressions. It was ignored before since it's a function declaration.
* Anonymous functions in `export default` will be treated as functions that don't get automatically assigned name, thus they'll be reported when the option is `as-needed`. They were valid before since they get assigned the `"default"` name (intentionally valid, there is an explicit condition for that and an example in the original issue [#7235](https://github.com/eslint/eslint/issues/7235#issue-179060965)).

Also, `export default function foo () {}` with `"never"` is an intentional exception to the new logic. It might be consistent to require removing the name, but users probably wouldn't want that.

Questions:

* Do we have consensus on both changes.
* Should we update the documentation (aside from the new examples). At the moment, it's explicitly about function expressions only. Also, `export default` does assign a name.

**Comment by btmills** [comment]
In today's TSC meeting, we added this to the v7.0.0 release!

File: docs/rules/func-names.md [hunk 2]
```diff
@@ -16,8 +16,8 @@ This rule can enforce or disallow the use of named function expressions.
 
 This rule has a string option:
 
-* `"always"` (default) requires function expressions to have a name
-* `"as-needed"` requires function expressions to have a name, if the name cannot be assigned automatically in an ES6 environment
+* `"always"` (default) requires function expressions and default export functions to have a name
+* `"as-needed"` requires function expressions and default export functions to have a name, if the name cannot be assigned automatically in an ES6 environment
```
Comment (golopot) [inline docs/rules/func-names.md]: > Should we add a short note that as-needed requires names for functions in export default, somewhere in the documentation (maybe in the ### as-needed section)?

@mdjermanovic How about this?

Comment (mdjermanovic) [reply docs/rules/func-names.md]: Hm, I think it still doesn't explain that the `as-needed` option requires a name for default export functions in spite of the fact that the name can be assigned automatically.

Perhaps we could revert this to keep these descriptions short (but slightly inaccurate) and add a note somewhere below?

Maybe something like this at the end of that section (right above `### always`):

```
Please note that `"always"` and `"as-needed"` require function expressions and function declarations in `export default` declarations to have a name.

Comment (golopot) [reply docs/rules/func-names.md]: That sounds good.

**Comment by kaicataldo** [comment]
Thanks for contributing to ESLint!
