### PR TITLE
Fix: Windows path parsing for JUnit (fixes #12507)

### LINKED ISSUE #12507: Parsing in `pathWithoutExt(filePath)` does not work for Windows paths
Environment is Windows 10 Version 1809

Environment Info:

Node version: v10.15.0
npm version: v6.4.1
Local ESLint version: v6.5.1 (Currently used)
Global ESLint version: Not found

**What parser (default, Babel-ESLint, etc.) are you using?** default (N/A)

**Please show your full configuration:** (N/A)

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

We run ESLint in Jenkins CI on a Windows host, and get the following type of output from failures
image

Currently, this means we do not know the filepath for the files with errors, only for the ones which passed.

This issue arises as a result of PR #11683. See below:

https://github.com/eslint/eslint/blob/287ca562811d037bde09a47af7f5b9c7b741e022/lib/cli-engine/formatters/junit.js#L28-L36

The above code assumes that POSIX filePaths are used, meaning that the function does not work as expected in Windows.

```bash
npx eslint home_page.js --format junit
```

**What did you expect to happen?**
I expect that in the `classname` tag below I can see the full path to the file, without the file extension for visualization within Jenkins CI on a Windows host. i.e. `C:\path\to\file` 
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
<testsuite package="org.eslint" time="0" tests="1" errors="1" name="C:\git\projectdirectory\home_page.js">
<testcase time="0" name="org.eslint.prefer-const" classname="C:\git\projectdirectory\home_page"><failure message="&apos;msg&apos; is never reassigned. Use &apos;const&apos; instead."><![CDATA[line 7, col 17, Error - &apos;msg&apos; is never reassigned. Use &apos;const&apos; instead. (prefer-const)]]></failure></testcase>
</testsuite>
</testsuites>
```

**What actually happened? Please include the actual, raw output from ESLint.**
The function above parses `filePath` incorrectly on Windows. `path.posix.dirname('C:\\path\\to\\file.js')` resolves to `.` on Windows, as `posix` forces an assumption of POSIX style paths.

This results in the following XML, without the full path to the file in the `classname` attribute:
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
<testsuite package="org.eslint" time="0" tests="1" errors="1" name="C:\git\projectdirectory\home_page.js">
<testcase time="0" name="org.eslint.prefer-const" classname="home_page"><failure message="&apos;msg&apos; is never reassigned. Use &apos;const&apos; instead."><![CDATA[line 7, col 17, Error - &apos;msg&apos; is never reassigned. Use &apos;const&apos; instead. (prefer-const)]]></failure></testcase>
</testsuite>
</testsuites>
```

**Are you willing to submit a pull request to fix this bug?**
Yes.

I would propose a fix where we do not use the `posix` specific implementation of Node's `path` library, and we let Node decide which implementation to use based on the underlying OS.

The main question arises in testing. In https://github.com/eslint/eslint/blob/master/tests/lib/cli-engine/formatters/junit.js is it possible to run a test with both POSIX and Windows style paths? My suggestion would be to have the test cases adapt to the current OS, but opinions would be valued here.

### PR DESCRIPTION
**Pull request by thewalla07**
This commit aims to fix the issues described in #12507 by removing the
assumption that POSIX style filePaths are supplied by messages.

The tests for this are also updated to run on both Windows and POSIX
based systems. The results can be seen by running ESLint with the JUnit
formatter on a Windows system.

Full details can be seen in the issue mentioned above.

**What is the purpose of this pull request? (put an "X" next to item)**
This PR is a followup to fix a missed bug introduced in #11683 where Windows paths are not supported properly.
[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
I changed the function `pathWithoutExt(filePath)` so that it does not assume POSIX style paths. Instead it will allow Node to determine which style of path to expect (POSIX or Windows) based on the OS.

From looking at the original PR it seems that this change to assume POSIX was done after the changes were approved, and might have been to force tests to pass (but I did not verify this).

Hence, I also updated the tests for the JUnit formatter so that they should run correctly on both Windows and *Nix machines by passing in an OS relevant `suppliedFilePath` to the test, and verifying with an OS relevant `expectedClassName`.

**Is there anything you'd like reviewers to focus on?**
Test sanity.

### CODE REVIEW

File: tests/lib/cli-engine/formatters/junit.js [hunk 1]
```diff
@@ -12,12 +12,37 @@
...
 //------------------------------------------------------------------------------
 // Tests
 //------------------------------------------------------------------------------
 
+/**
+ * Returns the suppliedFilePath for each test
+ * @returns {string} the filepath in a format that would be expected on either a win32 system or POSIX system
+ * @private
+ */
+function suppliedFilePath() {
```
Comment (kaicataldo) [inline tests/lib/cli-engine/formatters/junit.js]: Thoughts on making these two actual constants instead of having to call the functions everywhere?

**Comment by thewalla07** [comment]
> Generally, I think this looks good. One question I have (and I'm not sure of the answer): Do we want to rely on our CI that runs our tests in multiple OS's to exercise this code, or should we be mocking `process.platform` in these tests to ensure these code paths are always hit?

I did some investigation on this and it seems less feasible to test this way, although I agree this would have been nicer. If we mock `process.platform` we need to be guaranteed that this is done before the node module `path` is loaded, otherwise we have issues because `path` does not dynamically check which platform we are on (and this makes sense, it shouldn't). Even if we can satisfy this guarantee, we then cannot switch back to another platform in the same test. We could override many functions in this module to get the desired behavior but I think this is overkill for this test scenario.

File: tests/lib/cli-engine/formatters/junit.js (hunk 1 above)
Comment (thewalla07) [reply tests/lib/cli-engine/formatters/junit.js]: Fine for me, changed

**Comment by kaicataldo** [comment]
Understood - thanks for the detailed explanation!

**Comment by kaicataldo** [comment]
Sorry, my Windows machine is on the fritz. Will need to fix it tomorrow to be able to test this. If someone else from the team is able to verify this bug, please feel free to mark as accepted.

**Comment by kaicataldo** [comment]
Thanks for contributing!
