### PR TITLE
fix: Ensure unmatched glob patterns throw an error

### LINKED ISSUE #16275: Bug: [new config system] unmatched individual patterns are not reported
### Environment

Node version: v16.14.0
npm version: v8.3.1
Local ESLint version: v8.23.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19044

### What parser are you using?

Default (Espree)

### What did you do?

I ran the following command in my local clone of the eslint/eslint repo, `main` branch:

```
node ./bin/eslint.js "tools/*.js" "doesnotexist/*.js" -f tap
```

### What did you expect to happen?

Since there is no `doesnotexist` directory, I would expect an error saying that the `doesnotexist/*.js` pattern is unmatched:

```
Oops! Something went wrong! :(

ESLint: 8.23.0

No files matching the pattern "doesnotexist/*.js" were found.
Please check for typing mistakes in the pattern.
```

This is the current behavior in eslintrc mode (when `eslint.config.js` file is deleted).

### What actually happened?

Successful linting:

```
TAP version 13
1..7
ok 1 - D:\projects\eslint\tools\code-sample-minimizer.js
ok 2 - D:\projects\eslint\tools\config-rule.js
ok 3 - D:\projects\eslint\tools\eslint-fuzzer.js
ok 4 - D:\projects\eslint\tools\fetch-docs-links.js
ok 5 - D:\projects\eslint\tools\fuzzer-runner.js
ok 6 - D:\projects\eslint\tools\update-readme.js
ok 7 - D:\projects\eslint\tools\update-rule-types.js
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This happens because we're passing to `globby` all the patterns together, so we don't know if some of them didn't match anything.

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Before this change, the CLI running in flat config mode would not throw an error if at least one glob pattern matched. After this change, the CLI running in flat config mode throws an error, which matches the behavior of eslintrc mode.

Fixes #16275

#### Is there anything you'd like reviewers to focus on?

Please double-check the added test and the updated test to be sure the correct behavior is being tested.

### CODE REVIEW

File: lib/eslint/eslint-helpers.js [hunk 1]
```diff
@@ -151,94 +285,176 @@ async function globSearch({ basePath, patterns, configs }) {
...
+                    // update unmatched patterns for potential errors
+                    if (pathMatches) {
+                        unmatchedPatterns.delete(matcher.pattern);
+                    }
+
+                    return pathMatches || previousValue;
+                }, false)
+                : matchers.some(matcher => matcher.match(relativePath));
 
             return matchesPattern && !configs.isFileIgnored(entry.path);
```
Comment (mdjermanovic) [inline lib/eslint/eslint-helpers.js:310]: Here, if the file is ignored, it still removes patterns from `unmatchedPatterns`, which seems wrong because when there are multiple patterns and at least one matches some non-ignored files, patterns that match only ignored files will not be reported.

For example, run:

```
eslint "lib/*.js" "tools/*.js" --ignore-pattern "tools/*.js"
```

In flat config mode, this command exits with 0 because `"lib/*.js"` matches something, although `"tools/*.js"` does not (it matches only ignored files).

In eslintrc mode, the same command exits with 1:

```
Oops! Something went wrong! :(

ESLint: 8.26.0

You are linting "tools/*.js", but all of the files matching the glob pattern "tools/*.js" are ignored.

...
```

I think that eslintrc behavior is correct and that flat eslint should work the same.

File: lib/eslint/eslint-helpers.js [hunk 2]
```diff
@@ -47,6 +58,30 @@ class NoFilesFoundError extends Error {
     }
 }
 
+/**
+ * The error type when a search fails to match multiple patterns.
+ */
+class UnmatchedSearchPatternsErrror extends Error {
```
Comment (mdjermanovic) [inline lib/eslint/eslint-helpers.js:64]:
```suggestion
class UnmatchedSearchPatternsError extends Error {
```

Typo (three r in Errror).

File: lib/eslint/eslint-helpers.js (hunk 1 above)
Comment (nzakas) [reply lib/eslint/eslint-helpers.js:310]: Oh wow, nice catch. Yes this is a bug.

File: lib/eslint/eslint-helpers.js [hunk 3]
```diff
@@ -151,94 +285,185 @@ async function globSearch({ basePath, patterns, configs }) {
...
-                found = true;
-                return true;
-            }
-
-            return false;
+            // if the are no results we need to check for ignored files
+            await checkForIgnoredResults({
+                ...currentSearch,
+                errorOnUnmatchedPattern
+            });
```
Comment (mdjermanovic) [inline lib/eslint/eslint-helpers.js:446]: I think this should be removed.

With `errorOnUnmatchedPattern = true`, `globSearch` will either return some results or throw `UnmatchedSearchPatternsError`, so either way `globMultiSearch` will never fall into this branch?

With `errorOnUnmatchedPattern = false`, this causes a different behavior than that of eslintrc in regard to patterns that match only ignored files.

For example, run:

```
eslint "tools/*.js" --ignore-pattern "tools/*.js" --no-error-on-unmatched-pattern
```

In eslintrc mode, this exits with 0, meaning that `--no-error-on-unmatched-pattern` applies to patterns that match only ignored files too.

In flat config mode (current iteration of this PR), the same command throws an error:

```
Oops! Something went wrong! :(

ESLint: 8.26.0

You are linting "tools/*.js", but all of the files matching the glob pattern "tools/*.js" are ignored.
```

File: lib/eslint/eslint-helpers.js [hunk 4]
```diff
@@ -151,94 +285,185 @@ async function globSearch({ basePath, patterns, configs }) {
...
+ *      any files and `errorOnUnmatchedPattern` is true.
+ * @throws {AllFilesIgnoredError} If there is a pattern that matches files
+ *      when there are no ignores.
+ */
+async function checkForIgnoredResults({
+    basePath,
+    patterns,
+    rawPatterns,
+    patternsToCheck = patterns,
+    errorOnUnmatchedPattern
```
Comment (mdjermanovic) [inline lib/eslint/eslint-helpers.js:364]: Related to https://github.com/eslint/eslint/pull/16462#discussion_r1009869403, it doesn't seem that this function should  have `errorOnUnmatchedPattern` param, but rather be called only if `errorOnUnmatchedPattern = true`?

File: lib/eslint/eslint-helpers.js (hunk 3 above)
Comment (nzakas) [reply lib/eslint/eslint-helpers.js:446]: > In eslintrc mode, this exits with 0, meaning that --no-error-on-unmatched-pattern applies to patterns that match only ignored files too.

Ah! I misunderstood what we were already doing. I thought —no-error-on-unmatched-pattern only applied to patterns without a match that weren’t caused by ignores. 

Really nice catch!

File: lib/eslint/eslint-helpers.js [hunk 5]
```diff
@@ -151,94 +285,183 @@ async function globSearch({ basePath, patterns, configs }) {
...
+            const error = result.reason;
 
-        globStream.on("data", () => {
-            globStream.destroy();
-            resolve(true);
-        });
+            // unexpected errors should be re-thrown
+            if (!error.basePath) {
+                throw error;
+            }
```
Comment (mdjermanovic) [inline lib/eslint/eslint-helpers.js:453]: I think this should be outside `if (errorOnUnmatchedPattern) {}`, so that `errorOnUnmatchedPattern: false` does not suppress unexpected errors like file system errors. I denied permissions on `tools/internal-testers` directory, and then ran `eslint tools -f tap --no-error-on-unmatched-pattern`. It exits with 0 without linting anything. In eslintrc mode, the same command throws EPERM, which is I think better than silently ignoring the whole pattern.

File: lib/eslint/eslint-helpers.js [hunk 6]
```diff
@@ -151,94 +285,183 @@ async function globSearch({ basePath, patterns, configs }) {
...
 
-            const relativePath = normalizeToPosix(path.relative(basePath, entry.path));
-
-            if (matcher.match(relativePath)) {
-                found = true;
-                return true;
+            // if the are no results we need to check for ignored files
+            if (errorOnUnmatchedPattern) {
+                await checkForIgnoredResults(currentSearch);
             }
```
[the remark this answers is not in the document]
Comment (nzakas) [reply lib/eslint/eslint-helpers.js:440]: Oh agree, I just missed it.

File: lib/eslint/eslint-helpers.js (hunk 5 above)
Comment (nzakas) [reply lib/eslint/eslint-helpers.js:453]: Ah good call.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

I left one comment, but I think it can be addressed in a follow-up, so I'm merging this now for the release.
