### PR TITLE
fix: Ensure that glob patterns are matched correctly.

### LINKED ISSUE #16299: Bug: [new config system] path to a directory can still lint files outside that directory
### Environment

Node version: v16.14.0
npm version: v8.3.1
Local ESLint version: v8.23.1 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19044

### What parser are you using?

Default (Espree)

### What did you do?

Folder structure:

```
my-app/
├── docs1/
│   └── foo.md
├── docs2/
│   └── bar.md
└── eslint.config.js 
```

Config file:

```js
// eslint.config.js
module.exports = [{
    files: ["docs*/**/*.md"]
}];
```

Content of `.md` files is not important.

Command:

```
eslint docs1 -f tap
```

### What did you expect to happen?

```
TAP version 13
1..1
ok 1 - D:\tmp\my-app\docs1\foo.md
```

### What actually happened?

```
TAP version 13
1..2
ok 1 - D:\tmp\my-app\docs1\foo.md
ok 2 - D:\tmp\my-app\docs2\bar.md
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This happens because we are passing the `docs*/**/*.md` pattern to globby. The pattern is correctly selected as a pattern that can match files inside the `docs1` directory, but it can also match files outside the `docs1` directory.

Some solutions could be to:

1. Calculate a new pattern that would match like `docs*/**/*.md` but only inside the `docs1` directory. This seems very complex.
2. Keep passing the `docs*/**/*.md` pattern to globby, and after the globby call filter out results that are not inside the `docs1` directory. This should work at the end, but globby will still traverse directories outside `docs1`, which seems wrong.
3. Pass `docs1/**/*` to globby, and after the globby call filter out results that are not matched by `docs*/**/*.md`. This should work, and I think it's a better approach than 2.

### LINKED ISSUE #16413: Bug: [new config system] Files outside `cwd` were not found
### Environment

Node version: v16.14.0
npm version: v8.3.1
Local ESLint version: `main` branch
Global ESLint version: Not found
Operating System: win32 10.0.19044

### What parser are you using?

Default (Espree)

### What did you do?

```
my-app/
├── a.js
├── eslint.config.js
└── foo/
```

```js
// eslint.config.js
module.exports = [];

```

Command:

```
cd foo && eslint "../*.js" -f tap
```

### What did you expect to happen?

```
TAP version 13
1..2
ok 1 - D:\tmp\my-app\a.js
ok 2 - D:\tmp\my-app\eslint.config.js
```

This was the actual result before https://github.com/eslint/eslint/pull/16369. This is also the actual result when eslintrc config is used.

### What actually happened?

```
Oops! Something went wrong! :(

ESLint: 8.25.0

No files matching the pattern "../*.js" were found.
Please check for typing mistakes in the pattern.
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Refactored the glob search functionality to better handle relative paths. Also dramatically simplified the logic of figuring out which patterns to run.

Fixes #16413
Fixes #16299

#### Is there anything you'd like reviewers to focus on?

~~There is a change in behavior for patterns of `foo/**/*` in this PR. Previously, this would not match `*.txt` files, but I'm really not sure why. It seems like `foo/**/*` should match all files regardless of extension, so I updated that test to reflect this. Please let me know if this makes sense.~~

The error messages for patterns that don't match anything have changed. It was previously the interpolated pattern (you pass `foo` and the pattern is reported as `foo/**/*.js`) but now it reports the posix-normalized pattern. This is closer to matching what eslintrc does, which has the original pattern without it being posix-normalized. I think this changes makes sense but wanted to double check with the team.

### CODE REVIEW

File: tests/lib/eslint/flat-eslint.js [hunk 1]
```diff
@@ -811,8 +840,10 @@ describe("FlatESLint", () => {
 
                 assert.strictEqual(results.length, 2);
                 assert.strictEqual(results[0].messages.length, 1);
+                assert.strictEqual(results[0].filePath, getFixturePath("shallow-glob/subdir/subsubdir/broken.js"));
```
Comment (nzakas) [inline tests/lib/eslint/flat-eslint.js:843]: Added for clarity.

File: tests/lib/eslint/flat-eslint.js [hunk 2]
```diff
@@ -963,7 +994,7 @@ describe("FlatESLint", () => {
 
                 await assert.rejects(async () => {
                     await eslint.lintFiles(["node_modules"]);
-                }, /All files matched by 'node_modules\/\*\*\/\*.js' are ignored\./u);
+                }, /All files matched by 'node_modules' are ignored\./u);
```
Comment (nzakas) [inline tests/lib/eslint/flat-eslint.js:997]: With this update, the reported glob patterns match what is passed on the command line instead of the interpolated patterns we used. This matches the behavior of `eslintrc` and seems preferable to me.

File: tests/lib/eslint/flat-eslint.js [hunk 3]
```diff
@@ -4437,7 +4468,7 @@ describe("FlatESLint", () => {
             beforeEach(prepare);
             afterEach(cleanup);
 
-            it("'lintFiles()' with a directory path should NOT contain 'foo/test.txt' and 'foo/nested/test.txt'.", async () => {
+            it("'lintFiles()' with a directory path should contain 'foo/test.txt' and 'foo/nested/test.txt'.", async () => {
```
Comment (nzakas) [inline tests/lib/eslint/flat-eslint.js:4471]: For some reason `foo/**/*` was NOT matching `.txt` files prior to the changes in this PR. That seems like a mistake based on how flat config is intended to work, so I updated this test.

Comment (nzakas) [reply tests/lib/eslint/flat-eslint.js:4471]: On second thought, I believe this change is incorrect. I was previously filtering out `/*` and I think I should still do that. I'll get to work on that tomorrow.

Comment (mdjermanovic) [reply tests/lib/eslint/flat-eslint.js:4471]: Maybe we could simplify this by updating `ConfigArray#getConfig` to consider the file ignored if it doesn't match at least one pattern that doesn't end with `*`.  That would unify the behavior of directories and globs, so `eslint foo`, where `foo` is a directory, would be the same as `eslint "foo/**"`. A difference from the current design is that all targeted file extensions would need to be specified in the config file. For example, `eslint "src/**/*.ts"` would not match anything if the only config entry is `files: ["src/**"]`. That entry would have to be `files: ["src/**/*.ts"]` (or there could be another one that adds all ts files as lint targets, e.g. `files: ["**/*.ts"]`).

Comment (nzakas) [reply tests/lib/eslint/flat-eslint.js:4471]: Yup, that's exactly what I've implemented. Basically, the behavior of `/**` and`/*` now act as if the `files` key is missing: they only apply if something else matches.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
