### PR TITLE
Fix: Allow comments in key-spacing groups (fixes #1632)

### LINKED ISSUE #1632: key-spacing won't allow for comments
Comments should be disregarded when determining `key-spacing`.

version `0.11.0`

config:
```
"key-spacing": [ 2, { "align": "colon" } ]
// or
"key-spacing": [ 2, { "align": "value" } ]
```

code:
```
o = {
    longKey: 1,
    key2   : 2,
    // comment explaining key3
    key3   : 3
};
```
error:
```
5:4  error  Extra space after key "key3"  key-spacing
```

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7563040-key-spacing-won-t-allow-for-comments?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by btmills**

### CODE REVIEW

File: lib/rules/key-spacing.js [hunk 1]
```diff
@@ -47,6 +47,40 @@ function last(arr) {
...
+    if (candidateStartLine - groupEndLine <= 1) {
+        return true;
+    }
+
+    // Check that the first comment is adjacent to the end of the group, the
+    // last comment is adjacent to the candidate property, and that successive
+    // comments are adjacent to each other.
+    if (
+        (comments = candidate.leadingComments) &&
+        comments[0].loc.start.line - groupEndLine <= 1 &&
```
Comment (nzakas) [inline lib/rules/key-spacing.js]: Can you move the assignment outside the condition? The condition is complicated enough already.

**Comment by btmills** [comment]
Done.

**Comment by nzakas** [comment]
Lgtm. Thanks.
