### PR TITLE
fix!: remove deprecated `SourceCode` methods

### LINKED ISSUE #20113: Change Request: Remove deprecated SourceCode methods
### ESLint version

v9.35.0

### What problem do you want to solve?

A handful of `SourceCode` methods have been marked as deprecated for multiple versions but are still present in the runtime and type definitions. Specifically:

- `getTokenOrCommentBefore()`: Replaced by `SourceCode#getTokenBefore()` with the `{ includeComments: true }` option.
- `getTokenOrCommentAfter()`: Replaced by `SourceCode#getTokenAfter()` with the `{ includeComments: true }` option.
- `isSpaceBetweenTokens()`: Replaced by `SourceCode#isSpaceBetween()`
- `getJSDocComment()`

Only `isSpaceBetweenTokens` is still used in core, and its usages are confined to deprecated formatting rules. The other three methods are unused by core.

### What do you think is the correct solution?

Remove these deprecated `SourceCode` methods

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by Pixel998**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[x] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

- Removed long-deprecated `SourceCode` methods:
  - `getTokenOrCommentBefore`
  - `getTokenOrCommentAfter`
  - `isSpaceBetweenTokens`
  - `getJSDocComment`
 - Updated internal usages, tests, and docs accordingly.

Fixes #20113

### CODE REVIEW

File: tests/lib/languages/js/source-code/source-code.js
Comment (mdjermanovic) [inline tests/lib/languages/js/source-code/source-code.js:1]: This diff looks weird. I've manually checked that the only changes are removals of `describe("getJSDocComment()"` and `describe("isSpaceBetweenTokens()"` blocks.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Would like a second review.

**Review by JoshuaKGoldberg — APPROVED** [review]
🔪 great!

The diff really is unfortunate. But the changes really are a relatively straightforward removal.

**Comment by fasttime** [comment]
Note that there are merge conflicts now.

File: lib/types/index.d.ts
Comment (mdjermanovic) [inline lib/types/index.d.ts:1]: Should we now also remove these (added in https://github.com/eslint/eslint/commit/a1f06a350c4155c4dbf39bf932a38d71d70f1b65)?

https://github.com/eslint/eslint/blob/a1f06a350c4155c4dbf39bf932a38d71d70f1b65/lib/types/index.d.ts#L268-L278

**Review by fasttime — DISMISSED** [review]
LGTM, thanks!

**Review by mdjermanovic — DISMISSED** [review]
LGTM, thanks!

**Comment by snitin315** [comment]
Since we have started merging breaking changes, I think we can move this PR from the blocked state?

**Review by snitin315 — COMMENTED** [review]
@Pixel998 Let's update the migration guide as well.

**Comment by mdjermanovic** [comment]
> Since we have started merging breaking changes, I think we can move this PR from the blocked state?

Yes, we can continue work by updating the migration guide.

**Comment by Pixel998** [comment]
I've updated the migration guide.

File: docs/src/use/migrate-to-10.0.0.md [hunk 1]
```diff
@@ -286,6 +287,30 @@ The removed `context` properties must be done manually as there may not be a dir
...
+- `getJSDocComment()`
+
+These methods have been deprecated for multiple major versions and were primarily used by deprecated formatting rules and internal ESLint utilities. Custom rules using these methods must be updated to use their modern replacements.
+
+**To address:** In your custom rules, make the following changes:
+
+| **Removed on `SourceCode`**           | **Replacement**                                   |
+| ------------------------------------- | ------------------------------------------------- |
+| `getTokenOrCommentBefore(node)`       | `getTokenBefore(node, { includeComments: true })` |
+| `getTokenOrCommentAfter(node)`        | `getTokenAfter(node, { includeComments: true })`  |
```
Comment (mdjermanovic) [inline docs/src/use/migrate-to-10.0.0.md]:
```suggestion
| `getTokenOrCommentBefore(nodeOrToken, skip)`       | `getTokenBefore(nodeOrToken, { includeComments: true, skip })` |
| `getTokenOrCommentAfter(nodeOrToken, skip)`        | `getTokenAfter(nodeOrToken, { includeComments: true, skip })`  |
```

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
