### PR TITLE
fix: ignore empty switch statements with comments in no-empty rule

### LINKED ISSUE #20000: Rule Change: no-empty rule does not ignore empty switch statements with comments
### What rule do you want to change?

no-empty

### What change do you want to make?

Generate fewer warnings

### How do you think the change should be implemented?

A new default behavior

### Example code

```js
switch (foo) {
  /* empty */
}
```

### What does the rule currently do for this code?

The rule reports an error for the empty switch statement, even though it contains a comment. 

### What will the rule do after it's changed?

After the change, the rule will ignore switch statements that are empty but contain a comment, similar to how it handles other empty blocks.

### Participation

- [x] I am willing to submit a pull request to implement this change.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by jaymarvelz**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

This PR enhances the no-empty rule to no longer report an error for switch statements that are empty but contain a comment. This aligns the behavior for switch statements with how the rule already handles other empty block statements.

- Added a check to detect comments between the braces of an empty switch statement. If comments are present, the rule now exits without reporting an error.
- Previously, the rule highlighted the entire switch statement for being empty. Now, it precisely highlights only the empty block braces ({}), which is consistent with the reporting for other block types.
- Added a suggestion that provides a fix to insert a /* empty */ comment into empty switch statement that triggers the rule.
- Updated the test suite to verify the new behavior and ensure the suggestion works correctly. Also added an example to the rule's documentation to reflect this change.

Fixes #20000

### CODE REVIEW

File: lib/rules/no-empty.js [hunk 1]
```diff
@@ -104,10 +104,47 @@ module.exports = {
...
 						messageId: "unexpected",
 						data: { type: "switch" },
+						suggest: [
+							{
+								messageId: "suggestComment",
+								data: { type: "switch" },
+								fix(fixer) {
+									const range = [
+										openingBrace.range[1],
+										closingBrace.range[1] - 1,
```
Comment (mdjermanovic) [inline lib/rules/no-empty.js]:
```suggestion
										closingBrace.range[0],
```

To simplify a bit.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Leaving open for two more days, per our policies, to give other chance to review.
