### PR TITLE
New: Allow passing a function as `fix` option (fixes #8039)

### LINKED ISSUE #8039: Allow more control over fixes in CLIEngine
I'll talk a little about the use case I'm attempting to solve, and then my proposed solution:

### Problem

Currently, it is not a simple matter to tell ESLint to apply fixes from only one rule, or to disable particular rules from fixes.  Per-rule autofixing is being discussed in https://github.com/eslint/eslint/issues/8018, and @ljharb [mentioned](https://github.com/eslint/eslint/issues/8018#issuecomment-278199831) his use case of fixing one single rule at a time.  In a subsequent chat discussion, I learned that Airbnb also uses inline config to change some rules to `warn` severity, and he would like to avoid applying fixes to those lines.  Currently, there is no built-in way that I know of for ESLint to support this use case.

### Potential Solution

I would like to write a CLI tool (possibly an enhancement to [eslint-nibble](https://github.com/IanVS/eslint-nibble) which would allow users to autofix one single rule at a time, while still respecting the rest of the eslint configuration in their `.eslintrc` file.  Furthermore, I would like to allow an option to _not_ fix messages with a `severity` of `1`. 

Unfortunately, this is not currently possible.  To apply fixes with `CLIEngine`, it's necessary to configure it with `fix: true`.  This adds an `output` field to the results, which `CLIEngine.outputFixes()` applies to the filesystem.  However, the creation of the error messages and output occur together, when calling `CLIEngine.executeOnFiles` or `CLIEngine.executeOnText`.

### Proposal

My proposal is to allow users to modify the messages within `report.results` (for example, to strip out any messages with `severity: 1` or all except a particular rule), before fixes are applied.

I have experimented with adding an `applyFixesToReport` method to `CLIEngine`, which would accept a report object, do a little bit of work to get sourceFile objects using our existing utilities, and then call `SourceCodeFixer.applyFixes()`, returning a new `report` including an `output` string if fixes were applied from the messages in the originally supplied report.

The changes to ESLint are pretty minimal using this approach, and would allow much more flexibility in the fixes that ESLint performs.  I'd be happy to submit a PR if this suggestion is approved.

### PR DESCRIPTION
**Pull request by IanVS**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[X] Add something to the core
[ ] Other, please explain:

Closes #8039 

**What changes did you make? (Give an overview)**
The main change here is to allow the `fix` option of the CLIEngine to be either a boolean or now also a function which is given each linting message and is expected to return a boolean.  This will give users greater control over what kind of fixes are applied by ESLint.

**Is there anything you'd like reviewers to focus on?**
This may be somewhat incomplete.  I worked on it a few months ago, and then put it aside.  I've rebased on latest master and believe the happy path works correctly, but there may need to be more safety added around executing the function that is provided as the `fix` option, as right now all it does is check for truthiness of the return value (which is maybe fine, but is worth some consideration).

I'm happy to continue working on this to get it across the finish line, based on feedback from reviewers.  Or alternatively if anyone wants to jump in and take it over, I'm happy to turn it over as well.

### CODE REVIEW

**Comment by IanVS** [comment]
I've rebased this to account for the recent addition of `linter.verifyAndFix()`.

File: lib/linter.js [hunk 1]
```diff
@@ -1197,10 +1197,11 @@ class Linter extends EventEmitter {
      * @param {string} options.filename The filename from which the text was read.
      * @param {boolean} options.allowInlineConfig Flag indicating if inline comments
      *      should be allowed.
+     * @param {boolean|Function} shouldFix Determines whether fixes should be applied
      * @returns {Object} The result of the fix operation as returned from the
      *      SourceCodeFixer.
      */
-    verifyAndFix(text, config, options) {
+    verifyAndFix(text, config, options, shouldFix) {
```
Comment (not-an-aardvark) [inline lib/linter.js]: Nitpick: Could `fix` be one of the options (third parameter) rather than adding another parameter to this method (e.g. as a `fixFilter` property)? It would be nice to avoid the [boolean trap](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap).

File: tests/lib/util/source-code-fixer.js [hunk 2]
```diff
@@ -162,6 +163,48 @@ describe("SourceCodeFixer", () => {
...
+
+                assert.isFalse(result.fixed);
+            });
+
+            it("should return original text as output if 'shouldFix' function prevents all fixes", () => {
+                const shouldFixSpy = sinon.spy(() => false);
+                const result = SourceCodeFixer.applyFixes(sourceCode, [INSERT_AT_START], shouldFixSpy);
+
+                assert.equal(result.output, TEST_CODE);
+            });
```
Comment (not-an-aardvark) [inline tests/lib/util/source-code-fixer.js]: Can you add a test to assert that the fix filter is called as a pure function (without a `this` value)? I don't want to accidentally expose internal objects because that could make it difficult to change the implementation later if people start to rely on the `this` value.

Comment (not-an-aardvark) [inline tests/lib/util/source-code-fixer.js]: Can you add a test that asserts that only the fixes for which the fix filter returns `true` are applied? All of the filters in the existing tests appear to either always return true or always return false, but as a sanity check  it would be useful to make sure the function works when it only sometimes returns true.

File: lib/util/source-code-fixer.js [hunk 3]
```diff
@@ -88,32 +125,23 @@ SourceCodeFixer.applyFixes = function(sourceCode, messages) {
...
-                remainingMessages.push(problem);
-                continue;
-            }
-
-            // Remove BOM.
-            if ((start < 0 && end >= 0) || (start === 0 && fix.text.startsWith(BOM))) {
-                output = "";
+            if (typeof shouldFix === "function") {
+                if (shouldFix(problem)) {
+                    fixesWereApplied = attemptFix(problem) || fixesWereApplied;
```
Comment (not-an-aardvark) [inline lib/util/source-code-fixer.js]: If I'm understanding correctly, `attemptFix` will only return `false` if the current fix conflicts with another fix that has already been applied. In that case, will `fixesWereApplied` ever be `false` after this line?

File: lib/util/source-code-fixer.js [hunk 4]
```diff
@@ -88,32 +125,23 @@ SourceCodeFixer.applyFixes = function(sourceCode, messages) {
...
-            if (lastPos >= start || start > end) {
-                remainingMessages.push(problem);
-                continue;
-            }
-
-            // Remove BOM.
-            if ((start < 0 && end >= 0) || (start === 0 && fix.text.startsWith(BOM))) {
-                output = "";
+            if (typeof shouldFix === "function") {
+                if (shouldFix(problem)) {
```
Comment (not-an-aardvark) [inline lib/util/source-code-fixer.js]: Nitpick: Maybe this could be simplified to

```js
if (typeof shouldFix !== "function" || shouldFix(problem)) {
    // ...
} else {
    // ...
}
```

to avoid nesting/duplication.

File: lib/util/source-code-fixer.js [hunk 5]
```diff
@@ -70,6 +70,15 @@ SourceCodeFixer.applyFixes = function(sourceCode, messages) {
         };
     }
 
+    if (shouldFix === false) {
+        debug("shouldFix parameter was false, not attempting fixes");
+        return {
+            fixed: false,
+            messages,
+            output: ""
```
Comment (not-an-aardvark) [inline lib/util/source-code-fixer.js]: Should the output here be `sourceCode.text` rather than the empty string, since the resulting text is the same as the original text? (I'm not sure whether the other parts of the code check the `fixed` value before using the output, but setting the output to the original text seems like it would be least surprising in case `fixed` isn't checked.)

File: lib/util/source-code-fixer.js (hunk 3 above)
Comment (IanVS) [inline lib/util/source-code-fixer.js]: Yep, that's a great point.  I can't remember my thinking here, but I think I was trying to be cautious and not build in assumptions about the conditions under which `attemptFix` would return true or false.  But, the diff shows that currently we always return `true` from this block as it is.  I'll be happy to simplify this down, and add a comment about why it is always true.

**Comment by IanVS** [comment]
Thanks for the review and great suggestions, @not-an-aardvark.  I'll make your requested changes within the next few days.

File: lib/util/source-code-fixer.js [hunk 6]
```diff
@@ -88,32 +125,23 @@ SourceCodeFixer.applyFixes = function(sourceCode, messages) {
 
     if (fixes.length) {
         debug("Found fixes to apply");
+        let fixesWereApplied = false;
 
         for (const problem of fixes.sort(compareMessagesByFixRange)) {
-            const fix = problem.fix;
-            const start = fix.range[0];
-            const end = fix.range[1];
+            if (typeof shouldFix !== "function" || shouldFix(problem)) {
```
Comment (IanVS) [inline lib/util/source-code-fixer.js]: Note, we are only checking "truthiness" here.  I think that's okay, but the other option would be to check for an explicit `true` return value.

**Comment by IanVS** [comment]
Thanks again, @not-an-aardvark.  I believe I've addressed your comments.
