### PR TITLE
fix: Emit warning when empty config file is used

### LINKED ISSUE #19044: Bug: CJS config does not complain about no config object (while ESM config does)
### Environment

Local ESLint version: 9.13.0

### What parser are you using?

Default (Espree)

### What did you do?

No `"type"` declared inside `package.json`.

Three _blank_ config files:

- `eslint.config.cjs`
- `eslint.config.js`
- `eslint.config.mjs`

### What did you expect to happen?

ESLint should give the same output no matter which of the three blank config files are used.

### What actually happened?

- `npx eslint -c eslint.config.cjs`: no output
- `npx eslint -c eslint.config.js`: no output
- `npx eslint -c eslint.config.mjs`: the following error message was displayed:
```
Oops! Something went wrong! :(

ESLint: 9.13.0

TypeError: Config (unnamed): Unexpected undefined config at user-defined index 0.
```

### Link to Minimal Reproducible Example

https://github.com/abrahamguo/repro/tree/eslint-no-export

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Ensured consistent behavior when an empty CJS config file is loaded vs. an empty ESM config file. It now no longer throws an error in any situation and instead emits a warning.

fixes #19044

### CODE REVIEW

File: lib/config/config-loader.js [hunk 1]
```diff
@@ -499,11 +499,41 @@ class ConfigLoader {
...
+                    }
+                } else {
+                    if (Object.keys(fileConfig).length === 0) {
+                        debug(`Config file ${configFilePath} is an empty object`);
+                        emptyConfig = true;
+                    } else {
+                        configs.push(fileConfig);
+                    }
+                }
             }
```
Comment (mdjermanovic) [inline lib/config/config-loader.js:531]:
```suggestion
            if (!emptyConfig) {
                if (Array.isArray(fileConfig)) {
                    if (fileConfig.length === 0) {
                        debug(`Config file ${configFilePath} is an empty array`);
                        emptyConfig = true;
                    } else {
                        configs.push(...fileConfig);
                    }
                } else {
                    if (typeof fileConfig === "object" && fileConfig !== null && Object.keys(fileConfig).length === 0) {
                        debug(`Config file ${configFilePath} is an empty object`);
                        emptyConfig = true;
                    } else {
                        configs.push(fileConfig);
                    }
                }
            }
```

**Review by mdjermanovic — COMMENTED** [review]
To keep throwing an error on falsy values like `null` or `0`.

File: lib/config/config-loader.js [hunk 2]
```diff
@@ -499,11 +499,41 @@ class ConfigLoader {
...
+
+            if (emptyConfig) {
+                globalThis.process?.emitWarning?.(`Running ESLint with an empty config (from ${configFilePath}). Please double-check that this is what you want.`, "ESLintEmptyConfigWarning");
```
Comment (mdjermanovic) [inline lib/config/config-loader.js:534]:
```suggestion
                globalThis.process?.emitWarning?.(`Running ESLint with an empty config (from ${configFilePath}). Please double-check that this is what you want. If you want to run ESLint with an empty config, export [{}] to remove this warning.`, "ESLintEmptyConfigWarning");
```

A suggestion on how to remove the warning if empty config is intentional.

**Comment by nzakas** [comment]
Added some tests for `null` and `0` configs.

**Comment by mdjermanovic** [comment]
Several tests are failing now because exporting `undefined` no longer throws an error.

```
1) ESLint
       lintText()
         TypeScript config files
           should fail to load a CommonJS TS config file that exports undefined with a helpful error message:
     AssertionError [ERR_ASSERTION]: Missing expected rejection.
      at async Context.<anonymous> (tests/lib/eslint/eslint.js:1402:21)

  2) ESLint
       lintFiles()
         TypeScript config files
           should fail to load a CommonJS TS config file that exports undefined with a helpful error message:
     AssertionError [ERR_ASSERTION]: Missing expected rejection.
      at async Context.<anonymous> (tests/lib/eslint/eslint.js:5988:21)

  3) ESLint
       lintText()
         TypeScript config files
           should fail to load a CommonJS TS config file that exports undefined with a helpful error message:
     AssertionError [ERR_ASSERTION]: Missing expected rejection.
      at async Context.<anonymous> (tests/lib/eslint/eslint.js:1402:21)

  4) ESLint
       lintFiles()
         TypeScript config files
           should fail to load a CommonJS TS config file that exports undefined with a helpful error message:
     AssertionError [ERR_ASSERTION]: Missing expected rejection.
      at async Context.<anonymous> (tests/lib/eslint/eslint.js:59[88](https://github.com/eslint/eslint/actions/runs/13141435803/job/36669304213#step:5:89):21)
```

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
