### PR TITLE
Fix: `key-spacing` not enforcing no-space in minimum mode

### LINKED ISSUE #5008: The minimum mode of the key-spacing rule has a bug.
**ESLint version:** the master branch (commit 0acbe57602b1297cc1e7a4b04edac8651ed378f9)

In production code, I use the 1.10.3.

**Lint result:**

```shell
cjc:~/www/node/eslint$ ./bin/eslint.js -c .eslintrc.json index.js 

/home/cjc/www/node/eslint/index.js
  1:1  error  Use the global form of 'use strict'  strict

✖ 1 problem (1 error, 0 warnings)
```

**`eslintrc.json`:**

```js
{
  "rules": {
    "key-spacing": [2, { "mode": "minimum", "beforeColon": false, "afterColon": true }]
  }
}
```

**`index.js`:**

```js
(function() {
    var obj = {
        foo : "Foo"
    };

    obj.foo = "Bar";
}());
```

There should not be an extra space before the colon. I mean an error should be output.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30040416-the-minimum-mode-of-the-key-spacing-rule-has-a-bug?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BYK**
Fixes #5008

### CODE REVIEW

File: tests/lib/rules/key-spacing.js [hunk 1]
```diff
@@ -161,7 +160,7 @@ ruleTester.run("key-spacing", rule, {
             mode: "minimum"
         }]
     }, {
-        code: "obj = { key     :      longName };",
+        code: "obj = { key     :longName };",
```
Comment (BYK) [inline tests/lib/rules/key-spacing.js]: Isn't it weird that we had a test to ensure invalid behavior? :D

Comment (btmills) [inline tests/lib/rules/key-spacing.js]: Yeah, that's what threw me off on the issue. I figured given the test there must've been something I was missing.

**Comment by btmills** [comment]
LGTM
