### PR TITLE
Fix: Make outerIIFEBody work correctly (fixes #6585)

### LINKED ISSUE #6585: `indent`: `outerIIFEBody` option not using a multiplier, warning on non-IIFEs?
**What version of ESLint are you using?**
v3.0.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```sh
eslint --rule indent:[2,2,{outerIIFEBody:1}] file.js
```

**What did you do? Please include the actual source code causing the issue.**
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/test/test-base.js
```js
import fs from 'fs';
import path from 'path';
import test from 'tape';

import index from '../';

const files = { index };

fs.readdirSync(path.join(__dirname, '../rules')).forEach(name => {
  files[name] = require(`../rules/${name}`); // eslint-disable-line global-require
});

Object.keys(files).forEach(name => {
  const config = files[name];

  test(`${name}: does not reference react`, t => {
    t.plan(2);

    // scan plugins for react and fail if it is found
    const hasReactPlugin = Object.prototype.hasOwnProperty.call(config, 'plugins') &&
      config.plugins.indexOf('react') !== -1;
    t.notOk(hasReactPlugin, 'there is no react plugin');

    // scan rules for react/ and fail if any exist
    const reactRuleIds = Object.keys(config.rules)
      .filter(ruleId => ruleId.indexOf('react/') === 0);
    t.deepEquals(reactRuleIds, [], 'there are no react/ rules');
  });
});
```

**What did you expect to happen?**
No warnings.

**What actually happened? Please include the actual, raw output from ESLint.**
```sh
$PWD/packages/eslint-config-airbnb-base/test/test-base.js
  10:3  error  Expected indentation of 1 space character but found 2  indent
  14:3  error  Expected indentation of 1 space character but found 2  indent
  16:3  error  Expected indentation of 1 space character but found 2  indent
```

There are two problems here:
1) the warned lines are not actually file-level IIFEs - the file doesn't have an IIFE at all.
2) `outerIIFEBody` is set to 1 - this should be a multiplier of 1 on the indentation config of "2 spaces" - the errors indicate that it wants "1 space" which should **never** be required when the base indent is "2".

### PR DESCRIPTION
**Pull request by nzakas**
This should make the `outerIIFEBody` option work as intended:

1. Make sure the indent is a multiplier, not a set number of spaces.
2. Fix false positive top-level IIFE detection.

### CODE REVIEW

**Comment by ljharb** [comment]
This fixes the original problem I reported, thanks!

File: lib/rules/indent.js [hunk 1]
```diff
@@ -433,8 +438,9 @@ module.exports = {
             // is the outer IIFE and that option is enabled.
             var functionOffset = indentSize;
 
-            if (options.outerIIFEBody !== null && isOuterIIFE(calleeNode.parent)) {
-                functionOffset = options.outerIIFEBody;
+            if (options.outerIIFEBody !== null && isOuterIIFE(calleeNode)) {
+                functionOffset = options.outerIIFEBody * indentSize;
+                console.log(functionOffset);
```
Comment (alberto) [inline lib/rules/indent.js]: This sneaked in.

Comment (nzakas) [inline lib/rules/indent.js]: Doh! Thanks.
