### PR TITLE
Fix: Add a utility to avoid autofix conflicts (fixes #7928, fixes #8026)

### LINKED ISSUE #7928: `no-extra-semi` mistakenly removes necessary semicolon when `semi` is `never`
**Tell us about your environment**

* **ESLint Version:**
3.13.1
* **Node Version:**
6.9.3
* **npm Version:**
4.1.1
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

```yaml
rules:
  semi:
    - error
    - never
  no-extra-semi:
    - error
```

**What did you do? Please include the actual source code causing the issue.**

```js
var foo = function(){};
;[1].map(foo)
```

**What did you expect to happen?**
```js
var foo = function(){}
;[1].map(foo)
```
**What actually happened? Please include the actual, raw output from ESLint.**
```js
var foo = function(){}
[1].map(foo)
```

When `semi` is `never`, `no-extra-semi` is true, and there are whitespaces between two semicolons, those rules will delete both of semicolons. `semi` deletes the first one, and `no-extra-semi` deletes the second one.

### LINKED ISSUE #8026: no-else-return and no-useless-return autofixers cause incorrect code
**Tell us about your environment**

* **ESLint Version:** 3.14.1
* **Node Version:** 6.9.1
* **npm Version:** 3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```
module.exports = {
  rules: {
    "no-else-return": "error",
    "no-useless-return": "error"
  }
};
```

**What did you do? Please include the actual source code causing the issue.**

I ran `eslint --fix` on a file with this code:

```js
function f() {
  if (true) {
    return;
  } else {
    return 1;
  }
}
```

**What did you expect to happen?**

I expected the resulting code to have the same behavior. I don't care which of the two autofixes it applies, but it shouldn't apply both.

**What actually happened? Please include the actual, raw output from ESLint.**

eslint gave no output and changed the code to this:

```js
function f() {
  if (true) {
    
  } 
    return 1;
  
}
```

This code behaves differently because the function now always returns `1` instead of `undefined`.

The real-world case I ran into is that it's causing a test failure after running some automatic conversions, including `eslint --fix`, to convert the autoprefixer project from CoffeeScript to JavaScript: https://github.com/decaffeinate-examples/autoprefixer/blob/decaffeinate/lib/hacks/break-props.js#L51

Looks like this bug was introduced in eslint 3.14.0 when the new no-else-return autofixer was added.

### PR DESCRIPTION
**Pull request by alangpierce**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

See #7928 and #8026 for details.

**What changes did you make? (Give an overview)**

As discussed in #7928, this commit modifies the `no-else-return`,
`no-useless-return`, `semi`, and `no-extra-semi` rules to generate fix commands
with a larger range to avoid conflicting fixes being applied in the same pass. For
the first two, the entire enclosing function is "locked", and for the semicolon rules,
just the surrounding tokens are "locked".

This works using a new internal `FixTracker` class, which is sort of a builder-style
class that allows the rule to specify the range to retain and then supply an
operation, and the class figures out the final text replacement.

In the future, `FixTracker` could also allow multiple replacement operations,
e.g. to make the `no-extra-parens` code a little simpler. It also might be
useful as a public API in the future.

**Is there anything you'd like reviewers to focus on?**

Some minor things:
* Is there another API style that would be preferred rather than the fluent class approach for `FixTracker`?
* Is there a better place for the new tests than `tests/lib/cli-engine.js`? From what I could tell, there weren't really existing tests like this (that test the interaction between different rules after multiple passes).

Also, this is my second PR, so it wouldn't surprise me if I got some style-related things wrong.

### CODE REVIEW

File: lib/rules/no-extra-semi.js [hunk 1]
```diff
@@ -34,7 +40,9 @@ module.exports = {
                 node: nodeOrToken,
                 message: "Unnecessary semicolon.",
                 fix(fixer) {
-                    return fixer.remove(nodeOrToken);
+                    return new FixTracker(fixer, context.getSourceCode())
```
Comment (not-an-aardvark) [inline lib/rules/no-extra-semi.js]: Could you add a comment here with an explanation and/or a link to the relevant issue? Until we implement a more general solution to solving these conflicts, I don't want someone to look at this code and copy it somewhere else with the assumption that it's standard boilerplate for autofixing.

File: lib/testers/rule-tester.js [hunk 2]
```diff
@@ -490,7 +490,19 @@ RuleTester.prototype = {
                 }
 
                 if (item.hasOwnProperty("output")) {
-                    const fixResult = SourceCodeFixer.applyFixes(eslint.getSourceCode(), messages);
+                    let fixResult = SourceCodeFixer.applyFixes(eslint.getSourceCode(), messages);
+
+                    if (item.multipass) {
+                        for (let i = 0; i < 10; i++) {
```
Comment (not-an-aardvark) [inline lib/testers/rule-tester.js]: I feel like it's not ideal to use 10 as a magic number here since the constant could change in [CLIEngine](https://github.com/eslint/eslint/blob/6445d2a55af7e3b797c5f7a187227cf267e0017c/lib/cli-engine.js#L137).

File: lib/testers/rule-tester.js [hunk 3]
```diff
@@ -490,7 +490,19 @@ RuleTester.prototype = {
                 }
 
                 if (item.hasOwnProperty("output")) {
-                    const fixResult = SourceCodeFixer.applyFixes(eslint.getSourceCode(), messages);
+                    let fixResult = SourceCodeFixer.applyFixes(eslint.getSourceCode(), messages);
+
+                    if (item.multipass) {
```
Comment (not-an-aardvark) [inline lib/testers/rule-tester.js]: I'm a bit confused about why it's necessary to add an option here. Could you clarify?

My concern is that this would be a change to core, which I'd rather avoid until we decide on a general solution to conflicting fixes.

Comment (alangpierce) [inline lib/testers/rule-tester.js]: The current behavior of `RuleTester` is that it only allows you to assert the result of the first pass. This broke five tests (the ones where I added the `multipass` option), since those tests all make two fixes in the same function, which now requires the fixes to be done in two passes.

IMO it seems cleanest to have the test runner do what `cli-engine` does and apply fixes until the code gets to a fixed point, not just apply the first pass, so my first attempt was to change `RuleTester` to always do that. That caused two types of issues:

* A number of tests hard-code the parser output (see `tests/fixtures/parsers`). That parser output is only valid for the first pass, so the second pass would end up using an AST that didn't match the code, which caused all sorts of problems.
* About 20-30 other tests failed because there were further fixes to apply after the first  pass. Most of them were in the tests for the `indent` rule, but there were various others. I tried going through and updating all of them, but decided that that would probably make this change too big.

In the end, I decided to leave all of the other tests alone and just enable this new behavior on the tests that needed it.

When you say this would be a change to core, do you mean that `RuleTester` is a public API that might be used externally? I thought it was just an internal test util and I didn't realize there would be hesitation with changing it.

I could always just get rid of this change and change those five tests to only assert the result of the first pass (which would have one of the fixes but not the other). I was hoping there would still be a way to assert the final result if you actually ran the code through eslint, but I'm certainly fine holding off on that if you are.

File: lib/testers/rule-tester.js (hunk 2 above)
Comment (alangpierce) [inline lib/testers/rule-tester.js]: Makes sense. Really, seems like it would be cleanest if this code could actually call `multipassFix`, but seemed like that would probably be hard (although looking at it now, maybe not).

If we decide to keep this part, I can use a shared constant, I guess on `CLIEngine`.

File: lib/testers/rule-tester.js (hunk 3 above)
Comment (not-an-aardvark) [inline lib/testers/rule-tester.js]: > When you say this would be a change to core, do you mean that RuleTester is a public API that might be used externally? I thought it was just an internal test util and I didn't realize there would be hesitation with changing it.

Yes, `RuleTester` is exported as a property of the `eslint` object so that plugin authors can use it to test custom rules.

I think the best solution is probably to change the five tests to only assert the result of the first pass. (I agree that there is probably room for improvement in the `RuleTester` API as far as multipass is concerned -- I just think that should be a separate issue from this bugfix so that it can be discussed thoroughly.

Comment (alangpierce) [inline lib/testers/rule-tester.js]: Ok, sounds good, I'll do that.

File: lib/testers/rule-tester.js [hunk 4]
```diff
@@ -490,7 +490,19 @@ RuleTester.prototype = {
...
+                        for (let i = 0; i < 10; i++) {
+                            const newItem = Object.assign({}, item, { code: fixResult.output });
+                            const newResult = runRuleForItem(ruleName, newItem);
+
+                            fixResult = SourceCodeFixer.applyFixes(eslint.getSourceCode(), newResult.messages);
+                            if (newItem.code === fixResult.output) {
+                                break;
```
Comment (alangpierce) [inline lib/testers/rule-tester.js]: If we don't break here, we'd be running the rule again on exactly the same code as in the previous iteration, so it should again get no fixes assuming the rules are deterministic. So I feel like there isn't really a use case for continuing, but I might be overlooking something.

(Another thought I had was to fail the test after a certain number of iterations, since I feel like it indicates a bug in a rule if it doesn't reach a stable point after some number of fixes.)

File: lib/util/fix-tracker.js [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+//------------------------------------------------------------------------------
+// Public Interface
+//------------------------------------------------------------------------------
+
+/**
+ * A helper class to combine fix options into a fix command. Currently, it
+ * exposes some "retain" methods that extend the range of the text being
+ * replaced so that other fixes won't touch that region in the same pass.
+ */
+class FixTracker {
```
Comment (alangpierce) [inline lib/util/fix-tracker.js]: Yep, agreed that putting this stuff on `ruleFixer` would be cleaner (assuming `ruleFixer` can be changed to be aware of the source code), except for the fact that it's a public API, so we need to be careful about changing it.

File: lib/util/fix-tracker.js [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+    /**
+     * Create a fix command that replaces the given range with the given text,
+     * accounting for any retained ranges.
+     *
+     * @param {int[]} range The range to remove in the fix.
+     * @param {string} text The text to insert in place of the range.
+     * @returns {Object} The fix command.
+     */
+    replaceTextRange(range, text) {
+        const actualRetainedRange = this.retainedRange || range;
```
Comment (alangpierce) [inline lib/util/fix-tracker.js]: You're right, I was a little sloppy here. Your code example also doesn't handle the case where `retainedRange` isn't set. I'll fix, and I think a quick test should be easy as well.

File: lib/rules/no-extra-semi.js (hunk 1 above)
Comment (alangpierce) [inline lib/rules/no-extra-semi.js]: Ok, I'll put a short comment in all four spots.

**Comment by alangpierce** [comment]
Thanks for the review, I just updated the code to address the comments you mentioned.

Agreed that the `FixTracker` class is maybe more than it needs to be for this commit. Doing the range logic, error handling, and string manipulation in the individual rules was a bit messy and had some duplication, so it seemed nice to abstract it away, and the class approach seemed more flexible and readable than helper functions. Hopefully it also explores how we might have a public API for this sort of thing, and shows that it generally wouldn't complicate the implementation of rules (even if it would require more thought/care on the part of the rule author).

**Comment by not-an-aardvark** [comment]
I took the liberty of updating the initial PR description to clarify that this change no longer adds anything to `RuleTester`.

File: lib/rules/no-else-return.js [hunk 7]
```diff
@@ -86,7 +92,13 @@ module.exports = {
...
                         fixedSource = source;
                     }
-                    return fixer.replaceTextRange([elseToken.start, node.end], fixedSource);
+
+                    // Extend the replacement range to include the entire
+                    // function to avoid conflicting with no-useless-return.
+                    // https://github.com/eslint/eslint/issues/8026
+                    return new FixTracker(fixer, sourceCode)
+                        .retainEnclosingFunction(node)
+                        .replaceTextRange([elseToken.start, node.end], fixedSource);
```
Comment (mysticatea) [inline lib/rules/no-else-return.js]: Shouldn't those `FixTracker` methods merge to `fixer`?

Comment (not-an-aardvark) [inline lib/rules/no-else-return.js]: @mysticatea Since this fix might be a temporary workaround until #7928 is solved in a better way, we're trying to avoid making changes to core in this fix. So it adds `FixTracker` as an internal helper class, but it doesn't change the `ruleFixer` API because we're not sure how we'll want to change that in the future.

Comment (mysticatea) [inline lib/rules/no-else-return.js]: I got it. Thank you!

**Comment by mysticatea** [comment]
I have been investigating about multiple fixes per a report. 
I think It might get similar to this PR.

https://github.com/eslint/eslint/tree/multiple-fixes-per-report

In `semi` rule case: https://github.com/eslint/eslint/commit/adb8415a9852f709687a78df6d11958c06e24f2f
It supports multiple fixes per a report, then the rule context merges those fixes to one.

Thought?

**Comment by alangpierce** [comment]
@mysticatea Cool, that API makes sense. I don't know if I have a strong preference between a generator and a builder (which is basically what `FixTracker` is). I guess maybe one advantage of a builder is that it makes it more natural to specify options, whereas yielding an option is a little awkward IMO. For example, maybe a rule could do `fixTracker.runInIsolation()`. There's already a way to specify preferences, though, so I'm not too tied to that idea.

My vision for `FixTracker` in this PR was something like this progression of steps:

1.) In this PR, `FixTracker` is introduced as an internal API to fix the correctness issues with rule conflicts without needing an API change.

2.) We add support for multiple fixes when using `FixTracker`. For example, you might do this:
```
  return new FixTracker(fixer, sourceCode)
    .remove(openParenToken)
    .remove(closeParenToken)
    .build();
```

That's just a shorthand for doing one large fix that replaces that code range with the code without the tokens. This is an API break for `FixTracker`, and the other rules would need to be updated, but that's fine, since it's a private API.

3.) We iterate on the details of that API until we're happy with it (including strategies like `yield` instead of a builder), and move rules over that could benefit from it.

4.) We integrate `FixTracker` into `ruleFixer` so that it's ideally an additive change to the public API, and migrating built-in rules to that new public API would be easy.

5.) With the API semantics set, we experiment with different implementation strategies to see if there are good ways to improve performance. For example, this is when we'd decide whether to apply `remove(openParenToken)` and `remove(closeParenToken)` as separate changes to avoid conflicts (and thus run additional fixes in the same pass for perf reasons), or if the real-world perf improvement isn't enough to justify the added complexity.

To be clear, `FixTracker` is just one idea, and I think it makes plenty of sense to iterate on it or rethink it entirely. From a practical perspective, though, I do think it would be nice to fix #7928 and #8026 pretty soon. #8026 is causing test failures in a project I'm working on (https://github.com/decaffeinate/decaffeinate/issues/822).

**Comment by not-an-aardvark** [comment]
It looks like there's consensus that this is a good idea (and we can always change it later on, since it's not exposed anywhere). I'll plan to merge this in the next day or so unless anyone else requests changes.

**Comment by not-an-aardvark** [comment]
Thanks for contributing!
