### PR TITLE
Fix: do not autofix octal escape sequence (fixes #10031)

### LINKED ISSUE #10031: prefer-template autofixer should not convert a string to a template if it contains an octal escape sequence
**Tell us about your environment**

* **ESLint Version:** 4.18.1
* **Node Version:** 9.6.1
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
rules:
  prefer-template: error
parserOptions:
  ecmaVersion: 6
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
'\033' + foo
```

```bash
eslint theFile.js --fix
```

**What did you expect to happen?**

I expected no autofix to happen, because the string `'\033'` contains an octal escape sequence, which is a syntax error when it appears in a template literal.

**What actually happened? Please include the actual, raw output from ESLint.**

The problem was automatically fixed, resulting in a syntax error.

```
1:2  error  Parsing error: Octal literal in strict mode
```

(Note: the error message is a bit misleading; this is a parsing error because the resulting string is a template literal, not because it's in strict mode.)

### PR DESCRIPTION
**Pull request by malcolmsgroves**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

https://github.com/eslint/eslint/issues/10031

**What changes did you make? (Give an overview)**
Added a check for octal escape sequences in binary expressions. The```prefer-template``` rule does not attempt to fix binary expressions that contain octal escape sequences, and returns a ```null``` fixer object if this is the case.

Also added a test that ensures that binary expressions with octal escape sequences are not auto fixed.

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by malcolmsgroves** [comment]
@platinumazure could you take a look at this when you have a moment? Thanks!

File: lib/rules/prefer-template.js [hunk 1]
```diff
@@ -38,6 +38,45 @@ function getTopConcatBinaryExpression(node) {
...
+function isOctalEscapeSequence(node) {
+
+    // No need to check TemplateLiterals – would throw error with octal escape
+    const isStringLiteral = node.type === "Literal" && typeof node.value === "string";
+
+    if (!isStringLiteral) {
+        return false;
+    }
+
+    const match = node.raw.match(/^([^\\]|\\[^0-7])*\\([0-3][0-7]{1,2}|[4-7][0-7]|[0-7])/);
```
Comment (not-an-aardvark) [inline lib/rules/prefer-template.js]: I think the second part of this regular expression could be simplified from this:

```
([0-3][0-7]{1,2}|[4-7][0-7]|[0-7])
```

to this:

```
([0-7]{1,3})
```

...since it seems like the `[0-7]` character class will always match something even if the other cases don't.

File: tests/lib/rules/prefer-template.js [hunk 2]
```diff
@@ -187,6 +187,11 @@ ruleTester.run("prefer-template", rule, {
             code: "foo + 'handles unicode escapes correctly: \\x27'", // "\x27" === "'"
             output: "`${foo  }handles unicode escapes correctly: \\x27`",
             errors
+        },
+        {
+            code: "foo + 'does not autofix octal escape sequence' + '\\033'",
+            output: null,
+            errors
```
Comment (not-an-aardvark) [inline tests/lib/rules/prefer-template.js]: The regular expression you're using is fairly complicated. It seems correct as far as I can tell, but there are a lot of non-obvious cases, so I want to make sure we don't accidentally break those cases if we change the logic in the future. Can you add some tests for cases like the following?

* The string contains an unrelated escape before the octal escape: `` `\n other text \033` + foo ``
* The string contains a `\0` escape followed by an octal escape: `` `\0 other text \033` `` (I'm not sure this case is handled correctly right now)
* The string contains an escaped backslash: `` `\\033` + foo `` (this should get autofixed because there is not actually an octal escape).

**Comment by malcolmsgroves** [comment]
Thanks for the comments! I should be able to make the changes after the weekend

**Comment by malcolmsgroves** [comment]
@not-an-aardvark I added those tests and cleaned that regex up. You were right – it was mishandling ```\0``` null escape sequences, but should be good now. 

@platinumazure do you think I could work up a PR to move the octal matching to ast-utils?

**Comment by platinumazure** [comment]
@malcolmsgroves

> do you think I could work up a PR to move the octal matching to ast-utils?

Absolutely; certainly no need to do it in this PR. Might be good to see if other ESLint core rules could use it as well. Thanks!

**Comment by not-an-aardvark** [comment]
Thanks for continuing to work on this. Can you add a test for the '\0 other text \033' case (where an octal escape follows a `\0` escape)? From quickly glancing at the code it's not clear to me that this is fixed, since it seems like `isOctalEscapeSequence` simply returns false whenever `\0` appears in the string.

**Comment by malcolmsgroves** [comment]
@not-an-aardvark done, sorry I forgot to include the tests in the original changes. ```isOctalEscapeSequence``` seems to work fine

File: tests/lib/rules/prefer-template.js [hunk 3]
```diff
@@ -34,7 +34,8 @@ ruleTester.run("prefer-template", rule, {
 
         // https://github.com/eslint/eslint/issues/3507
         "var foo = `foo` + `bar` + \"hoge\";",
-        "var foo = `foo` +\n    `bar` +\n    \"hoge\";"
+        "var foo = `foo` +\n    `bar` +\n    \"hoge\";",
+        "var foo = `foo` + `\\0`;"
```
Comment (not-an-aardvark) [inline tests/lib/rules/prefer-template.js]: I think these "valid" tests aren't working correctly -- the strings in these tests are already template literals, so the rule isn't reporting them because there would be nothing to adjust anyway.

From testing out this branch locally, I think the string `\0` is still preventing an autofix.

**Comment by malcolmsgroves** [comment]
@not-an-aardvark should be good now, I changed the regex a bit and fixed those tests – string literals that only contain ```\0``` are now auto fixed
