### PR TITLE
Fix: refactor eslint-disable comment processing (fixes #9215)

### LINKED ISSUE #9215: Rule-specific eslint-enable comments don't work after global eslint-disable comments
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 8.4.0
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```yml
rules:
    semi: error
```

**What did you do? Please include the actual source code causing the issue.**

```js
/* eslint-disable */
/* eslint-enable semi */

foo
```

**What did you expect to happen?**

I expected a `semi` error to be reported on line 4, because the `semi` rule was reenabled on line 2.

**What actually happened? Please include the actual, raw output from ESLint.**

No error was reported.

I found this issue while refactoring the `eslint-disable` logic. I have a fix in progress.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/9215)

**What changes did you make? (Give an overview)**

This extracts the processing logic for `eslint-disable` comment processing into a different module file, rather than storing state on `Linter` throughout the comment traversal. This fixes bugs such as https://github.com/eslint/eslint/issues/9215, and adds a bunch of tests for edge cases to avoid issues like https://github.com/eslint/eslint/pull/9195 in the future.

This also improves the asymptotic complexity of disable comment checking logic -- it was previously `O(#problems * #disable comments)`, and now it's `O(#problems + #disable comments * log(#disable comments))`. In most cases this probably won't be noticeable because most files don't have very many disable comments.

edit: This also fixes https://github.com/eslint/eslint/issues/6592. I had forgotten that issue existed, but it seems like my resulting design is pretty similar to what was proposed there.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: tests/lib/linter.js [hunk 1]
```diff
@@ -1664,7 +1664,7 @@ describe("Linter", () => {
             assert.equal(messages[1].column, 19);
         });
 
-        it("should not report a violation", () => {
+        it("should report a violation", () => {
```
Comment (gyandeeps) [inline tests/lib/linter.js]: These unit test changes makes me little uncomfortable.... Ideally refactor should not change unit test...
I am questioning to better understand the intent...

**Comment by gyandeeps** [comment]
I like the overall intent of this change... we should try to breakdown cli-engine also..
thanks @not-an-aardvark for dng this n other changes...

File: tests/lib/linter.js (hunk 1 above)
Comment (not-an-aardvark) [reply tests/lib/linter.js]: I agree that in general, refactors shouldn't change unit tests.

However, I think these tests were asserting incorrect behavior. The first test was asserting that no error should be reported in cases like this:

```js
/* eslint no-alert: error */
/* eslint-disable */
/* eslint-disable */

/* eslint-enable */

alert('foo');
```

I don't think this makes sense because `eslint-enable` is supposed to enable all disabled rules, regardless of how the rules were disabled previously.

The second test was asserting that no error should be reported in cases like this:

```js
/* eslint no-alert: error */

/* eslint-disable no-alert */

/* eslint-disable no-console */

/* eslint-enable */

alert('foo');
```

I don't think this makes sense because `/* eslint-enable */` is supposed to enable all disabled rules, regardless of how many rules have been disabled before. (Previously, the user would need to use a second `/* eslint-enable */` comment to enable `no-alert` again.)

**Comment by platinumazure** [comment]
Thanks for knocking this out, @not-an-aardvark!
