### PR TITLE
Fix: Add space between async and param on fix (fixes #8682)

### LINKED ISSUE #8682: arrow-parens ("as-needed") doesn't take async into account
**Tell us about your environment**

* **ESLint Version:** 3.19.0 (with the latest babel-eslint)
* **Node Version:** 7.9.0
* **npm Version:** 4.2.0

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint (as eslint doesn't support async

**Please show your full configuration:**

final test with the following, still breaks:
```
{
  "root": true,
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 7,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true,
      "impliedStrict": true,
      "experimentalObjectRestSpread": true
    }
  },
  "env": {
    "browser": true,
    "mocha": true,
    "node": true,
    "es6": true
  },
  "globals": {
    "describe": false,
    "it": false
  },
  "rules": {
    "arrow-parens": [
      2,
      "as-needed"
    ]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
const foo = async(bar) => {
//...
}

```

**What did you expect to happen?**
fix to 
```js
const foo = async bar => {
//...
}```
(or just skip the line, would be fine too)

**What actually happened? Please include the actual, raw output from ESLint.**
```js
const foo = asyncbar => {
//...
}
```

as the async was no longer `async` (but `asyncbar`), causing the function to no longer be an async function
```
/path/to/foo.js
  24:25  error  Parsing error: await is a reserved word
```

### PR DESCRIPTION
**Pull request by soda0289**
**What is the purpose of this pull request? (put an "X" next to item)**
[ X ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

**What changes did you make? (Give an overview)**
Update the fixer code to add space between async and the arrow function parameter when they are side by side.

**Is there anything you'd like reviewers to focus on?**
Nothing in particular

### CODE REVIEW

File: lib/rules/arrow-parens.js [hunk 1]
```diff
@@ -51,13 +51,32 @@ module.exports = {
...
+
         /**
          * Determines whether a arrow function argument end with `)`
          * @param {ASTNode} node The arrow function node.
          * @returns {void}
          */
         function parens(node) {
-            const token = sourceCode.getFirstToken(node, node.async ? 1 : 0);
+            const isAsync = node.async;
+            const token = sourceCode.getFirstToken(node, isAsync ? 1 : 0);
```
Comment (not-an-aardvark) [inline lib/rules/arrow-parens.js]: I know this was here before, but can you give this variable a more descriptive name? It's not clear which token it's referring to.

File: lib/rules/arrow-parens.js [hunk 2]
```diff
@@ -51,13 +51,32 @@ module.exports = {
...
+
+            /**
+             * Remove the parenthesis around a parameter
+             * @param {Fixer} fixer Fixer
+             * @returns {string} fixed parameter
+             */
+            function fixParamsWithParenthesis(fixer) {
+                const paramToken = context.getTokenAfter(token);
+                const closingParenToken = context.getTokenAfter(paramToken);
+                const asyncToken = isAsync ? context.getTokenBefore(token) : null;
```
Comment (not-an-aardvark) [inline lib/rules/arrow-parens.js]: Can you use `sourceCode.getTokenBefore` and `sourceCode.getTokenAfter` instead of `context.getTokenBefore` and `context.getTokenAfter`? The latter two are deprecated.

**Comment by soda0289** [comment]
Changes:
- changed the `token` variable to `firstTokenOfParam`, which might be a opening paren or identifier.
- used source.getToken functions instead of context.getToken
- Removed extra blank lines

**Comment by kaicataldo** [comment]
Thanks for contributing!
