### PR TITLE
Fix: avoid exponential require-atomic-updates traversal (fixes #10893)

### LINKED ISSUE #10893: require-atomic-updates takes a very long time to run on large files
**Tell us about your environment**

* **ESLint Version:** 5.6 (though issue starts at 5.3)
* **Node Version:** 10.3.0
* **npm Version:** 6.1.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "extends": "@spothero",
    "settings": {
        "react": {
            "version": "latest"
        }
    },
    "rules": {
        "require-atomic-updates": 2
    }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import includes from 'lodash/includes';
import moment from 'moment';
import APIUtils from '@spothero/utils/api';
import StorageUtils from '@spothero/utils/storage';
import Config from 'config';
import UserUtils from 'user/user-utils';
import SearchTracking from 'utils/search-tracking';
import SegmentUtils from 'utils/segment';

const ReservationAPI = {
    async add({
        checkoutData,
        selectedRate,
        monthlyStarts = null,
        facility,
        onError,
        stripeToken = false,
        stripePaymentType = 'cc',
        setNewCardAsDefault = false,
        onSuccess = null,
        includeVehicleInResponse = false,
        includeFacilityInResponse = false,
        source = null,
        rentalSourceReferrer = null,
        checkoutStartTime = null
    }) {
        const {
            user,
            promoCode,
            isMonthly,
            eventId,
            paymentRequired,
            purchaseForCustomer,
            purchaseForCustomerReferralSource,
            purchaseForCustomerDescription,
            purchaseOnBehalfOfCustomer,
            affiliate,
            phoneNumberRequired,
            selectedCreditCard,
            licensePlateRequired,
            selectedLicensePlate,
            licensePlateState,
            newLicensePlate,
            newLicensePlateName,
            newLicensePlateIsDefault,
            referralSource,
            smsParkingPass,
            forceRedundantMonthly,
            vehicleMake,
            vehicleModel,
            vehicleYear,
            vehicleColor,
            saveVehicleAsDefault,
            acceptedTerms,
            contractFullName
        } = checkoutData;
        const ratePrice = (selectedRate.price / 100);
        const phoneNumberCleaned = (user.phoneNumber) ? user.phoneNumber.replace(/\D/g, '') : null;
        const isUserSavingNewCard = (user.status === UserUtils.AUTH_STATE.USER && selectedCreditCard === 'new' && !purchaseForCustomer && paymentRequired);
        const isMonthlyRecurringNewCard = (selectedCreditCard === 'new' && isMonthly && selectedRate.recurrable);
        const isPaymentRequired = (selectedCreditCard === 'admin') ? false : paymentRequired;
        const {
            searchUUID,
            actionUUID
        } = SearchTracking.getValues();
        const postData = {
            email: user.email,
            price: parseInt(Math.round(Number(ratePrice) * 100), 10),
            facility: facility.parking_spot_id,
            apply_sh_credit: (user.status === UserUtils.AUTH_STATE.USER),
            search_id: searchUUID,
            action_id: actionUUID
        };
        const config = {};
        const shExperimentVariations = StorageUtils.get('sh-experiment-variations', 'cookie');

        if (includeFacilityInResponse) {
            postData.include = 'facility';
        }

        if (includeVehicleInResponse) {
            if (postData.include) {
                postData.include += ',vehicle_info';
            } else {
                postData.include = 'vehicle_info';
            }
        }

        if (isMonthly) {
            postData.monthly_start_date = moment(monthlyStarts).format(Config.apiDateFormat);
            postData.rule = selectedRate.fullRule;
        } else {
            postData.starts = selectedRate.starts;
            postData.ends = selectedRate.ends;
            postData.rule_group_id = selectedRate.rule_group_id;
        }

        if (eventId) {
            postData.event = eventId;
        }

        if (user.phoneNumber && !phoneNumberCleaned) {
            postData.phone_number = user.phoneNumber;
        } else {
            if (phoneNumberCleaned) {
                postData.phone_number = phoneNumberCleaned;
            }
        }
    },
};

export default ReservationAPI;
```

```bash
eslint test.js
```

**What did you expect to happen?**
ESLint runs quickly on that file and shows all errors.

**What actually happened? Please include the actual, raw output from ESLint.**
The expected behavior happened, however it took WAY longer than it should have on this file. The file is contrived, its just a part of a file in our codebase where I started to see issues when I started to drill down into this.  We just upgraded from ESLint 5.2 to 5.6 on a large codebase and ESLint was stalling. We use our own config (https://github.com/spothero/eslint-config) so I naturally thought it was something I had messed up in the config.

I then created a repo that just had the `test.js` file and the above `.eslintrc` file. Through editing various things, I was finally able to realize that the `require-atomic-updates` rule was the culprit. If you disable it in the config with `0`, the file executes quickly. If you enable it, the file takes MUCH longer to execute. This becomes magnified when you have many files in the codebase and ESLint just seems to hang without ever finishing them and moving on to the next build step.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix (https://github.com/eslint/eslint/issues/10893)
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Previously, the `require-atomic-updates` rule would traverse over every path in the control flow graph, resulting in a runtime that was exponential in the number of edges in the graph. This commit updates the rule to use a lattice-based [dataflow analysis](https://en.wikipedia.org/wiki/Data-flow_analysis) algorithm, similar to the algorithms used by optimizing compilers.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: tests/lib/rules/require-atomic-updates.js [hunk 1]
```diff
@@ -68,7 +129,7 @@ ruleTester.run("require-atomic-updates", rule, {
             errors: [VARIABLE_ERROR]
         },
         {
-            code: "let foo; async function x() { foo = foo + (bar ? baz : await amount); }",
+            code: "let foo; async function x() { foo = foo + (barrr ? baz : await amount); }",
```
Comment (platinumazure) [inline tests/lib/rules/require-atomic-updates.js]: Not sure I understand the purpose of this change.

Comment (not-an-aardvark) [reply tests/lib/rules/require-atomic-updates.js]: Oops, this was accidental --- I temporarily changed it in order to be able to grep for a single test, but then I forgot to change it back.
