### PR TITLE
Fix: space-unary-ops flags expressions starting w/ keyword (fixes #2764)

### LINKED ISSUE #2764: "this" is an "Unary word operator" since 0.23.0
Got this error updating to 0.23.0:

```
Unary word operator "this" must be followed by whitespace  space-unary-ops
```

for this line:
```js
this.indents--;
```

Guessing it's related to #2696.

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #2764.

### CODE REVIEW

File: lib/rules/space-unary-ops.js [hunk 1]
```diff
@@ -65,7 +65,7 @@ module.exports = function(context) {
             firstToken = tokens[0],
             secondToken = tokens[1];
 
-        if (firstToken.type === "Keyword") {
+        if ((node.type === "NewExpression" || node.prefix) && firstToken.type === "Keyword") {
```
Comment (ilyavolodin) [inline lib/rules/space-unary-ops.js]: Can you add some tests for NewExpression as well?

Comment (michaelficarra) [inline lib/rules/space-unary-ops.js]: There's no tests to add. NewExpression already has tests.

**Comment by nzakas** [comment]
Lgtm
