### PR TITLE
Fix: Check comments in space-in-parens (fixes #4302)

### LINKED ISSUE #4302: [Regression] space-in-parens ignores comments again
The following code:
```js
function f(/* config */ config, /* config.proxies */ proxies) {
  return [config, proxies];
}
f();
```
now (in ESLint 1.8.0) fails if `space-in-parens` is enabled with a message: "There should be no spaces inside this paren"; it didn't in 1.7.3.

I'd expect it to not ignore the leading comment and treat it as not having a space directly after a paren (since there's no space there).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27838338-regression-space-in-parens-ignores-comments-again?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

File: lib/rules/space-in-parens.js [hunk 1]
```diff
@@ -184,9 +188,13 @@ module.exports = function(context) {
 
     return {
         "Program": function checkParenSpaces(node) {
-            var tokens = node.tokens;
-            var prevToken, nextToken;
+            var tokens, prevToken, nextToken;
             exceptions = getExceptions();
+            var comments = sourceCode.getAllComments();
```
Comment (nzakas) [inline lib/rules/space-in-parens.js]: This is some pretty heavy logic to be doing in a rule. I'd suggest adding this to `SourceCode`. Maybe a tokensAndComments property?

Comment (nzakas) [inline lib/rules/space-in-parens.js]: Oops, should be for line 195.

Comment (alberto) [inline lib/rules/space-in-parens.js]: Ok, I will move it there.

File: lib/util/source-code.js [hunk 2]
```diff
@@ -163,6 +163,16 @@ SourceCode.prototype = {
     },
 
     /**
+     * Retrieves an array containing all tokens and comments in the source code sorted by range.
+     * @returns {ASTNode[]} An array of tokens and comments sorted by range start.
+     */
+    getAllTokensAndComments: function() {
```
Comment (nzakas) [inline lib/util/source-code.js]: It's better to do this once and store on SourceCode. It's never going to change.

Comment (alberto) [inline lib/util/source-code.js]: Updated

File: lib/rules/space-in-parens.js [hunk 3]
```diff
@@ -184,9 +188,9 @@ module.exports = function(context) {
 
     return {
         "Program": function checkParenSpaces(node) {
-            var tokens = node.tokens;
-            var prevToken, nextToken;
+            var tokens, prevToken, nextToken;
             exceptions = getExceptions();
+            tokens = sourceCode.tokensAndComments;
```
Comment (gyandeeps) [inline lib/rules/space-in-parens.js]: Personally I prefer having functions for such things since this is exposed also.
Thoughts?

Comment (nzakas) [inline lib/rules/space-in-parens.js]: Functions are more expensive performance-wise, and we are only calculating this once, so I think property makes sense.

Comment (gyandeeps) [inline lib/rules/space-in-parens.js]: What meant was, it would still be calculated once but just to get the data wewill have a function like getTokenComment or something.

Comment (nzakas) [inline lib/rules/space-in-parens.js]: Yup, my point is that introduces overhead that is unnecessary because the value never changes. It's a lot less expensive to access a property than to call a function.

Comment (alberto) [inline lib/rules/space-in-parens.js]: @nzakas Unless I am missing something, you are talking about the extra cost of the function call, right? And that would only be paid when such function is called (right now, when this rule is enabled).

On the other hand, making it a property makes that code be executed every time `SourceCode` is instantiated. I guess that cost will be much higher compared to a function call.

Comment (nzakas) [inline lib/rules/space-in-parens.js]: Yes. However, as you mentioned in the issue, this change likely needs to be made in a bunch of rules, and in that case we want the array cached and directly accessible without a function call (which would be additional overhead on top of the property access. 

So we pay the cost up front, store the result, and basically get it for free every other time is used vs. calling a function that always had a cost.

Comment (alberto) [inline lib/rules/space-in-parens.js]: I'm not sure the other rules will be able to use this same method since they check for specific node types.

Comment (nzakas) [inline lib/rules/space-in-parens.js]: In any event, I think this is a good approach. If it ends up being suboptimal, I'm to blame. :)
