### PR TITLE
Fix: should not convert non-consecutive line comments to a single blo…

### LINKED ISSUE #9462: Proposal: Add option to make multiline-comment-style not coalesce non-consecutive single line comments
**Tell us about your environment**

* **ESLint Version:** 4.9.0
* **Node Version:** 8.6.0
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaVersion": 8,
        "sourceType": "script",
        "ecmaFeatures": {}
    },
    "rules": {
        "multiline-comment-style": 2
    },
    "env": {}
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
//someCommentedOutLineOfCode();

// Useful documentation about the next line
```

**What did you expect to happen?**
I expected fixing `multiline-comment-style` to leave two separate single-line comments.

**What actually happened? Please include the actual, raw output from ESLint.**
The fixer combines the two comments into:
```javascript
/*
 *someCommentedOutLineOfCode();
 *Useful documentation about the next line
 */
```

I believe it would be useful to have an option to have the rule not flag/fix single line comments with an empty line in between them. It seems like the intent behind the rule is to combine "block" comments composed of single line comments into a single real block comment, and I think that this option would more accurately reflect that desire.

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
…ck comment(fixes #9462)

**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by Aladdin-ADD** [comment]
I need to add some more tests. add "do not merge" label.

File: lib/rules/multiline-comment-style.js [hunk 1]
```diff
@@ -272,6 +272,7 @@ module.exports = {
                         if (
                             comment.type === "Line" &&
                             index && commentList[index - 1].type === "Line" &&
+                            sourceCode.getTokenBefore(comment, { includeComments: true }).loc.end.line === comment.loc.start.line - 1 &&
```
Comment (kaicataldo) [inline lib/rules/multiline-comment-style.js]: Suggestion: Maybe assign `sourceCode.getTokenBefore(comment, { includeComments: true })` to a variable that can be reused since this token is used for two checks in this conditional?

Comment (Aladdin-ADD) [reply lib/rules/multiline-comment-style.js]: sounds good!

Comment (kaicataldo) [reply lib/rules/multiline-comment-style.js]: Also, this won't ever be `undefined` because of [this line](https://github.com/eslint/eslint/pull/9475/files#diff-e8cce2004dd5e0386021b0e80370c8ebR269), correct?

Comment (Aladdin-ADD) [reply lib/rules/multiline-comment-style.js]: hmm.. I'm afraid I don't think so -- `tokenBefore` being null, returning `!tokenBefore` can be true.

Comment (kaicataldo) [reply lib/rules/multiline-comment-style.js]: Ah, right - just to be sure, can we either do:

```js
const tokenBefore = sourceCode.getTokenBefore(comment, { includeComments: true });

if (
  ...
  tokenBefore && tokenBefore.loc.end.line === comment.loc.start.line - 1 &&
  ...
)
```
Or right a test that tests that ensure this doesn't throw? It might not ever be `null` or `undefined`, in which case we're fine!

Comment (Aladdin-ADD) [reply lib/rules/multiline-comment-style.js]: >but prev line can make sure: index && ... index>0 means at least one comment.
all right. it's a little tricky, no harm to add this check.

File: tests/lib/rules/multiline-comment-style.js [hunk 2]
```diff
@@ -153,6 +153,30 @@ ruleTester.run("multiline-comment-style", rule, {
...
+        {
+            code: `
+                // a comment
+
+                // another comment
+            `,
+            options: ["starred-block"]
+        },
+        {
+            code: `
```
Comment (not-an-aardvark) [inline tests/lib/rules/multiline-comment-style.js]: Can you add a test for converting two separate line groups?

```js
/* eslint multiline-comment-style: [error, starred-block] */

// foo
// bar

// baz
// qux
```

should get fixed to:

```js
/*
 * foo
 * bar
 */

/*
 * baz
 * qux
 */
```
