### PR TITLE
Fix: Ensure piped in code will trigger correct errors (fixes #2154)

### LINKED ISSUE #2154: Bug: invalid config errors swallowed when using --stdin
See the output below.

When using `--stdin` and an invalid config file, the process exits silently with an exit code of 0.

```
~/Development/TechTests/my-react-frontend (immutable) gma08
> cat server.js | eslint --stdin

~/Development/TechTests/my-react-frontend (immutable) gma08
> eslint server.js

/usr/local/lib/node_modules/eslint/lib/config.js:59
            throw e;
                  ^
YAMLException: Cannot read config file: /Users/gma08/Development/TechTests/my-react-frontend/.eslintrc
Error: JS-YAML: missed comma between flow collection entries at line 11, column 17:
            "quotes": false,
                    ^
```

### PR DESCRIPTION
**Pull request by nzakas**
This is a bit gross. `bin/eslint.js` is the one file we don't have unit tests for, but I verified this is working.

The error was being swallowed because the method was being called in a callback.

### CODE REVIEW

File: bin/eslint.js [hunk 1]
```diff
@@ -7,7 +7,12 @@ var exitCode = 0,
 
 if (useStdIn) {
     process.stdin.pipe(concat({ encoding: "string" }, function(text) {
-        exitCode = cli.execute(process.argv, text);
+        try {
+            exitCode = cli.execute(process.argv, text);
+        } catch (ex) {
+            console.error(ex.message);
+            exitCode = 1;
+        }
```
Comment (lo1tuma) [inline bin/eslint.js]: Wouldn’t this error also end up in the `error` event of the stream? Anyway it is always a good idea to add an error handler to every error event (https://github.com/maxogden/concat-stream#error-handling).

File: bin/eslint.js [hunk 2]
```diff
@@ -7,7 +7,12 @@ var exitCode = 0,
 
 if (useStdIn) {
     process.stdin.pipe(concat({ encoding: "string" }, function(text) {
-        exitCode = cli.execute(process.argv, text);
+        try {
+            exitCode = cli.execute(process.argv, text);
+        } catch (ex) {
+            console.error(ex.message);
```
Comment (lo1tuma) [inline bin/eslint.js]: Is there any reason you don’t want to show the stacktrace in the console? This would actually lead to two different outputs for the same error. If `cli.execute` throws on line 18, it would output the stacktrace, if it throws on line 11 it only outputs the message.

**Comment by lo1tuma** [comment]
Maybe we should try to extract this functionality to a different file where we can write tests more easily or we should write tests for `bin/eslint.js`.

File: bin/eslint.js (hunk 1 above)
Comment (nzakas) [inline bin/eslint.js]: No, the error is thrown in the callback, not in the process of reading the stream.

File: bin/eslint.js (hunk 2 above)
Comment (nzakas) [inline bin/eslint.js]: Good point, I'll add that.

**Comment by nzakas** [comment]
If you want to take a stab at writing tests, I'm all for it. I just don't have the time to figure out the best way to do it (this is part of why we have `cli` and `CLIEngine` - I extracted as much as I could into those to get as much test coverage as possible).

File: bin/eslint.js (hunk 1 above)
Comment (lo1tuma) [inline bin/eslint.js]: Interesting, but somewhere the error gets caught.

**Comment by lo1tuma** [comment]
Alright, I will investigate how we could test this.

File: bin/eslint.js (hunk 1 above)
Comment (nzakas) [inline bin/eslint.js]: Yup, I just have no idea where and not enough patience to keep digging in. :)
