### PR TITLE
Fix: `no-spaced-func` had been crashed

### LINKED ISSUE #4508: no-spaced-func: Cannot read property 'value' of undefined
ESLint 1.10.1 fails on this code:

```js
const foo = new (Foo({dummy: true}))
````

Version 1.9.0 works correctly and parses the code without any problems.

Stack trace:
```
/Users/xeed/js/elevatehd-web/node_modules/eslint/lib/rules/no-spaced-func.js:31
        while (parenToken.value !== "(") {
                         ^

TypeError: Cannot read property 'value' of undefined
    at EventEmitter.detectOpenSpaces (/Users/xeed/js/elevatehd-web/node_modules/eslint/lib/rules/no-spaced-func.js:31:26)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/xeed/js/elevatehd-web/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (/Users/xeed/js/elevatehd-web/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/Users/xeed/js/elevatehd-web/node_modules/eslint/lib/eslint.js:767:36)
    at Controller.__execute (/Users/xeed/js/elevatehd-web/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/xeed/js/elevatehd-web/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/Users/xeed/js/elevatehd-web/node_modules/eslint/lib/eslint.js:764:24)
    at processText (/Users/xeed/js/elevatehd-web/node_modules/eslint/lib/cli-engine.js:230:27)
```

Node version: 4.2.1

Thanks for help!

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28501854-no-spaced-func-cannot-read-property-value-of-undefined?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #4508

If the `callee` is enclosed with parentheses and arguments parentheses
are omitted, `no-spaced-func` had been crashed.

### CODE REVIEW

File: tests/lib/rules/no-spaced-func.js [hunk 1]
```diff
@@ -33,7 +33,8 @@ ruleTester.run("no-spaced-func", rule, {
         "( f()() )(0)",
         "(function(){ if (foo) { bar(); } }());",
         "f(0, (1))",
-        "describe/*.only*/('foo', function () {});"
+        "describe/*.only*/('foo', function () {});",
```
Comment (ilyavolodin) [inline tests/lib/rules/no-spaced-func.js]: Can you remove `.only` please? Even though it's commented out, it still scary:-)

Comment (mysticatea) [inline tests/lib/rules/no-spaced-func.js]: This is a regression test for #2211?

Comment (ilyavolodin) [inline tests/lib/rules/no-spaced-func.js]: Sorry, I don't mean remove the whole test, just the commented out `only` call.

Comment (mysticatea) [inline tests/lib/rules/no-spaced-func.js]: I updated it!
