### PR TITLE
Fix: `generator-star-spacing` false positive (fixes #6135)

### LINKED ISSUE #6135: generator-star-spacing: false positive at computed methods
**What version of ESLint are you using?**

v2.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default.

**Please show your full configuration:**

nothing.

**What did you do? Please include the actual source code causing the issue.**

```js
/*eslint-env es6*/
/*eslint generator-star-spacing:[2, "after"]*/

class A {
    * foo() {
    }
    
    * [Symbol.iterator]() {
    }
}
```

**What did you expect to happen?**

No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

`generator-star-spacing` rule is warning at `* [Symbol.iterator]() {`

image

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #6135.

In addition, this should work fine for async function as well.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Ee.. I have no idea what I'm looking at. Could somebody who knows something about generators take a look?:-)

**Comment by mysticatea** [comment]
Unfortunately, @mention-bot was sleeping.

/cc @btmills @alberto

**Comment by alberto** [comment]
LGTM

File: lib/rules/generator-star-spacing.js [hunk 1]
```diff
@@ -100,12 +118,12 @@ module.exports = {
...
             if (node.parent.method || node.parent.type === "MethodDefinition") {
-                starToken = sourceCode.getTokenBefore(node, 1);
+                starToken = getStarToken(node.parent);
             } else {
-                starToken = sourceCode.getFirstToken(node, 1);
+                starToken = getStarToken(node);
             }
 
-            // Only check before when preceded by `function` keyword
+            // Only check before when preceded by `function`|`static` keyword
```
Comment (btmills) [inline lib/rules/generator-star-spacing.js]: Good catch 👍

**Comment by btmills** [comment]
The tests are very thorough, nice job @mysticatea. LGTM.

Not merging yet since this was over the weekend (ref #6009).

**Comment by nzakas** [comment]
Lgtm

File: lib/rules/generator-star-spacing.js [hunk 2]
```diff
@@ -55,6 +55,24 @@ module.exports = {
...
+         *
+         * @param {ASTNode} node - A node to get `*` token. This is one of
+         *      FunctionDeclaration, FunctionExpression, Property, and
+         *      MethodDefinition.
+         * @returns {Token} `*` token.
+         */
+        function getStarToken(node) {
+            var token = sourceCode.getFirstToken(node);
+
+            while (token.value !== "*") {
```
Comment (crashbell) [inline lib/rules/generator-star-spacing.js]: I got an exception with this code: 
```js
TypeError: Cannot read property 'value' of undefined
```
Not really sure what I missed when upgrading `eslint` to the latest one since this PR was merged 13 days ago and no  one reported this.

Comment (mysticatea) [inline lib/rules/generator-star-spacing.js]: @crashbell Please see also: #6274

Comment (crashbell) [inline lib/rules/generator-star-spacing.js]: Thanks @mysticatea!
