### PR TITLE
Fix: Report columns for `eol-last` correctly (fixes #7136)

### LINKED ISSUE #7136: `eol-last`: Issues should be reported in last column, not the first
Currently, `eol-last` always reports linting issues [in column 1](https://github.com/eslint/eslint/blob/master/lib/rules/eol-last.js#L42).

Earlier today, @kaicataldo and I had a [discussion about this](https://github.com/eslint/eslint/pull/6952#issuecomment-246533858) and thought that semantically, it would make more sense to report issues at: *last line, last column* (as opposed to: *last line, first column*), since the last EOL in a file is also the last character of a line.

One might argue that the last EOL is a newline, so we could theoretically also report the issue in column `0`, but in line `lines + 1`. For users, the latter approach might be unexpected and have bad editor integration.

What do you think?

### PR DESCRIPTION
**Pull request by kdex**
**What is the purpose of this pull request? (put an "X" next to item)**

```
[ ] Documentation update
[X] Bug fix
[ ] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:
```

**Tell us about your environment**

* **ESLint Version:** 3.5.0
* **Node Version:** 6.5.0
* **npm Version:** 3.10.7

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
See source code below, it contains the configuration.

**What did you do? Please include the actual source code causing the issue.**
Check below.

**What did you expect to happen?**

The following file should report an issue at line 2, column 16.
```js
/* eslint eol-last: [1, "always"] */
var a = "test";
```

The following file should report an issue at line 3, column 1.
```js
/* eslint eol-last: [1, "never"] */
var a = "test";\n
```

**What actually happened? Please include the actual, raw output from ESLint.**

Instead, the following file reported an issue at line 2, column 1.
```js
/* eslint eol-last: [1, "always"] */
var a = "test";
```
The second test ran fine.

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change (by fixing the tests that depended on column to be 1)
- [ ] <strike>I've updated documentation for my change</strike> (*not applicable*)

**What changes did you make? (Give an overview)**
Instead of reporting issues for column 1, the code now reports the issue for the last column of the line. This broke three tests, which have been fixed.

**Is there anything you'd like reviewers to focus on?**

More information is available in [this discussion](https://github.com/eslint/eslint/pull/6952#issuecomment-246533858).

### CODE REVIEW

File: lib/rules/eol-last.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ module.exports = {
                 const sourceCode = context.getSourceCode(),
                     src = sourceCode.getText(),
                     location = {
-                        column: 1,
+                        column: lodash.last(sourceCode.lines).length,
```
Comment (platinumazure) [inline lib/rules/eol-last.js]: Given that `context.report` is supposed to use zero-based columns, should this be `lodash.last(sourceCode.lines).length - 1`? (I might be mistaken here.)

Actually, maybe it should be `.length` when a newline is absent, since that's where we would want to insert a newline in auto-fix... Yeesh. This could be a can of worms.

Comment (kdex) [inline lib/rules/eol-last.js]: @platinumazure I believe that the current implementation is correct and already uses zero-based columns. That's quite a statement, so I'll better back it up with a few examples to verify:

### Unwanted EOL

```js
/* eslint eol-last: [1, "never"] */\n
var a = 2;\n
```
There are three lines in this example (verify by checking `sourceCode.lines.length`). The lengths of these lines are `[35, 10, 0]`.
The last line is where the error should be reported. `location.column` will be evaluated to `"".length`, which is `0`. This sounds right for the column.

After linting it, I could indeed verify that it uses column `0` (by logging it separately) and therefore, it reports:

`  3:1  warning  Newline not allowed at end of file        eol-last`,

as the output transforms indices to a 1-based format.

### Missing EOL

Consider the following code:

```js
/* eslint eol-last: [1, "always"] */\n
var a = 2;
```

The configuration implies that the code is faulty; we're missing an EOL character. This time, we only have two lines. The error should be reported in the last column of the line 2, which should be one index after ";" or in other words `"var a = 2;".indexOf(";") + 1`, which evaluates to `10`.

When linting, `location.column` will be evaluated to `"var a = 2;".length`, which evaluates to `10`. Exactly what we wanted. Looking at the report, we can verify that it uses column `10` and therefore reports:

`  2:11  warning  Newline required at end of file but not found  eol-last`

as the output transforms indices to a 1-based format.

Given that I haven't missed anything, this looks valid to me. :smile:

Comment (platinumazure) [inline lib/rules/eol-last.js]: No, that all sounds great! I was thinking for the newline-is-present case
that there would be only two lines, the last ending in \n.

Can you do me a favor and double check for \r\n as well? Then I'll be happy
:-)

Comment (kdex) [inline lib/rules/eol-last.js]: @platinumazure Of course! Here you go:

### Unwanted EOL (CRLF)

Consider the following file:
```js
/* eslint eol-last: [1, "never"] */\r\n
var a = 2;\r\n
```
Again, those are three lines, and their lengths are (maybe surprisingly), again, `[35, 10, 0]`. By the same argument, again, column `0` is used. Thus, we get the exact same error report for the first example:

`  3:1  warning  Newline not allowed at end of file        eol-last`

### Missing EOL (CRLF)

Just like in the LF example, we have only two lines in this case:
```js
/* eslint eol-last: [1, "always"] */\r\n
var a = 2;
```

Again, `eol-last` uses column `10` and thus reports:

`  2:11  warning  Newline required at end of file but not found  eol-last`

**Comment by nzakas** [comment]
LGTM, just waiting another day so others can review.

File: lib/rules/eol-last.js (hunk 1 above)
Comment (platinumazure) [inline lib/rules/eol-last.js]: All sounds good to me, then!

**Comment by kaicataldo** [comment]
LGTM

**Comment by kaicataldo** [comment]
LGTM. Thanks for contributing to ESLint!
