### PR TITLE
Fix: Install ESLint on init if not installed (fixes #5833)

### LINKED ISSUE #5833: Can't install eslint
I followed the install instructions: `npm install -g eslint` and then this:

```
$ eslint --init
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Standard
? What format do you want your config file to be in? JavaScript
Installing eslint-plugin-standard, eslint-config-standard
@mperham/sidekiq@0.5.0 /Users/mike/src/sjs
├── UNMET PEER DEPENDENCY eslint@^2.0.0-rc.0
├── eslint-config-standard@5.1.0 
├── UNMET PEER DEPENDENCY eslint-plugin-promise@^1.0.8
├── eslint-plugin-standard@1.3.2 
└── sidekiq@1.1.1  extraneous

npm WARN eslint-config-standard@5.1.0 requires a peer of eslint@^2.0.0-rc.0 but none was installed.
npm WARN eslint-config-standard@5.1.0 requires a peer of eslint-plugin-promise@^1.0.8 but none was installed.
npm WARN @mperham/sidekiq@0.5.0 No repository field.
```

Running `eslint lib`  gives this:

```
$ eslint lib

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-standard". This can happen for a couple different reasons:
[snip]
```

I'm new to the JavaScript world - please let me know if you need more info.

### PR DESCRIPTION
**Pull request by kaicataldo**
Screenshots:
screen shot 2016-04-15 at 11 30 26 pm
screen shot 2016-04-15 at 11 30 33 pm

### CODE REVIEW

File: lib/config/config-initializer.js [hunk 1]
```diff
@@ -76,12 +80,24 @@ function installModules(config) {
     if (modules.length === 0) {
         return;
     }
+
+    // Add eslint to list in case user does not have it installed locally
+    modules.unshift("eslint");
```
Comment (kaicataldo) [inline lib/config/config-initializer.js]: Put at the beginning of the array for clarity, so that you see it's installing right after reading the `"Local ESLint installation not found."` message

File: tests/lib/config/config-initializer.js [hunk 2]
```diff
@@ -183,19 +183,19 @@ describe("configInitializer", function() {
...
 
-                assert.deepEqual(config, {extends: "airbnb", plugins: ["react"]});
+                assert.deepEqual(config, {extends: "airbnb", "installedESLint": true, plugins: ["react"]});
             });
 
             it("should support the standard style guide", function() {
                 var config = init.getConfigForStyleGuide("standard");
 
-                assert.deepEqual(config, {extends: "standard", plugins: ["standard"]});
+                assert.deepEqual(config, {extends: "standard", "installedESLint": true, plugins: ["standard"]});
```
Comment (zxqfox) [inline tests/lib/config/config-initializer.js]: Hm, quotes around installedESLint?

Comment (kaicataldo) [inline tests/lib/config/config-initializer.js]: Thanks for catching that - should definitely be consistent with what's already there.

Comment (kaicataldo) [inline tests/lib/config/config-initializer.js]: Fixed :+1:

**Comment by platinumazure** [comment]
@nzakas @kaicataldo I realize the issue was flagged as a bug, but it feels like our policy used to be "use global installation of ESLint with globally installed plugins, and local with local, and it's up to the user to know the difference". This honestly feels like a new feature to me (or else an enhancement of `eslint --init`). Should this functionality really be classified as a patch-level fix?

**Comment by nzakas** [comment]
@platinumazure its a bug because the installation fails otherwise. `--init` is designed to work locally, and in this case, it's not working correctly.

**Comment by platinumazure** [comment]
@nzakas Sorry, I'm not sure I buy it. In the bug, the user installed ESLint globally (`npm install -g eslint`) and then tried to use `--init` for a local project. Nothing in the repro steps suggests that the user actually tried to run `eslint --init` on a local installation, and that this local installation had failed.

Don't get me wrong-- I completely support this change and I welcome any change that will make it easier for people to use ESLint by bridging the global and local experience. I just don't think this change is a bugfix, that's all.

File: tests/lib/config/config-initializer.js (hunk 2 above)
Comment (ilyavolodin) [inline tests/lib/config/config-initializer.js]: @kaicataldo We should probably also enable the rules to check for this on our repository

**Comment by kaicataldo** [comment]
@platinumazure The other plugins that are installed during `--init` are installed locally, though. If the user is using a global installation when running `eslint --init`, it'll install the requisite plugins locally with no way to actually run them. This is a really bad experience for the user. 

I think `--init` should get ESLint working right out of the box, and if the users running `--init` are new (which I'm guessing a large portion are - seems to be the audience this feature is geared towards) they may not even be aware they should be worried about a local vs global installation. They'll just see that they run `--init` and that it doesn't work.

**Comment by kaicataldo** [comment]
Even if we decide this isn't the solution, I think *something* has to change to make this a better user experience (whether it's pointing the user to docs, more in-depth logging during the config process, etc.). I'm a big believer in the UX of a project like this, and I think `--init` should be as friendly and as much of a one stop shop as possible, given that it's our solution for onboarding new users and users who don't want to spend time on configuration.

**Comment by platinumazure** [comment]
@kaicataldo My mistake, I didn't realize the other plugins are installed
locally.

@nzakas I withdraw my objection. Thanks for your patience.

**Comment by nzakas** [comment]
Lgtm
