### PR TITLE
Fix: Jsdoc comment for multi-line function expressions (fixes #4889)

### LINKED ISSUE #4889: The valid-jsdoc rule doesn't catch missing param for multi-line assignment expressions
With ESLint @ 1972678ba03c25d1e5babff17c2d2559116a4886, if an assignment expression spans multiple lines, `valid-jsdoc` doesn't catch missing `@param` or param description.  See the following example:

```js
/* eslint valid-jsdoc: [2, {requireReturn: false}] */

var obj = {};

/**
 * Single line assignment.  The valid-jsdoc rule catches the issue with the
 * missing param description.
 * @param {string} arg
 * @return {string} A string.
 */
obj.foo = function(arg) {
  return arg;
};

/**
 * Multi line assignment.  The valid-jsdoc rule misses the issue with the
 * missing param description.
 * @param {string} arg
 * @return {string} A string.
 */
obj.bar =
    function(arg) {
      return arg;
    };
```
>   5:1  error  Missing JSDoc parameter description for 'arg'  valid-jsdoc

The first comment block is correctly linted (it is missing the parameter description).  The second comment block is not correctly linted (it is also missing the parameter description).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29712314-the-valid-jsdoc-rule-doesn-t-catch-missing-param-for-multi-line-assignment-expressions?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by nzakas** [comment]
Lgtm

**Comment by tschaub** [comment]
Thanks for addressing this.  It looks like this introduced a regression that I'll ticket separately.

File: lib/util/source-code.js [hunk 1]
```diff
@@ -216,29 +216,28 @@ SourceCode.prototype = {
...
             case "ClassExpression":
-                return findJSDocComment(parent.parent.leadingComments, line);
+                return findJSDocComment(parent.parent.leadingComments, parent.parent.loc.start.line);
 
             case "ArrowFunctionExpression":
             case "FunctionExpression":
 
                 if (parent.type !== "CallExpression" && parent.type !== "NewExpression") {
-                    while (parent && !parent.leadingComments && !/Function/.test(parent.type)) {
+                    while (parent && !parent.leadingComments && !/Function/.test(parent.type) && parent.type !== "MethodDefinition") {
```
Comment (tschaub) [inline lib/util/source-code.js]: It looks like this might traverse too far up the tree.  See #4900.
