### PR TITLE
Breaking: log number of fixable problems (fixes #7364)

### LINKED ISSUE #7364: Report format: log number of fixable problems
I'm using eslint v3.7.1.

One of my favourite eslint features is the ability to fix a lot of problems automatically. When my team considers adding a new eslint rule, we take into account how many times the rule is broken and whether those new problems can be fixed automatically. So sometimes we want to know how many problems can be automatically fixed without actually running eslint with the `--fix` option.

The current report ends with something like this:

```
✖ 103 problems (103 errors, 12 warnings)
```

It would be great if the number of fixable problems was also included. Maybe like this:

```
✖ 103 problems (103 errors, 12 warnings).
88 errors, 2 warnings can be fixed by running eslint with the --fix option.
```

### PR DESCRIPTION
**Pull request by alberto**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[X] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Add number of fixable problems to `cli-engine` and consume it in stylish formatter. This fixes #7364 

**Is there anything you'd like reviewers to focus on?**
No.

### CODE REVIEW

File: lib/cli-engine.js [hunk 1]
```diff
@@ -93,13 +95,21 @@ function calculateStatsPerFile(messages) {
...
+                stat.fixableWarningCount++;
+            }
         }
         return stat;
     }, {
         errorCount: 0,
-        warningCount: 0
+        warningCount: 0,
+        fixableErrorCount: 0,
+        fixableWarningCount: 0
```
Comment (not-an-aardvark) [inline lib/cli-engine.js]: If I'm not mistaken, it's possible for formatters to compute this on their own without needing a change to core. Is there a reason to add this to the report object?

File: lib/formatters/stylish.js [hunk 2]
```diff
@@ -73,14 +77,22 @@ module.exports = function(results) {
...
-            warnings, pluralize(" warning", warnings), ")\n"
+            " (", errorCount, pluralize(" error", errorCount), ", ",
+            warningCount, pluralize(" warning", warningCount), ")\n"
         ].join(""));
+
+        if (fixableErrorCount > 0 || fixableWarningCount > 0) {
+            output += chalk[summaryColor].bold([
+                "  ", fixableErrorCount, pluralize(" error", fixableErrorCount), ", ",
+                fixableWarningCount, pluralize(" warning", fixableWarningCount),
+                " can potentially be fixed by running eslint with the `--fix` option.\n"
```
Comment (not-an-aardvark) [inline lib/formatters/stylish.js]: Current output:



Compared to the previous output, this seems a bit verbose to me. Can we reword it? For example:

> 2 problems (1 error, 1 warning), 1 problem potentially fixable with the \`--fix\` option

Since the `--fix` flag tries to fix both errors and warnings anyway, I don't think it's worth displaying fixable counts for each type of problem.

I'm open to bikeshedding on this. The reason I'm concerned about keeping the message short is because this gets printed for a large percentage of reports, so the output will need to be read quite a lot. I think it will be better for UX if we can keep the message as simple as possible while still conveying the same information.

File: lib/cli-engine.js (hunk 1 above)
Comment (alberto) [inline lib/cli-engine.js]: To avoid duplicating this logic on every formatter.

File: lib/formatters/stylish.js (hunk 2 above)
Comment (alberto) [inline lib/formatters/stylish.js]: I'm open for comments in the message too. I think the differentiation between errors and warnings may useful because not everyone wants to automatically fix warnings.

What about:
> 2 problems (1 error, 1 warning)
> 1 error, 1 warning potentially fixable with the `--fix` option

**Comment by alberto** [comment]
Updated message in stylish and added info to codeframe.

File: lib/formatters/codeframe.js [hunk 3]
```diff
@@ -74,11 +74,14 @@ function formatMessage(message, parentResult) {
...
  * @param   {number} warnings The number of warnings.
+ * @param   {number} fixableErrors The number of fixable errors.
+ * @param   {number} fixableWarnings The number of fixable warnings.
  * @returns {string}          The formatted output summary.
  */
-function formatSummary(errors, warnings) {
+function formatSummary(errors, warnings, fixableErrors, fixableWarnings) {
     const summaryColor = errors > 0 ? "red" : "yellow";
     const summary = [];
+    const fixablesSummay = [];
```
Comment (vitorbal) [inline lib/formatters/codeframe.js]: small typo: fixablesSummary

**Comment by ilyavolodin** [comment]
@alberto Could you rebase please?

**Comment by ilyavolodin** [comment]
I rebase this PR and added documentation. It's ready to be re-reviewed.
