### PR TITLE
Fix: Global block-scope-var check should work (fixes #1980)

### LINKED ISSUE #1980: block-scoped-var bug with modules
testing
```js
const React = require("react/addons");
const cx = React.addons.classSet;
```

with v0.16.1 and 
```json
{
  "ecmaFeatures" : {
    "modules" : true,
  },
  "env" : {
    "node": true,
    "es6" : true,
  },
  "rules" : {
    "block-scoped-var": 2,
  }
}
```

I get the error _"React" used outside of binding context_ from "block-scoped-var"

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9338253-block-scoped-var-bug-with-modules?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

File: lib/eslint.js [hunk 1]
```diff
@@ -660,6 +660,11 @@ module.exports = (function() {
                     ecmaFeatures.modules || ecmaFeatures.defaultParams ||
                     ecmaFeatures.destructuring) ? 6 : 5;
 
+            // can't have global return inside of modules
```
Comment (nzakas) [inline lib/eslint.js]: This is too late for this code, needs to happen before `parse()`.
