### PR TITLE
Fix: function body indent issues (fixes #3614, fixes #3799)

### LINKED ISSUE #3614: Indent error with the second function argument with eslint v1.3.1
Similar error was reported as issue #3591 which has been fixed since commit e8081 (I've confirmed), but I am still seeing the similar error with following code using rev 52c42b:

```js
'use strict';
/*eslint-disable no-console */
var Promise = require('bluebird');

function doSomething() {
    return Promise.resolve()
    .then(function () {
        var o = 1 + 2;
        return o;
    }, function (err) {
        console.log('err:', err);
        var o = 1 - 2;
        return o;
    });
}

doSomething()
.then(function (ans) {
    console.log('ans=%d', ans);
});
```
Here's the output:
```
test.js|11 col 9 error| Expected indentation of 12 space characters but found 8. (indent)
test.js|12 col 9 error| Expected indentation of 12 space characters but found 8. (indent)
test.js|13 col 9 error| Expected indentation of 12 space characters but found 8. (indent)
test.js|14 col 5 error| Expected indentation of 8 space characters but found 4. (indent)
```
My indent rule is `[2, 4]`

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26349191-indent-error-with-the-second-function-argument-with-eslint-v1-3-1?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #3799: Odd indent error after updating to 1.4.1
Ref: https://github.com/eslint/eslint/issues/3591#issuecomment-139669222

---

I'm seeing some odd indenting rule behavior after updating to **eslint@1.4.1**.

```
$ ./node_modules/grunt-eslint/node_modules/.bin/eslint --version
v1.4.1

$ grunt eslint:tests
Running "eslint:tests" (eslint) task

/Users/pdehaan/dev/fxa-content-server/tests/functional/oauth_reset_password.js
  40:9  warning  Expected indentation of 6 space characters but found 8  indent

✖ 1 problem (0 errors, 1 warning)


Done, without errors.
```

And here's my code:
```js
37:      return client.signUp(email, PASSWORD, { preVerified: true })
38:        .then(function (result) {
39:          // do nothing
40:        })
41:        .then(function () {
42:          // clear localStorage to avoid polluting other tests.
43:          return FunctionalHelpers.clearBrowserState(self, {
44:            contentServer: true,
45:            '123done': true
46:          });
47:        });
```

And here's the code that ESLint expects:
```js
      return client.signUp(email, PASSWORD, { preVerified: true })
        .then(function (result) {
          // do nothing
      })  // <---------- THIS LINE RIGHT HERE
        .then(function () {
          // clear localStorage to avoid polluting other tests.
          return FunctionalHelpers.clearBrowserState(self, {
            contentServer: true,
            '123done': true
          });
        });
```

I think this is due to the fact that the only element in my function is a comment.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26676865-odd-indent-error-after-updating-to-1-4-1?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**
I have cleaned up the logic for function body indent and found out that it was not catching a lot of errors and also it never respected the function under a variable declaration.

Note: Multi-line issue in general still persists.

### CODE REVIEW

File: lib/cli-engine.js [hunk 1]
```diff
@@ -475,8 +475,8 @@ CLIEngine.prototype = {
      */
     resolveFileGlobPatterns: function(patterns) {
         var extensions = this.options.extensions.map(function(ext) {
-                return ext.charAt(0) === "." ? ext.substr(1) : ext;
-            });
+            return ext.charAt(0) === "." ? ext.substr(1) : ext;
```
Comment (BYK) [inline lib/cli-engine.js]: hah

File: lib/rules/indent.js [hunk 2]
```diff
@@ -303,17 +327,16 @@ module.exports = function(context) {
             indent += indentSize;
         }
 
+        // function body indent should be indent + indent size
         indent += indentSize;
-        // If function content is not empty
```
Comment (BYK) [inline lib/rules/indent.js]: Ugh, I hated this part. Glad it is gone now.

**Comment by BYK** [comment]
Although this looks great, I think you've broken a "feature". People expected to indent functions extra without warning as long as it is consistent in the function. I think we should keep that (the part I hated that you remove) but may be behind an option which defaults to `true`: `allowExtraFunctionIndentation`.

**Comment by gyandeeps** [comment]
What you are mentioning was never a feature (can u share the example of the usecase u r talking about), it was happening because the rule was broken for function body including the bug where it never checked if the body is inside a variable declaration.

Remember, introducing such options (not a huge win option) is unnecessary complicating the rule with almost no gain. Its already so complicated.

**Comment by BYK** [comment]
Alright, I'm just warning you. It's on you if people start yelling about this after a release :D (otherwise I was gonna remove that in one of my earlier patches)

>Remember, introducing such options (not a huge win option) is unnecessary complicating the rule with almost no gain. Its already so complicated.

Totally agree. Suggested this to at least deprecate the "feature" gracefully.

**Comment by gyandeeps** [comment]
Can you share the use case which you are specifically talking about.

**Comment by BYK** [comment]
```
$.ajax().then(
    function x(a, b) {
        extraIndent();
    }, function () {
        something();
    }
);
```

Might be an example. I don't use this thing (the extra indent adaptation) so I'm not sure if I can come up with a legit case :)

**Comment by gyandeeps** [comment]
I just added a unit test for a similar case and it works. Before it used to give errors.

**Comment by BYK** [comment]
Alright, shutting up :D

**Comment by gyandeeps** [comment]
lol... I am just trying to find out if I am missing something.

File: lib/cli-engine.js (hunk 1 above)
Comment (gyandeeps) [inline lib/cli-engine.js]: This is an debatable known issue : https://github.com/eslint/eslint/issues/3352
Before it was not getting flagged because function body never took into consideration the variable declaration factor.

**Comment by nzakas** [comment]
All set here?

**Comment by BYK** [comment]
I'm good. LGTM :)
