### PR TITLE
Fix: Adds conditional for separateRequires in one-var (fixes #10179)

### LINKED ISSUE #10179: 'one-var' doesn't respect 'separateRequires' option with 'always' or 'consecutive'
**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 8.11.1
* **npm Version:** 5.8.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
	'root': true,
	'extends': [],
	'parserOptions': {
		'ecmaVersion': 8
	},
	'env': {
		'es6': true,
		'node': true
	},
	'rules': {
		'no-mixed-requires': [2, { 'allowCall': false }],
		'one-var': [2, { 'var': 'consecutive', 'separateRequires': true }],
	}
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
Took code from https://eslint.org/docs/rules/one-var#var-let-and-const under the `separateRequires` block.

```js
var foo = require('foo');
var bar = 'bar';

var foo = require('foo'),
	bar = require('bar');
```

Ran through Webstorm, which I presume just runs the configured package (which is the correct path) against the current file.

**What did you expect to happen?**
No errors are flagged.

**What actually happened? Please include the actual, raw output from ESLint.**
2 errors are flagged: The first `bar` variable wants to be joined with the first `foo`. The second foo/bar block wants to be joined with the first block. Interestingly if you make the `consecutive` option an `always`, the first error goes away.

### PR DESCRIPTION
**Pull request by sstern6**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Added conditionals to the `hasOnlyOneStatement` based on currentScope that has requires to avoid throwing an error when it should not.

**Is there anything you'd like reviewers to focus on?**
Looking at the function `hasOnlyOneStatement`, not sure if it actually does what the JSDocs suggest it does.  Ensure the changes I added did not make the rule more brittle and to make sure the function is aligned with the JSDocs, if its not, maybe we can open a ticket helping to clarify `hasOnlyOneStatement`.

Also, docs seem a little misleading here https://eslint.org/docs/rules/one-var#var-let-and-const. The following should be split into two separate examples IMO from speaking with @not-an-aardvark for clarification.

```
/*eslint one-var: ["error", { separateRequires: true, var: "always" }]*/
/*eslint-env node*/

var foo = require("foo");
var bar = "bar";

var foo = require("foo"),
    bar = require("bar");
```
Issue this fixes: https://github.com/eslint/eslint/issues/10179

Thank you

### CODE REVIEW

**Comment by kaicataldo** [comment]
Looks like the commit-message check is failing - mind updating the commit message and PR title according to [our guidelines](https://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changes)? It would be great if you could link the issue in the comment as well (it helps us reviewers keep track of everything 😄)!

**Comment by sstern6** [comment]
Will do @kaicataldo sorry about that, thought i had followed the guidelines.  Will update.

**Comment by kaicataldo** [comment]
No problem!

**Comment by platinumazure** [comment]
@sstern I think the period at the end might be triggering the commit message check. Can you please try removing that? (If you intend to push more commits, then you can just change the PR title instead.)

**Comment by sstern6** [comment]
@platinumazure @kaicataldo commit message fixed, any feedback on the PR?

**Comment by sstern6** [comment]
Bump, if anyone has time to take a look at this.

**Comment by sstern6** [comment]
Sounds good.

**Comment by sstern6** [comment]
@platinumazure will have this updated for re-review tonight, sorry about the delay.

File: lib/rules/one-var.js [hunk 1]
```diff
@@ -255,7 +255,9 @@ module.exports = {
 
             if (currentOptions.uninitialized === MODE_ALWAYS && currentOptions.initialized === MODE_ALWAYS) {
                 if (currentScope.uninitialized || currentScope.initialized) {
-                    return false;
+                    if (!hasRequires) {
```
Comment (kaicataldo) [inline lib/rules/one-var.js]: Should this also be using `separateRequires`? I can't do a deep dive at the moment, but this caught my eye.

File: lib/rules/one-var.js [hunk 2]
```diff
@@ -266,7 +268,9 @@ module.exports = {
             }
             if (declarationCounts.initialized > 0) {
                 if (currentOptions.initialized === MODE_ALWAYS && currentScope.initialized) {
-                    return false;
+                    if (!hasRequires) {
```
Comment (kaicataldo) [inline lib/rules/one-var.js]: Same comment as above.

File: lib/rules/one-var.js (hunk 1 above)
Comment (sstern6) [reply lib/rules/one-var.js]: instead of separate requires?

**Comment by sstern6** [comment]
@platinumazure added the test you wanted.  Noticed in the fix though that its adding an extra space, I can fix this here or open another issue.

https://github.com/eslint/eslint/pull/10980/files#diff-dc5dd8abac35c54b3db7451ddb0a8f79R1106

File: lib/rules/one-var.js (hunk 1 above)
Comment (sstern6) [reply lib/rules/one-var.js]: @kaicataldo could you expand on your question, dont think I understand what youre asking.

Comment (kaicataldo) [reply lib/rules/one-var.js]: Sorry, got a bit busy and lost track of this. My question was about these checks always checking if there are `require`s but not checking if the `separateRequires` config option was set or not. Hopefully I'll be able to look at this a little closer later tonight.

Comment (sstern6) [reply lib/rules/one-var.js]: @kaicataldo I see.  Good point.  The false being returned in my contributions allow this conditional to be fulfilled. https://github.com/eslint/eslint/blob/56a677c45f6555096dc50b19806f243c17d994ef/lib/rules/one-var.js#L441.  Though thats a good point, for this ticket i could add `options.separateRequires && !hasRequires`.

WDYT?

**Comment by sstern6** [comment]
thanks @platinumazure did you want me to open a new issue with the extra space in the autofix or is that expected.

**Comment by sstern6** [comment]
@platinumazure need anything else from me on this PR?

**Comment by platinumazure** [comment]
@sstern6 No, not at this point. I'll restart the Travis and AppVeyor builds to see if they'll pass-- if not, we'll need you to fix any lint or test issues that may arise :smile:

**Comment by platinumazure** [comment]
@sstern6 Looks like you have a lint error about one of your test cases-- we like to have a consistent order of the test case properties and the test case you added doesn't stick to that. Can you please fix that? Then this should be ready for final review by the team!

File: tests/lib/rules/one-var.js [hunk 3]
```diff
@@ -1092,6 +1100,17 @@ ruleTester.run("one-var", rule, {
                 column: 25
             }]
         },
+        {
+            code: "var a = true; var b = false;",
+            options: [{ separateRequires: true, var: "always" }],
+            output: "var a = true,  b = false;",
```
[the remark this answers is not in the document]
Comment (sstern6) [reply tests/lib/rules/one-var.js]: Sounds good, sorry about the delay.  Will have this finished this week.

**Comment by korneliakobiela** [comment]
Oh, If this PR is abandoned I would like to complete it based on the committed code.

**Comment by sstern6** [comment]
@korneliakobiela sorry been busy with other stuff lately ill have this done tonight.  Been open too long sorry about that everyone.  If I dont get it done tonight please feel free to take it.

**Comment by korneliakobiela** [comment]
Ok, please give me about two weeks to get known code and complete this PR

File: tests/lib/rules/one-var.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (sstern6) [reply tests/lib/rules/one-var.js]: @platinumazure addressed comments.

**Comment by platinumazure** [comment]
@kaicataldo Could you please take a look at this and make sure your concerns are addressed? (If you're not sure, maybe it would help to think of a test case which could be added.) Thanks!

**Comment by kaicataldo** [comment]
Sorry I lost track of this. Don't let me hold things up!
