### PR TITLE
Fix: add parentheses in no-extra-boolean-cast autofixer (fixes #7912)

### LINKED ISSUE #7912: no-extra-boolean-cast --fix
* **ESLint Version:**
3.13.1
* **Node Version:**
7.4.0
* **npm Version:**
4.0.5

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```
{
  "rules": {
    "no-extra-boolean-cast": "error"
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
run ```eslint --fix``` on the code below:
```js
function baz(foo)  { return !Boolean(foo && foo.bar); }
```
**What did you expect to happen?**
I expect to "Boolean" to be removed from the code.

**What actually happened? Please include the actual, raw output from ESLint.**
The brackets get dropped causing change of the behaviour of my code.
```js
function baz(foo)  { return !foo && foo.bar; }
```

### PR DESCRIPTION
**Pull request by sprzybylski**
**What is the purpose of this pull request? (put an "X" next to item)**
[X] Bug fix for #7912 

**What changes did you make? (Give an overview)**
I've change autofixer in no-extra-boolean-cast rule for "Redundant Boolean call" to include brackets if the inner part is an expression.

### CODE REVIEW

File: lib/rules/no-extra-boolean-cast.js [hunk 1]
```diff
@@ -91,7 +91,14 @@ module.exports = {
                     context.report({
                         node,
                         message: "Redundant Boolean call.",
-                        fix: fixer => fixer.replaceText(node, sourceCode.getText(node.arguments[0]))
+                        fix: fixer => {
+                            const argument = node.arguments[0];
+
+                            if (argument.type === "LogicalExpression") {
```
Comment (not-an-aardvark) [inline lib/rules/no-extra-boolean-cast.js]: This will fix the specific case in the bug report, but I think the problem will still exist for arguments that aren't `LogicalExpression` nodes. For example, this fix would still be incorrect:

```js
!Boolean(1 + 2);

// gets fixed to:

!1 + 2;
```

I think best solution would be to check the *precedence* of the argument. The fixer should only add parentheses if the argument has lower precedence than the `!Boolean(...)` node, which is a `UnaryExpression`. (If the argument has higher precedence, the `!` operator will get applied to the entire argument anyway.)

For example, a `UnaryExpression` has a higher precedence than a `LogicalExpression`, so `!foo && bar` gets parsed as `(!foo) && bar`. On the other hand, a `CallExpression` has lower precedence than a `UnaryExpression`, so `!foo()` will get parsed as `!(foo())` rather than `(!foo)()`.

A function to get the precedence of a node can be found [here](https://github.com/eslint/eslint/blob/427543afb4bf024869b8a243c793824eca73ad67/lib/ast-utils.js#L613-L703) in `ast-utils.js`

File: lib/rules/no-extra-boolean-cast.js [hunk 2]
```diff
@@ -91,7 +97,14 @@ module.exports = {
                     context.report({
                         node,
                         message: "Redundant Boolean call.",
-                        fix: fixer => fixer.replaceText(node, sourceCode.getText(node.arguments[0]))
+                        fix: fixer => {
+                            const argument = node.arguments[0];
+
+                            if (astUtils.getPrecedence(argument) < astUtils.getPrecedence(node)) {
```
Comment (sprzybylski) [inline lib/rules/no-extra-boolean-cast.js]: I'm not 100% sure if I get you suggestion right @not-an-aardvark . In this case node precedence will always be the same because its CallExpression every time.

Comment (not-an-aardvark) [inline lib/rules/no-extra-boolean-cast.js]: It looks like this is using the precedence of the `Boolean()` call expression, but remember that the call expression won't exist anymore when `Boolean` is removed. Instead, I think we want to compare it to `node.parent`, which is a `UnaryExpression`.

To double-check, I think it would be a good idea to add cases like these to the tests:

```js
!Boolean(foo + bar);

// fixed to

!(foo + bar);

// ---

!Boolean(+foo);

// fixed to

!+foo;

// ---

!Boolean(foo());

// fixed to

!foo();

// ---

!Boolean(foo = bar);

// fixed to

!(foo = bar);
```

Comment (sprzybylski) [inline lib/rules/no-extra-boolean-cast.js]: Updated PR. Thank you!
