### PR TITLE
Fix: Delete cache only when executing on files (fixes #6459)

### LINKED ISSUE #6459: Cache is deleted when linting text
**What version of ESLint are you using?**
Master

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
N/A

**What did you do? Please include the actual source code causing the issue.**

Given a directory with a file and an `.eslintcache`:
```
> tree -a
.
├── .eslintcache
└── foo.js
```

Running eslint on text with `--stdin` causes the `.eslintcache` file to be deleted:

```
> echo "var foo=42;" | eslint --stdin
> tree -a
.
└── foo.js
```

**What did you expect to happen?**

Since the cache is only used when executing on files, I would not expect the `.eslintcache` file to be deleted.  This causes problems when using eslint in a text editor like Atom, because it means as soon as a file is opened (and therefore linted), the cache file is deleted (see https://github.com/AtomLinter/linter-eslint/issues/587).  

I believe this is because the code which deletes the cache is too high in the CLIEngine execution [right after instantiation](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L460).  It could likely be moved into `executeOnFiles` as an `else` to [this check](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L641).

### PR DESCRIPTION
**Pull request by kaicataldo**

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM

File: lib/cli-engine.js [hunk 1]
```diff
@@ -694,6 +690,8 @@ CLIEngine.prototype = {
                     descriptor.meta.hashOfConfig = hashOfConfig;
                     descriptor.meta.results = res;
                 }
+            } else {
```
Comment (IanVS) [inline lib/cli-engine.js]: Question: Is there a reason you put this here instead of the first `if` block (https://github.com/eslint/eslint/pull/6540/files#diff-3daec82d5218d64d8f2fed4d21f8e6ccR636) ?

Comment (kaicataldo) [inline lib/cli-engine.js]: Not sure I follow - which first `if` block? I thought we were destroying the cache if it wasn't called with the `--cache` flag

Comment (IanVS) [inline lib/cli-engine.js]: Sorry, was rushing to get to a meeting.  The line I linked to is also an `if (options.cache) {`, which happens before the file is processed.  I think the cache should probably be destroyed up there, rather than here after the call to `processFile`, so I was asking if there was a reason you put it down here instead.

File: tests/lib/cli-engine.js [hunk 2]
```diff
@@ -1812,6 +1813,74 @@ describe("CLIEngine", function() {
                 assert.deepEqual(result, cachedResult, "result is the same with or without cache");
             });
 
+            it("should not delete cache when executing on text", function() {
```
Comment (IanVS) [inline tests/lib/cli-engine.js]: Is it worth also including a test for `should not delete cache when executing on text with a provided filename`, to address https://github.com/eslint/eslint/issues/6459#issuecomment-228552473 ?

File: lib/cli-engine.js (hunk 1 above)
Comment (kaicataldo) [inline lib/cli-engine.js]: Oh, I see now - sorry, didn't see the highlighted line because it was collapsed. No, I actually missed that. Definitely makes sense to put it up there. I'll update the PR :+1:

File: tests/lib/cli-engine.js (hunk 2 above)
Comment (kaicataldo) [inline tests/lib/cli-engine.js]: Makes sense to me

**Comment by kaicataldo** [comment]
@IanVS Updated - thanks for reviewing!

**Comment by IanVS** [comment]
👍  LGTM!

**Comment by gyandeeps** [comment]
LGTM :+1: 
Thanks for contributing.
