### PR TITLE
fix: handle files with unspecified path in `getRulesMetaForResults`

### LINKED ISSUE #16410: Bug: `FlatESLint` `getRulesMetaForResults` fails on anonymous files when option `cwd` is set
### Environment

Node version: v18.10.0
npm version: v8.19.2
Local ESLint version: v8.25.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 21.6.0

### What parser are you using?

Default (Espree)

### What did you do?

Using `FlatESLint`, the method `getRulesMetaForResults` thows an error for certain values of the option `cwd` when passed a result of an anonymous file. This happens whenever `cwd` is set to a subdirectory of the current directory.

The following repro shows the problem.

```js
import { join } from 'path';

const { default: { FlatESLint } } = await import('eslint/use-at-your-own-risk');

const cwd = join(process.cwd(), 'test'); // subdir 'test' doesn't need to exist for this repro.
const eslint = new FlatESLint({
    cwd,
    overrideConfig: { rules: { 'no-undef': 'warn' } },
    overrideConfigFile: true,
});
const results = await eslint.lintText('foo()');
eslint.getRulesMetaForResults(results); // throws TypeError
```

### What did you expect to happen?

Calling `getRulesMetaForResults` with the result of an anonymous file should not throw an error, regardless of the engine's `cwd`.

### What actually happened?

The above repro fails with an error like this:

<pre>
.../node_modules/eslint/lib/config/flat-config-helpers.js:54
    const plugin = config.plugins && config.plugins[pluginName];
                          ^

TypeError: Cannot read properties of undefined (reading 'plugins')
    at getRuleFromConfig (.../node_modules/eslint/lib/config/flat-config-helpers.js:54:27)
    at FlatESLint.getRulesMetaForResults (.../node_modules/eslint/lib/eslint/flat-eslint.js:703:30)
    at file://.../example.mjs:12:8
</pre>

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

What strikes me in the implementation are the different values used to call `configs.getConfig` in the case of an anonymous file: `lintText` calls `configs.getConfig` with a full path like `${cwd}/__placeholder__.js`

https://github.com/eslint/eslint/blob/173e82040895ad53b2d9940bfb3fb67a0478f00b/lib/eslint/flat-eslint.js#L956

whereas `getRulesMetaForResults` ends up calling `configs.getConfig("__placeholder__.js")`

https://github.com/eslint/eslint/blob/173e82040895ad53b2d9940bfb3fb67a0478f00b/lib/eslint/flat-eslint.js#L689-L699

Then it finds no config and it fails.

Another issue related to this is the unhelpful message of the `TypeError`.
When `getRulesMetaForResults` finds no matching config, it could simply tell the user that the results were not created from the current instance of ESLint (not the case here, but still).
The error message is already there, but it is currently only used in a more limited edge case:

https://github.com/eslint/eslint/blob/173e82040895ad53b2d9940bfb3fb67a0478f00b/lib/eslint/flat-eslint.js#L684

### PR DESCRIPTION
**Pull request by fasttime**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #16410

#### What changes did you make? (Give an overview)

* In `getRulesMetaForResults`, files with an unspecified path are now treated as if they were located inside `cwd`.
* In `getRulesMetaForResults`, when a result referencing a rule has no config, we will explicitly throw an error with a descriptive message.
* Added top-level, internal functions `getPlaceholderPath` and `createExtraneousResultsError` to avoid code repetition.
* Added two new unit tests.
* Renamed an existing unit test to better disambiguate it from a new one. Also changed the assertion to check both error message and constructor.

### CODE REVIEW

**Review by mdjermanovic — APPROVED** [review]
LGTM, but would like @nzakas to take a look.

**Comment by mdjermanovic** [comment]
Oh, and there's a merge conflict.

**Comment by fasttime** [comment]
Thanks for reviewing @mdjermanovic! I've rebased the branch and fixed the merge conflict.

File: lib/eslint/flat-eslint.js [hunk 1]
```diff
@@ -689,16 +710,20 @@ class FlatESLint {
...
 
             for (const { ruleId } of allMessages) {
+
+                /*
+                 * All of the plugin and rule information is contained within the
+                 * calculated config for the given file.
+                 */
+                const config = configs.getConfig(filePath);
+
+                if (!config) {
```
Comment (nzakas) [inline lib/eslint/flat-eslint.js:724]: There may be an edge case here. getConfig returns undefined if a file is ignore by the configuration, so it doesn’t necessarily mean that the file wasn’t run in this instance. I think this will result in an error if the results contain a warning for a file that was ignored.

You can test this by passing in a file that is specifically ignored.

**Review by nzakas — CHANGES_REQUESTED** [review]

File: lib/eslint/flat-eslint.js (hunk 1 above)
Comment (fasttime) [reply lib/eslint/flat-eslint.js:724]: Yes, I also thought about that. Now that #16402 has been fixed, the specific edge case you mention should be handled correctly. I will rebase the branch once again and add a new unit test to check the behavior in case an explicitly ignored file appears in the results when `warnIgnored` is set. Thanks for the feedback!

Comment (fasttime) [reply lib/eslint/flat-eslint.js:716]: I've added a new unit test for when an anonymous file is ignored and linted with `warnIgnored`. A similar case, where the file has a specified path, is already covered in another test: https://github.com/eslint/eslint/blob/740b20826fadc5322ea5547c1ba41793944e571d/tests/lib/eslint/flat-eslint.js#L3864-L3867

**Comment by fasttime** [comment]
Rebased and updated as suggested by @nzakas. Since the new unit tests are only relevant to `FlatESLint`, I put them all at the start of the `describe` block, just under another existing, `FlatESLint`-specific unit test.

File: lib/eslint/flat-eslint.js (hunk 1 above)
Comment (nzakas) [reply lib/eslint/flat-eslint.js:716]: I think we should add a test with `lintFiles()` as well. We need to make sure that if there are multiple files linted and one ignored that this won't throw an error.

My concern: `isFileIgnored()` just does `getConfig() === undefined`, so what you are really testing here is if a file is ignored. Because of that, it still seems like there's an edge case here that will bite us.

I think it would be safe to remove this check.

Comment (fasttime) [reply lib/eslint/flat-eslint.js:716]: Ignored file results, as they don't have any messages with a `ruleId`, should be skipped by the `continue` statement a few lines above.

The point of checking if a config is found here is to avoid results linted by a different engine. If a result was not linted by the current engine, it may have no config without being ignored. This specific case is covered in [this test](https://github.com/eslint/eslint/pull/16437/files#diff-bef458c9c787f61228076dadf8878220be8c0f0ab489daa129a0d237a2feae17R3753-R3783). If this check is removed, `getRulesMetaForResults` will still fail, but with a non-specific error message (because `config.plugins` cannot be accessed at some point).

Adding a test with linted files and an ignored file at the same time is a good idea. There are no tests with multiple results so far. Thanks for the suggestion!

**Comment by fasttime** [comment]
Added another unit test with `lintFiles()` as suggested by @nzakas.

File: tests/lib/eslint/flat-eslint.js [hunk 2]
```diff
@@ -3813,6 +3813,26 @@ describe("FlatESLint", () => {
...
+                overrideConfig: {
+                    rules: {
+                        "no-undef": 2,
+                        semi: 1
+                    }
+                }
+            });
+
+            const results = await engine.lintFiles(["missing-semicolon.js", "passing.js", "undef.js"]);
+            const rulesMeta = engine.getRulesMetaForResults(results);
```
[the remark this answers is not in the document]
Comment (fasttime) [reply tests/lib/eslint/flat-eslint.js:3836]: Okay, I've added an assertion to make sure that one of the messages returned by `lintFiles` belongs to an ignored file.
I chose this implementation because it doesn't require calling another method on the engine under test.
Alternatively, we could pass the `filePath` of each result to `isPathIgnored()`.

[the remark this answers is not in the document]
Comment (nzakas) [reply tests/lib/eslint/flat-eslint.js:3836]: This works. 👍

**Review by nzakas — APPROVED** [review]
LGTM. Thanks so much for this.
