### PR TITLE
Fix: syntax errors created by `object-shorthand` autofix (fixes #7574)

### LINKED ISSUE #7574: Linting with auto-fix with rule 'object-shorthand' breaks properties with async/await functions
**Configuration**
```
node 6.9.1
npm 3.10.8
dependencies: {
    "eslint": "^3.8.0",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-import": "^2.0.1",
    "babel-eslint": "^7.1.0",
    "eslint-config-xo": "^0.17.0",
    "eslint-config-xo-react": "^0.10.0",
    "eslint-plugin-ava": "^4.0.0",
    "eslint-plugin-react": "^6.6.0"
  }
```

**Have**
You have `index.js`:
```js
function MyObj() {}

MyObj.prototype = {
    someMethod: async function () {}
};
```

You have `.eslintrc`
```json
{
    "parserOptions": {
        "ecmaVersion": 2017
    },
    "rules": {
        "object-shorthand": ["error", "always"]
    }
}
```

You run:
```bash
./node_modules/.bin/eslint --fix ./index.js 
```

You get in `index.js`:
```js
export default {};

function MyObj() {}

MyObj.prototype = {
    someMethodnction() {} // wrong auto-fix
};
```

**Expects & caused by**
I've investigated that it caused by `object-shorthand` rule. 
```json
{
    "object-shorthand": ["error", "properties"]
}
```
If i set up it like that everything is ok. But I think with rule `["error", "always"]` also everything should be linted great.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

See https://github.com/eslint/eslint/issues/7574

**What changes did you make? (Give an overview)**

This fixes several bugs in `object-shorthand`'s autofixing.

* Previously, if an object had a computed key that was anything other than an identifier corresponding to a generator function property, the fixer would output unbalanced square brackets with `undefined` as the property name.

  ```js
  ({ [foo.bar]: function*() {} });

  // was previously fixed to:

  ({ [*[undefined]() {} }); // unexpected `undefined`
  ```
* Previously, the fixer would output invalid syntax if there was a space between a computed property and its closing bracket.
  ```js
  ({ [ foo ]: function() {} });

  // was previously fixed to:

  ({ [ foo () {} }); // no closing ]
  ```
* Previously, the fixer would output invalid syntax for generator functions if there was a space before the star.
  ```js
  ({ foo: function *() {} });

  // was previously fixed to:

  ({ *foo*() {} }); // extra star
  ```
* Previously, the fixer would output incorrect fixes for async functions (https://github.com/eslint/eslint/issues/7574).
  ```js
  ({ foo: async function() {} });

  // was previously fixed to:

  ({ foonction() {} }); // lol `foonction`
  ```

**Is there anything you'd like reviewers to focus on?**

This is a fairly bad bug, since the resulting code after autofixing an async function is still syntactically valid (so the user won't notice the issue), but it does something completely different than before. I'm hoping we can expedite this PR to get the fix into the upcoming release.

However, it is a semver-patch change, so it could also go into a patch release if we decide to create one for this release.

### CODE REVIEW

File: tests/lib/rules/object-shorthand.js [hunk 1]
```diff
@@ -144,6 +144,11 @@ ruleTester.run("object-shorthand", rule, {
...
         { code: "doSomething({[y]: function() {}})", output: "doSomething({[y]() {}})", parserOptions: { ecmaVersion: 6 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
         { code: "doSomething({['y']: function() {}})", output: "doSomething({['y']() {}})", parserOptions: { ecmaVersion: 6 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
+        { code: "({ foo: async function () {} })", output: "({ async foo () {} })", parserOptions: { ecmaVersion: 8 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
+        { code: "({ 'foo': async function() {} })", output: "({ async 'foo'() {} })", parserOptions: { ecmaVersion: 8 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
+        { code: "({ [foo]: async function() {} })", output: "({ async [foo]() {} })", parserOptions: { ecmaVersion: 8 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
+        { code: "({ [foo.bar]: function*() {} })", output: "({ *[foo.bar]() {} })", parserOptions: { ecmaVersion: 6 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
```
Comment (vitorbal) [inline tests/lib/rules/object-shorthand.js]: Could you add a test for the case when a generator function has a space before the star as well? Like in your PR overview example:
```js
({ foo: function *() {} });
```

File: tests/lib/rules/object-shorthand.js [hunk 2]
```diff
@@ -144,6 +144,11 @@ ruleTester.run("object-shorthand", rule, {
         { code: "doSomething({y: function() {}})", output: "doSomething({y() {}})", parserOptions: { ecmaVersion: 6 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
         { code: "doSomething({[y]: function() {}})", output: "doSomething({[y]() {}})", parserOptions: { ecmaVersion: 6 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
         { code: "doSomething({['y']: function() {}})", output: "doSomething({['y']() {}})", parserOptions: { ecmaVersion: 6 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
+        { code: "({ foo: async function () {} })", output: "({ async foo () {} })", parserOptions: { ecmaVersion: 8 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
+        { code: "({ 'foo': async function() {} })", output: "({ async 'foo'() {} })", parserOptions: { ecmaVersion: 8 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
+        { code: "({ [foo]: async function() {} })", output: "({ async [foo]() {} })", parserOptions: { ecmaVersion: 8 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
```
Comment (vitorbal) [inline tests/lib/rules/object-shorthand.js]: Just in case, how about an additional test for async **and** spaces inside the square brackets combined:
```js
({ [ foo ]: async function() {} })
```

File: tests/lib/rules/object-shorthand.js [hunk 3]
```diff
@@ -144,6 +144,11 @@ ruleTester.run("object-shorthand", rule, {
...
+        { code: "({ [foo.bar]: function*() {} })", output: "({ *[foo.bar]() {} })", parserOptions: { ecmaVersion: 6 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
+        { code: "({ [foo   ]: function() {} })", output: "({ [foo   ]() {} })", parserOptions: { ecmaVersion: 6 }, errors: [{ message: "Expected method shorthand.", type: "Property" }] },
```
Comment (vitorbal) [inline tests/lib/rules/object-shorthand.js]: I guess I'm being a bit picky (please don't hate me) but could we add a couple more tests, just in case, for when there are spaces only after the opening bracket, and for when there are spaces after the opening and the closing bracket?
```
({ [  foo   ]: function() {} })
({ [  foo]: function() {} })
```

**Comment by not-an-aardvark** [comment]
Updated to add the requested tests.
