### PR TITLE
Fix: Find JSXIdentifier refs in no-unused-vars (fixes #1534)

### LINKED ISSUE #1534: es6jsx: no-unused-vars misses JSX references
I'm using eslint v0.11.0-alpha.0 and getting `no-unused-vars` errors in my JSX template code:

```JavaScript
var React = require('react');

var App = React.createClass({
  render: function() {
    return (
      <div>
        <h1>wat</h1>
      </div>
    );
  }
});

React.render(<App />, document.body);
```

This produces the following errors:

```bash
ಠ_ಠ  ~/code/happytrack λ eslint durp.jsx

durp.jsx
  3:4   error  App is defined but never used                                 no-unused-vars
```

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/6634342-es6jsx-no-unused-vars-misses-jsx-references?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**
Bringing in this fix from the es6jsx branch.

### CODE REVIEW

File: lib/rules/no-unused-vars.js [hunk 1]
```diff
@@ -98,6 +99,21 @@ module.exports = function(context) {
...
             }
+        },
+
+        "JSXIdentifier": function(node) {
+            var scope = context.getScope(),
+                variables = scope.variables,
+                i,
+                len;
+
+            // mark XJSIdentifiers with a special flag
```
Comment (lo1tuma) [inline lib/rules/no-unused-vars.js]: This should be `JSXIdentifiers` instead of `XJSIdentifiers`.

Comment (nzakas) [inline lib/rules/no-unused-vars.js]: Damn out-of-date comments! Thanks.
