### PR TITLE
Fix: `no-*-assgin` rules support destructuring (fixes #3029)

### LINKED ISSUE #3029: `no-ex-assign`, `no-param-reassign`, and `no-native-reassign` are ignoring destructuring.
## test.js

```js
/* eslint no-ex-assign:2, no-param-reassign:2, no-native-reassign:2 */

try {} catch (ex) {
  [ex] = [0];
}

try {} catch ({message}) {
  message = 0;
}

function foo(a) {
  [a] = [0];
}

({Object, String}) = {};

var {Array, Number} = {};
```

## Command & Actual

On `master` branch.

```
> git log -1
commit fd421d43ec11c714fc2c0a97d0db74c054fd4ede
...
> node .\bin\eslint.js test.js --env es6 --no-eslintrc
>
```

No errors.

## Expected

```
test.js
   4:3   error  Do not assign to the exception parameter  no-ex-assign
   8:3   error  Do not assign to the exception parameter  no-ex-assign
  12:3   error  Assignment to function parameter 'a'      no-param-reassign
  15:1   error  Object is a read-only native object       no-native-reassign
  15:9   error  String is a read-only native object       no-native-reassign
  17:5   error  Redefinition of 'Array'                   no-native-reassign
  17:12  error  Redefinition of 'Number'                  no-native-reassign

✖ 5 problems (5 errors, 0 warnings)
```

----

I'm happy to work on this.

### PR DESCRIPTION
**Pull request by mysticatea**
I rewrote `no-*-assign` rules to support destructuring. Target rules are `no-ex-assign`, `no-param-reassign`, `no-native-reassign`, and `no-func-assign` (sorry, I had forgotten in #3029).

Basically those logic are same as `no-const-assign` and `no-class-assign`. In short, it takes variables from every declarations, then checks writing references in `variable.references`.

Note:

- `no-native-reassign` - those don't have its declaration in AST tree, so this rule checks `through` references of the global scope.  All references to implicit global variables are always unresolved.
- `no-func-assign` - if a function declaration is in the global scope, its references are unresolved (by escope's spec). In this case, this rule checks `through` references of the global scope.

Question:

- `no-native-reassign` - this rule checks the redeclaration and the shadowing. Why are not those reported by `no-redeclare` and `no-shadow`?  Variables of built-in objects exist in the global scope.

### CODE REVIEW

**Comment by nzakas** [comment]
> `no-native-reassign` - this rule checks the redeclaration and the shadowing. Why are not those reported by `no-redeclare` and `no-shadow`?  Variables of built-in objects exist in the global scope.

`no-redeclare` looks only at declarations, not assignments. `no-shadow` does the same.

File: lib/rules/no-native-reassign.js [hunk 1]
```diff
@@ -9,37 +9,74 @@
 // Rule Definition
 //------------------------------------------------------------------------------
 
+var NATIVE_OBJECTS = ["Array", "Boolean", "Date", "decodeURI",
```
Comment (nzakas) [inline lib/rules/no-native-reassign.js]: Maybe we should use the `globals` module for this?

Comment (mysticatea) [inline lib/rules/no-native-reassign.js]: Yeah, it's duplicate of #2971, so I will rebase.

**Comment by mysticatea** [comment]
@nzakas 

> no-redeclare looks only at declarations, not assignments. no-shadow does the same.

Yes. But

```js
var Object = 0; // `no-redeclare` does not warn this.

function foo() {
    var Object = 0; // `no-shadow` does not warn this.
}
```

Those patterns are warned by `no-native-reassign`.
I took an interest in reasons of that.

Currently, `no-native-reassign` checks only `VariableDeclaration` to check redeclarations/shadowing, so ignores the following patterns.

```js
import {Map} from "immutable";

function foo(Object) {
}

function Object() {
}

class Object {
}

try { } catch (Object) { }
```

Should I add checking for those?

**Comment by nzakas** [comment]
Ah, i see. It does seem like `no-redeclare` and `no-shadow` should check built-in globals.

Is this rule ready now?

**Comment by mysticatea** [comment]
OK, I will open new issue about `no-redeclare` and `no-shadow`.

Yes, this PR is ready for review.

**Comment by nzakas** [comment]
Lgtm
