### PR TITLE
Fix: consistent-return shouldn't report class constructors (fixes #7790)

### LINKED ISSUE #7790: cocsistent-return reports error in return inside ES6 class constructor
**Tell us about your environment**

ESLint: 3.12.2
Node: v4.6.2
yarn: 0.17.10

**What parser (default, Babel-ESLint, etc.) are you using?**

Babel-ESLint 7.1.1

**Please show your full configuration:**

```
parser: babel-eslint
rules:
  consistent-return: error
```

**What did you do? Please include the actual source code causing the issue.**

```js
class A {
  constructor(b) {
    if (b) {
      return b;
    }
  }
}
```

**What did you expect to happen?**

The return shouldn't be a problem, as it's in a constructor. 

ES5 constructors do not cause a problem:
```js
function F(b) {
  if (b) {
    return b;
  }
}
```

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint reports consistent-return

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (see https://github.com/eslint/eslint/issues/7790)

**What changes did you make? (Give an overview)**

This updates `consistent-return` to avoid reporting inconsistent returns in the `constructor` function of a `ClassExpression` or `ClassDeclaration`. The rule already ignores ES5 constructor functions, but it hadn't been updated to account for ES6 constructors yet.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: lib/rules/consistent-return.js [hunk 1]
```diff
@@ -33,6 +33,18 @@ function isUnreachable(segment) {
...
+* Checks whether a given node is a `constructor` method in an ES6 class
+* @param {ASTNode} node A node to check
+* @returns {boolean} `true` if the node is a `constructor` method
+*/
+function isClassConstructor(node) {
+    return node.type === "FunctionExpression" &&
+        node.parent &&
+        node.parent.type === "MethodDefinition" &&
+        node.parent.kind === "constructor";
+}
```
Comment (platinumazure) [inline lib/rules/consistent-return.js]: Wondering if this should be put in ast-utils as `isES6Constructor` (or `isClassConstructor`?). And maybe they could also export `isConstructor` which tests for both?

Comment (not-an-aardvark) [inline lib/rules/consistent-return.js]: I was searching for what other rules use `astUtils.isES5Constructor` (to see if those uses would also apply to checking for ES6 constructors), but I found that this is the only rule that uses it. Also, the function does not appear to have any tests. I wonder if it would be better to move `isES5Constructor` into `consistent-return` instead.

Comment (vitorbal) [inline lib/rules/consistent-return.js]: @not-an-aardvark I think I would be in favor of that as well.
