### PR TITLE
Fix: no-extra-parens incorrectly reports async function expressions

### LINKED ISSUE #9019: no-extra-parens incorrectly reports async function expressions
**Tell us about your environment**

* **ESLint Version:** 4.3.0
* **Node Version:** 8.2.1
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
parserOptions:
  ecmaVersion: 2017
rules:
  no-extra-parens: error
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
(async function() {})

(async function() {}())
```

**What did you expect to happen?**

I expected no error to be reported, because removing the parentheses results in a syntax error.

**What actually happened? Please include the actual, raw output from ESLint.**

```
1:1  error  Gratuitous parentheses around expression  no-extra-parens
3:1  error  Gratuitous parentheses around expression  no-extra-parens
```

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
(fixes #9019)

**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

**What changes did you make? (Give an overview)**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

File: tests/lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -314,6 +314,10 @@ ruleTester.run("no-extra-parens", rule, {
         { code: "foo + (bar + baz)", options: ["all", { nestedBinaryExpressions: false }] },
         { code: "foo && (bar && baz)", options: ["all", { nestedBinaryExpressions: false }] },
 
+        // https://github.com/eslint/eslint/issues/9019
+        { code: "(async function() {});" },
+        { code: "(async function () { }());" },
+
```
Comment (not-an-aardvark) [inline tests/lib/rules/no-extra-parens.js]: Can you add a test case for the following code?

```js
(async)
```

This should be invalid, since the parentheses are unnecessary. (`async` is used as an identifier here.)

File: lib/rules/no-extra-parens.js [hunk 2]
```diff
@@ -427,7 +427,8 @@ module.exports = {
                         secondToken.value === "function" ||
                         secondToken.value === "class" ||
                         secondToken.value === "let" && astUtils.isOpeningBracketToken(sourceCode.getTokenAfter(secondToken, astUtils.isNotClosingParenToken))
-                    )
+                    ) ||
+                    secondToken.type === "Identifier" && secondToken.value === "async"
```
Comment (not-an-aardvark) [inline lib/rules/no-extra-parens.js]: I think this should also check that the following token is `function`.

File: lib/rules/no-extra-parens.js [hunk 3]
```diff
@@ -418,6 +418,7 @@ module.exports = {
         function checkExpressionOrExportStatement(node) {
             const firstToken = isParenthesised(node) ? sourceCode.getTokenBefore(node) : sourceCode.getFirstToken(node);
             const secondToken = sourceCode.getTokenAfter(firstToken, astUtils.isNotOpeningParenToken);
+            const thirdToken = secondToken ? sourceCode.getTokenAfter(secondToken) : {};
```
Comment (not-an-aardvark) [inline lib/rules/no-extra-parens.js]: Nitpick: Instead of defaulting the token to an empty object, can you add  a null check to the conditional?

```js
/* ... */ && thirdToken && thirdToken.type === "Keyword" && /* ... */
```

I'm worried it would be confusing for a variable to sometimes reference a `Token` and sometimes reference an empty object.

**Comment by not-an-aardvark** [comment]
Looks like there are some merge conflicts here from https://github.com/eslint/eslint/commit/7ecfe6ad9d9024a6da248107e01a8027ff4e14dc.

**Comment by Aladdin-ADD** [comment]
@not-an-aardvark resolved.

**Comment by not-an-aardvark** [comment]
Thanks for contributing!
