### PR TITLE
Fix: Ensure **/node_modules works in ignore files (fixes #3788)

### LINKED ISSUE #3788: eslint 1.4 does not ignore patterns like "**/node_modules"
Hello,

My .gitignore file contains patterns like **/node_modules. eslint uses the .gitignore file (instead of the .eslintignore). It used to work but it stopped working after I upgraded from eslint 1.3 to 1.4. Now it returns error about files which are in the node_modules.

eslint = 1.4.1
.gitignore = **/node_modules
command = eslint  --quiet --ignore-path .gitignore

Thanks

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

**Comment by nzakas** [comment]
Oops, embeded `node_modules` was automatically ignored by git. Need to change up the test.

File: lib/cli-engine.js [hunk 1]
```diff
@@ -573,7 +572,9 @@ CLIEngine.prototype = {
             if (shell.test("-f", pattern) && !ignoredPaths.contains(pattern)) {
                 executeOnFile(pattern);
             } else {
-                glob.sync(pattern, globOptions).forEach(executeOnFile);
+                glob.sync(pattern, globOptions).filter(function(filename) {
+                    return !ignoredPaths.contains(filename);
```
Comment (BYK) [inline lib/cli-engine.js]: Looks like we should put the ignore check in `executeOnFile` at this point.

Also this may have a bad impact on performance. That's why I was trying to use the `ignore` option for `glob`. Is it completely broken?

Comment (nzakas) [inline lib/cli-engine.js]: It shouldn't affect performance in any demonstrative way. We're moving from O(n) to O(2n), which isn't that big of a deal.

Agree, though, better to move this into `executeFile()`.
