### PR TITLE
Fix: `space-before-keywords` had been wrong on getters

### LINKED ISSUE #3854: space-before-keyword matches getters
After updating from ESLint 1.4.3 to 1.5.0 I noticed the `space-before-keywords` rule with configuration `always` matches getters and setters.

```js
return {
  get prop() {  <-- reports: Missing space before keyword "(".
    return prop;
  }
};
```

This conflicts with `space-before-function-paren` set to `never`.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26802582-space-before-keyword-matches-getters?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #3854.
I made `space-before-keywords` ignoring methods, getters, and setters.

### CODE REVIEW

File: tests/lib/rules/space-before-keywords.js [hunk 1]
```diff
@@ -142,6 +139,13 @@ ruleTester.run("space-before-keywords", rule, {
         { code: "var foo =\nfunction bar () {}", options: never },
         { code: "function foo () { return function () {} }", options: never },
         { code: "var foo = { foo:function () {} }", options: never },
+        { code: "var foo = {bar() {}}", ecmaFeatures: { objectLiteralShorthandMethods: true } },
+        { code: "var foo = { bar() {} }", ecmaFeatures: { objectLiteralShorthandMethods: true }, options: never },
+        { code: "var foo = {\nbar() {}}", ecmaFeatures: { objectLiteralShorthandMethods: true }, options: never },
+        { code: "var foo = {get bar() {}}", ecmaFeatures: { objectLiteralShorthandMethods: true } },
```
Comment (michaelficarra) [inline tests/lib/rules/space-before-keywords.js]: `objectLiteralShorthandMethods` is not needed for getters and setters.

Comment (mysticatea) [inline tests/lib/rules/space-before-keywords.js]: Oh!

Comment (mysticatea) [inline tests/lib/rules/space-before-keywords.js]: Thank you @michaelficarra

**Comment by nzakas** [comment]
LGTM. Can you rebase?

**Comment by mysticatea** [comment]
I rebased.

The process for `FunctionExpression` was changed in #3850.
But the new process is checking `Identifier` (not keywords), so I overwrite that part with this PR.
