### PR TITLE
Update: fix uglified align in key-spacing (fixes #11414)

### LINKED ISSUE #11414: key-spacing + align: 'value' + jsx objects becomes ugly sometimes
screenshot 2019-02-19 at 18 51 23

image

**👀 Look at the repo with minimal reproducible example (dependencies, config, source):** https://github.com/a-x-/eslint-align-check

<br/><br/>

----

<br/><br/>

**environment**

* **ESLint Version:** latest (5.13.0)
* **Node Version:** latest (11.9.0)
* **npm Version:** latest (6.8.0)

**parser**: Babel-ESLint 

**minimal configuration:** (full config has no sense never : )

```js
{
  "plugins": [
    "react",
  ],
  "rules": {
    "key-spacing": ["warn", {
      "multiLine": {"align": "value"},
    }],
    // some related a bit rules
    "object-curly-newline": ["warn", { "multiline": true, "minProperties": 5 }],
    "object-property-newline": ["warn", {"allowAllPropertiesOnSameLine": true }],
    "object-curly-spacing": ["warn", "always", {
      "arraysInObjects": false,
      "objectsInObjects": false,
    }],
    // ...
  },
}
```

**source and command**

<details><summary>source before eslint --fix ran</summary>

```jsx
function Component () {
      return <div>
        <span style={{ display: 'inline-block', marginRight: '10px' }}>
          <Fa
            icon={ d.icon }
            style={{ marginRight: '4px', color: '#0C090A', opacity: '0.6', fontSize: '18px', verticalAlign: 'middle' }}
          />
          <span style={{ verticalAlign: 'bottom' }}>{ d.title }</span>
        </span>
        <span>
          <Fa
            icon="location-arrow"
            style={{ marginRight: '4px', color: '#0C090A', opacity: '0.6', fontSize: '18px', verticalAlign: 'middle' }}
          />
          <span style={{ verticalAlign: 'bottom' }}>{ this.state.info?.device.app_version }</span>
          <br />
          <span style={{ color: '#999999' }} title="Когда последний раз делал что-то в приложении">
            { this.state.info?.device.last_request_at }
          </span>
        </span>
      </div>;
}
```

</details>

```bash
eslint --fix file.jsx
```

**Expected:** don't re-align objects in jsx curlies.

**PR?** I'm not sure, maybe I can.

### PR DESCRIPTION
**Pull request by yeonjuan**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Count properties on a line as a single line.
I think this PR can fix #11414 

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by yeonjuan** [comment]
@kaicataldo I added more test cases for other options. thanks!

File: tests/lib/rules/key-spacing.js [hunk 1]
```diff
@@ -1769,5 +1977,218 @@ ruleTester.run("key-spacing", rule, {
...
+        output: [
+            "({",
+            "    foo: 1, bar: 2, baz: 3",
+            "});"
+        ].join("\n"),
+        options: [{
+            beforeColon: false
+        }],
+        errors: [
+            { messageId: "extraKey", data: { computed: "", key: "foo" }, line: 2, column: 5, type: "Identifier" },
```
Comment (aladdin-add) [inline tests/lib/rules/key-spacing.js]: unrelated: it would be better to refactor the messageIds to `"extraKey" || "extraComputedKey"`, rather than passing `data: {"computed": ""}`

**Comment by ibc** [comment]
So this change is producing this (IMHO unexpected) behavior:

https://github.com/eslint/eslint/issues/12597
