### PR TITLE
Fix: no-implicit-coercion string concat false positive (fixes #7057)

### LINKED ISSUE #7057: no-implicit-conversion should not warn on "" + "foo"
**What version of ESLint are you using?**
3.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
Running the test suite

**What did you do? Please include the actual source code causing the issue.**
I added a test that the following should be valid:

```
{code: "1 * 1"},
{code: "'' + 'foo'"},
```

and ran 

```
./node_modules/.bin/mocha /Users/eli/projects/eslint/tests/lib/rules/no-implicit-coercion.js
```

**What did you expect to happen?**
I expected these to be valid

**What actually happened? Please include the actual, raw output from ESLint.**
eslint was fine with `1 * 1` but not with `"" + "foo"`. 

While both of these aren't very good patterns for people to be following, there is nothing happening with type conversion here and thus `no-implicit-conversion` should not care about these cases.

### PR DESCRIPTION
**Pull request by kaicataldo**
The rule was checking that the `Literal` is not a number in the case of `+foo` (so it would not warn for `+42`), but was not doing the same for strings.

### CODE REVIEW

**Comment by TheSavior** [comment]
Thanks for doing this!

File: lib/rules/no-implicit-coercion.js [hunk 1]
```diff
@@ -106,14 +106,34 @@ function getNonNumericOperand(node) {
 }
 
 /**
+ * Checks whether a node is a string literal or not.
+ * @param {ASTNode} node The node to check.
+ * @returns {boolean} Whether or not the passed in node is a
+ * string literal or not.
+ */
+function isString(node) {
+    return node.type === "Literal" && typeof node.value === "string";
```
Comment (platinumazure) [inline lib/rules/no-implicit-coercion.js]: Consider using [`isStringLiteral` from ast-utils](https://github.com/eslint/eslint/blob/master/lib/ast-utils.js#L229)? (One significant difference, that function also checks for TemplateLiterals. I think that might be okay here, though.)

File: tests/lib/rules/no-implicit-coercion.js [hunk 2]
```diff
@@ -64,6 +64,10 @@ ruleTester.run("no-implicit-coercion", rule, {
         {code: "0 + foo"},
         {code: "~foo.bar()"},
 
+        // https://github.com/eslint/eslint/issues/7057
+        {code: "'' + 'foo'"},
+        {code: "+42"},
```
Comment (platinumazure) [inline tests/lib/rules/no-implicit-coercion.js]: Could you add a valid test for `"str += "non-empty"`? I didn't see it in the test file but you did change `isAppendEmptyString`. Thanks!

**Comment by platinumazure** [comment]
Left a suggestion about using an ast-utils method and adding a test.

In addition: If you do follow my suggestion and use ast-utils' `isStringLiteral` method, since that also allows TemplateLiteral nodes, could you add some representative tests that use template strings in place of strings in existing valid/invalid tests?

Thanks, otherwise looks great!

File: lib/rules/no-implicit-coercion.js (hunk 1 above)
Comment (kaicataldo) [inline lib/rules/no-implicit-coercion.js]: Oh cool! Didn't know about this - thanks!

**Comment by kaicataldo** [comment]
Updated with suggested changes - thanks!

**Comment by platinumazure** [comment]
Thanks @kaicataldo!

I was originally thinking of tests like this:

```js
foo + ``;
`` + foo;
```

Maybe I'm missing something-- are empty TemplateLiterals syntactically invalid?

**Comment by kaicataldo** [comment]
This is something that the rule does not currently check - do we want to lump that change into this bug fix?

**Comment by kaicataldo** [comment]
Updated - this has become a sort of enhancement in addition to the bug fix, in that it is now updated to work with ES6 `TemplateLiterals`. I'm fine with doing the bug fix and enhancement in the same PR, but would like to make sure others are okay with it too since it wasn't discussed in the issue.

**Comment by platinumazure** [comment]
Sorry, I didn't realize templates weren't flagged by this!

**Comment by kaicataldo** [comment]
Seems like a worthwhile update (I think this rule was written before ES6), just want to make sure it doesn't accidentally get snuck in without consideration :)

Happy to split this up into two PR's if we decide we want to keep it separate.

**Comment by TheSavior** [comment]
It seems like the easier and less controversial approach would be to split this into two PRs.

**Comment by platinumazure** [comment]
@kaicataldo Sorry, this came up because I wanted you to use ast-utils. :smile: If you want to revert that change so this PR remains a bugfix, please go ahead. I'll write an enhancement request issue for enforcing on template literals as well.

**Comment by kaicataldo** [comment]
No need to apologize :)

Alright, let's split this up. Will revert to the original PR and we can discuss adding support for template strings in a separate issue.

**Comment by kaicataldo** [comment]
Reverted to just the original bug fix (but still using `ast-utils.isStringLiteral()` - I still would prefer to use the built-in utility function with an extra guard than re-implement). I checked out a new branch with the `TemplateLiteral` check and tests, so if we decide to implement that it'll be quite simple!

**Comment by kaicataldo** [comment]
@platinumazure How does this look now? Want to make sure I get your feedback since you commented on the original iteration!

**Comment by platinumazure** [comment]
LGTM, thanks!

**Comment by vitorbal** [comment]
LGTM

**Comment by ilyavolodin** [comment]
LGTM. Thanks
