### PR TITLE
Fix: newline-before-return handles return as first token (fixes #5816)

### LINKED ISSUE #5816: newline-before-return throws exception if `return` is first token in file
**What version of ESLint are you using?**

2.7.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

(Note: This is a config based off of the shell command I wrote below.)

```json
{
    "env": {
        "node": true
    },
    "rules": {
        "newline-before-return": 2
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

```shell
$ echo "return;" | eslint --stdin --env node --no-eslintrc --rule "newline-before-return: 2"
```

**What did you expect to happen?**

No error (newline-before-return is written to detect that the statement is the first statement in its block and will forbid newlines in that case).

**What actually happened? Please include the actual, raw output from ESLint.**

```shell
Cannot read property 'loc' of undefined
TypeError: Cannot read property 'loc' of undefined
    at hasNewlineBefore (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\rules\newline-before-return.js:105:45)
    at EventEmitter.ReturnStatement (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\rules\newline-before-return.js:134:38)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:609:23)
    at CommentEventGenerator.enterNode (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\util\comment-event-generator.js:99:23)
    at Controller.traverser.traverse.enter (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\eslint.js:887:36)
    at Controller.__execute (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\node_modules\estraverse\estraverse.js:501:28)
```

---

The issue appears to be that in `hasNewlineBefore()` method, there is no defensive check around the existence of a token before the return statement. Presumably if there is no token before, then the "line number of the previous token" should be 1 (in a 1-based index).

### PR DESCRIPTION
**Pull request by platinumazure**
Issue isn't accepted yet, but I wanted to put something together while it was still fresh in my mind.

My assumption is that there's no need to call this out in the rule documentation. Please let me know if I should.

### CODE REVIEW

File: lib/rules/newline-before-return.js [hunk 1]
```diff
@@ -101,10 +102,18 @@ module.exports = function(context) {
...
-        var commentLines = calcCommentLines(node, tokenBefore);
+        var tokenBefore = sourceCode.getTokenBefore(node),
+            lineNumNode = node.loc.start.line,
+            lineNumTokenBefore,
+            commentLines;
+
+        if (tokenBefore) {
+            lineNumTokenBefore = tokenBefore.loc.end.line;
+        } else {
+            lineNumTokenBefore = 1;     // assume start of file
```
Comment (kaicataldo) [inline lib/rules/newline-before-return.js]: Two things: 

1) I don't think this check needs to happen twice. You could also just pass `lineNumTokenBefore` to the `calcCommentLines` function.

2) More importantly, I think `lineNumTokenBefore = 1` is the wrong assumed value if we have encounter a global `return`. It leads to these cases passing (which they shouldn't, given the current intention of the rule):
```js

// comment
return;
```
and
```js

return;
```

**Comment by kaicataldo** [comment]
Thanks for working on this, and good find with the issue! I quickly made a branch to illustrate the kinds of changes I'd like to see to fix this (because I know this code - only took a sec): https://github.com/eslint/eslint/commit/d13adb19fd44be1d4ccf8a7322a054e744d1d47d

File: tests/lib/rules/newline-before-return.js [hunk 2]
```diff
@@ -78,7 +78,23 @@ ruleTester.run("newline-before-return", rule, {
...
+        {
+            code: "var a;\n\nreturn;",
+            parserOptions: { ecmaFeatures: { globalReturn: true } }
+        },
+        {
+            code: "/* comment */\nreturn;",
+            parserOptions: { ecmaFeatures: { globalReturn: true } }
+        },
+        {
+            code: "\nreturn;",
```
Comment (kaicataldo) [inline tests/lib/rules/newline-before-return.js]: This actually should be invalid

**Comment by platinumazure** [comment]
I'll incorporate those changes tomorrow and we'll see how it looks.

**Comment by platinumazure** [comment]
@kaicataldo Thanks for your feedback. I've just pushed an update with your recommendations, as I understand them.

I realize now where I went wrong: I didn't like that the return statements are assumed to be on the next line after a multi-line comment (sometimes the comment is long and stands on its own, so that the return could still use a newline before it). However, that would more properly be handled as an enhancement request, so I will make a separate issue for that later. For this fix, consistent behavior (and, of course, no longer throwing) is much more important.

Please let me know if I have missed something.

**Comment by kaicataldo** [comment]
@platinumazure Awesome, this looks great to me! Only thing missing in my opinion is a test for a valid multiline comment. Otherwise, LGTM. @eslint/eslint-team Any other thoughts?

**Comment by kaicataldo** [comment]
Ah, and yeah, let's focus on fixing the bug with the currently accepted behavior. You should definitely make a new issue for an enhancement if you think the rule could be improved, though :+1:

**Comment by platinumazure** [comment]
Added the requested test case, your thoughts?

File: lib/rules/newline-before-return.js [hunk 3]
```diff
@@ -101,10 +101,18 @@ module.exports = function(context) {
...
-        var commentLines = calcCommentLines(node, tokenBefore);
+        var tokenBefore = sourceCode.getTokenBefore(node),
+            lineNumNode = node.loc.start.line,
+            lineNumTokenBefore,
+            commentLines;
+
+        if (tokenBefore) {
+            lineNumTokenBefore = tokenBefore.loc.end.line;
+        } else {
+            lineNumTokenBefore = 0;     // assume "just before" start of file
```
Comment (kaicataldo) [inline lib/rules/newline-before-return.js]: Nitpick (sorry, missed this on my first pass): First off, this shouldn't be a blocker for landing this. 

This comment might be a little confusing to the next person who's coming in without any context. Please let me know if you disagree, but in my mind the reason the default is `0` is two-fold: 

 - It allows us to accurately calculate the difference on line 117 (if there is no previous token, setting it to `0` makes sense because we're not subtracting any value for the nonexistent line number).
 - Since a comment can't be on line 0, `if (comment.loc.start.line === lineNumTokenBefore)` is correct.

So in my mine the `0` is not really an assumption of the location of anything, but the correct value for a nonexistent value when we do the required arithmetic for the rule.

I wonder if the comment is necessary at all? Again, very nitpicky and this shouldn't block this from being merged - just a thought. Thanks for bearing with me :)

**Comment by kaicataldo** [comment]
LGTM. Great work here!

File: lib/rules/newline-before-return.js (hunk 3 above)
Comment (platinumazure) [inline lib/rules/newline-before-return.js]: @kaicataldo To be honest, I wrote that comment because it helped me visualize what we were trying to go for here (I say this knowing that you and I seem to understand the rule a bit differently).

For me, it helped to understand the rules for global return by imagining a "line 0" with a block opening on it, and then we start counting intervening lines after line 0:

```js
// imaginary line 0: {
/* file comment header */
return;
// imaginary closing block I guess
```

But I admit that comment might not be useful to others.

Comment (kaicataldo) [inline lib/rules/newline-before-return.js]: Gotcha! Agreed, sounds like we just visualize what's going on differently. This isn't a blocker for me as far as landing this goes - thanks for explaining!

Comment (nzakas) [inline lib/rules/newline-before-return.js]: Agree with @kaicataldo that this comment is unclear without a lot of context. It would help to have a larger comment before the `if` block explaining that global `return` is a special case where we consider the previous line to be 0 so the rest of the functionality works correctly.

Comment (platinumazure) [inline lib/rules/newline-before-return.js]: @nzakas Sure, I can do that. Thanks for the feedback.

**Comment by platinumazure** [comment]
I just have one more piece of feedback to incorporate (which I will try to do tonight, US time). Hopefully this can be merged tonight or tomorrow. Thanks for your patience.

**Comment by platinumazure** [comment]
@nzakas @kaicaltado I've pushed a new commit with a comment that should hopefully work. I'm investigating the Travis build failure now.

**Comment by nzakas** [comment]
Lgtm. Thanks!
