### PR TITLE
Fix: no-multiple-empty-lines fails when empty line at EOF (fixes #4214)

### LINKED ISSUE #4214: Bug: no-multiple-empty-lines ignores failures when there is a single empty line at EOF
I introduced a bug in #4208 

Now when there is a single empty line at the end of the file, no errors are reported.

This should be invalid but it is not:
```js
var a=5;\n\n\n\nvar b = 3;\n
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27564715-bug-no-multiple-empty-lines-ignores-failures-when-there-is-a-single-empty-line-at-eof?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alberto**

### CODE REVIEW

File: tests/lib/rules/no-multiple-empty-lines.js [hunk 1]
```diff
@@ -82,7 +82,7 @@ ruleTester.run("no-multiple-empty-lines", rule, {
             options: ruleArgs
         },
         {
-            code: "// invalid 3\nvar a=5;\n\n\n\nvar b = 3;",
+            code: "// invalid 3\nvar a=5;\n\n\n\nvar b = 3;\n",
```
Comment (nzakas) [inline tests/lib/rules/no-multiple-empty-lines.js]: This doesn't seem correct - you changed the code but the expected error is the same? It would be better to leave existing tests alone and add a new test that explicitly shows the problem.

Comment (alberto) [inline tests/lib/rules/no-multiple-empty-lines.js]: Ok, I'll duplicate the test.

Comment (alberto) [inline tests/lib/rules/no-multiple-empty-lines.js]: Just for clarification, with the added empty line, the code was not detected as invalid anymore.

**Comment by nzakas** [comment]
LGTM
