### PR TITLE
Fix: Check division operator in astUtils.canTokensBeAdjacent

### LINKED ISSUE #12291: astUtils.canTokensBeAdjacent hardcoded espree.tokenize
**Tell us about your environment**

* **ESLint Version:**  6.4.0
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 2020,
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/* eslint no-implicit-coercion:error */

let x ="" + 1n;
```

```bash
eslint index.js
```

**What did you expect to happen?**

```js
let x =String(1n);
```

**What actually happened? Please include the actual, raw output from ESLint.**

`SyntaxError: Identifier directly after number` at `Espree.raise ... canTokensBeAdjacent`.

**Problem**

`astUtils.canTokensBeAdjacent` can accept a `string` value, which is useful when fixer adds some new code. But, it's using hardcoded `espree.tokenize` with `ecmaVersion: 2015`.

The same problem occurs with the following code when `babel-eslint` is used:

```js
/* eslint no-implicit-coercion:error */

class Foo {
  #a = 0;
  bar() {
    let x ="" + this.#a;
  }
}
```

**Are you willing to submit a pull request to fix this bug?**

Yes, but I'm not sure what would be the best approach. Whether to use the configured parser and configured options, or to somehow avoid this feature e.g., pass a token-like object instead of a string (that would require a change in 4-5 rules though).

### PR DESCRIPTION
**Pull request by mdjermanovic**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Bug fix

**Tell us about your environment**

* **ESLint Version:** 7.0.0-alpha.0
* **Node Version:** v12.14.0
* **npm Version:** v6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    parserOptions: {
        ecmaVersion: 2015
    },
};
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
/* eslint no-extra-parens: ["error"] */
/* eslint operator-assignment: ["error", "never"] */

a/(/**/b);

a/(//
  b);

a/(/regex/);

a/=/**/b;
```

[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dHJhLXBhcmVuczogW1wiZXJyb3JcIl0gKi9cbi8qIGVzbGludCBvcGVyYXRvci1hc3NpZ25tZW50OiBbXCJlcnJvclwiLCBcIm5ldmVyXCJdICovXG5cbmEvKC8qKi9iKTtcblxuYS8oLy9cbiAgYik7XG5cbmEvKC9yZWdleC8pO1xuXG5hLz0vKiovYjsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=) (v6.8.0 actual)

**What did you expect to happen?**

4 errors and auto-fix that would not comment out some code.

**What actually happened? Please include the actual, raw output from ESLint.**

4 errors and auto-fix to:

```js
/* eslint no-extra-parens: ["error"] */
/* eslint operator-assignment: ["error", "never"] */

a//**/b;

a///
  b;

a//regex/;

a= a//**/b;
```

In all 4 lines `/` becomes start of a line comment.

#### What changes did you make? (Give an overview)

* Fixed `astUtils.canTokensBeAdjacent` to account for the `/` operator on the left side and block comment, line comment or regex on the right side.
* Fixed `no-extra-parens` and `operator-assignment` rules to get and pass possible comment tokens as well.
* Since there are now rules that can pass comment tokens to `astUtils.canTokensBeAdjacent`, had to also add the logic for comments (I believe they can be adjacent with everything except for `/` on the left side).
* Fixed part of the code in `astUtils.canTokensBeAdjacent` that deals with string input (using `espree.tokenize`) to handle comments as well. I don't think this will affect the rules that are using this feature at the moment, but it should be a correct change and it also allowed testing this function with comments (all tests actually pass strings, maybe we should add some tests with tokens at some point since it's the most common case).
* Also upgraded `espree` in order to pass `espree.latestEcmaVersion` instead of a hard-coded version to `espree.tokenize()`, and added `try-catch` around `espree.tokenize()`. This should fix partially or entirely #12291 (edited to prevent auto-closing #12291),

#### Is there anything you'd like reviewers to focus on?

* Is this the correct way to get comments from `espree.tokenize`?

This can also happen in `operator-linebreak` in some edge cases. That rule has its own code to handle adjacent tokens, I'll see if it is possible to switch to `astUtils.canTokensBeAdjacent` (or fix the same issue there if it isn't) in a follow-up PR.

Marked as accepted since it's an obvious autofix bug.

### CODE REVIEW

File: lib/rules/utils/ast-utils.js [hunk 1]
```diff
@@ -1357,17 +1357,43 @@ module.exports = {
      * next to each other, behavior is undefined (although it should return `true` in most cases).
      */
     canTokensBeAdjacent(leftValue, rightValue) {
+        const espreeOptions = { ecmaVersion: 2020, comment: true, range: true };
+
         let leftToken;
 
         if (typeof leftValue === "string") {
-            const leftTokens = espree.tokenize(leftValue, { ecmaVersion: 2015 });
+            const tokens = espree.tokenize(leftValue, espreeOptions);
```
Comment (kaicataldo) [inline lib/rules/utils/ast-utils.js]: Do you mind adding a test for when a `Shebang` comment token is given as the left value? I don't think this could ever be a real world use case (since another token can't be on the same line as the shebang), but I do think we should make sure that this won't crash the process.

For reference, we mutate the text input to make the shebang a regular JS line comment before we parse in [`lib/linter/linter.js`](https://github.com/eslint/eslint/blob/master/lib/linter/linter.js#L632).

Comment (mdjermanovic) [reply lib/rules/utils/ast-utils.js]: You're right, that would crash! Maybe we could already add `try-catch` as suggested in [#12291 (comment)](https://github.com/eslint/eslint/issues/12291#issuecomment-552086069) and also close #12291 with this PR?

Comment (mdjermanovic) [reply lib/rules/utils/ast-utils.js]: `canTokensBeAdjacent` also didn't assume it could get a code (as a string argument) without any tokens, so it doesn't support a comment-only code. This isn't changed with this PR, it would still crash, so it isn't possible to call it with e.g.,:

```js
astUtils.canTokensBeAdjacent(someToken, "/* comment */");
```

Then, it might also make sense to support empty code as well, and maybe even to account for spaces at the start/end of the code (e.g., `canTokensBeAdjacent("a ", "b")` would return `true`).

Maybe we could do that as well in this PR?

Comment (kaicataldo) [reply lib/rules/utils/ast-utils.js]: That sounds good to me! I guess another option (or something we could do additionally) is just do is short circuit it and add an early return of `false` if the left value token is of type `Shebang`. That would save the process from having to run the parse at all.

Comment (mdjermanovic) [reply lib/rules/utils/ast-utils.js]: > That sounds good to me! I guess another option (or something we could do additionally) is to short circuit it and add an early return of `false` if the left value token is of type `Shebang`. That would save the process from having to run the tokenizing at all.

Maybe I didn't understand, but I think it isn't possible to check if the token is `Shebang` before tokenizing, because we don't have the token yet?

**Comment by kaicataldo** [comment]
Sorry, meant to submit those two comments yesterday.

File: lib/rules/utils/ast-utils.js (hunk 1 above)
Comment (kaicataldo) [reply lib/rules/utils/ast-utils.js]: Oh, I see, I missed that it could be a string or a token. Yes, if the left value is a string that won't work. I think the approach you sounds good :+1:

File: lib/rules/utils/ast-utils.js [hunk 2]
```diff
@@ -1357,17 +1357,43 @@ module.exports = {
      * next to each other, behavior is undefined (although it should return `true` in most cases).
      */
     canTokensBeAdjacent(leftValue, rightValue) {
+        const espreeOptions = { ecmaVersion: 2020, comment: true, range: true };
```
[the remark this answers is not in the document]
Comment (mdjermanovic) [reply lib/rules/utils/ast-utils.js]: That would be great! But, I'm not sure if there is a way to do that at the moment? Does `espree` support something like "latest" or provides a list of available versions?

[the remark this answers is not in the document]
Comment (aladdin-add) [reply lib/rules/utils/ast-utils.js]: v/_ \ I don't think `espree` has such a thing.

**Comment by mdjermanovic** [comment]
> Since this is already an improvement over the existing code, I would be fine with splitting these bug fixes over multiple PRs to keep them manageable. What do you think?

Agreed! Just added `try-catch` and explicit check for `Shebang` (test with the "token" returns `false` because of the condition, test with the string return `false` on tokenizing).

This PR is now ready for review since it fixes some issues and (I believe) doesn't add any new ones.

File: lib/rules/utils/ast-utils.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (kaicataldo) [reply lib/rules/utils/ast-utils.js]: It doesn’t, no! Definitely not a blocker for this - just an idea I had and wanted to write down for posterity 😄

[the remark this answers is not in the document]
Comment (mdjermanovic) [reply lib/rules/utils/ast-utils.js]: A list of all versions could be also useful for the online demo, it's hard-coded there and has to be updated manually.

[the remark this answers is not in the document]
Comment (kaicataldo) [reply lib/rules/utils/ast-utils.js]: PR here: https://github.com/eslint/espree/pull/430

**Comment by nzakas** [comment]
What are next steps here? Are we waiting for the Espree change?

**Comment by kaicataldo** [comment]
I can run an Espree release tomorrow as well. It would be good to get the updated API in before we run the next major release with https://github.com/eslint/espree/pull/429.

**Comment by mdjermanovic** [comment]
If it would be easier for reviewing, I can add a note in #12291 and update `canTokensBeAdjacent` with the new Espree interface in another PR when the new Espree version gets published.

**Comment by kaicataldo** [comment]
espree@6.2.0 has been released. [`latestEcmaVersion`](https://github.com/eslint/espree/pull/430) is now available for this PR!

**Comment by mdjermanovic** [comment]
> espree@6.2.0 has been released. [`latestEcmaVersion`](https://github.com/eslint/espree/pull/430) is now available for this PR!

Done!
