### PR TITLE
Fix: ignore return statements in dead code (fixes #11647)

### LINKED ISSUE #11647: `no-useless-return` removes return statements in unreachable code
**Tell us about your environment**

* **ESLint Version:** v5.16.0 (via the ESLint.org/demo website)
* **Node Version:** ESLint.org/demo website
* **npm Version:** ESLint.org/demo website

**What parser (default, Babel-ESLint, etc.) are you using?**

ESLint.org/demo default

**Please show your full configuration:**

[This eslint.org/demo configuration](https://eslint.org/demo/#eyJ0ZXh0IjoiZnVuY3Rpb24gZm9vKGFyZykge1xuICB0aHJvdyBuZXcgRXJyb3IoXCJEZWJ1Z2dpbmcuLi5cIik7XG5cbiAgaWYgKCFhcmcpIHtcbiAgICByZXR1cm47XG4gIH1cblxuICBjb25zb2xlLmxvZyhhcmcpO1xufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby11c2VsZXNzLXJldHVybiI6Mn0sImVudiI6e319fQ==) (configured with just the `no-useless-return` rule)

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
function foo(arg) {
  throw new Error("Debugging...");

  if (!arg) {
    return; // < This return incorrectly gets removed by auto-fix
  }

  console.log(arg);
}
```

Using eslint.org/demo link above

I added a `throw` statement to the top of my function to aid debugging, and the critical return statement from later in the code was dropped which I only discovered after removing the `throw` statement and strange errors occurring.

**What did you expect to happen?**

`return;` statement should be flagged in unreachable code if and only if it would be flagged in equivalent reachable code. (At least that's how I read [the comment in the source code](https://github.com/eslint/eslint/blob/8684f4646da33bfe81e8f7f8c2d1af8b31065564/lib/rules/no-useless-return.js#L102-L108).)

If we were to remove the `throw` line, the `return;` statement would not be flagged; therefore it should not be flagged with the `throw` statement present.

**What actually happened? Please include the actual, raw output from ESLint.**

`5:5 Unnecessary return statement.` and fixed code removes the `return` statement. (See eslint.org/demo link)

**Are you willing to submit a pull request to fix this bug?**

This is currently beyond my ESLint skillset.

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix #11647

**What changes did you make? (Give an overview)**

This PR fixes `no-useless-return` rule to ignore `return` statements in unreachable code.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: tests/lib/rules/no-useless-return.js [hunk 1]
```diff
@@ -418,11 +429,7 @@ ruleTester.run("no-useless-return", rule, {
         },
         {
             code: "function foo() { return; return; }",
-            output: "function foo() {  return; }", // Other case is fixed in the second pass.
-            errors: [
-                { message: "Unnecessary return statement.", type: "ReturnStatement" },
-                { message: "Unnecessary return statement.", type: "ReturnStatement" }
```
Comment (mysticatea) [inline tests/lib/rules/no-useless-return.js]: The rule now ignores unreachable code, so the second `return;` is just ignored.

File: tests/lib/rules/no-useless-return.js [hunk 2]
```diff
@@ -418,11 +429,7 @@ ruleTester.run("no-useless-return", rule, {
...
-            ]
+            output: "function foo() {  return; }"
```
Comment (platinumazure) [inline tests/lib/rules/no-useless-return.js]: I think it would be good to have an `errors` object showing 1 error, and use the column option to show that the first `return` is the one flagged.

**Comment by mysticatea** [comment]
Thank you for the review!

I added the `column` option to the last test case.
