### PR TITLE
Fix: valid-jsdoc does not throw on FieldType without value (fixes #7184)

### LINKED ISSUE #7184: valid-jsdoc crashes with a TypeError when given an invalid parameter type
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 6.6.0
* **npm Version:** 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```json
{
  "rules": {
    "valid-jsdoc": [2, {"preferType": {"foo": "bar"}}]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
/**
* @param {{gibberish}} bar - the parameter
*/
function foo(bar) { }
```

**What did you expect to happen?**

I expected ESLint to either report a JSDoc issue or exit without reporting an error.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint threw a TypeError:

```
TypeError: Cannot read property 'name' of null
    at getCurrentExpectedTypes (path/to/eslint/lib/rules/valid-jsdoc.js:153:21)
    at validateType (path/to/eslint/lib/rules/valid-jsdoc.js:195:39)
    at Array.forEach (native)
    at validateType (path/to/eslint/lib/rules/valid-jsdoc.js:201:22)
    at path/to/eslint/lib/rules/valid-jsdoc.js:330:25
    at Array.forEach (native)
    at EventEmitter.checkJSDoc (path/to/eslint/lib/rules/valid-jsdoc.js:255:28)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.leaveNode (path/to/eslint/lib/util/node-event-generator.js:49:22)
```

### PR DESCRIPTION
**Pull request by kaicataldo**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- [x] I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**
`valid-jsdoc` currently throws a `TypeError` when it encounters a `FieldType` that contains a key with a missing value. This is because `type.value` is actually `null` for `FieldType`s that have a key but no value (here's the [relevant code from Doctrine](https://github.com/eslint/doctrine/blob/12c7ad9d610a7f185bdbce7f6acf4b6c9a5c768b/lib/typed.js#L598-L601)).

Both [Doctrine](https://github.com/eslint/doctrine/blob/12c7ad9d610a7f185bdbce7f6acf4b6c9a5c768b/lib/typed.js#L577-L579) and the [JSDoc documentation](http://usejsdoc.org/tags-type.html) seem to indicate that this is valid.

From the JSDoc documentation:
>An object called 'myObj' with properties 'a' (a number), 'b' (a string) and 'c' (any type).
`{{a: number, b: string, c}} myObj`.

This change makes it so that the rule only validates the values of `FieldType`s with values (it should never check the key, as those are the property names, not types).

**Is there anything you'd like reviewers to focus on?**
Want to make sure my interpretation of the JSDoc documentation is correct :)

### CODE REVIEW

File: lib/rules/valid-jsdoc.js [hunk 1]
```diff
@@ -165,7 +165,7 @@ module.exports = {
         }
 
         /**
-         * Check if return tag type is void or undefined
+         * Validate type for a given JSDoc node
```
Comment (kaicataldo) [inline lib/rules/valid-jsdoc.js]: Copy paste error from line 121

File: tests/lib/rules/valid-jsdoc.js [hunk 2]
```diff
@@ -317,6 +317,21 @@ ruleTester.run("valid-jsdoc", rule, {
             code:
             "/**\n" +
             "* Foo\n" +
+            "* @param {{String:foo}} hi - desc\n" +
```
Comment (kaicataldo) [inline tests/lib/rules/valid-jsdoc.js]: This test is unrelated to my change - just wanted to ensure we were testing that only the value is enforced by the `preferType` option

**Comment by kaicataldo** [comment]
Actually, looks like this might be valid. Taking a different approach.

**Comment by kaicataldo** [comment]
Sorry, never mind - had missed this part of the JSDoc docs:
>An object called 'myObj' with properties 'a' (a number), 'b' (a string) and 'c' (any type).
`{{a: number, b: string, c}} myObj`

**Comment by kaicataldo** [comment]
Updated with the correct fix - sorry for the confusion!
