### PR TITLE
Fix: `brace-style` erroneously ignoring certain errors

### LINKED ISSUE #5197: allowSingleLine in allman style for brace-style
I use the Allman style of braces, so I have this setting in my .eslintrc.yaml file:
  
```
brace-style:
    - 1
    - allman
    - allowSingleLine: true
```
If I have this setting, brace style checking is entirely deactivated!
If I replace `allman` with `stroustrup`, it works, reporting lines with Allman style and not those in Stroustrup style, even on one line.
If I remove the last line, it works, but it complains on single line braces.

Sometime, eg. when making small objects like `{ id: 'foo' }`, I want to use the single line style.
Is it forbidden for the Allman style? Why?

### PR DESCRIPTION
**Pull request by BYK**
Fixes #5197.

`brace-style` was ignoring almost all `allman` checks when
`allowSingleLine` option was set. It was also ignoring closing brace
errors when there was a body error with a single-line body.

### CODE REVIEW

File: lib/rules/brace-style.js [hunk 1]
```diff
@@ -67,21 +67,31 @@ module.exports = function(context) {
...
+                    curlyToken.loc.start.line === curlyTokenEnd.loc.start.line;
+
+                if (allOnSameLine && params.allowSingleLine) {
+                    return;
+                }
 
                 if (style !== "allman" && previousToken.loc.start.line !== curlyToken.loc.start.line) {
                     context.report(node, OPEN_MESSAGE);
-                } else if (style === "allman" && previousToken.loc.start.line === curlyToken.loc.start.line && !params.allowSingleLine) {
+                } else if (
```
Comment (BYK) [inline lib/rules/brace-style.js]: can probably put the condition on a single line. Will do if requested.

File: lib/rules/brace-style.js [hunk 2]
```diff
@@ -67,21 +67,31 @@ module.exports = function(context) {
...
+                if (!block.body.length) {
                     return;
                 }
 
                 if (curlyToken.loc.start.line === block.body[0].loc.start.line) {
                     context.report(block.body[0], BODY_MESSAGE);
-                } else if (curlyTokenEnd.loc.start.line === block.body[block.body.length - 1].loc.start.line) {
+                }
+
+                if (curlyTokenEnd.loc.start.line === block.body[block.body.length - 1].loc.start.line) {
```
Comment (BYK) [inline lib/rules/brace-style.js]: Seems like that `else` was unnecessary and was masking some errors on the first pass. LMK if I missed something.

File: lib/rules/brace-style.js [hunk 3]
```diff
@@ -67,21 +67,31 @@ module.exports = function(context) {
                 previousToken = sourceCode.getTokenBefore(block);
                 curlyToken = sourceCode.getFirstToken(block);
                 curlyTokenEnd = sourceCode.getLastToken(block);
-                curlyTokensOnSameLine = curlyToken.loc.start.line === curlyTokenEnd.loc.start.line;
+                allOnSameLine = previousToken.loc.start.line === curlyToken.loc.start.line &&
```
Comment (btmills) [inline lib/rules/brace-style.js]: You should be able to remove the check in the middle and just compare previous to end.

Comment (BYK) [inline lib/rules/brace-style.js]: Hahaha, great catch!

Comment (BYK) [inline lib/rules/brace-style.js]: Updated!

File: lib/rules/brace-style.js (hunk 2 above)
Comment (nzakas) [inline lib/rules/brace-style.js]: As long as tests are passing, I think you're good.

**Comment by nzakas** [comment]
@btmills feel free to merge once you've verified your feedback was addressed.

File: lib/rules/brace-style.js (hunk 2 above)
Comment (BYK) [inline lib/rules/brace-style.js]: @nzakas - I did modify tests (added the masked errors) for them to pass with this change.

Comment (nzakas) [inline lib/rules/brace-style.js]: Should be fine, I think.

Comment (BYK) [inline lib/rules/brace-style.js]: Alright (and I concur). Just making sure I give you the full story.

**Comment by BYK** [comment]
@btmills, @nzakas ping
