### PR TITLE
Fix: find ignore file only in cwd (fixes #5087)

### LINKED ISSUE #5087: The explanation about .eslintignore seems wrong
Looking at http://eslint.org/docs/user-guide/configuring.html#ignoring-files-and-directories

Here is the wrong (or at least confusing) text:

> When ESLint is run, it looks in the current working directory to find an .eslintignore file before determining which files to lint. If this file is found, then those preferences are applied when traversing directories. Only one .eslintignore file can be used at a time, so .eslintignore files other than the one in the current working directory will not be used.

This is not the behavior I see, especially the `current working directory` part. It seems to me eslint tries to find a .eslintignore file in the parent directories as well.

Another issue is how it matches entries that do not start with '/'. Say we have the following structure:
```
/.eslintrc
/.eslintignore
/src/
/src/extensions/
/src/extensions/hello.js
/extensions/
/extensions/hello.js
```
And .eslintignore contains:
```
extensions
```

Then running eslint would ignore both `/src/extensions/hello.js` and `/extensions/hello.js`. And we get the same behavior whether we run eslint from the project's root directory or a subdirectory (eg `src`):
```
0:0  warning  File ignored because of a matching ignore pattern. Use --no-ignore to override
```

If we use `/extensions` instead of `extensions` in `.eslintignore`, then it works as I intend: it only ignores the top level `extensions` directory.

So at the very least this behavior should be described in the documentation. But best would be to change this behavior, and request a `**/` prefix to match subdirectories as well.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30288200-the-explanation-about-eslintignore-seems-wrong?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**
This was a bit messy - the tests that tested for looking up to parent directories weren't really testing anything, so when I made the change, they still passed. I fixed them so they actually tested something. :)

### CODE REVIEW

File: lib/ignored-paths.js [hunk 1]
```diff
@@ -37,20 +36,17 @@ var DEFAULT_OPTIONS = {
...
  */
 function findIgnoreFile(cwd) {
     cwd = cwd || DEFAULT_OPTIONS.cwd;
-    if (!ignoreFileFinder) {
-        ignoreFileFinder = new FileFinder(ESLINT_IGNORE_FILENAME, cwd);
-    }
 
-    return ignoreFileFinder.findInDirectoryOrParents(cwd);
+    var ignoreFilePath = path.resolve(cwd, ESLINT_IGNORE_FILENAME);
+    return fs.existsSync(ignoreFilePath) ? ignoreFilePath : "";
```
Comment (mysticatea) [inline lib/ignored-paths.js]: `fs.existsSync` has been deprecated: https://nodejs.org/api/fs.html#fs_fs_existssync_path

Comment (ilyavolodin) [inline lib/ignored-paths.js]: We use existsSync in a few more places (cli.js, config-file.js, Makefile.js and tests/lib/cli-engine.js). We should remove if everywhere, probably as a separate PR.

Comment (mysticatea) [inline lib/ignored-paths.js]: Sounds good.
