### PR TITLE
Fix: `indent` multi-line function call (fixes #4073, fixes #4075)

### LINKED ISSUE #4073: Indent rule, continuation indentation and jasmine tests
Please consider the following:

```javascript
it('should... some lengthy test description that is forced to be' +
  'wrapped into two lines since the line length limit is set', () => {
  expect(true).toBe(true);
});
```

on eslint 1.4.1 (and maybe on some later releases as well - I haven't checked) this is lint-free when one uses the following settings:

```
/* eslint-env es6,jasmine */
/* eslint indent: [2, 2] */
```

However in 1.6.0 (current) it triggers errors:
```
3:3 - Expected indentation of 4 space characters but found 2. (indent)
4:1 - Expected indentation of 2 space characters but found 0. (indent)
```

After using `--fix` this is what is considered correct in terms of the rule:

```javascript
it('should... some lengthy test description that is forced to be' +
  'wrapped into two lines since the line length limit is set', () => {
    expect(true).toBe(true);
  });
```

Apart from whether it's correct or not (all indentation-related statements about correctness are arguable) it changes a lot of lines in the VCS history when applied.

As I analysed the problem it is because the first argument of `it` (the lengthy string) continuation is indented with 2 spaces (one step).
If one removes the continuation indentation like this:

```javascript
it('should... some lengthy test description that is forced to be' +
'wrapped into two lines since the line length limit is set', () => {
  expect(true).toBe(true);
});
```

it becomes lint-free again. I'd go for it if it was possible to set IDE autoformatting rules like this. Sadly - it's not.

If I understand how the rule works then function body is expected to be indented with one step more than the line where function body block begins.
This is correct in case the function beginning is the only thing in the line as well as for cases where it's the last thing in the line (example of short `it` description). For the case I described (long description) there might be slightly more sophisticated rule needed that takes multiline (i.e. concatenated + line breaks) strings into consideration applied.

I managed to save my VCS line history this way:

```javascript
it(`should... some lengthy test description that is forced to be
wrapped into two lines since the line length limit is set`, () => {
  expect(true).toBe(true);
});
```

but it should be considered a hack. I applied it so the code in my project is autoformatting-safe in terms of IDE our team members use (a necessity for now since `--fix` is not available for all rules yet).

What I'd like is to discuss whether it's possible do define a rule what will allow multiline strings in the way described in snippets above.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27231682-indent-rule-continuation-indentation-and-jasmine-tests?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #4075: Indent rule with multi-line object literals
Below example should pass, but the rule seems to get confused by the object literal. It passes in 0.24, fails in 1.6.0. [Real example](https://github.com/nodejs/node/blob/a334ddc467af6bfb3a93245a7e6f571c8dd01fa2/test/sequential/test-regress-GH-4948.js#L19-L27).
````
indent: [2,2]
````
````js
require('http').request({hostname: 'localhost',
                         port: 80}, function(res) {
  res.end();
});
````
````
  3:3  error  Expected indentation of 27 space characters but found 2  indent
  4:1  error  Expected indentation of 25 space characters but found 0  indent
````
ref: https://github.com/nodejs/node/pull/2286

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27237030-indent-rule-with-multi-line-object-literals?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

File: tests/fixtures/rules/indent/indent-valid-fixture-1.js [hunk 1]
```diff
@@ -412,10 +412,10 @@ if( "very very long multi line" +
 
 a( "very very long multi line" +
     "with weird indentation", function() {
-      b();
-      a(); // ->
-      c(); // <-
-    });
+  b();
+  a(); // ->
```
Comment (BYK) [inline tests/fixtures/rules/indent/indent-valid-fixture-1.js]: I'd say this doesn't have weird indentation anymore :)

**Comment by nzakas** [comment]
Lgtm
