### PR TITLE
Fix: Allow linting of .hidden files/folders (fixes #4828)

### LINKED ISSUE #4828: Can't pass dot/hidden files on command line
Hello,
since JavaScript config files are supported now, can you please consider adding a (at least optional) way to ask `eslint` to lint also hidden/dot files (e.g. `.eslintrc.js` or `.eslintrc.json` with the JSON plugin) if a name to a directory is passed (e.g. `eslint .`)?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29459770-optionally-lint-dot-hidden-files?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by IanVS**
**What issue does this pull request address?**
#4828

**What changes did you make? (Give an overview)**
The main change here is to set an option on node_glob to return dotfiles from glob patterns (anything other than explicitly passed files).   In order for dotfiles to actually be linted, though, a negating ignore pattern like `!.*` will need to be used to override the default ignore behavior.

This turned out to be a bit more involved than just returning hidden files from our glob patterns.  That's because we were _not_ ignoring dotfiles by default in all cases, only when an `options` object was provided to `listFilesToProcess`, which was nearly always.  Except, it turns out, in the test `"should not return hidden files for standard glob patterns"`.  That _was_ okay, because globs would never return dotfiles, but that started failing as soon as I made the core change in this PR.  

Now that the glob pattern will include hidden files, we need to apply the default ignore rules.  _However_, we also want to _not_ ignore dotfiles if they are explicitly included in the glob pattern.  The only way I could find to solve this problem was to directly check the glob pattern with a regex to see if it includes hidden files.  If so, dotfiles are not ignored, and otherwise they are.

**Is there anything you'd like reviewers to focus on?**
Please give my regex a sanity check.  I tried to test it out and it seems to work, but I'm not super-confident in my regex skills.

I would also be happy to include any other tests that anyone thinks might be useful.

### CODE REVIEW

File: lib/util/glob-util.js [hunk 1]
```diff
@@ -160,10 +154,25 @@ function listFilesToProcess(globPatterns, options) {
...
-            addFile(fs.realpathSync(file), !shell.test("-d", file));
+            const ignoredPaths = new IgnoredPaths(options);
+
+            addFile(fs.realpathSync(file), !shell.test("-d", file), ignoredPaths);
         } else {
+
+            // regex to find .hidden or /.hidden patterns, but not ./relative or ../relative
+            const globIncludesDotfiles = /(?:(?:^\.)|(?:[\/\\]\.))[^\/\\\.].*/.test(pattern);
+
+            options.dotfiles = options.dotfiles || globIncludesDotfiles;
```
Comment (ilyavolodin) [inline lib/util/glob-util.js]: Should this option (dotfiles) be documented somewhere? How can it be set outside of `addFile` function?

Comment (IanVS) [inline lib/util/glob-util.js]: As far as I can tell, it's internal only.  It's been there since we switched over to `node-glob`, in fact.  (https://github.com/eslint/eslint/blob/master/lib/ignored-paths.js#L113)

Comment (ilyavolodin) [inline lib/util/glob-util.js]: Hmm... We seemed to leaked a bunch of undocumented features into our options:-) Ok, another question then, would this start linting dotfiles automatically, or does user needs to do something to include them?

Comment (IanVS) [inline lib/util/glob-util.js]: Dotfiles/dotfolders will not be linted in most cases, only if the user explicitly does one of the following:

1. specifies a glob which would include dotfiles (e.g. `.*` or `test/**/.*`) (this is what the regex is to find)
2. unignores dotfiles with an `--ignore-pattern` or pattern in an `.eslintignore` file.  This is similar to our other default ignores of `node_modules` and `bower_components`

Comment (nzakas) [inline lib/util/glob-util.js]: Can you add some documentation explaining this behavior? It's still unclear to me under what circumstances a dot file will be linted and when it will not. If it's not clear to us on the team, then we definitely need this to be explicitly described somewhere for end users.

**Comment by nzakas** [comment]
As mentioned in my other comment, I think we need some good documentation around this behavior as I don't think it's clear on its own. Specifically, we need to be clear about:

1. If a dot file is passed on the command line, is it always linted? (Hopefully yes.)
2. If I run `eslint .`, will dot files be linted?
3. If I run `eslint .*`, will dot files be linted?
4. If dot files aren't linted, what do I do to make them linted?

**Comment by IanVS** [comment]
Will do.  :+1:

**Comment by pdehaan** [comment]
I recently hit this while trying to figure out why ESLint wasn't linting any of the files in a React ./.storybook/* directory. This PR and comments were excellent in helping me figure everything out.

Basically we had to modify .eslintrc to include `!.*` and then explicitly tell ESLint to lint `.` and `.storybook`:

```js
"test:lint": "eslint . .storybook",
```

Thanks again for your excellent work on ESLint!

**Comment by IanVS** [comment]
@nzakas here are a few answers.  I will find good places to document this in code as well as in the docs, but that will take a little more time.

>1\. If a dot file is passed on the command line, is it always linted? (Hopefully yes.)

This behavior is unchanged by this PR.  If a dotfile is passed on the command line, it is treated as any other file.  If it is ignored, a warning is shown.  If it is ignored by default, the warning is `File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override`.  We can talk about whether this is the right behavior, but again, it is unchanged by this PR.

> 2\. If I run `eslint .`, will dot files be linted?

No, again that is unchanged here. (although see the answer to `4.` below)

> 3\. If I run eslint .*, will dot files be linted?

That depends on the user's shell.  If they are using something like zsh, the glob is expanded to a list of files before eslint ever sees it.  In that case, this PR does not change the behavior of master, and is exactly like `1.` above.

If, however, the shell does not expand, or the user adds double quotes around the glob (`eslint ".*"`), then this PR _does_ change behavior.  Previously, all dotfiles would be ignored without warning, defeating the point of what was passed in.  Now, any dotfiles matching the glob will be linted. 

> 4\. If dot files aren't linted, what do I do to make them linted?

This is the other change in this PR.  As I said above, `eslint .` will not lint dotfiles.  Currently, `eslint . --ignore-pattern '!.*'` will _also_ not lint dotfiles.  In other words, the ignore pattern doesn't work.  With this PR, that ignore pattern will unignore all dotfiles, causing them to be linted.  Of course, the same principle applies if the pattern is added to a `.eslintignore` file.

I hope this makes it a bit clearer for the team as to the current behavior, as well as the purpose of this PR.  As I said, I will try to simplify and clean this up and get it into docs if it's agreed that this is the right approach.  I also have a few other small tweaks to make, but I want to wait until https://github.com/eslint/eslint/pull/6783 is merged because I'm going to have some merge conflicts.

**Comment by ilyavolodin** [comment]
@IanVS  Just to make sure I fully understand. If you lint using any pattern that specifically includes dot-files, dot-files will not be linted, message that they are skipped will not be displayed. If you want to lint dot-files you have to do one of 2 things:
Use a pattern that will include dot-files OR
Un-ignore dot files either on command line or through .eslintignore file.

Is that correct?

**Comment by IanVS** [comment]
@ilyavolodin sorry, can you be a bit more specific.  When you say "any pattern that specifically includes dot-files", do you mean a glob (one that is not shell-expanded) like `**/.*.js`? Also, are you asking about the current behavior, or the behavior of this PR?

**Comment by ilyavolodin** [comment]
@IanVS Yes, a glob like the one you provided. And I'm asking about this PR.

**Comment by IanVS** [comment]
With this PR and that pattern, all matching dotfiles will be linted.  Essentially, the default ignore of dotfiles is turned off if a glob pattern specifying dotfiles or dotfolders is given.  Other ignore rules from `.eslintignore` or `--ignore-pattern` are still respected and files matching those are silently ignored (as before).

**Comment by nzakas** [comment]
Sorry, lost track of this. 

The one thing that I'm not sure is the behavior we want is passing a dot file on the command line. It seems like this should lint the file:

```
eslint .eslintrc.js
```

I thought we had changed this behavior before so that explicitly passed files would always be linted regardless of ignore settings?

**Comment by IanVS** [comment]
>I thought we had changed this behavior before so that explicitly passed files would always be linted regardless of ignore settings?

Not to my knowledge, and that's definitely not the current behavior.  And actually, changing that behavior would effect other tools like atom's eslint plugin, as dotfiles would start being linted when opened whereas they currently are not.  I'm not saying it wouldn't necessarily be the right thing to do, but I _do_ personally think it should be addressed in a separate issue/PR and have some discussion first.

**Comment by IanVS** [comment]
BTW, I will rebase this with master tonight.

**Comment by IanVS** [comment]
I've rebased onto master.

**Comment by IanVS** [comment]
@nzakas the reason I am reluctant to "lint anything passed explicitly" partly lies in that being a more difficult challenge to solve.  There is not always an easy distinction between "explicitly passed" and "expanded from a glob by the user's shell".  I think this PR gives some "quick" wins towards being able to lint dotfiles, and there will need to be a larger re-architecture to be able to always lint directly specified files.

**Comment by ilyavolodin** [comment]
Hmm.. This is strange. I wonder when this changed. I definitely remember us changing our code to always lint anything explicitly passed on the command line. That was a long while ago, but that was the decision made.

**Comment by IanVS** [comment]
I'd be interested to see that, because it must have been before my time (pre 1.0).  I have never seen that behavior.  It's always warned me when an explicitly passed file was ignored.

**Comment by nzakas** [comment]
@IanVS You were part of the discussion: https://github.com/eslint/eslint/issues/3649#issuecomment-137845412

**Comment by IanVS** [comment]
@nzakas that was a slightly different issue which had to do with linting an explicitly-passed file with a non-`.js` extension.  As you can see from the [test which was added](https://github.com/eslint/eslint/pull/3666/files#diff-6e3261f1362e4e13d9d684e4cae1a127R307), it did not address ignored files at all.

**Comment by nzakas** [comment]
Sorry, I lost track of this. :( Thanks for clarifying @Ianvs, I see that I was conflating two issues.

In that case, I think this should be good to merge. @ilyavolodin thoughts?

**Comment by ilyavolodin** [comment]
I think it's good to go.
