### PR TITLE
Fix: improve `constructor-super` errors for literals (fixes #5449)

### LINKED ISSUE #5449: constructor-super - super() must be called even if the class extends null
**What version of ESLint are you using?**
**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**

I'm using the online demo with the default configuration (+ `es6`).

**What did you do? Please include the actual source code causing the issue.**
```js
class A extends null {
	constructor() {
		super();
	}
}

new A();
```
```js
class B extends null {
	constructor() {}
}

new B();
```

**What did you expect to happen?**

The first code should be fine, in the second ESLint should warn `2:2 - Expected to call 'super()'.`

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint warns `3:3 - Unexpected 'super()'.` for the first code, while the second is considered fine.

**Specification:**

- In a class definition, if *ClassHeritage* is present (so even if it is `extends null`), the class' *[[ConstructorKind]]* internal slot is set to `"derived"`. <sup>[14.5.14](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-runtime-semantics-classdefinitionevaluation) - step 15</sup>
- When instantiating a new class<sup>[9.2.2 - [[Construct]]](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-ecmascript-function-objects-construct-argumentslist-newtarget)</sup>, *OrdinaryCallBindThis*<sup>[9.2.1.2](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-ordinarycallbindthis)</sup> (which sets *envRec.[[thisBindingStatus]]* to `"initialized"` by calling the *BindThisValue*<sup>[8.1.1.3.1](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-bindthisvalue)</sup>) is only called if `[[ConstructorKind]]` is `"base"`<sup>[9.2.2](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-ecmascript-function-objects-construct-argumentslist-newtarget) - Steps 4 and 8</sup>, so *envRec.[[thisBindingStatus]]* remains `"uninitialized"` even if the class `extends null`.
- The *[[Construct]]* function<sup>[9.2.2](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-ecmascript-function-objects-construct-argumentslist-newtarget) - step 15</sup> returns the result of calling the *envRec.GetThisBinding()* function, which throws if *envRec.[[thisBindingStatus]]* is `"uninitialized"`<sup>[8.1.1.3.4](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-function-environment-records-getthisbinding) - Step 3</sup>.

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #5449 .

This PR was squashed from 2 commits:

- d93552a86098bb4690d230142a87f8a4e98c14ac Fixes a bug of code path analysis. I found it while I wrote this change.
- 2497bf7f42a71c6570023ef05661827447af8ec5 Improves the behavior for classes which inherit from a non-constructor.
  - The error message for classes which inherit from a non-constructor is improved.
    - `"Unexpected 'super()' because 'super' is not a constructor."`
  - The lacking `super()` cases for classes which inherit from a non-constructor are now invalid cases.
  - Enhancements the check whether a class inherits from a constructor or not.

### CODE REVIEW

File: lib/rules/constructor-super.js [hunk 1]
```diff
@@ -31,6 +25,57 @@ function isConstructorFunction(node) {
...
+        case "MemberExpression":
+        case "CallExpression":
+        case "NewExpression":
+        case "YieldExpression":
+        case "TaggedTemplateExpression":
+        case "MetaProperty":
+            return true;
+
+        case "Identifier":
+            return node.name !== "undefined";
```
Comment (michaelficarra) [inline lib/rules/constructor-super.js]: `undefined` can be shadowed. You either shouldn't make this exception, or you should make this exception for *every* non-constructor intrinsic (under the assumption that none of them could be shadowed). I would go with the former. It is safer.

File: lib/rules/constructor-super.js [hunk 2]
```diff
@@ -274,15 +300,15 @@ module.exports = function(context) {
                         message: "Unexpected duplicate 'super()'.",
                         node: node
                     });
+                } else if (!funcInfo.superIsConstructor) {
+                    context.report({
+                        message: "Unexpected 'super()' because 'super' is not a constructor.",
```
Comment (michaelficarra) [inline lib/rules/constructor-super.js]: I would say "... because *superclass* is not ...".

File: lib/rules/constructor-super.js (hunk 1 above)
Comment (mysticatea) [inline lib/rules/constructor-super.js]: Yeah, I thought shadowing, but I know there was a well-known pattern past:

```js
!(function(undefined) {
    //...
}());
```

So I didn't check it.

File: lib/rules/constructor-super.js (hunk 2 above)
Comment (mysticatea) [inline lib/rules/constructor-super.js]: Hmm, I think the class and the constructor are different things in the mind of many people, so class is not a constructor always?

In fact, this message was copied from the message of Chrome.

image

Comment (nzakas) [inline lib/rules/constructor-super.js]: Let's go with this for now. If we get feedback that the message is confusing, we can always change it later.

**Comment by nzakas** [comment]
Lgtm
