### PR TITLE
Fix: support Rest/Spread Properties (fixes #9885)

### LINKED ISSUE #9885: 🎉 Object Rest/Spread Properties arrived at stage 4
> https://github.com/tc39/proposals/commit/7a04292f2e6f11fbcfef8a7b20a0bf5aedba79a4

It's the time to update our rules to be according to the current ESTree spec.

- [x] Update Espree to support the syntax in `ecmaVersion:2018`.
  I think we should keep `ecmaFeatures.experimentalObjectRestSpread` to avoid breaking changes.
  1. If `ecmaVersion:2018` and no `ecmaFeatures.experimentalObjectRestSpread`, Espree generates `RestElement`/`SpreadElement`.
  2.  If `ecmaFeatures.experimentalObjectRestSpread:true`, Espree generates `ExperimentalRestProperty`/`ExperimentalSpreadProperty` as is.
- [x] Update core rules to support the syntax.

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix

Fixes #9885.

**What changes did you make? (Give an overview)**

This PR focuses on "rules work fine if people replace `experimentalObjectRestSpread: true` to `ecmaVersion: 2018`". I cloned all tests which have `experimentalObjectRestSpread: true` option, then rewrote it to `ecmaVersion: 2018`.

I updated the tests of 14 rules, then I fixed 4 rules (`no-self-assign`, `no-unused-vars`, `object-shorthand`, and `rest-spread-spacing`).

**Is there anything you'd like reviewers to focus on?**

Nothing in particular.

### CODE REVIEW

File: lib/rules/key-spacing.js [hunk 1]
```diff
@@ -360,9 +360,10 @@ module.exports = {
          */
         function isKeyValueProperty(property) {
             return !(
-                (property.method ||
+                property.method ||
                 property.shorthand ||
-                property.kind !== "init" || property.type !== "Property") // Could be "ExperimentalSpreadProperty" or "SpreadProperty"
+                property.kind !== "init" ||
+                property.type !== "Property" // Could be "ExperimentalSpreadProperty" or "SpreadElement"
```
Comment (mysticatea) [inline lib/rules/key-spacing.js]: This is trivial; I just removed extra parens.

File: tests/lib/rules/key-spacing.js [hunk 2]
```diff
@@ -524,7 +596,7 @@ ruleTester.run("key-spacing", rule, {
             beforeColon: true,
             afterColon: false
         }],
-        parserOptions: { ecmaVersion: 6, ecmaFeatures: { experimentalObjectRestSpread: true } }
```
Comment (mysticatea) [inline tests/lib/rules/key-spacing.js]: This removing in this file is trivial; those were unused.

File: tests/lib/rules/key-spacing.js [hunk 3]
```diff
@@ -524,7 +596,7 @@ ruleTester.run("key-spacing", rule, {
...
+        parserOptions: { ecmaVersion: 6 }
```
Comment (mysticatea) [inline tests/lib/rules/key-spacing.js]: Removing such as this in this file is trivial; those were unused.

**Comment by mysticatea** [comment]
@ljharb I'll check it.

**Comment by mysticatea** [comment]
It's no problem. I added test cases.

**Comment by not-an-aardvark** [comment]
Thanks for contributing!
