### PR TITLE
Fix: newline-after-var declare and export (fixes #2325)

### LINKED ISSUE #2325: newline-after-var declare and export
Another issue with newline-after-var when it is enabled I get an error when exporting one let after another. This is in version v0.19.0
```
export let A = "A";
export let B = "B";
```
Which seems to be an error given that this does not 
```
 let A = "A";
 let B = "B";
```

the message is `warning  Expected blank line after variable declarations  newline-after-var`

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

File: lib/rules/newline-after-var.js [hunk 1]
```diff
@@ -51,6 +51,17 @@ module.exports = function(context) {
     }
 
     /**
+     * Determine if provided keyword is an export specifiers
+     * @private
+     * @param {string} keyword - keyword to test
+     * @returns {boolean} True if `keyword` is an export specifier
+     */
+    function isExportSpecifier(keyword) {
```
Comment (nzakas) [inline lib/rules/newline-after-var.js]: `keyword` should be `nodeType`.

**Comment by gyandeeps** [comment]
@nzakas Changes have been made.

**Comment by nzakas** [comment]
Lgtm. Thanks!
