### PR TITLE
Fix: block-scoped-var to work with destructuring (fixes #1863)

### LINKED ISSUE #1863: destructuring doesn't work with block-scoped-var
.eslintrc

```yaml
---
  ecmaFeatures:
    destructuring: true

  rules:
    block-scoped-var: 2
```

test.js
```javascript
function myFunc(foo) {
  "use strict";
  var { bar } = foo;

  bar.hello();
}

myFunc();
```

Error:
```
test.js
  5:2  error  "bar" used outside of binding context  block-scoped-var

✖ 1 problem (1 error, 0 warnings)
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8792903-destructuring-doesn-t-work-with-block-scoped-var?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nzakas**

### CODE REVIEW

File: tests/lib/rules/block-scoped-var.js [hunk 1]
```diff
@@ -31,6 +31,8 @@ eslintTester.addRuleTest("lib/rules/block-scoped-var", {
         "function f() { var hasOwnProperty; { hasOwnProperty; } }",
         "function f(){ a; b; var a, b; }",
         "function f(){ g(); function g(){} }",
+        { code: "function myFunc(foo) {  \"use strict\";  var { bar } = foo;  bar.hello();}", ecmaFeatures: { destructuring: true } },
```
Comment (zaggino) [inline tests/lib/rules/block-scoped-var.js]: `ecmaFeatures: { destructuring: true }` is not mentioned in https://github.com/eslint/eslint/tree/master/docs/configuring

Comment (nzakas) [inline tests/lib/rules/block-scoped-var.js]: Can you file an issue for that?

Comment (zaggino) [inline tests/lib/rules/block-scoped-var.js]: https://github.com/eslint/eslint/issues/1942
