### PR TITLE
Fix: duplicated error message if a crash occurs (fixes #8964)

### LINKED ISSUE #8964: When a crash occurs, the error message is printed twice
**Tell us about your environment**

* **ESLint Version:** 4.2.0
* **Node Version:** 8.1.4
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
rules:
  no-restricted-syntax: [error, 'Invalid selector [[[[']
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
a;
```

**What did you expect to happen?**

The configuration isn't valid (it includes an invalid selector), so I expected ESLint to output an error message.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint outputted the same error message twice, once with the stack trace and once without:

<details>
<summary>Output</summary>

```
Syntax error in selector "Invalid selector [[[[" at position 18: Expected " ", "." or [^ [\],():#!=><~+.] but "[" found.
Error: Syntax error in selector "Invalid selector [[[[" at position 18: Expected " ", "." or [^ [\],():#!=><~+.] but "[" found.
    at tryParseSelector (/path/to/node_modules/eslint/lib/util/node-event-generator.js:163:19)
    at lodash.memoize.rawSelector (/path/to/node_modules/eslint/lib/util/node-event-generator.js:175:28)
    at memoized (/path/to/node_modules/lodash/lodash.js:10566:27)
    at NodeEventGenerator.eventNames.forEach.rawSelector (/path/to/node_modules/eslint/lib/util/node-event-generator.js:235:30)
    at Array.forEach (native)
    at new NodeEventGenerator (/path/to/node_modules/eslint/lib/util/node-event-generator.js:234:20)
    at Linter.verify (/path/to/node_modules/eslint/lib/linter.js:909:34)
    at processText (/path/to/node_modules/eslint/lib/cli-engine.js:203:31)
    at processFile (/path/to/node_modules/eslint/lib/cli-engine.js:245:18)
    at executeOnFile (/path/to/node_modules/eslint/lib/cli-engine.js:585:25)

```

</details>

This isn't specific to the `no-restricted-syntax` rule -- it seems to occur whenever any error is thrown from anywhere.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix (https://github.com/eslint/eslint/issues/8964)

**What changes did you make? (Give an overview)**

This updates the uncaught exception handler to avoid printing the error message twice. The error message is included in the stack, so it's not necessary to print the error message and the stack separately.

**Is there anything you'd like reviewers to focus on?**

Nothing in particular

### CODE REVIEW

File: bin/eslint.js [hunk 1]
```diff
@@ -44,11 +44,10 @@ process.once("uncaughtException", err => {
     if (typeof err.messageTemplate === "string" && err.messageTemplate.length > 0) {
         const template = lodash.template(fs.readFileSync(path.resolve(__dirname, `../messages/${err.messageTemplate}.txt`), "utf-8"));
 
-        console.log("\nOops! Something went wrong! :(");
-        console.log(`\n${template(err.messageData || {})}`);
+        console.error("\nOops! Something went wrong! :(");
```
Comment (ilyavolodin) [inline bin/eslint.js]: I wonder if this might be considered as a breaking change? If somebody wrote an integration that listens for stdout they will get nothing in the case of the crash. But I think that's too much of an edge case.

Comment (not-an-aardvark) [inline bin/eslint.js]: I suppose that's possible. Do you think it would be better to separate that into a different commit and schedule it for 5.0?
