### PR TITLE
Fix: Change error message logic for implicit file ignore (fixes #12873)

### LINKED ISSUE #12873: Eslint falsely reports matching configured ignore pattern for implicit ignore pattern
**Tell us about your environment**

* **ESLint Version:** 7.0.0-alpha.0
* **Node Version:** v12.14.1
* **npm Version:** v6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "extends": "airbnb-base"
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I was told that an additional issue needed to be opened for code changes. #12348 has been scoped to be documentation changes only. That issue has the original instructions to reproduce the issue, although I have been able to successfully reproduce the issue myself.

If I have a file located in a dot directory (for example, `client/.storybook/config.js`), I can lint it by telling eslint to analyze the directory it lives in (`npx eslint client/.storybook`). However, if I try to lint the file directory, I am incorrectly told that the file has been ignored because of a matching ignore pattern. I have no ignore patterns defined, so this is incorrect. The file was actually ignored due to an implicit ignore rule.

Source: N/A

```bash
npx eslint client/.storybook/config.js
```

**What did you expect to happen?**

Eslint should indicate that the file was ignored by default.

**What actually happened? Please include the actual, raw output from ESLint.**

Eslint indicated that the file was ignored because of a configured ignore pattern. I have no ignore patterns configured.

**Are you willing to submit a pull request to fix this bug?**

Yes

### PR DESCRIPTION
**Pull request by snhardin**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [X] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[X] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Addresses issue #12873 

#### What changes did you make? (Give an overview)

I adjusted the logic that determines what message to send when a file is ignored.

### CODE REVIEW

**Comment by kaicataldo** [comment]
Copying from [this comment](https://github.com/eslint/eslint/issues/12873#issuecomment-583484376):

I wonder if it would be helpful to differentiate between when a file is ignored due to it being in a dotfolder versus it being a dotfile?

**Comment by nzakas** [comment]
@kaicataldo can you be more specific with your feedback? Are you requesting a change in this PR or just asking for an opinion?

**Comment by kaicataldo** [comment]
Sure thing - sorry for the confusion. My comment wasn't intended to be a blocker. It was just an idea I thought might improve the user experience a bit. Looking at it again, though, I think the current error message is sufficient :+1:.

File: lib/cli-engine/cli-engine.js [hunk 1]
```diff
@@ -278,7 +278,8 @@ function verifyText({
  */
 function createIgnoreResult(filePath, baseDir) {
     let message;
-    const isHidden = /^\./u.test(path.basename(filePath));
+    const isHidden = filePath.split(path.sep)
+        .find(directory => /^\./u.test(directory));
```
Comment (kaicataldo) [inline lib/cli-engine/cli-engine.js]:
```suggestion
        .find(segment => /^\./u.test(segment));
```

Comment (kaicataldo) [reply lib/cli-engine/cli-engine.js]: Small suggestion for clarity, since the final segment can be a directory or file.

Comment (snhardin) [reply lib/cli-engine/cli-engine.js]: Done!

**Comment by kaicataldo** [comment]
Thank you for contributing!
