### PR TITLE
Fix: ignore comma before closing paren (fixes #11295)

### LINKED ISSUE #11295: `comma-spacing` has conflict with `space-in-parens`
**Tell us about your environment**

* **ESLint Version:** 5.12.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "rules": {
    "comma-spacing": 2,
    "space-in-parens": [2, "never"]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Source code:
```js
fn(a, b, )

// or

fn(a, b,)
```

Here is the reproduction link: https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IGNvbW1hLXNwYWNpbmc6IDIgKi9cclxuLyogZXNsaW50IHNwYWNlLWluLXBhcmVuczogWzIsICduZXZlciddICovXHJcbmZuKGEsIGIsKSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==

**What did you expect to happen?**
Lint-free.

**What actually happened? Please include the actual, raw output from ESLint.**
Reported linting error, see the reproduction link.

**Are you willing to submit a pull request to fix this bug?**
Yes.

### PR DESCRIPTION
**Pull request by g-plane**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Bug fix

**What changes did you make? (Give an overview)**
Fixes #11295 

**Is there anything you'd like reviewers to focus on?**
Maybe no.

### CODE REVIEW

File: tests/lib/rules/comma-spacing.js [hunk 1]
```diff
@@ -61,6 +61,7 @@ ruleTester.run("comma-spacing", rule, {
         "['  ,  ']",
         { code: "[`  ,  `]", parserOptions: { ecmaVersion: 6 } },
         { code: "`${[1, 2]}`", parserOptions: { ecmaVersion: 6 } },
+        { code: "fn(a, b,)", parserOptions: { ecmaVersion: 2018 } }, // #11295
```
Comment (kaicataldo) [inline tests/lib/rules/comma-spacing.js]: Would it possible to also include tests with an arrow function, function expression, and function declaration, just to document the expected behavior? Thanks!
