### PR TITLE
fix: false positive with assignment in `no-extra-parens`

### LINKED ISSUE #16850: Bug: `no-extra-parens` autofix changes assignment semantics
### Environment

Node version: v18.13.0
npm version: v8.19.3
Local ESLint version: v8.33.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 22.2.0

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
{
    "parserOptions": {
        "ecmaVersion": 2015
    },
    "rules": {
        "no-extra-parens": [
            "error"
        ]
    }
}
```
</details>

```js
let foo, bar;
(foo) = function () { };
(bar) = class { };
console.log(foo.name + bar.name);
```

### What did you expect to happen?

ESLint should not remove the parentheses in `(foo)` and `(bar)` automatically. The parentheses are required to prevent the class or function from having its `name` property set to the name of the variable.

### What actually happened?

The parentheses around `foo` and `bar` are removed by the autofix. The resulting code prints `foobar` instead of an empty string like the original code.

[**DEMO LINK**](https://eslint.org/play/#eyJ0ZXh0IjoibGV0IGZvbywgYmFyO1xuKGZvbykgPSBmdW5jdGlvbiAoKSB7IH07XG4oYmFyKSA9IGNsYXNzIHsgfTtcbmNvbnNvbGUubG9nKGZvby5uYW1lICsgYmFyLm5hbWUpO1xuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoyMDE1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLWV4dHJhLXBhcmVucyI6WyJlcnJvciJdfSwiZW52Ijp7fX19)

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

My suggestion is to disable the autofix for parentheses around a single identifier on the left side of an assignment when the right side contains an anonymous class or anonymous function. This would avoid unexpected changes in program behavior in some edge cases.

I can't decide if keeping the warning in the first place would be good or not.

### PR DESCRIPTION
**Pull request by fasttime**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes #16850

#### What changes did you make? (Give an overview)

Added an exception to the rule `no-extra-parens`. Parentheses around a single identifier will no longer be reported if the identifier is the LHS of an assignment with `=`, `&&=`, `||=` or `??=` and the RHS being an anonymous class or function or an arrow function.

### CODE REVIEW

File: lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -766,6 +766,36 @@ module.exports = {
...
+        /**
+         * Checks if the left-hand side of an assignment is an identifier and the right-hand side is
+         * an anonymous class or function.
+         *
+         * As per https://tc39.es/ecma262/#sec-assignment-operators-runtime-semantics-evaluation, an
+         * assignment where the right-hand side is an anonymous class or function and the left-hand
+         * side is an *unparenthesized* identifier has different semantics than other assignments.
+         * Specifically, when an expression like `foo = function () {}` is evaluated, `foo.name`
+         * will be set to the string "foo", i.e. the identifier name. The same thing does not happen
+         * when evaluating `(foo) = () => {}`.
```
[the remark this answers is not in the document]
Comment (fasttime) [reply lib/rules/no-extra-parens.js]: Sorry, my mistake. It's fixed now.

File: lib/rules/no-extra-parens.js [hunk 2]
```diff
@@ -766,6 +766,36 @@ module.exports = {
...
+
+                if (rhsType === "ArrowFunctionExpression") {
+                    return true;
+                }
+                if ((rhsType === "FunctionExpression" || rhsType === "ClassExpression") && !right.id) {
+                    return true;
+                }
+            }
+            return false;
+        }
```
Comment (mdjermanovic) [inline lib/rules/no-extra-parens.js:797]: Should we also check the operator? Per the spec, this behavior seems to apply only if the operator is one of `=`, `&&=`, `||=`, or `??=`, not e.g. `+=`.

Comment (fasttime) [reply lib/rules/no-extra-parens.js:797]: @mdjermanovic I think so. I got confused because Babel doesn't seem to care about the operand, and decides to [keep the parentheses](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=G4QwTgBCDcBQAUICUEDUBeCAzArgOwGMAXASwHs8IAjeFAbwgF85EUNt9jzLaIHnYQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.20.15&externalPlugins=&assumptions=%7B%7D) even when optimizing `(a) += function () {}`. This made me think that I could be missing some edge case, but actually the spec is clear enough in defining the semantics of each operator (group) in a separate section. I'm going to update the PR like you suggested. Thanks!

Comment (fasttime) [reply lib/rules/no-extra-parens.js]: Updated as per discussion.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!
