### PR TITLE
Fix: Corrected notice for invalid (:) plugin names

### LINKED ISSUE #13255: "ESLint couldn't find the plugin" notice loses a last character
**Tell us about your environment**

* **ESLint Version:** 6.8.0
* **Node Version:** 12.0.0
* **npm Version:** 6.14.4

**What parser (default, Babel-ESLint, etc.) are you using?**

Not relevant, but `"@typescript-eslint/parser"`

**Please show your full configuration:** 

<details>
<summary>Configuration</summary>

```js
module.exports = {
  extends: [
    "plugin:eslint-config-prettier",
  ],
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
eslint --print-config ./eslintrc.js
```

**What did you expect to happen?**

The module name being reported as not existing should be ... `eslint-config-prettier`, I'm guessing?

**What actually happened? Please include the actual, raw output from ESLint.**

```
Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the plugin "eslint-plugin-eslint-config-prettie".

(The package "eslint-plugin-eslint-config-prettie" was not found when loaded as a Node module from the directory "C:\Code\tslinttest".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-eslint-config-prettie@latest --save-dev

The plugin "eslint-plugin-eslint-config-prettie" was referenced from the config file in ".eslintrc.js".

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

This issue split from: https://github.com/typescript-eslint/tslint-to-eslint-config/issues/439.

**Are you willing to submit a pull request to fix this bug?**

I'd love to! 🤗

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

- [x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))

#### What changes did you make? (Give an overview)

Three small, related changes:
* The plugin name parsed in the config array factory shouldn't slice off the last digit when there isn't a `/` in the name.
* Shared naming normalization shouldn't add a `plugin-` if the module name has a seemingly erroneous `:`.
* For those `:` names, a new `plugin-missing` error message suggests that the plugin name might be invalid.

This'll be the new error contents from the example in the issue:

```
Oops! Something went wrong! :(

ESLint: 7.4.0

ESLint couldn't find the plugin "plugin:eslint-config-prettier".

(The package "plugin:eslint-config-prettier" was not found when loaded as a Node module from the directory "/Users/josh/repos/linttemp".)

It looks like this might not be a valid plugin name. Did you use the name of a preset configuration instead of a plugin?

The plugin "plugin:eslint-config-prettier" was referenced from the config file in ".eslintrc.js".

If you still can't figure out the problem, please stop by https://eslint.org/chat to chat with the team.
```

Fixes #13255. Although the issue is marked as `working as intended`, the comments indicate the error message given for an invalid plugin name should be improved.

#### Is there anything you'd like reviewers to focus on?

I'm not confident this is the right error message... would welcome someone with more ESLint context helping improve it please! 😄

### CODE REVIEW

File: lib/cli-engine/config-array-factory.js [hunk 1]
```diff
@@ -802,7 +802,7 @@ class ConfigArrayFactory {
      */
     _loadExtendedPluginConfig(extendName, ctx) {
         const slashIndex = extendName.lastIndexOf("/");
-        const pluginName = extendName.slice("plugin:".length, slashIndex);
+        const pluginName = slashIndex === -1 ? extendName : extendName.slice("plugin:".length, slashIndex);
```
Comment (mdjermanovic) [inline lib/cli-engine/config-array-factory.js:805]: Could we maybe just throw here if `slashIndex === -1`, instead of continuing and trying to load a module with a malformed name (e.g., `"plugin:eslint-config-prettier"`).

`ESLint couldn't find the plugin "plugin:eslint-config-prettier"` could be confusing, because the real issue is a wrong configuration entry in `"extends"`: it's either missing `/config-name` at the end, or has the `plugin:` prefix while it shouldn't have that prefix (in the case that it's actually a config, not a plugin).

File: lib/cli-engine/config-array-factory.js [hunk 2]
```diff
@@ -274,14 +274,15 @@ function loadESLintIgnoreFile(filePath) {
  * Creates an error to notify about a missing config to extend from.
  * @param {string} configName The name of the missing config.
  * @param {string} importerName The name of the config that imported the missing config
+ * @param {string} messageTemplate The text tempalte to source error strings from.
```
Comment (JoshuaKGoldberg) [inline lib/cli-engine/config-array-factory.js:277]: Err, whoops:

```suggestion
 * @param {string} messageTemplate The text template to source error strings from.
```

**Review by mdjermanovic — CHANGES_REQUESTED** [review]

File: messages/plugin-invalid.txt [hunk 3]
```diff
@@ -0,0 +1,9 @@
+ESLint couldn't find the plugin "<%- pluginName %>".
+
+(The package "<%- pluginName %>" was not found when loaded as a Node module from the directory "<%- resolvePluginsRelativeTo %>".)
+
+It looks like this might not be a valid plugin name. Did you use the name of a shareable config instead of a plugin?
```
[the remark this answers is not in the document]
Comment (JoshuaKGoldberg) [reply messages/plugin-invalid.txt]: Oh! Thank you, now I understand how this works together. Appreciated!

File: messages/plugin-invalid.txt [hunk 4]
```diff
@@ -0,0 +1,8 @@
+"<%= configName %>" is invalid syntax for a config specifier.
+
+* If your intention is to extend from a configuration exported from the plugin, add the configuration name after a slash: e.g. "<%= configName %>/myConfig".
+* If this is the name of a shareable config instead of a plugin, remove the "plugin:" prefix: i.e. "<%= configName.slice("plugin:".length) %>".
```
Comment (JoshuaKGoldberg) [inline messages/plugin-invalid.txt:4]: TIL this is allowed in [`_.template`](https://lodash.com/docs/4.17.15#template). Confirmed locally this does what we want it to:

```

Oops! Something went wrong! :(

ESLint: 7.7.0

"plugin:wat" is invalid syntax for a config specifier.

* If your intention is to extend from a configuration exported from the plugin, add the configuration name after a slash: e.g. "plugin:wat/myConfig".
* If this is the name of a shareable config instead of a plugin, remove the "plugin:" prefix: i.e. "wat".

'"plugin:wat"' was referenced from the config file in "C:\Code\eslinttemp\.eslintrc.json".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

Comment (mdjermanovic) [reply messages/plugin-invalid.txt:4]: This output looks awesome!

I can also confirm locally that this works. It seems that `<-` and `<=` can evaluate code, although it doesn't look like that in the lodash docs.

File: tests/lib/cli-engine/config-array-factory.js [hunk 5]
```diff
@@ -1515,6 +1515,23 @@ describe("ConfigArrayFactory", () => {
             }, /Failed to load config "plugin:invalid-config\/bar" to extend from./u);
         });
 
+        it("should throw an error with a message template when a plugin referenced for a plugin config is invalid", () => {
```
Comment (mdjermanovic) [inline tests/lib/cli-engine/config-array-factory.js:1518]:
```suggestion
        it("should throw an error with a message template when a plugin config specifier is missing config name", () => {
```

File: tests/lib/cli-engine/config-array-factory.js [hunk 6]
```diff
@@ -1515,6 +1515,23 @@ describe("ConfigArrayFactory", () => {
...
+            try {
+                applyExtends({
+                    extends: "plugin:nonexistent-plugin",
```
Comment (mdjermanovic) [inline tests/lib/cli-engine/config-array-factory.js:1521]: Can we rename `nonexistent-plugin` to something else, since this isn't testing a case where the plugin doesn't exist (it would be the same if it does exist)

**Review by mdjermanovic — CHANGES_REQUESTED** [review]
Looks great! I left just a few small suggestions.

**Review by mdjermanovic — APPROVED** [review]
Looks great, thanks!

**Review by nzakas — APPROVED** [review]

**Review by kaicataldo — APPROVED** [review]

**Comment by kaicataldo** [comment]
Thanks for contributing!
