### PR TITLE
Fix: dot-location errors with parenthesized objects (fixes #11868)

### LINKED ISSUE #11868: eslint --fix with dot-location breaks code
* **ESLint Version: 5.16.0**
* **Node Version: 8.1.4**
* **npm Version: 6.7.0**

[ESLint playground link](https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgZG90LWxvY2F0aW9uOiBbXCJlcnJvclwiLCBcIm9iamVjdFwiXSovXG5cbnZhciBmb28gPSAoXG4gIGNvbmQxID09IHRydWUgJiZcbiAgY29uZDJmdW5jKClcbikudG9TdHJpbmcoKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjUsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOjIsImZvci1kaXJlY3Rpb24iOjIsImdldHRlci1yZXR1cm4iOjIsIm5vLWNhc2UtZGVjbGFyYXRpb25zIjoyLCJuby1jbGFzcy1hc3NpZ24iOjIsIm5vLWNvbXBhcmUtbmVnLXplcm8iOjIsIm5vLWNvbmQtYXNzaWduIjoyLCJuby1jb25zb2xlIjoyLCJuby1jb25zdC1hc3NpZ24iOjIsIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6Miwibm8tY29udHJvbC1yZWdleCI6Miwibm8tZGVidWdnZXIiOjIsIm5vLWRlbGV0ZS12YXIiOjIsIm5vLWR1cGUtYXJncyI6Miwibm8tZHVwZS1jbGFzcy1tZW1iZXJzIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1uZXctc3ltYm9sIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNwYXJzZS1hcnJheXMiOjIsIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjoyLCJuby11bmRlZiI6Miwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOjIsIm5vLXVucmVhY2hhYmxlIjoyLCJuby11bnNhZmUtZmluYWxseSI6Miwibm8tdW5zYWZlLW5lZ2F0aW9uIjoyLCJuby11bnVzZWQtbGFiZWxzIjoyLCJuby11bnVzZWQtdmFycyI6Miwibm8tdXNlbGVzcy1lc2NhcGUiOjIsInJlcXVpcmUteWllbGQiOjIsInVzZS1pc25hbiI6MiwidmFsaWQtdHlwZW9mIjoyfSwiZW52Ijp7fX19)

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/*eslint dot-location: ["error", "object"]*/

var foo = (
  cond1 == true &&
  cond2func()
).toString();
```

```bash
eslint --fix
```

**What did you expect to happen?**

No change to file

**What actually happened? Please include the actual, raw output from ESLint.**

```js
/*eslint dot-location: ["error", "object"]*/

var foo = (
  cond1 == true &&
  cond2func().
)toString();
```

As you can see, this code doesn't even parse. `eslint --fix` should never break correctness and certainly shouldn't ever output something that fails to parse.

### PR DESCRIPTION
**Pull request by mdjermanovic**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix #11868

**What changes did you make? (Give an overview)**

Fixed `dot-location` rule (`"object"` option) because it produces syntax errors with parenthesized objects. 

Parentheses around `MemberExpression.object` node are now treated as a part of the 'object'.

For example, the following was a false positive:

```js
( 
  object
).
property
```

and the auto-fix produced syntax error:

```js
( 
  object.
)
property
```

With this PR, the example above does not have a warning.

Also, with this PR auto-fix works correctly for similar cases that do have warnings. For example, this:

```js
( 
  object
)
.property
```

will be fixed to:

```js
( 
  object
).
property
```

I've also added several test cases unrelated to this issue.

**Is there anything you'd like reviewers to focus on?**

* If the first token before the `MemberExpression.property` is not a `dot` token, the rule will ignore that node. I believe there is no need to support this case ([post](https://github.com/eslint/eslint/issues/11868#issuecomment-506919269)).
* The rule doesn't check if the `dot` is right after the `object` (or parens now) / right before the `property`. This is valid syntax: `a   .   b` and produces no `dot-location` warnings. Perhaps there could be an additional option to 'attach' the dot, I could open an issue if this wasn't already discussed.

### CODE REVIEW

File: lib/rules/dot-location.js [hunk 1]
```diff
@@ -54,29 +54,36 @@ module.exports = {
          */
         function checkDotLocation(obj, prop, node) {
             const dot = sourceCode.getTokenBefore(prop);
-            const textBeforeDot = sourceCode.getText().slice(obj.range[1], dot.range[0]);
+
+            /* istanbul ignore if */
+            if (astUtils.isNotDotToken(dot)) {
```
Comment (not-an-aardvark) [inline lib/rules/dot-location.js]: What's the purpose of this conditional? Is it just a sanity check?

Comment (mdjermanovic) [reply lib/rules/dot-location.js]: Yes, it's a bit strange now. 

This should never happen, I couldn't find an example in proposals, typescript etc. It's basically inherited from the previous version, the purpose was most likely to check for `[]` (computed key), which isn't necessary now. 

But, it was also a check for an unknown syntax, so I wasn't sure should it stay or not. 

Anyway, I completely agree that the purpose of this line is not clear to a reader, and it's better to do something about it. Should I remove the check, or add a comment?

Comment (mdjermanovic) [reply lib/rules/dot-location.js]: I've added the comment.

If it would be better, I can remove the whole conditional, too.

Comment (kaicataldo) [reply lib/rules/dot-location.js]: Unless we can find a test case where this guard is necessary, I’d be more inclined to remove it for future maintainers’ sake.

**Comment by mdjermanovic** [comment]
I'll be away for two weeks from next Tuesday. If the `isNotDotToken` is a blocking issue I could remove that conditional now, to not wait that long. In any case, please don't close the PR if I'm not responding in next couple of weeks :)

**Comment by kaicataldo** [comment]
My vote would be to remove it, but I also don’t want to hold up landing this. If you can remove it, that sounds good to me! Otherwise, I’d be fine with merging this and revisiting that. Thanks for working on this!

**Comment by mdjermanovic** [comment]
It's removed now. 

It looks like this conditional (in the form: `if (dot.type === "Punctuator" && dot.value === "."`) was indeed added to check computed properties in 45cda23 (PR #2506 which also fixed an unrelated or semi-related #2504).

I didn't remove `isDotToken()` and `isNotDotToken()` functions from `ast_utils`. They were added in the first commit, both are unused now but they have their own test cases and might be useful for something else in the future.

I've also added more test cases with computed properties.
