### PR TITLE
Fix: `no-shadow` allows shadowing in the TDZ (fixes #2568)

### LINKED ISSUE #2568: no-shadow: shadowing in the TDZ should be allowed
Hi,

adding the following spec to ```tests/lib/rules/no-shadow.js``` among the valid rules:

```
{ code: "{ let x = 1; } let x = 2;", ecmaFeatures: {blockBindings: true} }
```
it fails with the error ```x is already declared in the upper scope.``` at ```line 1```, ```column 6```, which is where the ```x``` inside the block is declared.

Due to TDZ, the ```x``` in the outer scope cannot be accessed until its ```let``` declaration statement is evaluated, so we *might* allow shadowing in this case.

Thank you a lot,
Francesco

**edit:** I've documented myself a bit better about TDZ and fixed the bug report accordingly.

### PR DESCRIPTION
**Pull request by mysticatea**
I changed `no-shadow` rule to allowing shadowing in the TDZ.
But, if there are function/class scopes between the two variables, it's excepted.

### CODE REVIEW

**Comment by mysticatea** [comment]
I implemented that it doesn't allow shadowing if there are function/class scopes between the two variables.  Because the inner scope can be executed after the variable of the outer scope was declared.

But I consider, even if there were function/class scopes between the two variables, to allow shadowing may be better.

e.g. `xs = xs.filter(x => x != null); let x = xs[0];`

I want advice.

File: tests/lib/rules/no-shadow.js [hunk 1]
```diff
@@ -91,6 +93,16 @@ eslintTester.addRuleTest("lib/rules/no-shadow", {
             errors: [{ message: "x is already declared in the upper scope.", type: "Identifier"}]
         },
         {
+            code: "{ let x = 2; } var x = 1;",
```
Comment (xjamundx) [inline tests/lib/rules/no-shadow.js]: This seems valid, though a bit tricky :)

File: tests/lib/rules/no-shadow.js [hunk 2]
```diff
@@ -91,6 +93,16 @@ eslintTester.addRuleTest("lib/rules/no-shadow", {
...
+            ecmaFeatures: {blockBindings: true},
+            errors: [{ message: "x is already declared in the upper scope.", type: "Identifier"}]
+        },
+        {
+            code: "function a() { let x = 2; } let x = 1;",
```
Comment (xjamundx) [inline tests/lib/rules/no-shadow.js]: Does this really ever shadow each other?

Comment (xjamundx) [inline tests/lib/rules/no-shadow.js]: I'd probably say this type of thing is fine, but I'd like feedback from others.

**Comment by xjamundx** [comment]
Generally I'd lean on the side of leniency :)

File: tests/lib/rules/no-shadow.js (hunk 2 above)
Comment (ilyavolodin) [inline tests/lib/rules/no-shadow.js]: This is not shadowing. Block variables are not hoisted, so inside `a` `x` is not yet defined. So this example shouldn't error.

Comment (michaelficarra) [inline tests/lib/rules/no-shadow.js]: It's in the TDZ. That's what this PR is all about.

File: tests/lib/rules/no-shadow.js (hunk 1 above)
Comment (mysticatea) [inline tests/lib/rules/no-shadow.js]: Wow, I had not thought it.
I agree, I also think it's valid.

File: tests/lib/rules/no-shadow.js (hunk 2 above)
Comment (mysticatea) [inline tests/lib/rules/no-shadow.js]: Hm, my first thought is:

```js
function a() { consle.log(x); }
let x = "hello";
a(); // print "hello"
```

so declarations in a function in the TDZ can shadow outer declarations.
But now, I think it's bad usage (`no-use-before-define`?), so I will make this into valid.

**Comment by mysticatea** [comment]
Thank you for many advice!
I'm working in keeping with those.

Now, I have one question.
How should we do this case?

```js
{ let x; }
function x() { }
```

`FunctionDeclaration` defines a function at compile time (statically), not at run time.
This behavior is well known (`no-use-before-define` has `nofunc` option).

**Comment by mysticatea** [comment]
By way of trial, I added an option `inTDZ`.

**Comment by davidaurelio** [comment]
Wouldn’t `"function"` be a better default?

**Comment by mysticatea** [comment]
Yeah, I hovered between `never` and `function`.

Since `nofunc` of `no-use-before-define` is not default, now, I'm considering `never` has better consistency. (in brief, functions aren't hoisted.)

File: lib/rules/no-shadow.js [hunk 3]
```diff
@@ -55,6 +59,35 @@ module.exports = function(context) {
...
+     */
+    function isInTdz(variable, scopeVar) {
+        var outerDef = scopeVar.defs[0];
+        var inner = getNameRange(variable);
+        var outer = getNameRange(scopeVar);
+        return (
+            inner != null &&
+            outer != null &&
+            inner[1] < outer[0] &&
+            // Expects FunctionDeclaration if is {"tdz":"function"}.
```
Comment (mysticatea) [inline lib/rules/no-shadow.js]: Oops, I wanted to say "except", not "expect".

**Comment by davidaurelio** [comment]
iirc function declarations *are* hoisted.

Check http://jsrocks.org/2015/01/temporal-dead-zone-tdz-demystified/ (the last example before “TDZ is everywhere!”).

**Comment by mysticatea** [comment]
Ah, tests failed because #2635.

@davidaurelio Yes, function declarations are hoisted.
But, I wanted to say an existing rule (`no-use-before-define`) treats function declarations as not hoisted by default. (I'm sorry my English is poor.)

For example:

```json
{
    "rules": {
        "no-use-before-define": 2,
        "no-shadow": [2, {"inTDZ": "function"}]
    },
    "ecmaFeatures": {
        "blockBindings": true
    }
}
```

```js
x();
{ let x; }
function x() { }
```

ESLint will report warnings:

```
> eslint test.js --reset

test.js
  1:0  error  x was used before it was defined          no-use-before-define
  2:6  error  x is already declared in the upper scope  no-shadow

✖ 2 problems (2 errors, 0 warnings)
```

`no-use-before-define` says "x is before defined".
`no-shadow` says "x is already declared".

I felt it's strange, so I chose `"never"` as default.
I want to more feedback, and if the result is "`function` is better default", I will fix it.

**Comment by nzakas** [comment]
Are you still working on this?

**Comment by mysticatea** [comment]
If problems are nothing in reviews, my work is only `git rebase`, probably.

**Comment by ilyavolodin** [comment]
LGTM

**Comment by nzakas** [comment]
I'm concerned about the option name - I don't think people generally know what `TDZ` means. Do we need an option at all? Is there a default behavior that makes sense for everyone?

**Comment by mysticatea** [comment]
I agree that `TDZ` is a specialized knowledge.
I thought an other name idea, `"hoist"`.
It's well known that declarations in JavaScript are hoisted.

I thought the least surprise default behavior is `{"hoist": "never"}`. But if developers use this together `no-use-before-define` with `"nofunc"`, they expect functions are hoisted, so `{"hoist": "function"}` is best.
So I think we should write about related options in the documents of `no-shadow` and `no-use-before-define`.

**Comment by nzakas** [comment]
Yeah, hoist is much better. I do think hoist:functions should be the default.

**Comment by mysticatea** [comment]
I fixed the default option.

But I feel strange, "if you use this rule with no option, you should use an option on other rules".

File: lib/rules/no-shadow.js [hunk 4]
```diff
@@ -133,4 +167,13 @@ module.exports = function(context) {
 
 };
 
-module.exports.schema = [];
+module.exports.schema = [
+    {
+        "type": "object",
+        "properties": {
+            "hoist": {
+                "enum": ["all", "function", "never"]
```
Comment (mysticatea) [inline lib/rules/no-shadow.js]: Oops, I forgot to fix here.

**Comment by nzakas** [comment]
I don't think it's a problem - I'm not even sure the warning is necessary.

**Comment by mysticatea** [comment]
Why do you think so?

**Comment by nzakas** [comment]
Because hosting is a fact of life in JS. If you've configured to ignore it, there are probably a lot of other inconsistencies that will pop up.

**Comment by mysticatea** [comment]
I agree hoisting is a part of JS. 
Now I don't have opposite opinions about `no-shadow` rule's behavior, so, probably, I should make an issue about the default behavior of `no-use-before-define` rule.

What should I work to merge this PR?
I should remove "Related" sections from md?

**Comment by nzakas** [comment]
Yeah, let's remove the "related" section for now, and please open a new issue for no - use - before - define.

**Comment by mysticatea** [comment]
I removed the "related" section and rebased to the current master branch.
Thank you for great supports.

**Comment by ilyavolodin** [comment]
LGTM
