### PR TITLE
Fix: object-curly-spacing doesn't know types

### LINKED ISSUE #5537: object-curly-spacing+objectsInObjects thinks `{ a: function () {} }` delimiter is an object.
**What version of ESLint are you using?**

v2.2.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**

I'm using ESLint to parse my source code.

**What did you do? Please include the actual source code causing the issue.**

When evaluating

```js
"object-curly-spacing": [2, "always", {
    "objectsInObjects": false
}]
```

I am being told that my no-op function in an inline object is an "objectInObject".

```js
var a = { noop: function () {} };
```

**What did you expect to happen?**

I expected ESLint to understand the difference between a closing bracket in a function block scope delimiter and a javascript object.

**What actually happened? Please include the actual, raw output from ESLint.**

It assumed the block scope delimiters were part of a javascript object.

### LINKED ISSUE #5538: object-curly-spacing+arraysInObjects thinks `{ a: list[0] }` delimiter is an array.
**What version of ESLint are you using?**

v2.2.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**

I'm using ESLint to parse my source code.

**What did you do? Please include the actual source code causing the issue.**

When evaluating

```js
"object-curly-spacing": [2, "always", {
    "arraysInObjects": false
}]
```

I am being told that my array index operation in an inline object is an "arrayInObject".

```js
var a = { thingInList: list[0] };
```

**What did you expect to happen?**

I expected ESLint to understand the difference between a closing bracket in an array index access operation and a javascript array.

**What actually happened? Please include the actual, raw output from ESLint.**

It assumed the array index access brackets were part of a javascript array.

### PR DESCRIPTION
**Pull request by BYK**
Fixes #5537, fixes #5538.

`object-curly-spacing` was blindly checking the penultimate token for
`objectsInObjects` and `arraysInObjects` options and it was confusing
computed member expressions and function expressions with array and
object expressions respectively. This patch adds a type check for the
penultimate tokens owner node.

### CODE REVIEW

File: lib/rules/object-curly-spacing.js [hunk 1]
```diff
@@ -121,9 +121,10 @@ module.exports = function(context) {
      * @returns {void}
      */
     function validateBraceSpacing(node, first, second, penultimate, last) {
+        var penultimateType = sourceCode.getNodeByRangeIndex(penultimate.start).type;
```
Comment (BYK) [inline lib/rules/object-curly-spacing.js]: This may be expensive so deferring the actual node getting to the very last moment in the boolean expressions below might be a good idea.

Comment (nzakas) [inline lib/rules/object-curly-spacing.js]: Hmmm yeah, could be slow, especially because it will be called a bunch of times. Maybe we can speed up `getNodeByRangeIndex` by caching results?

Comment (BYK) [inline lib/rules/object-curly-spacing.js]: So you're suggesting both my "calculate at the last moment" thing and memoizing `getNodeByRangeIndex` method? Or are you just suggesting caching inside the rule?

File: lib/rules/object-curly-spacing.js [hunk 2]
```diff
@@ -121,9 +121,10 @@ module.exports = function(context) {
...
         var closingCurlyBraceMustBeSpaced =
```
Comment (alberto) [inline lib/rules/object-curly-spacing.js]: If this is expensive, `closingCurlyBraceMustBeSpaced ` calculation could be moved [here](https://github.com/eslint/eslint/pull/5545/files#diff-9da030a8c7c9a4eea24f42982a0391b0L141)

Comment (BYK) [inline lib/rules/object-curly-spacing.js]: That also makes sense. I'll tidy this up a bit, thanks!

**Comment by BYK** [comment]
Updated. I ran `npm run perf` and median perf numbers look slightly better after the patch. Guessing that's thanks to @alberto's suggestion :)

**Comment by btmills** [comment]
LGTM
