### PR TITLE
Fix: ignored-paths for Windows path (fixes #10687)

### LINKED ISSUE #10687: Some tests about .eslintignore file are failing on Windows
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 10.4.0
* **npm Version:** 6.1.0

**What parser (default, Babel-ESLint, etc.) are you using?**
**Please show your full configuration:**

N/A

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

`npm test` on our repo.

**What did you expect to happen?**

Tests are passed.

**What actually happened? Please include the actual, raw output from ESLint.**

```
> npm i; npm t
npm WARN eslint-plugin-es@1.3.1 requires a peer of eslint@>=4.19.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-eslint-plugin@1.4.0 requires a peer of eslint@>=4.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-node@7.0.1 requires a peer of eslint@>=4.19.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

updated 1 package and audited 6116 packages in 12.179s
found 12 vulnerabilities (4 low, 6 moderate, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> eslint@5.2.0 test C:\Users\starc\Documents\GitHub\eslint
> node Makefile.js test

Validating Makefile.js
Validating .eslintrc.js
Validating JSON Files
Validating Markdown Files
Validating JavaScript files
Validating JavaScript test files
Validating rules
Running unit tests

  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬...](node:10708) [ESLINT_LEGACY_ECMAFEATURES] DeprecationWarning: The 'ecmaFeatures' config file property is deprecated, and has no effect. (found in "tests\fixtures\config-file\ecma-features\.eslintrc.yml")
(node:10708) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "tests\fixtures\config-file\experimental-object-rest-spread\basic\.eslintrc.yml")
(node:10708) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "tests\fixtures\config-file\experimental-object-rest-spread\subdir\.eslintrc.yml")
(node:10708) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "tests\fixtures\config-file\experimental-object-rest-spread\extends\common.yml")
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬.]


  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬](node:10708) [DEP0094] DeprecationWarning: assert.fail() with more than one argument is deprecated. Please use assert.strictEqual() instead or only pass a message.
  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]

  18351 passing (1m)
  4 failing

  1) CLIEngine
       executeOnFiles()
         should ignore one-level down node_modules when ignore file has 'node_modules/' in it:

      AssertionError: expected 2 to equal 1
      + expected - actual

      -2
      +1

      at Context.it (tests\lib\cli-engine.js:1107:20)

  2) CLIEngine
       executeOnFiles()
         should ignore all files and throw an error when tests/fixtures/ is in ignore file:
     AssertionError: expected [Function] to throw an error
      at Context.it (tests\lib\cli-engine.js:1124:20)

  3) IgnoredPaths
       initialization
         should load .eslintignore from cwd when explicitly passed:
     AssertionError: expected [ Array(5) ] to include 'sampleignorepattern'
      at Context.it (tests\lib\ignored-paths.js:128:20)

  4) IgnoredPaths
       initialization with ignorePath containing commented lines
         should not include comments in ignore rules:
     AssertionError: expected [ Array(5) ] to include 'this_one_not'
      at Context.it (tests\lib\ignored-paths.js:453:20)



=============================================================================
Writing coverage object [C:\Users\starc\Documents\GitHub\eslint\coverage\coverage.json]
Writing coverage reports at [C:\Users\starc\Documents\GitHub\eslint\coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 99.29% ( 14358/14460 ), 165 ignored
Branches     : 98.26% ( 11051/11247 ), 122 ignored
Functions    : 99.71% ( 2427/2434 ), 28 ignored
Lines        : 99.29% ( 14213/14314 )
================================================================================
C:\Users\starc\Documents\GitHub\eslint\node_modules\shelljs\src\common.js:401
      if (config.fatal) throw e;
                        ^

Error: exec: (node:10708) [ESLINT_LEGACY_ECMAFEATURES] DeprecationWarning: The 'ecmaFeatures' config file property is deprecated, and has
no effect. (found in "tests/fixtures/config-file/ecma-features/.eslintrc.yml")
(node:10708) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "tests/fixtures/config-file/experimental-object-rest-spread/basic/.eslintrc.yml")
(node:10708) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "tests/fixtures/config-file/experimental-object-rest-spread/subdir/.eslintrc.yml")
(node:10708) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "tests/fixtures/config-file/experimental-object-rest-spread/extends/common.yml")



(node:10708) [DEP0094] DeprecationWarning: assert.fail() with more than one argument is deprecated. Please use assert.strictEqual() instead or only pass a message.
=============================================================================
Writing coverage object [C:/Users/starc/Documents/GitHub/eslint/coverage/coverage.json]
Writing coverage reports at [C:/Users/starc/Documents/GitHub/eslint/coverage]
=============================================================================

    at Object.error (C:\Users\starc\Documents\GitHub\eslint\node_modules\shelljs\src\common.js:110:27)
    at execSync (C:\Users\starc\Documents\GitHub\eslint\node_modules\shelljs\src\exec.js:99:12)
    at _exec (C:\Users\starc\Documents\GitHub\eslint\node_modules\shelljs\src\exec.js:202:12)
    at C:\Users\starc\Documents\GitHub\eslint\node_modules\shelljs\src\common.js:335:23
    at Function.target.test (C:\Users\starc\Documents\GitHub\eslint\Makefile.js:602:18)
    at Object.global.target.(anonymous function) [as test] (C:\Users\starc\Documents\GitHub\eslint\node_modules\shelljs\make.js:36:40)
    at C:\Users\starc\Documents\GitHub\eslint\node_modules\shelljs\make.js:48:27
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (C:\Users\starc\Documents\GitHub\eslint\node_modules\shelljs\make.js:46:10)
    at ontimeout (timers.js:427:11)
npm ERR! Test failed.  See above for more details.
```

### PR DESCRIPTION
**Pull request by mysticatea**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Bug fix: fixes #10687 

**What changes did you make? (Give an overview)**

This PR fixes some problems of ignored-paths on Windows.

1. Fixes that the Windows path separator is mixed into patterns.
2. Fixes that it doesn't handle CRLF line separators correctly in `.eslintignore` files.

**Is there anything you'd like reviewers to focus on?**

I'm not sure why Appvoyer didn't find this...

### CODE REVIEW

File: lib/ignored-paths.js [hunk 1]
```diff
@@ -94,7 +94,11 @@ function relativize(globPattern, relativePathToOldBaseDir) {
     const globWithoutPrefix = globPattern.replace(/^!/, "");
 
     if (globWithoutPrefix.startsWith("/")) {
-        return `${prefix}/${relativePathToOldBaseDir}${globWithoutPrefix}`;
+        const relativePathPrefix = (typeof process !== "undefined" && process.platform === "win32")
+            ? relativePathToOldBaseDir.replace(/\\/g, "/")
+            : relativePathToOldBaseDir;
+
+        return `${prefix}/${relativePathPrefix}${globWithoutPrefix}`;
```
Comment (mysticatea) [inline lib/ignored-paths.js]: I found `relativePathToOldBaseDir` can be `../../../foo/bar`, is this a problem?

File: lib/ignored-paths.js [hunk 2]
```diff
@@ -94,7 +94,11 @@ function relativize(globPattern, relativePathToOldBaseDir) {
     const globWithoutPrefix = globPattern.replace(/^!/, "");
 
     if (globWithoutPrefix.startsWith("/")) {
-        return `${prefix}/${relativePathToOldBaseDir}${globWithoutPrefix}`;
+        const relativePathPrefix = (typeof process !== "undefined" && process.platform === "win32")
```
Comment (not-an-aardvark) [inline lib/ignored-paths.js]: Could this be:

```js
const relativePathPrefix = relativePathToOldBaseDir.replace(
    new RegExp(`\\${path.SEP}`, "g"),
    "/"
);
```

That would avoid the need to depend on `process`.

File: lib/ignored-paths.js (hunk 1 above)
Comment (not-an-aardvark) [reply lib/ignored-paths.js]: Hmm, it might be. I had assumed that one of `this.ignoreFileDir` and `this.options.cwd` would be the parent of the other. If `this.ignoreFileDir` and `this.options.cwd` are in different directories, maybe `this.getBaseDir()` should return a common ancestor.

**Comment by mysticatea** [comment]
I updated this PR.

**Comment by mysticatea** [comment]
I added some `debug()`s.

File: lib/ignored-paths.js [hunk 3]
```diff
@@ -229,23 +243,54 @@ class IgnoredPaths {
...
+        if (!this._baseDir) {
+            const a = path.resolve(this.options.cwd);
+            const b = path.resolve(this.ignoreFileDir);
+            let lastSepPos = 0;
+
+            // Set the shorter one (it's the common ancestor if one includes the other).
+            this._baseDir = a.length < b.length ? a : b;
+
+            // Set the common ancestor.
+            for (let i = 0; i < a.length && i < b.length; ++i) {
```
Comment (not-an-aardvark) [inline lib/ignored-paths.js]: Would it work to split on `path.sep` rather than iterating over each character?

```js
const cwd = path.resolve(this.options.cwd);
const ignoreFileDir = path.resolve(this.ignoreFileDir);

if (cwd === ignoreFileDir) {
    this._baseDir = cwd;
} else {
    const cwdParts = cwd.split(path.sep);
    const ignoreFileDirParts = ignoreFileDir.split(path.sep);

    const longerParts = cwdParts.length > ignoreFileDirParts.length
        ? cwdParts
        : ignoreFileDirParts;

    this._baseDir = longerParts.slice(
        0,
        longerParts.findIndex((_, index) => cwdParts[index] !== ignoreFileDirParts[index])
    );
}
```

File: tests/lib/ignored-paths.js [hunk 4]
```diff
@@ -244,6 +244,12 @@ describe("IgnoredPaths", () => {
             assert.strictEqual(ignoredPaths.ignoreFileDir, path.dirname(ignoreFilePath));
         });
 
+        it("should set the common ancestor directory of cwd and ignorePath", () => {
+            const ignoredPaths = new IgnoredPaths({ ignore: true, ignorePath: ignoreFilePath, cwd: path.resolve(ignoreFilePath, "../../../testcwd") });
+
+            assert.strictEqual(ignoredPaths.getBaseDir(), path.resolve(ignoreFilePath, "../../.."));
+        });
+
```
Comment (not-an-aardvark) [inline tests/lib/ignored-paths.js]: Can you add tests for an ignore file with `\r\n`? (Git would convert the linebreaks to `\n` when the repository is cloned, so it would probably be necessary to create the file at runtime.)

Comment (not-an-aardvark) [inline tests/lib/ignored-paths.js]: Can you add tests for `ignoredPaths.contains` when `ignoreFilePath` and `cwd` are siblings? It would be useful to make sure that the default ignore patterns (e.g. `node_modules`) and custom ignore patterns both work.

Comment (not-an-aardvark) [inline tests/lib/ignored-paths.js]: Is it feasible to add a test for when the baseDir is only a windows drive letter?

File: lib/ignored-paths.js (hunk 3 above)
Comment (mysticatea) [reply lib/ignored-paths.js]: Hm. I wrote that code as being careful to use only one traverse on the path strings. Indeed, though it's `O(n)` as is...

File: tests/lib/ignored-paths.js (hunk 4 above)
Comment (mysticatea) [reply tests/lib/ignored-paths.js]: The base directory was only a Windows drive letter on Appvoyer environments.
But I'm not sure if we can write such a test safely or not, because of permissions. On my PC, the base directory has often become the home directory of my login user because the temporary directory for tests is in ` ~\AppData\Local\Temp`.

Comment (mysticatea) [reply tests/lib/ignored-paths.js]: I added it.

Comment (mysticatea) [reply tests/lib/ignored-paths.js]: Probably I added it.
