### PR TITLE
Fix: check assignment property target in camelcase (fixes #13025)

### LINKED ISSUE #13025: [camelcase] false negative in destructuring with assignment
**Tell us about your environment**

* **ESLint Version:** 7.0.0-alpha.2
* **Node Version:** v11.15.0
* **npm Version:** 6.7.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

* [Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgY2FtZWxjYXNlOiBbXCJlcnJvclwiXSAqL1xudmFyIG9iaiA9IHt9O1xuXG5vYmouZm9fbyA9IGQ7XG4oeyBhOiBvYmouZm9fbyB9ID0gb2JqKTtcbihbb2IuZm9fb10gPSBiYXIpO1xuXG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7ImJyb3dzZXIiOmZhbHNlLCJub2RlIjpmYWxzZX19fQ==)

```js
/*eslint camelcase: ["error"] */
var obj = {};

obj.fo_o = d;  // Warning
({ a: obj.fo_o } = {d: d}); // No Warning
([ob.fo_o] = bar); // No Warning
```

**What did you expect to happen?**

I expect 3 warnings.

**What actually happened? Please include the actual, raw output from ESLint.**

One warning

The below cases are not warned

```js
({ a: obj.fo_o } = {d: d}); // No warning
([ob.fo_o] = bar); // No Warning
```

**Are you willing to submit a pull request to fix this bug?**

Yes!

I think the proper behavior should be as belows.

```js
/*eslint camelcase: ["error"] */
obj.fo_o = d; // warning
({ a: obj.fo_o } = bar); // warning
([ob.fo_o] = bar); // warning
```

```js
/*eslint camelcase: ["error", {"ignoreDestructuring": true}] */
obj.fo_o = d; // warning
({ a: obj.fo_o } = bar); // warning
([ob.fo_o] = bar); // warning
```

```js
/*eslint camelcase: ["error", {"properties": "never"}] */
obj.fo_o = d; // No warning
({ a: obj.fo_o } = {d: d}); // No warning
([ob.fo_o] = bar); // No warning
```

### PR DESCRIPTION
**Pull request by yeonjuan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).
- [x] The team has reached consensus on the changes proposed in this pull request. If not, I understand that the evaluation process will begin with this pull request and won't be merged until the team has reached consensus.

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

As mentioned in #13025, I added checking assignment property target in destructuring

#### Is there anything you'd like reviewers to focus on?

This PR, Fixes #13025

### CODE REVIEW

File: lib/rules/camelcase.js [hunk 1]
```diff
@@ -125,6 +125,38 @@ module.exports = {
...
+         *
+         * For examples:
+         *    ({a: b.foo} = c);  // => true for `foo`
+         *    ({a: b[foo]} = c); // => true for `foo`
+         *    ([a.foo] = b);     // => true for `foo`
+         *    ([a[foo]] = b);    // => true for `foo`
+         *    ({...a.foo} = b);  // => true for `foo`
+         *    ({...a[foo]} = b); // => true for `foo`
+         * @param {ASTNode} node An Identifier node to check
+         * @returns {boolean} True if the node is an assignment target property in destructuring.
```
Comment (mdjermanovic) [inline lib/rules/camelcase.js]: I think it should also return `true` for cases such as `[a.foo = 1] = b`, otherwise this would be a false negative:

```js
/* eslint camelcase: ["error", { properties: "always" }] */

[a.b_c = 1] = d;
```

File: lib/rules/camelcase.js [hunk 2]
```diff
@@ -125,6 +125,38 @@ module.exports = {
...
+            ) {
+                const effectiveParent = node.parent.parent;
+
+                return (
+                    effectiveParent &&
+                    effectiveParent.type === "Property" &&
+                    effectiveParent.value === node.parent &&
+                    effectiveParent.parent.type === "ObjectPattern" ||
+                    effectiveParent.type === "ArrayPattern" ||
+                    effectiveParent.type === "RestElement"
```
Comment (mdjermanovic) [inline lib/rules/camelcase.js]: This is same as:

```js
(effectiveParent &&
effectiveParent.type === "Property" &&
effectiveParent.value === node.parent &&
effectiveParent.parent.type === "ObjectPattern") ||
effectiveParent.type === "ArrayPattern" ||
effectiveParent.type === "RestElement"
```

so it will still crash if `effectiveParent` doesn't exist, instead of returning `false`.

I think we can actually just remove `effectiveParent &&`, because `MemberExpression` must have its `parent` node.

**Comment by yeonjuan** [comment]
@mdjermanovic Thanks for the review. I changed it.

**Comment by kaicataldo** [comment]
Thanks for contributing!
