### PR TITLE
Fix: Require semicolon after import/export statements (fixes #2174)

### LINKED ISSUE #2174: Require semicolon after import statements
Semicolons are not enforced after import statements.

Example:

import * as utils from './utils'

should be enforced to have a semicolon:

import * as utils from './utils';

Right now, with the semi rule on in eslint, this does not warn or throw an error.

### PR DESCRIPTION
**Pull request by gyandeeps**
I used all the scenarios from this link: https://github.com/estree/estree/blob/master/es6.md#modules

I have not included all the node type for `import` as all the types got resolved by one only. But for `export` I had to use more than 1.

One scenario I did leave out for `export` was 

```.js
export var foo = 1
```

In the above code, we throw 2 errors. One by `ExportNamedDeclaration` and another by `VariableDeclaration`.

Not sure yet on how to handle this scenario. any suggestions?

### CODE REVIEW

**Comment by nzakas** [comment]
I think it's fine to let VariableDeclaration handle the error.

File: tests/lib/rules/semi.js [hunk 1]
```diff
@@ -43,6 +43,16 @@ eslintTester.addRuleTest("lib/rules/semi", {
         { code: "for (let thing of {}) {\n  console.log(thing);\n}", ecmaFeatures: { forOf: true, blockBindings: true }}
     ],
     invalid: [
+        { code: "import * as utils from './utils'", ecmaFeatures: { modules: true }, errors: [{ message: "Missing semicolon.", type: "ImportDeclaration"}] },
```
Comment (nzakas) [inline tests/lib/rules/semi.js]: Can you also add some invalid tests to be sure we are honoring never?

Also, can you add a few valid tests?

**Comment by gyandeeps** [comment]
@nzakas All the changes made. :+1: 
We should be good to go now.

**Comment by nzakas** [comment]
LGTM. Thanks!
