### PR TITLE
Fix: no-extra-parens ExpressionStatement restricted prods (fixes #4902)

### LINKED ISSUE #4902: no-extra-parens errors for ExpressionStatement restricted productions
Currently, `no-extra-parens` incorrectly reports

```js
(function(){});
```

and

```js
(class{});
```

and

```js
(let[a] = b);
```

as having unnecessary parens, even though they are needed. PR incoming.

**edit:** For more info, see the note here: http://tc39.github.io/ecma262/#prod-ExpressionStatement

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29740963-no-extra-parens-errors-for-expressionstatement-restricted-productions?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F282608&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #4902.

### CODE REVIEW

File: tests/lib/rules/no-extra-parens.js [hunk 1]
```diff
@@ -129,8 +129,14 @@ ruleTester.run("no-extra-parens", rule, {
...
 
+        // ExpressionStatement restricted productions
+        "({});",
+        "(function(){});",
+        "(let[a] = b);",
+        { code: "(function*(){});", parserOptions: { ecmaVersion: 6 } },
+        { code: "(class{});", parserOptions: { ecmaVersion: 6 } },
+
         // special cases
-        "(a + b) * (c + d) == e",
```
Comment (michaelficarra) [inline tests/lib/rules/no-extra-parens.js]: This is only removed because it's not a special case and it's already covered by two separate tests above.

File: tests/lib/rules/no-extra-parens.js [hunk 2]
```diff
@@ -129,8 +129,14 @@ ruleTester.run("no-extra-parens", rule, {
         "[a, b]",
         "!{a: 0, b: 1}",
 
+        // ExpressionStatement restricted productions
+        "({});",
+        "(function(){});",
+        "(let[a] = b);",
```
Comment (michaelficarra) [inline tests/lib/rules/no-extra-parens.js]: I couldn't add this same test under ES6 mode because of this outstanding espree issue: https://github.com/eslint/espree/issues/149

File: lib/rules/no-extra-parens.js [hunk 3]
```diff
@@ -348,25 +348,21 @@ module.exports = function(context) {
...
-                        firstToken.value !== "{" ||
-                        node.expression.type === "ObjectExpression"
-                    ) &&
-                    // For such as `(function(){}.foo.bar)`
+                firstTokens = context.getFirstTokens(node.expression, 2);
+                firstToken = firstTokens[0];
+                secondToken = firstTokens[1];
+
+                if (
+                    !firstToken ||
```
Comment (michaelficarra) [inline lib/rules/no-extra-parens.js]: I don't love using a falsiness test here, but eslint yelled at me for using `== null`, and I'm not about to try to figure out whether I should check for `undefined` or `null` values in the array returned by this function.

**Comment by ilyavolodin** [comment]
I wonder if this should be marked as breaking due to `(function(){})`?

**Comment by nzakas** [comment]
@ilyavolodin why would that be breaking?

**Comment by michaelficarra** [comment]
It shouldn't be a breaking change. The rule is now making strictly fewer reports.

**Comment by ilyavolodin** [comment]
Before `(function(){})` was marked as invalid, now it's valid. I guess less restrictive change is not breaking.

**Comment by michaelficarra** [comment]
Even the other way around (if it was reporting things that it previously wasn't) would not necessarily be breaking. It's not breaking if the user asked for those errors but was not getting them.

**Comment by nzakas** [comment]
Yeah, this was a bug plain and simple, I don't see any breaking change here.
