### PR TITLE
Breaking: upgrade espree and support new class features (refs #14343)

### LINKED ISSUE #13021: [camelcase] false positive when parsing object pattern with a default value, and using a non-default parser.
**Tell us about your environment**

* **ESLint Version:** 6.7.0
* **Node Version:** 12

**What parser (default, Babel-ESLint, etc.) are you using?**
default, typescript-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  rules: {
    camelcase: ['error', {
      "properties": "never",
      "ignoreDestructuring": true
    }],
  },
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Context: https://github.com/typescript-eslint/typescript-eslint/issues/1686
A user of typescript-eslint received a linting error with the following code, even though it should be covered by the options above.

```js
  const res = {a_b:123}
  const {a_b=0} = res
//       ^^^ Error Identifier 'a_b' is not in camel case
```

This error occurs when parsing with typescript-eslint, and not with the default parser.
Thinking this was a bug in the typescript-eslint parser, I did some digging, and it turns out that the acorn reuses the AST node in two places (i.e. the two `a_b` Identifiers are referentially equal).
https://github.com/acornjs/acorn/issues/928

This causes the parent references to be set incorrectly, as the node's parent will be that of whichever node was traversed last.

Logging this here because:
- the rule doesn't work with the "correct" parent pointers,
- the rule will have to be updated for when the bug in acorn is fixed.

### LINKED ISSUE #14343: support Class Fields
**The version of ESLint you are using.**
n/w

**The problem you want to solve.**
support class fields officially.

**Your take on the correct solution to problem.**

- [ ] parser supports
- [ ] some rules needs to be updated

### LINKED ISSUE #14632: Add Support for Top-level await
Today Top-level await reached Stage 4.
This brings new depth to async modules, and I'm looking forward to seeing it implemented in ESLint in the near future.

- [x] Ecma262 update: https://github.com/tc39/ecma262/pull/2408
- [x] ESTree update: n/a
- [x] Acorn update: https://github.com/acornjs/acorn/pull/1040
- [x] `eslint-visitor-keys` 
- [x] `espree` update: https://github.com/eslint/espree/pull/505
- [x] `eslint-scope` update: 
- [ ] `eslint` update:

### PR DESCRIPTION
**Pull request by mysticatea**
WIP.

Remaining steps:

- [x] update `id-denylist`
- [x] update `id-length`
- [x] update `id-match`
- [x] check if other rules need updates or not.
- [x] check rules again after rest.
- [x] release `espree` and `eslint-scope`.
- [x] update `package.json` with the new versions of `espree` and `eslint-scope`.

---

Refs #14343
Fixes #14632

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Changes an existing rule
[X] Other, please explain: The espree update contains breaking changes.

#### What changes did you make? (Give an overview)

- Upgrade espree. This contains a big breaking change about https://github.com/acornjs/acorn/commit/85f41501c536d9141e50f616f5db6b37e5f0b31b. As a result of this AST structure change, some rules (`camelcase`, `id-denylist`, `id-length`, and `id-match`) are broken. This PR contains the fix of those rules as well. It will fix #13021.
- Support public class fields, private class fields, private class methods/accessors, and static of them. You need `parserOptions: { ecmaVersion: 2022 }` to use the new class features. This PR also change a ton of rules to support the new class features.

| Commit  | Rule                        | Description                                                                                                                      |
| :------ | :-------------------------- | :------------------------------------------------------------------------------------------------------------------------------- |
| 150fd19 | `camelcase`                 | This is a large refactoring. Now the rule understands code semantics better by using variables and references of `eslint-scope`.
| d8a912b | `class-methods-use-this`    | It perceives functions at class field initializers.
| e50a84c | `computed-property-spacing` | It perceives the computed keys of class fields.
| e7e860f | `func-names`                | Functions at field initializers have inferred names. The rule with `"as-needed"` option recognizes that.
| -       | `id-denylist`               | (not yet)
| -       | `id-length`                 | (not yet)
| -       | `id-match`                  | (not yet)
| e5cff29 | `indent`                    | It perceives class fields and indent class fields.
| 553aac0 | `keyword-spacing`           | It's related in three contextual keywords: `get`, `set`, `static`. Tweaks spacing between those and private identifier. And it additinally checks class fields.
| 7da3ed4 | `no-dupe-class-members`     | It perceives public class fields. Duplication of private members is syntax error.
| 4404054, 9d1700d | `no-eval`          | It perceives that `this.eval()` at class field initializers is not eval. The `ast-utils` change in 7ccd811 and 8009406 is related.
| 29275bd | `no-extra-semi`             | It perceives empty class elements preceded by class fields.
| 7ccd811, 8009406 | `no-invalid-this`  | It perceives that `this` in class field initializers is valid.
| 160013d | `no-multi-assign`           | It perceives assignments at class field initializers.
| 06c676c | `no-self-assign`            | It perceives private member accesses.
| 9a494a2 | `no-undef-init`             | It perceives unnecessary `undefined` at class field initializers.
| 4098d55 | `no-underscore-dangle`      | It perceives underscore in private identifiers.
| 40492d3 | `no-unreachable`            | It perceives that class fields are unreachable in rare cases. See also [this comment](https://github.com/eslint/eslint/commit/40492d396437f69b4a02333e80cb68e92d0a8ddf#diff-7951b939b188489129312130dbc19104e2f88db5f2a2a3c0523bd2af48a0eab6R323-R329).
| ef87576 | `no-useless-computed-key`   | It perceives the computed keys of class fields.
| b320bbd | `operator-linebreak`        | It perceives `=` of class field initializers.
| 6fffdc6 | `prefer-exponentiation-operator` | It perceives private identifier and doesn't confused with that. This upgrades `eslint-utils`.
| 803b06a | `quotes`                    | It perceives class fields.
| 7b89143 | `semi-spacing`              | It perceives `;` of class fields.
| b50db18 | `semi-style`                | It perceives `;` of class fields.
| 560e0cf | `semi`                      | It perceives `;` of class fields. Some cases are affected by `beforeStatementContinuationChars` option.
| 04e1ace | `space-infix-ops`           | It perceives `=` of class field initializers.

And this PR adds some tests to a ton of rules.

#### Is there anything you'd like reviewers to focus on?

- Please check if there are more rules that need to be fixed for class fields.
- More tests?
- Are there wrong fixes by misunderstandings of the spec?
- There are rules that generate new errors for class fields. Is that good?
- A large refactoring exists for `camelcase`, `id-denylist`, `id-length`, and `id-match`. Is this good or not?

### CODE REVIEW

**Comment by samarmohan** [comment]
Wouldn’t it be easier for reviewers if you broke this up into multiple prs? This one pr does a lot.

**Comment by rdotg** [comment]
Keep up the good work @mysticatea very excited for this 🙌

**Comment by mdjermanovic** [comment]
@mysticatea do we also plan to update code path analysis, or shall we leave it as is?

For example:

```js
a = 1;

class A {
  foo = a++;
}

b = a;
```

`a++` is in the same code path (and same code segment) as `a = 1` and `b = a`, but it isn't really executed between them.

Non-static `PropertyDefinition` (or at least `PropertyDefinition#value`) is logically a separate code path?

**Comment by mdjermanovic** [comment]
Rules that use `scope1.variableScope === scope2.variableScope` logic:

```js
/* eslint no-use-before-define: ["error", { "variables": false }] */

class A {
    foo = x; // false positive?
}

const x = 1;
```

```js
/* eslint require-atomic-updates: error */

async () => {
    let i;

    foo(class { x = i++ });

    i = i + await bar(); // false negative?
}
```

Less sure about this one, since formally it isn't a function so maybe we could add an option later:

```js
/* eslint no-loop-func: error */

for (var i = 0; i < 10; i++) {
    foo[i] = class {
        x = i; // false negative?
    }
}
```

File: lib/rules/func-names.js [hunk 1]
```diff
@@ -118,6 +118,7 @@ module.exports = {
             return isObjectOrClassMethod(node) ||
                 (parent.type === "VariableDeclarator" && parent.id.type === "Identifier" && parent.init === node) ||
                 (parent.type === "Property" && parent.value === node) ||
+                (parent.type === "PropertyDefinition" && parent.value === node) ||
```
[the remark this answers is not in the document]
Comment (mdjermanovic) [reply lib/rules/func-names.js:121]: It's `"a"` in the latest Firefox, so this is most likely a Chrome bug.

**Comment by mdjermanovic** [comment]
`semi` false positive:

```js
/* eslint semi: ["error", "never"] */

class A {
    a = b; // syntax error without `;`
    *c(){}
}

```

**Comment by mdjermanovic** [comment]
`dot-notation` false positive:

```js
/* eslint dot-notation: ["error", { allowKeywords: false }] */

class C {
    #in;
    foo() {
        this.#in; // autofixed to `this["in"]`
    }
}
```

File: lib/rules/class-methods-use-this.js [hunk 2]
```diff
@@ -118,6 +126,8 @@ module.exports = {
             "FunctionDeclaration:exit": exitFunction,
             FunctionExpression: enterFunction,
             "FunctionExpression:exit": exitFunction,
+            "PropertyDefinition > ArrowFunctionExpression.value": enterFunction,
+            "PropertyDefinition > ArrowFunctionExpression.value:exit": exitFunction,
```
Comment (mdjermanovic) [inline lib/rules/class-methods-use-this.js:130]: Should we put this behind an option, since this isn't a class method by definition?

File: lib/rules/no-undef-init.js [hunk 3]
```diff
@@ -34,37 +34,88 @@ module.exports = {
...
+                    throw new Error("unreachable");
+            }
+        }
+
         return {
 
-            VariableDeclarator(node) {
-                const name = sourceCode.getText(node.id),
-                    init = node.init && node.init.name,
+            "VariableDeclarator, PropertyDefinition"(node) {
```
Comment (mdjermanovic) [inline lib/rules/no-undef-init.js:87]: I think `PropertyDefinition` should be behind an option (or a separate rule?), the docs for this rule says that it checks variable declarations.

File: lib/rules/no-useless-computed-key.js [hunk 4]
```diff
@@ -97,6 +97,7 @@ module.exports = {
 
         return {
             Property: check,
+            PropertyDefinition: enforceForClassMembers ? check : lodash.noop,
```
Comment (mdjermanovic) [inline lib/rules/no-useless-computed-key.js:100]: We should add something like `|| node.type === "PropertyDefinition"` on line 64:

```js
/* eslint no-useless-computed-key: ["error", { enforceForClassMembers: true }] */

class C {
    ["constructor"]; // false positive
    static ["prototype"]; // false positive
    ["__proto__"]; // false negative
}
```

(also, `lodash` has been removed in the meantime)

**Comment by mdjermanovic** [comment]
In `class-methods-use-this`, `"exceptMethods": ["a"]` allows both `a` and `#a`:

```js
/* eslint class-methods-use-this: ["error", { exceptMethods: ["a"] }] */

class C {
    a() {} // ok
    #a() {} // ok
}
```

Does it make sense, or should `#a()` be allowed only by `"#a"`?

**Comment by mdjermanovic** [comment]
`no-extra-parens`:

```js
/* eslint no-extra-parens: ["error"] */

class C {
  [(a)]; // false negative
  b = (c + d); // false negative
}
```

**Comment by mdjermanovic** [comment]
`no-dupe-class-members` reports instance field and prototype method with the same name as duplicates, but that's a bit different from all other combinations where one definition basically overwrites the other. In this case, both are applied, and someone could write something like this:

```js
class C {
    a = this.a.bind(this);
    a() {
        // uses `this`
    }
}
```

Thoughts?

**Comment by mysticatea** [comment]
I'm sorry for my inactive while a time. I'm rebooting...

**Comment by mysticatea** [comment]
> @mysticatea do we also plan to update code path analysis, or shall we leave it as is?
> 
> For example:
> 
> ```js
> a = 1;
> 
> class A {
>   foo = a++;
> }
> 
> b = a;
> ```
> 
> `a++` is in the same code path (and same code segment) as `a = 1` and `b = a`, but it isn't really executed between them.
> 
> Non-static `PropertyDefinition` (or at least `PropertyDefinition#value`) is logically a separate code path?

Oh. I had forgotten about code path analysis.
Yes, by the spec, class field initializers are implicit functions. The initializers define implicit functions and it's called from class instance instantiation process (by the way, the implicit functions define `arguments` local variable, but the use of `arguments` in class field initializers is a syntax error). Therefore, it should separate code paths and create scope.

File: lib/rules/func-names.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (mysticatea) [reply lib/rules/func-names.js:121]: In [10.2.1.3 Runtime Semantics: EvaluateBody](https://tc39.es/ecma262/#sec-runtime-semantics-evaluatebody) of class field initializers, if the initializer value is an anonymous function, the evaluation gives the field name to the anonymous function.

[the remark this answers is not in the document]
Comment (mysticatea) [reply lib/rules/func-names.js:121]: The class field name is `the result of evaluating ClassElementName` in [https://tc39.es/ecma262/#sec-runtime-semantics-classfielddefinitionevaluation](https://tc39.es/ecma262/#sec-runtime-semantics-classfielddefinitionevaluation). It means evaluating computed properties ([13.2.5.4 Runtime Semantics: Evaluation](https://tc39.es/ecma262/#sec-object-initializer-runtime-semantics-evaluation)).

**Comment by mdjermanovic** [comment]
Some more `semi` false positives:

```js
/* eslint semi: ["error", "never"] */

class C {
    get; // false positive
    set;  // false positive
    static; // false positive

    foo() {}
}
```

`async` is ok because of [`[no LineTerminator here]`](https://tc39.es/ecma262/#prod-AsyncMethod)

We could maybe also consider checking these in `no-expected-multiline`, in the future.

**Comment by mdjermanovic** [comment]
`prefer-destructuring` false positive:

```js
/* eslint prefer-destructuring: [
    "error",
    { "object": true },
    { "enforceForRenamedProperties": true }
]*/

class C {
    #x;
    foo() {
        const bar = this.#x; // false positive
    }
}
```

`{ #x: bar }` is not a valid pattern.

File: lib/rules/no-unreachable.js [hunk 5]
```diff
@@ -212,6 +223,39 @@ module.exports = {
...
+            },
+            "ClassDeclaration, ClassExpression:exit"(node) {
+                const { hasConstructor, hasSuperCall } = classInfo;
+                const hasExtends = Boolean(node.superClass);
+
+                classInfo = classInfo.upper;
+
+                if (hasConstructor && hasExtends && !hasSuperCall) {
+                    for (const element of node.body.body) {
+                        if (element.type === "PropertyDefinition") {
```
Comment (mdjermanovic) [inline lib/rules/no-unreachable.js:244]:
```suggestion
                        if (element.type === "PropertyDefinition" && !element.static) {
```

```js
class B extends A {
    constructor() {
        return {};
    }
    static x = 5; // false positive
}
```

**Comment by mdjermanovic** [comment]
A very edge case:

```js
/* eslint no-unreachable: ["error"] */

class B extends A {
    x; // false positive
    constructor() {
        class C extends A {
            [super().y]; // false negative
            constructor() {
                return {};
            }
        }
    }
}
```

(similar behavior with `extends super()`)

**Comment by mdjermanovic** [comment]
`operator-linebreak` checks `]` of computed keys instead of `=`:

```js
/* eslint operator-linebreak: ["error"] */

class C {
    [x
    ] = y; // ']' should be placed at the end of the line  operator-linebreak
}

```

**Comment by mdjermanovic** [comment]
It seems that `lines-between-class-members` doesn't support semicolon-less style:

```js
/*eslint lines-between-class-members: error*/

class A {
    x = y

    ;[z]
}
```

autofixed:

```js
/*eslint lines-between-class-members: error*/

class A {
    x = y

    ;

[z]
}

```

**Comment by mdjermanovic** [comment]
`no-undef-init` (if it will apply to class fields) autofix removes `]` of computed fields, and can produce continuation after `get`, `set`, `static`:

```js
/*eslint no-undef-init: error*/

class A {
    [x] = undefined;
}

class B {
    get = undefined

    foo
}
```

autofixed to:

```js
/*eslint no-undef-init: error*/

class A {
    [x; // syntax error
}

class B {
    get

    foo
} // syntax error
```

**Comment by mdjermanovic** [comment]
We should update the documentation for [func-names](https://eslint.org/docs/rules/func-names) (bolded emphasis is mine):

> `"as-needed"` requires function expressions to have a name, if the name cannot be assigned automatically in an **ES6 environment**

File: lib/rules/keyword-spacing.js [hunk 6]
```diff
@@ -22,7 +22,7 @@ const PREV_TOKEN_M = /^[)\]}>*]$/u;
 const NEXT_TOKEN_M = /^[{*]$/u;
 const TEMPLATE_OPEN_PAREN = /\$\{$/u;
 const TEMPLATE_CLOSE_PAREN = /^\}/u;
-const CHECK_TYPE = /^(?:JSXElement|RegularExpression|String|Template)$/u;
+const CHECK_TYPE = /^(?:JSXElement|RegularExpression|String|Template|PrivateIdentifier)$/u;
```
Comment (mdjermanovic) [inline lib/rules/keyword-spacing.js:25]: `keyword#foo` is ok, but `#fookeyword` isn't:

```js
/* eslint keyword-spacing: ["error", { "before": false  }] */

class C {
    #x;
    foo() {
        for (this.#x of bar); // false positive, autofixed to `this.#xof bar`
    }
}

```

**Comment by mdjermanovic** [comment]
A couple more `semi` false positives:

```js
/* eslint semi: ["error", "never"] */

class A {
    x = foo; // false positive
    in
}

class B {
    x = foo; // false positive
    instanceof 
}
```

File: lib/rules/no-multi-assign.js [hunk 7]
```diff
@@ -45,16 +45,21 @@ module.exports = {
         const options = context.options[0] || {
             ignoreNonDeclaration: false
         };
-        const targetParent = options.ignoreNonDeclaration ? ["VariableDeclarator"] : ["AssignmentExpression", "VariableDeclarator"];
+        const selectors = [
+            "VariableDeclarator > AssignmentExpression.init",
+            "PropertyDefinition > AssignmentExpression.value"
```
Comment (mdjermanovic) [inline lib/rules/no-multi-assign.js:50]: I think it makes sense that `"ignoreNonDeclaration": true` does not ignore initializing class fields, but we should probably update the docs.

Current:

> `"ignoreNonDeclaration"`: When set to `true`, the rule allows chains that don't include initializing a variable in a declaration. Default is `false`.

Updated:

> `"ignoreNonDeclaration"`: When set to `true`, the rule allows chains that don't include initializing a variable in a declaration or initializing a class field. Default is `false`.

and it would be good to a class field example in "Examples of incorrect code for the `{ "ignoreNonDeclaration": true }` option".

File: lib/rules/no-useless-computed-key.js (hunk 4 above)
Comment (mdjermanovic) [reply lib/rules/no-useless-computed-key.js:100]: `static ["constructor"]` is also false positive (produces parsing error instead of a runtime error in a maybe-unused code).

For some reason, "constructor" is allowed as the name of a static method, but not as the name of a static field.

> ClassElement : static MethodDefinition
> * It is a Syntax Error if PropName of MethodDefinition is "prototype".
>
> ClassElement : static FieldDefinition ;
> * It is a Syntax Error if PropName of FieldDefinition is "prototype" or "constructor".

**Comment by mdjermanovic** [comment]
`func-name-matching`:

```js
/* eslint func-name-matching: ["error"] */

class C {
    constructor() {
        this.x = function foo() {}; // this is reported
    }

    x = function foo() {}; // this isn't, false negative?
}
```

I'm not sure if the same should apply to private fields too. An anonymous function would infer `"#x"`, not `"x"`. Since the function's `id.name` cannot match `#x`, private identifiers should be ignored?

Also, the rule has a bug now - it assumes that `astUtils.getStaticPropertyName()` must return a string for a non-computed member access:

```js
/* eslint func-name-matching: ["error"] */

class C {
    #x;
    constructor() {
        this.#x = function foo() {}; // TypeError: Cannot read property 'length' of null at isIdentifierNameES5
    }
}
```

**Comment by mdjermanovic** [comment]
`complexity` rule - when a function being checked has a class definition inside, code in the methods doesn't contribute to complexity of that function, so code in instance field initializers most likely shouldn't as well:

```js
/* eslint complexity: ["error", 3] */

function checkme() { // 1
    a || b; // 2

    class C {
        x = a || b; // 3
        y = a || b; // 4
    }
}

// 4:1  error  Function 'checkme' has a complexity of 4. Maximum allowed is 3  complexity
```

Code in static class field initializers arguably shouldn't count too, although they're executed right after the definition, similar to how code in IIFEs doesn't contribute to the enclosing function's complexity.

**Comment by mdjermanovic** [comment]
`class-methods-use-this` false negative:

```js
/* eslint class-methods-use-this: ["error"] */

class C {
    doesNotUseThis() { // false negative
        return class { foo = this };
    }
}

```

**Comment by nzakas** [comment]
Both Espree and eslint-scope have been released.

**Comment by nzakas** [comment]
I updated eslint-scope and Espree, and fixed a text that relied on `lib/scope-manager` to exist.

This still has some failing tests, but we can at least start looking at the rules.

**Comment by nzakas** [comment]
Oh, I also rebased and fixed the merge conflicts. :)

**Comment by mdjermanovic** [comment]
> * A large refactoring exists for `camelcase`, `id-denylist`, `id-length`, and `id-match`. Is this good or not?

`camelcase` LGTM, aside from maybe https://github.com/eslint/eslint/pull/14591#discussion_r676212379. A small downside is that it might stop reporting identifiers in unknown syntax (e.g., typescript enums), but I think that shouldn't be a concern.

**Comment by nzakas** [comment]
Working on fixing the failing tests. They're all based on the shorthand object properties due to the change in the way that Acorn represents them (one unique node for name and value instead of sharing the same node)

**Comment by nzakas** [comment]
I updated `id-denylist` to check class fields. Please let me know any feedback on that.

**Note:** I did not update `id-blacklist`, which is deprecated in favor of `id-denylist`.

@mdjermanovic if you think there are existing bugs in rules, can you open separate issues for those? I'd like to keep this PR focused on just changes needed to address class fields.

**Comment by mdjermanovic** [comment]
> I updated `id-denylist` to check class fields. Please let me know any feedback on that.

It makes sense to check private identifiers in `id-denylist`.

All changes in `id-denylist` LGTM, with two notes:

* [`&& !isShorthandPropertyDefinition(node)`](https://github.com/eslint/eslint/blob/a8dad97da91140b02b6887245aa6b204843534cf/lib/rules/id-denylist.js#L194) doesn't make sense now and should be removed. `function isShorthandPropertyDefinition` can be removed.
* [`parent.value !== node &&`](https://github.com/eslint/eslint/blob/a8dad97da91140b02b6887245aa6b204843534cf/lib/rules/id-denylist.js#L87) doesn't make sense now and should be removed. `function isRenamedInDestructuring` should be renamed to, e.g., `function isPropertyNameInDestructuring`.

**Comment by nzakas** [comment]
@mdjermanovic wow, nice eye! I've made those fixes.

**Comment by nzakas** [comment]
I updated `id-length` to also check class fields.

I updated `id-match` with a new option, `classFields`, that opts-in to checking class fields. By default, this rule doesn't check object properties, so I also thought it shouldn't check class fields, but there should be a way to opt-in.

I think this should finalize this PR, so I'll mark it ready for review. We can discover whether or not other rules need to be updated as we test out the prereleases.

**Comment by mdjermanovic** [comment]
A remaining task is to update code path analysis to create separate code paths for class field initializers (https://github.com/eslint/eslint/pull/14591#issuecomment-856955385 and https://github.com/eslint/eslint/pull/14591#issuecomment-870937972). This is a change in the core that affects rules (built-in and custom), so it might be good to implement it before beta release?
 
Aside from that, I left comments for about 15-20 rules. Some are obvious bugs, some need discussion. I can open issues after we merge this PR, so that they could be worked on in parallel.

**Comment by nzakas** [comment]
I think code path analysis may not make it. @mysticatea is the only one who really understands it. I can take a swing at it but unsure how far I can actually get.

Yes, let’s deal with other rule changes separately. There is always a long tail of rule changes to support new syntax, and that’s part of what the beta period is for.

**Review by nzakas — APPROVED** [review]

File: lib/rules/camelcase.js [hunk 8]
```diff
@@ -204,122 +180,214 @@ module.exports = {
...
+                         */
+                        reportReferenceId(reference.identifier);
+                    }
+                }
 
-                    // Report AssignmentExpressions only if they are the left side of the assignment
-                    } else if (effectiveParent.type === "AssignmentExpression" && nameIsUnderscored && (effectiveParent.right.type !== "MemberExpression" || effectiveParent.left.type === "MemberExpression" && effectiveParent.left.property.name === node.name)) {
-                        report(node);
+                // Undefined globals.
+                for (const reference of scope.through) {
```
[the remark this answers is not in the document]
Comment (nzakas) [reply lib/rules/camelcase.js:268]: @mdjermanovic what is the action here? It's not clear from your comment.

[the remark this answers is not in the document]
Comment (mdjermanovic) [reply lib/rules/camelcase.js:268]: In the previous version, the `"ignoreGlobals"` option didn't apply to undefined variables. 

(this isn't related to class fields, but to the overall refactoring of the `camelcase` rule that was done in this PR)

I'll prepare a PR to restore the previous behavior in this regard.

[the remark this answers is not in the document]
Comment (mdjermanovic) [reply lib/rules/camelcase.js:268]: https://github.com/eslint/eslint/pull/14966
